var searchData=
[
  ['d3d12texturedata_5ft_0',['D3D12TextureData_t',['../struct_o_v_r_1_1_open_v_r_1_1_d3_d12_texture_data__t.html',1,'OVR::OpenVR']]],
  ['dataentry_1',['DataEntry',['../class_oculus_1_1_platform_1_1_samples_1_1_simple_platform_sample_1_1_data_entry.html',1,'Oculus::Platform::Samples::SimplePlatformSample']]],
  ['datamodel_2',['DataModel',['../class_oculus_1_1_platform_1_1_data_model.html',1,'Oculus::Platform']]],
  ['datamodifier_3',['DataModifier',['../class_oculus_1_1_interaction_1_1_input_1_1_data_modifier.html',1,'Oculus::Interaction::Input']]],
  ['datamodifier_3c_20bodydataasset_20_3e_4',['DataModifier&lt; BodyDataAsset &gt;',['../class_oculus_1_1_interaction_1_1_input_1_1_data_modifier.html',1,'Oculus::Interaction::Input']]],
  ['datamodifier_3c_20controllerdataasset_20_3e_5',['DataModifier&lt; ControllerDataAsset &gt;',['../class_oculus_1_1_interaction_1_1_input_1_1_data_modifier.html',1,'Oculus::Interaction::Input']]],
  ['datamodifier_3c_20handdataasset_20_3e_6',['DataModifier&lt; HandDataAsset &gt;',['../class_oculus_1_1_interaction_1_1_input_1_1_data_modifier.html',1,'Oculus::Interaction::Input']]],
  ['datamodifier_3c_20hmddataasset_20_3e_7',['DataModifier&lt; HmdDataAsset &gt;',['../class_oculus_1_1_interaction_1_1_input_1_1_data_modifier.html',1,'Oculus::Interaction::Input']]],
  ['datasource_8',['DataSource',['../class_oculus_1_1_interaction_1_1_input_1_1_data_source.html',1,'Oculus::Interaction::Input']]],
  ['datasource_3c_20bodydataasset_20_3e_9',['DataSource&lt; BodyDataAsset &gt;',['../class_oculus_1_1_interaction_1_1_input_1_1_data_source.html',1,'Oculus::Interaction::Input']]],
  ['datasource_3c_20controllerdataasset_20_3e_10',['DataSource&lt; ControllerDataAsset &gt;',['../class_oculus_1_1_interaction_1_1_input_1_1_data_source.html',1,'Oculus::Interaction::Input']]],
  ['datasource_3c_20handdataasset_20_3e_11',['DataSource&lt; HandDataAsset &gt;',['../class_oculus_1_1_interaction_1_1_input_1_1_data_source.html',1,'Oculus::Interaction::Input']]],
  ['datasource_3c_20hmddataasset_20_3e_12',['DataSource&lt; HmdDataAsset &gt;',['../class_oculus_1_1_interaction_1_1_input_1_1_data_source.html',1,'Oculus::Interaction::Input']]],
  ['datetimeconverter_13',['DateTimeConverter',['../class_meta_1_1_wit_ai_1_1_json_1_1_date_time_converter.html',1,'Meta::WitAi::Json']]],
  ['datetimeutility_14',['DateTimeUtility',['../class_oculus_1_1_voice_1_1_core_1_1_utilities_1_1_date_time_utility.html',1,'Oculus::Voice::Core::Utilities']]],
  ['debuggizmos_15',['DebugGizmos',['../class_oculus_1_1_interaction_1_1_debug_gizmos.html',1,'Oculus::Interaction']]],
  ['debuggizmoseditorfallback_16',['DebugGizmosEditorFallback',['../class_oculus_1_1_interaction_1_1_editor_1_1_generated_1_1_debug_gizmos_editor_fallback.html',1,'Oculus::Interaction::Editor::Generated']]],
  ['debugmodel_17',['debugmodel',['../class_oculus_1_1_interaction_1_1_active_state_group_1_1_debug_model.html',1,'Oculus.Interaction.ActiveStateGroup.DebugModel'],['../class_oculus_1_1_interaction_1_1_active_state_not_1_1_debug_model.html',1,'Oculus.Interaction.ActiveStateNot.DebugModel'],['../class_oculus_1_1_interaction_1_1_active_state_toggle_1_1_debug_model.html',1,'Oculus.Interaction.ActiveStateToggle.DebugModel'],['../class_oculus_1_1_interaction_1_1_pose_detection_1_1_sequence_1_1_debug_model.html',1,'Oculus.Interaction.PoseDetection.Sequence.DebugModel'],['../class_oculus_1_1_interaction_1_1_pose_detection_1_1_sequence_active_state_1_1_debug_model.html',1,'Oculus.Interaction.PoseDetection.SequenceActiveState.DebugModel']]],
  ['debuguibuilder_18',['DebugUIBuilder',['../class_debug_u_i_builder.html',1,'']]],
  ['debuguisample_19',['DebugUISample',['../class_debug_u_i_sample.html',1,'']]],
  ['defaulttokenvalidatorprovider_20',['DefaultTokenValidatorProvider',['../class_meta_1_1_wit_ai_1_1_wit_auth_utility_1_1_default_token_validator_provider.html',1,'Meta::WitAi::WitAuthUtility']]],
  ['deferredpassthroughmeshaddition_21',['DeferredPassthroughMeshAddition',['../struct_o_v_r_passthrough_layer_1_1_deferred_passthrough_mesh_addition.html',1,'OVRPassthroughLayer']]],
  ['deserializablelist_22',['DeserializableList',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['deserializablelist_3c_20achievementdefinition_20_3e_23',['DeserializableList&lt; AchievementDefinition &gt;',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['deserializablelist_3c_20achievementprogress_20_3e_24',['DeserializableList&lt; AchievementProgress &gt;',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['deserializablelist_3c_20applicationinvite_20_3e_25',['DeserializableList&lt; ApplicationInvite &gt;',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['deserializablelist_3c_20assetdetails_20_3e_26',['DeserializableList&lt; AssetDetails &gt;',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['deserializablelist_3c_20blockeduser_20_3e_27',['DeserializableList&lt; BlockedUser &gt;',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['deserializablelist_3c_20challenge_20_3e_28',['DeserializableList&lt; Challenge &gt;',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['deserializablelist_3c_20challengeentry_20_3e_29',['DeserializableList&lt; ChallengeEntry &gt;',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['deserializablelist_3c_20destination_20_3e_30',['DeserializableList&lt; Destination &gt;',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['deserializablelist_3c_20installedapplication_20_3e_31',['DeserializableList&lt; InstalledApplication &gt;',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['deserializablelist_3c_20leaderboard_20_3e_32',['DeserializableList&lt; Leaderboard &gt;',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['deserializablelist_3c_20leaderboardentry_20_3e_33',['DeserializableList&lt; LeaderboardEntry &gt;',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['deserializablelist_3c_20linkedaccount_20_3e_34',['DeserializableList&lt; LinkedAccount &gt;',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['deserializablelist_3c_20netsyncsession_20_3e_35',['DeserializableList&lt; NetSyncSession &gt;',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['deserializablelist_3c_20netsyncvoipattenuationvalue_20_3e_36',['DeserializableList&lt; NetSyncVoipAttenuationValue &gt;',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['deserializablelist_3c_20pid_20_3e_37',['DeserializableList&lt; Pid &gt;',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['deserializablelist_3c_20product_20_3e_38',['DeserializableList&lt; Product &gt;',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['deserializablelist_3c_20purchase_20_3e_39',['DeserializableList&lt; Purchase &gt;',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['deserializablelist_3c_20sdkaccount_20_3e_40',['DeserializableList&lt; SdkAccount &gt;',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['deserializablelist_3c_20user_20_3e_41',['DeserializableList&lt; User &gt;',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['deserializablelist_3c_20usercapability_20_3e_42',['DeserializableList&lt; UserCapability &gt;',['../class_oculus_1_1_platform_1_1_models_1_1_deserializable_list.html',1,'Oculus::Platform::Models']]],
  ['destination_43',['Destination',['../class_oculus_1_1_platform_1_1_models_1_1_destination.html',1,'Oculus::Platform::Models']]],
  ['destinationlist_44',['DestinationList',['../class_oculus_1_1_platform_1_1_models_1_1_destination_list.html',1,'Oculus::Platform::Models']]],
  ['development_45',['Development',['../class_o_v_r_spatial_anchor_1_1_development.html',1,'OVRSpatialAnchor']]],
  ['deviceapplicationintegrity_46',['DeviceApplicationIntegrity',['../class_oculus_1_1_platform_1_1_device_application_integrity.html',1,'Oculus::Platform']]],
  ['dictationactivation_47',['DictationActivation',['../class_meta_1_1_voice_1_1_samples_1_1_dictation_1_1_dictation_activation.html',1,'Meta::Voice::Samples::Dictation']]],
  ['dictationconfiguration_48',['DictationConfiguration',['../class_oculus_1_1_voice_1_1_dictation_1_1_configuration_1_1_dictation_configuration.html',1,'Oculus::Voice::Dictation::Configuration']]],
  ['dictationconfigurationbinding_49',['DictationConfigurationBinding',['../class_oculus_1_1_voice_1_1_dictation_1_1_bindings_1_1_android_1_1_dictation_configuration_binding.html',1,'Oculus::Voice::Dictation::Bindings::Android']]],
  ['dictationeventpropertydrawer_50',['DictationEventPropertyDrawer',['../class_meta_1_1_wit_ai_1_1_dictation_1_1_events_1_1_editor_1_1_dictation_event_property_drawer.html',1,'Meta::WitAi::Dictation::Events::Editor']]],
  ['dictationevents_51',['DictationEvents',['../class_meta_1_1_wit_ai_1_1_dictation_1_1_events_1_1_dictation_events.html',1,'Meta::WitAi::Dictation::Events']]],
  ['dictationlistener_52',['DictationListener',['../interface_oculus_1_1_voice_1_1_dictation_1_1_listeners_1_1_dictation_listener.html',1,'Oculus::Voice::Dictation::Listeners']]],
  ['dictationlistenerbinding_53',['DictationListenerBinding',['../class_oculus_1_1_voice_1_1_dictation_1_1_bindings_1_1_android_1_1_dictation_listener_binding.html',1,'Oculus::Voice::Dictation::Bindings::Android']]],
  ['dictationservice_54',['DictationService',['../class_meta_1_1_wit_ai_1_1_dictation_1_1_dictation_service.html',1,'Meta::WitAi::Dictation']]],
  ['dictationserviceaudioeventreference_55',['DictationServiceAudioEventReference',['../class_meta_1_1_wit_ai_1_1_service_references_1_1_dictation_service_audio_event_reference.html',1,'Meta::WitAi::ServiceReferences']]],
  ['dictationservicereference_56',['DictationServiceReference',['../struct_meta_1_1_wit_ai_1_1_utilities_1_1_dictation_service_reference.html',1,'Meta::WitAi::Utilities']]],
  ['dictationsession_57',['DictationSession',['../class_meta_1_1_wit_ai_1_1_dictation_1_1_data_1_1_dictation_session.html',1,'Meta::WitAi::Dictation::Data']]],
  ['dictationsessionevent_58',['DictationSessionEvent',['../class_meta_1_1_wit_ai_1_1_dictation_1_1_events_1_1_dictation_session_event.html',1,'Meta::WitAi::Dictation::Events']]],
  ['dictionarylist_59',['DictionaryList',['../class_meta_1_1_wit_ai_1_1_utilities_1_1_dictionary_list.html',1,'Meta::WitAi::Utilities']]],
  ['dictionaryscope_60',['DictionaryScope',['../struct_o_v_r_object_pool_1_1_dictionary_scope.html',1,'OVRObjectPool']]],
  ['directorysyncer_61',['DirectorySyncer',['../class_directory_syncer.html',1,'']]],
  ['displayrefreshratechangeddata_62',['DisplayRefreshRateChangedData',['../struct_o_v_r_deserialize_1_1_display_refresh_rate_changed_data.html',1,'OVRDeserialize']]],
  ['distancegrabbable_63',['DistanceGrabbable',['../class_oculus_sample_framework_1_1_distance_grabbable.html',1,'OculusSampleFramework']]],
  ['distancegrabber_64',['DistanceGrabber',['../class_oculus_sample_framework_1_1_distance_grabber.html',1,'OculusSampleFramework']]],
  ['distancegrabbersample_65',['DistanceGrabberSample',['../class_oculus_sample_framework_1_1_distance_grabber_sample.html',1,'OculusSampleFramework']]],
  ['distancegrabinteractable_66',['DistanceGrabInteractable',['../class_oculus_1_1_interaction_1_1_distance_grab_interactable.html',1,'Oculus::Interaction']]],
  ['distancegrabinteractableeditorfallback_67',['DistanceGrabInteractableEditorFallback',['../class_oculus_1_1_interaction_1_1_editor_1_1_generated_1_1_distance_grab_interactable_editor_fallback.html',1,'Oculus::Interaction::Editor::Generated']]],
  ['distancegrabinteractor_68',['DistanceGrabInteractor',['../class_oculus_1_1_interaction_1_1_distance_grab_interactor.html',1,'Oculus::Interaction']]],
  ['distancegrabinteractoreditorfallback_69',['DistanceGrabInteractorEditorFallback',['../class_oculus_1_1_interaction_1_1_editor_1_1_generated_1_1_distance_grab_interactor_editor_fallback.html',1,'Oculus::Interaction::Editor::Generated']]],
  ['distancehandgrabinteractable_70',['DistanceHandGrabInteractable',['../class_oculus_1_1_interaction_1_1_hand_grab_1_1_distance_hand_grab_interactable.html',1,'Oculus::Interaction::HandGrab']]],
  ['distancehandgrabinteractableeditor_71',['DistanceHandGrabInteractableEditor',['../class_oculus_1_1_interaction_1_1_hand_grab_1_1_editor_1_1_distance_hand_grab_interactable_editor.html',1,'Oculus::Interaction::HandGrab::Editor']]],
  ['distancehandgrabinteractableeditorfallback_72',['DistanceHandGrabInteractableEditorFallback',['../class_oculus_1_1_interaction_1_1_hand_grab_1_1_editor_1_1_generated_1_1_distance_hand_grab_interactable_editor_fallback.html',1,'Oculus::Interaction::HandGrab::Editor::Generated']]],
  ['distancehandgrabinteractor_73',['DistanceHandGrabInteractor',['../class_oculus_1_1_interaction_1_1_hand_grab_1_1_distance_hand_grab_interactor.html',1,'Oculus::Interaction::HandGrab']]],
  ['distancehandgrabinteractoreditorfallback_74',['DistanceHandGrabInteractorEditorFallback',['../class_oculus_1_1_interaction_1_1_hand_grab_1_1_editor_1_1_generated_1_1_distance_hand_grab_interactor_editor_fallback.html',1,'Oculus::Interaction::HandGrab::Editor::Generated']]],
  ['distantcandidatecomputer_75',['DistantCandidateComputer',['../class_oculus_1_1_interaction_1_1_distant_candidate_computer.html',1,'Oculus::Interaction']]],
  ['distantcandidatecomputer_3c_20oculus_3a_3ainteraction_3a_3adistancegrabinteractor_2c_20oculus_3a_3ainteraction_3a_3adistancegrabinteractable_20_3e_76',['DistantCandidateComputer&lt; Oculus::Interaction::DistanceGrabInteractor, Oculus::Interaction::DistanceGrabInteractable &gt;',['../class_oculus_1_1_interaction_1_1_distant_candidate_computer.html',1,'Oculus::Interaction']]],
  ['distantcandidatecomputer_3c_20oculus_3a_3ainteraction_3a_3ahandgrab_3a_3adistancehandgrabinteractor_2c_20oculus_3a_3ainteraction_3a_3ahandgrab_3a_3adistancehandgrabinteractable_20_3e_77',['DistantCandidateComputer&lt; Oculus::Interaction::HandGrab::DistanceHandGrabInteractor, Oculus::Interaction::HandGrab::DistanceHandGrabInteractable &gt;',['../class_oculus_1_1_interaction_1_1_distant_candidate_computer.html',1,'Oculus::Interaction']]],
  ['distantinteractionlinerenderervisual_78',['DistantInteractionLineRendererVisual',['../class_oculus_1_1_interaction_1_1_distance_reticles_1_1_distant_interaction_line_renderer_visual.html',1,'Oculus::Interaction::DistanceReticles']]],
  ['distantinteractionlinerenderervisualeditorfallback_79',['DistantInteractionLineRendererVisualEditorFallback',['../class_oculus_1_1_interaction_1_1_distance_reticles_1_1_editor_1_1_generated_1_1_distant_interact9d9931a522fe982d5c4c4dc51b50a2b8.html',1,'Oculus::Interaction::DistanceReticles::Editor::Generated']]],
  ['distantinteractionlinevisual_80',['DistantInteractionLineVisual',['../class_oculus_1_1_interaction_1_1_distance_reticles_1_1_distant_interaction_line_visual.html',1,'Oculus::Interaction::DistanceReticles']]],
  ['distantinteractionpolylinevisual_81',['DistantInteractionPolylineVisual',['../class_oculus_1_1_interaction_1_1_distance_reticles_1_1_distant_interaction_polyline_visual.html',1,'Oculus::Interaction::DistanceReticles']]],
  ['distantinteractionpolylinevisualeditorfallback_82',['DistantInteractionPolylineVisualEditorFallback',['../class_oculus_1_1_interaction_1_1_distance_reticles_1_1_editor_1_1_generated_1_1_distant_interact1ee900f99adfbfa08ed6c702300ba001.html',1,'Oculus::Interaction::DistanceReticles::Editor::Generated']]],
  ['distantinteractiontubevisual_83',['DistantInteractionTubeVisual',['../class_oculus_1_1_interaction_1_1_distance_reticles_1_1_distant_interaction_tube_visual.html',1,'Oculus::Interaction::DistanceReticles']]],
  ['distantinteractiontubevisualeditorfallback_84',['DistantInteractionTubeVisualEditorFallback',['../class_oculus_1_1_interaction_1_1_distance_reticles_1_1_editor_1_1_generated_1_1_distant_interaction_tube_visual_editor_fallback.html',1,'Oculus::Interaction::DistanceReticles::Editor::Generated']]],
  ['distantpointdetector_85',['DistantPointDetector',['../class_oculus_1_1_interaction_1_1_distant_point_detector.html',1,'Oculus::Interaction']]],
  ['distantpointdetectorfrustums_86',['DistantPointDetectorFrustums',['../struct_oculus_1_1_interaction_1_1_distant_point_detector_frustums.html',1,'Oculus::Interaction']]],
  ['distortioncoordinates_5ft_87',['DistortionCoordinates_t',['../struct_o_v_r_1_1_open_v_r_1_1_distortion_coordinates__t.html',1,'OVR::OpenVR']]],
  ['dotgridproperties_88',['DotGridProperties',['../class_oculus_1_1_interaction_1_1_dot_grid_properties.html',1,'Oculus::Interaction']]],
  ['dotgridpropertieseditorfallback_89',['DotGridPropertiesEditorFallback',['../class_oculus_1_1_interaction_1_1_editor_1_1_generated_1_1_dot_grid_properties_editor_fallback.html',1,'Oculus::Interaction::Editor::Generated']]],
  ['dragthresholdsconfig_90',['DragThresholdsConfig',['../class_oculus_1_1_interaction_1_1_poke_interactable_1_1_drag_thresholds_config.html',1,'Oculus::Interaction::PokeInteractable']]],
  ['drawerinspectorcomment_91',['DrawerInspectorComment',['../class_drawer_inspector_comment.html',1,'']]],
  ['drawerinspectornote_92',['DrawerInspectorNote',['../class_drawer_inspector_note.html',1,'']]],
  ['driverdirectmode_5fframetiming_93',['DriverDirectMode_FrameTiming',['../struct_o_v_r_1_1_open_v_r_1_1_driver_direct_mode___frame_timing.html',1,'OVR::OpenVR']]],
  ['dummypointreticle_94',['DummyPointReticle',['../class_oculus_1_1_interaction_1_1_distance_reticles_1_1_distant_interaction_line_visual_1_1_dummy_point_reticle.html',1,'Oculus::Interaction::DistanceReticles::DistantInteractionLineVisual']]],
  ['dynamicentitydataprovider_95',['DynamicEntityDataProvider',['../class_meta_1_1_wit_ai_1_1_data_1_1_entities_1_1_dynamic_entity_data_provider.html',1,'Meta::WitAi::Data::Entities']]],
  ['dynamicentitykeywordregistry_96',['DynamicEntityKeywordRegistry',['../class_meta_1_1_wit_ai_1_1_data_1_1_entities_1_1_dynamic_entity_keyword_registry.html',1,'Meta::WitAi::Data::Entities']]],
  ['dynamicentityprovider_97',['DynamicEntityProvider',['../class_meta_1_1_wit_ai_1_1_data_1_1_entities_1_1_dynamic_entity_provider.html',1,'Meta::WitAi::Data::Entities']]],
  ['dynamicrangeattribute_98',['DynamicRangeAttribute',['../class_meta_1_1_wit_ai_1_1_utilities_1_1_dynamic_range_attribute.html',1,'Meta::WitAi::Utilities']]],
  ['dynamicrangeattributedrawer_99',['DynamicRangeAttributeDrawer',['../class_meta_1_1_wit_ai_1_1_drawers_1_1_dynamic_range_attribute_drawer.html',1,'Meta::WitAi::Drawers']]]
];
