var searchData=
[
  ['faceexpressionsenumerator_0',['FaceExpressionsEnumerator',['../struct_o_v_r_face_expressions_1_1_face_expressions_enumerator.html',1,'OVRFaceExpressions']]],
  ['faceexpressionstatus_1',['FaceExpressionStatus',['../struct_o_v_r_plugin_1_1_face_expression_status.html',1,'OVRPlugin']]],
  ['faceexpressionstatusinternal_2',['FaceExpressionStatusInternal',['../struct_o_v_r_plugin_1_1_face_expression_status_internal.html',1,'OVRPlugin']]],
  ['facestate_3',['FaceState',['../struct_o_v_r_plugin_1_1_face_state.html',1,'OVRPlugin']]],
  ['facestate2internal_4',['FaceState2Internal',['../struct_o_v_r_plugin_1_1_face_state2_internal.html',1,'OVRPlugin']]],
  ['facestateinternal_5',['FaceStateInternal',['../struct_o_v_r_plugin_1_1_face_state_internal.html',1,'OVRPlugin']]],
  ['fadetextafteractive_6',['FadeTextAfterActive',['../class_oculus_1_1_interaction_1_1_samples_1_1_fade_text_after_active.html',1,'Oculus::Interaction::Samples']]],
  ['fastlist_7',['FastList',['../class_fast_list.html',1,'']]],
  ['fastlist_3c_20ovr_3a_3aaudiomanagerinspector_3a_3aitemrect_20_3e_8',['FastList&lt; OVR::AudioManagerInspector::ItemRect &gt;',['../class_fast_list.html',1,'']]],
  ['fastlist_3c_20ovr_3a_3asoundemitter_20_3e_9',['FastList&lt; OVR::SoundEmitter &gt;',['../class_fast_list.html',1,'']]],
  ['fastlist_3c_20ovr_3a_3asoundgroup_20_3e_10',['FastList&lt; OVR::SoundGroup &gt;',['../class_fast_list.html',1,'']]],
  ['featureconfig_11',['FeatureConfig',['../class_oculus_1_1_interaction_1_1_pose_detection_1_1_editor_1_1_model_1_1_feature_config.html',1,'Oculus::Interaction::PoseDetection::Editor::Model']]],
  ['featureconfigbase_12',['FeatureConfigBase',['../class_oculus_1_1_interaction_1_1_pose_detection_1_1_feature_config_base.html',1,'Oculus::Interaction::PoseDetection']]],
  ['featureconfigbase_3c_20fingerfeature_20_3e_13',['FeatureConfigBase&lt; FingerFeature &gt;',['../class_oculus_1_1_interaction_1_1_pose_detection_1_1_feature_config_base.html',1,'Oculus::Interaction::PoseDetection']]],
  ['featureconfigbase_3c_20handjointid_20_3e_14',['FeatureConfigBase&lt; HandJointId &gt;',['../class_oculus_1_1_interaction_1_1_pose_detection_1_1_feature_config_base.html',1,'Oculus::Interaction::PoseDetection']]],
  ['featureconfigbase_3c_20transformfeature_20_3e_15',['FeatureConfigBase&lt; TransformFeature &gt;',['../class_oculus_1_1_interaction_1_1_pose_detection_1_1_feature_config_base.html',1,'Oculus::Interaction::PoseDetection']]],
  ['featureconfigbuilder_16',['FeatureConfigBuilder',['../class_oculus_1_1_interaction_1_1_pose_detection_1_1_feature_config_builder.html',1,'Oculus::Interaction::PoseDetection']]],
  ['featureconfiglist_17',['FeatureConfigList',['../class_oculus_1_1_interaction_1_1_pose_detection_1_1_editor_1_1_model_1_1_feature_config_list.html',1,'Oculus::Interaction::PoseDetection::Editor::Model']]],
  ['featuredescription_18',['FeatureDescription',['../class_oculus_1_1_interaction_1_1_pose_detection_1_1_feature_description.html',1,'Oculus::Interaction::PoseDetection']]],
  ['featurelistpropertydrawer_19',['FeatureListPropertyDrawer',['../class_oculus_1_1_interaction_1_1_pose_detection_1_1_editor_1_1_feature_list_property_drawer.html',1,'Oculus::Interaction::PoseDetection::Editor']]],
  ['featurestatedescription_20',['FeatureStateDescription',['../class_oculus_1_1_interaction_1_1_pose_detection_1_1_feature_state_description.html',1,'Oculus::Interaction::PoseDetection']]],
  ['featurestateprovider_21',['FeatureStateProvider',['../class_oculus_1_1_interaction_1_1_pose_detection_1_1_feature_state_provider.html',1,'Oculus::Interaction::PoseDetection']]],
  ['featurestateprovider_3c_20fingerfeature_2c_20string_20_3e_22',['FeatureStateProvider&lt; FingerFeature, string &gt;',['../class_oculus_1_1_interaction_1_1_pose_detection_1_1_feature_state_provider.html',1,'Oculus::Interaction::PoseDetection']]],
  ['featurestateprovider_3c_20transformfeature_2c_20string_20_3e_23',['FeatureStateProvider&lt; TransformFeature, string &gt;',['../class_oculus_1_1_interaction_1_1_pose_detection_1_1_feature_state_provider.html',1,'Oculus::Interaction::PoseDetection']]],
  ['featurestatesnapshot_24',['FeatureStateSnapshot',['../struct_oculus_1_1_interaction_1_1_pose_detection_1_1_feature_state_provider_1_1_feature_state_snapshot.html',1,'Oculus::Interaction::PoseDetection::FeatureStateProvider']]],
  ['featurestatethresholdmodel_25',['FeatureStateThresholdModel',['../class_oculus_1_1_interaction_1_1_pose_detection_1_1_editor_1_1_feature_state_thresholds_editor_1a9c7f7bf5ba8b07ccc6df61a1d3f3ff5.html',1,'Oculus::Interaction::PoseDetection::Editor::FeatureStateThresholdsEditor']]],
  ['featurestatethresholdseditor_26',['FeatureStateThresholdsEditor',['../class_oculus_1_1_interaction_1_1_pose_detection_1_1_editor_1_1_feature_state_thresholds_editor.html',1,'Oculus::Interaction::PoseDetection::Editor']]],
  ['featurestatethresholdseditor_3c_20fingerfeature_20_3e_27',['FeatureStateThresholdsEditor&lt; FingerFeature &gt;',['../class_oculus_1_1_interaction_1_1_pose_detection_1_1_editor_1_1_feature_state_thresholds_editor.html',1,'Oculus::Interaction::PoseDetection::Editor']]],
  ['featurestatethresholdseditor_3c_20transformfeature_20_3e_28',['FeatureStateThresholdsEditor&lt; TransformFeature &gt;',['../class_oculus_1_1_interaction_1_1_pose_detection_1_1_editor_1_1_feature_state_thresholds_editor.html',1,'Oculus::Interaction::PoseDetection::Editor']]],
  ['featurestatethresholdsmodel_29',['FeatureStateThresholdsModel',['../class_oculus_1_1_interaction_1_1_pose_detection_1_1_editor_1_1_feature_state_thresholds_editor_1282edf40b65ee1575e5e3f479ed2d692.html',1,'Oculus::Interaction::PoseDetection::Editor::FeatureStateThresholdsEditor']]],
  ['fieldgui_30',['FieldGUI',['../class_meta_1_1_wit_ai_1_1_windows_1_1_field_g_u_i.html',1,'Meta::WitAi::Windows']]],
  ['fieldwiringstrategies_31',['FieldWiringStrategies',['../class_oculus_1_1_interaction_1_1_editor_1_1_field_wiring_strategies.html',1,'Oculus::Interaction::Editor']]],
  ['filteredtransform_32',['FilteredTransform',['../class_oculus_1_1_interaction_1_1_utils_1_1_filtered_transform.html',1,'Oculus::Interaction::Utils']]],
  ['filteredtransformeditorfallback_33',['FilteredTransformEditorFallback',['../class_oculus_1_1_interaction_1_1_utils_1_1_editor_1_1_generated_1_1_filtered_transform_editor_fallback.html',1,'Oculus::Interaction::Utils::Editor::Generated']]],
  ['filterreaddelegate_34',['FilterReadDelegate',['../class_oculus_1_1_platform_1_1_voip_audio_source_hi_level_1_1_filter_read_delegate.html',1,'Oculus::Platform::VoipAudioSourceHiLevel']]],
  ['fingerfeatureconfig_35',['FingerFeatureConfig',['../class_oculus_1_1_interaction_1_1_pose_detection_1_1_shape_recognizer_1_1_finger_feature_config.html',1,'Oculus::Interaction::PoseDetection::ShapeRecognizer']]],
  ['fingerfeatureconfigbuilder_36',['FingerFeatureConfigBuilder',['../class_oculus_1_1_interaction_1_1_pose_detection_1_1_finger_feature_config_builder.html',1,'Oculus::Interaction::PoseDetection']]],
  ['fingerfeatureconfiglist_37',['FingerFeatureConfigList',['../class_oculus_1_1_interaction_1_1_pose_detection_1_1_shape_recognizer_1_1_finger_feature_config_list.html',1,'Oculus::Interaction::PoseDetection::ShapeRecognizer']]],
  ['fingerfeaturedebugvisual_38',['FingerFeatureDebugVisual',['../class_oculus_1_1_interaction_1_1_pose_detection_1_1_debug_1_1_finger_feature_debug_visual.html',1,'Oculus::Interaction::PoseDetection::Debug']]],
  ['fingerfeaturedebugvisualeditorfallback_39',['FingerFeatureDebugVisualEditorFallback',['../class_oculus_1_1_interaction_1_1_pose_detection_1_1_debug_1_1_editor_1_1_generated_1_1_finger_fe3486528f08053b6105fcd9efa5f18c98.html',1,'Oculus::Interaction::PoseDetection::Debug::Editor::Generated']]],
  ['fingerfeaturelistpropertydrawer_40',['FingerFeatureListPropertyDrawer',['../class_oculus_1_1_interaction_1_1_pose_detection_1_1_editor_1_1_finger_feature_list_property_drawer.html',1,'Oculus::Interaction::PoseDetection::Editor']]],
  ['fingerfeatureproperties_41',['FingerFeatureProperties',['../class_oculus_1_1_interaction_1_1_pose_detection_1_1_finger_feature_properties.html',1,'Oculus::Interaction::PoseDetection']]],
  ['fingerfeatureskeletaldebugvisual_42',['FingerFeatureSkeletalDebugVisual',['../class_oculus_1_1_interaction_1_1_pose_detection_1_1_debug_1_1_finger_feature_skeletal_debug_visual.html',1,'Oculus::Interaction::PoseDetection::Debug']]],
  ['fingerfeatureskeletaldebugvisualeditorfallback_43',['FingerFeatureSkeletalDebugVisualEditorFallback',['../class_oculus_1_1_interaction_1_1_pose_detection_1_1_debug_1_1_editor_1_1_generated_1_1_finger_fec6379e19d0a904bfff84416fe5e06a5a.html',1,'Oculus::Interaction::PoseDetection::Debug::Editor::Generated']]],
  ['fingerfeaturestateprovider_44',['FingerFeatureStateProvider',['../class_oculus_1_1_interaction_1_1_pose_detection_1_1_finger_feature_state_provider.html',1,'Oculus::Interaction::PoseDetection']]],
  ['fingerfeaturestateprovidereditorfallback_45',['FingerFeatureStateProviderEditorFallback',['../class_oculus_1_1_interaction_1_1_pose_detection_1_1_editor_1_1_generated_1_1_finger_feature_state_provider_editor_fallback.html',1,'Oculus::Interaction::PoseDetection::Editor::Generated']]],
  ['fingerfeaturestateproviderref_46',['FingerFeatureStateProviderRef',['../class_oculus_1_1_interaction_1_1_finger_feature_state_provider_ref.html',1,'Oculus::Interaction']]],
  ['fingerfeaturestateproviderrefeditorfallback_47',['FingerFeatureStateProviderRefEditorFallback',['../class_oculus_1_1_interaction_1_1_editor_1_1_generated_1_1_finger_feature_state_provider_ref_editor_fallback.html',1,'Oculus::Interaction::Editor::Generated']]],
  ['fingerfeaturestatethreshold_48',['FingerFeatureStateThreshold',['../class_oculus_1_1_interaction_1_1_pose_detection_1_1_finger_feature_state_threshold.html',1,'Oculus::Interaction::PoseDetection']]],
  ['fingerfeaturestatethresholds_49',['FingerFeatureStateThresholds',['../class_oculus_1_1_interaction_1_1_pose_detection_1_1_finger_feature_state_thresholds.html',1,'Oculus::Interaction::PoseDetection']]],
  ['fingerfeaturestatethresholdseditor_50',['FingerFeatureStateThresholdsEditor',['../class_oculus_1_1_interaction_1_1_pose_detection_1_1_editor_1_1_finger_feature_state_thresholds_editor.html',1,'Oculus::Interaction::PoseDetection::Editor']]],
  ['fingerfeaturestateusage_51',['FingerFeatureStateUsage',['../struct_oculus_1_1_interaction_1_1_pose_detection_1_1_shape_recognizer_active_state_1_1_finger_feature_state_usage.html',1,'Oculus::Interaction::PoseDetection::ShapeRecognizerActiveState']]],
  ['fingerfeaturethresholds_52',['FingerFeatureThresholds',['../class_oculus_1_1_interaction_1_1_pose_detection_1_1_finger_feature_thresholds.html',1,'Oculus::Interaction::PoseDetection']]],
  ['fingerpalmgrabapi_53',['FingerPalmGrabAPI',['../class_oculus_1_1_interaction_1_1_grab_a_p_i_1_1_finger_palm_grab_a_p_i.html',1,'Oculus::Interaction::GrabAPI']]],
  ['fingerpinchdata_54',['FingerPinchData',['../class_oculus_1_1_interaction_1_1_grab_a_p_i_1_1_finger_raw_pinch_a_p_i_1_1_finger_pinch_data.html',1,'Oculus::Interaction::GrabAPI::FingerRawPinchAPI']]],
  ['fingerpinchgrabapi_55',['FingerPinchGrabAPI',['../class_oculus_1_1_interaction_1_1_grab_a_p_i_1_1_finger_pinch_grab_a_p_i.html',1,'Oculus::Interaction::GrabAPI']]],
  ['fingerpinchvalue_56',['FingerPinchValue',['../class_oculus_1_1_interaction_1_1_finger_pinch_value.html',1,'Oculus::Interaction']]],
  ['fingerpinchvalueeditorfallback_57',['FingerPinchValueEditorFallback',['../class_oculus_1_1_interaction_1_1_editor_1_1_generated_1_1_finger_pinch_value_editor_fallback.html',1,'Oculus::Interaction::Editor::Generated']]],
  ['fingerrawpinchapi_58',['FingerRawPinchAPI',['../class_oculus_1_1_interaction_1_1_grab_a_p_i_1_1_finger_raw_pinch_a_p_i.html',1,'Oculus::Interaction::GrabAPI']]],
  ['fingerrawpinchinjector_59',['FingerRawPinchInjector',['../class_oculus_1_1_interaction_1_1_grab_a_p_i_1_1_finger_raw_pinch_injector.html',1,'Oculus::Interaction::GrabAPI']]],
  ['fingerrawpinchinjectoreditorfallback_60',['FingerRawPinchInjectorEditorFallback',['../class_oculus_1_1_interaction_1_1_grab_a_p_i_1_1_editor_1_1_generated_1_1_finger_raw_pinch_injector_editor_fallback.html',1,'Oculus::Interaction::GrabAPI::Editor::Generated']]],
  ['fingershapes_61',['FingerShapes',['../class_oculus_1_1_interaction_1_1_pose_detection_1_1_finger_shapes.html',1,'Oculus::Interaction::PoseDetection']]],
  ['fingersmetadata_62',['FingersMetadata',['../class_oculus_1_1_interaction_1_1_input_1_1_fingers_metadata.html',1,'Oculus::Interaction::Input']]],
  ['fingerstatethresholds_63',['FingerStateThresholds',['../struct_oculus_1_1_interaction_1_1_pose_detection_1_1_finger_feature_state_provider_1_1_finger_state_thresholds.html',1,'Oculus::Interaction::PoseDetection::FingerFeatureStateProvider']]],
  ['fingerstatus_64',['FingerStatus',['../class_oculus_1_1_interaction_1_1_touch_hand_grab_interactor_1_1_finger_status.html',1,'Oculus::Interaction::TouchHandGrabInteractor']]],
  ['fingertippoketool_65',['FingerTipPokeTool',['../class_oculus_sample_framework_1_1_finger_tip_poke_tool.html',1,'OculusSampleFramework']]],
  ['fingertippoketoolview_66',['FingerTipPokeToolView',['../class_oculus_sample_framework_1_1_finger_tip_poke_tool_view.html',1,'OculusSampleFramework']]],
  ['firebaseenabler_67',['FirebaseEnabler',['../class_firebase_enabler.html',1,'']]],
  ['firsthoverinteractorgroup_68',['FirstHoverInteractorGroup',['../class_oculus_1_1_interaction_1_1_first_hover_interactor_group.html',1,'Oculus::Interaction']]],
  ['firsthoverinteractorgroupeditorfallback_69',['FirstHoverInteractorGroupEditorFallback',['../class_oculus_1_1_interaction_1_1_editor_1_1_generated_1_1_first_hover_interactor_group_editor_fallback.html',1,'Oculus::Interaction::Editor::Generated']]],
  ['fixedscalehand_70',['FixedScaleHand',['../class_oculus_1_1_interaction_1_1_input_1_1_fixed_scale_hand.html',1,'Oculus::Interaction::Input']]],
  ['fixedscalehandeditorfallback_71',['FixedScaleHandEditorFallback',['../class_oculus_1_1_interaction_1_1_input_1_1_editor_1_1_generated_1_1_fixed_scale_hand_editor_fallback.html',1,'Oculus::Interaction::Input::Editor::Generated']]],
  ['fixrecord_72',['FixRecord',['../class_assets_1_1_o_v_r_1_1_scripts_1_1_fix_record.html',1,'Assets::OVR::Scripts']]],
  ['flashlight_73',['Flashlight',['../class_flashlight.html',1,'']]],
  ['flashlightcontroller_74',['FlashlightController',['../class_flashlight_controller.html',1,'']]],
  ['fliptrianglewindingjob_75',['FlipTriangleWindingJob',['../struct_o_v_r_triangle_mesh_1_1_flip_triangle_winding_job.html',1,'OVRTriangleMesh']]],
  ['floatconstraint_76',['FloatConstraint',['../class_oculus_1_1_interaction_1_1_float_constraint.html',1,'Oculus::Interaction']]],
  ['floattostringevent_77',['FloatToStringEvent',['../class_meta_1_1_wit_ai_1_1_utilities_1_1_float_to_string_event.html',1,'Meta::WitAi::Utilities']]],
  ['fmodplugininterface_78',['FMODPluginInterface',['../class_o_n_s_p_propagation_1_1_f_m_o_d_plugin_interface.html',1,'ONSPPropagation']]],
  ['foldoutgroup_79',['FoldoutGroup',['../class_meta_1_1_voice_1_1_hub_1_1_u_i_components_1_1_foldout_group.html',1,'Meta::Voice::Hub::UIComponents']]],
  ['foldouthierarchy_80',['FoldoutHierarchy',['../class_meta_1_1_voice_1_1_hub_1_1_u_i_components_1_1_foldout_hierarchy.html',1,'Meta::Voice::Hub::UIComponents']]],
  ['foldouthierarchy_3c_20meta_3a_3avoice_3a_3ahub_3a_3ametahub_3a_3apagereference_20_3e_81',['FoldoutHierarchy&lt; Meta::Voice::Hub::MetaHub::PageReference &gt;',['../class_meta_1_1_voice_1_1_hub_1_1_u_i_components_1_1_foldout_hierarchy.html',1,'Meta::Voice::Hub::UIComponents']]],
  ['foldouthierarchyitem_82',['FoldoutHierarchyItem',['../class_meta_1_1_voice_1_1_hub_1_1_u_i_components_1_1_foldout_hierarchy_item.html',1,'Meta::Voice::Hub::UIComponents']]],
  ['followtarget_83',['FollowTarget',['../class_oculus_1_1_interaction_1_1_hand_grab_1_1_follow_target.html',1,'Oculus::Interaction::HandGrab']]],
  ['followtargetprovider_84',['FollowTargetProvider',['../class_oculus_1_1_interaction_1_1_hand_grab_1_1_follow_target_provider.html',1,'Oculus::Interaction::HandGrab']]],
  ['followtargetprovidereditorfallback_85',['FollowTargetProviderEditorFallback',['../class_oculus_1_1_interaction_1_1_hand_grab_1_1_editor_1_1_generated_1_1_follow_target_provider_editor_fallback.html',1,'Oculus::Interaction::HandGrab::Editor::Generated']]],
  ['formattedvalueevents_86',['FormattedValueEvents',['../class_meta_1_1_wit_ai_1_1_callback_handlers_1_1_formatted_value_events.html',1,'Meta::WitAi::CallbackHandlers']]],
  ['fovf_87',['Fovf',['../struct_o_v_r_plugin_1_1_fovf.html',1,'OVRPlugin']]],
  ['frame_88',['Frame',['../class_o_v_r_lip_sync_1_1_frame.html',1,'OVRLipSync']]],
  ['frameheader_89',['FrameHeader',['../struct_o_v_r_network_1_1_frame_header.html',1,'OVRNetwork']]],
  ['fromhandprefabdatasource_90',['FromHandPrefabDataSource',['../class_oculus_1_1_interaction_1_1_input_1_1_from_hand_prefab_data_source.html',1,'Oculus::Interaction::Input']]],
  ['fromhandprefabdatasourceeditor_91',['FromHandPrefabDataSourceEditor',['../class_oculus_1_1_interaction_1_1_hands_1_1_editor_1_1_from_hand_prefab_data_source_editor.html',1,'Oculus::Interaction::Hands::Editor']]],
  ['fromhandprefabdatasourceeditorfallback_92',['FromHandPrefabDataSourceEditorFallback',['../class_oculus_1_1_interaction_1_1_input_1_1_editor_1_1_generated_1_1_from_hand_prefab_data_source_editor_fallback.html',1,'Oculus::Interaction::Input::Editor::Generated']]],
  ['fromovrbodydatasource_93',['FromOVRBodyDataSource',['../class_oculus_1_1_interaction_1_1_body_1_1_input_1_1_from_o_v_r_body_data_source.html',1,'Oculus::Interaction::Body::Input']]],
  ['fromovrcontrollerdatasource_94',['FromOVRControllerDataSource',['../class_oculus_1_1_interaction_1_1_input_1_1_from_o_v_r_controller_data_source.html',1,'Oculus::Interaction::Input']]],
  ['fromovrcontrollerhanddatasource_95',['FromOVRControllerHandDataSource',['../class_oculus_1_1_interaction_1_1_input_1_1_from_o_v_r_controller_hand_data_source.html',1,'Oculus::Interaction::Input']]],
  ['fromovrhanddatasource_96',['FromOVRHandDataSource',['../class_oculus_1_1_interaction_1_1_input_1_1_from_o_v_r_hand_data_source.html',1,'Oculus::Interaction::Input']]],
  ['fromovrhmddatasource_97',['FromOVRHmdDataSource',['../class_oculus_1_1_interaction_1_1_input_1_1_from_o_v_r_hmd_data_source.html',1,'Oculus::Interaction::Input']]],
  ['frustum_98',['Frustum',['../struct_o_v_r_tracker_1_1_frustum.html',1,'OVRTracker']]],
  ['frustumf_99',['Frustumf',['../struct_o_v_r_plugin_1_1_frustumf.html',1,'OVRPlugin']]],
  ['frustumf2_100',['Frustumf2',['../struct_o_v_r_plugin_1_1_frustumf2.html',1,'OVRPlugin']]],
  ['furniturespawner_101',['FurnitureSpawner',['../class_furniture_spawner.html',1,'']]]
];
