var searchData=
[
  ['packagecleanup_0',['PackageCleanup',['../class_oculus_1_1_interaction_1_1_editor_1_1_package_cleanup.html',1,'Oculus::Interaction::Editor']]],
  ['packet_1',['Packet',['../class_oculus_1_1_platform_1_1_packet.html',1,'Oculus::Platform']]],
  ['pagegroup_2',['PageGroup',['../class_meta_1_1_voice_1_1_hub_1_1_meta_hub_1_1_page_group.html',1,'Meta::Voice::Hub::MetaHub']]],
  ['pagereference_3',['PageReference',['../struct_meta_1_1_voice_1_1_hub_1_1_meta_hub_1_1_page_reference.html',1,'Meta::Voice::Hub::MetaHub']]],
  ['panelhmdfollower_4',['PanelHMDFollower',['../class_oculus_sample_framework_1_1_panel_h_m_d_follower.html',1,'OculusSampleFramework']]],
  ['paralleltextactivator_5',['ParallelTextActivator',['../class_meta_1_1_voice_1_1_samples_1_1_shapes_1_1_parallel_text_activator.html',1,'Meta::Voice::Samples::Shapes']]],
  ['parsing_6',['Parsing',['../class_gradle_1_1_template_1_1_parsing.html',1,'Gradle::Template']]],
  ['parties_7',['Parties',['../class_oculus_1_1_platform_1_1_parties.html',1,'Oculus::Platform']]],
  ['party_8',['Party',['../class_oculus_1_1_platform_1_1_models_1_1_party.html',1,'Oculus::Platform::Models']]],
  ['partyid_9',['PartyID',['../class_oculus_1_1_platform_1_1_models_1_1_party_i_d.html',1,'Oculus::Platform::Models']]],
  ['partyupdatenotification_10',['PartyUpdateNotification',['../class_oculus_1_1_platform_1_1_models_1_1_party_update_notification.html',1,'Oculus::Platform::Models']]],
  ['passthroughbrush_11',['PassthroughBrush',['../class_passthrough_brush.html',1,'']]],
  ['passthroughcapabilities_12',['passthroughcapabilities',['../class_o_v_r_manager_1_1_passthrough_capabilities.html',1,'OVRManager.PassthroughCapabilities'],['../struct_o_v_r_plugin_1_1_passthrough_capabilities.html',1,'OVRPlugin.PassthroughCapabilities']]],
  ['passthroughcolorlutdata_13',['PassthroughColorLutData',['../struct_o_v_r_plugin_1_1_passthrough_color_lut_data.html',1,'OVRPlugin']]],
  ['passthroughcontroller_14',['PassthroughController',['../class_passthrough_controller.html',1,'']]],
  ['passthroughmeshinstance_15',['PassthroughMeshInstance',['../struct_o_v_r_passthrough_layer_1_1_passthrough_mesh_instance.html',1,'OVRPassthroughLayer']]],
  ['passthroughplayineditor_16',['PassthroughPlayInEditor',['../class_passthrough_play_in_editor.html',1,'']]],
  ['passthroughpreferences_17',['PassthroughPreferences',['../struct_o_v_r_plugin_1_1_passthrough_preferences.html',1,'OVRPlugin']]],
  ['passthroughprojectionsurface_18',['PassthroughProjectionSurface',['../class_passthrough_projection_surface.html',1,'']]],
  ['passthroughstyler_19',['PassthroughStyler',['../class_passthrough_styler.html',1,'']]],
  ['passthroughsurface_20',['PassthroughSurface',['../class_passthrough_surface.html',1,'']]],
  ['pathhelper_21',['PathHelper',['../class_path_helper.html',1,'']]],
  ['pathvalues_22',['PathValues',['../class_meta_1_1_wit_ai_1_1_lib_1_1_export_parser_1_1_path_values.html',1,'Meta::WitAi::Lib::ExportParser']]],
  ['pauseoninputloss_23',['PauseOnInputLoss',['../class_oculus_sample_framework_1_1_pause_on_input_loss.html',1,'OculusSampleFramework']]],
  ['perfmetrics_24',['PerfMetrics',['../class_o_v_r_system_perf_metrics_1_1_perf_metrics.html',1,'OVRSystemPerfMetrics']]],
  ['physicsgrabbable_25',['PhysicsGrabbable',['../class_oculus_1_1_interaction_1_1_physics_grabbable.html',1,'Oculus::Interaction']]],
  ['physicsgrabbableeditorfallback_26',['PhysicsGrabbableEditorFallback',['../class_oculus_1_1_interaction_1_1_editor_1_1_generated_1_1_physics_grabbable_editor_fallback.html',1,'Oculus::Interaction::Editor::Generated']]],
  ['pid_27',['Pid',['../class_oculus_1_1_platform_1_1_models_1_1_pid.html',1,'Oculus::Platform::Models']]],
  ['pidlist_28',['PidList',['../class_oculus_1_1_platform_1_1_models_1_1_pid_list.html',1,'Oculus::Platform::Models']]],
  ['pinchpointervisual_29',['PinchPointerVisual',['../class_oculus_1_1_interaction_1_1_pinch_pointer_visual.html',1,'Oculus::Interaction']]],
  ['pinchstatemodule_30',['PinchStateModule',['../class_oculus_sample_framework_1_1_pinch_state_module.html',1,'OculusSampleFramework']]],
  ['pingresult_31',['PingResult',['../class_oculus_1_1_platform_1_1_models_1_1_ping_result.html',1,'Oculus::Platform::Models']]],
  ['pinnedarray_32',['PinnedArray',['../struct_o_v_r_plugin_1_1_pinned_array.html',1,'OVRPlugin']]],
  ['planesurface_33',['PlaneSurface',['../class_oculus_1_1_interaction_1_1_surfaces_1_1_plane_surface.html',1,'Oculus::Interaction::Surfaces']]],
  ['planesurfaceeditor_34',['PlaneSurfaceEditor',['../class_oculus_1_1_interaction_1_1_editor_1_1_plane_surface_editor.html',1,'Oculus::Interaction::Editor']]],
  ['planesurfaceeditorfallback_35',['PlaneSurfaceEditorFallback',['../class_oculus_1_1_interaction_1_1_surfaces_1_1_editor_1_1_generated_1_1_plane_surface_editor_fallback.html',1,'Oculus::Interaction::Surfaces::Editor::Generated']]],
  ['platformdictationimpl_36',['PlatformDictationImpl',['../class_oculus_1_1_voice_1_1_dictation_1_1_bindings_1_1_android_1_1_platform_dictation_impl.html',1,'Oculus::Voice::Dictation::Bindings::Android']]],
  ['platformdictationsdkbinding_37',['PlatformDictationSDKBinding',['../class_oculus_1_1_voice_1_1_dictation_1_1_bindings_1_1_android_1_1_platform_dictation_s_d_k_binding.html',1,'Oculus::Voice::Dictation::Bindings::Android']]],
  ['platformdictationsession_38',['PlatformDictationSession',['../class_oculus_1_1_voice_1_1_dictation_1_1_bindings_1_1_android_1_1_platform_dictation_session.html',1,'Oculus::Voice::Dictation::Bindings::Android']]],
  ['platforminitialize_39',['PlatformInitialize',['../class_oculus_1_1_platform_1_1_models_1_1_platform_initialize.html',1,'Oculus::Platform::Models']]],
  ['platforminternal_40',['PlatformInternal',['../class_oculus_1_1_platform_1_1_platform_internal.html',1,'Oculus::Platform']]],
  ['platformsettings_41',['PlatformSettings',['../class_oculus_1_1_platform_1_1_platform_settings.html',1,'Oculus::Platform']]],
  ['playerlocomotor_42',['PlayerLocomotor',['../class_oculus_1_1_interaction_1_1_locomotion_1_1_player_locomotor.html',1,'Oculus::Interaction::Locomotion']]],
  ['playerlocomotoreditorfallback_43',['PlayerLocomotorEditorFallback',['../class_oculus_1_1_interaction_1_1_locomotion_1_1_editor_1_1_generated_1_1_player_locomotor_editor_fallback.html',1,'Oculus::Interaction::Locomotion::Editor::Generated']]],
  ['pluginupdater_44',['PluginUpdater',['../class_oculus_1_1_interaction_1_1_plugin_updater.html',1,'Oculus::Interaction']]],
  ['point_45',['Point',['../class_o_n_s_p_propagation_material_1_1_point.html',1,'ONSPPropagationMaterial']]],
  ['pointablecanvas_46',['PointableCanvas',['../class_oculus_1_1_interaction_1_1_pointable_canvas.html',1,'Oculus::Interaction']]],
  ['pointablecanvaseditorfallback_47',['PointableCanvasEditorFallback',['../class_oculus_1_1_interaction_1_1_editor_1_1_generated_1_1_pointable_canvas_editor_fallback.html',1,'Oculus::Interaction::Editor::Generated']]],
  ['pointablecanvaseventargs_48',['PointableCanvasEventArgs',['../class_oculus_1_1_interaction_1_1_pointable_canvas_event_args.html',1,'Oculus::Interaction']]],
  ['pointablecanvasmesh_49',['PointableCanvasMesh',['../class_oculus_1_1_interaction_1_1_pointable_canvas_mesh.html',1,'Oculus::Interaction']]],
  ['pointablecanvasmesheditorfallback_50',['PointableCanvasMeshEditorFallback',['../class_oculus_1_1_interaction_1_1_editor_1_1_generated_1_1_pointable_canvas_mesh_editor_fallback.html',1,'Oculus::Interaction::Editor::Generated']]],
  ['pointablecanvasmodule_51',['PointableCanvasModule',['../class_oculus_1_1_interaction_1_1_pointable_canvas_module.html',1,'Oculus::Interaction']]],
  ['pointablecanvasmoduleeditorfallback_52',['PointableCanvasModuleEditorFallback',['../class_oculus_1_1_interaction_1_1_editor_1_1_generated_1_1_pointable_canvas_module_editor_fallback.html',1,'Oculus::Interaction::Editor::Generated']]],
  ['pointablecanvasunityeventwrapper_53',['PointableCanvasUnityEventWrapper',['../class_oculus_1_1_interaction_1_1_pointable_canvas_unity_event_wrapper.html',1,'Oculus::Interaction']]],
  ['pointablecanvasunityeventwrappereditorfallback_54',['PointableCanvasUnityEventWrapperEditorFallback',['../class_oculus_1_1_interaction_1_1_editor_1_1_generated_1_1_pointable_canvas_unity_event_wrapper_editor_fallback.html',1,'Oculus::Interaction::Editor::Generated']]],
  ['pointabledebuggizmos_55',['PointableDebugGizmos',['../class_oculus_1_1_interaction_1_1_pointable_debug_gizmos.html',1,'Oculus::Interaction']]],
  ['pointabledebuggizmoseditorfallback_56',['PointableDebugGizmosEditorFallback',['../class_oculus_1_1_interaction_1_1_editor_1_1_generated_1_1_pointable_debug_gizmos_editor_fallback.html',1,'Oculus::Interaction::Editor::Generated']]],
  ['pointabledebugpolylinegizmos_57',['PointableDebugPolylineGizmos',['../class_oculus_1_1_interaction_1_1_deprecated_1_1_pointable_debug_polyline_gizmos.html',1,'Oculus::Interaction::Deprecated']]],
  ['pointabledebugvisual_58',['PointableDebugVisual',['../class_oculus_1_1_interaction_1_1_pointable_debug_visual.html',1,'Oculus::Interaction']]],
  ['pointabledebugvisualeditorfallback_59',['PointableDebugVisualEditorFallback',['../class_oculus_1_1_interaction_1_1_editor_1_1_generated_1_1_pointable_debug_visual_editor_fallback.html',1,'Oculus::Interaction::Editor::Generated']]],
  ['pointableelement_60',['PointableElement',['../class_oculus_1_1_interaction_1_1_pointable_element.html',1,'Oculus::Interaction']]],
  ['pointableelementeditorfallback_61',['PointableElementEditorFallback',['../class_oculus_1_1_interaction_1_1_editor_1_1_generated_1_1_pointable_element_editor_fallback.html',1,'Oculus::Interaction::Editor::Generated']]],
  ['pointableunityeventwrapper_62',['PointableUnityEventWrapper',['../class_oculus_1_1_interaction_1_1_pointable_unity_event_wrapper.html',1,'Oculus::Interaction']]],
  ['pointableunityeventwrappereditorfallback_63',['PointableUnityEventWrapperEditorFallback',['../class_oculus_1_1_interaction_1_1_editor_1_1_generated_1_1_pointable_unity_event_wrapper_editor_fallback.html',1,'Oculus::Interaction::Editor::Generated']]],
  ['pointdata_64',['PointData',['../class_oculus_1_1_interaction_1_1_pointable_debug_gizmos_1_1_point_data.html',1,'Oculus::Interaction::PointableDebugGizmos']]],
  ['pointer_65',['Pointer',['../class_oculus_1_1_interaction_1_1_pointable_canvas_module_1_1_pointer.html',1,'Oculus::Interaction::PointableCanvasModule']]],
  ['pointerevent_66',['PointerEvent',['../struct_oculus_1_1_interaction_1_1_pointer_event.html',1,'Oculus::Interaction']]],
  ['pointereventdataextension_67',['PointerEventDataExtension',['../class_unity_engine_1_1_event_systems_1_1_pointer_event_data_extension.html',1,'UnityEngine::EventSystems']]],
  ['pointerinteractable_68',['PointerInteractable',['../class_oculus_1_1_interaction_1_1_pointer_interactable.html',1,'Oculus::Interaction']]],
  ['pointerinteractable_3c_20distancegrabinteractor_2c_20distancegrabinteractable_20_3e_69',['PointerInteractable&lt; DistanceGrabInteractor, DistanceGrabInteractable &gt;',['../class_oculus_1_1_interaction_1_1_pointer_interactable.html',1,'Oculus::Interaction']]],
  ['pointerinteractable_3c_20distancehandgrabinteractor_2c_20distancehandgrabinteractable_20_3e_70',['PointerInteractable&lt; DistanceHandGrabInteractor, DistanceHandGrabInteractable &gt;',['../class_oculus_1_1_interaction_1_1_pointer_interactable.html',1,'Oculus::Interaction']]],
  ['pointerinteractable_3c_20grabinteractor_2c_20grabinteractable_20_3e_71',['PointerInteractable&lt; GrabInteractor, GrabInteractable &gt;',['../class_oculus_1_1_interaction_1_1_pointer_interactable.html',1,'Oculus::Interaction']]],
  ['pointerinteractable_3c_20handgrabinteractor_2c_20handgrabinteractable_20_3e_72',['PointerInteractable&lt; HandGrabInteractor, HandGrabInteractable &gt;',['../class_oculus_1_1_interaction_1_1_pointer_interactable.html',1,'Oculus::Interaction']]],
  ['pointerinteractable_3c_20pokeinteractor_2c_20pokeinteractable_20_3e_73',['PointerInteractable&lt; PokeInteractor, PokeInteractable &gt;',['../class_oculus_1_1_interaction_1_1_pointer_interactable.html',1,'Oculus::Interaction']]],
  ['pointerinteractable_3c_20rayinteractor_2c_20rayinteractable_20_3e_74',['PointerInteractable&lt; RayInteractor, RayInteractable &gt;',['../class_oculus_1_1_interaction_1_1_pointer_interactable.html',1,'Oculus::Interaction']]],
  ['pointerinteractable_3c_20touchhandgrabinteractor_2c_20touchhandgrabinteractable_20_3e_75',['PointerInteractable&lt; TouchHandGrabInteractor, TouchHandGrabInteractable &gt;',['../class_oculus_1_1_interaction_1_1_pointer_interactable.html',1,'Oculus::Interaction']]],
  ['pointerinteractor_76',['PointerInteractor',['../class_oculus_1_1_interaction_1_1_pointer_interactor.html',1,'Oculus::Interaction']]],
  ['pointerinteractor_3c_20distancegrabinteractor_2c_20distancegrabinteractable_20_3e_77',['PointerInteractor&lt; DistanceGrabInteractor, DistanceGrabInteractable &gt;',['../class_oculus_1_1_interaction_1_1_pointer_interactor.html',1,'Oculus::Interaction']]],
  ['pointerinteractor_3c_20distancehandgrabinteractor_2c_20distancehandgrabinteractable_20_3e_78',['PointerInteractor&lt; DistanceHandGrabInteractor, DistanceHandGrabInteractable &gt;',['../class_oculus_1_1_interaction_1_1_pointer_interactor.html',1,'Oculus::Interaction']]],
  ['pointerinteractor_3c_20grabinteractor_2c_20grabinteractable_20_3e_79',['PointerInteractor&lt; GrabInteractor, GrabInteractable &gt;',['../class_oculus_1_1_interaction_1_1_pointer_interactor.html',1,'Oculus::Interaction']]],
  ['pointerinteractor_3c_20handgrabinteractor_2c_20handgrabinteractable_20_3e_80',['PointerInteractor&lt; HandGrabInteractor, HandGrabInteractable &gt;',['../class_oculus_1_1_interaction_1_1_pointer_interactor.html',1,'Oculus::Interaction']]],
  ['pointerinteractor_3c_20pokeinteractor_2c_20pokeinteractable_20_3e_81',['PointerInteractor&lt; PokeInteractor, PokeInteractable &gt;',['../class_oculus_1_1_interaction_1_1_pointer_interactor.html',1,'Oculus::Interaction']]],
  ['pointerinteractor_3c_20rayinteractor_2c_20rayinteractable_20_3e_82',['PointerInteractor&lt; RayInteractor, RayInteractable &gt;',['../class_oculus_1_1_interaction_1_1_pointer_interactor.html',1,'Oculus::Interaction']]],
  ['pointerinteractor_3c_20touchhandgrabinteractor_2c_20touchhandgrabinteractable_20_3e_83',['PointerInteractor&lt; TouchHandGrabInteractor, TouchHandGrabInteractable &gt;',['../class_oculus_1_1_interaction_1_1_pointer_interactor.html',1,'Oculus::Interaction']]],
  ['pokeinteractable_84',['PokeInteractable',['../class_oculus_1_1_interaction_1_1_poke_interactable.html',1,'Oculus::Interaction']]],
  ['pokeinteractableeditor_85',['PokeInteractableEditor',['../class_oculus_1_1_interaction_1_1_editor_1_1_poke_interactable_editor.html',1,'Oculus::Interaction::Editor']]],
  ['pokeinteractableeditorfallback_86',['PokeInteractableEditorFallback',['../class_oculus_1_1_interaction_1_1_editor_1_1_generated_1_1_poke_interactable_editor_fallback.html',1,'Oculus::Interaction::Editor::Generated']]],
  ['pokeinteractablevisual_87',['PokeInteractableVisual',['../class_oculus_1_1_interaction_1_1_poke_interactable_visual.html',1,'Oculus::Interaction']]],
  ['pokeinteractablevisualeditorfallback_88',['PokeInteractableVisualEditorFallback',['../class_oculus_1_1_interaction_1_1_editor_1_1_generated_1_1_poke_interactable_visual_editor_fallback.html',1,'Oculus::Interaction::Editor::Generated']]],
  ['pokeinteractor_89',['PokeInteractor',['../class_oculus_1_1_interaction_1_1_poke_interactor.html',1,'Oculus::Interaction']]],
  ['pokeinteractoreditor_90',['PokeInteractorEditor',['../class_oculus_1_1_interaction_1_1_editor_1_1_poke_interactor_editor.html',1,'Oculus::Interaction::Editor']]],
  ['pokeinteractoreditorfallback_91',['PokeInteractorEditorFallback',['../class_oculus_1_1_interaction_1_1_editor_1_1_generated_1_1_poke_interactor_editor_fallback.html',1,'Oculus::Interaction::Editor::Generated']]],
  ['pollnexteventunion_92',['PollNextEventUnion',['../struct_o_v_r_1_1_open_v_r_1_1_c_v_r_system_1_1_poll_next_event_union.html',1,'OVR::OpenVR::CVRSystem']]],
  ['pollnextoverlayeventunion_93',['PollNextOverlayEventUnion',['../struct_o_v_r_1_1_open_v_r_1_1_c_v_r_overlay_1_1_poll_next_overlay_event_union.html',1,'OVR::OpenVR::CVROverlay']]],
  ['polygonalboundary2dinternal_94',['PolygonalBoundary2DInternal',['../struct_o_v_r_plugin_1_1_polygonal_boundary2_d_internal.html',1,'OVRPlugin']]],
  ['polylinegizmos_95',['PolylineGizmos',['../class_oculus_1_1_interaction_1_1_deprecated_1_1_polyline_gizmos.html',1,'Oculus::Interaction::Deprecated']]],
  ['polylinerenderer_96',['PolylineRenderer',['../class_oculus_1_1_interaction_1_1_polyline_renderer.html',1,'Oculus::Interaction']]],
  ['populatemeshdatajob_97',['PopulateMeshDataJob',['../struct_o_v_r_scene_volume_mesh_filter_1_1_populate_mesh_data_job.html',1,'OVRSceneVolumeMeshFilter']]],
  ['pose_98',['Pose',['../class_oculus_sample_framework_1_1_pose.html',1,'OculusSampleFramework']]],
  ['posecapturecountdown_99',['PoseCaptureCountdown',['../class_oculus_1_1_interaction_1_1_body_1_1_samples_1_1_pose_capture_countdown.html',1,'Oculus::Interaction::Body::Samples']]],
  ['posedata_100',['PoseData',['../class_oculus_1_1_interaction_1_1_pose_detection_1_1_joint_delta_provider_1_1_pose_data.html',1,'Oculus::Interaction::PoseDetection::JointDeltaProvider']]],
  ['posef_101',['Posef',['../struct_o_v_r_plugin_1_1_posef.html',1,'OVRPlugin']]],
  ['posefrombody_102',['PoseFromBody',['../class_oculus_1_1_interaction_1_1_body_1_1_pose_detection_1_1_pose_from_body.html',1,'Oculus::Interaction::Body::PoseDetection']]],
  ['posemeasureparameters_103',['PoseMeasureParameters',['../struct_oculus_1_1_interaction_1_1_grab_1_1_pose_measure_parameters.html',1,'Oculus::Interaction::Grab']]],
  ['posestatef_104',['PoseStatef',['../struct_o_v_r_plugin_1_1_pose_statef.html',1,'OVRPlugin']]],
  ['posetraveldata_105',['PoseTravelData',['../struct_oculus_1_1_interaction_1_1_hand_grab_1_1_pose_travel_data.html',1,'Oculus::Interaction::HandGrab']]],
  ['poseusesample_106',['PoseUseSample',['../class_oculus_1_1_interaction_1_1_samples_1_1_pose_use_sample.html',1,'Oculus::Interaction::Samples']]],
  ['poseutils_107',['PoseUtils',['../class_oculus_1_1_interaction_1_1_pose_utils.html',1,'Oculus::Interaction']]],
  ['positionpinningconfig_108',['PositionPinningConfig',['../class_oculus_1_1_interaction_1_1_poke_interactable_1_1_position_pinning_config.html',1,'Oculus::Interaction::PokeInteractable']]],
  ['pressurebreakable_109',['PressureBreakable',['../class_oculus_1_1_interaction_1_1_pressure_breakable.html',1,'Oculus::Interaction']]],
  ['pressuresquishable_110',['PressureSquishable',['../class_oculus_1_1_interaction_1_1_pressure_squishable.html',1,'Oculus::Interaction']]],
  ['processport_111',['ProcessPort',['../class_process_port.html',1,'']]],
  ['product_112',['Product',['../class_oculus_1_1_platform_1_1_models_1_1_product.html',1,'Oculus::Platform::Models']]],
  ['productlist_113',['ProductList',['../class_oculus_1_1_platform_1_1_models_1_1_product_list.html',1,'Oculus::Platform::Models']]],
  ['profiletokenmodel_114',['ProfileTokenModel',['../class_oculus_1_1_platform_1_1_profile_token_model.html',1,'Oculus::Platform']]],
  ['progresscurve_115',['ProgressCurve',['../class_oculus_1_1_interaction_1_1_progress_curve.html',1,'Oculus::Interaction']]],
  ['propagationinterface_116',['PropagationInterface',['../interface_o_n_s_p_propagation_1_1_propagation_interface.html',1,'ONSPPropagation']]],
  ['properties_117',['properties',['../class_gradle_1_1_properties.html',1,'Gradle.Properties'],['../class_meta_1_1_wit_ai_1_1_callback_handlers_1_1_value_path_matcher_property_drawer_1_1_properties.html',1,'Meta.WitAi.CallbackHandlers.ValuePathMatcherPropertyDrawer.Properties'],['../class_oculus_1_1_interaction_1_1_unity_canvas_1_1_canvas_mesh_renderer_1_1_properties.html',1,'Oculus.Interaction.UnityCanvas.CanvasMeshRenderer.Properties'],['../class_oculus_1_1_interaction_1_1_unity_canvas_1_1_canvas_render_texture_1_1_properties.html',1,'Oculus.Interaction.UnityCanvas.CanvasRenderTexture.Properties'],['../class_oculus_1_1_interaction_1_1_unity_canvas_1_1_o_v_r_canvas_mesh_renderer_1_1_properties.html',1,'Oculus.Interaction.UnityCanvas.OVRCanvasMeshRenderer.Properties']]],
  ['purchase_118',['Purchase',['../class_oculus_1_1_platform_1_1_models_1_1_purchase.html',1,'Oculus::Platform::Models']]],
  ['purchaselist_119',['PurchaseList',['../class_oculus_1_1_platform_1_1_models_1_1_purchase_list.html',1,'Oculus::Platform::Models']]]
];
