var searchData=
[
  ['iactivestate_0',['IActiveState',['../interface_oculus_1_1_interaction_1_1_i_active_state.html',1,'Oculus::Interaction']]],
  ['iactivestatemodel_1',['IActiveStateModel',['../interface_oculus_1_1_interaction_1_1_pose_detection_1_1_debug_1_1_i_active_state_model.html',1,'Oculus::Interaction::PoseDetection::Debug']]],
  ['iactivestatenodeui_2',['IActiveStateNodeUI',['../interface_oculus_1_1_interaction_1_1_pose_detection_1_1_debug_1_1_i_active_state_node_u_i.html',1,'Oculus::Interaction::PoseDetection::Debug']]],
  ['iactivestatetreenode_3',['IActiveStateTreeNode',['../interface_oculus_1_1_interaction_1_1_pose_detection_1_1_debug_1_1_i_active_state_tree_node.html',1,'Oculus::Interaction::PoseDetection::Debug']]],
  ['iap_4',['IAP',['../class_oculus_1_1_platform_1_1_i_a_p.html',1,'Oculus::Platform']]],
  ['iapplicationdetailprovider_5',['IApplicationDetailProvider',['../interface_meta_1_1_wit_ai_1_1_data_1_1_configuration_1_1_i_application_detail_provider.html',1,'Meta::WitAi::Data::Configuration']]],
  ['iaudioclipprovider_6',['IAudioClipProvider',['../interface_meta_1_1_voice_1_1_audio_1_1_i_audio_clip_provider.html',1,'Meta::Voice::Audio']]],
  ['iaudioclipstream_7',['IAudioClipStream',['../interface_meta_1_1_voice_1_1_audio_1_1_i_audio_clip_stream.html',1,'Meta::Voice::Audio']]],
  ['iaudioeventprovider_8',['IAudioEventProvider',['../interface_meta_1_1_wit_ai_1_1_interfaces_1_1_i_audio_event_provider.html',1,'Meta::WitAi::Interfaces']]],
  ['iaudioinputevents_9',['IAudioInputEvents',['../interface_meta_1_1_wit_ai_1_1_interfaces_1_1_i_audio_input_events.html',1,'Meta::WitAi::Interfaces']]],
  ['iaudioinputsource_10',['IAudioInputSource',['../interface_meta_1_1_wit_ai_1_1_interfaces_1_1_i_audio_input_source.html',1,'Meta::WitAi::Interfaces']]],
  ['iaudioplayer_11',['IAudioPlayer',['../interface_meta_1_1_voice_1_1_audio_1_1_i_audio_player.html',1,'Meta::Voice::Audio']]],
  ['iaudiosourceprovider_12',['IAudioSourceProvider',['../interface_meta_1_1_voice_1_1_audio_1_1_i_audio_source_provider.html',1,'Meta::Voice::Audio']]],
  ['iaudiosystem_13',['IAudioSystem',['../interface_meta_1_1_voice_1_1_audio_1_1_i_audio_system.html',1,'Meta::Voice::Audio']]],
  ['iaxis1d_14',['IAxis1D',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_axis1_d.html',1,'Oculus::Interaction::Input']]],
  ['iaxis2d_15',['IAxis2D',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_axis2_d.html',1,'Oculus::Interaction::Input']]],
  ['ibody_16',['IBody',['../interface_oculus_1_1_interaction_1_1_body_1_1_input_1_1_i_body.html',1,'Oculus::Interaction::Body::Input']]],
  ['ibodypose_17',['IBodyPose',['../interface_oculus_1_1_interaction_1_1_body_1_1_pose_detection_1_1_i_body_pose.html',1,'Oculus::Interaction::Body::PoseDetection']]],
  ['ibounds_18',['IBounds',['../interface_oculus_1_1_interaction_1_1_surfaces_1_1_i_bounds.html',1,'Oculus::Interaction::Surfaces']]],
  ['iboundsclipper_19',['IBoundsClipper',['../interface_oculus_1_1_interaction_1_1_surfaces_1_1_i_bounds_clipper.html',1,'Oculus::Interaction::Surfaces']]],
  ['ibutton_20',['IButton',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_button.html',1,'Oculus::Interaction::Input']]],
  ['icandidatecomparer_21',['ICandidateComparer',['../interface_oculus_1_1_interaction_1_1_i_candidate_comparer.html',1,'Oculus::Interaction']]],
  ['icandidateposition_22',['ICandidatePosition',['../interface_oculus_1_1_interaction_1_1_i_candidate_position.html',1,'Oculus::Interaction']]],
  ['iclippedsurface_23',['IClippedSurface',['../interface_oculus_1_1_interaction_1_1_surfaces_1_1_i_clipped_surface.html',1,'Oculus::Interaction::Surfaces']]],
  ['iclippedsurface_3c_20iboundsclipper_20_3e_24',['IClippedSurface&lt; IBoundsClipper &gt;',['../interface_oculus_1_1_interaction_1_1_surfaces_1_1_i_clipped_surface.html',1,'Oculus::Interaction::Surfaces']]],
  ['iclippedsurface_3c_20icylinderclipper_20_3e_25',['IClippedSurface&lt; ICylinderClipper &gt;',['../interface_oculus_1_1_interaction_1_1_surfaces_1_1_i_clipped_surface.html',1,'Oculus::Interaction::Surfaces']]],
  ['icollidersref_26',['ICollidersRef',['../interface_oculus_1_1_interaction_1_1_i_colliders_ref.html',1,'Oculus::Interaction']]],
  ['iconnection_27',['IConnection',['../interface_oculus_1_1_voice_1_1_core_1_1_bindings_1_1_interfaces_1_1_i_connection.html',1,'Oculus::Voice::Core::Bindings::Interfaces']]],
  ['icontroller_28',['IController',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_controller.html',1,'Oculus::Interaction::Input']]],
  ['icontrollerdatamodifier_29',['IControllerDataModifier',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_controller_data_modifier.html',1,'Oculus::Interaction::Input']]],
  ['icopyfrom_30',['ICopyFrom',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_copy_from.html',1,'Oculus::Interaction::Input']]],
  ['icopyfrom_3c_20bodydataasset_20_3e_31',['ICopyFrom&lt; BodyDataAsset &gt;',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_copy_from.html',1,'Oculus::Interaction::Input']]],
  ['icopyfrom_3c_20controllerdataasset_20_3e_32',['ICopyFrom&lt; ControllerDataAsset &gt;',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_copy_from.html',1,'Oculus::Interaction::Input']]],
  ['icopyfrom_3c_20handdataasset_20_3e_33',['ICopyFrom&lt; HandDataAsset &gt;',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_copy_from.html',1,'Oculus::Interaction::Input']]],
  ['icopyfrom_3c_20hmddataasset_20_3e_34',['ICopyFrom&lt; HmdDataAsset &gt;',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_copy_from.html',1,'Oculus::Interaction::Input']]],
  ['icurvedplane_35',['ICurvedPlane',['../interface_oculus_1_1_interaction_1_1_i_curved_plane.html',1,'Oculus::Interaction']]],
  ['icylinderclipper_36',['ICylinderClipper',['../interface_oculus_1_1_interaction_1_1_surfaces_1_1_i_cylinder_clipper.html',1,'Oculus::Interaction::Surfaces']]],
  ['idatasource_37',['IDataSource',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_data_source.html',1,'Oculus::Interaction::Input']]],
  ['idictationservice_38',['IDictationService',['../interface_meta_1_1_wit_ai_1_1_dictation_1_1_i_dictation_service.html',1,'Meta::WitAi::Dictation']]],
  ['idistanceinteractor_39',['IDistanceInteractor',['../interface_oculus_1_1_interaction_1_1_i_distance_interactor.html',1,'Oculus::Interaction']]],
  ['idynamicentitiesprovider_40',['IDynamicEntitiesProvider',['../interface_meta_1_1_wit_ai_1_1_interfaces_1_1_i_dynamic_entities_provider.html',1,'Meta::WitAi::Interfaces']]],
  ['ienumerablehashset_41',['IEnumerableHashSet',['../interface_oculus_1_1_interaction_1_1_collections_1_1_i_enumerable_hash_set.html',1,'Oculus::Interaction::Collections']]],
  ['ienumerablehashset_3c_20bodyjointid_20_3e_42',['IEnumerableHashSet&lt; BodyJointId &gt;',['../interface_oculus_1_1_interaction_1_1_collections_1_1_i_enumerable_hash_set.html',1,'Oculus::Interaction::Collections']]],
  ['ievent_43',['IEvent',['../interface_oculus_1_1_interaction_1_1_i_event.html',1,'Oculus::Interaction']]],
  ['ifeaturestatethreshold_44',['IFeatureStateThreshold',['../interface_oculus_1_1_interaction_1_1_pose_detection_1_1_i_feature_state_threshold.html',1,'Oculus::Interaction::PoseDetection']]],
  ['ifeaturestatethreshold_3c_20string_20_3e_45',['IFeatureStateThreshold&lt; string &gt;',['../interface_oculus_1_1_interaction_1_1_pose_detection_1_1_i_feature_state_threshold.html',1,'Oculus::Interaction::PoseDetection']]],
  ['ifeaturestatethresholds_46',['IFeatureStateThresholds',['../interface_oculus_1_1_interaction_1_1_pose_detection_1_1_i_feature_state_thresholds.html',1,'Oculus::Interaction::PoseDetection']]],
  ['ifeaturestatethresholds_3c_20fingerfeature_2c_20string_20_3e_47',['IFeatureStateThresholds&lt; FingerFeature, string &gt;',['../interface_oculus_1_1_interaction_1_1_pose_detection_1_1_i_feature_state_thresholds.html',1,'Oculus::Interaction::PoseDetection']]],
  ['ifeaturestatethresholds_3c_20transformfeature_2c_20string_20_3e_48',['IFeatureStateThresholds&lt; TransformFeature, string &gt;',['../interface_oculus_1_1_interaction_1_1_pose_detection_1_1_i_feature_state_thresholds.html',1,'Oculus::Interaction::PoseDetection']]],
  ['ifeaturethresholds_49',['IFeatureThresholds',['../interface_oculus_1_1_interaction_1_1_pose_detection_1_1_i_feature_thresholds.html',1,'Oculus::Interaction::PoseDetection']]],
  ['ifeaturethresholds_3c_20fingerfeature_2c_20string_20_3e_50',['IFeatureThresholds&lt; FingerFeature, string &gt;',['../interface_oculus_1_1_interaction_1_1_pose_detection_1_1_i_feature_thresholds.html',1,'Oculus::Interaction::PoseDetection']]],
  ['ifeaturethresholds_3c_20transformfeature_2c_20string_20_3e_51',['IFeatureThresholds&lt; TransformFeature, string &gt;',['../interface_oculus_1_1_interaction_1_1_pose_detection_1_1_i_feature_thresholds.html',1,'Oculus::Interaction::PoseDetection']]],
  ['ifingerapi_52',['IFingerAPI',['../interface_oculus_1_1_interaction_1_1_i_finger_a_p_i.html',1,'Oculus::Interaction']]],
  ['ifingerfeaturestateprovider_53',['IFingerFeatureStateProvider',['../interface_oculus_1_1_interaction_1_1_pose_detection_1_1_i_finger_feature_state_provider.html',1,'Oculus::Interaction::PoseDetection']]],
  ['ifingeruseapi_54',['IFingerUseAPI',['../interface_oculus_1_1_interaction_1_1_i_finger_use_a_p_i.html',1,'Oculus::Interaction']]],
  ['igameobjectfilter_55',['IGameObjectFilter',['../interface_oculus_1_1_interaction_1_1_i_game_object_filter.html',1,'Oculus::Interaction']]],
  ['igrabbable_56',['IGrabbable',['../interface_oculus_1_1_interaction_1_1_i_grabbable.html',1,'Oculus::Interaction']]],
  ['igrabsurface_57',['IGrabSurface',['../interface_oculus_1_1_interaction_1_1_grab_1_1_grab_surfaces_1_1_i_grab_surface.html',1,'Oculus::Interaction::Grab::GrabSurfaces']]],
  ['ihand_58',['IHand',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_hand.html',1,'Oculus::Interaction::Input']]],
  ['ihandgrabinteractable_59',['IHandGrabInteractable',['../interface_oculus_1_1_interaction_1_1_hand_grab_1_1_i_hand_grab_interactable.html',1,'Oculus::Interaction::HandGrab']]],
  ['ihandgrabinteractor_60',['IHandGrabInteractor',['../interface_oculus_1_1_interaction_1_1_hand_grab_1_1_i_hand_grab_interactor.html',1,'Oculus::Interaction::HandGrab']]],
  ['ihandgrabstate_61',['IHandGrabState',['../interface_oculus_1_1_interaction_1_1_hand_grab_1_1_i_hand_grab_state.html',1,'Oculus::Interaction::HandGrab']]],
  ['ihandgrabusedelegate_62',['IHandGrabUseDelegate',['../interface_oculus_1_1_interaction_1_1_hand_grab_1_1_i_hand_grab_use_delegate.html',1,'Oculus::Interaction::HandGrab']]],
  ['ihandskeletonprovider_63',['IHandSkeletonProvider',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_hand_skeleton_provider.html',1,'Oculus::Interaction::Input']]],
  ['ihandspheremap_64',['IHandSphereMap',['../interface_oculus_1_1_interaction_1_1_i_hand_sphere_map.html',1,'Oculus::Interaction']]],
  ['ihandvisual_65',['IHandVisual',['../interface_oculus_1_1_interaction_1_1_i_hand_visual.html',1,'Oculus::Interaction']]],
  ['ihmd_66',['IHmd',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_hmd.html',1,'Oculus::Interaction::Input']]],
  ['iinputsource_67',['IInputSource',['../interface_o_v_r_virtual_keyboard_1_1_i_input_source.html',1,'OVRVirtualKeyboard']]],
  ['iinteractable_68',['IInteractable',['../interface_oculus_1_1_interaction_1_1_i_interactable.html',1,'Oculus::Interaction']]],
  ['iinteractableview_69',['IInteractableView',['../interface_oculus_1_1_interaction_1_1_i_interactable_view.html',1,'Oculus::Interaction']]],
  ['iinteractor_70',['IInteractor',['../interface_oculus_1_1_interaction_1_1_i_interactor.html',1,'Oculus::Interaction']]],
  ['iinteractorview_71',['IInteractorView',['../interface_oculus_1_1_interaction_1_1_i_interactor_view.html',1,'Oculus::Interaction']]],
  ['ijointdeltaprovider_72',['IJointDeltaProvider',['../interface_oculus_1_1_interaction_1_1_pose_detection_1_1_i_joint_delta_provider.html',1,'Oculus::Interaction::PoseDetection']]],
  ['ijsondeserializer_73',['IJsonDeserializer',['../interface_meta_1_1_wit_ai_1_1_json_1_1_i_json_deserializer.html',1,'Meta::WitAi::Json']]],
  ['ijsonserializer_74',['IJsonSerializer',['../interface_meta_1_1_wit_ai_1_1_json_1_1_i_json_serializer.html',1,'Meta::WitAi::Json']]],
  ['ilocomotioneventbroadcaster_75',['ILocomotionEventBroadcaster',['../interface_oculus_1_1_interaction_1_1_locomotion_1_1_i_locomotion_event_broadcaster.html',1,'Oculus::Interaction::Locomotion']]],
  ['ilocomotioneventhandler_76',['ILocomotionEventHandler',['../interface_oculus_1_1_interaction_1_1_locomotion_1_1_i_locomotion_event_handler.html',1,'Oculus::Interaction::Locomotion']]],
  ['imagedisplayscriptableobjecteditor_77',['ImageDisplayScriptableObjectEditor',['../class_meta_1_1_voice_1_1_hub_1_1_image_display_scriptable_object_editor.html',1,'Meta::Voice::Hub']]],
  ['imagepage_78',['ImagePage',['../class_meta_1_1_voice_1_1_hub_1_1_image_page.html',1,'Meta::Voice::Hub']]],
  ['imageview_79',['ImageView',['../class_meta_1_1_voice_1_1_hub_1_1_u_i_components_1_1_image_view.html',1,'Meta::Voice::Hub::UIComponents']]],
  ['imageviewer_80',['ImageViewer',['../class_image_viewer.html',1,'']]],
  ['imetahubpage_81',['IMetaHubPage',['../interface_meta_1_1_voice_1_1_hub_1_1_interfaces_1_1_i_meta_hub_page.html',1,'Meta::Voice::Hub::Interfaces']]],
  ['imicrophone_82',['IMicrophone',['../interface_oculus_1_1_platform_1_1_i_microphone.html',1,'Oculus::Platform']]],
  ['imovement_83',['IMovement',['../interface_oculus_1_1_interaction_1_1_i_movement.html',1,'Oculus::Interaction']]],
  ['imovementprovider_84',['IMovementProvider',['../interface_oculus_1_1_interaction_1_1_i_movement_provider.html',1,'Oculus::Interaction']]],
  ['impactaudio_85',['ImpactAudio',['../struct_oculus_1_1_interaction_1_1_impact_audio.html',1,'Oculus::Interaction']]],
  ['imusample_5ft_86',['ImuSample_t',['../struct_o_v_r_1_1_open_v_r_1_1_imu_sample__t.html',1,'OVR::OpenVR']]],
  ['incrementalresultsubscriber_87',['IncrementalResultSubscriber',['../class_o_v_r_task_1_1_incremental_result_subscriber.html',1,'OVRTask']]],
  ['indexpinchsafereleaseselector_88',['IndexPinchSafeReleaseSelector',['../class_oculus_1_1_interaction_1_1_index_pinch_safe_release_selector.html',1,'Oculus::Interaction']]],
  ['indexpinchsafereleaseselectoreditorfallback_89',['IndexPinchSafeReleaseSelectorEditorFallback',['../class_oculus_1_1_interaction_1_1_editor_1_1_generated_1_1_index_pinch_safe_release_selector_editor_fallback.html',1,'Oculus::Interaction::Editor::Generated']]],
  ['indexpinchselector_90',['IndexPinchSelector',['../class_oculus_1_1_interaction_1_1_index_pinch_selector.html',1,'Oculus::Interaction']]],
  ['indexpinchselectoreditorfallback_91',['IndexPinchSelectorEditorFallback',['../class_oculus_1_1_interaction_1_1_editor_1_1_generated_1_1_index_pinch_selector_editor_fallback.html',1,'Oculus::Interaction::Editor::Generated']]],
  ['inlpaudiorequest_92',['INLPAudioRequest',['../interface_meta_1_1_voice_1_1_i_n_l_p_audio_request.html',1,'Meta::Voice']]],
  ['inlpaudiorequestevents_93',['INLPAudioRequestEvents',['../interface_meta_1_1_voice_1_1_i_n_l_p_audio_request_events.html',1,'Meta::Voice']]],
  ['inlpaudiorequestoptions_94',['INLPAudioRequestOptions',['../interface_meta_1_1_voice_1_1_i_n_l_p_audio_request_options.html',1,'Meta::Voice']]],
  ['inlpaudiorequestresults_95',['INLPAudioRequestResults',['../interface_meta_1_1_voice_1_1_i_n_l_p_audio_request_results.html',1,'Meta::Voice']]],
  ['inlprequestevents_96',['INLPRequestEvents',['../interface_meta_1_1_voice_1_1_i_n_l_p_request_events.html',1,'Meta::Voice']]],
  ['inlprequestoptions_97',['INLPRequestOptions',['../interface_meta_1_1_voice_1_1_i_n_l_p_request_options.html',1,'Meta::Voice']]],
  ['inlprequestresults_98',['INLPRequestResults',['../interface_meta_1_1_voice_1_1_i_n_l_p_request_results.html',1,'Meta::Voice']]],
  ['inlptextrequest_99',['INLPTextRequest',['../interface_meta_1_1_voice_1_1_i_n_l_p_text_request.html',1,'Meta::Voice']]],
  ['inlptextrequestevents_100',['INLPTextRequestEvents',['../interface_meta_1_1_voice_1_1_i_n_l_p_text_request_events.html',1,'Meta::Voice']]],
  ['inlptextrequestoptions_101',['INLPTextRequestOptions',['../interface_meta_1_1_voice_1_1_i_n_l_p_text_request_options.html',1,'Meta::Voice']]],
  ['inlptextrequestresults_102',['INLPTextRequestResults',['../interface_meta_1_1_voice_1_1_i_n_l_p_text_request_results.html',1,'Meta::Voice']]],
  ['inputanalogactiondata_5ft_103',['InputAnalogActionData_t',['../struct_o_v_r_1_1_open_v_r_1_1_input_analog_action_data__t.html',1,'OVR::OpenVR']]],
  ['inputaxis_104',['InputAxis',['../class_oculus_1_1_interaction_1_1_unity_1_1_input_1_1_input_axis.html',1,'Oculus::Interaction::Unity::Input']]],
  ['inputaxiseditorfallback_105',['InputAxisEditorFallback',['../class_oculus_1_1_interaction_1_1_unity_1_1_input_1_1_editor_1_1_generated_1_1_input_axis_editor_fallback.html',1,'Oculus::Interaction::Unity::Input::Editor::Generated']]],
  ['inputbutton_106',['InputButton',['../class_oculus_1_1_interaction_1_1_unity_1_1_input_1_1_input_button.html',1,'Oculus::Interaction::Unity::Input']]],
  ['inputbuttoneditorfallback_107',['InputButtonEditorFallback',['../class_oculus_1_1_interaction_1_1_unity_1_1_input_1_1_editor_1_1_generated_1_1_input_button_editor_fallback.html',1,'Oculus::Interaction::Unity::Input::Editor::Generated']]],
  ['inputdigitalactiondata_5ft_108',['InputDigitalActionData_t',['../struct_o_v_r_1_1_open_v_r_1_1_input_digital_action_data__t.html',1,'OVR::OpenVR']]],
  ['inputkey_109',['InputKey',['../class_oculus_1_1_interaction_1_1_unity_1_1_input_1_1_input_key.html',1,'Oculus::Interaction::Unity::Input']]],
  ['inputkeyeditorfallback_110',['InputKeyEditorFallback',['../class_oculus_1_1_interaction_1_1_unity_1_1_input_1_1_editor_1_1_generated_1_1_input_key_editor_fallback.html',1,'Oculus::Interaction::Unity::Input::Editor::Generated']]],
  ['inputmousebutton_111',['InputMouseButton',['../class_oculus_1_1_interaction_1_1_unity_1_1_input_1_1_input_mouse_button.html',1,'Oculus::Interaction::Unity::Input']]],
  ['inputmousebuttoneditorfallback_112',['InputMouseButtonEditorFallback',['../class_oculus_1_1_interaction_1_1_unity_1_1_input_1_1_editor_1_1_generated_1_1_input_mouse_button_editor_fallback.html',1,'Oculus::Interaction::Unity::Input::Editor::Generated']]],
  ['inputnodestate_113',['InputNodeState',['../struct_o_v_r_g_l_t_f_animatinon_node_1_1_input_node_state.html',1,'OVRGLTFAnimatinonNode']]],
  ['inputorigininfo_5ft_114',['InputOriginInfo_t',['../struct_o_v_r_1_1_open_v_r_1_1_input_origin_info__t.html',1,'OVR::OpenVR']]],
  ['inputposeactiondata_5ft_115',['InputPoseActionData_t',['../struct_o_v_r_1_1_open_v_r_1_1_input_pose_action_data__t.html',1,'OVR::OpenVR']]],
  ['inputskeletalactiondata_5ft_116',['InputSkeletalActionData_t',['../struct_o_v_r_1_1_open_v_r_1_1_input_skeletal_action_data__t.html',1,'OVR::OpenVR']]],
  ['insightpassthroughkeyboardhandsintensity_117',['InsightPassthroughKeyboardHandsIntensity',['../struct_o_v_r_plugin_1_1_insight_passthrough_keyboard_hands_intensity.html',1,'OVRPlugin']]],
  ['insightpassthroughstyle_118',['InsightPassthroughStyle',['../struct_o_v_r_plugin_1_1_insight_passthrough_style.html',1,'OVRPlugin']]],
  ['insightpassthroughstyle2_119',['InsightPassthroughStyle2',['../struct_o_v_r_plugin_1_1_insight_passthrough_style2.html',1,'OVRPlugin']]],
  ['inspectorbuttonattribute_120',['InspectorButtonAttribute',['../class_oculus_1_1_interaction_1_1_inspector_button_attribute.html',1,'Oculus::Interaction']]],
  ['inspectorcommentattribute_121',['InspectorCommentAttribute',['../class_inspector_comment_attribute.html',1,'']]],
  ['inspectornoteattribute_122',['InspectorNoteAttribute',['../class_inspector_note_attribute.html',1,'']]],
  ['installedapplication_123',['InstalledApplication',['../class_oculus_1_1_platform_1_1_models_1_1_installed_application.html',1,'Oculus::Platform::Models']]],
  ['installedapplicationlist_124',['InstalledApplicationList',['../class_oculus_1_1_platform_1_1_models_1_1_installed_application_list.html',1,'Oculus::Platform::Models']]],
  ['interactable_125',['interactable',['../class_oculus_1_1_interaction_1_1_interactable.html',1,'Oculus.Interaction.Interactable&lt; TInteractor, TInteractable &gt;'],['../class_oculus_sample_framework_1_1_interactable.html',1,'OculusSampleFramework.Interactable']]],
  ['interactable_3c_20handgrabuseinteractor_2c_20handgrabuseinteractable_20_3e_126',['Interactable&lt; HandGrabUseInteractor, HandGrabUseInteractable &gt;',['../class_oculus_1_1_interaction_1_1_interactable.html',1,'Oculus::Interaction']]],
  ['interactable_3c_20locomotionaxisturnerinteractor_2c_20locomotionaxisturnerinteractable_20_3e_127',['Interactable&lt; LocomotionAxisTurnerInteractor, LocomotionAxisTurnerInteractable &gt;',['../class_oculus_1_1_interaction_1_1_interactable.html',1,'Oculus::Interaction']]],
  ['interactable_3c_20locomotionturnerinteractor_2c_20locomotionturnerinteractable_20_3e_128',['Interactable&lt; LocomotionTurnerInteractor, LocomotionTurnerInteractable &gt;',['../class_oculus_1_1_interaction_1_1_interactable.html',1,'Oculus::Interaction']]],
  ['interactable_3c_20snapinteractor_2c_20snapinteractable_20_3e_129',['Interactable&lt; SnapInteractor, SnapInteractable &gt;',['../class_oculus_1_1_interaction_1_1_interactable.html',1,'Oculus::Interaction']]],
  ['interactable_3c_20teleportinteractor_2c_20teleportinteractable_20_3e_130',['Interactable&lt; TeleportInteractor, TeleportInteractable &gt;',['../class_oculus_1_1_interaction_1_1_interactable.html',1,'Oculus::Interaction']]],
  ['interactablecollisioninfo_131',['InteractableCollisionInfo',['../class_oculus_sample_framework_1_1_interactable_collision_info.html',1,'OculusSampleFramework']]],
  ['interactablecolorvisual_132',['InteractableColorVisual',['../class_oculus_1_1_interaction_1_1_interactable_color_visual.html',1,'Oculus::Interaction']]],
  ['interactablecolorvisualeditorfallback_133',['InteractableColorVisualEditorFallback',['../class_oculus_1_1_interaction_1_1_editor_1_1_generated_1_1_interactable_color_visual_editor_fallback.html',1,'Oculus::Interaction::Editor::Generated']]],
  ['interactabledebugvisual_134',['InteractableDebugVisual',['../class_oculus_1_1_interaction_1_1_interactable_debug_visual.html',1,'Oculus::Interaction']]],
  ['interactabledebugvisualeditorfallback_135',['InteractableDebugVisualEditorFallback',['../class_oculus_1_1_interaction_1_1_editor_1_1_generated_1_1_interactable_debug_visual_editor_fallback.html',1,'Oculus::Interaction::Editor::Generated']]],
  ['interactablegroup_136',['InteractableGroup',['../class_oculus_1_1_interaction_1_1_interactable_group.html',1,'Oculus::Interaction']]],
  ['interactablegroupeditorfallback_137',['InteractableGroupEditorFallback',['../class_oculus_1_1_interaction_1_1_editor_1_1_generated_1_1_interactable_group_editor_fallback.html',1,'Oculus::Interaction::Editor::Generated']]],
  ['interactablegroupview_138',['InteractableGroupView',['../class_oculus_1_1_interaction_1_1_interactable_group_view.html',1,'Oculus::Interaction']]],
  ['interactablegroupvieweditorfallback_139',['InteractableGroupViewEditorFallback',['../class_oculus_1_1_interaction_1_1_editor_1_1_generated_1_1_interactable_group_view_editor_fallback.html',1,'Oculus::Interaction::Editor::Generated']]],
  ['interactablelimits_140',['InteractableLimits',['../struct_oculus_1_1_interaction_1_1_interactable_group_1_1_interactable_limits.html',1,'Oculus::Interaction::InteractableGroup']]],
  ['interactableregistry_141',['interactableregistry',['../class_oculus_1_1_interaction_1_1_interactable_registry.html',1,'Oculus.Interaction.InteractableRegistry&lt; TInteractor, TInteractable &gt;'],['../class_oculus_sample_framework_1_1_interactable_registry.html',1,'OculusSampleFramework.InteractableRegistry']]],
  ['interactableset_142',['InteractableSet',['../struct_oculus_1_1_interaction_1_1_interactable_registry_1_1_interactable_set.html',1,'Oculus::Interaction::InteractableRegistry']]],
  ['interactablestateargs_143',['InteractableStateArgs',['../class_oculus_sample_framework_1_1_interactable_state_args.html',1,'OculusSampleFramework']]],
  ['interactablestateargsevent_144',['InteractableStateArgsEvent',['../class_oculus_sample_framework_1_1_interactable_1_1_interactable_state_args_event.html',1,'OculusSampleFramework::Interactable']]],
  ['interactablestatechangeargs_145',['InteractableStateChangeArgs',['../struct_oculus_1_1_interaction_1_1_interactable_state_change_args.html',1,'Oculus::Interaction']]],
  ['interactabletool_146',['InteractableTool',['../class_oculus_sample_framework_1_1_interactable_tool.html',1,'OculusSampleFramework']]],
  ['interactabletoolscreator_147',['InteractableToolsCreator',['../class_oculus_sample_framework_1_1_interactable_tools_creator.html',1,'OculusSampleFramework']]],
  ['interactabletoolsinputrouter_148',['InteractableToolsInputRouter',['../class_oculus_sample_framework_1_1_interactable_tools_input_router.html',1,'OculusSampleFramework']]],
  ['interactabletoolview_149',['InteractableToolView',['../interface_oculus_sample_framework_1_1_interactable_tool_view.html',1,'OculusSampleFramework']]],
  ['interactabletriggerbroadcaster_150',['InteractableTriggerBroadcaster',['../class_oculus_1_1_interaction_1_1_interactable_trigger_broadcaster.html',1,'Oculus::Interaction']]],
  ['interactabletriggerbroadcastereditorfallback_151',['InteractableTriggerBroadcasterEditorFallback',['../class_oculus_1_1_interaction_1_1_editor_1_1_generated_1_1_interactable_trigger_broadcaster_editor_fallback.html',1,'Oculus::Interaction::Editor::Generated']]],
  ['interactableunityeventwrapper_152',['InteractableUnityEventWrapper',['../class_oculus_1_1_interaction_1_1_interactable_unity_event_wrapper.html',1,'Oculus::Interaction']]],
  ['interactableunityeventwrappereditorfallback_153',['InteractableUnityEventWrapperEditorFallback',['../class_oculus_1_1_interaction_1_1_editor_1_1_generated_1_1_interactable_unity_event_wrapper_editor_fallback.html',1,'Oculus::Interaction::Editor::Generated']]],
  ['interactionautowiring_154',['InteractionAutoWiring',['../class_oculus_1_1_interaction_1_1_editor_1_1_interaction_auto_wiring.html',1,'Oculus::Interaction::Editor']]],
  ['interactor_155',['Interactor',['../class_oculus_1_1_interaction_1_1_interactor.html',1,'Oculus::Interaction']]],
  ['interactor_3c_20handgrabuseinteractor_2c_20handgrabuseinteractable_20_3e_156',['Interactor&lt; HandGrabUseInteractor, HandGrabUseInteractable &gt;',['../class_oculus_1_1_interaction_1_1_interactor.html',1,'Oculus::Interaction']]],
  ['interactor_3c_20locomotionaxisturnerinteractor_2c_20locomotionaxisturnerinteractable_20_3e_157',['Interactor&lt; LocomotionAxisTurnerInteractor, LocomotionAxisTurnerInteractable &gt;',['../class_oculus_1_1_interaction_1_1_interactor.html',1,'Oculus::Interaction']]],
  ['interactor_3c_20locomotionturnerinteractor_2c_20locomotionturnerinteractable_20_3e_158',['Interactor&lt; LocomotionTurnerInteractor, LocomotionTurnerInteractable &gt;',['../class_oculus_1_1_interaction_1_1_interactor.html',1,'Oculus::Interaction']]],
  ['interactor_3c_20snapinteractor_2c_20snapinteractable_20_3e_159',['Interactor&lt; SnapInteractor, SnapInteractable &gt;',['../class_oculus_1_1_interaction_1_1_interactor.html',1,'Oculus::Interaction']]],
  ['interactor_3c_20teleportinteractor_2c_20teleportinteractable_20_3e_160',['Interactor&lt; TeleportInteractor, TeleportInteractable &gt;',['../class_oculus_1_1_interaction_1_1_interactor.html',1,'Oculus::Interaction']]],
  ['interactoractivestate_161',['InteractorActiveState',['../class_oculus_1_1_interaction_1_1_interactor_active_state.html',1,'Oculus::Interaction']]],
  ['interactoractivestateeditorfallback_162',['InteractorActiveStateEditorFallback',['../class_oculus_1_1_interaction_1_1_editor_1_1_generated_1_1_interactor_active_state_editor_fallback.html',1,'Oculus::Interaction::Editor::Generated']]],
  ['interactordebugvisual_163',['InteractorDebugVisual',['../class_oculus_1_1_interaction_1_1_interactor_debug_visual.html',1,'Oculus::Interaction']]],
  ['interactordebugvisualeditorfallback_164',['InteractorDebugVisualEditorFallback',['../class_oculus_1_1_interaction_1_1_editor_1_1_generated_1_1_interactor_debug_visual_editor_fallback.html',1,'Oculus::Interaction::Editor::Generated']]],
  ['interactorgroup_165',['InteractorGroup',['../class_oculus_1_1_interaction_1_1_interactor_group.html',1,'Oculus::Interaction']]],
  ['interactorreticle_166',['InteractorReticle',['../class_oculus_1_1_interaction_1_1_distance_reticles_1_1_interactor_reticle.html',1,'Oculus::Interaction::DistanceReticles']]],
  ['interactorreticle_3c_20reticledataghost_20_3e_167',['InteractorReticle&lt; ReticleDataGhost &gt;',['../class_oculus_1_1_interaction_1_1_distance_reticles_1_1_interactor_reticle.html',1,'Oculus::Interaction::DistanceReticles']]],
  ['interactorreticle_3c_20reticledataicon_20_3e_168',['InteractorReticle&lt; ReticleDataIcon &gt;',['../class_oculus_1_1_interaction_1_1_distance_reticles_1_1_interactor_reticle.html',1,'Oculus::Interaction::DistanceReticles']]],
  ['interactorreticle_3c_20reticledatamesh_20_3e_169',['InteractorReticle&lt; ReticleDataMesh &gt;',['../class_oculus_1_1_interaction_1_1_distance_reticles_1_1_interactor_reticle.html',1,'Oculus::Interaction::DistanceReticles']]],
  ['interactorreticle_3c_20reticledatateleport_20_3e_170',['InteractorReticle&lt; ReticleDataTeleport &gt;',['../class_oculus_1_1_interaction_1_1_distance_reticles_1_1_interactor_reticle.html',1,'Oculus::Interaction::DistanceReticles']]],
  ['interactorrootoverridedata_171',['InteractorRootOverrideData',['../struct_o_v_r_virtual_keyboard_1_1_interactor_root_transform_override_1_1_interactor_root_override_data.html',1,'OVRVirtualKeyboard::InteractorRootTransformOverride']]],
  ['interactorroottransformoverride_172',['InteractorRootTransformOverride',['../class_o_v_r_virtual_keyboard_1_1_interactor_root_transform_override.html',1,'OVRVirtualKeyboard']]],
  ['interactorstatechangeargs_173',['InteractorStateChangeArgs',['../struct_oculus_1_1_interaction_1_1_interactor_state_change_args.html',1,'Oculus::Interaction']]],
  ['interactorunityeventwrapper_174',['InteractorUnityEventWrapper',['../class_oculus_1_1_interaction_1_1_interactor_unity_event_wrapper.html',1,'Oculus::Interaction']]],
  ['interactorunityeventwrappereditorfallback_175',['InteractorUnityEventWrapperEditorFallback',['../class_oculus_1_1_interaction_1_1_editor_1_1_generated_1_1_interactor_unity_event_wrapper_editor_fallback.html',1,'Oculus::Interaction::Editor::Generated']]],
  ['interfaceattribute_176',['InterfaceAttribute',['../class_oculus_1_1_interaction_1_1_interface_attribute.html',1,'Oculus::Interaction']]],
  ['interfacedrawer_177',['InterfaceDrawer',['../class_oculus_1_1_interaction_1_1_interface_support_1_1_interface_drawer.html',1,'Oculus::Interaction::InterfaceSupport']]],
  ['interfacepicker_178',['InterfacePicker',['../class_oculus_1_1_interaction_1_1_interface_support_1_1_interface_picker.html',1,'Oculus::Interaction::InterfaceSupport']]],
  ['internaldata_179',['InternalData',['../class_o_v_r_task_1_1_internal_data.html',1,'OVRTask']]],
  ['interpolatedcolorluthandler_180',['InterpolatedColorLutHandler',['../class_o_v_r_passthrough_layer_1_1_interpolated_color_lut_handler.html',1,'OVRPassthroughLayer']]],
  ['interpolationcache_181',['InterpolationCache',['../class_oculus_1_1_interaction_1_1_hand_grab_1_1_grab_pose_finder_1_1_interpolation_cache.html',1,'Oculus::Interaction::HandGrab::GrabPoseFinder']]],
  ['intersectionmaskcircle_5ft_182',['IntersectionMaskCircle_t',['../struct_o_v_r_1_1_open_v_r_1_1_intersection_mask_circle__t.html',1,'OVR::OpenVR']]],
  ['intersectionmaskrectangle_5ft_183',['IntersectionMaskRectangle_t',['../struct_o_v_r_1_1_open_v_r_1_1_intersection_mask_rectangle__t.html',1,'OVR::OpenVR']]],
  ['invertedcapture_184',['InvertedCapture',['../struct_o_v_r_spatial_anchor_1_1_inverted_capture.html',1,'OVRSpatialAnchor']]],
  ['inviteoptions_185',['InviteOptions',['../class_oculus_1_1_platform_1_1_invite_options.html',1,'Oculus::Platform']]],
  ['invitepanelresultinfo_186',['InvitePanelResultInfo',['../class_oculus_1_1_platform_1_1_models_1_1_invite_panel_result_info.html',1,'Oculus::Platform::Models']]],
  ['ioneeurofilter_187',['IOneEuroFilter',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_one_euro_filter.html',1,'Oculus::Interaction::Input']]],
  ['ioneeurofilter_3c_20float_20_3e_188',['IOneEuroFilter&lt; float &gt;',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_one_euro_filter.html',1,'Oculus::Interaction::Input']]],
  ['ioneeurofilter_3c_20quaternion_20_3e_189',['IOneEuroFilter&lt; Quaternion &gt;',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_one_euro_filter.html',1,'Oculus::Interaction::Input']]],
  ['ioneeurofilter_3c_20vector3_20_3e_190',['IOneEuroFilter&lt; Vector3 &gt;',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_one_euro_filter.html',1,'Oculus::Interaction::Input']]],
  ['ioutility_191',['IOUtility',['../class_meta_1_1_wit_ai_1_1_utilities_1_1_i_o_utility.html',1,'Meta::WitAi::Utilities']]],
  ['ioverridesize_192',['IOverrideSize',['../interface_meta_1_1_voice_1_1_hub_1_1_interfaces_1_1_i_override_size.html',1,'Meta::Voice::Hub::Interfaces']]],
  ['iovranchorcomponent_193',['IOVRAnchorComponent',['../interface_i_o_v_r_anchor_component.html',1,'']]],
  ['iovranchorcomponent_3c_20ovranchorcontainer_20_3e_194',['IOVRAnchorComponent&lt; OVRAnchorContainer &gt;',['../interface_i_o_v_r_anchor_component.html',1,'']]],
  ['iovranchorcomponent_3c_20ovrbounded2d_20_3e_195',['IOVRAnchorComponent&lt; OVRBounded2D &gt;',['../interface_i_o_v_r_anchor_component.html',1,'']]],
  ['iovranchorcomponent_3c_20ovrbounded3d_20_3e_196',['IOVRAnchorComponent&lt; OVRBounded3D &gt;',['../interface_i_o_v_r_anchor_component.html',1,'']]],
  ['iovranchorcomponent_3c_20ovrlocatable_20_3e_197',['IOVRAnchorComponent&lt; OVRLocatable &gt;',['../interface_i_o_v_r_anchor_component.html',1,'']]],
  ['iovranchorcomponent_3c_20ovrroomlayout_20_3e_198',['IOVRAnchorComponent&lt; OVRRoomLayout &gt;',['../interface_i_o_v_r_anchor_component.html',1,'']]],
  ['iovranchorcomponent_3c_20ovrsemanticlabels_20_3e_199',['IOVRAnchorComponent&lt; OVRSemanticLabels &gt;',['../interface_i_o_v_r_anchor_component.html',1,'']]],
  ['iovranchorcomponent_3c_20ovrsharable_20_3e_200',['IOVRAnchorComponent&lt; OVRSharable &gt;',['../interface_i_o_v_r_anchor_component.html',1,'']]],
  ['iovranchorcomponent_3c_20ovrstorable_20_3e_201',['IOVRAnchorComponent&lt; OVRStorable &gt;',['../interface_i_o_v_r_anchor_component.html',1,'']]],
  ['iovranchorcomponent_3c_20ovrtrianglemesh_20_3e_202',['IOVRAnchorComponent&lt; OVRTriangleMesh &gt;',['../interface_i_o_v_r_anchor_component.html',1,'']]],
  ['iovrcamerarigref_203',['IOVRCameraRigRef',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_o_v_r_camera_rig_ref.html',1,'Oculus::Interaction::Input']]],
  ['iovrmeshdataprovider_204',['IOVRMeshDataProvider',['../interface_o_v_r_mesh_1_1_i_o_v_r_mesh_data_provider.html',1,'OVRMesh']]],
  ['iovrmeshrendererdataprovider_205',['IOVRMeshRendererDataProvider',['../interface_o_v_r_mesh_renderer_1_1_i_o_v_r_mesh_renderer_data_provider.html',1,'OVRMeshRenderer']]],
  ['iovrplugininfosupplier_206',['IOVRPluginInfoSupplier',['../interface_oculus_1_1_v_r_1_1_editor_1_1_i_o_v_r_plugin_info_supplier.html',1,'Oculus::VR::Editor']]],
  ['iovrskeletondataprovider_207',['IOVRSkeletonDataProvider',['../interface_o_v_r_skeleton_1_1_i_o_v_r_skeleton_data_provider.html',1,'OVRSkeleton']]],
  ['iovrskeletonrendererdataprovider_208',['IOVRSkeletonRendererDataProvider',['../interface_o_v_r_skeleton_renderer_1_1_i_o_v_r_skeleton_renderer_data_provider.html',1,'OVRSkeletonRenderer']]],
  ['ipageinfo_209',['IPageInfo',['../interface_meta_1_1_voice_1_1_hub_1_1_interfaces_1_1_i_page_info.html',1,'Meta::Voice::Hub::Interfaces']]],
  ['iplatformvoiceservice_210',['IPlatformVoiceService',['../interface_oculus_1_1_voice_1_1_interfaces_1_1_i_platform_voice_service.html',1,'Oculus::Voice::Interfaces']]],
  ['ipointable_211',['IPointable',['../interface_oculus_1_1_interaction_1_1_i_pointable.html',1,'Oculus::Interaction']]],
  ['ipointablecanvas_212',['IPointableCanvas',['../interface_oculus_1_1_interaction_1_1_i_pointable_canvas.html',1,'Oculus::Interaction']]],
  ['ipointableelement_213',['IPointableElement',['../interface_oculus_1_1_interaction_1_1_i_pointable_element.html',1,'Oculus::Interaction']]],
  ['ipolyline_214',['IPolyline',['../interface_oculus_1_1_interaction_1_1_i_polyline.html',1,'Oculus::Interaction']]],
  ['iposeinputdevice_215',['IPoseInputDevice',['../interface_oculus_1_1_interaction_1_1_throw_1_1_i_pose_input_device.html',1,'Oculus::Interaction::Throw']]],
  ['ireadonlyhandskeleton_216',['IReadOnlyHandSkeleton',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_read_only_hand_skeleton.html',1,'Oculus::Interaction::Input']]],
  ['ireadonlyhandskeletonjointlist_217',['IReadOnlyHandSkeletonJointList',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_read_only_hand_skeleton_joint_list.html',1,'Oculus::Interaction::Input']]],
  ['irelativetoref_218',['IRelativeToRef',['../interface_oculus_1_1_interaction_1_1_i_relative_to_ref.html',1,'Oculus::Interaction']]],
  ['iremotedrawable_219',['IRemoteDrawable',['../interface_oculus_1_1_interaction_1_1_editor_1_1_i_remote_drawable.html',1,'Oculus::Interaction::Editor']]],
  ['irequest_220',['IRequest',['../interface_meta_1_1_wit_ai_1_1_i_request.html',1,'Meta::WitAi']]],
  ['ireticledata_221',['IReticleData',['../interface_oculus_1_1_interaction_1_1_distance_reticles_1_1_i_reticle_data.html',1,'Oculus::Interaction::DistanceReticles']]],
  ['irigidbodyref_222',['IRigidbodyRef',['../interface_oculus_1_1_interaction_1_1_i_rigidbody_ref.html',1,'Oculus::Interaction']]],
  ['iselector_223',['ISelector',['../interface_oculus_1_1_interaction_1_1_i_selector.html',1,'Oculus::Interaction']]],
  ['iserviceevents_224',['IServiceEvents',['../interface_oculus_1_1_voice_1_1_dictation_1_1_bindings_1_1_android_1_1_i_service_events.html',1,'Oculus::Voice::Dictation::Bindings::Android']]],
  ['iskeletonmapping_225',['ISkeletonMapping',['../interface_oculus_1_1_interaction_1_1_body_1_1_input_1_1_i_skeleton_mapping.html',1,'Oculus::Interaction::Body::Input']]],
  ['isnapposedelegate_226',['ISnapPoseDelegate',['../interface_oculus_1_1_interaction_1_1_i_snap_pose_delegate.html',1,'Oculus::Interaction']]],
  ['ispeakertextpostprocessor_227',['ISpeakerTextPostprocessor',['../interface_meta_1_1_wit_ai_1_1_t_t_s_1_1_interfaces_1_1_i_speaker_text_postprocessor.html',1,'Meta::WitAi::TTS::Interfaces']]],
  ['ispeakertextpreprocessor_228',['ISpeakerTextPreprocessor',['../interface_meta_1_1_wit_ai_1_1_t_t_s_1_1_interfaces_1_1_i_speaker_text_preprocessor.html',1,'Meta::WitAi::TTS::Interfaces']]],
  ['ispeecheventprovider_229',['ISpeechEventProvider',['../interface_meta_1_1_wit_ai_1_1_speech_1_1_i_speech_event_provider.html',1,'Meta::WitAi::Speech']]],
  ['ispeechevents_230',['ISpeechEvents',['../interface_meta_1_1_wit_ai_1_1_interfaces_1_1_i_speech_events.html',1,'Meta::WitAi::Interfaces']]],
  ['istringreference_231',['IStringReference',['../interface_meta_1_1_wit_ai_1_1_data_1_1_value_references_1_1_i_string_reference.html',1,'Meta::WitAi::Data::ValueReferences']]],
  ['istylehandler_232',['IStyleHandler',['../interface_o_v_r_passthrough_layer_1_1_i_style_handler.html',1,'OVRPassthroughLayer']]],
  ['isurface_233',['ISurface',['../interface_oculus_1_1_interaction_1_1_surfaces_1_1_i_surface.html',1,'Oculus::Interaction::Surfaces']]],
  ['isurfacepatch_234',['ISurfacePatch',['../interface_oculus_1_1_interaction_1_1_surfaces_1_1_i_surface_patch.html',1,'Oculus::Interaction::Surfaces']]],
  ['itelemetryeventsprovider_235',['ITelemetryEventsProvider',['../interface_meta_1_1_wit_ai_1_1_i_telemetry_events_provider.html',1,'Meta::WitAi']]],
  ['itemrect_236',['ItemRect',['../class_o_v_r_1_1_audio_manager_inspector_1_1_item_rect.html',1,'OVR::AudioManagerInspector']]],
  ['itemscope_237',['ItemScope',['../struct_o_v_r_object_pool_1_1_item_scope.html',1,'OVRObjectPool']]],
  ['itokenvalidationprovider_238',['ITokenValidationProvider',['../interface_meta_1_1_wit_ai_1_1_wit_auth_utility_1_1_i_token_validation_provider.html',1,'Meta::WitAi::WitAuthUtility']]],
  ['itrackingtoworldtransformer_239',['ITrackingToWorldTransformer',['../interface_oculus_1_1_interaction_1_1_input_1_1_i_tracking_to_world_transformer.html',1,'Oculus::Interaction::Input']]],
  ['itranscriptionevent_240',['ITranscriptionEvent',['../interface_meta_1_1_wit_ai_1_1_interfaces_1_1_i_transcription_event.html',1,'Meta::WitAi::Interfaces']]],
  ['itranscriptioneventprovider_241',['ITranscriptionEventProvider',['../interface_meta_1_1_wit_ai_1_1_interfaces_1_1_i_transcription_event_provider.html',1,'Meta::WitAi::Interfaces']]],
  ['itranscriptionprovider_242',['ITranscriptionProvider',['../interface_meta_1_1_wit_ai_1_1_interfaces_1_1_i_transcription_provider.html',1,'Meta::WitAi::Interfaces']]],
  ['itranscriptionrequest_243',['ITranscriptionRequest',['../interface_meta_1_1_voice_1_1_i_transcription_request.html',1,'Meta::Voice']]],
  ['itranscriptionrequestevents_244',['ITranscriptionRequestEvents',['../interface_meta_1_1_voice_1_1_i_transcription_request_events.html',1,'Meta::Voice']]],
  ['itranscriptionrequestoptions_245',['ITranscriptionRequestOptions',['../interface_meta_1_1_voice_1_1_i_transcription_request_options.html',1,'Meta::Voice']]],
  ['itranscriptionrequestresults_246',['ITranscriptionRequestResults',['../interface_meta_1_1_voice_1_1_i_transcription_request_results.html',1,'Meta::Voice']]],
  ['itransformer_247',['ITransformer',['../interface_oculus_1_1_interaction_1_1_i_transformer.html',1,'Oculus::Interaction']]],
  ['itransformfeaturestateprovider_248',['ITransformFeatureStateProvider',['../interface_oculus_1_1_interaction_1_1_pose_detection_1_1_i_transform_feature_state_provider.html',1,'Oculus::Interaction::PoseDetection']]],
  ['ittsdiskcachehandler_249',['ITTSDiskCacheHandler',['../interface_meta_1_1_wit_ai_1_1_t_t_s_1_1_interfaces_1_1_i_t_t_s_disk_cache_handler.html',1,'Meta::WitAi::TTS::Interfaces']]],
  ['ittsphraseprovider_250',['ITTSPhraseProvider',['../interface_meta_1_1_wit_ai_1_1_t_t_s_1_1_utilities_1_1_i_t_t_s_phrase_provider.html',1,'Meta::WitAi::TTS::Utilities']]],
  ['ittsruntimecachehandler_251',['ITTSRuntimeCacheHandler',['../interface_meta_1_1_wit_ai_1_1_t_t_s_1_1_interfaces_1_1_i_t_t_s_runtime_cache_handler.html',1,'Meta::WitAi::TTS::Interfaces']]],
  ['ittsvoiceprovider_252',['ITTSVoiceProvider',['../interface_meta_1_1_wit_ai_1_1_t_t_s_1_1_interfaces_1_1_i_t_t_s_voice_provider.html',1,'Meta::WitAi::TTS::Interfaces']]],
  ['ittswebhandler_253',['ITTSWebHandler',['../interface_meta_1_1_wit_ai_1_1_t_t_s_1_1_interfaces_1_1_i_t_t_s_web_handler.html',1,'Meta::WitAi::TTS::Interfaces']]],
  ['iupdatedriver_254',['IUpdateDriver',['../interface_oculus_1_1_interaction_1_1_i_update_driver.html',1,'Oculus::Interaction']]],
  ['ivcbindingevents_255',['IVCBindingEvents',['../interface_oculus_1_1_voice_1_1_bindings_1_1_android_1_1_i_v_c_binding_events.html',1,'Oculus::Voice::Bindings::Android']]],
  ['ivelocitycalculator_256',['IVelocityCalculator',['../interface_oculus_1_1_interaction_1_1_throw_1_1_i_velocity_calculator.html',1,'Oculus::Interaction::Throw']]],
  ['ivoiceactivationhandler_257',['IVoiceActivationHandler',['../interface_meta_1_1_wit_ai_1_1_i_voice_activation_handler.html',1,'Meta::WitAi']]],
  ['ivoiceeventprovider_258',['IVoiceEventProvider',['../interface_meta_1_1_wit_ai_1_1_i_voice_event_provider.html',1,'Meta::WitAi']]],
  ['ivoicerequest_259',['IVoiceRequest',['../interface_meta_1_1_voice_1_1_i_voice_request.html',1,'Meta::Voice']]],
  ['ivoicerequestevents_260',['IVoiceRequestEvents',['../interface_meta_1_1_voice_1_1_i_voice_request_events.html',1,'Meta::Voice']]],
  ['ivoicerequestoptions_261',['IVoiceRequestOptions',['../interface_meta_1_1_voice_1_1_i_voice_request_options.html',1,'Meta::Voice']]],
  ['ivoicerequestresults_262',['IVoiceRequestResults',['../interface_meta_1_1_voice_1_1_i_voice_request_results.html',1,'Meta::Voice']]],
  ['ivoicesdklogger_263',['IVoiceSDKLogger',['../interface_oculus_1_1_voice_1_1_core_1_1_bindings_1_1_interfaces_1_1_i_voice_s_d_k_logger.html',1,'Oculus::Voice::Core::Bindings::Interfaces']]],
  ['ivoiceservice_264',['IVoiceService',['../interface_meta_1_1_wit_ai_1_1_i_voice_service.html',1,'Meta::WitAi']]],
  ['ivoippcmsource_265',['IVoipPCMSource',['../interface_oculus_1_1_platform_1_1_i_voip_p_c_m_source.html',1,'Oculus::Platform']]],
  ['ivrapplications_266',['IVRApplications',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_applications.html',1,'OVR::OpenVR']]],
  ['ivrchaperone_267',['IVRChaperone',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_chaperone.html',1,'OVR::OpenVR']]],
  ['ivrchaperonesetup_268',['IVRChaperoneSetup',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_chaperone_setup.html',1,'OVR::OpenVR']]],
  ['ivrcompositor_269',['IVRCompositor',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_compositor.html',1,'OVR::OpenVR']]],
  ['ivrdrivermanager_270',['IVRDriverManager',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_driver_manager.html',1,'OVR::OpenVR']]],
  ['ivrequeststreamable_271',['IVRequestStreamable',['../interface_meta_1_1_wit_ai_1_1_requests_1_1_i_v_request_streamable.html',1,'Meta::WitAi::Requests']]],
  ['ivrextendeddisplay_272',['IVRExtendedDisplay',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_extended_display.html',1,'OVR::OpenVR']]],
  ['ivrinput_273',['IVRInput',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_input.html',1,'OVR::OpenVR']]],
  ['ivriobuffer_274',['IVRIOBuffer',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_i_o_buffer.html',1,'OVR::OpenVR']]],
  ['ivrnotifications_275',['IVRNotifications',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_notifications.html',1,'OVR::OpenVR']]],
  ['ivroverlay_276',['IVROverlay',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_overlay.html',1,'OVR::OpenVR']]],
  ['ivrrendermodels_277',['IVRRenderModels',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_render_models.html',1,'OVR::OpenVR']]],
  ['ivrresources_278',['IVRResources',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_resources.html',1,'OVR::OpenVR']]],
  ['ivrscreenshots_279',['IVRScreenshots',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_screenshots.html',1,'OVR::OpenVR']]],
  ['ivrsettings_280',['IVRSettings',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_settings.html',1,'OVR::OpenVR']]],
  ['ivrspatialanchors_281',['IVRSpatialAnchors',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_spatial_anchors.html',1,'OVR::OpenVR']]],
  ['ivrsystem_282',['IVRSystem',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_system.html',1,'OVR::OpenVR']]],
  ['ivrtrackedcamera_283',['IVRTrackedCamera',['../struct_o_v_r_1_1_open_v_r_1_1_i_v_r_tracked_camera.html',1,'OVR::OpenVR']]],
  ['iwitbytedatareadyhandler_284',['IWitByteDataReadyHandler',['../interface_meta_1_1_wit_ai_1_1_events_1_1_i_wit_byte_data_ready_handler.html',1,'Meta::WitAi::Events']]],
  ['iwitbytedatasenthandler_285',['IWitByteDataSentHandler',['../interface_meta_1_1_wit_ai_1_1_events_1_1_i_wit_byte_data_sent_handler.html',1,'Meta::WitAi::Events']]],
  ['iwitconfigurationprovider_286',['IWitConfigurationProvider',['../interface_meta_1_1_wit_ai_1_1_interfaces_1_1_i_wit_configuration_provider.html',1,'Meta::WitAi::Interfaces']]],
  ['iwitrequestconfiguration_287',['IWitRequestConfiguration',['../interface_meta_1_1_wit_ai_1_1_i_wit_request_configuration.html',1,'Meta::WitAi']]],
  ['iwitrequestendpointinfo_288',['IWitRequestEndpointInfo',['../interface_meta_1_1_wit_ai_1_1_i_wit_request_endpoint_info.html',1,'Meta::WitAi']]],
  ['iwitrequestprovider_289',['IWitRequestProvider',['../interface_meta_1_1_wit_ai_1_1_interfaces_1_1_i_wit_request_provider.html',1,'Meta::WitAi::Interfaces']]],
  ['iwitruntimeconfigprovider_290',['IWitRuntimeConfigProvider',['../interface_meta_1_1_wit_ai_1_1_i_wit_runtime_config_provider.html',1,'Meta::WitAi']]]
];
