VR_Test: OVRSpatialAnchor Class Reference
OVRSpatialAnchor Class Reference
Represents a spatial anchor.
Classes
class Development
struct EraseOptions
Represents options for erasing OVRSpatialAnchor.
struct InvertedCapture
This struct helped inverting callback signature when using OVRTasks. OVRTasks expect Action{TResult, TCapture} signature but public API requires Action{TCapture, TResult} signature.
struct LoadOptions
Options for loading unbound spatial anchors used by OVRSpatialAnchor.LoadUnboundAnchors.
struct MultiAnchorDelegatePair
struct SaveOptions
Represents options for saving OVRSpatialAnchor.
struct UnboundAnchor
A spatial anchor that has not been bound to an OVRSpatialAnchor.
Public Types
enum OperationResult {
Success = 0 , Failure = -1000 , Failure_SpaceCloudStorageDisabled = -2000 , Failure_SpaceMappingInsufficient = -2001 ,
Failure_SpaceLocalizationFailed = -2002 , Failure_SpaceNetworkTimeout = -2003 , Failure_SpaceNetworkRequestFailed = -2004
}
Public Member Functions
void InitializeFromExisting (OVRSpace space, Guid uuid)
Initializes this component from an existing space handle and uuid, e.g., the result of a call to OVRPlugin.QuerySpaces.
void Save (Action< OVRSpatialAnchor, bool > onComplete=null)
Saves the OVRSpatialAnchor to local persistent storage.
void Save (SaveOptions saveOptions, Action< OVRSpatialAnchor, bool > onComplete=null)
Saves the OVRSpatialAnchor with specified SaveOptions.
OVRTask< bool > SaveAsync ()
Saves the OVRSpatialAnchor with specified SaveOptions.
OVRTask< bool > SaveAsync (SaveOptions saveOptions)
Saves the OVRSpatialAnchor with specified SaveOptions.
void Share (OVRSpaceUser user, Action< OperationResult > onComplete=null)
Shares the anchor to an OVRSpaceUser. The specified user will be able to download, track, and share specified anchors.
OVRTask< OperationResult > ShareAsync (OVRSpaceUser user)
Shares the anchor to an OVRSpaceUser. The specified user will be able to download, track, and share specified anchors.
void Share (OVRSpaceUser user1, OVRSpaceUser user2, Action< OperationResult > onComplete=null)
Shares the anchor with two OVRSpaceUser. Specified users will be able to download, track, and share specified anchors.
OVRTask< OperationResult > ShareAsync (OVRSpaceUser user1, OVRSpaceUser user2)
Shares the anchor to an OVRSpaceUser. The specified user will be able to download, track, and share specified anchors.
void Share (OVRSpaceUser user1, OVRSpaceUser user2, OVRSpaceUser user3, Action< OperationResult > onComplete=null)
Shares the anchor with three OVRSpaceUser. Specified users will be able to download, track, and share specified anchors.
OVRTask< OperationResult > ShareAsync (OVRSpaceUser user1, OVRSpaceUser user2, OVRSpaceUser user3)
Shares the anchor to an OVRSpaceUser. The specified user will be able to download, track, and share specified anchors.
void Share (OVRSpaceUser user1, OVRSpaceUser user2, OVRSpaceUser user3, OVRSpaceUser user4, Action< OperationResult > onComplete=null)
Shares the anchor with four OVRSpaceUser. Specified users will be able to download, track, and share specified anchors.
OVRTask< OperationResult > ShareAsync (OVRSpaceUser user1, OVRSpaceUser user2, OVRSpaceUser user3, OVRSpaceUser user4)
Shares the anchor to an OVRSpaceUser. The specified user will be able to download, track, and share specified anchors.
void Share (IEnumerable< OVRSpaceUser > users, Action< OperationResult > onComplete=null)
Shares the anchor to a collection of OVRSpaceUser. Specified users will be able to download, track, and share specified anchors.
OVRTask< OperationResult > ShareAsync (IEnumerable< OVRSpaceUser > users)
Shares the anchor to an OVRSpaceUser. The specified user will be able to download, track, and share specified anchors.
void Erase (Action< OVRSpatialAnchor, bool > onComplete=null)
Erases the OVRSpatialAnchor from persistent storage.
void Erase (EraseOptions eraseOptions, Action< OVRSpatialAnchor, bool > onComplete=null)
Erases the OVRSpatialAnchor from specified storage.
OVRTask< bool > EraseAsync ()
Erases the OVRSpatialAnchor from specified storage.
OVRTask< bool > EraseAsync (EraseOptions eraseOptions)
Erases the OVRSpatialAnchor from specified storage.
Static Public Member Functions
static void Save (ICollection< OVRSpatialAnchor > anchors, SaveOptions saveOptions, Action< ICollection< OVRSpatialAnchor >, OperationResult > onComplete=null)
Saves a collection of OVRSpatialAnchor to specified storage.
static void Share (ICollection< OVRSpatialAnchor > anchors, ICollection< OVRSpaceUser > users, Action< ICollection< OVRSpatialAnchor >, OperationResult > onComplete=null)
Shares a collection of OVRSpatialAnchor to specified users. Specified users will be able to download, track, and share specified anchors.
static bool LoadUnboundAnchors (LoadOptions options, Action< UnboundAnchor[]> onComplete)
Performs a query for anchors with the specified options .
static OVRTask< UnboundAnchor[]> LoadUnboundAnchorsAsync (LoadOptions options)
Performs a query for anchors with the specified options .
Properties
OVRSpace Space [get, private set]
The space associated with the spatial anchor.
Guid Uuid [get, private set]
The UUID associated with the spatial anchor.
bool Created [get]
Checks whether the spatial anchor is created.
bool PendingCreation [get]
Checks whether the spatial anchor is pending creation.
bool Localized [get]
Checks whether the spatial anchor is localized.
Events
Action< OperationResult > OnLocalize
Event that is dispatched when the localization process finishes.
Private Types
enum MultiAnchorActionType { Save , Share }
Private Member Functions
OVRTask< OperationResult > ShareAsyncInternal (List< OVRSpaceUser > users)
List< OVRSpatialAnchor > GetListToStoreTheShareRequest (List< OVRSpaceUser > users)
void InitializeUnchecked (OVRSpace space, Guid uuid)
void Start ()
void Update ()
void LateUpdate ()
void OnDestroy ()
OVRPose GetTrackingSpacePose ()
void CreateSpatialAnchor ()
void UpdateTransform ()
Static Private Member Functions
static NativeArray< ulong > ToNativeArray (ICollection< OVRSpatialAnchor > anchors)
static List< OVRSpatialAnchor > CopyAnchorListIntoListFromPool (IEnumerable< OVRSpatialAnchor > anchorList)
static bool AreSortedUserListsEqual (IReadOnlyList< OVRSpaceUser > sortedList1, IReadOnlyList< OVRSpaceUser > sortedList2)
static void ThrowIfBound (Guid uuid)
static void SaveBatchAnchors ()
static void ShareBatchAnchors ()
static bool TryExtractValue< TKey, TValue > (Dictionary< TKey, TValue > dict, TKey key, out TValue value)
static void InitializeOnLoad ()
static void InvokeMultiAnchorDelegate (ulong requestId, OperationResult result, MultiAnchorActionType actionType)
static void OnSpatialAnchorCreateComplete (ulong requestId, bool success, OVRSpace space, Guid uuid)
static void OnSpaceSaveComplete (ulong requestId, OVRSpace space, bool result, Guid uuid)
static void OnSpaceEraseComplete (ulong requestId, bool result, Guid uuid, OVRPlugin.SpaceStorageLocation location)
static void OnSpaceQueryComplete (ulong requestId, bool queryResult)
static void PopulateUnbound (Guid uuid, UInt64 space)
static void OnSpaceSetComponentStatusComplete (ulong requestId, bool result, OVRSpace space, Guid uuid, OVRPlugin.SpaceComponentType componentType, bool enabled)
static void OnSpaceListSaveComplete (ulong requestId, OperationResult result)
static void OnShareSpacesComplete (ulong requestId, OperationResult result)
Private Attributes
bool _startCalled
ulong _requestId
readonly SaveOptions _defaultSaveOptions
readonly EraseOptions _defaultEraseOptions
Static Private Attributes
static readonly Dictionary< ulong, OVRSpatialAnchor > CreationRequests
static readonly Dictionary< OVRSpace.StorageLocation, List< OVRSpatialAnchor > > SaveRequests
static readonly Dictionary< OVRSpatialAnchor, Guid > AsyncRequestTaskIds
static readonly List<(List< OVRSpaceUser >, List< OVRSpatialAnchor >)> ShareRequests
static readonly Dictionary< ulong, MultiAnchorDelegatePair > MultiAnchorCompletionDelegates
static readonly List< UnboundAnchor > UnboundAnchorBuffer = new List<UnboundAnchor>()
static readonly OVRPlugin.SpaceComponentType[] ComponentTypeBuffer = new OVRPlugin.SpaceComponentType[32]
Detailed Description
Represents a spatial anchor.
This component can be used in two ways: to create a new spatial anchor or to bind to an existing spatial anchor.
To create a new spatial anchor, simply add this component to any GameObject. The transform of the GameObject is used to create a new spatial anchor in the Oculus Runtime. Afterwards, the GameObject's transform will be updated automatically. The creation operation is asynchronous, and, if it fails, this component will be destroyed.
To load previously saved anchors and bind them to an OVRSpatialAnchor, see LoadUnboundAnchors.
Definition at line 45 of file OVRSpatialAnchor.cs.
Member Enumeration Documentation
MultiAnchorActionType
enum OVRSpatialAnchor.MultiAnchorActionType private
Definition at line 1474 of file OVRSpatialAnchor.cs.
    {
        Save,
        Share
    }
OperationResult
enum OVRSpatialAnchor.OperationResult
Enumerator
Success
Operation succeeded.
Failure
Operation failed.
Failure_SpaceCloudStorageDisabled
Saving anchors to cloud storage is not permitted by the user.
Failure_SpaceMappingInsufficient
The user was able to download the anchors, but the device was unable to localize itself in the spatial data received from the sharing device.
Failure_SpaceLocalizationFailed
The user was able to download the anchors, but the device was unable to localize them.
Failure_SpaceNetworkTimeout
Network operation timed out.
Failure_SpaceNetworkRequestFailed
Network operation failed.
Definition at line 1562 of file OVRSpatialAnchor.cs.
    {
        Success = 0,
        Failure = -1000,
        Failure_SpaceCloudStorageDisabled = -2000,
        Failure_SpaceMappingInsufficient = -2001,
        Failure_SpaceLocalizationFailed = -2002,
        Failure_SpaceNetworkTimeout = -2003,
        Failure_SpaceNetworkRequestFailed = -2004,
    }
Constructor & Destructor Documentation
OVRSpatialAnchor()
static OVRSpatialAnchor.OVRSpatialAnchor () static private
Definition at line 889 of file OVRSpatialAnchor.cs.
    {
        OVRManager.SpatialAnchorCreateComplete += OnSpatialAnchorCreateComplete;
        OVRManager.SpaceSaveComplete += OnSpaceSaveComplete;
        OVRManager.SpaceListSaveComplete += OnSpaceListSaveComplete;
        OVRManager.ShareSpacesComplete += OnShareSpacesComplete;
        OVRManager.SpaceEraseComplete += OnSpaceEraseComplete;
        OVRManager.SpaceQueryComplete += OnSpaceQueryComplete;
        OVRManager.SpaceSetComponentStatusComplete += OnSpaceSetComponentStatusComplete;
    }
Member Function Documentation
AreSortedUserListsEqual()
static bool OVRSpatialAnchor.AreSortedUserListsEqual (IReadOnlyList< OVRSpaceUser > sortedList1, IReadOnlyList< OVRSpaceUser > sortedList2) static private
Definition at line 601 of file OVRSpatialAnchor.cs.
    {
        if (sortedList1.Count != sortedList2.Count)
        {
            return false;
        }
        for (var i = 0; i < sortedList1.Count; i++)
        {
            if (sortedList1[i].Id != sortedList2[i].Id)
            {
                return false;
            }
        }
        return true;
    }
CopyAnchorListIntoListFromPool()
static List< OVRSpatialAnchor > OVRSpatialAnchor.CopyAnchorListIntoListFromPool (IEnumerable< OVRSpatialAnchor > anchorList) static private
Definition at line 295 of file OVRSpatialAnchor.cs.
    {
        var poolList = OVRObjectPool.List<OVRSpatialAnchor>();
        poolList.AddRange(anchorList);
        return poolList;
    }
CreateSpatialAnchor()
void OVRSpatialAnchor.CreateSpatialAnchor () private
Definition at line 791 of file OVRSpatialAnchor.cs.
    {
        var created = OVRPlugin.CreateSpatialAnchor(new OVRPlugin.SpatialAnchorCreateInfo
        {
            BaseTracking = OVRPlugin.GetTrackingOriginType(),
            PoseInSpace = GetTrackingSpacePose().ToPosef(),
            Time = OVRPlugin.GetTimeInSeconds(),
        }, out _requestId);
        OVRTelemetry.Client.MarkerStart(OVRTelemetryConstants.Scene.MarkerId.SpatialAnchorCreate,
            _requestId.GetHashCode());
        if (created)
        {
            Development.LogRequest(_requestId, $"Creating spatial anchor...");
            CreationRequests[_requestId] = this;
        }
        else
        {
            OVRTelemetry.Client.MarkerEnd(OVRTelemetryConstants.Scene.MarkerId.SpatialAnchorCreate,
                OVRPlugin.Qpl.ResultType.Fail, _requestId.GetHashCode());
            Development.LogError(
                $"{nameof(OVRPlugin)}.{nameof(OVRPlugin.CreateSpatialAnchor)} failed. Destroying {nameof(OVRSpatialAnchor)} component.");
            Destroy(this);
        }
    }
Erase() [1/2]
void OVRSpatialAnchor.Erase (Action< OVRSpatialAnchor, bool > onComplete = null)
Erases the OVRSpatialAnchor from persistent storage.
This method is asynchronous. Use onComplete to be notified of completion. Erasing an OVRSpatialAnchor does not destroy the anchor.
Parameters
onComplete Invoked when the erase operation completes. May be null. Parameters are
OVRSpatialAnchor: The anchor being erased.
bool: A value indicating whether the erase operation succeeded.
Definition at line 632 of file OVRSpatialAnchor.cs.
    {
        Erase(_defaultEraseOptions, onComplete);
    }
References Erase().
Erase() [2/2]
void OVRSpatialAnchor.Erase (EraseOptions eraseOptions, Action< OVRSpatialAnchor, bool > onComplete = null)
Erases the OVRSpatialAnchor from specified storage.
This method is asynchronous. Use onComplete to be notified of completion. Erasing an OVRSpatialAnchor does not destroy the anchor.
Parameters
eraseOptions Options how the anchor should be erased.
onComplete Invoked when the erase operation completes. May be null. Parameters are
OVRSpatialAnchor: The anchor being erased.
bool: A value indicating whether the erase operation succeeded.
Definition at line 650 of file OVRSpatialAnchor.cs.
    {
        var task = EraseAsync(eraseOptions);
        if (onComplete != null)
        {
            InvertedCapture<bool, OVRSpatialAnchor>.ContinueTaskWith(task, onComplete, this);
        }
    }
References EraseAsync().
EraseAsync() [1/2]
OVRTask< bool > OVRSpatialAnchor.EraseAsync ()
Erases the OVRSpatialAnchor from specified storage.
This method is asynchronous; use the returned OVRTask<TResult> to be notified of completion. Erasing an OVRSpatialAnchor does not destroy the anchor.
Returns
An OVRTask<TResult> with a boolean type parameter indicating the success of the erase operation.
EraseAsync() [2/2]
OVRTask< bool > OVRSpatialAnchor.EraseAsync (EraseOptions eraseOptions)
Erases the OVRSpatialAnchor from specified storage.
This method is asynchronous; use the returned OVRTask<TResult> to be notified of completion. Erasing an OVRSpatialAnchor does not destroy the anchor.
Parameters
eraseOptions Options for how the anchor should be erased.
Returns
An OVRTask<TResult> with a boolean type parameter indicating the success of the erase operation.
GetListToStoreTheShareRequest()
List< OVRSpatialAnchor > OVRSpatialAnchor.GetListToStoreTheShareRequest (List< OVRSpaceUser > users) private
Definition at line 581 of file OVRSpatialAnchor.cs.
    {
        users.Sort((x, y) => x.Id.CompareTo(y.Id));
        foreach (var (shareRequestUsers, shareRequestAnchors) in ShareRequests)
        {
            if (!AreSortedUserListsEqual(users, shareRequestUsers))
            {
                continue;
            }
            // reuse the current request
            return shareRequestAnchors;
        }
        // add a new request
        var anchorList = OVRObjectPool.List<OVRSpatialAnchor>();
        ShareRequests.Add((users, anchorList));
        return anchorList;
    }
GetTrackingSpacePose()
OVRPose OVRSpatialAnchor.GetTrackingSpacePose () private
Definition at line 779 of file OVRSpatialAnchor.cs.
    {
        var mainCamera = Camera.main;
        if (mainCamera)
        {
            return transform.ToTrackingSpacePose(mainCamera);
        }
        Development.LogWarning($"No main camera found. Using world-space pose.");
        return transform.ToOVRPose(isLocal: false);
    }
InitializeFromExisting()
void OVRSpatialAnchor.InitializeFromExisting (OVRSpace space, Guid uuid)
Initializes this component from an existing space handle and uuid, e.g., the result of a call to OVRPlugin.QuerySpaces.
This method associates the component with an existing spatial anchor, for example, the one that was saved in a previous session. Do not call this method to create a new spatial anchor.
If you call this method, you must do so prior to the component's Start method. You cannot change the spatial anchor associated with this component after that.
Parameters
space The existing OVRSpace to associate with this spatial anchor.
uuid The universally unique identifier to associate with this spatial anchor.
Exceptions
InvalidOperationException Thrown if Start has already been called on this component.
ArgumentException Thrown if space is not OVRSpace.Valid.
Definition at line 123 of file OVRSpatialAnchor.cs.
    {
        if (_startCalled)
            throw new InvalidOperationException(
                $"Cannot call {nameof(InitializeFromExisting)} after {nameof(Start)}. This must be set once upon creation.");
        try
        {
            if (!space.Valid)
                throw new ArgumentException($"Invalid space {space}.", nameof(space));
            ThrowIfBound(uuid);
        }
        catch
        {
            Destroy(this);
            throw;
        }
        InitializeUnchecked(space, uuid);
    }
References OVRSpace.Valid.
InitializeOnLoad()
static void OVRSpatialAnchor.InitializeOnLoad () static private
Definition at line 881 of file OVRSpatialAnchor.cs.
    {
        CreationRequests.Clear();
        MultiAnchorCompletionDelegates.Clear();
        UnboundAnchorBuffer.Clear();
        SpatialAnchors.Clear();
    }
InitializeUnchecked()
void OVRSpatialAnchor.InitializeUnchecked (OVRSpace space, Guid uuid) private
Definition at line 697 of file OVRSpatialAnchor.cs.
    {
        SpatialAnchors.Add(uuid, this);
        _requestId = 0;
        Space = space;
        Uuid = uuid;
        OVRPlugin.SetSpaceComponentStatus(Space, OVRPlugin.SpaceComponentType.Locatable, true, 0, out _);
        OVRPlugin.SetSpaceComponentStatus(Space, OVRPlugin.SpaceComponentType.Storable, true, 0, out _);
        OVRPlugin.SetSpaceComponentStatus(Space, OVRPlugin.SpaceComponentType.Sharable, true, 0, out _);
        // Try to update the pose as soon as we can.
        UpdateTransform();
    }
InvokeMultiAnchorDelegate()
static void OVRSpatialAnchor.InvokeMultiAnchorDelegate (ulong requestId, OperationResult result, MultiAnchorActionType actionType) static private
Definition at line 900 of file OVRSpatialAnchor.cs.
    {
        if (!TryExtractValue(MultiAnchorCompletionDelegates, requestId, out var value))
        {
            return;
        }
        if (actionType == MultiAnchorActionType.Save)
        {
            OVRTelemetry.Client.MarkerEnd(OVRTelemetryConstants.Scene.MarkerId.SpatialAnchorSave,
                result == OperationResult.Success ? OVRPlugin.Qpl.ResultType.Success : OVRPlugin.Qpl.ResultType.Fail,
                requestId.GetHashCode());
        }
        value.Delegate?.Invoke(value.Anchors, result);
        try
        {
            foreach (var anchor in value.Anchors)
            {
                switch (actionType)
                {
                    case MultiAnchorActionType.Save:
                    {
                        if (result != OperationResult.Success)
{
                            Development.LogError(
                                $"[{anchor.Uuid}] {nameof(OVRPlugin)}.{nameof(OVRPlugin.SaveSpaceList)} failed with result: {result}.");
                        }
                        if (AsyncRequestTaskIds.TryGetValue(anchor, out var taskId))
{
                            AsyncRequestTaskIds.Remove(anchor);
                            OVRTask.GetExisting<bool>(taskId).SetResult(result == OperationResult.Success);
                        }
                        break;
                    }
                    case MultiAnchorActionType.Share:
                    {
                        if (result != OperationResult.Success)
{
                            Development.LogError(
                                $"[{anchor.Uuid}] {nameof(OVRPlugin)}.{nameof(OVRPlugin.ShareSpaces)} failed with result: {result}.");
                        }
                        if (AsyncRequestTaskIds.TryGetValue(anchor, out var taskId))
{
                            AsyncRequestTaskIds.Remove(anchor);
                            OVRTask.GetExisting<OperationResult>(taskId).SetResult(result);
                        }
                        break;
                    }
                    default:
                        throw new ArgumentOutOfRangeException(nameof(actionType), actionType, null);
                }
            }
        }
        finally
        {
            OVRObjectPool.Return(value.Anchors);
        }
    }
LateUpdate()
void OVRSpatialAnchor.LateUpdate () private
Definition at line 733 of file OVRSpatialAnchor.cs.
    {
        SaveBatchAnchors();
        ShareBatchAnchors();
    }
LoadUnboundAnchors()
static bool OVRSpatialAnchor.LoadUnboundAnchors (LoadOptions options, Action< UnboundAnchor[]> onComplete) static
Performs a query for anchors with the specified options .
Use this method to find anchors that were previously persisted with Save(Action<OVRSpatialAnchor, bool>. The query is asynchronous; when the query completes, onComplete is invoked with an array of UnboundAnchors for which tracking may be requested.
Parameters
options Options that affect the query.
onComplete A delegate invoked when the query completes. The delegate accepts one argument:
UnboundAnchor[]: An array of unbound anchors.
If the operation fails, onComplete is invoked with null.
Returns
Returns true if the operation could be initiated; otherwise false.
Exceptions
ArgumentNullException Thrown if onComplete is null.
InvalidOperationException Thrown if LoadOptions.Uuids of options is null.
Definition at line 1316 of file OVRSpatialAnchor.cs.
    {
        var task = LoadUnboundAnchorsAsync(options);
        task.ContinueWith(onComplete);
        return task.IsPending;
    }
References LoadUnboundAnchorsAsync().
LoadUnboundAnchorsAsync()
static OVRTask< UnboundAnchor[]> OVRSpatialAnchor.LoadUnboundAnchorsAsync (LoadOptions options) static
Performs a query for anchors with the specified options .
Use this method to find anchors that were previously persisted with Save(Action<OVRSpatialAnchor, bool>. The query is asynchronous; when the query completes, the returned OVRTask<TResult> will contain an array of UnboundAnchors for which tracking may be requested.
Parameters
options Options that affect the query.
Returns
An OVRTask<TResult> with a T:UnboundAnchor[] type parameter containing the loaded unbound anchors.
Exceptions
InvalidOperationException Thrown if LoadOptions.Uuids of options is null.
Definition at line 1337 of file OVRSpatialAnchor.cs.
    {
        if (options.Uuids == null)
        {
            throw new InvalidOperationException($"{nameof(LoadOptions)}.{nameof(LoadOptions.Uuids)} must not be null.");
        }
        if (!options.ToQueryOptions().TryQuerySpaces(out var requestId))
        {
            Development.LogError($"{nameof(OVRPlugin.QuerySpaces)} failed.");
            return OVRTask.FromResult<UnboundAnchor[]>(null);
        }
        Development.LogRequest(requestId, $"{nameof(OVRPlugin.QuerySpaces)}: Query created.");
        return OVRTask.FromRequest<UnboundAnchor[]>(requestId);
    }
References OVRSpatialAnchor.LoadOptions.Uuids.
OnDestroy()
void OVRSpatialAnchor.OnDestroy () private
Definition at line 769 of file OVRSpatialAnchor.cs.
    {
        if (Space.Valid)
        {
            OVRPlugin.DestroySpace(Space);
        }
        SpatialAnchors.Remove(Uuid);
    }
OnShareSpacesComplete()
static void OVRSpatialAnchor.OnShareSpacesComplete (ulong requestId, OperationResult result) static private
Definition at line 1489 of file OVRSpatialAnchor.cs.
    {
        Development.LogRequestResult(requestId, result >= 0,
            $"Spaces shared.",
            $"Spaces share failed with error {result}.");
        InvokeMultiAnchorDelegate(requestId, result, MultiAnchorActionType.Share);
    }
OnSpaceEraseComplete()
static void OVRSpatialAnchor.OnSpaceEraseComplete (ulong requestId, bool result, Guid uuid, OVRPlugin::SpaceStorageLocation location) static private
Definition at line 1005 of file OVRSpatialAnchor.cs.
    {
        Development.LogRequestResult(requestId, result,
            $"[{uuid}] Erased.",
            $"[{uuid}] Erase failed.");
    }
OnSpaceListSaveComplete()
static void OVRSpatialAnchor.OnSpaceListSaveComplete (ulong requestId, OperationResult result) static private
Definition at line 1480 of file OVRSpatialAnchor.cs.
    {
        Development.LogRequestResult(requestId, result >= 0,
            $"Spaces saved.",
            $"Spaces save failed with error {result}.");
        InvokeMultiAnchorDelegate(requestId, result, MultiAnchorActionType.Save);
    }
OnSpaceQueryComplete()
static void OVRSpatialAnchor.OnSpaceQueryComplete (ulong requestId, bool queryResult) static private
Definition at line 1355 of file OVRSpatialAnchor.cs.
    {
        Development.LogRequestResult(requestId, queryResult,
            $"{nameof(OVRPlugin.QuerySpaces)}: Query succeeded.",
            $"{nameof(OVRPlugin.QuerySpaces)}: Query failed.");
        var hasPendingTask = OVRTask.GetExisting<UnboundAnchor[]>(requestId).IsPending;
        if (!hasPendingTask)
        {
            return;
        }
        OVRTelemetry.Client.MarkerEnd(OVRTelemetryConstants.Scene.MarkerId.SpatialAnchorQuery,
            queryResult ? OVRPlugin.Qpl.ResultType.Success : OVRPlugin.Qpl.ResultType.Fail,
            requestId.GetHashCode());
        if (!queryResult)
        {
            OVRTask.GetExisting<UnboundAnchor[]>(requestId).SetResult(null);
            return;
        }
        if (OVRPlugin.RetrieveSpaceQueryResults(requestId, out var results, Allocator.Temp))
        {
            Development.Log(
                $"{nameof(OVRPlugin.RetrieveSpaceQueryResults)}({requestId}): Retrieved {results.Length} results.");
        }
        else
        {
            Development.LogError(
                $"{nameof(OVRPlugin.RetrieveSpaceQueryResults)}({requestId}): Failed to retrieve results.");
            OVRTask.GetExisting<UnboundAnchor[]>(requestId).SetResult(null);
            return;
        }
        using var disposer = results;
        UnboundAnchorBuffer.Clear();
        foreach (var result in results)
        {
            PopulateUnbound(result.uuid, result.space);
        }
        Development.Log(
            $"Invoking callback with {UnboundAnchorBuffer.Count} unbound anchor{(UnboundAnchorBuffer.Count == 1 ? "" : "s")}.");
        var unboundAnchors = UnboundAnchorBuffer.Count == 0
            ? Array.Empty<UnboundAnchor>()
            : UnboundAnchorBuffer.ToArray();
        OVRTask.GetExisting<UnboundAnchor[]>(requestId).SetResult(unboundAnchors);
    }
OnSpaceSaveComplete()
static void OVRSpatialAnchor.OnSpaceSaveComplete (ulong requestId, OVRSpace space, bool result, Guid uuid) static private
Definition at line 998 of file OVRSpatialAnchor.cs.
    {
        Development.LogRequestResult(requestId, result,
            $"[{uuid}] Saved.",
            $"[{uuid}] Save failed.");
    }
OnSpaceSetComponentStatusComplete()
static void OVRSpatialAnchor.OnSpaceSetComponentStatusComplete (ulong requestId, bool result, OVRSpace space, Guid uuid, OVRPlugin::SpaceComponentType componentType, bool enabled) static private
Definition at line 1461 of file OVRSpatialAnchor.cs.
    {
        Development.LogRequestResult(requestId, result,
            $"[{uuid}] {componentType} {(enabled ? "enabled" : "disabled")}.",
            $"[{uuid}] Failed to set {componentType} status.");
        if (componentType == OVRPlugin.SpaceComponentType.Locatable && SpatialAnchors.TryGetValue(uuid, out var anchor))
        {
            anchor.OnLocalize?.Invoke(enabled ? OperationResult.Success : OperationResult.Failure);
        }
    }
OnSpatialAnchorCreateComplete()
static void OVRSpatialAnchor.OnSpatialAnchorCreateComplete (ulong requestId, bool success, OVRSpace space, Guid uuid) static private
Definition at line 966 of file OVRSpatialAnchor.cs.
    {
        Development.LogRequestResult(requestId, success,
            $"[{uuid}] Spatial anchor created.",
            $"Failed to create spatial anchor. Destroying {nameof(OVRSpatialAnchor)} component.");
        if (!TryExtractValue(CreationRequests, requestId, out var anchor)) return;
        OVRTelemetry.Client.MarkerEnd(OVRTelemetryConstants.Scene.MarkerId.SpatialAnchorCreate,
            success ? OVRPlugin.Qpl.ResultType.Success : OVRPlugin.Qpl.ResultType.Fail,
            requestId.GetHashCode());
        if (success && anchor)
        {
            // All good; complete setup of OVRSpatialAnchor component.
            anchor.InitializeUnchecked(space, uuid);
            return;
        }
        if (success && !anchor)
        {
            // Creation succeeded, but the OVRSpatialAnchor component was destroyed before the callback completed.
            OVRPlugin.DestroySpace(space);
        }
        else if (!success && anchor)
        {
            // The OVRSpatialAnchor component exists but creation failed.
            Destroy(anchor);
        }
        // else if creation failed and the OVRSpatialAnchor component was destroyed, nothing to do.
    }
PopulateUnbound()
static void OVRSpatialAnchor.PopulateUnbound (Guid uuid, UInt64 space) static private
Definition at line 1408 of file OVRSpatialAnchor.cs.
    {
        if (SpatialAnchors.ContainsKey(uuid))
        {
            Development.Log($"[{uuid}] Anchor is already bound to an {nameof(OVRSpatialAnchor)}. Ignoring.");
            return;
        }
        // See if it supports localization
        if (!OVRPlugin.EnumerateSpaceSupportedComponents(space, out var numSupportedComponents,
                ComponentTypeBuffer))
        {
            Development.LogWarning($"[{uuid}] Unable to enumerate supported component types. Ignoring.");
            return;
        }
        var supportsLocatable = false;
        for (var i = 0; i < numSupportedComponents; i++)
        {
            supportsLocatable |= ComponentTypeBuffer[i] == OVRPlugin.SpaceComponentType.Locatable;
        }
#if DEVELOPMENT_BUILD
        var supportedComponentTypesMsg =
            $"[{uuid}] Supports {numSupportedComponents} component type(s): {(numSupportedComponents == 0 ? "(none)" : string.Join(", ", ComponentTypeBuffer.Take((int)numSupportedComponents).Select(c => c.ToString())))}";
#endif
        if (!supportsLocatable)
        {
#if DEVELOPMENT_BUILD
            Development.Log($"{supportedComponentTypesMsg} -- ignoring because it does not support localization.");
#endif
            return;
        }
        if (!OVRPlugin.GetSpaceComponentStatus(space, OVRPlugin.SpaceComponentType.Locatable, out var enabled,
                out var changePending))
        {
#if DEVELOPMENT_BUILD
            Development.Log($"{supportedComponentTypesMsg} -- ignoring because failed to get localization.");
#endif
            return;
        }
#if DEVELOPMENT_BUILD
        Development.Log($"{supportedComponentTypesMsg}.");
#endif
        Debug.Log($"{uuid}: locatable enabled? {enabled} changePending? {changePending}");
        UnboundAnchorBuffer.Add(new UnboundAnchor(space, uuid));
    }
Save() [1/3]
void OVRSpatialAnchor.Save (Action< OVRSpatialAnchor, bool > onComplete = null)
Saves the OVRSpatialAnchor to local persistent storage.
This method is asynchronous. Use onComplete to be notified of completion.
When saved, an OVRSpatialAnchor can be loaded by a different session. Use the Uuid to identify the same OVRSpatialAnchor at a future time.
This operation fully succeeds or fails, which means, either all anchors are successfully saved, or the operation fails.
Parameters
onComplete Invoked when the save operation completes. May be null. Parameters are
OVRSpatialAnchor: The anchor being saved.
bool: A value indicating whether the save operation succeeded.
Definition at line 162 of file OVRSpatialAnchor.cs.
    {
        Save(_defaultSaveOptions, onComplete);
    }
References Save().
Save() [2/3]
static void OVRSpatialAnchor.Save (ICollection< OVRSpatialAnchor > anchors, SaveOptions saveOptions, Action< ICollection< OVRSpatialAnchor >, OperationResult > onComplete = null) static
Saves a collection of OVRSpatialAnchor to specified storage.
This method is asynchronous. Use onComplete to be notified of completion. When saved, an OVRSpatialAnchor can be loaded by a different session. Use the Uuid to identify the same OVRSpatialAnchor at a future time.
Parameters
anchors Collection of anchors
saveOptions Options how the anchors are saved whether local or cloud.
onComplete Invoked when the save operation completes. May be null. onComplete receives two parameters:
ICollection&lt;OVRSpatialAnchor&gt;: The same collection as in anchors parameter
OperationResult: An error code indicating whether the save operation succeeded or not.
Exceptions
ArgumentNullException Thrown if anchors is null.
Definition at line 261 of file OVRSpatialAnchor.cs.
    {
        if (anchors == null)
            throw new ArgumentNullException(nameof(anchors));
        using var spaces = ToNativeArray(anchors);
        var saveResult =
            OVRPlugin.SaveSpaceList(spaces, saveOptions.Storage.ToSpaceStorageLocation(), out var requestId);
        if (saveResult.IsSuccess())
        {
            Development.LogRequest(requestId, $"Saving spatial anchors...");
            MultiAnchorCompletionDelegates[requestId] = new MultiAnchorDelegatePair
            {
                Anchors = CopyAnchorListIntoListFromPool(anchors),
                Delegate = onComplete
            };
            if (onComplete != null)
            {
                OVRTelemetry.Client.MarkerStart(OVRTelemetryConstants.Scene.MarkerId.SpatialAnchorSave,
                    requestId.GetHashCode());
            }
        }
        else
        {
            Development.LogError(
                $"{nameof(OVRPlugin)}.{nameof(OVRPlugin.SaveSpaceList)} failed with error {saveResult}.");
            onComplete?.Invoke(anchors, (OperationResult)saveResult);
        }
    }
References OVRSpatialAnchor.SaveOptions.Storage.
Save() [3/3]
void OVRSpatialAnchor.Save (SaveOptions saveOptions, Action< OVRSpatialAnchor, bool > onComplete = null)
Saves the OVRSpatialAnchor with specified SaveOptions.
This method is asynchronous. Use onComplete to be notified of completion. When saved, the OVRSpatialAnchor can be loaded by a different session. Use the Uuid to identify the same OVRSpatialAnchor at a future time.
This operation fully succeeds or fails; that is, either all anchors are successfully saved, or the operation fails.
Parameters
saveOptions Options how the anchor is saved. whether local or cloud.
onComplete Invoked when the save operation completes. May be null. Parameters are
OVRSpatialAnchor: The anchor being saved.
bool: A value indicating whether the save operation succeeded.
Definition at line 197 of file OVRSpatialAnchor.cs.
    {
        var task = SaveAsync(saveOptions);
        if (onComplete != null)
        {
            InvertedCapture<bool, OVRSpatialAnchor>.ContinueTaskWith(task, onComplete, this);
        }
    }
References SaveAsync().
SaveAsync() [1/2]
OVRTask< bool > OVRSpatialAnchor.SaveAsync ()
Saves the OVRSpatialAnchor with specified SaveOptions.
This method is asynchronous; use the returned OVRTask<TResult> to be notified of completion. When saved, the OVRSpatialAnchor can be loaded by a different session. Use the Uuid to identify the same OVRSpatialAnchor at a future time.
This operation fully succeeds or fails; that is, either all anchors are successfully saved, or the operation fails.
Returns
An OVRTask<TResult> with a boolean type parameter indicating the success of the save operation.
SaveAsync() [2/2]
OVRTask< bool > OVRSpatialAnchor.SaveAsync (SaveOptions saveOptions)
Saves the OVRSpatialAnchor with specified SaveOptions.
This method is asynchronous; use the returned OVRTask<TResult> to be notified of completion. When saved, the OVRSpatialAnchor can be loaded by a different session. Use the Uuid to identify the same OVRSpatialAnchor at a future time.
This operation fully succeeds or fails; that is, either all anchors are successfully saved, or the operation fails.
Parameters
saveOptions Options for how the anchor will be saved.
Returns
An OVRTask<TResult> with a boolean type parameter indicating the success of the save operation.
Definition at line 237 of file OVRSpatialAnchor.cs.
    {
        var requestId = Guid.NewGuid();
        SaveRequests[saveOptions.Storage].Add(this);
        AsyncRequestTaskIds[this] = requestId;
        return OVRTask.FromGuid<bool>(requestId);
    }
References OVRSpatialAnchor.SaveOptions.Storage.
SaveBatchAnchors()
static void OVRSpatialAnchor.SaveBatchAnchors () static private
Definition at line 739 of file OVRSpatialAnchor.cs.
    {
        foreach (var pair in SaveRequests)
        {
            if (pair.Value.Count == 0)
            {
                continue;
            }
            Save(pair.Value, new SaveOptions { Storage = pair.Key });
            pair.Value.Clear();
        }
    }
Share() [1/6]
static void OVRSpatialAnchor.Share (ICollection< OVRSpatialAnchor > anchors, ICollection< OVRSpaceUser > users, Action< ICollection< OVRSpatialAnchor >, OperationResult > onComplete = null) static
Shares a collection of OVRSpatialAnchor to specified users. Specified users will be able to download, track, and share specified anchors.
This method is asynchronous. Use onComplete to be notified of completion.
This operation fully succeeds or fails, which means, either all anchors are successfully shared or the operation fails.
Parameters
anchors The collection of anchors to share.
users An array of Oculus users to share these anchors with.
onComplete Invoked when the share operation completes. May be null. Delegate parameter is
ICollection&lt;OVRSpatialAnchor&gt;: The collection of anchors being shared.
OperationResult: An error code that indicates whether the share operation succeeded or not.
Exceptions
ArgumentNullException Thrown if anchors is null.
Definition at line 537 of file OVRSpatialAnchor.cs.
    {
        if (anchors == null)
            throw new ArgumentNullException(nameof(anchors));
        using var spaces = ToNativeArray(anchors);
        var handles = new NativeArray<ulong>(users.Count, Allocator.Temp);
        using var disposer = handles;
        int i = 0;
        foreach (var user in users)
        {
            handles[i++] = user._handle;
        }
        var shareResult = OVRPlugin.ShareSpaces(spaces, handles, out var requestId);
        if (shareResult.IsSuccess())
        {
            Development.LogRequest(requestId, $"Sharing {(uint)spaces.Length} spatial anchors...");
            MultiAnchorCompletionDelegates[requestId] = new MultiAnchorDelegatePair
            {
                Anchors = CopyAnchorListIntoListFromPool(anchors),
                Delegate = onComplete
            };
        }
        else
        {
            Development.LogError(
                $"{nameof(OVRPlugin)}.{nameof(OVRPlugin.ShareSpaces)}  failed with error {shareResult}.");
            onComplete?.Invoke(anchors, (OperationResult)shareResult);
        }
    }
Share() [2/6]
void OVRSpatialAnchor.Share (IEnumerable< OVRSpaceUser > users, Action< OperationResult > onComplete = null)
Shares the anchor to a collection of OVRSpaceUser. Specified users will be able to download, track, and share specified anchors.
This method is asynchronous. Use onComplete to be notified of completion.
Parameters
users A collection of Oculus users to share the anchor with.
onComplete Invoked when the share operation completes. May be null. Delegate parameter is
OperationResult: An error code that indicates whether the share operation succeeded or not.
Definition at line 492 of file OVRSpatialAnchor.cs.
    {
        var task = ShareAsync(users);
        if (onComplete != null)
        {
            task.ContinueWith(onComplete);
        }
    }
References ShareAsync().
Share() [3/6]
void OVRSpatialAnchor.Share (OVRSpaceUser user, Action< OperationResult > onComplete = null)
Shares the anchor to an OVRSpaceUser. The specified user will be able to download, track, and share specified anchors.
This method is asynchronous. Use onComplete to be notified of completion.
Parameters
user An Oculus user to share the anchor with.
onComplete Invoked when the share operation completes. May be null. Delegate parameter is
OperationResult: An error code that indicates whether the share operation succeeded or not.
Definition at line 315 of file OVRSpatialAnchor.cs.
    {
        var task = ShareAsync(user);
        if (onComplete != null)
        {
            task.ContinueWith(onComplete);
        }
    }
References ShareAsync().
Share() [4/6]
void OVRSpatialAnchor.Share (OVRSpaceUser user1, OVRSpaceUser user2, Action< OperationResult > onComplete = null)
Shares the anchor with two OVRSpaceUser. Specified users will be able to download, track, and share specified anchors.
This method is asynchronous. Use onComplete to be notified of completion.
Parameters
user1 An Oculus user to share the anchor with.
user2 An Oculus user to share the anchor with.
onComplete Invoked when the share operation completes. May be null. Delegate parameter is
OperationResult: An error code that indicates whether the share operation succeeded or not.
Definition at line 355 of file OVRSpatialAnchor.cs.
    {
        var task = ShareAsync(user1, user2);
        if (onComplete != null)
        {
            task.ContinueWith(onComplete);
        }
    }
References ShareAsync().
Share() [5/6]
void OVRSpatialAnchor.Share (OVRSpaceUser user1, OVRSpaceUser user2, OVRSpaceUser user3, Action< OperationResult > onComplete = null)
Shares the anchor with three OVRSpaceUser. Specified users will be able to download, track, and share specified anchors.
This method is asynchronous. Use onComplete to be notified of completion.
Parameters
user1 An Oculus user to share the anchor with.
user2 An Oculus user to share the anchor with.
user3 An Oculus user to share the anchor with.
onComplete Invoked when the share operation completes. May be null. Delegate parameter is
OperationResult: An error code that indicates whether the share operation succeeded or not.
Definition at line 398 of file OVRSpatialAnchor.cs.
    {
        var task = ShareAsync(user1, user2, user3);
        if (onComplete != null)
        {
            task.ContinueWith(onComplete);
        }
    }
References ShareAsync().
Share() [6/6]
void OVRSpatialAnchor.Share (OVRSpaceUser user1, OVRSpaceUser user2, OVRSpaceUser user3, OVRSpaceUser user4, Action< OperationResult > onComplete = null)
Shares the anchor with four OVRSpaceUser. Specified users will be able to download, track, and share specified anchors.
This method is asynchronous. Use onComplete to be notified of completion.
Parameters
user1 An Oculus user to share the anchor with.
user2 An Oculus user to share the anchor with.
user3 An Oculus user to share the anchor with.
user4 An Oculus user to share the anchor with.
onComplete Invoked when the share operation completes. May be null. Delegate parameter is
OperationResult: An error code that indicates whether the share operation succeeded or not.
Definition at line 445 of file OVRSpatialAnchor.cs.
    {
        var task = ShareAsync(user1, user2, user3, user4);
        if (onComplete != null)
        {
            task.ContinueWith(onComplete);
        }
    }
References ShareAsync().
ShareAsync() [1/5]
OVRTask< OperationResult > OVRSpatialAnchor.ShareAsync (IEnumerable< OVRSpaceUser > users)
Shares the anchor to an OVRSpaceUser. The specified user will be able to download, track, and share specified anchors.
This method is asynchronous; use the returned OVRTask<TResult> to be notified of completion.
Parameters
users A collection of Oculus users to share the anchor with.
Returns
An OVRTask<TResult> with a OperationResult type parameter indicating the success of the share operation.
Definition at line 512 of file OVRSpatialAnchor.cs.
    {
        var userList = OVRObjectPool.List<OVRSpaceUser>();
        userList.AddRange(users);
        return ShareAsyncInternal(userList);
    }
ShareAsync() [2/5]
OVRTask< OperationResult > OVRSpatialAnchor.ShareAsync (OVRSpaceUser user)
Shares the anchor to an OVRSpaceUser. The specified user will be able to download, track, and share specified anchors.
This method is asynchronous; use the returned OVRTask<TResult> to be notified of completion.
Parameters
user An Oculus user to share the anchor with.
Returns
An OVRTask<TResult> with a OperationResult type parameter indicating the success of the share operation.
Definition at line 335 of file OVRSpatialAnchor.cs.
    {
        var userList = OVRObjectPool.List<OVRSpaceUser>();
        userList.Add(user);
        return ShareAsyncInternal(userList);
    }
ShareAsync() [3/5]
OVRTask< OperationResult > OVRSpatialAnchor.ShareAsync (OVRSpaceUser user1, OVRSpaceUser user2)
Shares the anchor to an OVRSpaceUser. The specified user will be able to download, track, and share specified anchors.
This method is asynchronous; use the returned OVRTask<TResult> to be notified of completion.
Parameters
user1 An Oculus user to share the anchor with.
user2 An Oculus user to share the anchor with.
Returns
An OVRTask<TResult> with a OperationResult type parameter indicating the success of the share operation.
Definition at line 376 of file OVRSpatialAnchor.cs.
    {
        var userList = OVRObjectPool.List<OVRSpaceUser>();
        userList.Add(user1);
        userList.Add(user2);
        return ShareAsyncInternal(userList);
    }
ShareAsync() [4/5]
OVRTask< OperationResult > OVRSpatialAnchor.ShareAsync (OVRSpaceUser user1, OVRSpaceUser user2, OVRSpaceUser user3)
Shares the anchor to an OVRSpaceUser. The specified user will be able to download, track, and share specified anchors.
This method is asynchronous; use the returned OVRTask<TResult> to be notified of completion.
Parameters
user1 An Oculus user to share the anchor with.
user2 An Oculus user to share the anchor with.
user3 An Oculus user to share the anchor with.
Returns
An OVRTask<TResult> with a OperationResult type parameter indicating the success of the share operation.
Definition at line 421 of file OVRSpatialAnchor.cs.
    {
        var userList = OVRObjectPool.List<OVRSpaceUser>();
        userList.Add(user1);
        userList.Add(user2);
        userList.Add(user3);
        return ShareAsyncInternal(userList);
    }
ShareAsync() [5/5]
OVRTask< OperationResult > OVRSpatialAnchor.ShareAsync (OVRSpaceUser user1, OVRSpaceUser user2, OVRSpaceUser user3, OVRSpaceUser user4)
Shares the anchor to an OVRSpaceUser. The specified user will be able to download, track, and share specified anchors.
This method is asynchronous; use the returned OVRTask<TResult> to be notified of completion.
Parameters
user1 An Oculus user to share the anchor with.
user2 An Oculus user to share the anchor with.
user3 An Oculus user to share the anchor with.
user4 An Oculus user to share the anchor with.
Returns
An OVRTask<TResult> with a OperationResult type parameter indicating the success of the share operation.
Definition at line 469 of file OVRSpatialAnchor.cs.
    {
        var userList = OVRObjectPool.List<OVRSpaceUser>();
        userList.Add(user1);
        userList.Add(user2);
        userList.Add(user3);
        userList.Add(user4);
        return ShareAsyncInternal(userList);
    }
ShareAsyncInternal()
OVRTask< OperationResult > OVRSpatialAnchor.ShareAsyncInternal (List< OVRSpaceUser > users) private
Definition at line 572 of file OVRSpatialAnchor.cs.
    {
        var shareRequestAnchors = GetListToStoreTheShareRequest(users);
        shareRequestAnchors.Add(this);
        var requestId = Guid.NewGuid();
        AsyncRequestTaskIds[this] = requestId;
        return OVRTask.FromGuid<OperationResult>(requestId);
    }
ShareBatchAnchors()
static void OVRSpatialAnchor.ShareBatchAnchors () static private
Definition at line 753 of file OVRSpatialAnchor.cs.
    {
        foreach (var (userList, anchorList) in ShareRequests)
        {
            if (userList.Count > 0 && anchorList.Count > 0)
            {
                Share(anchorList, userList);
            }
            OVRObjectPool.Return(userList);
            OVRObjectPool.Return(anchorList);
        }
        ShareRequests.Clear();
    }
Start()
void OVRSpatialAnchor.Start () private
Definition at line 711 of file OVRSpatialAnchor.cs.
    {
        _startCalled = true;
        if (Space.Valid)
        {
            Development.Log($"[{Uuid}] Created spatial anchor from existing an existing space.");
        }
        else
        {
            CreateSpatialAnchor();
        }
    }
ThrowIfBound()
static void OVRSpatialAnchor.ThrowIfBound (Guid uuid) static private
Definition at line 689 of file OVRSpatialAnchor.cs.
    {
        if (SpatialAnchors.ContainsKey(uuid))
            throw new InvalidOperationException(
                $"Spatial anchor with uuid {uuid} is already bound to an {nameof(OVRSpatialAnchor)}.");
    }
ToNativeArray()
static NativeArray< ulong > OVRSpatialAnchor.ToNativeArray (ICollection< OVRSpatialAnchor > anchors) static private
Definition at line 167 of file OVRSpatialAnchor.cs.
    {
        var count = anchors.Count;
        var spaces = new NativeArray<ulong>(count, Allocator.Temp);
        var i = 0;
        foreach (var anchor in anchors.ToNonAlloc())
        {
            spaces[i++] = anchor ? anchor.Space : 0;
        }
        return spaces;
    }
Update()
void OVRSpatialAnchor.Update () private
Definition at line 725 of file OVRSpatialAnchor.cs.
    {
        if (Space.Valid)
        {
            UpdateTransform();
        }
    }
UpdateTransform()
void OVRSpatialAnchor.UpdateTransform () private
Definition at line 837 of file OVRSpatialAnchor.cs.
    {
        if (TryGetPose(Space, out var pose))
        {
            transform.SetPositionAndRotation(pose.position, pose.orientation);
        }
    }
Member Data Documentation
_defaultEraseOptions
readonly EraseOptions OVRSpatialAnchor._defaultEraseOptions private
Initial value:
= new EraseOptions
    {
        Storage = OVRSpace.StorageLocation.Local,
    }
Definition at line 56 of file OVRSpatialAnchor.cs.
    {
        Storage = OVRSpace.StorageLocation.Local,
    };
_defaultSaveOptions
readonly SaveOptions OVRSpatialAnchor._defaultSaveOptions private
Initial value:
= new SaveOptions
    {
        Storage = OVRSpace.StorageLocation.Local,
    }
Definition at line 51 of file OVRSpatialAnchor.cs.
    {
        Storage = OVRSpace.StorageLocation.Local,
    };
_requestId
ulong OVRSpatialAnchor._requestId private
Definition at line 49 of file OVRSpatialAnchor.cs.
_startCalled
bool OVRSpatialAnchor._startCalled private
Definition at line 47 of file OVRSpatialAnchor.cs.
AsyncRequestTaskIds
readonly Dictionary<OVRSpatialAnchor, Guid> OVRSpatialAnchor.AsyncRequestTaskIds static private
Initial value:
=
        new Dictionary<OVRSpatialAnchor, Guid>()
Definition at line 867 of file OVRSpatialAnchor.cs.
ComponentTypeBuffer
readonly OVRPlugin.SpaceComponentType [] OVRSpatialAnchor.ComponentTypeBuffer = new OVRPlugin.SpaceComponentType[32] static private
Definition at line 878 of file OVRSpatialAnchor.cs.
CreationRequests
readonly Dictionary<ulong, OVRSpatialAnchor> OVRSpatialAnchor.CreationRequests static private
Initial value:
=
        new Dictionary<ulong, OVRSpatialAnchor>()
Definition at line 857 of file OVRSpatialAnchor.cs.
MultiAnchorCompletionDelegates
readonly Dictionary<ulong, MultiAnchorDelegatePair> OVRSpatialAnchor.MultiAnchorCompletionDelegates static private
Initial value:
=
        new Dictionary<ulong, MultiAnchorDelegatePair>()
Definition at line 873 of file OVRSpatialAnchor.cs.
SaveRequests
readonly Dictionary<OVRSpace.StorageLocation, List<OVRSpatialAnchor> > OVRSpatialAnchor.SaveRequests static private
Initial value:
=
        new Dictionary<OVRSpace.StorageLocation, List<OVRSpatialAnchor>>
        {
            { OVRSpace.StorageLocation.Cloud, new List<OVRSpatialAnchor>() },
            { OVRSpace.StorageLocation.Local, new List<OVRSpatialAnchor>() },
        }
Definition at line 860 of file OVRSpatialAnchor.cs.
        {
            { OVRSpace.StorageLocation.Cloud, new List<OVRSpatialAnchor>() },
            { OVRSpace.StorageLocation.Local, new List<OVRSpatialAnchor>() },
        };
ShareRequests
readonly List<(List<OVRSpaceUser>, List<OVRSpatialAnchor>)> OVRSpatialAnchor.ShareRequests static private
Initial value:
=
        new List<(List<OVRSpaceUser>, List<OVRSpatialAnchor>)>()
Definition at line 870 of file OVRSpatialAnchor.cs.
UnboundAnchorBuffer
readonly List<UnboundAnchor> OVRSpatialAnchor.UnboundAnchorBuffer = new List<UnboundAnchor>() static private
Definition at line 876 of file OVRSpatialAnchor.cs.
Property Documentation
Created
bool OVRSpatialAnchor.Created get
Checks whether the spatial anchor is created.
Creation is asynchronous and may take several frames. If creation fails, the component is destroyed.
Definition at line 90 of file OVRSpatialAnchor.cs.
Localized
bool OVRSpatialAnchor.Localized get
Checks whether the spatial anchor is localized.
When you create a new spatial anchor, it may take a few frames before it is localized. Once localized, its transform updates automatically.
Definition at line 104 of file OVRSpatialAnchor.cs.
PendingCreation
bool OVRSpatialAnchor.PendingCreation get
Checks whether the spatial anchor is pending creation.
Definition at line 95 of file OVRSpatialAnchor.cs.
Space
OVRSpace OVRSpatialAnchor.Space get private set
The space associated with the spatial anchor.
The OVRSpace represents the runtime instance of the spatial anchor and will change across different sessions.
Definition at line 73 of file OVRSpatialAnchor.cs.
{ get; private set; }
Uuid
Guid OVRSpatialAnchor.Uuid get private set
The UUID associated with the spatial anchor.
UUIDs persist across sessions. If you load a persisted anchor, you can use the UUID to identify it.
Definition at line 82 of file OVRSpatialAnchor.cs.
{ get; private set; }
Event Documentation
OnLocalize
Action<OperationResult> OVRSpatialAnchor.OnLocalize
Event that is dispatched when the localization process finishes.
Definition at line 64 of file OVRSpatialAnchor.cs.
The documentation for this class was generated from the following file:
Assets/Oculus/VR/Scripts/OVRSpatialAnchor.cs