VR_Test: OculusSampleFramework.RayTool Class Reference
OculusSampleFramework.RayTool Class Reference
Ray tool used for far-field interactions.
Public Member Functions
override void Initialize ()
override List< InteractableCollisionInfo > GetNextIntersectingObjects ()
override void FocusOnInteractable (Interactable focusedInteractable, ColliderZone colliderZone)
override void DeFocus ()
Public Member Functions inherited from OculusSampleFramework.InteractableTool
List< InteractableCollisionInfo > GetCurrentIntersectingObjects ()
List< InteractableCollisionInfo > GetNextIntersectingObjects ()
void FocusOnInteractable (Interactable focusedInteractable, ColliderZone colliderZone)
Used to tell the tool to "focus" on a specific object, if focusing is indeed possible given the tool type.
void DeFocus ()
void Initialize ()
KeyValuePair< Interactable, InteractableCollisionInfo > GetFirstCurrentCollisionInfo ()
void ClearAllCurrentCollisionInfos ()
virtual void UpdateCurrentCollisionsBasedOnDepth ()
For each intersecting interactable, update meta data to indicate deepest collision only.
virtual void UpdateLatestCollisionData ()
If our collision information changed per frame, make note of it. Removed, added and remaining objects must get their proper events.
Properties
override InteractableToolTags ToolTags [get]
override ToolInputState ToolInputState [get]
override bool IsFarFieldTool [get]
override bool EnableState [get, set]
Properties inherited from OculusSampleFramework.InteractableTool
Transform ToolTransform [get]
bool IsRightHandedTool [get, set]
InteractableToolTags ToolTags [get]
ToolInputState ToolInputState [get]
bool IsFarFieldTool [get]
Vector3 Velocity [get, protected set]
Vector3 InteractionPosition [get, protected set]
Sometimes we want the position of a tool for stuff like pokes.
bool EnableState [get, set]
Private Member Functions
void OnDestroy ()
void Update ()
Vector3 GetRayCastOrigin ()
Avoid hand collider during raycasts so move origin some distance away from where tool is.
bool HasRayReleasedInteractable (Interactable focusedInteractable)
Interactable FindTargetInteractable ()
Find all objects from primary ray cast or if that fails, all objects in a cone around main ray direction via a "secondary" cast.
Interactable FindPrimaryRaycastHit (Vector3 rayOrigin, Vector3 rayDirection)
Find first hit that is supports our tool's method of interaction.
Interactable FindInteractableViaConeTest (Vector3 rayOrigin, Vector3 rayDirection)
If primary cast fails, try secondary test to see if we can target an interactable. This target has to be far enough and support our tool via appropriate tags, and must be within a certain angle from our primary ray direction.
Private Attributes
RayToolView _rayToolView = null
float _coneAngleDegrees = 20.0f
float _farFieldMaxDistance = 5f
PinchStateModule _pinchStateModule = new PinchStateModule()
Interactable _focusedInteractable
Collider[] _collidersOverlapped = new Collider[NUM_COLLIDERS_TO_TEST]
Interactable _currInteractableCastedAgainst = null
float _coneAngleReleaseDegrees
RaycastHit[] _primaryHits = new RaycastHit[NUM_MAX_PRIMARY_HITS]
Collider[] _secondaryOverlapResults = new Collider[NUM_MAX_SECONDARY_HITS]
bool _initialized = false
Static Private Attributes
const float MINIMUM_RAY_CAST_DISTANCE = 0.8f
const float COLLIDER_RADIUS = 0.01f
const int NUM_MAX_PRIMARY_HITS = 10
const int NUM_MAX_SECONDARY_HITS = 25
const int NUM_COLLIDERS_TO_TEST = 20
Additional Inherited Members
Protected Attributes inherited from OculusSampleFramework.InteractableTool
List< InteractableCollisionInfo > _currentIntersectingObjects
List of objects that intersect tool.
Detailed Description
Ray tool used for far-field interactions.
Definition at line 31 of file RayTool.cs.
Member Function Documentation
DeFocus()
override void OculusSampleFramework.RayTool.DeFocus ()
Definition at line 345 of file RayTool.cs.
        {
            _rayToolView.SetFocusedInteractable(null);
            _focusedInteractable = null;
        }
FindInteractableViaConeTest()
Interactable OculusSampleFramework.RayTool.FindInteractableViaConeTest (Vector3 rayOrigin, Vector3 rayDirection) private
If primary cast fails, try secondary test to see if we can target an interactable. This target has to be far enough and support our tool via appropriate tags, and must be within a certain angle from our primary ray direction.
Parameters
rayOrigin Primary ray origin.
rayDirection Primary ray direction.
Returns
Interactable found, if any.
Definition at line 285 of file RayTool.cs.
        {
            Interactable targetInteractable = null;
            float minDistance = 0.0f;
            float minDotProductThreshold = Mathf.Cos(_coneAngleDegrees * Mathf.Deg2Rad);
            // cone extends from center line, where angle is split between top and bottom half
            float halfAngle = Mathf.Deg2Rad * _coneAngleDegrees * 0.5f;
            float coneRadius = Mathf.Tan(halfAngle) * _farFieldMaxDistance;
            int numColliders = Physics.OverlapBoxNonAlloc(
                rayOrigin + rayDirection * _farFieldMaxDistance * 0.5f, // center
                new Vector3(coneRadius, coneRadius, _farFieldMaxDistance * 0.5f), //half extents
                _secondaryOverlapResults, transform.rotation);
            for (int i = 0; i < numColliders; i++)
            {
                Collider colliderHit = _secondaryOverlapResults[i];
                // skip invalid colliders
                var colliderZone = colliderHit.GetComponent<ColliderZone>();
                if (colliderZone == null)
                {
                    continue;
                }
                // skip invalid components
                Interactable interactableComponent = colliderZone.ParentInteractable;
                if (interactableComponent == null ||
                    (interactableComponent.ValidToolTagsMask & (int)ToolTags) == 0)
                {
                    continue;
                }
                var vectorToInteractable = interactableComponent.transform.position - rayOrigin;
                var distanceToInteractable = vectorToInteractable.magnitude;
                vectorToInteractable /= distanceToInteractable;
                var dotProduct = Vector3.Dot(vectorToInteractable, rayDirection);
                // must be inside cone!
                if (dotProduct < minDotProductThreshold)
                {
                    continue;
                }
                if (targetInteractable == null || distanceToInteractable < minDistance)
                {
                    targetInteractable = interactableComponent;
                    minDistance = distanceToInteractable;
                }
            }
            return targetInteractable;
        }
FindPrimaryRaycastHit()
Interactable OculusSampleFramework.RayTool.FindPrimaryRaycastHit (Vector3 rayOrigin, Vector3 rayDirection) private
Find first hit that is supports our tool's method of interaction.
Definition at line 239 of file RayTool.cs.
        {
            Interactable interactableCastedAgainst = null;
            // hit order not guaranteed, so find closest
            int numHits = Physics.RaycastNonAlloc(new Ray(rayOrigin, rayDirection), _primaryHits, Mathf.Infinity);
            float minDistance = 0.0f;
            for (int hitIndex = 0; hitIndex < numHits; hitIndex++)
            {
                RaycastHit raycastHit = _primaryHits[hitIndex];
                // continue if something occludes it and that object is not an interactable
                var currentHitColliderZone = raycastHit.transform.GetComponent<ColliderZone>();
                if (currentHitColliderZone == null)
                {
                    continue;
                }
                // at this point we have encountered an interactable. Only consider it if
                // it allows interaction with our tool. Otherwise ignore it.
                Interactable currentInteractable = currentHitColliderZone.ParentInteractable;
                if (currentInteractable == null || (currentInteractable.ValidToolTagsMask & (int)ToolTags) == 0)
                {
                    continue;
                }
                var vectorToInteractable = currentInteractable.transform.position - rayOrigin;
                var distanceToInteractable = vectorToInteractable.magnitude;
                if (interactableCastedAgainst == null || distanceToInteractable < minDistance)
                {
                    interactableCastedAgainst = currentInteractable;
                    minDistance = distanceToInteractable;
                }
            }
            return interactableCastedAgainst;
        }
FindTargetInteractable()
Interactable OculusSampleFramework.RayTool.FindTargetInteractable () private
Find all objects from primary ray cast or if that fails, all objects in a cone around main ray direction via a "secondary" cast.
Definition at line 218 of file RayTool.cs.
        {
            var rayOrigin = GetRayCastOrigin();
            var rayDirection = transform.forward;
            Interactable targetInteractable = null;
            // attempt primary ray cast
            targetInteractable = FindPrimaryRaycastHit(rayOrigin, rayDirection);
            // if primary cast fails, try secondary cone test
            if (targetInteractable == null)
            {
                targetInteractable = FindInteractableViaConeTest(rayOrigin, rayDirection);
            }
            return targetInteractable;
        }
References OculusSampleFramework.RayTool.FindInteractableViaConeTest(), OculusSampleFramework.RayTool.FindPrimaryRaycastHit(), and OculusSampleFramework.RayTool.GetRayCastOrigin().
FocusOnInteractable()
override void OculusSampleFramework.RayTool.FocusOnInteractable (Interactable focusedInteractable, ColliderZone colliderZone)
Definition at line 338 of file RayTool.cs.
        {
            _rayToolView.SetFocusedInteractable(focusedInteractable);
            _focusedInteractable = focusedInteractable;
        }
GetNextIntersectingObjects()
override List< InteractableCollisionInfo > OculusSampleFramework.RayTool.GetNextIntersectingObjects ()
Definition at line 142 of file RayTool.cs.
        {
            if (!_initialized)
            {
                return _currentIntersectingObjects;
            }
            // if we already have focused on something, keep it until the angle between
            // our forward direction and object vector becomes too large
            if (_currInteractableCastedAgainst != null &&
                HasRayReleasedInteractable(_currInteractableCastedAgainst))
            {
                // reset state
                _currInteractableCastedAgainst = null;
            }
            // Find target interactable if we haven't found one before.
            if (_currInteractableCastedAgainst == null)
            {
                _currentIntersectingObjects.Clear();
                _currInteractableCastedAgainst = FindTargetInteractable();
                // If we have found one, query collision zones.
                if (_currInteractableCastedAgainst != null)
                {
                    var targetHitPoint = _currInteractableCastedAgainst.transform.position;
                    int numHits = Physics.OverlapSphereNonAlloc(targetHitPoint, COLLIDER_RADIUS, _collidersOverlapped);
                    // find all colliders encountered; focus only on ones belonging to target element
                    for (int i = 0; i < numHits; i++)
                    {
                        Collider colliderHit = _collidersOverlapped[i];
                        var colliderZone = colliderHit.GetComponent<ColliderZone>();
                        if (colliderZone == null)
{
                            continue;
                        }
                        Interactable interactableComponent = colliderZone.ParentInteractable;
                        if (interactableComponent == null || interactableComponent
                            != _currInteractableCastedAgainst)
{
                            continue;
                        }
                        InteractableCollisionInfo collisionInfo = new InteractableCollisionInfo(colliderZone,
                            colliderZone.CollisionDepth, this);
                        _currentIntersectingObjects.Add(collisionInfo);
                    }
                    // clear intersecting object if no collisions were found
                    if (_currentIntersectingObjects.Count == 0)
                    {
                        _currInteractableCastedAgainst = null;
                    }
                }
            }
            return _currentIntersectingObjects;
        }
GetRayCastOrigin()
Vector3 OculusSampleFramework.RayTool.GetRayCastOrigin () private
Avoid hand collider during raycasts so move origin some distance away from where tool is.
Returns
Proper raycast origin.
Definition at line 137 of file RayTool.cs.
        {
            return transform.position + MINIMUM_RAY_CAST_DISTANCE * transform.forward;
        }
HasRayReleasedInteractable()
bool OculusSampleFramework.RayTool.HasRayReleasedInteractable (Interactable focusedInteractable) private
Definition at line 203 of file RayTool.cs.
        {
            var ourPosition = transform.position;
            var forwardDirection = transform.forward;
            var hysteresisDotThreshold = Mathf.Cos(_coneAngleReleaseDegrees * Mathf.Deg2Rad);
            var vectorToFocusedObject = focusedInteractable.transform.position - ourPosition;
            vectorToFocusedObject.Normalize();
            var hysteresisDotProduct = Vector3.Dot(vectorToFocusedObject, forwardDirection);
            return hysteresisDotProduct < hysteresisDotThreshold;
        }
Initialize()
override void OculusSampleFramework.RayTool.Initialize ()
Definition at line 94 of file RayTool.cs.
        {
            Assert.IsNotNull(_rayToolView);
            InteractableToolsInputRouter.Instance.RegisterInteractableTool(this);
            _rayToolView.InteractableTool = this;
            _coneAngleReleaseDegrees = _coneAngleDegrees * 1.2f;
            _initialized = true;
        }
OnDestroy()
void OculusSampleFramework.RayTool.OnDestroy () private
Definition at line 103 of file RayTool.cs.
        {
            if (InteractableToolsInputRouter.Instance != null)
            {
                InteractableToolsInputRouter.Instance.UnregisterInteractableTool(this);
            }
        }
Update()
void OculusSampleFramework.RayTool.Update () private
Definition at line 111 of file RayTool.cs.
        {
            if (!HandsManager.Instance || !HandsManager.Instance.IsInitialized() || !_initialized)
            {
                return;
            }
            var hand = IsRightHandedTool ? HandsManager.Instance.RightHand : HandsManager.Instance.LeftHand;
            var pointer = hand.PointerPose;
            transform.position = pointer.position;
            transform.rotation = pointer.rotation;
            var prevPosition = InteractionPosition;
            var currPosition = transform.position;
            Velocity = (currPosition - prevPosition) / Time.deltaTime;
            InteractionPosition = currPosition;
            _pinchStateModule.UpdateState(hand, _focusedInteractable);
            _rayToolView.ToolActivateState = _pinchStateModule.PinchSteadyOnFocusedObject ||
                                             _pinchStateModule.PinchDownOnFocusedObject;
        }
Member Data Documentation
_collidersOverlapped
Collider [] OculusSampleFramework.RayTool._collidersOverlapped = new Collider[NUM_COLLIDERS_TO_TEST] private
Definition at line 85 of file RayTool.cs.
_coneAngleDegrees
float OculusSampleFramework.RayTool._coneAngleDegrees = 20.0f private
Definition at line 40 of file RayTool.cs.
_coneAngleReleaseDegrees
float OculusSampleFramework.RayTool._coneAngleReleaseDegrees private
Definition at line 88 of file RayTool.cs.
_currInteractableCastedAgainst
Interactable OculusSampleFramework.RayTool._currInteractableCastedAgainst = null private
Definition at line 87 of file RayTool.cs.
_farFieldMaxDistance
float OculusSampleFramework.RayTool._farFieldMaxDistance = 5f private
Definition at line 41 of file RayTool.cs.
_focusedInteractable
Interactable OculusSampleFramework.RayTool._focusedInteractable private
Definition at line 49 of file RayTool.cs.
_initialized
bool OculusSampleFramework.RayTool._initialized = false private
Definition at line 92 of file RayTool.cs.
_pinchStateModule
PinchStateModule OculusSampleFramework.RayTool._pinchStateModule = new PinchStateModule() private
Definition at line 48 of file RayTool.cs.
_primaryHits
RaycastHit [] OculusSampleFramework.RayTool._primaryHits = new RaycastHit[NUM_MAX_PRIMARY_HITS] private
Definition at line 90 of file RayTool.cs.
_rayToolView
RayToolView OculusSampleFramework.RayTool._rayToolView = null private
Definition at line 39 of file RayTool.cs.
_secondaryOverlapResults
Collider [] OculusSampleFramework.RayTool._secondaryOverlapResults = new Collider[NUM_MAX_SECONDARY_HITS] private
Definition at line 91 of file RayTool.cs.
COLLIDER_RADIUS
const float OculusSampleFramework.RayTool.COLLIDER_RADIUS = 0.01f static private
Definition at line 34 of file RayTool.cs.
MINIMUM_RAY_CAST_DISTANCE
const float OculusSampleFramework.RayTool.MINIMUM_RAY_CAST_DISTANCE = 0.8f static private
Definition at line 33 of file RayTool.cs.
NUM_COLLIDERS_TO_TEST
const int OculusSampleFramework.RayTool.NUM_COLLIDERS_TO_TEST = 20 static private
Definition at line 37 of file RayTool.cs.
NUM_MAX_PRIMARY_HITS
const int OculusSampleFramework.RayTool.NUM_MAX_PRIMARY_HITS = 10 static private
Definition at line 35 of file RayTool.cs.
NUM_MAX_SECONDARY_HITS
const int OculusSampleFramework.RayTool.NUM_MAX_SECONDARY_HITS = 25 static private
Definition at line 36 of file RayTool.cs.
Property Documentation
EnableState
override bool OculusSampleFramework.RayTool.EnableState get set
Definition at line 79 of file RayTool.cs.
        {
            get { return _rayToolView.EnableState; }
            set { _rayToolView.EnableState = value; }
        }
IsFarFieldTool
override bool OculusSampleFramework.RayTool.IsFarFieldTool get
Definition at line 74 of file RayTool.cs.
        {
            get { return true; }
        }
ToolInputState
override ToolInputState OculusSampleFramework.RayTool.ToolInputState get
Definition at line 51 of file RayTool.cs.
        {
            get
            {
                if (_pinchStateModule.PinchDownOnFocusedObject)
                {
                    return ToolInputState.PrimaryInputDown;
                }
                if (_pinchStateModule.PinchSteadyOnFocusedObject)
                {
                    return ToolInputState.PrimaryInputDownStay;
                }
                if (_pinchStateModule.PinchUpAndDownOnFocusedObject)
                {
                    return ToolInputState.PrimaryInputUp;
                }
                return ToolInputState.Inactive;
            }
        }
ToolTags
override InteractableToolTags OculusSampleFramework.RayTool.ToolTags get
Definition at line 43 of file RayTool.cs.
        {
            get { return InteractableToolTags.Ray; }
        }
The documentation for this class was generated from the following file:
Assets/Oculus/SampleFramework/Core/HandsInteraction/Scripts/Tools/RayTool.cs