VR_Test: Oculus.Interaction.OneGrabPhysicsJointTransformer Class Reference
Oculus.Interaction.OneGrabPhysicsJointTransformer Class Reference
A Transformer that moves the target using Physics joints Updates an internal kinematic rigidbody attached with a joint to the grabbable. It also supports adding custom joints for grabbing to improve stability on some constrained grabs.
Public Member Functions
void Initialize (IGrabbable grabbable)
void BeginTransform ()
void UpdateTransform ()
void EndTransform ()
void InjectOptionalCustomJoint (ConfigurableJoint customJoint)
Protected Member Functions
GameObject CreateJointHolder ()
Creates a disabled GameObject for holding the data of the desired custom joint.
Properties
bool IsKinematicGrab [get, set]
Private Member Functions
void OnValidate ()
Ensure the custom joint is set to a disabled GameObject, as it will be used just to read the values and duplicate them onto a new dynamically generated joint.
void FixedUpdate ()
Joint AddJoint (Rigidbody rigidbody)
Attaches the grabbable to a rigidbody using a joint. It will use the desired joint configuration set in _customJoint or the default one. rigidbody The rigidbody to be attached to this grabbable using a joint
void RemoveCurrentJoint ()
Destroys the current joint. Ideally it should just disable it, but Unity does not allow it.
Rigidbody GetGrabRigidbody ()
Generates (or retrieves from a cache) a rigidbody to be used for connecting to grabbable via joints.
void RemoveCurrentGrabRigidbody ()
Disables the currently grabbing rigidbody so it can be recycled for future grabs.
Rigidbody CreateRigidBody ()
Creates a new proxy RigidBody to anchor the grabbables.
Joint CreateDefaultJoint ()
When no custom joint is specified, this joint is used. An unbreakable Fixed joint without Preprocessing.
Static Private Member Functions
static ConfigurableJoint CloneJoint (ConfigurableJoint joint, GameObject destination)
Copy all the properties of a ConfigurableJoint onto a new one.
Private Attributes
ConfigurableJoint _customJoint
Optional. The custom joint to use when grabbing the grabbable. Set this field to a Joint in a disabled GameObject, it will be duplicated every time a new Grabber grabs this object, and the anchoring will be adjusted automatically. If not set a FixedJoint will be used. If the grabbable is already attached to something with a joint, using preprocessing here is not recommended.
bool _isKinematicGrab = true
Indicates if the grabbing rigidbody should be kinematic or not. Non-kinematic grabs can be interesting for simulating weight or more robust interactions.
Joint _joint
Rigidbody _grabbingRigidbody
IGrabbable _grabbable
Vector3 _targetPosition
Quaternion _targetRotation
Static Private Attributes
static List< Rigidbody > _cachedGrabbingRigidbodies = new List<Rigidbody>()
Detailed Description
A Transformer that moves the target using Physics joints Updates an internal kinematic rigidbody attached with a joint to the grabbable. It also supports adding custom joints for grabbing to improve stability on some constrained grabs.
Definition at line 33 of file OneGrabPhysicsJointTransformer.cs.
Member Function Documentation
AddJoint()
Joint Oculus.Interaction.OneGrabPhysicsJointTransformer.AddJoint (Rigidbody rigidbody) private
Attaches the grabbable to a rigidbody using a joint. It will use the desired joint configuration set in _customJoint or the default one. rigidbody The rigidbody to be attached to this grabbable using a joint
Returns
The generated joint
Definition at line 146 of file OneGrabPhysicsJointTransformer.cs.
        {
            RemoveCurrentJoint();
            Joint joint;
            if (_customJoint != null)
            {
                joint = CloneJoint(_customJoint, this.gameObject);
            }
            else
            {
                joint = CreateDefaultJoint();
            }
            joint.connectedBody = rigidbody;
            joint.autoConfigureConnectedAnchor = false;
            joint.anchor = joint.transform.InverseTransformPoint(rigidbody.transform.position);
            joint.connectedAnchor = Vector3.zero;
            return joint;
        }
References Oculus.Interaction.OneGrabPhysicsJointTransformer._customJoint, Oculus.Interaction.OneGrabPhysicsJointTransformer.CloneJoint(), Oculus.Interaction.OneGrabPhysicsJointTransformer.CreateDefaultJoint(), and Oculus.Interaction.OneGrabPhysicsJointTransformer.RemoveCurrentJoint().
BeginTransform()
void Oculus.Interaction.OneGrabPhysicsJointTransformer.BeginTransform ()
Implements Oculus.Interaction.ITransformer.
Definition at line 102 of file OneGrabPhysicsJointTransformer.cs.
        {
            Vector3 grabPointPosition = _grabbable.GrabPoints[0].position;
            Quaternion grabPointRotation = _grabbable.GrabPoints[0].rotation;
            _grabbingRigidbody = GetGrabRigidbody();
            _grabbingRigidbody.transform.SetPositionAndRotation(grabPointPosition, grabPointRotation);
            _joint = AddJoint(_grabbingRigidbody);
        }
CloneJoint()
static ConfigurableJoint Oculus.Interaction.OneGrabPhysicsJointTransformer.CloneJoint (ConfigurableJoint joint, GameObject destination) static private
Copy all the properties of a ConfigurableJoint onto a new one.
Parameters
joint The ConfigurableJoint to be copied.
destination The GameObject that will contain the new ConfigurableJoint.
Returns
The created Joint.
From ConfigurableJoint
Definition at line 262 of file OneGrabPhysicsJointTransformer.cs.
        {
            ConfigurableJoint clonedJoint = destination.gameObject.AddComponent<ConfigurableJoint>();
            //From Joint
            clonedJoint.connectedBody = joint.connectedBody;
            clonedJoint.axis = joint.axis;
            clonedJoint.anchor = joint.anchor;
            clonedJoint.connectedAnchor = joint.connectedAnchor;
            clonedJoint.autoConfigureConnectedAnchor = joint.autoConfigureConnectedAnchor;
            clonedJoint.breakForce = joint.breakForce;
            clonedJoint.breakTorque = joint.breakTorque;
            clonedJoint.enableCollision = joint.enableCollision;
            clonedJoint.enablePreprocessing = joint.enablePreprocessing;
            clonedJoint.massScale = joint.massScale;
            clonedJoint.connectedMassScale = joint.connectedMassScale;
            clonedJoint.projectionAngle = joint.projectionAngle;
            clonedJoint.projectionDistance = joint.projectionDistance;
            clonedJoint.projectionMode = joint.projectionMode;
            clonedJoint.slerpDrive = joint.slerpDrive;
            clonedJoint.angularYZDrive = joint.angularYZDrive;
            clonedJoint.angularXDrive = joint.angularXDrive;
            clonedJoint.rotationDriveMode = joint.rotationDriveMode;
            clonedJoint.targetAngularVelocity = joint.targetAngularVelocity;
            clonedJoint.targetRotation = joint.targetRotation;
            clonedJoint.zDrive = joint.zDrive;
            clonedJoint.yDrive = joint.yDrive;
            clonedJoint.xDrive = joint.xDrive;
            clonedJoint.targetVelocity = joint.targetVelocity;
            clonedJoint.targetPosition = joint.targetPosition;
            clonedJoint.angularZLimit = joint.angularZLimit;
            clonedJoint.angularYLimit = joint.angularYLimit;
            clonedJoint.highAngularXLimit = joint.highAngularXLimit;
            clonedJoint.lowAngularXLimit = joint.lowAngularXLimit;
            clonedJoint.linearLimit = joint.linearLimit;
            clonedJoint.angularYZLimitSpring = joint.angularYZLimitSpring;
            clonedJoint.angularXLimitSpring = joint.angularXLimitSpring;
            clonedJoint.linearLimitSpring = joint.linearLimitSpring;
            clonedJoint.angularZMotion = joint.angularZMotion;
            clonedJoint.angularYMotion = joint.angularYMotion;
            clonedJoint.angularXMotion = joint.angularXMotion;
            clonedJoint.zMotion = joint.zMotion;
            clonedJoint.yMotion = joint.yMotion;
            clonedJoint.xMotion = joint.xMotion;
            clonedJoint.secondaryAxis = joint.secondaryAxis;
            clonedJoint.configuredInWorldSpace = joint.configuredInWorldSpace;
            clonedJoint.swapBodies = joint.swapBodies;
            return clonedJoint;
        }
CreateDefaultJoint()
Joint Oculus.Interaction.OneGrabPhysicsJointTransformer.CreateDefaultJoint () private
When no custom joint is specified, this joint is used. An unbreakable Fixed joint without Preprocessing.
Returns
The generated FixedJoint
Definition at line 233 of file OneGrabPhysicsJointTransformer.cs.
        {
            Joint joint = this.gameObject.AddComponent<FixedJoint>();
            joint.breakForce = Mathf.Infinity;
            joint.enablePreprocessing = false;
            return joint;
        }
CreateJointHolder()
GameObject Oculus.Interaction.OneGrabPhysicsJointTransformer.CreateJointHolder () protected
Creates a disabled GameObject for holding the data of the desired custom joint.
Returns
A children GameObject for holding joint data.
Definition at line 245 of file OneGrabPhysicsJointTransformer.cs.
        {
            GameObject savedJointHolder = new GameObject();
            savedJointHolder.name = "Saved Joint";
            savedJointHolder.SetActive(false);
            savedJointHolder.transform.SetParent(this.transform);
            Rigidbody body = savedJointHolder.AddComponent<Rigidbody>();
            body.isKinematic = true;
            return savedJointHolder;
        }
CreateRigidBody()
Rigidbody Oculus.Interaction.OneGrabPhysicsJointTransformer.CreateRigidBody () private
Creates a new proxy RigidBody to anchor the grabbables.
Returns
A new kinematic Rigidbody
Definition at line 216 of file OneGrabPhysicsJointTransformer.cs.
        {
            GameObject go = new GameObject();
            go.name = "Proxy RigidBody";
            go.SetActive(false);
            go.transform.SetParent(null);
            Rigidbody body = go.AddComponent<Rigidbody>();
            body.useGravity = false;
            body.isKinematic = false;
            return body;
        }
EndTransform()
void Oculus.Interaction.OneGrabPhysicsJointTransformer.EndTransform ()
Implements Oculus.Interaction.ITransformer.
Definition at line 133 of file OneGrabPhysicsJointTransformer.cs.
        {
            RemoveCurrentJoint();
            RemoveCurrentGrabRigidbody();
        }
FixedUpdate()
void Oculus.Interaction.OneGrabPhysicsJointTransformer.FixedUpdate () private
Definition at line 124 of file OneGrabPhysicsJointTransformer.cs.
        {
            if (!_isKinematicGrab && _grabbingRigidbody != null)
            {
                _grabbingRigidbody.MovePosition(_targetPosition);
                _grabbingRigidbody.MoveRotation(_targetRotation);
            }
        }
GetGrabRigidbody()
Rigidbody Oculus.Interaction.OneGrabPhysicsJointTransformer.GetGrabRigidbody () private
Generates (or retrieves from a cache) a rigidbody to be used for connecting to grabbable via joints.
Returns
The generated rigidbody.
Definition at line 185 of file OneGrabPhysicsJointTransformer.cs.
        {
            Rigidbody rigidbody = _cachedGrabbingRigidbodies.Find(rb => !rb.gameObject.activeSelf);
            if (rigidbody == null)
            {
                rigidbody = CreateRigidBody();
                _cachedGrabbingRigidbodies.Add(rigidbody);
            }
            rigidbody.gameObject.SetActive(true);
            rigidbody.isKinematic = _isKinematicGrab;
            return rigidbody;
        }
References Oculus.Interaction.OneGrabPhysicsJointTransformer._isKinematicGrab, and Oculus.Interaction.OneGrabPhysicsJointTransformer.CreateRigidBody().
Initialize()
void Oculus.Interaction.OneGrabPhysicsJointTransformer.Initialize (IGrabbable grabbable)
Implements Oculus.Interaction.ITransformer.
Definition at line 97 of file OneGrabPhysicsJointTransformer.cs.
        {
            _grabbable = grabbable;
        }
InjectOptionalCustomJoint()
void Oculus.Interaction.OneGrabPhysicsJointTransformer.InjectOptionalCustomJoint (ConfigurableJoint customJoint)
Definition at line 316 of file OneGrabPhysicsJointTransformer.cs.
        {
            _customJoint = customJoint;
        }
OnValidate()
void Oculus.Interaction.OneGrabPhysicsJointTransformer.OnValidate () private
Ensure the custom joint is set to a disabled GameObject, as it will be used just to read the values and duplicate them onto a new dynamically generated joint.
Definition at line 80 of file OneGrabPhysicsJointTransformer.cs.
        {
            if (_customJoint != null)
            {
                if (_customJoint.gameObject == this.gameObject)
                {
                    Debug.LogWarning($"The OptionalCustomJoint must be placed in a disabled child GameObject. Moving it.", this.gameObject);
                    GameObject holder = CreateJointHolder();
                    _customJoint = CloneJoint(_customJoint, holder);
                }
                else
                {
                    _customJoint.gameObject.SetActive(false);
                }
            }
        }
References Oculus.Interaction.OneGrabPhysicsJointTransformer._customJoint, Oculus.Interaction.OneGrabPhysicsJointTransformer.CloneJoint(), and Oculus.Interaction.OneGrabPhysicsJointTransformer.CreateJointHolder().
RemoveCurrentGrabRigidbody()
void Oculus.Interaction.OneGrabPhysicsJointTransformer.RemoveCurrentGrabRigidbody () private
Disables the currently grabbing rigidbody so it can be recycled for future grabs.
Definition at line 202 of file OneGrabPhysicsJointTransformer.cs.
        {
            if (_grabbingRigidbody != null)
            {
                _grabbingRigidbody.gameObject.SetActive(false);
                _grabbingRigidbody.isKinematic = true;
                _grabbingRigidbody = null;
            }
        }
RemoveCurrentJoint()
void Oculus.Interaction.OneGrabPhysicsJointTransformer.RemoveCurrentJoint () private
Destroys the current joint. Ideally it should just disable it, but Unity does not allow it.
Definition at line 172 of file OneGrabPhysicsJointTransformer.cs.
        {
            if (_joint != null)
            {
                Destroy(_joint);
            }
        }
UpdateTransform()
void Oculus.Interaction.OneGrabPhysicsJointTransformer.UpdateTransform ()
Implements Oculus.Interaction.ITransformer.
Definition at line 112 of file OneGrabPhysicsJointTransformer.cs.
        {
            Pose grabPoint = _grabbable.GrabPoints[0];
            _targetPosition = grabPoint.position;
            _targetRotation = grabPoint.rotation;
            if (_isKinematicGrab)
            {
                _grabbingRigidbody.transform.SetPositionAndRotation(_targetPosition, _targetRotation);
            }
        }
Member Data Documentation
_cachedGrabbingRigidbodies
List<Rigidbody> Oculus.Interaction.OneGrabPhysicsJointTransformer._cachedGrabbingRigidbodies = new List<Rigidbody>() static private
Definition at line 69 of file OneGrabPhysicsJointTransformer.cs.
_customJoint
ConfigurableJoint Oculus.Interaction.OneGrabPhysicsJointTransformer._customJoint private
Optional. The custom joint to use when grabbing the grabbable. Set this field to a Joint in a disabled GameObject, it will be duplicated every time a new Grabber grabs this object, and the anchoring will be adjusted automatically. If not set a FixedJoint will be used. If the grabbable is already attached to something with a joint, using preprocessing here is not recommended.
Definition at line 44 of file OneGrabPhysicsJointTransformer.cs.
_grabbable
IGrabbable Oculus.Interaction.OneGrabPhysicsJointTransformer._grabbable private
Definition at line 71 of file OneGrabPhysicsJointTransformer.cs.
_grabbingRigidbody
Rigidbody Oculus.Interaction.OneGrabPhysicsJointTransformer._grabbingRigidbody private
Definition at line 68 of file OneGrabPhysicsJointTransformer.cs.
_isKinematicGrab
bool Oculus.Interaction.OneGrabPhysicsJointTransformer._isKinematicGrab = true private
Indicates if the grabbing rigidbody should be kinematic or not. Non-kinematic grabs can be interesting for simulating weight or more robust interactions.
Definition at line 53 of file OneGrabPhysicsJointTransformer.cs.
_joint
Joint Oculus.Interaction.OneGrabPhysicsJointTransformer._joint private
Definition at line 67 of file OneGrabPhysicsJointTransformer.cs.
_targetPosition
Vector3 Oculus.Interaction.OneGrabPhysicsJointTransformer._targetPosition private
Definition at line 73 of file OneGrabPhysicsJointTransformer.cs.
_targetRotation
Quaternion Oculus.Interaction.OneGrabPhysicsJointTransformer._targetRotation private
Definition at line 74 of file OneGrabPhysicsJointTransformer.cs.
Property Documentation
IsKinematicGrab
bool Oculus.Interaction.OneGrabPhysicsJointTransformer.IsKinematicGrab get set
Definition at line 55 of file OneGrabPhysicsJointTransformer.cs.
        {
            get
            {
                return _isKinematicGrab;
            }
            set
            {
                _isKinematicGrab = value;
            }
        }
The documentation for this class was generated from the following file:
Assets/Oculus/Interaction/Runtime/Scripts/Interaction/Grabbable/OneGrabPhysicsJointTransformer.cs