VR_Test: Meta.WitAi.Lib.Mic Class Reference
Meta.WitAi.Lib.Mic Class Reference
Public Member Functions
void CheckForInput ()
Safely starts mic if possible.
void SafeStartMicrophone ()
void RefreshMicDevices ()
Refresh mic device list.
void ChangeDevice (int index)
Changes to a Mic device for Recording.
void StartRecording (int sampleLen=10)
Starts to stream the input of the current Mic device.
void StopRecording ()
Ends the Mic stream.
void StartRecording (int sampleLen)
void StopRecording ()
void CheckForInput ()
Checks for input.
Properties
bool IsRecording [get, private set]
Whether the microphone is running.
AudioEncoding AudioEncoding = new AudioEncoding() [get]
Settings used to encode audio. Defaults to optimal server settings.
float[] Sample [get, private set]
Last populated audio sample.
int SampleDurationMS [get, private set]
Sample duration/length in milliseconds.
bool IsInputAvailable [get]
Check if input is available & start if possible.
int SampleLength [get]
The length of the sample float array.
AudioClip AudioClip [get, private set]
The AudioClip currently being streamed in the Mic.
int AudioClipSampleRate [get, set]
List< string > Devices [get]
List of all the available Mic devices.
int CurrentDeviceIndex = -1 [get, private set]
Index of the current Mic device in m_Devices.
string CurrentDeviceName [get]
Gets the name of the Mic device currently in use.
int MicPosition [get]
static Mic Instance [get]
Properties inherited from Meta.WitAi.Interfaces.IAudioInputSource
Events
Action OnStartRecording
Invoked when the instance starts Recording.
Action OnStartRecordingFailed
Invoked when an AudioClip couldn't be created to start recording.
Action< int, float[], float > OnSampleReady
Invoked everytime an audio frame is collected. Includes the frame.
Action OnStopRecording
Invoked when the instance stop Recording.
Events inherited from Meta.WitAi.Interfaces.IAudioInputSource
Action OnStartRecording
Invoked when the instance starts Recording.
Action OnStartRecordingFailed
Invoked when an AudioClip couldn't be created to start recording.
Action< int, float[], float > OnSampleReady
Invoked everytime an audio frame is collected. Includes the frame.
Action OnStopRecording
Invoked when the instance stop Recording.
Private Member Functions
void OnEnable ()
void OnDisable ()
void OnApplicationFocus (bool hasFocus)
void OnApplicationPause (bool pauseStatus)
void OnDestroy ()
void StartMicrophone ()
void StopMicrophone ()
IEnumerator ReadRawAudio ()
bool MicrophoneIsRecording (string device)
string[] MicrophoneGetDevices ()
int MicrophoneGetPosition (string device)
bool MicrophoneIsRecording (string device)
string[] MicrophoneGetDevices ()
int MicrophoneGetPosition (string device)
Private Attributes
int _audioClipSampleRate = 16000
List< string > _devices
int m_SampleCount = 0
Static Private Attributes
const bool MIC_CLIP_LOOP = true
const int MIC_CLIP_CHANNELS = 1
const int MS_TO_SECONDS = 1000
static Mic m_Instance
Detailed Description
Definition at line 38 of file Mic.cs.
Member Function Documentation
ChangeDevice()
void Meta.WitAi.Lib.Mic.ChangeDevice (int index)
Changes to a Mic device for Recording.
Parameters
index The index of the Mic device. Refer to Devices
Definition at line 319 of file Mic.cs.
        {
            StopMicrophone();
            CurrentDeviceIndex = index;
            StartMicrophone();
        }
References Meta.WitAi.Lib.Mic.CurrentDeviceIndex.
CheckForInput() [1/2]
void Meta.WitAi.Lib.Mic.CheckForInput ()
Safely starts mic if possible.
Implements Meta.WitAi.Interfaces.IAudioInputSource.
CheckForInput() [2/2]
void Meta.WitAi.Lib.Mic.CheckForInput ()
Checks for input.
Implements Meta.WitAi.Interfaces.IAudioInputSource.
Definition at line 55 of file Mic.cs.
        {
        }
MicrophoneGetDevices() [1/2]
string[] Meta.WitAi.Lib.Mic.MicrophoneGetDevices () private
Definition at line 476 of file Mic.cs.
        {
#if UNITY_WEBGL && !UNITY_EDITOR
            return new string[] {};
#else
            return Microphone.devices;
#endif
        }
MicrophoneGetDevices() [2/2]
string[] Meta.WitAi.Lib.Mic.MicrophoneGetDevices () private
Definition at line 64 of file Mic.cs.
        {
            VLog.E("Direct microphone use is not currently supported in WebGL.");
            return new string[] {};
        }
MicrophoneGetPosition() [1/2]
int Meta.WitAi.Lib.Mic.MicrophoneGetPosition (string device) private
Definition at line 485 of file Mic.cs.
        {
#if UNITY_WEBGL && !UNITY_EDITOR
            // This should (probably) never happen, since the Start/Stop Recording methods will
            // silently fail under webGL.
            return 0;
#else
            return Microphone.GetPosition(device);
#endif
        }
MicrophoneGetPosition() [2/2]
int Meta.WitAi.Lib.Mic.MicrophoneGetPosition (string device) private
Definition at line 70 of file Mic.cs.
        {
            // This should (probably) never happen, since the Start/Stop Recording methods will
            // silently fail under webGL.
            return 0;
        }
MicrophoneIsRecording() [1/2]
bool Meta.WitAi.Lib.Mic.MicrophoneIsRecording (string device) private
Definition at line 467 of file Mic.cs.
        {
#if UNITY_WEBGL && !UNITY_EDITOR
            return false;
#else
            return !string.IsNullOrEmpty(device) && Microphone.IsRecording(device);
#endif
        }
MicrophoneIsRecording() [2/2]
bool Meta.WitAi.Lib.Mic.MicrophoneIsRecording (string device) private
Definition at line 59 of file Mic.cs.
        {
            return false;
        }
OnApplicationFocus()
void Meta.WitAi.Lib.Mic.OnApplicationFocus (bool hasFocus) private
Definition at line 224 of file Mic.cs.
        {
            #if UNITY_ANDROID && !UNITY_EDITOR
            if (hasFocus && IsRecording)
            {
                VLog.D($"Mic was recording and app is resumed, resuming listening on {CurrentDeviceName}");
                SafeStartMicrophone();
                StartCoroutine(ReadRawAudio());
            }
            else if (!hasFocus)
            {
                VLog.D($"Stopping listening on {CurrentDeviceName} due to loss of focus.");
                StopMicrophone();
            }
            #endif
        }
OnApplicationPause()
void Meta.WitAi.Lib.Mic.OnApplicationPause (bool pauseStatus) private
Definition at line 241 of file Mic.cs.
        {
            #if UNITY_ANDROID && !UNITY_EDITOR
            if (pauseStatus)
            {
                VLog.D($"Stopping listening on {CurrentDeviceName} due to application pause.");
                StopMicrophone();
            }
            #endif
        }
OnDestroy()
void Meta.WitAi.Lib.Mic.OnDestroy () private
Definition at line 252 of file Mic.cs.
        {
            StopMicrophone();
        }
OnDisable()
void Meta.WitAi.Lib.Mic.OnDisable () private
Definition at line 219 of file Mic.cs.
        {
            StopMicrophone();
        }
OnEnable()
void Meta.WitAi.Lib.Mic.OnEnable () private
Definition at line 214 of file Mic.cs.
        {
            SafeStartMicrophone();
        }
ReadRawAudio()
IEnumerator Meta.WitAi.Lib.Mic.ReadRawAudio () private
Definition at line 413 of file Mic.cs.
        {
            int loops = 0;
            int readAbsPos = MicrophoneGetPosition(CurrentDeviceName);
            int prevPos = readAbsPos;
            float[] temp = new float[Sample.Length];
            while (AudioClip != null && MicrophoneIsRecording(CurrentDeviceName) && IsRecording)
            {
                bool isNewDataAvailable = true;
                while (isNewDataAvailable && AudioClip)
                {
                    int currPos = MicrophoneGetPosition(CurrentDeviceName);
                    if (currPos < prevPos)
                        loops++;
                    prevPos = currPos;
                    var currAbsPos = loops * AudioClip.samples + currPos;
                    var nextReadAbsPos = readAbsPos + temp.Length;
                    float levelMax = 0;
                    if (nextReadAbsPos < currAbsPos)
                    {
                        AudioClip.GetData(temp, readAbsPos % AudioClip.samples);
                        for (int i = 0; i < temp.Length; i++)
{
                            float wavePeak = temp[i] * temp[i];
                            if (levelMax < wavePeak)
{
                                levelMax = wavePeak;
                            }
                        }
                        Sample = temp;
                        m_SampleCount++;
                        OnSampleReady?.Invoke(m_SampleCount, Sample, levelMax);
                        readAbsPos = nextReadAbsPos;
                        isNewDataAvailable = true;
                    }
                    else
                        isNewDataAvailable = false;
                }
                yield return null;
            }
        }
RefreshMicDevices()
void Meta.WitAi.Lib.Mic.RefreshMicDevices ()
Refresh mic device list.
Definition at line 291 of file Mic.cs.
        {
            string oldDevice = CurrentDeviceName;
            _devices = new List<string>();
            UnityEngine.Profiling.Profiler.BeginSample("Microphone Devices");
            string[] micIDs = MicrophoneGetDevices();
            if (micIDs != null)
            {
                _devices.AddRange(micIDs);
            }
            if (_devices.Count == 0)
            {
                VLog.W("No mics found");
            }
            else
            {
                VLog.D($"Found {_devices.Count} Mics");
            }
            UnityEngine.Profiling.Profiler.EndSample();
            CurrentDeviceIndex = _devices.IndexOf(oldDevice);
        }
References Meta.WitAi.Lib.Mic.CurrentDeviceIndex, Meta.WitAi.Lib.Mic.CurrentDeviceName, Meta.WitAi.VLog.D(), and Meta.WitAi.VLog.W().
SafeStartMicrophone()
void Meta.WitAi.Lib.Mic.SafeStartMicrophone ()
Definition at line 258 of file Mic.cs.
        {
            // Can't start if inactive
            if (!gameObject.activeInHierarchy)
            {
                return;
            }
            // Look for devices
            if (Devices == null || Devices.Count == 0)
            {
                // Check for devices
                RefreshMicDevices();
                // None found
                if (Devices == null || Devices.Count == 0)
                {
                    return;
                }
            }
            // Ignore if already setup & recording
            string micID = CurrentDeviceName;
            if (!string.IsNullOrEmpty(micID) && AudioClip != null && string.Equals(micID, AudioClip.name) && MicrophoneIsRecording(micID))
            {
                return;
            }
            // Set device
            ChangeDevice(CurrentDeviceIndex < 0 ? 0 : CurrentDeviceIndex);
        }
StartMicrophone()
void Meta.WitAi.Lib.Mic.StartMicrophone () private
Definition at line 326 of file Mic.cs.
        {
#if !UNITY_WEBGL || UNITY_EDITOR
            VLog.D("Reserved mic " + CurrentDeviceName);
            AudioClip = Microphone.Start(CurrentDeviceName, MIC_CLIP_LOOP, MIC_CLIP_CHANNELS, AudioClipSampleRate);
            AudioClip.name = CurrentDeviceName;
            // Init the num of channels from AudioClip in
            // the AudioEncoding
            AudioEncoding.numChannels = AudioClip.channels;
#endif
        }
StartRecording() [1/2]
void Meta.WitAi.Lib.Mic.StartRecording (int sampleLen)
Implements Meta.WitAi.Interfaces.IAudioInputSource.
Definition at line 41 of file Mic.cs.
        {
            VLog.E("Direct microphone use is not currently supported in WebGL.");
            OnStartRecordingFailed?.Invoke();
        }
StartRecording() [2/2]
void Meta.WitAi.Lib.Mic.StartRecording (int sampleLen = 10)
Starts to stream the input of the current Mic device.
Implements Meta.WitAi.Interfaces.IAudioInputSource.
Definition at line 362 of file Mic.cs.
        {
            // Still unavailable, exit
            if (!IsInputAvailable)
            {
                return;
            }
            // Stop recording if doing so
            StopRecording();
            IsRecording = true;
            SampleDurationMS = sampleLen;
            if (AudioClip)
            {
                Sample = new float[AudioClipSampleRate / MS_TO_SECONDS * SampleDurationMS * AudioClip.channels];
                StartCoroutine(ReadRawAudio());
#if !UNITY_WEBGL || UNITY_EDITOR
                // Make sure we seek before we start reading data
                MicrophoneGetPosition(CurrentDeviceName);
                VLog.D("Started recording with " + CurrentDeviceName);
#endif
                if (OnStartRecording != null)
                    OnStartRecording.Invoke();
            }
            else
            {
                OnStartRecordingFailed.Invoke();
            }
        }
References Meta.WitAi.Lib.Mic.AudioClip, Meta.WitAi.Lib.Mic.CurrentDeviceName, Meta.WitAi.VLog.D(), Meta.WitAi.Lib.Mic.IsInputAvailable, Meta.WitAi.Lib.Mic.IsRecording, Meta.WitAi.Lib.Mic.OnStartRecording, Meta.WitAi.Lib.Mic.OnStartRecordingFailed, Meta.WitAi.Lib.Mic.SampleDurationMS, and Meta.WitAi.Lib.Mic.StopRecording().
StopMicrophone()
void Meta.WitAi.Lib.Mic.StopMicrophone () private
Definition at line 338 of file Mic.cs.
        {
            if (MicrophoneIsRecording(CurrentDeviceName))
            {
#if !UNITY_WEBGL || UNITY_EDITOR
                VLog.D("Released mic " + CurrentDeviceName);
                Microphone.End(CurrentDeviceName);
#endif
            }
            if (AudioClip != null)
            {
                AudioClip.DestroySafely();
                AudioClip = null;
            }
        }
StopRecording() [1/2]
void Meta.WitAi.Lib.Mic.StopRecording ()
Ends the Mic stream.
Implements Meta.WitAi.Interfaces.IAudioInputSource.
Definition at line 400 of file Mic.cs.
        {
            if (!IsRecording) return;
            IsRecording = false;
            StopCoroutine(ReadRawAudio());
            VLog.D("Stopped recording with " + CurrentDeviceName);
            if (OnStopRecording != null)
                OnStopRecording.Invoke();
        }
References Meta.WitAi.Lib.Mic.CurrentDeviceName, Meta.WitAi.VLog.D(), Meta.WitAi.Lib.Mic.IsRecording, and Meta.WitAi.Lib.Mic.OnStopRecording.
StopRecording() [2/2]
void Meta.WitAi.Lib.Mic.StopRecording ()
Implements Meta.WitAi.Interfaces.IAudioInputSource.
Definition at line 47 of file Mic.cs.
        {
            OnStopRecording?.Invoke();
        }
Member Data Documentation
_audioClipSampleRate
int Meta.WitAi.Lib.Mic._audioClipSampleRate = 16000 private
Definition at line 102 of file Mic.cs.
_devices
List<string> Meta.WitAi.Lib.Mic._devices private
Definition at line 138 of file Mic.cs.
m_Instance
Mic Meta.WitAi.Lib.Mic.m_Instance static private
Definition at line 197 of file Mic.cs.
m_SampleCount
int Meta.WitAi.Lib.Mic.m_SampleCount = 0 private
Definition at line 158 of file Mic.cs.
MIC_CLIP_CHANNELS
const int Meta.WitAi.Lib.Mic.MIC_CLIP_CHANNELS = 1 static private
Definition at line 121 of file Mic.cs.
MIC_CLIP_LOOP
const bool Meta.WitAi.Lib.Mic.MIC_CLIP_LOOP = true static private
Definition at line 120 of file Mic.cs.
MS_TO_SECONDS
const int Meta.WitAi.Lib.Mic.MS_TO_SECONDS = 1000 static private
Definition at line 122 of file Mic.cs.
Property Documentation
AudioClip
AudioClip Meta.WitAi.Lib.Mic.AudioClip get private set
The AudioClip currently being streamed in the Mic.
Definition at line 99 of file Mic.cs.
{ get; private set; }
AudioClipSampleRate
int Meta.WitAi.Lib.Mic.AudioClipSampleRate get set
Definition at line 103 of file Mic.cs.
        {
            get => _audioClipSampleRate;
            set
            {
                if (IsRecording)
                {
                    Debug.LogError($"Mic - Cannot set audio sample rate once already recording\nRecording Rate: {_audioClipSampleRate}\nDesired Rate: {value}");
                }
                else
                {
                    _audioClipSampleRate = value;
                }
            }
        }
AudioEncoding
AudioEncoding Meta.WitAi.Lib.Mic.AudioEncoding = new AudioEncoding() get
Settings used to encode audio. Defaults to optimal server settings.
Implements Meta.WitAi.Interfaces.IAudioInputSource.
Definition at line 53 of file Mic.cs.
{ get; } = new AudioEncoding();
CurrentDeviceIndex
int Meta.WitAi.Lib.Mic.CurrentDeviceIndex = -1 get private set
Index of the current Mic device in m_Devices.
Definition at line 143 of file Mic.cs.
{ get; private set; } = -1;
CurrentDeviceName
string Meta.WitAi.Lib.Mic.CurrentDeviceName get
Gets the name of the Mic device currently in use.
Definition at line 148 of file Mic.cs.
        {
            get
            {
                if (CurrentDeviceIndex < 0 || CurrentDeviceIndex >= Devices.Count)
                    return string.Empty;
                return Devices[CurrentDeviceIndex];
            }
        }
Devices
List<string> Meta.WitAi.Lib.Mic.Devices get
List of all the available Mic devices.
Definition at line 127 of file Mic.cs.
        {
            get
            {
                if (null == _devices)
                {
                    RefreshMicDevices();
                }
                return _devices;
            }
        }
Instance
Mic Meta.WitAi.Lib.Mic.Instance static get
Definition at line 199 of file Mic.cs.
        {
            get
            {
                if (m_Instance == null)
                    m_Instance = GameObject.FindObjectOfType<Mic>();
                if (m_Instance == null && Application.isPlaying)
                {
                    m_Instance = new GameObject("UniMic.Mic").AddComponent<Mic>();
                    DontDestroyOnLoad(m_Instance.gameObject);
                }
                return m_Instance;
            }
        }
IsInputAvailable
bool Meta.WitAi.Lib.Mic.IsInputAvailable get
Check if input is available & start if possible.
Implements Meta.WitAi.Interfaces.IAudioInputSource.
Definition at line 68 of file Mic.cs.
        {
            get
            {
                // Has not begun
                if (!AudioClip)
                {
                    // Try begin
                    SafeStartMicrophone();
                }
                // True if audio clip exists
                return AudioClip;
            }
        }
IsRecording
bool Meta.WitAi.Lib.Mic.IsRecording get private set
Whether the microphone is running.
Implements Meta.WitAi.Interfaces.IAudioInputSource.
Definition at line 48 of file Mic.cs.
{ get; private set; }
MicPosition
int Meta.WitAi.Lib.Mic.MicPosition get private
Definition at line 160 of file Mic.cs.
Sample
float [] Meta.WitAi.Lib.Mic.Sample get private set
Last populated audio sample.
Definition at line 58 of file Mic.cs.
{ get; private set; }
SampleDurationMS
int Meta.WitAi.Lib.Mic.SampleDurationMS get private set
Sample duration/length in milliseconds.
Definition at line 63 of file Mic.cs.
{ get; private set; }
SampleLength
int Meta.WitAi.Lib.Mic.SampleLength get
The length of the sample float array.
Definition at line 91 of file Mic.cs.
        {
            get { return AudioEncoding.samplerate * SampleDurationMS / 1000; }
        }
Event Documentation
OnSampleReady
Action< int, float[], float > Meta.WitAi.Lib.Mic.OnSampleReady
Invoked everytime an audio frame is collected. Includes the frame.
Definition at line 182 of file Mic.cs.
OnStartRecording
Action Meta.WitAi.Lib.Mic.OnStartRecording
Invoked when the instance starts Recording.
Definition at line 172 of file Mic.cs.
OnStartRecordingFailed
Action Meta.WitAi.Lib.Mic.OnStartRecordingFailed
Invoked when an AudioClip couldn't be created to start recording.
Definition at line 177 of file Mic.cs.
OnStopRecording
Action Meta.WitAi.Lib.Mic.OnStopRecording
Invoked when the instance stop Recording.
Definition at line 187 of file Mic.cs.
The documentation for this class was generated from the following files:
Assets/Oculus/Voice/Lib/Wit.ai/Scripts/Runtime/Lib/Mic/Other/Mic.cs
Assets/Oculus/Voice/Lib/Wit.ai/Scripts/Runtime/Lib/Mic/WebGL/Mic.cs