VR_Test: Meta.Conduit.ManifestLoader Class Reference
Meta.Conduit.ManifestLoader Class Reference
Loads the manifest and resolves its actions so they can be used during dispatching.
Public Member Functions
Manifest LoadManifest (string manifestLocalPath)
Manifest LoadManifestFromString (string manifestText)
Detailed Description
Loads the manifest and resolves its actions so they can be used during dispatching.
Definition at line 18 of file ManifestLoader.cs.
Member Function Documentation
LoadManifest()
Manifest Meta.Conduit.ManifestLoader.LoadManifest (string manifestLocalPath)
Definition at line 21 of file ManifestLoader.cs.
        {
            var extIndex = manifestLocalPath.LastIndexOf('.');
            var ignoreEnd = extIndex == -1 ? manifestLocalPath : manifestLocalPath.Substring(0, extIndex);
            var jsonFile = Resources.Load<TextAsset>(ignoreEnd);
            if (jsonFile == null)
            {
                VLog.E($"Conduit Error - No Manifest found at Resources/{manifestLocalPath}");
                return null;
            }
            var rawJson = jsonFile.text;
            return LoadManifestFromString(rawJson);
        }
References Meta.WitAi.VLog.E(), and Meta.Conduit.ManifestLoader.LoadManifestFromString().
LoadManifestFromString()
Manifest Meta.Conduit.ManifestLoader.LoadManifestFromString (string manifestText)
Definition at line 37 of file ManifestLoader.cs.
        {
            var manifest = JsonConvert.DeserializeObject<Manifest>(manifestText, null, true);
            if (manifest.ResolveActions())
            {
                VLog.D($"Successfully Loaded Conduit manifest");
            }
            else
            {
                VLog.E($"Fail to resolve actions from Conduit manifest");
            }
            return manifest;
        }
References Meta.WitAi.VLog.D(), and Meta.WitAi.VLog.E().
The documentation for this class was generated from the following file:
Assets/Oculus/Voice/Lib/Wit.ai/Lib/Conduit/Runtime/Data/ManifestLoader.cs