VR_Test: Oculus.Interaction.HandGrab.Visuals.HandGhost Class Reference
Oculus.Interaction.HandGrab.Visuals.HandGhost Class Reference
A static (non-user controlled) representation of a hand. This script is used to be able to manually visualize hand grab poses.
Public Member Functions
void SetPose (HandGrabPose handGrabPose)
Relay to the Puppet to set the ghost hand to the desired static pose.
void SetPose (HandPose userPose, Pose rootPose)
void SetRootPose (Pose rootPose, Transform relativeTo)
Moves the underlying puppet so the wrist point aligns with the given parameters.
void InjectAllHandGhost (HandPuppet puppet)
void InjectHandPuppet (HandPuppet puppet)
void InjectOptionalHandGrabPose (HandGrabPose handGrabPose)
Protected Member Functions
virtual void Reset ()
virtual void OnValidate ()
virtual void Start ()
Private Attributes
HandPuppet _puppet
The puppet is used to actually move the representation of the hand.
HandGrabPose _handGrabPose
The HandGrab point can be set so the ghost automatically adopts the desired pose of said point.
Detailed Description
A static (non-user controlled) representation of a hand. This script is used to be able to manually visualize hand grab poses.
Definition at line 30 of file HandGhost.cs.
Member Function Documentation
InjectAllHandGhost()
void Oculus.Interaction.HandGrab.Visuals.HandGhost.InjectAllHandGhost (HandPuppet puppet)
Definition at line 118 of file HandGhost.cs.
        {
            InjectHandPuppet(puppet);
        }
InjectHandPuppet()
void Oculus.Interaction.HandGrab.Visuals.HandGhost.InjectHandPuppet (HandPuppet puppet)
Definition at line 122 of file HandGhost.cs.
        {
            _puppet = puppet;
        }
InjectOptionalHandGrabPose()
void Oculus.Interaction.HandGrab.Visuals.HandGhost.InjectOptionalHandGrabPose (HandGrabPose handGrabPose)
Definition at line 126 of file HandGhost.cs.
        {
            _handGrabPose = handGrabPose;
        }
OnValidate()
virtual void Oculus.Interaction.HandGrab.Visuals.HandGhost.OnValidate () protected virtual
Definition at line 53 of file HandGhost.cs.
        {
            if (_puppet == null)
            {
                return;
            }
            if (_handGrabPose == null)
            {
                HandGrabPose point = this.GetComponentInParent<HandGrabPose>();
                if (point != null)
                {
                    SetPose(point);
                }
            }
            else if (_handGrabPose != null)
            {
                SetPose(_handGrabPose);
            }
        }
Reset()
virtual void Oculus.Interaction.HandGrab.Visuals.HandGhost.Reset () protected virtual
Definition at line 47 of file HandGhost.cs.
        {
            _puppet = this.GetComponent<HandPuppet>();
            _handGrabPose = this.GetComponentInParent<HandGrabPose>();
        }
SetPose() [1/2]
void Oculus.Interaction.HandGrab.Visuals.HandGhost.SetPose (HandGrabPose handGrabPose)
Relay to the Puppet to set the ghost hand to the desired static pose.
Parameters
handGrabPose The point to read the HandPose from
Definition at line 84 of file HandGhost.cs.
        {
            HandPose userPose = handGrabPose.HandPose;
            if (userPose == null)
            {
                return;
            }
            _puppet.SetJointRotations(userPose.JointRotations);
            SetRootPose(handGrabPose.RelativePose, handGrabPose.RelativeTo);
        }
References Oculus.Interaction.HandGrab.Visuals.HandGhost._puppet, Oculus.Interaction.HandGrab.HandPose.JointRotations, Oculus.Interaction.HandGrab.HandGrabPose.RelativePose, Oculus.Interaction.HandGrab.HandGrabPose.RelativeTo, Oculus.Interaction.HandGrab.Visuals.HandPuppet.SetJointRotations(), and Oculus.Interaction.HandGrab.Visuals.HandGhost.SetRootPose().
SetPose() [2/2]
void Oculus.Interaction.HandGrab.Visuals.HandGhost.SetPose (HandPose userPose, Pose rootPose)
Definition at line 96 of file HandGhost.cs.
        {
            _puppet.SetJointRotations(userPose.JointRotations);
            _puppet.SetRootPose(rootPose);
        }
SetRootPose()
void Oculus.Interaction.HandGrab.Visuals.HandGhost.SetRootPose (Pose rootPose, Transform relativeTo)
Moves the underlying puppet so the wrist point aligns with the given parameters.
Parameters
rootPose The relative wrist pose to align the hand to
relativeTo The object to use as anchor
Definition at line 107 of file HandGhost.cs.
        {
            Pose pose = rootPose;
            if (relativeTo != null)
            {
                pose = PoseUtils.GlobalPoseScaled(relativeTo, rootPose);
            }
            _puppet.SetRootPose(pose);
        }
References Oculus.Interaction.HandGrab.Visuals.HandGhost._puppet, Oculus.Interaction.PoseUtils.GlobalPoseScaled(), and Oculus.Interaction.HandGrab.Visuals.HandPuppet.SetRootPose().
Start()
virtual void Oculus.Interaction.HandGrab.Visuals.HandGhost.Start () protected virtual
Definition at line 75 of file HandGhost.cs.
        {
            this.AssertField(_puppet, nameof(_puppet));
        }
Member Data Documentation
_handGrabPose
HandGrabPose Oculus.Interaction.HandGrab.Visuals.HandGhost._handGrabPose private
The HandGrab point can be set so the ghost automatically adopts the desired pose of said point.
Definition at line 44 of file HandGhost.cs.
_puppet
HandPuppet Oculus.Interaction.HandGrab.Visuals.HandGhost._puppet private
The puppet is used to actually move the representation of the hand.
Definition at line 36 of file HandGhost.cs.
The documentation for this class was generated from the following file:
Assets/Oculus/Interaction/Runtime/Scripts/Grab/Visuals/HandGhost.cs