VR_Test: Meta.Voice.Samples.Shapes.ColorChanger Class Reference
Meta.Voice.Samples.Shapes.ColorChanger Class Reference
Public Member Functions
void UpdateColor (WitResponseNode commandResult)
Directly processes a command result getting the slots with WitResult utilities.
void UpdateColor (string[] colorNames, string[] shapes)
Updates the colors of a set of shape, or all colors split across the shapes.
void UpdateColorAllShapes (string[] colorNames)
Updates the colors of the shapes, with colours split across the shapes.
Private Member Functions
void SetColor (Transform trans, Color color)
Sets the color of the specified transform.
Detailed Description
Definition at line 28 of file ColorChanger.cs.
Member Function Documentation
SetColor()
void Meta.Voice.Samples.Shapes.ColorChanger.SetColor (Transform trans, Color color) private
Sets the color of the specified transform.
Parameters
trans
color
Definition at line 35 of file ColorChanger.cs.
        {
            trans.GetComponent<Renderer>().material.color = color;
        }
UpdateColor() [1/2]
void Meta.Voice.Samples.Shapes.ColorChanger.UpdateColor (string[] colorNames, string[] shapes)
Updates the colors of a set of shape, or all colors split across the shapes.
Parameters
colorNames The names of the colors to be processed
shapes The shape names or if empty all shapes
Definition at line 56 of file ColorChanger.cs.
        {
            if (shapes.Length != 0 && colorNames.Length != shapes.Length)
            {
                return;
            }
            if (shapes.Length == 0 || shapes[0] == "color"){
                UpdateColorAllShapes(colorNames);
                return;
            }
            for(var entity = 0; entity < colorNames.Length; entity++)
            {
                if (!ColorUtility.TryParseHtmlString(colorNames[entity], out var color)) return;
                for (int i = 0; i < transform.childCount; i++)
                {
                    Transform child = transform.GetChild(i);
                    if (String.Equals(shapes[entity], child.name,
                            StringComparison.CurrentCultureIgnoreCase))
                    {
                        SetColor(child, color);
                        break;
                    }
                }
            }
        }
References Meta.Voice.Samples.Shapes.ColorChanger.SetColor(), and Meta.Voice.Samples.Shapes.ColorChanger.UpdateColorAllShapes().
UpdateColor() [2/2]
void Meta.Voice.Samples.Shapes.ColorChanger.UpdateColor (WitResponseNode commandResult)
Directly processes a command result getting the slots with WitResult utilities.
Parameters
commandResult Result data from Wit.ai activation to be processed
Definition at line 44 of file ColorChanger.cs.
        {
            string[] colorNames = commandResult.GetAllEntityValues("color:color");
            string[] shapes = commandResult.GetAllEntityValues("shape:shape");
            UpdateColor(colorNames, shapes);
        }
References Meta.Voice.Samples.Shapes.ColorChanger.UpdateColor().
UpdateColorAllShapes()
void Meta.Voice.Samples.Shapes.ColorChanger.UpdateColorAllShapes (string[] colorNames)
Updates the colors of the shapes, with colours split across the shapes.
Parameters
colorNames The names of the colors to be processed
Definition at line 87 of file ColorChanger.cs.
        {
            var unspecifiedShape = 0;
            for(var entity = 0; entity < colorNames.Length; entity++)
            {
                if (!ColorUtility.TryParseHtmlString(colorNames[entity], out var color)) return;
                var splitLimit = (transform.childCount/colorNames.Length) * (entity+1);
                while (unspecifiedShape < splitLimit)
                {
                    SetColor(transform.GetChild(unspecifiedShape), color);
                    unspecifiedShape++;
                }
            }
        }
References Meta.Voice.Samples.Shapes.ColorChanger.SetColor().
The documentation for this class was generated from the following file:
Assets/Oculus/Voice/Samples/Shapes/Scripts/ColorChanger.cs