VR_Test: Meta.WitAi.TTS.TTSService Class Reference
Meta.WitAi.TTS.TTSService Class Reference abstract
Public Member Functions
virtual string GetInvalidError ()
Returns error if invalid.
string GetFinalText (string textToSpeak, TTSVoiceSettings voiceSettings)
Gets the text to be spoken after applying all relevant voice settings.
virtual string GetClipID (string textToSpeak, TTSVoiceSettings voiceSettings)
Obtain unique id for clip data.
TTSClipData Load (string textToSpeak, Action< TTSClipData, string > onStreamReady=null)
TTSClipData Load (string textToSpeak, string presetVoiceId, Action< TTSClipData, string > onStreamReady=null)
TTSClipData Load (string textToSpeak, string presetVoiceId, TTSDiskCacheSettings diskCacheSettings, Action< TTSClipData, string > onStreamReady=null)
TTSClipData Load (string textToSpeak, TTSVoiceSettings voiceSettings, TTSDiskCacheSettings diskCacheSettings, Action< TTSClipData, string > onStreamReady=null)
virtual TTSClipData Load (string textToSpeak, string clipID, TTSVoiceSettings voiceSettings, TTSDiskCacheSettings diskCacheSettings, Action< TTSClipData, string > onStreamReady)
Perform a request for a TTS audio clip.
void UnloadAll ()
Unload all audio clips from the runtime cache.
void Unload (TTSClipData clipData)
Force a runtime cache unload.
TTSClipData GetRuntimeCachedClip (string clipID)
Obtain a clip from the runtime cache, if applicable.
TTSClipData[] GetAllRuntimeCachedClips ()
Obtain all clips from the runtime cache, if applicable.
bool ShouldCacheToDisk (TTSClipData clipData)
Whether a specific clip should be cached.
string GetDiskCachePath (string textToSpeak, string clipID, TTSVoiceSettings voiceSettings, TTSDiskCacheSettings diskCacheSettings)
Get disk cache.
TTSClipData DownloadToDiskCache (string textToSpeak, Action< TTSClipData, string, string > onDownloadComplete=null)
TTSClipData DownloadToDiskCache (string textToSpeak, string presetVoiceId, Action< TTSClipData, string, string > onDownloadComplete=null)
TTSClipData DownloadToDiskCache (string textToSpeak, string presetVoiceId, TTSDiskCacheSettings diskCacheSettings, Action< TTSClipData, string, string > onDownloadComplete=null)
TTSClipData DownloadToDiskCache (string textToSpeak, TTSVoiceSettings voiceSettings, TTSDiskCacheSettings diskCacheSettings, Action< TTSClipData, string, string > onDownloadComplete=null)
TTSClipData DownloadToDiskCache (string textToSpeak, string clipID, TTSVoiceSettings voiceSettings, TTSDiskCacheSettings diskCacheSettings, Action< TTSClipData, string, string > onDownloadComplete=null)
Perform a download for a TTS audio clip.
TTSVoiceSettings[] GetAllPresetVoiceSettings ()
Return all preset voice settings.
TTSVoiceSettings GetPresetVoiceSettings (string presetVoiceId)
Return preset voice settings for a specific id.
Protected Member Functions
virtual void Awake ()
virtual void Start ()
virtual void OnEnable ()
virtual void OnDisable ()
virtual void AddDelegates ()
virtual void RemoveDelegates ()
virtual void OnDestroy ()
virtual string GetClipLog (string logMessage, TTSClipData clipData)
Get clip log data.
virtual void AppendFinalText (StringBuilder builder, string textToSpeak, TTSVoiceSettings voiceSettings)
virtual TTSClipData CreateClipData (string textToSpeak, string clipID, TTSVoiceSettings voiceSettings, TTSDiskCacheSettings diskCacheSettings)
Creates new clip data or returns existing cached clip.
virtual IAudioClipStream CreateClipStream ()
virtual AudioType GetAudioType ()
virtual void SetClipLoadState (TTSClipData clipData, TTSClipLoadState loadState)
virtual void OnUnloadBegin (TTSClipData clipData)
Perform clip unload.
virtual void OnRuntimeClipAdded (TTSClipData clipData)
Called when runtime cache adds a clip.
virtual void OnRuntimeClipRemoved (TTSClipData clipData)
Called when runtime cache unloads a clip.
virtual void DownloadToDiskCache (TTSClipData clipData, Action< TTSClipData, string, string > onDownloadComplete)
Properties
static TTSService Instance [get]
IAudioSystem AudioSystem [get, set]
Audio system to be used for streaming & playback.
ITTSRuntimeCacheHandler RuntimeCacheHandler [get]
ITTSDiskCacheHandler DiskCacheHandler [get]
ITTSWebHandler WebHandler [get]
ITTSVoiceProvider VoiceProvider [get]
TTSServiceEvents Events [get]
Events
static Action< TTSService > OnServiceStart
Static event called whenever any TTSService.Awake is called.
static Action< TTSService > OnServiceDestroy
Static event called whenever any TTSService.OnDestroy is called.
Private Member Functions
string GetSha256Hash (SHA256 shaHash, string input)
IEnumerator CallAfterAMoment (Action call)
void OnLoadBegin (TTSClipData clipData)
void OnDiskStreamBegin (TTSClipData clipData)
void OnWebStreamBegin (TTSClipData clipData)
void OnStreamBegin (TTSClipData clipData, bool fromDisk)
void OnDiskStreamCancel (TTSClipData clipData)
void OnWebStreamCancel (TTSClipData clipData)
void OnStreamCancel (TTSClipData clipData, bool fromDisk)
void OnDiskStreamError (TTSClipData clipData, string error)
void OnWebStreamError (TTSClipData clipData, string error)
void OnStreamError (TTSClipData clipData, string error, bool fromDisk)
void OnDiskStreamReady (TTSClipData clipData)
void OnWebStreamReady (TTSClipData clipData)
void OnStreamReady (TTSClipData clipData, bool fromDisk)
void OnStreamUpdated (TTSClipData clipData, IAudioClipStream clipStream, bool fromDisk)
void OnStreamComplete (TTSClipData clipData, IAudioClipStream clipStream, bool fromDisk)
void OnWebDownloadBegin (TTSClipData clipData, string downloadPath)
void OnWebDownloadSuccess (TTSClipData clipData, string downloadPath)
void OnWebDownloadCancel (TTSClipData clipData, string downloadPath)
void OnWebDownloadError (TTSClipData clipData, string downloadPath, string error)
Private Attributes
IAudioSystem _audioSystem
TTSServiceEvents _events = new TTSServiceEvents()
bool _delegates = false
readonly SHA256 CLIP_HASH = SHA256.Create()
Static Private Attributes
static TTSService _instance
const string CLIP_ID_DELIM = "|"
Detailed Description
Definition at line 24 of file TTSService.cs.
Member Function Documentation
AddDelegates()
virtual void Meta.WitAi.TTS.TTSService.AddDelegates () protected virtual
Definition at line 136 of file TTSService.cs.
        {
            // Ignore if already added
            if (_delegates)
            {
                return;
            }
            _delegates = true;
            if (RuntimeCacheHandler != null)
            {
                RuntimeCacheHandler.OnClipAdded.AddListener(OnRuntimeClipAdded);
                RuntimeCacheHandler.OnClipRemoved.AddListener(OnRuntimeClipRemoved);
            }
            if (DiskCacheHandler != null)
            {
                DiskCacheHandler.DiskStreamEvents.OnStreamBegin.AddListener(OnDiskStreamBegin);
                DiskCacheHandler.DiskStreamEvents.OnStreamCancel.AddListener(OnDiskStreamCancel);
                DiskCacheHandler.DiskStreamEvents.OnStreamReady.AddListener(OnDiskStreamReady);
                DiskCacheHandler.DiskStreamEvents.OnStreamError.AddListener(OnDiskStreamError);
            }
            if (WebHandler != null)
            {
                WebHandler.WebStreamEvents.OnStreamBegin.AddListener(OnWebStreamBegin);
                WebHandler.WebStreamEvents.OnStreamCancel.AddListener(OnWebStreamCancel);
                WebHandler.WebStreamEvents.OnStreamReady.AddListener(OnWebStreamReady);
                WebHandler.WebStreamEvents.OnStreamError.AddListener(OnWebStreamError);
                WebHandler.WebDownloadEvents.OnDownloadBegin.AddListener(OnWebDownloadBegin);
                WebHandler.WebDownloadEvents.OnDownloadCancel.AddListener(OnWebDownloadCancel);
                WebHandler.WebDownloadEvents.OnDownloadSuccess.AddListener(OnWebDownloadSuccess);
                WebHandler.WebDownloadEvents.OnDownloadError.AddListener(OnWebDownloadError);
            }
        }
AppendFinalText()
virtual void Meta.WitAi.TTS.TTSService.AppendFinalText (StringBuilder builder, string textToSpeak, TTSVoiceSettings voiceSettings) protected virtual
Definition at line 265 of file TTSService.cs.
        {
            if (!string.IsNullOrEmpty(voiceSettings?.PrependedText))
            {
                builder.Append(voiceSettings.PrependedText);
            }
            builder.Append(textToSpeak);
            if (!string.IsNullOrEmpty(voiceSettings?.AppendedText))
            {
                builder.Append(voiceSettings.AppendedText);
            }
        }
Awake()
virtual void Meta.WitAi.TTS.TTSService.Awake () protected virtual
Definition at line 110 of file TTSService.cs.
        {
            _instance = this;
            _delegates = false;
        }
CallAfterAMoment()
IEnumerator Meta.WitAi.TTS.TTSService.CallAfterAMoment (Action call) private
Definition at line 564 of file TTSService.cs.
        {
            if (Application.isPlaying)
            {
                yield return new WaitForEndOfFrame();
            }
            else
            {
                yield return null;
            }
            call();
        }
CreateClipData()
virtual TTSClipData Meta.WitAi.TTS.TTSService.CreateClipData (string textToSpeak, string clipID, TTSVoiceSettings voiceSettings, TTSDiskCacheSettings diskCacheSettings) protected virtual
Creates new clip data or returns existing cached clip.
Parameters
textToSpeak Text to speak
clipID Unique clip id
voiceSettings Voice settings
diskCacheSettings Disk Cache settings
Returns
Clip data structure
Definition at line 329 of file TTSService.cs.
        {
            // Use default voice settings if none are set
            if (voiceSettings == null && VoiceProvider != null)
            {
                voiceSettings = VoiceProvider.VoiceDefaultSettings;
            }
            // Use default disk cache settings if none are set
            if (diskCacheSettings == null && DiskCacheHandler != null)
            {
                diskCacheSettings = DiskCacheHandler.DiskCacheDefaultSettings;
            }
            // Determine clip id if empty
            if (string.IsNullOrEmpty(clipID))
            {
                clipID = GetClipID(textToSpeak, voiceSettings);
            }
            // Get clip from runtime cache if applicable
            TTSClipData clipData = GetRuntimeCachedClip(clipID);
            if (clipData != null)
            {
                return clipData;
            }
            // Generate new clip data
            clipData = new TTSClipData()
            {
                clipID = clipID,
                audioType = GetAudioType(),
                textToSpeak = GetFinalText(textToSpeak, voiceSettings),
                voiceSettings = voiceSettings,
                diskCacheSettings = diskCacheSettings,
                loadState = TTSClipLoadState.Unloaded,
                loadProgress = 0f,
                queryParameters = VoiceProvider?.EncodeVoiceSettings(voiceSettings),
                queryStream = false,
                clipStream = CreateClipStream()
            };
            // Return generated clip
            return clipData;
        }
References Meta.WitAi.TTS.Interfaces.ITTSDiskCacheHandler.DiskCacheDefaultSettings, Meta.WitAi.TTS.Interfaces.ITTSVoiceProvider.EncodeVoiceSettings(), Meta.WitAi.TTS.TTSService.GetClipID(), Meta.WitAi.TTS.TTSService.GetFinalText(), Meta.WitAi.TTS.TTSService.GetRuntimeCachedClip(), and Meta.WitAi.TTS.Interfaces.ITTSVoiceProvider.VoiceDefaultSettings.
CreateClipStream()
virtual IAudioClipStream Meta.WitAi.TTS.TTSService.CreateClipStream () protected virtual
Definition at line 374 of file TTSService.cs.
        {
            // Default
            if (AudioSystem == null)
            {
                return new UnityAudioClipStream(WitConstants.ENDPOINT_TTS_CHANNELS, WitConstants.ENDPOINT_TTS_SAMPLE_RATE, 0.1f);
            }
            // Get audio clip via audio system
            return AudioSystem.GetAudioClipStream(WitConstants.ENDPOINT_TTS_CHANNELS,
                WitConstants.ENDPOINT_TTS_SAMPLE_RATE);
        }
DownloadToDiskCache() [1/2]
TTSClipData Meta.WitAi.TTS.TTSService.DownloadToDiskCache (string textToSpeak, string clipID, TTSVoiceSettings voiceSettings, TTSDiskCacheSettings diskCacheSettings, Action< TTSClipData, string, string > onDownloadComplete = null)
Perform a download for a TTS audio clip.
Parameters
textToSpeak Text to be spoken in clip
clipID Unique clip id
voiceSettings Custom voice settings
diskCacheSettings Custom disk cache settings
onDownloadComplete Callback when file has finished downloading
Returns
Generated TTS clip data
Definition at line 854 of file TTSService.cs.
        {
            TTSClipData clipData = CreateClipData(textToSpeak, clipID, voiceSettings, diskCacheSettings);
            DownloadToDiskCache(clipData, onDownloadComplete);
            return clipData;
        }
References Meta.WitAi.TTS.TTSService.CreateClipData().
DownloadToDiskCache() [2/2]
virtual void Meta.WitAi.TTS.TTSService.DownloadToDiskCache (TTSClipData clipData, Action< TTSClipData, string, string > onDownloadComplete) protected virtual
Definition at line 863 of file TTSService.cs.
        {
            // Add delegates if needed
            AddDelegates();
            // Check if cached to disk & log
            string downloadPath = DiskCacheHandler.GetDiskCachePath(clipData);
            DiskCacheHandler.CheckCachedToDisk(clipData, (clip, found) =>
            {
                // Cache checked
                VLog.D(GetClipLog($"Disk Cache {(found ? "Found" : "Missing")}\nPath: {downloadPath}", clipData));
                // Already downloaded, return successful
                if (found)
                {
                    onDownloadComplete?.Invoke(clipData, downloadPath, string.Empty);
                    return;
                }
                // Preload selected but not in disk cache, return an error
                if (Application.isPlaying && clipData.diskCacheSettings.DiskCacheLocation == TTSDiskCacheLocation.Preload)
                {
                    onDownloadComplete?.Invoke(clipData, downloadPath, WitConstants.ERROR_TTS_CACHE_DOWNLOAD);
                    return;
                }
                // Add download completion callback
                clipData.onDownloadComplete += (error) => onDownloadComplete?.Invoke(clipData, downloadPath, error);
                // Download to cache
                WebHandler.RequestDownloadFromWeb(clipData, downloadPath);
            });
        }
GetAllPresetVoiceSettings()
TTSVoiceSettings[] Meta.WitAi.TTS.TTSService.GetAllPresetVoiceSettings ()
Return all preset voice settings.
Returns
GetAudioType()
virtual AudioType Meta.WitAi.TTS.TTSService.GetAudioType () protected virtual
Definition at line 387 of file TTSService.cs.
        {
            return AudioType.WAV;
        }
GetClipID()
virtual string Meta.WitAi.TTS.TTSService.GetClipID (string textToSpeak, TTSVoiceSettings voiceSettings) virtual
Obtain unique id for clip data.
Definition at line 281 of file TTSService.cs.
        {
            // Get a text string for a unique id
            StringBuilder uniqueId = new StringBuilder();
            // Add all data items
            if (VoiceProvider != null)
            {
                Dictionary<string, string> data = VoiceProvider.EncodeVoiceSettings(voiceSettings);
                foreach (var key in data.Keys)
                {
                    string keyClean = data[key].Replace(CLIP_ID_DELIM, "");
                    uniqueId.Append(keyClean);
                    uniqueId.Append(CLIP_ID_DELIM);
                }
            }
            // Finally, add unique id
            AppendFinalText(uniqueId, textToSpeak, voiceSettings);
            // Return id
            return GetSha256Hash(CLIP_HASH, uniqueId.ToString().ToLower());
        }
References Meta.WitAi.TTS.Interfaces.ITTSVoiceProvider.EncodeVoiceSettings().
GetClipLog()
virtual string Meta.WitAi.TTS.TTSService.GetClipLog (string logMessage, TTSClipData clipData) protected virtual
Get clip log data.
Definition at line 217 of file TTSService.cs.
        {
            StringBuilder builder = new StringBuilder();
            builder.AppendLine(logMessage);
            if (clipData != null)
            {
                builder.AppendLine($"Voice: {(clipData.voiceSettings == null ? "Default" : clipData.voiceSettings.SettingsId)}");
                builder.AppendLine($"Text: {clipData.textToSpeak}");
                builder.AppendLine($"ID: {clipData.clipID}");
                TTSDiskCacheLocation cacheLocation = TTSDiskCacheLocation.Stream;
                if (DiskCacheHandler != null)
                {
                    TTSDiskCacheSettings settings = clipData.diskCacheSettings;
                    if (settings == null)
                    {
                        settings = DiskCacheHandler.DiskCacheDefaultSettings;
                    }
                    if (settings != null)
                    {
                        cacheLocation = settings.DiskCacheLocation;
                    }
                }
                builder.AppendLine($"Cache: {cacheLocation}");
                builder.AppendLine($"Type: {clipData.audioType}");
                builder.AppendLine($"Length: {(clipData.clipStream == null ? "NULL" : clipData.clipStream.Length + " secs")}");
            }
            return builder.ToString();
        }
References Meta.WitAi.TTS.Interfaces.ITTSDiskCacheHandler.DiskCacheDefaultSettings, and Meta.WitAi.TTS.Data.TTSDiskCacheSettings.DiskCacheLocation.
GetDiskCachePath()
string Meta.WitAi.TTS.TTSService.GetDiskCachePath (string textToSpeak, string clipID, TTSVoiceSettings voiceSettings, TTSDiskCacheSettings diskCacheSettings)
Get disk cache.
Parameters
textToSpeak Text to be spoken in clip
clipID Unique clip id
voiceSettings Custom voice settings
diskCacheSettings Custom disk cache settings
Returns
GetFinalText()
string Meta.WitAi.TTS.TTSService.GetFinalText (string textToSpeak, TTSVoiceSettings voiceSettings)
Gets the text to be spoken after applying all relevant voice settings.
Parameters
textToSpeak Text to be spoken by a particular voice
voiceSettings Voice settings to be used
Returns
Returns a the final text to be spoken
Definition at line 258 of file TTSService.cs.
        {
            StringBuilder result = new StringBuilder();
            AppendFinalText(result, textToSpeak, voiceSettings);
            return result.ToString();
        }
GetInvalidError()
virtual string Meta.WitAi.TTS.TTSService.GetInvalidError () virtual
Returns error if invalid.
Reimplemented in Meta.WitAi.TTS.Integrations.TTSWit.
Definition at line 91 of file TTSService.cs.
        {
            if (WebHandler == null)
            {
                return "Web Handler Missing";
            }
            if (VoiceProvider == null)
            {
                return "Voice Provider Missing";
            }
            return string.Empty;
        }
GetPresetVoiceSettings()
TTSVoiceSettings Meta.WitAi.TTS.TTSService.GetPresetVoiceSettings (string presetVoiceId)
Return preset voice settings for a specific id.
Parameters
presetVoiceId
Returns
Definition at line 956 of file TTSService.cs.
        {
            if (VoiceProvider == null || VoiceProvider.PresetVoiceSettings == null)
            {
                return null;
            }
            return Array.Find(VoiceProvider.PresetVoiceSettings, (v) => string.Equals(v.SettingsId, presetVoiceId, StringComparison.CurrentCultureIgnoreCase));
        }
References Meta.WitAi.TTS.Interfaces.ITTSVoiceProvider.PresetVoiceSettings.
GetSha256Hash()
string Meta.WitAi.TTS.TTSService.GetSha256Hash (SHA256 shaHash, string input) private
Definition at line 302 of file TTSService.cs.
        {
            // Convert the input string to a byte array and compute the hash.
            byte[] data = shaHash.ComputeHash(Encoding.UTF8.GetBytes(input));
            // Create a new Stringbuilder to collect the bytes
            // and create a string.
            StringBuilder sBuilder = new StringBuilder();
            // Loop through each byte of the hashed data
            // and format each one as a hexadecimal string.
            for (int i = 0; i < data.Length; i++)
            {
                sBuilder.Append(data[i].ToString("x2"));
            }
            // Return the hexadecimal string.
            return sBuilder.ToString();
        }
Load()
virtual TTSClipData Meta.WitAi.TTS.TTSService.Load (string textToSpeak, string clipID, TTSVoiceSettings voiceSettings, TTSDiskCacheSettings diskCacheSettings, Action< TTSClipData, string > onStreamReady) virtual
Perform a request for a TTS audio clip.
Parameters
textToSpeak Text to be spoken in clip
clipID Unique clip id
voiceSettings Custom voice settings
diskCacheSettings Custom cache settings
Returns
Generated TTS clip data
Definition at line 414 of file TTSService.cs.
        {
            // Add delegates if needed
            AddDelegates();
            // Get clip data
            TTSClipData clipData = CreateClipData(textToSpeak, clipID, voiceSettings, diskCacheSettings);
            if (clipData == null)
            {
                VLog.E("No clip provided");
                onStreamReady?.Invoke(clipData, "No clip provided");
                return null;
            }
            if (string.IsNullOrEmpty(clipData.textToSpeak))
            {
                clipData.loadState = TTSClipLoadState.Loaded;
            }
            // From Runtime Cache
            if (clipData.loadState != TTSClipLoadState.Unloaded)
            {
                // Add callback
                if (onStreamReady != null)
                {
                    // Call once ready
                    if (clipData.loadState == TTSClipLoadState.Preparing)
                    {
                        clipData.onPlaybackReady += (e) => onStreamReady(clipData, e);
                    }
                    // Call after return
                    else
                    {
                        CoroutineUtility.StartCoroutine(CallAfterAMoment(() => onStreamReady(clipData,
                            clipData.loadState == TTSClipLoadState.Loaded ? string.Empty : "Error")));
                    }
                }
                // Return clip
                return clipData;
            }
            // Add to runtime cache if possible
            if (RuntimeCacheHandler != null)
            {
                if (!RuntimeCacheHandler.AddClip(clipData))
                {
                    // Add callback
                    if (onStreamReady != null)
                    {
                        // Call once ready
                        if (clipData.loadState == TTSClipLoadState.Preparing)
{
                            clipData.onPlaybackReady += (e) => onStreamReady(clipData, e);
                        }
                        // Call after return
                        else
{
                            CoroutineUtility.StartCoroutine(CallAfterAMoment(() => onStreamReady(clipData,
                                clipData.loadState == TTSClipLoadState.Loaded ? string.Empty : "Error")));
                        }
                    }
                    // Return clip
                    return clipData;
                }
            }
            // Load begin
            else
            {
                OnLoadBegin(clipData);
            }
            // Add on ready delegate
            clipData.onPlaybackReady += (error) => onStreamReady?.Invoke(clipData, error);
            // Wait a moment and load
            CoroutineUtility.StartCoroutine(CallAfterAMoment(() =>
            {
                // Check for invalid text
                string invalidError = WebHandler.IsTextValid(clipData.textToSpeak);
                if (!string.IsNullOrEmpty(invalidError))
                {
                    OnWebStreamError(clipData, invalidError);
                    return;
                }
                // If should cache to disk, attempt to do so
                if (ShouldCacheToDisk(clipData))
                {
                    // Download was canceled before starting
                    if (clipData.loadState != TTSClipLoadState.Preparing)
                    {
                        string downloadPath = DiskCacheHandler.GetDiskCachePath(clipData);
                        OnWebDownloadBegin(clipData, downloadPath);
                        OnWebDownloadCancel(clipData, downloadPath);
                        OnWebStreamBegin(clipData);
                        OnWebStreamCancel(clipData);
                        return;
                    }
                    // Download
                    DownloadToDiskCache(clipData, (clipData2, downloadPath, error) =>
                    {
                        // Download was canceled before starting
                        if (string.Equals(error, WitConstants.CANCEL_ERROR))
{
                            OnWebStreamBegin(clipData);
                            OnWebStreamCancel(clipData);
                            return;
                        }
                        // Not in cache & cannot download
                        if (string.Equals(error, WitConstants.ERROR_TTS_CACHE_DOWNLOAD))
{
                            WebHandler?.RequestStreamFromWeb(clipData);
                            return;
                        }
                        // Download failed, throw error
                        if (!string.IsNullOrEmpty(error))
{
                            OnWebStreamBegin(clipData);
                            OnWebStreamError(clipData, error);
                            return;
                        }
                        // Stream from Cache
                        DiskCacheHandler?.StreamFromDiskCache(clipData);
                    });
                }
                // Simply stream from the web
                else
                {
                    // Stream was canceled before starting
                    if (clipData.loadState != TTSClipLoadState.Preparing)
                    {
                        OnWebStreamBegin(clipData);
                        OnWebStreamCancel(clipData);
                        return;
                    }
                    // Stream
                    WebHandler?.RequestStreamFromWeb(clipData);
                }
            }));
            // Return data
            return clipData;
        }
References Meta.WitAi.TTS.Interfaces.ITTSRuntimeCacheHandler.AddClip(), Meta.WitAi.TTS.TTSService.CreateClipData(), Meta.WitAi.VLog.E(), Meta.WitAi.TTS.Interfaces.ITTSDiskCacheHandler.GetDiskCachePath(), Meta.WitAi.TTS.Interfaces.ITTSWebHandler.IsTextValid(), Meta.WitAi.TTS.Interfaces.ITTSWebHandler.RequestStreamFromWeb(), Meta.WitAi.TTS.TTSService.ShouldCacheToDisk(), and Meta.WitAi.TTS.Interfaces.ITTSDiskCacheHandler.StreamFromDiskCache().
OnDestroy()
virtual void Meta.WitAi.TTS.TTSService.OnDestroy () protected virtual
Definition at line 204 of file TTSService.cs.
        {
            if (_instance == this)
            {
                _instance = null;
            }
            UnloadAll();
            OnServiceDestroy?.Invoke(this);
        }
OnDisable()
virtual void Meta.WitAi.TTS.TTSService.OnDisable () protected virtual
Definition at line 130 of file TTSService.cs.
        {
            RemoveDelegates();
        }
OnEnable()
virtual void Meta.WitAi.TTS.TTSService.OnEnable () protected virtual
Definition at line 121 of file TTSService.cs.
        {
            string validError = GetInvalidError();
            if (!string.IsNullOrEmpty(validError))
            {
                VLog.W(validError);
            }
        }
OnLoadBegin()
void Meta.WitAi.TTS.TTSService.OnLoadBegin (TTSClipData clipData) private
Definition at line 577 of file TTSService.cs.
        {
            // Now preparing
            SetClipLoadState(clipData, TTSClipLoadState.Preparing);
            // Begin load
            VLog.D(GetClipLog("Load Clip", clipData));
            Events?.OnClipCreated?.Invoke(clipData);
        }
OnRuntimeClipAdded()
virtual void Meta.WitAi.TTS.TTSService.OnRuntimeClipAdded (TTSClipData clipData) protected virtual
Called when runtime cache adds a clip.
Parameters
clipData
OnRuntimeClipRemoved()
virtual void Meta.WitAi.TTS.TTSService.OnRuntimeClipRemoved (TTSClipData clipData) protected virtual
Called when runtime cache unloads a clip.
Parameters
clipData Clip to be unloaded
OnStreamBegin()
void Meta.WitAi.TTS.TTSService.OnStreamBegin (TTSClipData clipData, bool fromDisk) private
Definition at line 589 of file TTSService.cs.
        {
            // Set delegates for clip stream update/completion
            if (clipData.clipStream != null)
            {
                clipData.clipStream.OnStreamUpdated = (cs) => OnStreamUpdated(clipData, cs, fromDisk);
                clipData.clipStream.OnStreamComplete = (cs) => OnStreamComplete(clipData, cs, fromDisk);
            }
            // Callback delegate
            VLog.D(GetClipLog($"{(fromDisk ? "Disk" : "Web")} Stream Begin", clipData));
            Events?.Stream?.OnStreamBegin?.Invoke(clipData);
        }
OnStreamCancel()
void Meta.WitAi.TTS.TTSService.OnStreamCancel (TTSClipData clipData, bool fromDisk) private
Definition at line 605 of file TTSService.cs.
        {
            // Handled as an error
            SetClipLoadState(clipData, TTSClipLoadState.Error);
            // Invoke
            clipData.onPlaybackReady?.Invoke(WitConstants.CANCEL_ERROR);
            clipData.onPlaybackReady = null;
            // Callback delegate
            VLog.D(GetClipLog($"{(fromDisk ? "Disk" : "Web")} Stream Canceled", clipData));
            Events?.Stream?.OnStreamCancel?.Invoke(clipData);
            // Unload clip
            Unload(clipData);
        }
OnStreamComplete()
void Meta.WitAi.TTS.TTSService.OnStreamComplete (TTSClipData clipData, IAudioClipStream clipStream, bool fromDisk) private
Definition at line 701 of file TTSService.cs.
        {
            // Ignore invalid
            if (clipStream == null || clipData == null || clipStream != clipData.clipStream)
            {
                return;
            }
            // Log & call event
            VLog.D(GetClipLog($"{(fromDisk ? "Disk" : "Web")} Stream Complete", clipData));
            Events?.Stream?.OnStreamComplete?.Invoke(clipData);
            // Web request completion
            if (!fromDisk)
            {
                Events?.WebRequest?.OnRequestComplete.Invoke(clipData);
            }
        }
OnStreamError()
void Meta.WitAi.TTS.TTSService.OnStreamError (TTSClipData clipData, string error, bool fromDisk) private
Definition at line 624 of file TTSService.cs.
        {
            // Cancelled
            if (error.Equals(WitConstants.CANCEL_ERROR))
            {
                OnStreamCancel(clipData, fromDisk);
                return;
            }
            // Error
            SetClipLoadState(clipData, TTSClipLoadState.Error);
            // Invoke playback is ready
            clipData.onPlaybackReady?.Invoke(error);
            clipData.onPlaybackReady = null;
            // Stream error
            VLog.E(GetClipLog($"{(fromDisk ? "Disk" : "Web")} Stream Error\nError: {error}", clipData));
            Events?.Stream?.OnStreamError?.Invoke(clipData, error);
            // Unload clip
            Unload(clipData);
        }
OnStreamReady()
void Meta.WitAi.TTS.TTSService.OnStreamReady (TTSClipData clipData, bool fromDisk) private
Definition at line 650 of file TTSService.cs.
        {
            // Refresh cache for file size
            if (RuntimeCacheHandler != null)
            {
                // Stop forcing an unload if runtime cache update fails
                RuntimeCacheHandler.OnClipRemoved.RemoveListener(OnRuntimeClipRemoved);
                bool failed = !RuntimeCacheHandler.AddClip(clipData);
                RuntimeCacheHandler.OnClipRemoved.AddListener(OnRuntimeClipRemoved);
                // Handle fail directly
                if (failed)
                {
                    OnStreamError(clipData, "Removed from runtime cache due to file size", fromDisk);
                    OnRuntimeClipRemoved(clipData);
                    return;
                }
            }
            // Set delegates again since the stream may have changed during setup
            if (clipData.clipStream != null)
            {
                clipData.clipStream.OnStreamUpdated = (cs) => OnStreamUpdated(clipData, cs, fromDisk);
                clipData.clipStream.OnStreamComplete = (cs) => OnStreamComplete(clipData, cs, fromDisk);
            }
            // Set clip stream state
            SetClipLoadState(clipData, TTSClipLoadState.Loaded);
            VLog.D(GetClipLog($"{(fromDisk ? "Disk" : "Web")} Stream Ready", clipData));
            // Invoke playback is ready
            clipData.onPlaybackReady?.Invoke(string.Empty);
            clipData.onPlaybackReady = null;
            // Callback delegate
            Events?.Stream?.OnStreamReady?.Invoke(clipData);
        }
OnStreamUpdated()
void Meta.WitAi.TTS.TTSService.OnStreamUpdated (TTSClipData clipData, IAudioClipStream clipStream, bool fromDisk) private
Definition at line 688 of file TTSService.cs.
        {
            // Ignore invalid
            if (clipStream == null || clipData == null || clipStream != clipData.clipStream)
            {
                return;
            }
            // Log & call event
            VLog.D(GetClipLog($"{(fromDisk ? "Disk" : "Web")} Stream Updated", clipData));
            Events?.Stream?.OnStreamClipUpdate?.Invoke(clipData);
        }
OnUnloadBegin()
virtual void Meta.WitAi.TTS.TTSService.OnUnloadBegin (TTSClipData clipData) protected virtual
Perform clip unload.
Parameters
clipID
Definition at line 761 of file TTSService.cs.
        {
            // Abort if currently preparing
            if (clipData.loadState == TTSClipLoadState.Preparing)
            {
                // Cancel web stream
                WebHandler?.CancelWebStream(clipData);
                // Cancel web download to cache
                WebHandler?.CancelWebDownload(clipData, GetDiskCachePath(clipData.textToSpeak, clipData.clipID, clipData.voiceSettings, clipData.diskCacheSettings));
                // Cancel disk cache stream
                DiskCacheHandler?.CancelDiskCacheStream(clipData);
            }
            // Unloads clip stream
            clipData.clipStream = null;
            // Clip is now unloaded
            SetClipLoadState(clipData, TTSClipLoadState.Unloaded);
            // Unload
            VLog.D(GetClipLog($"Unload Clip", clipData));
            Events?.OnClipUnloaded?.Invoke(clipData);
        }
References Meta.WitAi.TTS.Interfaces.ITTSDiskCacheHandler.CancelDiskCacheStream(), Meta.WitAi.TTS.Interfaces.ITTSWebHandler.CancelWebDownload(), Meta.WitAi.TTS.Interfaces.ITTSWebHandler.CancelWebStream(), Meta.WitAi.VLog.D(), Meta.WitAi.TTS.TTSService.GetClipLog(), and Meta.WitAi.TTS.TTSService.GetDiskCachePath().
OnWebDownloadBegin()
void Meta.WitAi.TTS.TTSService.OnWebDownloadBegin (TTSClipData clipData, string downloadPath) private
Definition at line 897 of file TTSService.cs.
        {
            VLog.D(GetClipLog($"Download Clip - Begin\nPath: {downloadPath}", clipData));
            Events?.Download?.OnDownloadBegin?.Invoke(clipData, downloadPath);
        }
OnWebDownloadCancel()
void Meta.WitAi.TTS.TTSService.OnWebDownloadCancel (TTSClipData clipData, string downloadPath) private
Definition at line 914 of file TTSService.cs.
        {
            // Invoke clip callback & clear
            clipData.onDownloadComplete?.Invoke(WitConstants.CANCEL_ERROR);
            clipData.onDownloadComplete = null;
            // Log
            VLog.D(GetClipLog($"Download Clip - Canceled\nPath: {downloadPath}", clipData));
            Events?.Download?.OnDownloadCancel?.Invoke(clipData, downloadPath);
        }
OnWebDownloadError()
void Meta.WitAi.TTS.TTSService.OnWebDownloadError (TTSClipData clipData, string downloadPath, string error) private
Definition at line 925 of file TTSService.cs.
        {
            // Cancelled
            if (error.Equals(WitConstants.CANCEL_ERROR))
            {
                OnWebDownloadCancel(clipData, downloadPath);
                return;
            }
            // Invoke clip callback & clear
            clipData.onDownloadComplete?.Invoke(error);
            clipData.onDownloadComplete = null;
            // Log
            VLog.E(GetClipLog($"Download Clip - Failed\nPath: {downloadPath}\nError: {error}", clipData));
            Events?.Download?.OnDownloadError?.Invoke(clipData, downloadPath, error);
        }
OnWebDownloadSuccess()
void Meta.WitAi.TTS.TTSService.OnWebDownloadSuccess (TTSClipData clipData, string downloadPath) private
Definition at line 903 of file TTSService.cs.
        {
            // Invoke clip callback & clear
            clipData.onDownloadComplete?.Invoke(string.Empty);
            clipData.onDownloadComplete = null;
            // Log
            VLog.D(GetClipLog($"Download Clip - Success\nPath: {downloadPath}", clipData));
            Events?.Download?.OnDownloadSuccess?.Invoke(clipData, downloadPath);
        }
RemoveDelegates()
virtual void Meta.WitAi.TTS.TTSService.RemoveDelegates () protected virtual
Definition at line 170 of file TTSService.cs.
        {
            // Ignore if not yet added
            if (!_delegates)
            {
                return;
            }
            _delegates = false;
            if (RuntimeCacheHandler != null)
            {
                RuntimeCacheHandler.OnClipAdded.RemoveListener(OnRuntimeClipAdded);
                RuntimeCacheHandler.OnClipRemoved.RemoveListener(OnRuntimeClipRemoved);
            }
            if (DiskCacheHandler != null)
            {
                DiskCacheHandler.DiskStreamEvents.OnStreamBegin.RemoveListener(OnDiskStreamBegin);
                DiskCacheHandler.DiskStreamEvents.OnStreamCancel.RemoveListener(OnDiskStreamCancel);
                DiskCacheHandler.DiskStreamEvents.OnStreamReady.RemoveListener(OnDiskStreamReady);
                DiskCacheHandler.DiskStreamEvents.OnStreamError.RemoveListener(OnDiskStreamError);
            }
            if (WebHandler != null)
            {
                WebHandler.WebStreamEvents.OnStreamBegin.RemoveListener(OnWebStreamBegin);
                WebHandler.WebStreamEvents.OnStreamCancel.RemoveListener(OnWebStreamCancel);
                WebHandler.WebStreamEvents.OnStreamReady.RemoveListener(OnWebStreamReady);
                WebHandler.WebStreamEvents.OnStreamError.RemoveListener(OnWebStreamError);
                WebHandler.WebDownloadEvents.OnDownloadBegin.RemoveListener(OnWebDownloadBegin);
                WebHandler.WebDownloadEvents.OnDownloadCancel.RemoveListener(OnWebDownloadCancel);
                WebHandler.WebDownloadEvents.OnDownloadSuccess.RemoveListener(OnWebDownloadSuccess);
                WebHandler.WebDownloadEvents.OnDownloadError.RemoveListener(OnWebDownloadError);
            }
        }
SetClipLoadState()
virtual void Meta.WitAi.TTS.TTSService.SetClipLoadState (TTSClipData clipData, TTSClipLoadState loadState) protected virtual
Definition at line 392 of file TTSService.cs.
        {
            clipData.loadState = loadState;
            clipData.onStateChange?.Invoke(clipData, clipData.loadState);
        }
ShouldCacheToDisk()
bool Meta.WitAi.TTS.TTSService.ShouldCacheToDisk (TTSClipData clipData)
Whether a specific clip should be cached.
Parameters
clipData Clip data
Returns
True if should be cached
Start()
virtual void Meta.WitAi.TTS.TTSService.Start () protected virtual
Definition at line 116 of file TTSService.cs.
        {
            OnServiceStart?.Invoke(this);
        }
Unload()
void Meta.WitAi.TTS.TTSService.Unload (TTSClipData clipData)
Force a runtime cache unload.
Definition at line 746 of file TTSService.cs.
        {
            if (RuntimeCacheHandler != null)
            {
                RuntimeCacheHandler.RemoveClip(clipData.clipID);
            }
            else
            {
                OnUnloadBegin(clipData);
            }
        }
References Meta.WitAi.TTS.TTSService.OnUnloadBegin(), and Meta.WitAi.TTS.Interfaces.ITTSRuntimeCacheHandler.RemoveClip().
UnloadAll()
void Meta.WitAi.TTS.TTSService.UnloadAll ()
Unload all audio clips from the runtime cache.
Definition at line 725 of file TTSService.cs.
        {
            // Failed
            TTSClipData[] clips = RuntimeCacheHandler?.GetClips();
            if (clips == null)
            {
                return;
            }
            // Copy array
            HashSet<TTSClipData> remaining = new HashSet<TTSClipData>(clips);
            // Unload all clips
            foreach (var clip in remaining)
            {
                Unload(clip);
            }
        }
References Meta.WitAi.TTS.Interfaces.ITTSRuntimeCacheHandler.GetClips(), and Meta.WitAi.TTS.TTSService.Unload().
Member Data Documentation
_audioSystem
IAudioSystem Meta.WitAi.TTS.TTSService._audioSystem private
Definition at line 68 of file TTSService.cs.
_delegates
bool Meta.WitAi.TTS.TTSService._delegates = false private
Definition at line 135 of file TTSService.cs.
_events
TTSServiceEvents Meta.WitAi.TTS.TTSService._events = new TTSServiceEvents() private
Definition at line 107 of file TTSService.cs.
_instance
TTSService Meta.WitAi.TTS.TTSService._instance static private
Definition at line 45 of file TTSService.cs.
CLIP_HASH
readonly SHA256 Meta.WitAi.TTS.TTSService.CLIP_HASH = SHA256.Create() private
Definition at line 250 of file TTSService.cs.
CLIP_ID_DELIM
const string Meta.WitAi.TTS.TTSService.CLIP_ID_DELIM = "|" static private
Definition at line 249 of file TTSService.cs.
Property Documentation
AudioSystem
IAudioSystem Meta.WitAi.TTS.TTSService.AudioSystem get set
Audio system to be used for streaming & playback.
Definition at line 50 of file TTSService.cs.
        {
            get
            {
                if (_audioSystem == null && Application.isPlaying)
                {
                    // Search on TTS Service
                    _audioSystem = gameObject.GetComponent<IAudioSystem>();
                    if (_audioSystem == null)
                    {
                        // Add default unity audio system if not found
                        _audioSystem = gameObject.AddComponent<UnityAudioSystem>();
                    }
                }
                return _audioSystem;
            }
            set => _audioSystem = value;
        }
DiskCacheHandler
ITTSDiskCacheHandler Meta.WitAi.TTS.TTSService.DiskCacheHandler get abstract
Definition at line 73 of file TTSService.cs.
{ get; }
Events
TTSServiceEvents Meta.WitAi.TTS.TTSService.Events get
Definition at line 105 of file TTSService.cs.
Instance
TTSService Meta.WitAi.TTS.TTSService.Instance static get
Definition at line 28 of file TTSService.cs.
        {
            get
            {
                if (_instance == null)
                {
                    // Get all services
                    TTSService[] services = Resources.FindObjectsOfTypeAll<TTSService>();
                    if (services != null)
                    {
                        // Set as first instance that isn't a prefab
                        _instance = Array.Find(services, (o) => o.gameObject.scene.rootCount != 0);
                    }
                }
                return _instance;
            }
        }
RuntimeCacheHandler
ITTSRuntimeCacheHandler Meta.WitAi.TTS.TTSService.RuntimeCacheHandler get abstract
Definition at line 71 of file TTSService.cs.
{ get; }
VoiceProvider
ITTSVoiceProvider Meta.WitAi.TTS.TTSService.VoiceProvider get abstract
Definition at line 77 of file TTSService.cs.
{ get; }
WebHandler
ITTSWebHandler Meta.WitAi.TTS.TTSService.WebHandler get abstract
Definition at line 75 of file TTSService.cs.
{ get; }
Event Documentation
OnServiceDestroy
Action<TTSService> Meta.WitAi.TTS.TTSService.OnServiceDestroy static
Static event called whenever any TTSService.OnDestroy is called.
Definition at line 86 of file TTSService.cs.
OnServiceStart
Action<TTSService> Meta.WitAi.TTS.TTSService.OnServiceStart static
Static event called whenever any TTSService.Awake is called.
Definition at line 82 of file TTSService.cs.
The documentation for this class was generated from the following file:
Assets/Oculus/Voice/Lib/Wit.ai/Features/TTS/Scripts/Runtime/TTSService.cs