VR_Test: TeleportInputHandlerTouch Class Reference
TeleportInputHandlerTouch Class Reference
When this component is enabled, the player will be able to aim and trigger teleport behavior using Oculus Touch controllers.
Public Types
enum InputModes { CapacitiveButtonForAimAndTeleport , SeparateButtonsForAimAndTeleport , ThumbstickTeleport , ThumbstickTeleportForwardBackOnly }
The touch input handler supports three different modes for controlling teleports.
enum AimCapTouchButtons {
A , B , LeftTrigger , LeftThumbstick ,
RightTrigger , RightThumbstick , X , Y
}
These buttons are used for selecting which capacitive button is used when InputMode==CapacitiveButtonForAimAndTeleport.
Public Member Functions
override LocomotionTeleport.TeleportIntentions GetIntention ()
Based on the input mode, controller state, and current intention of the teleport controller, return the apparent intention of the user.
override void GetAimData (out Ray aimRay)
Public Member Functions inherited from TeleportInputHandlerHMD
override LocomotionTeleport.TeleportIntentions GetIntention ()
Based on the input mode, controller state, and current intention of the teleport controller, return the apparent intention of the user.
override void GetAimData (out Ray aimRay)
Public Member Functions inherited from TeleportInputHandler
LocomotionTeleport.TeleportIntentions GetIntention ()
One of the core functions of the TeleportInputHandler is to notify the LocomotionTeleport of the current intentions of the user with respect to aiming, teleporting, and abandoning a pending teleport. Derivations of this class will check buttons or whatever inputs they require to return values indicating what the user is trying to do.
void GetAimData (out Ray aimRay)
Returns the aim ray for pointing at targets, which is generally based on a touch controller or HMD pose.
Public Attributes
Transform LeftHand
Transform RightHand
InputModes InputMode
OVRInput.Controller AimingController
Which controller is being used for aiming.
AimCapTouchButtons CapacitiveAimAndTeleportButton
The button to use for triggering aim and teleport when InputMode==CapacitiveButtonForAimAndTeleport.
float ThumbstickTeleportThreshold = 0.5f
The thumbstick magnitude required to trigger aiming and teleports when InputMode==InputModes.ThumbstickTeleport.
Public Attributes inherited from TeleportInputHandlerHMD
OVRInput.RawButton AimButton
The button used to begin aiming for a teleport.
OVRInput.RawButton TeleportButton
The button used to trigger the teleport after aiming. It can be the same button as the AimButton, however you cannot abort a teleport if it is.
bool FastTeleport
When true, the system will not use the PreTeleport intention which will allow a teleport to occur on a button downpress. When false, the button downpress will trigger the PreTeleport intention and the Teleport intention when the button is released.
Private Member Functions
void Start ()
Private Attributes
readonly OVRInput.RawButton[] _rawButtons
readonly OVRInput.RawTouch[] _rawTouch
OVRInput.Controller InitiatingController
Additional Inherited Members
Protected Member Functions inherited from TeleportInputHandler
override void AddEventHandlers ()
Derived classes that need to use event handlers need to override this method and call the base class to ensure all event handlers are added as intended.
override void RemoveEventHandlers ()
Derived classes that need to use event handlers need to override this method and call the base class to ensure all event handlers are removed as intended.
Protected Member Functions inherited from TeleportSupport
virtual void OnEnable ()
OnEnable is virtual so that derived classes can set up references to objects before AddEventHandlers is called, as is required by TeleportSupport derivations.
virtual void OnDisable ()
Properties inherited from TeleportInputHandlerHMD
Transform Pointer [get, private set]
Properties inherited from TeleportSupport
LocomotionTeleport LocomotionTeleport [get, private set]
Detailed Description
When this component is enabled, the player will be able to aim and trigger teleport behavior using Oculus Touch controllers.
Definition at line 18 of file TeleportInputHandlerTouch.cs.
Member Enumeration Documentation
AimCapTouchButtons
enum TeleportInputHandlerTouch.AimCapTouchButtons
These buttons are used for selecting which capacitive button is used when InputMode==CapacitiveButtonForAimAndTeleport.
Definition at line 58 of file TeleportInputHandlerTouch.cs.
    {
        A,
        B,
        LeftTrigger,
        LeftThumbstick,
        RightTrigger,
        RightThumbstick,
        X,
        Y
    }
InputModes
enum TeleportInputHandlerTouch.InputModes
The touch input handler supports three different modes for controlling teleports.
Enumerator
CapacitiveButtonForAimAndTeleport
Touching a capacitive button will start the aiming, and pressing that button will trigger the teleport.
SeparateButtonsForAimAndTeleport
One button will start the aiming, another button will trigger the teleport.
ThumbstickTeleport
A thumbstick in any direction is used for starting the aiming, and releasing the thumbstick will trigger the teleport.
ThumbstickTeleportForwardBackOnly
A thumbstick forward or back is used for starting the aiming, and releasing the thumbstick will trigger the teleport.
Definition at line 26 of file TeleportInputHandlerTouch.cs.
    {
        CapacitiveButtonForAimAndTeleport,
        SeparateButtonsForAimAndTeleport,
        ThumbstickTeleport,
        ThumbstickTeleportForwardBackOnly
    }
Member Function Documentation
GetAimData()
override void TeleportInputHandlerTouch.GetAimData (out Ray aimRay)
Definition at line 275 of file TeleportInputHandlerTouch.cs.
    {
        OVRInput.Controller sourceController = AimingController;
        if (sourceController == OVRInput.Controller.Touch)
        {
            sourceController = InitiatingController;
        }
        Transform t = (sourceController == OVRInput.Controller.LTouch) ? LeftHand : RightHand;
        aimRay = new Ray(t.position, t.forward);
    }
GetIntention()
override LocomotionTeleport.TeleportIntentions TeleportInputHandlerTouch.GetIntention ()
Based on the input mode, controller state, and current intention of the teleport controller, return the apparent intention of the user.
Returns
Definition at line 124 of file TeleportInputHandlerTouch.cs.
    {
        if (!isActiveAndEnabled)
        {
            return global::LocomotionTeleport.TeleportIntentions.None;
        }
        // If capacitive touch isn't being used, the base implementation will do the work.
        if (InputMode == InputModes.SeparateButtonsForAimAndTeleport)
        {
            return base.GetIntention();
        }
        // ThumbstickTeleport will begin aiming when the thumbstick is pushed.
        if (InputMode == InputModes.ThumbstickTeleport || InputMode == InputModes.ThumbstickTeleportForwardBackOnly)
        {
            // Note there's a bit of wasted work here if you're only using 1 thumbstick to trigger teleport.
            // Feel free to delete the extra code for the unnecessary stick.
            Vector2 leftStick = OVRInput.Get(OVRInput.RawAxis2D.LThumbstick);
            Vector2 rightStick = OVRInput.Get(OVRInput.RawAxis2D.RThumbstick);
            float leftMag = 0.0f;
            float rightMag = 0.0f;
            float bestMag = 0.0f;
            OVRInput.Controller bestController = OVRInput.Controller.Touch;
            bool leftTouched = OVRInput.Get(OVRInput.RawTouch.LThumbstick);
            bool rightTouched = OVRInput.Get(OVRInput.RawTouch.RThumbstick);
            if (InputMode == InputModes.ThumbstickTeleportForwardBackOnly &&
                LocomotionTeleport.CurrentIntention != LocomotionTeleport.TeleportIntentions.Aim)
            {
                // If user is aiming, ThumbstickTeleport and ThumbstickTeleportForwardBackOnly are identical. But if not, we only want magnitude along the forward or back vector.
                leftMag = Mathf.Abs(Vector2.Dot(leftStick, Vector2.up));
                rightMag = Mathf.Abs(Vector2.Dot(rightStick, Vector2.up));
            }
            else
            {
                leftMag = leftStick.magnitude;
                rightMag = rightStick.magnitude;
            }
            if (AimingController == OVRInput.Controller.LTouch)
            {
                bestMag = leftMag;
                bestController = OVRInput.Controller.LTouch;
            }
            else if (AimingController == OVRInput.Controller.RTouch)
            {
                bestMag = rightMag;
                bestController = OVRInput.Controller.RTouch;
            }
            else
            {
                if (leftMag > rightMag)
                {
                    bestMag = leftMag;
                    bestController = OVRInput.Controller.LTouch;
                }
                else
                {
                    bestMag = rightMag;
                    bestController = OVRInput.Controller.RTouch;
                }
            }
            bool touching = bestMag > ThumbstickTeleportThreshold
                            || (AimingController == OVRInput.Controller.Touch && (leftTouched || rightTouched))
                            || (AimingController == OVRInput.Controller.LTouch && leftTouched)
                            || (AimingController == OVRInput.Controller.RTouch && rightTouched);
            if (!touching)
            {
                if (LocomotionTeleport.CurrentIntention == LocomotionTeleport.TeleportIntentions.Aim)
                {
                    // If the user has released the thumbstick, enter the PreTeleport state unless FastTeleport is enabled,
                    // in which case enter the Teleport state.
                    return FastTeleport
                        ? LocomotionTeleport.TeleportIntentions.Teleport
                        : LocomotionTeleport.TeleportIntentions.PreTeleport;
                }
                // If the user is already in the preteleport state, the intention will be to either remain in this state or switch to Teleport
                if (LocomotionTeleport.CurrentIntention == LocomotionTeleport.TeleportIntentions.PreTeleport)
                {
                    return LocomotionTeleport.TeleportIntentions.Teleport;
                }
            }
            else
            {
                if (LocomotionTeleport.CurrentIntention == LocomotionTeleport.TeleportIntentions.Aim)
                {
                    return LocomotionTeleport.TeleportIntentions.Aim;
                }
            }
            if (bestMag > ThumbstickTeleportThreshold)
            {
                InitiatingController = bestController;
                return LocomotionTeleport.TeleportIntentions.Aim;
            }
            return LocomotionTeleport.TeleportIntentions.None;
        }
        // Capacitive touch logic is essentially the same as the base logic, except the button types are different
        // so different methods need to be used.
        var teleportButton = _rawButtons[(int)CapacitiveAimAndTeleportButton];
        if (LocomotionTeleport.CurrentIntention == LocomotionTeleport.TeleportIntentions.Aim)
        {
            // If the user has actually pressed the teleport button, enter the preteleport state.
            if (OVRInput.GetDown(teleportButton))
            {
                // If the user has released the thumbstick, enter the PreTeleport state unless FastTeleport is enabled,
                // in which case enter the Teleport state.
                return FastTeleport
                    ? LocomotionTeleport.TeleportIntentions.Teleport
                    : LocomotionTeleport.TeleportIntentions.PreTeleport;
            }
        }
        // If the user is already in the PreTeleport state, the intention will be to either remain in this state or switch to Teleport
        if (LocomotionTeleport.CurrentIntention == LocomotionTeleport.TeleportIntentions.PreTeleport)
        {
            // If they released the button, switch to Teleport.
            if (FastTeleport || OVRInput.GetUp(teleportButton))
            {
                // Button released, enter the Teleport state.
                return LocomotionTeleport.TeleportIntentions.Teleport;
            }
            // Button still down, remain in PreTeleport so they can orient the destination if an orientation handler supports it.
            return LocomotionTeleport.TeleportIntentions.PreTeleport;
        }
        // If it made it this far, then we need to determine if the user intends to be aiming with the capacitive touch.
        // The first check is if cap touch has been triggered.
        if (OVRInput.GetDown(_rawTouch[(int)CapacitiveAimAndTeleportButton]))
        {
            return LocomotionTeleport.TeleportIntentions.Aim;
        }
        if (LocomotionTeleport.CurrentIntention == LocomotionTeleport.TeleportIntentions.Aim)
        {
            if (!OVRInput.GetUp(_rawTouch[(int)CapacitiveAimAndTeleportButton]))
            {
                return LocomotionTeleport.TeleportIntentions.Aim;
            }
        }
        return LocomotionTeleport.TeleportIntentions.None;
    }
References AimingController, CapacitiveAimAndTeleportButton, LocomotionTeleport.CurrentIntention, TeleportInputHandlerHMD.FastTeleport, OVRInput.Get(), OVRInput.GetDown(), OVRInput.GetUp(), and ThumbstickTeleportThreshold.
Start()
void TeleportInputHandlerTouch.Start () private
Definition at line 116 of file TeleportInputHandlerTouch.cs.
    {
    }
Member Data Documentation
_rawButtons
readonly OVRInput.RawButton [] TeleportInputHandlerTouch._rawButtons private
Initial value:
=
    {
        OVRInput.RawButton.A,
        OVRInput.RawButton.B,
        OVRInput.RawButton.LIndexTrigger,
        OVRInput.RawButton.LThumbstick,
        OVRInput.RawButton.RIndexTrigger,
        OVRInput.RawButton.RThumbstick,
        OVRInput.RawButton.X,
        OVRInput.RawButton.Y
    }
Definition at line 70 of file TeleportInputHandlerTouch.cs.
    {
        OVRInput.RawButton.A,
        OVRInput.RawButton.B,
        OVRInput.RawButton.LIndexTrigger,
        OVRInput.RawButton.LThumbstick,
        OVRInput.RawButton.RIndexTrigger,
        OVRInput.RawButton.RThumbstick,
        OVRInput.RawButton.X,
        OVRInput.RawButton.Y
    };
_rawTouch
readonly OVRInput.RawTouch [] TeleportInputHandlerTouch._rawTouch private
Initial value:
=
    {
        OVRInput.RawTouch.A,
        OVRInput.RawTouch.B,
        OVRInput.RawTouch.LIndexTrigger,
        OVRInput.RawTouch.LThumbstick,
        OVRInput.RawTouch.RIndexTrigger,
        OVRInput.RawTouch.RThumbstick,
        OVRInput.RawTouch.X,
        OVRInput.RawTouch.Y
    }
Definition at line 82 of file TeleportInputHandlerTouch.cs.
    {
        OVRInput.RawTouch.A,
        OVRInput.RawTouch.B,
        OVRInput.RawTouch.LIndexTrigger,
        OVRInput.RawTouch.LThumbstick,
        OVRInput.RawTouch.RIndexTrigger,
        OVRInput.RawTouch.RThumbstick,
        OVRInput.RawTouch.X,
        OVRInput.RawTouch.Y
    };
AimingController
OVRInput.Controller TeleportInputHandlerTouch.AimingController
Which controller is being used for aiming.
Definition at line 98 of file TeleportInputHandlerTouch.cs.
CapacitiveAimAndTeleportButton
AimCapTouchButtons TeleportInputHandlerTouch.CapacitiveAimAndTeleportButton
The button to use for triggering aim and teleport when InputMode==CapacitiveButtonForAimAndTeleport.
Definition at line 107 of file TeleportInputHandlerTouch.cs.
InitiatingController
OVRInput.Controller TeleportInputHandlerTouch.InitiatingController private
Definition at line 100 of file TeleportInputHandlerTouch.cs.
InputMode
InputModes TeleportInputHandlerTouch.InputMode
Definition at line 53 of file TeleportInputHandlerTouch.cs.
LeftHand
Transform TeleportInputHandlerTouch.LeftHand
Definition at line 20 of file TeleportInputHandlerTouch.cs.
RightHand
Transform TeleportInputHandlerTouch.RightHand
Definition at line 21 of file TeleportInputHandlerTouch.cs.
ThumbstickTeleportThreshold
float TeleportInputHandlerTouch.ThumbstickTeleportThreshold = 0.5f
The thumbstick magnitude required to trigger aiming and teleports when InputMode==InputModes.ThumbstickTeleport.
Definition at line 114 of file TeleportInputHandlerTouch.cs.
The documentation for this class was generated from the following file:
Assets/Oculus/SampleFramework/Core/Locomotion/Scripts/TeleportInputHandlerTouch.cs