VR_Test: Meta.WitAi.WitService Class Reference
Meta.WitAi.WitService Class Reference
Public Member Functions
virtual bool IsConfigurationValid ()
Check configuration, client access token & app id.
void Activate ()
Activate the microphone and send data to Wit for NLU processing.
void Activate (WitRequestOptions requestOptions)
VoiceServiceRequest Activate (WitRequestOptions requestOptions, VoiceServiceRequestEvents requestEvents)
Activate the microphone and wait for threshold and then send data.
void ActivateImmediately ()
Activate the microphone and immediately send data to Wit for NLU processing.
void ActivateImmediately (WitRequestOptions requestOptions)
VoiceServiceRequest ActivateImmediately (WitRequestOptions requestOptions, VoiceServiceRequestEvents requestEvents)
Activate the microphone and send data for NLU processing with custom request options.
void ExecuteRequest (WitRequest newRequest)
Execute a wit request immediately.
void Activate (string text)
Activate the microphone and send data to Wit for NLU processing.
void Activate (string text, WitRequestOptions requestOptions)
VoiceServiceRequest Activate (string text, WitRequestOptions requestOptions, VoiceServiceRequestEvents requestEvents)
Send text data for NLU processing with custom request options & events.
void Deactivate ()
Stop listening and submit the collected microphone data to wit for processing.
void DeactivateAndAbortRequest (VoiceServiceRequest request)
Stop listening and cancel a specific report.
void DeactivateAndAbortRequest ()
Stop listening and abort any requests that may be active without waiting for a response.
Protected Member Functions
void Awake ()
void OnEnable ()
void OnDisable ()
virtual void OnSceneLoaded (Scene scene, LoadSceneMode mode)
void SetMicDelegates (bool add)
virtual void SendRecordingRequest ()
Sends recording request if possible.
void SetupRequest (WitRequest newRequest)
Setup recording request.
Properties
WitConfiguration Configuration [get]
bool Active [get]
Returns true if wit is currently active and listening with the mic.
bool IsRequestActive [get]
Active if recording, transmitting, or queued up.
IVoiceEventProvider VoiceEventProvider [get, set]
ITelemetryEventsProvider TelemetryEventsProvider [get, set]
IWitRuntimeConfigProvider ConfigurationProvider [get, set]
WitRuntimeConfiguration RuntimeConfiguration [get]
VoiceEvents VoiceEvents [get]
TelemetryEvents TelemetryEvents [get]
ITranscriptionProvider TranscriptionProvider [get, set]
Gets/Sets a custom transcription provider. This can be used to replace any built in asr with an on device model or other provided source.
IWitRequestProvider WitRequestProvider [get, set]
bool MicActive [get]
bool ShouldSendMicData [get]
Properties inherited from Meta.WitAi.IVoiceEventProvider
Properties inherited from Meta.WitAi.IVoiceActivationHandler
Properties inherited from Meta.WitAi.ITelemetryEventsProvider
Properties inherited from Meta.WitAi.IWitRuntimeConfigProvider
Properties inherited from Meta.WitAi.Interfaces.IWitConfigurationProvider
Private Member Functions
void StopRecording ()
void OnWitReadyForData ()
void StartRecording ()
void OnMicStartListening ()
void OnMicStoppedListening ()
void OnByteDataReady (byte[] buffer, int offset, int length)
void OnMicSampleReady (RingBuffer< byte >.Marker marker, float levelMax)
void Update ()
void OnMicLevelChanged (float level)
void OnTranscriptionMicLevelChanged (float level)
void FinalizeAudioDurationTracker ()
IEnumerator DeactivateDueToTimeLimit ()
void DeactivateRequest (UnityEvent onComplete=null, bool abort=false)
void DeactivateWitRequest (VoiceServiceRequest request, bool abort)
void OnPartialTranscription (string transcription)
void OnFullTranscription (string transcription)
void HandlePartialResult (WitResponseNode response)
Main thread call to handle partial response callbacks.
void HandleResult (VoiceServiceRequest request)
Main thread call to handle result callbacks.
void HandleComplete (VoiceServiceRequest request)
Handle request completion.
Private Attributes
float _lastMinVolumeLevelTime
WitRequest _recordingRequest
bool _isSoundWakeActive
RingBuffer< byte >.Marker _lastSampleMarker
bool _minKeepAliveWasHit
bool _isActive
long _minSampleByteCount = 1024 * 10
IVoiceEventProvider _voiceEventProvider
ITelemetryEventsProvider _telemetryEventsProvider
IWitRuntimeConfigProvider _runtimeConfigProvider
ITranscriptionProvider _activeTranscriptionProvider
Coroutine _timeLimitCoroutine
IWitRequestProvider _witRequestProvider
bool _receivedTranscription
float _lastWordTime
HashSet< VoiceServiceRequest > _transmitRequests = new HashSet<VoiceServiceRequest>()
Coroutine _queueHandler
IWitByteDataReadyHandler[] _dataReadyHandlers
IWitByteDataSentHandler[] _dataSentHandlers
IDynamicEntitiesProvider[] _dynamicEntityProviders
float _time
AudioBuffer _buffer
bool _bufferDelegates = false
Detailed Description
Definition at line 25 of file WitService.cs.
Member Function Documentation
Activate() [1/2]
VoiceServiceRequest Meta.WitAi.WitService.Activate (string text, WitRequestOptions requestOptions, VoiceServiceRequestEvents requestEvents)
Send text data for NLU processing with custom request options & events.
Parameters
text Text to be used for NLU processing
requestOptions Additional options such as dynamic entities
requestEvents Events specific to the request's lifecycle
Implements Meta.WitAi.IVoiceActivationHandler.
Definition at line 400 of file WitService.cs.
        {
            // Not valid
            if (!IsConfigurationValid())
            {
                VLog.E($"Your AppVoiceExperience \"{gameObject.name}\" does not have a wit config assigned. Understanding Viewer activations will not trigger in game events..");
                return null;
            }
            // Handle option setup
            VoiceEvents.OnRequestOptionSetup?.Invoke(requestOptions);
            // Generate request
            VoiceServiceRequest request = Configuration.CreateMessageRequest(requestOptions, requestEvents, _dynamicEntityProviders);
            request.Events.OnCancel.AddListener(HandleResult);
            request.Events.OnFailed.AddListener(HandleResult);
            request.Events.OnSuccess.AddListener(HandleResult);
            request.Events.OnComplete.AddListener(HandleComplete);
            _transmitRequests.Add(request);
            // Call on create delegates
            VoiceEvents?.OnRequestInitialized?.Invoke(request);
            #pragma warning disable CS0618
            VoiceEvents?.OnRequestCreated?.Invoke(null);
            VoiceEvents?.OnSend?.Invoke(request);
            // Send & return
            request.Send(text);
            return request;
        }
References Meta.WitAi.VLog.E(), Meta.WitAi.WitService.HandleComplete(), Meta.WitAi.WitService.HandleResult(), Meta.WitAi.WitService.IsConfigurationValid(), and Meta.Voice.NLPRequest< TUnityEvent, TOptions, TEvents, TResults >.Send().
Activate() [2/2]
VoiceServiceRequest Meta.WitAi.WitService.Activate (WitRequestOptions requestOptions, VoiceServiceRequestEvents requestEvents)
Activate the microphone and wait for threshold and then send data.
Parameters
requestOptions Additional options such as dynamic entities
requestEvents Events specific to the request's lifecycle
Implements Meta.WitAi.IVoiceActivationHandler.
Definition at line 252 of file WitService.cs.
        {
            // Not valid
            if (!IsConfigurationValid())
            {
                VLog.E($"Your AppVoiceExperience \"{gameObject.name}\" does not have a wit config assigned. Understanding Viewer activations will not trigger in game events..");
                return null;
            }
            // Already recording
            if (_isActive)
            {
                return null;
            }
            // Stop recording
            StopRecording();
            // Now active
            _isActive = true;
            _lastSampleMarker = AudioBuffer.Instance.CreateMarker(ConfigurationProvider.RuntimeConfiguration.preferredActivationOffset);
            _lastMinVolumeLevelTime = float.PositiveInfinity;
            _lastWordTime = float.PositiveInfinity;
            _receivedTranscription = false;
            // Generate request
            WitRequest request = WitRequestProvider != null ? WitRequestProvider.CreateWitRequest(RuntimeConfiguration.witConfiguration, requestOptions, requestEvents, _dynamicEntityProviders)
                : RuntimeConfiguration.witConfiguration.CreateSpeechRequest(requestOptions, requestEvents, _dynamicEntityProviders);
            SetupRequest(request);
            // Start recording if possible
            if (ShouldSendMicData)
            {
                if (!AudioBuffer.Instance.IsRecording(this))
                {
                    _minKeepAliveWasHit = false;
                    _isSoundWakeActive = true;
                    StartRecording();
                }
                _recordingRequest.ActivateAudio();
            }
            // Activate transcription provider
            _activeTranscriptionProvider?.Activate();
            // Return the generated request
            return _recordingRequest;
        }
References Meta.WitAi.Interfaces.ITranscriptionProvider.Activate(), Meta.WitAi.VLog.E(), Meta.WitAi.WitService.IsConfigurationValid(), and Meta.WitAi.WitService.SetupRequest().
ActivateImmediately()
VoiceServiceRequest Meta.WitAi.WitService.ActivateImmediately (WitRequestOptions requestOptions, VoiceServiceRequestEvents requestEvents)
Activate the microphone and send data for NLU processing with custom request options.
Parameters
requestOptions Additional options such as dynamic entities
requestEvents Events specific to the request's lifecycle
Implements Meta.WitAi.IVoiceActivationHandler.
Definition at line 304 of file WitService.cs.
        {
            // Activate mic & generate request if possible
            var request = Activate(requestOptions, requestEvents);
            if (request == null)
            {
                return null;
            }
            // Send recording request
            SendRecordingRequest();
            // Start marker
            _lastSampleMarker = AudioBuffer.Instance.CreateMarker(ConfigurationProvider
                .RuntimeConfiguration.preferredActivationOffset);
            // Return the request
            return request;
        }
References Meta.WitAi.WitService.Activate(), and Meta.WitAi.WitService.SendRecordingRequest().
Awake()
void Meta.WitAi.WitService.Awake () protected
Definition at line 170 of file WitService.cs.
        {
            _dataReadyHandlers = GetComponents<IWitByteDataReadyHandler>();
            _dataSentHandlers = GetComponents<IWitByteDataSentHandler>();
        }
Deactivate()
void Meta.WitAi.WitService.Deactivate ()
Stop listening and submit the collected microphone data to wit for processing.
Implements Meta.WitAi.IVoiceActivationHandler.
Definition at line 602 of file WitService.cs.
        {
            DeactivateRequest(AudioBuffer.Instance.IsRecording(this) ? VoiceEvents?.OnStoppedListeningDueToDeactivation : null, false);
        }
DeactivateAndAbortRequest() [1/2]
void Meta.WitAi.WitService.DeactivateAndAbortRequest ()
Stop listening and abort any requests that may be active without waiting for a response.
Implements Meta.WitAi.IVoiceActivationHandler.
Definition at line 621 of file WitService.cs.
        {
            DeactivateRequest(AudioBuffer.Instance.IsRecording(this) ? VoiceEvents?.OnStoppedListeningDueToDeactivation : null, true);
        }
DeactivateAndAbortRequest() [2/2]
void Meta.WitAi.WitService.DeactivateAndAbortRequest (VoiceServiceRequest request)
Stop listening and cancel a specific report.
Implements Meta.WitAi.IVoiceActivationHandler.
Definition at line 610 of file WitService.cs.
        {
            if (request != null)
            {
                VoiceEvents?.OnAborting?.Invoke();
                request.Cancel();
            }
        }
DeactivateDueToTimeLimit()
IEnumerator Meta.WitAi.WitService.DeactivateDueToTimeLimit () private
Definition at line 626 of file WitService.cs.
        {
            yield return new WaitForSeconds(RuntimeConfiguration.maxRecordingTime);
            if (IsRequestActive)
            {
                VLog.D($"Deactivated input due to timeout.\nMax Record Time: {RuntimeConfiguration.maxRecordingTime}");
                DeactivateRequest(VoiceEvents?.OnStoppedListeningDueToTimeout, false);
            }
        }
DeactivateRequest()
void Meta.WitAi.WitService.DeactivateRequest (UnityEvent onComplete = null, bool abort = false) private
Definition at line 635 of file WitService.cs.
        {
            // Aborting
            if (abort)
            {
                VoiceEvents?.OnAborting?.Invoke();
            }
            // Stop timeout coroutine
            if (null != _timeLimitCoroutine)
            {
                StopCoroutine(_timeLimitCoroutine);
                _timeLimitCoroutine = null;
            }
            // No longer active
            _isActive = false;
            // Stop recording
            StopRecording();
            FinalizeAudioDurationTracker();
            // Deactivate transcription provider
            _activeTranscriptionProvider?.Deactivate();
            // Deactivate recording request
            WitRequest previousRequest = _recordingRequest;
            _recordingRequest = null;
            DeactivateWitRequest(previousRequest, abort);
            // Abort transmitting requests
            if (abort)
            {
                HashSet<VoiceServiceRequest> requests = _transmitRequests;
                _transmitRequests = new HashSet<VoiceServiceRequest>();
                foreach (var request in requests)
                {
                    DeactivateWitRequest(request, true);
                }
            }
            // Transmit recording request
            else if (previousRequest != null && previousRequest.IsActive && _minKeepAliveWasHit)
            {
                _transmitRequests.Add(_recordingRequest);
                _recordingRequest = null;
                VoiceEvents?.OnMicDataSent?.Invoke();
            }
            // Disable below event
            _minKeepAliveWasHit = false;
            // Perform on complete event
            onComplete?.Invoke();
        }
DeactivateWitRequest()
void Meta.WitAi.WitService.DeactivateWitRequest (VoiceServiceRequest request, bool abort) private
Definition at line 689 of file WitService.cs.
        {
            if (request == null)
            {
                return;
            }
            if (abort)
            {
                request.Cancel("Request was aborted by user.");
            }
            else if (request.IsAudioInputActivated)
            {
                request.DeactivateAudio();
            }
        }
ExecuteRequest()
void Meta.WitAi.WitService.ExecuteRequest (WitRequest newRequest)
Execute a wit request immediately.
Parameters
recordingRequest
Definition at line 376 of file WitService.cs.
        {
            if (newRequest == null || newRequest.State != VoiceRequestState.Initialized)
            {
                return;
            }
            SetupRequest(newRequest);
            newRequest.AudioEncoding = AudioBuffer.Instance.AudioEncoding;
            newRequest.audioDurationTracker = new AudioDurationTracker(_recordingRequest.Options?.RequestId,
                newRequest.AudioEncoding);
            #pragma warning disable CS0618
            VoiceEvents.OnRequestCreated?.Invoke(_recordingRequest);
            VoiceEvents.OnSend?.Invoke(_recordingRequest);
            _timeLimitCoroutine = StartCoroutine(DeactivateDueToTimeLimit());
            newRequest.Send();
        }
References Meta.WitAi.WitRequest.AudioEncoding, Meta.Voice.NLPRequest< TUnityEvent, TOptions, TEvents, TResults >.Send(), and Meta.WitAi.WitService.SetupRequest().
FinalizeAudioDurationTracker()
void Meta.WitAi.WitService.FinalizeAudioDurationTracker () private
Definition at line 572 of file WitService.cs.
        {
            AudioDurationTracker audioDurationTracker = _recordingRequest?.audioDurationTracker;
            if (audioDurationTracker == null)
            {
                return;
            }
            if (null == _recordingRequest)
            {
                VLog.W($"Missing request for recording.");
                return;
            }
            string requestId = _recordingRequest.Options?.RequestId;
            if (!string.Equals(requestId, audioDurationTracker.GetRequestId()))
            {
                VLog.W($"Mismatch in request IDs when finalizing AudioDurationTracker. " +
                       $"Expected {requestId} but got {audioDurationTracker.GetRequestId()}");
                return;
            }
            audioDurationTracker.FinalizeAudio();
            TelemetryEvents.OnAudioTrackerFinished?.Invoke(audioDurationTracker.GetFinalizeTimeStamp(), audioDurationTracker.GetAudioDuration());
        }
HandleComplete()
void Meta.WitAi.WitService.HandleComplete (VoiceServiceRequest request) private
Handle request completion.
Definition at line 774 of file WitService.cs.
        {
            // Remove all event listeners
            request.Events.OnPartialTranscription.RemoveListener(OnPartialTranscription);
            request.Events.OnFullTranscription.RemoveListener(OnFullTranscription);
            request.Events.OnPartialResponse.RemoveListener(HandlePartialResult);
            request.Events.OnCancel.RemoveListener(HandleResult);
            request.Events.OnFailed.RemoveListener(HandleResult);
            request.Events.OnSuccess.RemoveListener(HandleResult);
            request.Events.OnComplete.RemoveListener(HandleComplete);
            // Complete
            VoiceEvents?.OnComplete?.Invoke(request);
        }
References Meta.WitAi.WitService.HandleComplete(), Meta.WitAi.WitService.HandlePartialResult(), and Meta.WitAi.WitService.HandleResult().
HandlePartialResult()
void Meta.WitAi.WitService.HandlePartialResult (WitResponseNode response) private
Main thread call to handle partial response callbacks.
Definition at line 723 of file WitService.cs.
        {
            if (response != null)
            {
                VoiceEvents?.OnPartialResponse?.Invoke(response);
            }
        }
HandleResult()
void Meta.WitAi.WitService.HandleResult (VoiceServiceRequest request) private
Main thread call to handle result callbacks.
Definition at line 733 of file WitService.cs.
        {
            // If result is obtained before transcription
            if (request == _recordingRequest)
            {
                DeactivateRequest(null, false);
            }
            // Handle Success
            if (request.State == VoiceRequestState.Successful)
            {
                VLog.D("Request Success");
                VoiceEvents?.OnResponse?.Invoke(request.Results.ResponseData);
                VoiceEvents?.OnRequestCompleted?.Invoke();
            }
            // Handle Cancellation
            else if (request.State == VoiceRequestState.Canceled)
            {
                VLog.D($"Request Canceled\nReason: {request.Results.Message}");
                VoiceEvents?.OnCanceled?.Invoke(request.Results.Message);
                if (!string.Equals(request.Results.Message, WitConstants.CANCEL_MESSAGE_PRE_SEND))
                {
                    VoiceEvents?.OnAborted?.Invoke();
                }
            }
            // Handle Failure
            else if (request.State == VoiceRequestState.Failed)
            {
                VLog.D($"Request Failed\nError: {request.Results.Message}");
                VoiceEvents?.OnError?.Invoke("HTTP Error " + request.Results.StatusCode, request.Results.Message);
                VoiceEvents?.OnRequestCompleted?.Invoke();
            }
            // Remove from transmit list, missing if aborted
            if ( _transmitRequests.Contains(request))
            {
                _transmitRequests.Remove(request);
            }
        }
References Meta.WitAi.VLog.D(), and Meta.WitAi.Requests.VoiceServiceRequest.StatusCode.
IsConfigurationValid()
virtual bool Meta.WitAi.WitService.IsConfigurationValid () virtual
Check configuration, client access token & app id.
Definition at line 162 of file WitService.cs.
        {
            return RuntimeConfiguration.witConfiguration != null &&
                   !string.IsNullOrEmpty(RuntimeConfiguration.witConfiguration.GetClientAccessToken());
        }
References Meta.WitAi.Data.Configuration.WitConfiguration.GetClientAccessToken().
OnByteDataReady()
void Meta.WitAi.WitService.OnByteDataReady (byte[] buffer, int offset, int length) private
Definition at line 482 of file WitService.cs.
        {
            VoiceEvents?.OnByteDataReady.Invoke(buffer, offset, length);
            for (int i = 0; null != _dataReadyHandlers && i < _dataReadyHandlers.Length; i++)
            {
                _dataReadyHandlers[i].OnWitDataReady(buffer, offset, length);
            }
        }
OnDisable()
void Meta.WitAi.WitService.OnDisable () protected
Definition at line 193 of file WitService.cs.
        {
            SceneManager.sceneLoaded -= OnSceneLoaded;
            AudioBufferEvents e = AudioBuffer.Instance?.Events;
            SetMicDelegates(false);
        }
OnEnable()
void Meta.WitAi.WitService.OnEnable () protected
Definition at line 176 of file WitService.cs.
        {
            SceneManager.sceneLoaded += OnSceneLoaded;
            _runtimeConfigProvider = GetComponent<IWitRuntimeConfigProvider>();
            _voiceEventProvider = GetComponent<IVoiceEventProvider>();
            if (null == _activeTranscriptionProvider && null != RuntimeConfiguration &&
                RuntimeConfiguration.customTranscriptionProvider)
            {
                TranscriptionProvider = RuntimeConfiguration.customTranscriptionProvider;
            }
            SetMicDelegates(true);
            _dynamicEntityProviders = GetComponents<IDynamicEntitiesProvider>();
        }
OnFullTranscription()
void Meta.WitAi.WitService.OnFullTranscription (string transcription) private
Definition at line 713 of file WitService.cs.
        {
            VoiceEvents?.OnFullTranscription?.Invoke(transcription);
        }
OnMicLevelChanged()
void Meta.WitAi.WitService.OnMicLevelChanged (float level) private
Definition at line 552 of file WitService.cs.
        {
            if (null != TranscriptionProvider && TranscriptionProvider.OverrideMicLevel) return;
            if (level > RuntimeConfiguration.minKeepAliveVolume)
            {
                _lastMinVolumeLevelTime = _time;
                _minKeepAliveWasHit = true;
            }
            VoiceEvents?.OnMicLevelChanged?.Invoke(level);
        }
OnMicSampleReady()
void Meta.WitAi.WitService.OnMicSampleReady (RingBuffer< byte >::Marker marker, float levelMax) private
Definition at line 492 of file WitService.cs.
        {
            if (null == _lastSampleMarker || _recordingRequest == null) return;
            if (_minSampleByteCount > _lastSampleMarker.RingBuffer.Capacity)
            {
                _minSampleByteCount = _lastSampleMarker.RingBuffer.Capacity;
            }
            if (_recordingRequest.State == VoiceRequestState.Transmitting && _recordingRequest.IsInputStreamReady && _lastSampleMarker.AvailableByteCount >= _minSampleByteCount)
            {
                // Flush the marker since the last read and send it to Wit
                _lastSampleMarker.ReadIntoWriters(
                    (buffer, offset, length) =>
                    {
                        _recordingRequest.Write(buffer, offset, length);
                    },
                    (buffer, offset, length) => VoiceEvents?.OnByteDataSent?.Invoke(buffer, offset, length),
                    (buffer, offset, length) =>
                    {
                        for (int i = 0; i < _dataSentHandlers.Length; i++)
{
                            _dataSentHandlers[i]?.OnWitDataSent(buffer, offset, length);
                        }
                    });
                if (_receivedTranscription)
                {
                    float elapsed = _time - _lastWordTime;
                    if (elapsed >
                        RuntimeConfiguration.minTranscriptionKeepAliveTimeInSeconds)
                    {
                        VLog.D($"Deactivated due to inactivity. No new words detected in {elapsed:0.00} seconds.");
                        DeactivateRequest(VoiceEvents?.OnStoppedListeningDueToInactivity);
                    }
                }
                else
                {
                    float elapsed = _time - _lastMinVolumeLevelTime;
                    if (elapsed >
                        RuntimeConfiguration.minKeepAliveTimeInSeconds)
                    {
                        VLog.D($"Deactivated due to inactivity. No sound detected in {elapsed:0.00} seconds.");
                        DeactivateRequest(VoiceEvents?.OnStoppedListeningDueToInactivity);
                    }
                }
            }
            else if (_isSoundWakeActive && levelMax > RuntimeConfiguration.soundWakeThreshold)
            {
                VoiceEvents?.OnMinimumWakeThresholdHit?.Invoke();
                SendRecordingRequest();
                _lastSampleMarker.Offset(RuntimeConfiguration.sampleLengthInMs * -2);
            }
        }
OnMicStartListening()
void Meta.WitAi.WitService.OnMicStartListening () private
Definition at line 472 of file WitService.cs.
        {
            VoiceEvents?.OnStartListening?.Invoke();
        }
OnMicStoppedListening()
void Meta.WitAi.WitService.OnMicStoppedListening () private
Definition at line 477 of file WitService.cs.
        {
            VoiceEvents?.OnStoppedListening?.Invoke();
        }
OnPartialTranscription()
void Meta.WitAi.WitService.OnPartialTranscription (string transcription) private
Definition at line 707 of file WitService.cs.
        {
            _receivedTranscription = true;
            _lastWordTime = _time;
            VoiceEvents?.OnPartialTranscription.Invoke(transcription);
        }
OnSceneLoaded()
virtual void Meta.WitAi.WitService.OnSceneLoaded (Scene scene, LoadSceneMode mode) protected virtual
Definition at line 200 of file WitService.cs.
        {
            SetMicDelegates(true);
        }
OnTranscriptionMicLevelChanged()
void Meta.WitAi.WitService.OnTranscriptionMicLevelChanged (float level) private
Definition at line 564 of file WitService.cs.
        {
            if (null != TranscriptionProvider && TranscriptionProvider.OverrideMicLevel)
            {
                OnMicLevelChanged(level);
            }
        }
OnWitReadyForData()
void Meta.WitAi.WitService.OnWitReadyForData () private
Definition at line 440 of file WitService.cs.
        {
            _lastMinVolumeLevelTime = _time;
            if (!AudioBuffer.Instance.IsRecording(this))
            {
                StartRecording();
            }
        }
SendRecordingRequest()
virtual void Meta.WitAi.WitService.SendRecordingRequest () protected virtual
Sends recording request if possible.
Definition at line 326 of file WitService.cs.
        {
            if (_recordingRequest == null || _recordingRequest.State != VoiceRequestState.Initialized)
            {
                return;
            }
            // Sound wake active
            _isSoundWakeActive = false;
            // Execute request
            if (ShouldSendMicData)
            {
                ExecuteRequest(_recordingRequest);
            }
        }
References Meta.WitAi.WitService.ExecuteRequest().
SetMicDelegates()
void Meta.WitAi.WitService.SetMicDelegates (bool add) protected
Definition at line 207 of file WitService.cs.
        {
            // Obtain buffer
            if (_buffer == null)
            {
                _buffer = AudioBuffer.Instance;
                _bufferDelegates = false;
            }
            // Get events if possible
            AudioBufferEvents e = _buffer?.Events;
            if (e == null)
            {
                return;
            }
            // Already set
            if (_bufferDelegates == add)
            {
                return;
            }
            // Set delegates
            _bufferDelegates = add;
            // Add delegates
            if (add)
            {
                e.OnMicLevelChanged.AddListener(OnMicLevelChanged);
                e.OnByteDataReady.AddListener(OnByteDataReady);
                e.OnSampleReady += OnMicSampleReady;
            }
            // Remove delegates
            else
            {
                e.OnMicLevelChanged.RemoveListener(OnMicLevelChanged);
                e.OnByteDataReady.RemoveListener(OnByteDataReady);
                e.OnSampleReady -= OnMicSampleReady;
            }
        }
SetupRequest()
void Meta.WitAi.WitService.SetupRequest (WitRequest newRequest) protected
Setup recording request.
Parameters
recordingRequest
Definition at line 346 of file WitService.cs.
        {
            if (_recordingRequest == newRequest)
            {
                return;
            }
            // Set request & events
            _recordingRequest = newRequest;
            // Add input stream ready check
            _recordingRequest.onInputStreamReady += r => OnWitReadyForData();
            // Add events
            _recordingRequest.Events.OnPartialTranscription.AddListener(OnPartialTranscription);
            _recordingRequest.Events.OnFullTranscription.AddListener(OnFullTranscription);
            _recordingRequest.Events.OnPartialResponse.AddListener(HandlePartialResult);
            _recordingRequest.Events.OnCancel.AddListener(HandleResult);
            _recordingRequest.Events.OnFailed.AddListener(HandleResult);
            _recordingRequest.Events.OnSuccess.AddListener(HandleResult);
            _recordingRequest.Events.OnComplete.AddListener(HandleComplete);
            // Call service events
            VoiceEvents.OnRequestOptionSetup?.Invoke(_recordingRequest.Options);
            VoiceEvents.OnRequestInitialized?.Invoke(_recordingRequest);
        }
References Meta.WitAi.WitService.HandleComplete(), Meta.WitAi.WitService.HandlePartialResult(), and Meta.WitAi.WitService.HandleResult().
StartRecording()
void Meta.WitAi.WitService.StartRecording () private
Definition at line 449 of file WitService.cs.
        {
            // Check for input
            if (!AudioBuffer.Instance.IsInputAvailable)
            {
                AudioBuffer.Instance.CheckForInput();
            }
            // Wait for input and then try again
            if (!AudioBuffer.Instance.IsInputAvailable)
            {
                VoiceEvents.OnError.Invoke("Input Error", "No input source was available. Cannot activate for voice input.");
                return;
            }
            // Already recording
            if (AudioBuffer.Instance.IsRecording(this))
            {
                return;
            }
            // Start recording
            AudioBuffer.Instance.StartRecording(this);
        }
StopRecording()
void Meta.WitAi.WitService.StopRecording () private
Definition at line 434 of file WitService.cs.
        {
            if (!AudioBuffer.Instance.IsRecording(this)) return;
            AudioBuffer.Instance.StopRecording(this);
        }
Update()
void Meta.WitAi.WitService.Update () private
Definition at line 547 of file WitService.cs.
        {
            _time = Time.time;
        }
Member Data Documentation
_activeTranscriptionProvider
ITranscriptionProvider Meta.WitAi.WitService._activeTranscriptionProvider private
Definition at line 39 of file WitService.cs.
_buffer
AudioBuffer Meta.WitAi.WitService._buffer private
Definition at line 205 of file WitService.cs.
_bufferDelegates
bool Meta.WitAi.WitService._bufferDelegates = false private
Definition at line 206 of file WitService.cs.
_dataReadyHandlers
IWitByteDataReadyHandler [] Meta.WitAi.WitService._dataReadyHandlers private
Definition at line 55 of file WitService.cs.
_dataSentHandlers
IWitByteDataSentHandler [] Meta.WitAi.WitService._dataSentHandlers private
Definition at line 56 of file WitService.cs.
_dynamicEntityProviders
IDynamicEntitiesProvider [] Meta.WitAi.WitService._dynamicEntityProviders private
Definition at line 57 of file WitService.cs.
_isActive
bool Meta.WitAi.WitService._isActive private
Definition at line 33 of file WitService.cs.
_isSoundWakeActive
bool Meta.WitAi.WitService._isSoundWakeActive private
Definition at line 30 of file WitService.cs.
_lastMinVolumeLevelTime
float Meta.WitAi.WitService._lastMinVolumeLevelTime private
Definition at line 27 of file WitService.cs.
_lastSampleMarker
RingBuffer<byte>.Marker Meta.WitAi.WitService._lastSampleMarker private
Definition at line 31 of file WitService.cs.
_lastWordTime
float Meta.WitAi.WitService._lastWordTime private
Definition at line 45 of file WitService.cs.
_minKeepAliveWasHit
bool Meta.WitAi.WitService._minKeepAliveWasHit private
Definition at line 32 of file WitService.cs.
_minSampleByteCount
long Meta.WitAi.WitService._minSampleByteCount = 1024 * 10 private
Definition at line 34 of file WitService.cs.
_queueHandler
Coroutine Meta.WitAi.WitService._queueHandler private
Definition at line 49 of file WitService.cs.
_receivedTranscription
bool Meta.WitAi.WitService._receivedTranscription private
Definition at line 44 of file WitService.cs.
_recordingRequest
WitRequest Meta.WitAi.WitService._recordingRequest private
Definition at line 28 of file WitService.cs.
_runtimeConfigProvider
IWitRuntimeConfigProvider Meta.WitAi.WitService._runtimeConfigProvider private
Definition at line 38 of file WitService.cs.
_telemetryEventsProvider
ITelemetryEventsProvider Meta.WitAi.WitService._telemetryEventsProvider private
Definition at line 37 of file WitService.cs.
_time
float Meta.WitAi.WitService._time private
Definition at line 58 of file WitService.cs.
_timeLimitCoroutine
Coroutine Meta.WitAi.WitService._timeLimitCoroutine private
Definition at line 40 of file WitService.cs.
_transmitRequests
HashSet<VoiceServiceRequest> Meta.WitAi.WitService._transmitRequests = new HashSet<VoiceServiceRequest>() private
Definition at line 48 of file WitService.cs.
_voiceEventProvider
IVoiceEventProvider Meta.WitAi.WitService._voiceEventProvider private
Definition at line 36 of file WitService.cs.
_witRequestProvider
IWitRequestProvider Meta.WitAi.WitService._witRequestProvider private
Definition at line 41 of file WitService.cs.
Property Documentation
Active
bool Meta.WitAi.WitService.Active get
Returns true if wit is currently active and listening with the mic.
Implements Meta.WitAi.IVoiceActivationHandler.
Definition at line 65 of file WitService.cs.
Configuration
WitConfiguration Meta.WitAi.WitService.Configuration get
Implements Meta.WitAi.Interfaces.IWitConfigurationProvider.
Definition at line 52 of file WitService.cs.
ConfigurationProvider
IWitRuntimeConfigProvider Meta.WitAi.WitService.ConfigurationProvider get set
Definition at line 94 of file WitService.cs.
        {
            get => _runtimeConfigProvider;
            set => _runtimeConfigProvider = value;
        }
IsRequestActive
bool Meta.WitAi.WitService.IsRequestActive get
Active if recording, transmitting, or queued up.
Definition at line 70 of file WitService.cs.
        {
            get
            {
                if (null != _recordingRequest && _recordingRequest.IsActive)
                {
                    return true;
                }
                return false;
            }
        }
MicActive
bool Meta.WitAi.WitService.MicActive get
Definition at line 154 of file WitService.cs.
RuntimeConfiguration
WitRuntimeConfiguration Meta.WitAi.WitService.RuntimeConfiguration get
Implements Meta.WitAi.IWitRuntimeConfigProvider.
Definition at line 100 of file WitService.cs.
ShouldSendMicData
bool Meta.WitAi.WitService.ShouldSendMicData get protected
Definition at line 156 of file WitService.cs.
TelemetryEvents
TelemetryEvents Meta.WitAi.WitService.TelemetryEvents get
Implements Meta.WitAi.ITelemetryEventsProvider.
Definition at line 105 of file WitService.cs.
TelemetryEventsProvider
ITelemetryEventsProvider Meta.WitAi.WitService.TelemetryEventsProvider get set
Definition at line 88 of file WitService.cs.
        {
            get => _telemetryEventsProvider;
            set => _telemetryEventsProvider = value;
        }
TranscriptionProvider
ITranscriptionProvider Meta.WitAi.WitService.TranscriptionProvider get set
Gets/Sets a custom transcription provider. This can be used to replace any built in asr with an on device model or other provided source.
Definition at line 111 of file WitService.cs.
        {
            get => _activeTranscriptionProvider;
            set
            {
                if (null != _activeTranscriptionProvider)
                {
                    _activeTranscriptionProvider.OnFullTranscription.RemoveListener(
                        OnFullTranscription);
                    _activeTranscriptionProvider.OnPartialTranscription.RemoveListener(
                        OnPartialTranscription);
                    _activeTranscriptionProvider.OnMicLevelChanged.RemoveListener(
                        OnTranscriptionMicLevelChanged);
                    _activeTranscriptionProvider.OnStartListening.RemoveListener(
                        OnMicStartListening);
                    _activeTranscriptionProvider.OnStoppedListening.RemoveListener(
                        OnMicStoppedListening);
                }
                _activeTranscriptionProvider = value;
                if (null != _activeTranscriptionProvider)
                {
                    _activeTranscriptionProvider.OnFullTranscription.AddListener(
                        OnFullTranscription);
                    _activeTranscriptionProvider.OnPartialTranscription.AddListener(
                        OnPartialTranscription);
                    _activeTranscriptionProvider.OnMicLevelChanged.AddListener(
                        OnTranscriptionMicLevelChanged);
                    _activeTranscriptionProvider.OnStartListening.AddListener(
                        OnMicStartListening);
                    _activeTranscriptionProvider.OnStoppedListening.AddListener(
                        OnMicStoppedListening);
                }
            }
        }
VoiceEventProvider
IVoiceEventProvider Meta.WitAi.WitService.VoiceEventProvider get set
Definition at line 82 of file WitService.cs.
        {
            get => _voiceEventProvider;
            set => _voiceEventProvider = value;
        }
VoiceEvents
VoiceEvents Meta.WitAi.WitService.VoiceEvents get
Implements Meta.WitAi.IVoiceEventProvider.
Definition at line 103 of file WitService.cs.
WitRequestProvider
IWitRequestProvider Meta.WitAi.WitService.WitRequestProvider get set
Definition at line 148 of file WitService.cs.
        {
            get => _witRequestProvider;
            set => _witRequestProvider = value;
        }
The documentation for this class was generated from the following file:
Assets/Oculus/Voice/Lib/Wit.ai/Scripts/Runtime/WitService.cs