VR_Test: Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults > Class Template Reference
Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults > Class Template Reference abstract
Abstract class for all transcription requests.
Public Member Functions
virtual void ActivateAudio ()
Public request to activate audio input.
virtual void DeactivateAudio ()
Public request to deactivate audio input.
override void Send ()
Ensure audio is activated prior to sending.
override void Cancel (string reason=WitConstants.CANCEL_MESSAGE_DEFAULT)
Ensure audio is deactivated prior to cancellation.
Public Member Functions inherited from Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >
VoiceRequest (TOptions newOptions, TEvents newEvents)
Constructor class for voice requests.
Protected Member Functions
TranscriptionRequest (TOptions newOptions, TEvents newEvents)
Constructor class for transcription requests.
virtual void SetAudioInputState (VoiceAudioInputState newAudioInputState)
Set audio input state.
override void AppendLogData (StringBuilder log, bool warning)
Append request specific data to log.
void ApplyTranscription (string newTranscription, bool newIsFinal)
Applies a transcription to the current results.
virtual void OnTranscriptionChanged ()
Called when transcription has been set.
string GetActivateAudioError ()
Implementations need to provide errors when audio input is not found.
virtual void OnAudioActivation ()
Called when audio activation begins.
void HandleAudioActivation ()
Child class audio activation handler needs to call SetAudioInputState when complete.
virtual void OnStartListening ()
Called when audio activation is in effect and input is being listened to.
virtual void OnAudioDeactivation ()
Called when audio deactivation begins.
void HandleAudioDeactivation ()
Child class audio deactivation handler needs to call SetAudioInputState when complete.
virtual void OnStopListening ()
Called when audio input state is no longer being listened to.
override void OnSuccess ()
Method for subclass success handling.
Protected Member Functions inherited from Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >
virtual void OnInit ()
Call after initialization.
virtual void SetState (VoiceRequestState newState)
Apply the voice request state.
void SetDownloadProgress (float newProgress)
Set current request download progress.
void SetUploadProgress (float newProgress)
Set current request upload progress.
void RaiseEvent (TUnityEvent requestEvent)
Raises a voice request event.
void Log (string log, bool warning=false)
Internal method for.
void LogW (string log)
virtual string GetSendError ()
Internal way to determine send error.
virtual void OnSend ()
Call after transmission begins.
void HandleSend ()
Child class send implementation Call HandleFailure, HandleCancel from this class.
TResults GetResultsWithMessage (string newMessage)
Returns an empty result object with a specific message.
virtual void HandleFailure (string error)
Method for handling failure with only an error string.
virtual void HandleFailure (TResults results)
Method for handling failure with a full result object.
virtual void OnFailed ()
Call after failure state set.
virtual void HandleSuccess (TResults results)
Method for handling success with a full result object.
void HandleCancel ()
Handle cancelation in subclass.
virtual void OnCancel ()
Call after cancellation state set.
virtual void OnComplete ()
Call after failure, success or cancellation.
Properties
VoiceAudioInputState AudioInputState = VoiceAudioInputState.Off [get, private set]
The current audio input state.
bool IsAudioInputActivated [get]
Whether or not audio is currently activated.
bool IsListening [get]
Whether or not audio is currently being listened to.
bool CanActivateAudio [get]
Determine whether audio can be activated based on activation error existing.
bool CanDeactivateAudio [get]
Determine whether audio can be activated based on activation error existing.
string Transcription [get]
Transcription data.
bool IsFinalTranscription [get]
Whether the current transcription is a final transcription or not.
string[] FinalTranscriptions [get]
An array of all finalized transcriptions.
Properties inherited from Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >
VoiceRequestState State = (VoiceRequestState) (-1) [get, private set]
The states of a voice request.
bool IsActive [get]
Active if not currently canceled, failed or successful.
float DownloadProgress = 0f [get, private set]
Download progress of the current request transmission if available.
float UploadProgress = 0f [get, private set]
Upload progress of the current request transmission if available.
TOptions Options [get, private set]
Options sent as the request parameters.
TEvents Events [get, private set]
Events specific to this voice request.
TResults Results [get, protected set]
Results returned from the request.
bool CanSend [get]
Whether request can currently transmit data.
Properties inherited from Meta.Voice.IVoiceRequest< TUnityEvent, TOptions, TEvents, TResults >
Properties inherited from Meta.Voice.ITranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >
Detailed Description
Abstract class for all transcription requests.
Template Parameters
TUnityEvent The type of event callback performed by TEvents for all event callbacks
TOptions The type containing all specific options to be passed to the end service.
TEvents The type containing all events of TSession to be called throughout the lifecycle of the request.
TResults The type containing all data that can be returned from the end service.
Type Constraints
TUnityEvent : UnityEventBase
TOptions : ITranscriptionRequestOptions
TEvents : TranscriptionRequestEvents<TUnityEvent>
TResults : ITranscriptionRequestResults
Definition at line 23 of file TranscriptionRequest.cs.
Constructor & Destructor Documentation
TranscriptionRequest()
Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.TranscriptionRequest (TOptions newOptions, TEvents newEvents) protected
Constructor class for transcription requests.
Parameters
newOptions The request parameters to be used
newEvents The request events to be called throughout it's lifecycle
Definition at line 62 of file TranscriptionRequest.cs.
: base(newOptions, newEvents) {}
Member Function Documentation
ActivateAudio()
virtual void Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.ActivateAudio () virtual
Public request to activate audio input.
Implements Meta.Voice.ITranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.
Definition at line 166 of file TranscriptionRequest.cs.
        {
            // Ignore if already activated
            if (IsAudioInputActivated)
            {
                LogW($"Activate Audio Ignored\nReason: Already activated");
                return;
            }
            // Fail if activation is not possible
            string activationError = GetActivateAudioError();
            if (!string.IsNullOrEmpty(activationError))
            {
                LogW($"Activate Audio Failed\nReason: {activationError}");
                HandleFailure(activationError);
                return;
            }
            // Begin activating
            SetAudioInputState(VoiceAudioInputState.Activating);
        }
References Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.GetActivateAudioError(), Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.HandleFailure(), Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.IsAudioInputActivated, and Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.SetAudioInputState().
AppendLogData()
override void Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.AppendLogData (StringBuilder log, bool warning) protected virtual
Append request specific data to log.
Parameters
log Building log
warning True if this is a warning log
Reimplemented from Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.
Definition at line 103 of file TranscriptionRequest.cs.
        {
            base.AppendLogData(log, warning);
            // Append audio input state
            log.AppendLine($"Audio Input State: {AudioInputState}");
            // Append current transcription
            log.AppendLine($"Transcription: {Results?.Transcription}");
        }
ApplyTranscription()
void Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.ApplyTranscription (string newTranscription, bool newIsFinal) abstract protected
Applies a transcription to the current results.
Parameters
newTranscription The transcription returned
Cancel()
override void Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.Cancel (string reason = WitConstants::CANCEL_MESSAGE_DEFAULT) virtual
Ensure audio is deactivated prior to cancellation.
Reimplemented from Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.
Definition at line 297 of file TranscriptionRequest.cs.
        {
            // Deactivate audio if needed
            if (IsAudioInputActivated)
            {
                DeactivateAudio();
            }
            // Cancel audio request
            base.Cancel(reason);
        }
References Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.DeactivateAudio(), and Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.IsAudioInputActivated.
DeactivateAudio()
virtual void Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.DeactivateAudio () virtual
Public request to deactivate audio input.
Implements Meta.Voice.ITranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.
Definition at line 218 of file TranscriptionRequest.cs.
        {
            // Ignore if not activated
            if (!IsAudioInputActivated)
            {
                LogW($"Deactivate Audio Ignored\nReason: Not currently activated");
                return;
            }
            // Set deactivation
            SetAudioInputState(VoiceAudioInputState.Deactivating);
        }
References Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.IsAudioInputActivated, and Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.SetAudioInputState().
OnAudioActivation()
virtual void Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.OnAudioActivation () protected virtual
Called when audio activation begins.
Definition at line 191 of file TranscriptionRequest.cs.
        {
            Log("Activate Audio Begin");
            RaiseEvent(Events?.OnAudioActivation);
        }
References Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.Events, Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.Log(), Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.OnAudioActivation(), and Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.RaiseEvent().
OnAudioDeactivation()
virtual void Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.OnAudioDeactivation () protected virtual
Called when audio deactivation begins.
Definition at line 234 of file TranscriptionRequest.cs.
        {
            Log("Deactivate Audio Begin");
            RaiseEvent(Events?.OnAudioDeactivation);
        }
References Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.Events, Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.Log(), Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.OnAudioDeactivation(), and Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.RaiseEvent().
OnStartListening()
virtual void Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.OnStartListening () protected virtual
Called when audio activation is in effect and input is being listened to.
Definition at line 207 of file TranscriptionRequest.cs.
        {
            Log("Activate Audio Complete");
            RaiseEvent(Events?.OnStartListening);
        }
References Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.Events, Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.Log(), Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.OnStartListening(), and Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.RaiseEvent().
OnStopListening()
virtual void Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.OnStopListening () protected virtual
Called when audio input state is no longer being listened to.
Definition at line 250 of file TranscriptionRequest.cs.
        {
            Log("Deactivate Audio Complete");
            RaiseEvent(Events?.OnStopListening);
            // Handle early cancellation
            if (State == VoiceRequestState.Initialized)
            {
                Cancel(WitConstants.CANCEL_MESSAGE_PRE_SEND);
            }
        }
References Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.Cancel(), Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.Events, Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.Log(), Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.OnStopListening(), Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.RaiseEvent(), and Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.State.
OnSuccess()
override void Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.OnSuccess () protected virtual
Method for subclass success handling.
Reimplemented from Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.
Definition at line 281 of file TranscriptionRequest.cs.
        {
            // Handle transcription as though it is final
            if (!IsFinalTranscription && !string.IsNullOrEmpty(Transcription))
            {
                ApplyTranscription(Transcription, true);
            }
            // Call success events
            base.OnSuccess();
        }
References Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.ApplyTranscription(), Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.IsFinalTranscription, and Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.Transcription.
OnTranscriptionChanged()
virtual void Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.OnTranscriptionChanged () protected virtual
Called when transcription has been set.
Definition at line 144 of file TranscriptionRequest.cs.
        {
            if (!IsFinalTranscription)
            {
                Events?.OnPartialTranscription?.Invoke(Transcription);
            }
            else
            {
                Events?.OnFullTranscription?.Invoke(Transcription);
            }
        }
References Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.Events, Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.IsFinalTranscription, and Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.Transcription.
Send()
override void Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.Send () virtual
Ensure audio is activated prior to sending.
Reimplemented from Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.
Definition at line 267 of file TranscriptionRequest.cs.
        {
            // Activate audio if needed & possible
            if (!IsAudioInputActivated && CanActivateAudio && CanSend)
            {
                ActivateAudio();
            }
            // Send audio request if possible
            base.Send();
        }
References Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.ActivateAudio(), Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.CanActivateAudio, Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.CanSend, and Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.IsAudioInputActivated.
SetAudioInputState()
virtual void Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.SetAudioInputState (VoiceAudioInputState newAudioInputState) protected virtual
Set audio input state.
Definition at line 67 of file TranscriptionRequest.cs.
        {
            // Ignore if same
            if (AudioInputState == newAudioInputState)
            {
                return;
            }
            // Apply audio input state
            AudioInputState = newAudioInputState;
            RaiseEvent(Events?.OnAudioInputStateChange);
            // Raise events
            switch (AudioInputState)
            {
                case VoiceAudioInputState.Activating:
                    OnAudioActivation();
                    HandleAudioActivation();
                    break;
                case VoiceAudioInputState.On:
                    OnStartListening();
                    break;
                case VoiceAudioInputState.Deactivating:
                    OnAudioDeactivation();
                    HandleAudioDeactivation();
                    break;
                case VoiceAudioInputState.Off:
                    OnStopListening();
                    break;
            }
        }
References Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.AudioInputState, Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.Events, Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.HandleAudioActivation(), Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.HandleAudioDeactivation(), Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.OnAudioActivation(), Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.OnAudioDeactivation(), Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.OnStartListening(), Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.OnStopListening(), and Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.RaiseEvent().
Property Documentation
AudioInputState
VoiceAudioInputState Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.AudioInputState = VoiceAudioInputState.Off get private set
The current audio input state.
Implements Meta.Voice.ITranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.
Definition at line 34 of file TranscriptionRequest.cs.
{ get; private set; } = VoiceAudioInputState.Off;
CanActivateAudio
bool Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.CanActivateAudio get
Determine whether audio can be activated based on activation error existing.
Implements Meta.Voice.ITranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.
Definition at line 49 of file TranscriptionRequest.cs.
CanDeactivateAudio
bool Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.CanDeactivateAudio get
Determine whether audio can be activated based on activation error existing.
Implements Meta.Voice.ITranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.
Definition at line 54 of file TranscriptionRequest.cs.
FinalTranscriptions
string [] Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.FinalTranscriptions get
An array of all finalized transcriptions.
Definition at line 131 of file TranscriptionRequest.cs.
        {
            get => Results?.FinalTranscriptions;
        }
IsAudioInputActivated
bool Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.IsAudioInputActivated get
Whether or not audio is currently activated.
Implements Meta.Voice.ITranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.
Definition at line 39 of file TranscriptionRequest.cs.
IsFinalTranscription
bool Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.IsFinalTranscription get
Whether the current transcription is a final transcription or not.
Definition at line 124 of file TranscriptionRequest.cs.
        {
            get => Results != null && Results.IsFinalTranscription;
        }
IsListening
bool Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.IsListening get
Whether or not audio is currently being listened to.
Implements Meta.Voice.ITranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.
Definition at line 44 of file TranscriptionRequest.cs.
Transcription
string Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.Transcription get
Transcription data.
Definition at line 117 of file TranscriptionRequest.cs.
        {
            get => Results?.Transcription;
        }
The documentation for this class was generated from the following file:
Assets/Oculus/Voice/Lib/Wit.ai/Lib/Wit/Runtime/Requests/Transcription/TranscriptionRequest.cs