VR_Test: Meta.Voice.Audio.AudioClipStream Class Reference
Meta.Voice.Audio.AudioClipStream Class Reference abstract
A simple abstract class that can be used to simplify the code required for a custom IAudioClipStream.
Public Member Functions
virtual void AddSamples (float[] samples)
Adds an array of samples to the current stream.
virtual void SetTotalSamples (int totalSamples)
Calls on occassions where the total samples are known. Either prior to a disk load or following a stream completion.
virtual void UpdateState ()
Calls to determine if completion method should be called.
virtual void Unload ()
Called when clip stream should be completely removed from ram.
Protected Member Functions
AudioClipStream (int newChannels, int newSampleRate, float newStreamReadyLength)
The constructor that takes in a total channel & sample rate.
virtual void HandleStreamReady ()
Perform on stream updated invocation.
virtual void HandleStreamUpdated ()
Perform on stream update following ready.
virtual void HandleStreamComplete ()
Perform on stream complete invocation.
Properties
bool IsReady [get, private set]
Whether or not the stream is ready for playback.
bool IsComplete [get, private set]
Whether or not the stream has been completed.
int Channels [get, private set]
The current number of channels in this audio data stream.
int SampleRate [get, private set]
A getter for the current sample rate of how many samples per second should be played.
int AddedSamples [get, protected set]
The total number of samples currently added to this stream.
int TotalSamples [get, protected set]
The total number of samples expected for this stream.
float Length [get]
The length of the stream in seconds. Typically TotalSamples * Channels * SampleRate.
float StreamReadyLength [get, private set]
A getter for the minimum length in seconds required before the OnStreamReady method is called.
AudioClipStreamDelegate OnStreamReady [get, set]
The callback delegate for stream completion once SetContentLength is called & all samples have been added via the AddSamples(float[] samples) method.
AudioClipStreamDelegate OnStreamUpdated [get, set]
The callback delegate for stream update if any additional data such as the AudioClip is expected to update mid stream. This can be set externally but should only be called within the clip stream itself.
AudioClipStreamDelegate OnStreamComplete [get, set]
The callback delegate for stream completion once SetContentLength is called & all samples have been added via the AddSamples(float[] samples) method.
Properties inherited from Meta.Voice.Audio.IAudioClipStream
Detailed Description
A simple abstract class that can be used to simplify the code required for a custom IAudioClipStream.
Definition at line 17 of file AudioClipStream.cs.
Constructor & Destructor Documentation
AudioClipStream()
Meta.Voice.Audio.AudioClipStream.AudioClipStream (int newChannels, int newSampleRate, float newStreamReadyLength) protected
The constructor that takes in a total channel & sample rate.
Parameters
newChannels The channels to be used for streaming
newSampleRate The new sample rate
newStreamReadyLength The minimum length in seconds required before the OnStreamReady method is called
Definition at line 82 of file AudioClipStream.cs.
        {
            // Set parameters
            Channels = newChannels;
            SampleRate = newSampleRate;
            StreamReadyLength = newStreamReadyLength;
            // Clear counts & bools
            AddedSamples = 0;
            TotalSamples = 0;
            IsReady = false;
            IsComplete = false;
        }
References Meta.Voice.Audio.AudioClipStream.AddedSamples, Meta.Voice.Audio.AudioClipStream.Channels, Meta.Voice.Audio.AudioClipStream.IsComplete, Meta.Voice.Audio.AudioClipStream.IsReady, Meta.Voice.Audio.AudioClipStream.SampleRate, Meta.Voice.Audio.AudioClipStream.StreamReadyLength, and Meta.Voice.Audio.AudioClipStream.TotalSamples.
Member Function Documentation
AddSamples()
virtual void Meta.Voice.Audio.AudioClipStream.AddSamples (float[] samples) virtual
Adds an array of samples to the current stream.
Parameters
samples A list of decoded floats from 0f to 1f
Implements Meta.Voice.Audio.IAudioClipStream.
Reimplemented in Meta.Voice.Audio.UnityAudioClipStream.
Definition at line 100 of file AudioClipStream.cs.
        {
            AddedSamples += samples.Length;
            UpdateState();
        }
References Meta.Voice.Audio.AudioClipStream.AddedSamples, and Meta.Voice.Audio.AudioClipStream.UpdateState().
HandleStreamComplete()
virtual void Meta.Voice.Audio.AudioClipStream.HandleStreamComplete () protected virtual
Perform on stream complete invocation.
Definition at line 163 of file AudioClipStream.cs.
        {
            if (IsComplete)
            {
                return;
            }
            IsComplete = true;
            OnStreamComplete?.Invoke(this);
        }
References Meta.Voice.Audio.AudioClipStream.IsComplete, and Meta.Voice.Audio.AudioClipStream.OnStreamComplete.
HandleStreamReady()
virtual void Meta.Voice.Audio.AudioClipStream.HandleStreamReady () protected virtual
Perform on stream updated invocation.
Definition at line 138 of file AudioClipStream.cs.
        {
            if (IsReady)
            {
                return;
            }
            IsReady = true;
            OnStreamReady?.Invoke(this);
        }
References Meta.Voice.Audio.AudioClipStream.IsReady, and Meta.Voice.Audio.AudioClipStream.OnStreamReady.
HandleStreamUpdated()
virtual void Meta.Voice.Audio.AudioClipStream.HandleStreamUpdated () protected virtual
Perform on stream update following ready.
Definition at line 151 of file AudioClipStream.cs.
        {
            if (!IsReady)
            {
                return;
            }
            OnStreamUpdated?.Invoke(this);
        }
References Meta.Voice.Audio.AudioClipStream.IsReady, and Meta.Voice.Audio.AudioClipStream.OnStreamUpdated.
SetTotalSamples()
virtual void Meta.Voice.Audio.AudioClipStream.SetTotalSamples (int totalSamples) virtual
Calls on occassions where the total samples are known. Either prior to a disk load or following a stream completion.
Parameters
totalSamples The total samples is the final number of samples to be received
Implements Meta.Voice.Audio.IAudioClipStream.
Reimplemented in Meta.Voice.Audio.UnityAudioClipStream.
Definition at line 111 of file AudioClipStream.cs.
        {
            TotalSamples = totalSamples;
            UpdateState();
        }
References Meta.Voice.Audio.AudioClipStream.TotalSamples, and Meta.Voice.Audio.AudioClipStream.UpdateState().
Unload()
virtual void Meta.Voice.Audio.AudioClipStream.Unload () virtual
Called when clip stream should be completely removed from ram.
Implements Meta.Voice.Audio.IAudioClipStream.
Reimplemented in Meta.Voice.Audio.UnityAudioClipStream.
Definition at line 176 of file AudioClipStream.cs.
        {
            OnStreamReady = null;
            OnStreamUpdated = null;
            OnStreamComplete = null;
        }
References Meta.Voice.Audio.AudioClipStream.OnStreamComplete, Meta.Voice.Audio.AudioClipStream.OnStreamReady, and Meta.Voice.Audio.AudioClipStream.OnStreamUpdated.
UpdateState()
virtual void Meta.Voice.Audio.AudioClipStream.UpdateState () virtual
Calls to determine if completion method should be called.
Implements Meta.Voice.Audio.IAudioClipStream.
Definition at line 120 of file AudioClipStream.cs.
        {
            // Stream ready
            if (!IsReady && (StreamReadyLength <= 0f ||
                             (float) AddedSamples * Channels * SampleRate >= StreamReadyLength))
            {
                HandleStreamReady();
            }
            // Stream complete (Don't check if newly ready)
            else if (!IsComplete && TotalSamples > 0 && AddedSamples == TotalSamples)
            {
                HandleStreamComplete();
            }
        }
References Meta.Voice.Audio.AudioClipStream.AddedSamples, Meta.Voice.Audio.AudioClipStream.Channels, Meta.Voice.Audio.AudioClipStream.HandleStreamComplete(), Meta.Voice.Audio.AudioClipStream.HandleStreamReady(), Meta.Voice.Audio.AudioClipStream.IsComplete, Meta.Voice.Audio.AudioClipStream.IsReady, Meta.Voice.Audio.AudioClipStream.SampleRate, Meta.Voice.Audio.AudioClipStream.StreamReadyLength, and Meta.Voice.Audio.AudioClipStream.TotalSamples.
Property Documentation
AddedSamples
int Meta.Voice.Audio.AudioClipStream.AddedSamples get protected set
The total number of samples currently added to this stream.
Implements Meta.Voice.Audio.IAudioClipStream.
Definition at line 41 of file AudioClipStream.cs.
{ get; protected set; }
Channels
int Meta.Voice.Audio.AudioClipStream.Channels get private set
The current number of channels in this audio data stream.
Implements Meta.Voice.Audio.IAudioClipStream.
Definition at line 32 of file AudioClipStream.cs.
{ get; private set; }
IsComplete
bool Meta.Voice.Audio.AudioClipStream.IsComplete get private set
Whether or not the stream has been completed.
Implements Meta.Voice.Audio.IAudioClipStream.
Definition at line 27 of file AudioClipStream.cs.
{ get; private set; }
IsReady
bool Meta.Voice.Audio.AudioClipStream.IsReady get private set
Whether or not the stream is ready for playback.
Implements Meta.Voice.Audio.IAudioClipStream.
Definition at line 22 of file AudioClipStream.cs.
{ get; private set; }
Length
float Meta.Voice.Audio.AudioClipStream.Length get
The length of the stream in seconds. Typically TotalSamples * Channels * SampleRate.
Implements Meta.Voice.Audio.IAudioClipStream.
Definition at line 50 of file AudioClipStream.cs.
OnStreamComplete
AudioClipStreamDelegate Meta.Voice.Audio.AudioClipStream.OnStreamComplete get set
The callback delegate for stream completion once SetContentLength is called & all samples have been added via the AddSamples(float[] samples) method.
Implements Meta.Voice.Audio.IAudioClipStream.
Definition at line 74 of file AudioClipStream.cs.
{ get; set; }
OnStreamReady
AudioClipStreamDelegate Meta.Voice.Audio.AudioClipStream.OnStreamReady get set
The callback delegate for stream completion once SetContentLength is called & all samples have been added via the AddSamples(float[] samples) method.
Implements Meta.Voice.Audio.IAudioClipStream.
Definition at line 61 of file AudioClipStream.cs.
{ get; set; }
OnStreamUpdated
AudioClipStreamDelegate Meta.Voice.Audio.AudioClipStream.OnStreamUpdated get set
The callback delegate for stream update if any additional data such as the AudioClip is expected to update mid stream. This can be set externally but should only be called within the clip stream itself.
Implements Meta.Voice.Audio.IAudioClipStream.
Definition at line 68 of file AudioClipStream.cs.
{ get; set; }
SampleRate
int Meta.Voice.Audio.AudioClipStream.SampleRate get private set
A getter for the current sample rate of how many samples per second should be played.
Implements Meta.Voice.Audio.IAudioClipStream.
Definition at line 36 of file AudioClipStream.cs.
{ get; private set; }
StreamReadyLength
float Meta.Voice.Audio.AudioClipStream.StreamReadyLength get private set
A getter for the minimum length in seconds required before the OnStreamReady method is called.
Implements Meta.Voice.Audio.IAudioClipStream.
Definition at line 55 of file AudioClipStream.cs.
{ get; private set; }
TotalSamples
int Meta.Voice.Audio.AudioClipStream.TotalSamples get protected set
The total number of samples expected for this stream.
Implements Meta.Voice.Audio.IAudioClipStream.
Definition at line 45 of file AudioClipStream.cs.
{ get; protected set; }
The documentation for this class was generated from the following file:
Assets/Oculus/Voice/Lib/Wit.ai/Lib/Wit/Runtime/Audio/AudioClipStream.cs