VR_Test: Oculus.Interaction.PoseUtils Class Reference
Oculus.Interaction.PoseUtils Class Reference
Tools for working with Unity Poses.
Static Public Member Functions
static void SetPose (this Transform transform, in Pose pose, Space space=Space.World)
Assigns a Pose to a given transform.
static Pose GetPose (this Transform transform, Space space=Space.World)
Extract the position/rotation of a given transform.
static void Multiply (in Pose a, in Pose b, ref Pose result)
Compose two poses, applying the first to the second one.
static Pose Multiply (in Pose a, in Pose b)
static void Premultiply (this ref Pose a, in Pose b)
Compose two poses, applying the provided one on top of the caller.
static void Postmultiply (this ref Pose a, in Pose b)
Compose two poses, applying the caller on top of the provided pose.
static void Lerp (this ref Pose from, in Pose to, float t)
Moves the calling pose towards a target one using interpolation.
static void Lerp (in Pose from, in Pose to, float t, ref Pose result)
Interpolation between two poses.
static void Inverse (in Pose a, ref Pose result)
static void Invert (this ref Pose a)
static void CopyFrom (this ref Pose to, in Pose from)
static Pose Delta (this Transform from, Transform to)
Get the position/rotation difference between two transforms. Unaffected by scale.
static Pose Delta (this Transform from, in Pose to)
Get the position/rotation difference between a transform and a pose. Unaffected by scale.
static void Delta (this Transform from, in Pose to, ref Pose result)
Get the position/rotation difference between a transform and a pose. Unaffected by scale.
static Pose Delta (in Pose from, in Pose to)
Get the position/rotation difference between two poses. Unaffected by scale.
static Pose DeltaScaled (Transform from, Transform to)
Get the position/rotation difference between two transforms. Affected by the scale of from.
static Pose DeltaScaled (Transform from, Pose to)
Get the position/rotation difference between a transform and a pose. Affected by the scale of from.
static Pose GlobalPose (this Transform reference, in Pose offset)
Get the world position/rotation of a relative position. Unaffected by scale.
static Pose GlobalPoseScaled (Transform relativeTo, Pose offset)
Get the world position/rotation of a relative position. Affected by the scale of the transform.
static Pose MirrorPoseRotation (this in Pose pose, Vector3 normal, Vector3 tangent)
Rotate a pose around an axis.
Static Private Member Functions
static Pose Delta (Vector3 fromPosition, Quaternion fromRotation, Vector3 toPosition, Quaternion toRotation)
Get the position/rotation difference between two poses, indicated with separated positions and rotations.
static void Delta (Vector3 fromPosition, Quaternion fromRotation, Vector3 toPosition, Quaternion toRotation, ref Pose result)
Detailed Description
Tools for working with Unity Poses.
Definition at line 28 of file PoseUtils.cs.
Member Function Documentation
CopyFrom()
static void Oculus.Interaction.PoseUtils.CopyFrom (this ref Pose to, in Pose from) static
Definition at line 141 of file PoseUtils.cs.
        {
            to.position = from.position;
            to.rotation = from.rotation;
        }
Delta() [1/6]
static Pose Oculus.Interaction.PoseUtils.Delta (in Pose from, in Pose to) static
Get the position/rotation difference between two poses. Unaffected by scale.
Parameters
from The base pose.
to The target pose.
Returns
A Pose indicating the delta.
Definition at line 190 of file PoseUtils.cs.
        {
            return Delta(from.position, from.rotation, to.position, to.rotation);
        }
References Oculus.Interaction.PoseUtils.Delta().
Delta() [2/6]
static Pose Oculus.Interaction.PoseUtils.Delta (this Transform from, in Pose to) static
Get the position/rotation difference between a transform and a pose. Unaffected by scale.
Parameters
from The base transform.
to The target pose.
Returns
A Pose indicating the delta.
Definition at line 166 of file PoseUtils.cs.
        {
            return Delta(from.position, from.rotation, to.position, to.rotation);
        }
References Oculus.Interaction.PoseUtils.Delta().
Delta() [3/6]
static void Oculus.Interaction.PoseUtils.Delta (this Transform from, in Pose to, ref Pose result) static
Get the position/rotation difference between a transform and a pose. Unaffected by scale.
Parameters
from The base transform.
to The target pose.
result Output: The pose with the delta
Definition at line 178 of file PoseUtils.cs.
        {
            Delta(from.position, from.rotation, to.position, to.rotation, ref result);
        }
References Oculus.Interaction.PoseUtils.Delta().
Delta() [4/6]
static Pose Oculus.Interaction.PoseUtils.Delta (this Transform from, Transform to) static
Get the position/rotation difference between two transforms. Unaffected by scale.
Parameters
from The base transform.
to The target transform.
Returns
A Pose indicating the position/rotation change
Definition at line 154 of file PoseUtils.cs.
        {
            return Delta(from.position, from.rotation, to.position, to.rotation);
        }
References Oculus.Interaction.PoseUtils.Delta().
Delta() [5/6]
static Pose Oculus.Interaction.PoseUtils.Delta (Vector3 fromPosition, Quaternion fromRotation, Vector3 toPosition, Quaternion toRotation) static private
Get the position/rotation difference between two poses, indicated with separated positions and rotations.
Parameters
fromPosition The base position.
fromRotation The base rotation.
toPosition The target position.
toRotation The target rotation.
Returns
A Pose indicating the delta.
Definition at line 203 of file PoseUtils.cs.
        {
            Pose result = new Pose();
            Delta(fromPosition, fromRotation, toPosition, toRotation, ref result);
            return result;
        }
References Oculus.Interaction.PoseUtils.Delta().
Delta() [6/6]
static void Oculus.Interaction.PoseUtils.Delta (Vector3 fromPosition, Quaternion fromRotation, Vector3 toPosition, Quaternion toRotation, ref Pose result) static private
Definition at line 210 of file PoseUtils.cs.
        {
            Quaternion inverseFromRot = Quaternion.Inverse(fromRotation);
            result.position = inverseFromRot * (toPosition - fromPosition);
            result.rotation = inverseFromRot * toRotation;
        }
DeltaScaled() [1/2]
static Pose Oculus.Interaction.PoseUtils.DeltaScaled (Transform from, Pose to) static
Get the position/rotation difference between a transform and a pose. Affected by the scale of from.
Parameters
from The base transform.
to The target pose.
Returns
The pose with the delta
Definition at line 239 of file PoseUtils.cs.
        {
            Pose delta;
            delta.position = from.InverseTransformPoint(to.position);
            delta.rotation = Quaternion.Inverse(from.rotation) * to.rotation;
            return delta;
        }
DeltaScaled() [2/2]
static Pose Oculus.Interaction.PoseUtils.DeltaScaled (Transform from, Transform to) static
Get the position/rotation difference between two transforms. Affected by the scale of from.
Parameters
from The base transform.
to The target transform.
Returns
Output: The pose with the delta
Definition at line 224 of file PoseUtils.cs.
        {
            Pose delta;
            delta.position = from.InverseTransformPoint(to.position);
            delta.rotation = Quaternion.Inverse(from.rotation) * to.rotation;
            return delta;
        }
GetPose()
static Pose Oculus.Interaction.PoseUtils.GetPose (this Transform transform, Space space = Space::World) static
Extract the position/rotation of a given transform.
Parameters
transform The transform from which to extract the pose.
space If the desired position/rotation is the world or local one.
Returns
A Pose containing the position/rotation of the transform.
Definition at line 55 of file PoseUtils.cs.
        {
            if (space == Space.World)
            {
                return new Pose(transform.position, transform.rotation);
            }
            else
            {
                return new Pose(transform.localPosition, transform.localRotation);
            }
        }
GlobalPose()
static Pose Oculus.Interaction.PoseUtils.GlobalPose (this Transform reference, in Pose offset) static
Get the world position/rotation of a relative position. Unaffected by scale.
Parameters
reference The transform in which the offset is local.
offset The offset from the reference.
Returns
A Pose in world units.
Definition at line 254 of file PoseUtils.cs.
        {
            return new Pose(
                reference.position + reference.rotation * offset.position,
                reference.rotation * offset.rotation);
        }
GlobalPoseScaled()
static Pose Oculus.Interaction.PoseUtils.GlobalPoseScaled (Transform relativeTo, Pose offset) static
Get the world position/rotation of a relative position. Affected by the scale of the transform.
Parameters
relativeTo The transform in which the offset is local.
offset The offset from the reference.
Returns
A Pose in world units.
Definition at line 268 of file PoseUtils.cs.
        {
            Pose pose;
            pose.position = relativeTo.TransformPoint(offset.position);
            pose.rotation = relativeTo.rotation * offset.rotation;
            return pose;
        }
Inverse()
static void Oculus.Interaction.PoseUtils.Inverse (in Pose a, ref Pose result) static
Definition at line 130 of file PoseUtils.cs.
        {
            result.rotation = Quaternion.Inverse(a.rotation);
            result.position = result.rotation * -a.position;
        }
Invert()
static void Oculus.Interaction.PoseUtils.Invert (this ref Pose a) static
Definition at line 136 of file PoseUtils.cs.
        {
            Inverse(a, ref a);
        }
Lerp() [1/2]
static void Oculus.Interaction.PoseUtils.Lerp (in Pose from, in Pose to, float t, ref Pose result) static
Interpolation between two poses.
Parameters
from From pose.
to To pose.
t Interpolation factor, normalized but will not be clamped.
result A Pose between a and b
Definition at line 124 of file PoseUtils.cs.
        {
            result.position = Vector3.LerpUnclamped(from.position, to.position, t);
            result.rotation = Quaternion.SlerpUnclamped(from.rotation, to.rotation, t);
        }
Lerp() [2/2]
static void Oculus.Interaction.PoseUtils.Lerp (this ref Pose from, in Pose to, float t) static
Moves the calling pose towards a target one using interpolation.
Parameters
from Original pose to interpolate from
to Target pose for the interpolation.
t Interpolation factor, normalized but will not be clamped.
Definition at line 112 of file PoseUtils.cs.
        {
            Lerp(from, to, t, ref from);
        }
References Oculus.Interaction.PoseUtils.Lerp().
MirrorPoseRotation()
static Pose Oculus.Interaction.PoseUtils.MirrorPoseRotation (this in Pose pose, Vector3 normal, Vector3 tangent) static
Rotate a pose around an axis.
Parameters
pose The pose to mirror.
normal The direction of the mirror.
tangent The tangent of the mirror.
Returns
A mirrored pose.
Definition at line 283 of file PoseUtils.cs.
        {
            Pose mirrorPose = pose;
            Vector3 forward = pose.rotation * -Vector3.forward;
            Vector3 projectedForward = Vector3.ProjectOnPlane(forward, normal);
            float angleForward = Vector3.SignedAngle(projectedForward, tangent, normal);
            Vector3 mirrorForward = Quaternion.AngleAxis(2 * angleForward, normal) * forward;
            Vector3 up = pose.rotation * -Vector3.up;
            Vector3 projectedUp = Vector3.ProjectOnPlane(up, normal);
            float angleUp = Vector3.SignedAngle(projectedUp, tangent, normal);
            Vector3 mirrorUp = Quaternion.AngleAxis(2 * angleUp, normal) * up;
            mirrorPose.rotation = Quaternion.LookRotation(mirrorForward, mirrorUp);
            return mirrorPose;
        }
Multiply() [1/2]
static Pose Oculus.Interaction.PoseUtils.Multiply (in Pose a, in Pose b) static
Definition at line 79 of file PoseUtils.cs.
        {
            Pose result = new Pose();
            Multiply(a, b, ref result);
            return result;
        }
Multiply() [2/2]
static void Oculus.Interaction.PoseUtils.Multiply (in Pose a, in Pose b, ref Pose result) static
Compose two poses, applying the first to the second one.
Parameters
a First pose to compose.
b Pose to compose over the first one.
result A Pose with the two operands applied.
Definition at line 73 of file PoseUtils.cs.
        {
            result.position = a.position + a.rotation * b.position;
            result.rotation = a.rotation * b.rotation;
        }
Postmultiply()
static void Oculus.Interaction.PoseUtils.Postmultiply (this ref Pose a, in Pose b) static
Compose two poses, applying the caller on top of the provided pose.
Parameters
a Pose to compose upon.
b Pose to compose over the first one.
Definition at line 101 of file PoseUtils.cs.
        {
            Multiply(b, a, ref a);
        }
References Oculus.Interaction.PoseUtils.Multiply().
Premultiply()
static void Oculus.Interaction.PoseUtils.Premultiply (this ref Pose a, in Pose b) static
Compose two poses, applying the provided one on top of the caller.
Parameters
a Pose to compose upon.
b Pose to compose over the first one.
Definition at line 91 of file PoseUtils.cs.
        {
            Multiply(a, b, ref a);
        }
References Oculus.Interaction.PoseUtils.Multiply().
SetPose()
static void Oculus.Interaction.PoseUtils.SetPose (this Transform transform, in Pose pose, Space space = Space::World) static
Assigns a Pose to a given transform.
Parameters
transform The transform to which apply the pose.
pose The desired pose.
space If the pose should be applied to the local position/rotation or world position/rotation.
Definition at line 36 of file PoseUtils.cs.
        {
            if (space == Space.World)
            {
                transform.SetPositionAndRotation(pose.position, pose.rotation);
            }
            else
            {
                transform.localRotation = pose.rotation;
                transform.localPosition = pose.position;
            }
        }
The documentation for this class was generated from the following file:
Assets/Oculus/Interaction/Runtime/Scripts/Utils/PoseUtils.cs