VR_Test: Meta.WitAi.Requests.VoiceServiceRequestOptions Class Reference
Meta.WitAi.Requests.VoiceServiceRequestOptions Class Reference
Classes
class QueryParam
Public Member Functions
VoiceServiceRequestOptions (params QueryParam[] newParams)
Setup with a randomly generated guid.
VoiceServiceRequestOptions (string newRequestId, params QueryParam[] newParams)
Setup with a specific guid.
Static Public Member Functions
static Dictionary< string, string > ConvertQueryParams (QueryParam[] newParams)
Generates a dictionary of key/value strings from a query param array.
Protected Member Functions
virtual string GetUniqueRequestId ()
Generates a random guid.
Properties
string RequestId [get, private set]
Unique request id used for request tracking internally & externally.
Dictionary< string, string > QueryParams [get, private set]
Additional request query parameters to be sent with the request.
string Text [get, set]
The text to be submitted for a text request.
float AudioThreshold [get, set]
The threshold to be used for an audio request.
Properties inherited from Meta.Voice.IVoiceRequestOptions
Properties inherited from Meta.Voice.ITranscriptionRequestOptions
Properties inherited from Meta.Voice.INLPTextRequestOptions
Detailed Description
Definition at line 15 of file VoiceServiceRequestOptions.cs.
Constructor & Destructor Documentation
VoiceServiceRequestOptions() [1/2]
Meta.WitAi.Requests.VoiceServiceRequestOptions.VoiceServiceRequestOptions (params QueryParam[] newParams)
Setup with a randomly generated guid.
Definition at line 43 of file VoiceServiceRequestOptions.cs.
        {
            RequestId = GetUniqueRequestId();
            QueryParams = ConvertQueryParams(newParams);
        }
References Meta.WitAi.Requests.VoiceServiceRequestOptions.ConvertQueryParams(), Meta.WitAi.Requests.VoiceServiceRequestOptions.GetUniqueRequestId(), Meta.WitAi.Requests.VoiceServiceRequestOptions.QueryParams, and Meta.WitAi.Requests.VoiceServiceRequestOptions.RequestId.
VoiceServiceRequestOptions() [2/2]
Meta.WitAi.Requests.VoiceServiceRequestOptions.VoiceServiceRequestOptions (string newRequestId, params QueryParam[] newParams)
Setup with a specific guid.
Definition at line 51 of file VoiceServiceRequestOptions.cs.
        {
            RequestId = string.IsNullOrEmpty(newRequestId) ? GetUniqueRequestId() : newRequestId;
            QueryParams = ConvertQueryParams(newParams);
        }
References Meta.WitAi.Requests.VoiceServiceRequestOptions.ConvertQueryParams(), Meta.WitAi.Requests.VoiceServiceRequestOptions.GetUniqueRequestId(), Meta.WitAi.Requests.VoiceServiceRequestOptions.QueryParams, and Meta.WitAi.Requests.VoiceServiceRequestOptions.RequestId.
Member Function Documentation
ConvertQueryParams()
static Dictionary< string, string > Meta.WitAi.Requests.VoiceServiceRequestOptions.ConvertQueryParams (QueryParam[] newParams) static
Generates a dictionary of key/value strings from a query param array.
Definition at line 63 of file VoiceServiceRequestOptions.cs.
        {
            Dictionary<string, string> results = new Dictionary<string, string>();
            foreach (var param in newParams)
            {
                if (!string.IsNullOrEmpty(param.key))
                {
                    results[param.key] = results[param.value];
                }
            }
            return results;
        }
Property Documentation
AudioThreshold
float Meta.WitAi.Requests.VoiceServiceRequestOptions.AudioThreshold get set
The threshold to be used for an audio request.
Implements Meta.Voice.ITranscriptionRequestOptions.
Definition at line 38 of file VoiceServiceRequestOptions.cs.
{ get; set; }
QueryParams
Dictionary<string, string> Meta.WitAi.Requests.VoiceServiceRequestOptions.QueryParams get private set
Additional request query parameters to be sent with the request.
Definition at line 24 of file VoiceServiceRequestOptions.cs.
{ get; private set; }
RequestId
string Meta.WitAi.Requests.VoiceServiceRequestOptions.RequestId get private set
Unique request id used for request tracking internally & externally.
Implements Meta.Voice.IVoiceRequestOptions.
Definition at line 20 of file VoiceServiceRequestOptions.cs.
{ get; private set; }
Text
string Meta.WitAi.Requests.VoiceServiceRequestOptions.Text get set
The text to be submitted for a text request.
Implements Meta.Voice.INLPTextRequestOptions.
Definition at line 34 of file VoiceServiceRequestOptions.cs.
{ get; set; }
The documentation for this class was generated from the following file:
Assets/Oculus/Voice/Lib/Wit.ai/Scripts/Runtime/Requests/VoiceServiceRequestOptions.cs