VR_Test: OVRLipSyncMicInput Class Reference
OVRLipSyncMicInput Class Reference
Public Types
enum micActivation { HoldToSpeak , PushToSpeak , ConstantSpeak }
Public Member Functions
void MicDeviceGUI (float left, float top, float width, float height, float buttonSpaceTop, float buttonSpaceLeft)
Mics the device GU.
void GetMicCaps ()
Gets the mic caps.
void StartMicrophone ()
Starts the microphone.
void StopMicrophone ()
Stops the microphone.
Public Attributes
AudioSource audioSource = null
bool enableMicSelectionGUI = false
KeyCode micSelectionGUIKey = KeyCode.M
micActivation micControl = micActivation.ConstantSpeak
KeyCode micActivationKey = KeyCode.Space
string selectedDevice
Properties
float MicFrequency [get, set]
Private Member Functions
void Awake ()
Awake this instance.
void Start ()
Start this instance.
void InitializeMicrophone ()
Initializes the microphone.
void Update ()
Update this instance.
void OnApplicationFocus (bool focus)
Raises the application focus event.
void OnApplicationPause (bool pauseStatus)
Raises the application pause event.
void OnDisable ()
void OnGUI ()
Raises the GU event.
float GetAveragedVolume ()
Gets the averaged volume.
Private Attributes
float micInputVolume = 100
int micFrequency = 48000
bool micSelected = false
int minFreq
int maxFreq
bool focused = true
bool initialized = false
Detailed Description
Definition at line 32 of file OVRLipSyncMicInput.cs.
Member Enumeration Documentation
micActivation
enum OVRLipSyncMicInput.micActivation
Definition at line 34 of file OVRLipSyncMicInput.cs.
    {
        HoldToSpeak,
        PushToSpeak,
        ConstantSpeak
    }
Member Function Documentation
Awake()
void OVRLipSyncMicInput.Awake () private
Awake this instance.
Definition at line 89 of file OVRLipSyncMicInput.cs.
    {
        // First thing to do, cache the unity audio source (can be managed by the
        // user if audio source can change)
        if (!audioSource) audioSource = GetComponent<AudioSource>();
        if (!audioSource) return; // this should never happen
    }
GetAveragedVolume()
float OVRLipSyncMicInput.GetAveragedVolume () private
Gets the averaged volume.
Returns
The averaged volume.
Definition at line 366 of file OVRLipSyncMicInput.cs.
    {
        // We will use the SR to get average volume
        // return OVRSpeechRec.GetAverageVolume();
        return 0.0f;
    }
GetMicCaps()
void OVRLipSyncMicInput.GetMicCaps ()
Gets the mic caps.
Definition at line 292 of file OVRLipSyncMicInput.cs.
    {
        if (micSelected == false) return;
        //Gets the frequency of the device
        Microphone.GetDeviceCaps(selectedDevice, out minFreq, out maxFreq);
        if (minFreq == 0 && maxFreq == 0)
        {
            Debug.LogWarning("GetMicCaps warning:: min and max frequencies are 0");
            minFreq = 44100;
            maxFreq = 44100;
        }
        if (micFrequency > maxFreq)
            micFrequency = maxFreq;
    }
InitializeMicrophone()
void OVRLipSyncMicInput.InitializeMicrophone () private
Initializes the microphone.
Definition at line 111 of file OVRLipSyncMicInput.cs.
    {
        if (initialized)
        {
            return;
        }
        if (Microphone.devices.Length == 0)
        {
            return;
        }
        selectedDevice = Microphone.devices[0].ToString();
        micSelected = true;
        GetMicCaps();
        initialized = true;
    }
References GetMicCaps().
MicDeviceGUI()
void OVRLipSyncMicInput.MicDeviceGUI (float left, float top, float width, float height, float buttonSpaceTop, float buttonSpaceLeft)
Mics the device GU.
Parameters
left Left.
top Top.
width Width.
height Height.
buttonSpaceTop Button space top.
buttonSpaceLeft Button space left.
Definition at line 262 of file OVRLipSyncMicInput.cs.
    {
        //If there is more than one device, choose one.
        if (Microphone.devices.Length >= 1 && enableMicSelectionGUI == true && micSelected == false)
        {
            for (int i = 0; i < Microphone.devices.Length; ++i)
            {
                if (GUI.Button(new Rect(left + ((width + buttonSpaceLeft) * i),
                                        top + ((height + buttonSpaceTop) * i), width, height),
                               Microphone.devices[i].ToString()))
                {
                    StopMicrophone();
                    selectedDevice = Microphone.devices[i].ToString();
                    micSelected = true;
                    GetMicCaps();
                    StartMicrophone();
                }
            }
        }
    }
References GetMicCaps(), StartMicrophone(), and StopMicrophone().
OnApplicationFocus()
void OVRLipSyncMicInput.OnApplicationFocus (bool focus) private
Raises the application focus event.
Parameters
focus If set to true: focused.
Definition at line 216 of file OVRLipSyncMicInput.cs.
    {
        focused = focus;
        if (!focused)
            StopMicrophone();
    }
References StopMicrophone().
OnApplicationPause()
void OVRLipSyncMicInput.OnApplicationPause (bool pauseStatus) private
Raises the application pause event.
Parameters
pauseStatus If set to true: paused.
Definition at line 228 of file OVRLipSyncMicInput.cs.
    {
        focused = !pauseStatus;
        if (!focused)
            StopMicrophone();
    }
References StopMicrophone().
OnDisable()
void OVRLipSyncMicInput.OnDisable () private
Definition at line 236 of file OVRLipSyncMicInput.cs.
    {
        StopMicrophone();
    }
OnGUI()
void OVRLipSyncMicInput.OnGUI () private
Raises the GU event.
Definition at line 244 of file OVRLipSyncMicInput.cs.
    {
        MicDeviceGUI((Screen.width / 2) - 150, (Screen.height / 2) - 75, 300, 50, 10, -300);
    }
References MicDeviceGUI().
Start()
void OVRLipSyncMicInput.Start () private
Start this instance.
Definition at line 100 of file OVRLipSyncMicInput.cs.
    {
        audioSource.loop = true;     // Set the AudioClip to loop
        audioSource.mute = false;
        InitializeMicrophone();
    }
References InitializeMicrophone().
StartMicrophone()
void OVRLipSyncMicInput.StartMicrophone ()
Starts the microphone.
Definition at line 313 of file OVRLipSyncMicInput.cs.
    {
        if (micSelected == false) return;
        //Starts recording
        audioSource.clip = Microphone.Start(selectedDevice, true, 1, micFrequency);
        Stopwatch timer = Stopwatch.StartNew();
        // Wait until the recording has started
        while (!(Microphone.GetPosition(selectedDevice) > 0) && timer.Elapsed.TotalMilliseconds < 1000) {
            Thread.Sleep(50);
        }
        if (Microphone.GetPosition(selectedDevice) <= 0)
        {
            throw new Exception("Timeout initializing microphone " + selectedDevice);
        }
        // Play the audio source
        audioSource.Play();
    }
StopMicrophone()
void OVRLipSyncMicInput.StopMicrophone ()
Stops the microphone.
Definition at line 338 of file OVRLipSyncMicInput.cs.
    {
        if (micSelected == false) return;
        // Overriden with a clip to play? Don't stop the audio source
        if ((audioSource != null) &&
            (audioSource.clip != null) &&
            (audioSource.clip.name == "Microphone"))
        {
            audioSource.Stop();
        }
        // Reset to stop mouth movement
        OVRLipSyncContext context = GetComponent<OVRLipSyncContext>();
        context.ResetContext();
        Microphone.End(selectedDevice);
    }
References OVRLipSyncContextBase.ResetContext().
Update()
void OVRLipSyncMicInput.Update () private
Update this instance.
Definition at line 131 of file OVRLipSyncMicInput.cs.
    {
        if (!focused)
        {
            if (Microphone.IsRecording(selectedDevice))
            {
                StopMicrophone();
            }
            return;
        }
        if (!Application.isPlaying)
        {
            StopMicrophone();
            return;
        }
        // Lazy Microphone initialization (needed on Android)
        if (!initialized)
        {
            InitializeMicrophone();
        }
        audioSource.volume = (micInputVolume / 100);
        //Hold To Speak
        if (micControl == micActivation.HoldToSpeak)
        {
            if (Input.GetKey(micActivationKey))
            {
                if (!Microphone.IsRecording(selectedDevice))
                {
                    StartMicrophone();
                }
            }
            else
            {
                if (Microphone.IsRecording(selectedDevice))
                {
                    StopMicrophone();
                }
            }
        }
        //Push To Talk
        if (micControl == micActivation.PushToSpeak)
        {
            if (Input.GetKeyDown(micActivationKey))
            {
                if (Microphone.IsRecording(selectedDevice))
                {
                    StopMicrophone();
                }
                else if (!Microphone.IsRecording(selectedDevice))
                {
                    StartMicrophone();
                }
            }
        }
        //Constant Speak
        if (micControl == micActivation.ConstantSpeak)
        {
            if (!Microphone.IsRecording(selectedDevice))
            {
                StartMicrophone();
            }
        }
        //Mic Selected = False
        if (enableMicSelectionGUI)
        {
            if (Input.GetKeyDown(micSelectionGUIKey))
            {
                micSelected = false;
            }
        }
    }
References InitializeMicrophone(), StartMicrophone(), and StopMicrophone().
Member Data Documentation
audioSource
AudioSource OVRLipSyncMicInput.audioSource = null
Definition at line 44 of file OVRLipSyncMicInput.cs.
enableMicSelectionGUI
bool OVRLipSyncMicInput.enableMicSelectionGUI = false
Definition at line 48 of file OVRLipSyncMicInput.cs.
focused
bool OVRLipSyncMicInput.focused = true private
Definition at line 79 of file OVRLipSyncMicInput.cs.
initialized
bool OVRLipSyncMicInput.initialized = false private
Definition at line 80 of file OVRLipSyncMicInput.cs.
maxFreq
int OVRLipSyncMicInput.maxFreq private
Definition at line 78 of file OVRLipSyncMicInput.cs.
micActivationKey
KeyCode OVRLipSyncMicInput.micActivationKey = KeyCode.Space
Definition at line 71 of file OVRLipSyncMicInput.cs.
micControl
micActivation OVRLipSyncMicInput.micControl = micActivation.ConstantSpeak
Definition at line 68 of file OVRLipSyncMicInput.cs.
micFrequency
int OVRLipSyncMicInput.micFrequency = 48000 private
Definition at line 59 of file OVRLipSyncMicInput.cs.
micInputVolume
float OVRLipSyncMicInput.micInputVolume = 100 private
Definition at line 55 of file OVRLipSyncMicInput.cs.
micSelected
bool OVRLipSyncMicInput.micSelected = false private
Definition at line 77 of file OVRLipSyncMicInput.cs.
micSelectionGUIKey
KeyCode OVRLipSyncMicInput.micSelectionGUIKey = KeyCode.M
Definition at line 50 of file OVRLipSyncMicInput.cs.
minFreq
int OVRLipSyncMicInput.minFreq private
Definition at line 78 of file OVRLipSyncMicInput.cs.
selectedDevice
string OVRLipSyncMicInput.selectedDevice
Definition at line 74 of file OVRLipSyncMicInput.cs.
Property Documentation
MicFrequency
float OVRLipSyncMicInput.MicFrequency get set
Definition at line 60 of file OVRLipSyncMicInput.cs.
    {
        get { return micFrequency; }
        set { micFrequency = (int)Mathf.Clamp((float)value, 0, 96000); }
    }
The documentation for this class was generated from the following file:
Assets/Oculus/LipSync/Scripts/OVRLipSyncMicInput.cs