VR_Test: Meta.WitAi.TTS.Integrations.TTSRuntimeCache Class Reference
Meta.WitAi.TTS.Integrations.TTSRuntimeCache Class Reference
Public Member Functions
TTSClipData[] GetClips ()
Simple getter for all clips.
TTSClipData GetClip (string clipID)
Getter for a clip that also moves clip to the back of the queue.
bool AddClip (TTSClipData clipData)
Add clip to cache and ensure it is most recently referenced.
void RemoveClip (string clipID)
Remove clip from cache immediately.
int GetCacheDiskSize ()
Get RAM size of cache in KBs.
Static Public Member Functions
static long GetClipBytes (AudioClip clip)
static long GetClipBytes (int channels, int samples)
Public Attributes
bool ClipLimit = true
Whether or not to unload clip data after the clip capacity is hit.
int ClipCapacity = 20
The maximum clips allowed in the runtime cache.
bool RamLimit = true
Whether or not to unload clip data after the ram capacity is hit.
int RamCapacity = 32768
The maximum amount of RAM allowed in the runtime cache. In KBs.
Protected Member Functions
virtual void OnDestroy ()
bool IsCacheFull ()
Check if cache is full.
Properties
TTSClipEvent OnClipAdded = new TTSClipEvent() [get, set]
On clip added callback.
TTSClipEvent OnClipRemoved = new TTSClipEvent() [get, set]
On clip removed callback.
Properties inherited from Meta.WitAi.TTS.Interfaces.ITTSRuntimeCacheHandler
Private Attributes
Dictionary< string, TTSClipData > _clips = new Dictionary<string, TTSClipData>()
List< string > _clipOrder = new List<string>()
Detailed Description
Definition at line 20 of file TTSRuntimeCache.cs.
Member Function Documentation
AddClip()
bool Meta.WitAi.TTS.Integrations.TTSRuntimeCache.AddClip (TTSClipData clipData)
Add clip to cache and ensure it is most recently referenced.
Parameters
clipData
Implements Meta.WitAi.TTS.Interfaces.ITTSRuntimeCacheHandler.
Definition at line 100 of file TTSRuntimeCache.cs.
        {
            // Do not add null
            if (clipData == null)
            {
                return false;
            }
            // Remove from order
            bool wasAdded = true;
            int clipIndex = _clipOrder.IndexOf(clipData.clipID);
            if (clipIndex != -1)
            {
                wasAdded = false;
                _clipOrder.RemoveAt(clipIndex);
            }
            // Add clip
            _clips[clipData.clipID] = clipData;
            // Add to end of order
            _clipOrder.Add(clipData.clipID);
            // Evict least recently used clips
            while (IsCacheFull() && _clipOrder.Count > 0)
            {
                // Remove clip
                RemoveClip(_clipOrder[0]);
            }
            // Call add delegate even if removed
            if (wasAdded && _clips.Keys.Count > 0)
            {
                OnClipAdded?.Invoke(clipData);
            }
            // True if successfully added
            return _clips.Keys.Count > 0;
        }
References Meta.WitAi.TTS.Integrations.TTSRuntimeCache.IsCacheFull(), Meta.WitAi.TTS.Integrations.TTSRuntimeCache.OnClipAdded, and Meta.WitAi.TTS.Integrations.TTSRuntimeCache.RemoveClip().
GetCacheDiskSize()
int Meta.WitAi.TTS.Integrations.TTSRuntimeCache.GetCacheDiskSize ()
Get RAM size of cache in KBs.
Returns
Returns size in KBs rounded up
Definition at line 184 of file TTSRuntimeCache.cs.
        {
            long total = 0;
            foreach (var key in _clips.Keys)
            {
                total += GetClipBytes(_clips[key].clipStream.Channels, _clips[key].clipStream.TotalSamples);
            }
            return (int)(total / (long)1024) + 1;
        }
GetClip()
TTSClipData Meta.WitAi.TTS.Integrations.TTSRuntimeCache.GetClip (string clipID)
Getter for a clip that also moves clip to the back of the queue.
Implements Meta.WitAi.TTS.Interfaces.ITTSRuntimeCacheHandler.
Definition at line 79 of file TTSRuntimeCache.cs.
        {
            // Id not found
            if (!_clips.ContainsKey(clipID))
            {
                return null;
            }
            // Sort to end
            int clipIndex = _clipOrder.IndexOf(clipID);
            _clipOrder.RemoveAt(clipIndex);
            _clipOrder.Add(clipID);
            // Return clip
            return _clips[clipID];
        }
GetClipBytes() [1/2]
static long Meta.WitAi.TTS.Integrations.TTSRuntimeCache.GetClipBytes (AudioClip clip) static
Definition at line 194 of file TTSRuntimeCache.cs.
        {
            if (clip != null)
            {
                return GetClipBytes(clip.channels, clip.samples);
            }
            return 0;
        }
GetClipBytes() [2/2]
static long Meta.WitAi.TTS.Integrations.TTSRuntimeCache.GetClipBytes (int channels, int samples) static
Definition at line 203 of file TTSRuntimeCache.cs.
        {
            return channels * samples * 2;
        }
GetClips()
TTSClipData[] Meta.WitAi.TTS.Integrations.TTSRuntimeCache.GetClips ()
Simple getter for all clips.
Implements Meta.WitAi.TTS.Interfaces.ITTSRuntimeCacheHandler.
IsCacheFull()
bool Meta.WitAi.TTS.Integrations.TTSRuntimeCache.IsCacheFull () protected
Check if cache is full.
Definition at line 165 of file TTSRuntimeCache.cs.
        {
            // Capacity full
            if (ClipLimit && _clipOrder.Count > ClipCapacity)
            {
                return true;
            }
            // Ram full
            if (RamLimit && GetCacheDiskSize() > RamCapacity)
            {
                return true;
            }
            // Free
            return false;
        }
References Meta.WitAi.TTS.Integrations.TTSRuntimeCache.ClipCapacity, Meta.WitAi.TTS.Integrations.TTSRuntimeCache.ClipLimit, Meta.WitAi.TTS.Integrations.TTSRuntimeCache.GetCacheDiskSize(), Meta.WitAi.TTS.Integrations.TTSRuntimeCache.RamCapacity, and Meta.WitAi.TTS.Integrations.TTSRuntimeCache.RamLimit.
OnDestroy()
virtual void Meta.WitAi.TTS.Integrations.TTSRuntimeCache.OnDestroy () protected virtual
Definition at line 70 of file TTSRuntimeCache.cs.
        {
            _clips.Clear();
            _clipOrder.Clear();
        }
RemoveClip()
void Meta.WitAi.TTS.Integrations.TTSRuntimeCache.RemoveClip (string clipID)
Remove clip from cache immediately.
Parameters
clipID
Implements Meta.WitAi.TTS.Interfaces.ITTSRuntimeCacheHandler.
Definition at line 142 of file TTSRuntimeCache.cs.
        {
            // Id not found
            if (!_clips.ContainsKey(clipID))
            {
                return;
            }
            // Remove from dictionary
            TTSClipData clipData = _clips[clipID];
            _clips.Remove(clipID);
            // Remove from order list
            int clipIndex = _clipOrder.IndexOf(clipID);
            _clipOrder.RemoveAt(clipIndex);
            // Call remove delegate
            OnClipRemoved?.Invoke(clipData);
        }
References Meta.WitAi.TTS.Integrations.TTSRuntimeCache.OnClipRemoved.
Member Data Documentation
_clipOrder
List<string> Meta.WitAi.TTS.Integrations.TTSRuntimeCache._clipOrder = new List<string>() private
Definition at line 62 of file TTSRuntimeCache.cs.
_clips
Dictionary<string, TTSClipData> Meta.WitAi.TTS.Integrations.TTSRuntimeCache._clips = new Dictionary<string, TTSClipData>() private
Definition at line 61 of file TTSRuntimeCache.cs.
ClipCapacity
int Meta.WitAi.TTS.Integrations.TTSRuntimeCache.ClipCapacity = 20
The maximum clips allowed in the runtime cache.
Definition at line 35 of file TTSRuntimeCache.cs.
ClipLimit
bool Meta.WitAi.TTS.Integrations.TTSRuntimeCache.ClipLimit = true
Whether or not to unload clip data after the clip capacity is hit.
Definition at line 28 of file TTSRuntimeCache.cs.
RamCapacity
int Meta.WitAi.TTS.Integrations.TTSRuntimeCache.RamCapacity = 32768
The maximum amount of RAM allowed in the runtime cache. In KBs.
Definition at line 49 of file TTSRuntimeCache.cs.
RamLimit
bool Meta.WitAi.TTS.Integrations.TTSRuntimeCache.RamLimit = true
Whether or not to unload clip data after the ram capacity is hit.
Definition at line 42 of file TTSRuntimeCache.cs.
Property Documentation
OnClipAdded
TTSClipEvent Meta.WitAi.TTS.Integrations.TTSRuntimeCache.OnClipAdded = new TTSClipEvent() get set
On clip added callback.
Implements Meta.WitAi.TTS.Interfaces.ITTSRuntimeCacheHandler.
Definition at line 54 of file TTSRuntimeCache.cs.
{ get; set; } = new TTSClipEvent();
OnClipRemoved
TTSClipEvent Meta.WitAi.TTS.Integrations.TTSRuntimeCache.OnClipRemoved = new TTSClipEvent() get set
On clip removed callback.
Implements Meta.WitAi.TTS.Interfaces.ITTSRuntimeCacheHandler.
Definition at line 58 of file TTSRuntimeCache.cs.
{ get; set; } = new TTSClipEvent();
The documentation for this class was generated from the following file:
Assets/Oculus/Voice/Lib/Wit.ai/Features/TTS/Scripts/Runtime/Integrations/TTSRuntimeCache.cs