VR_Test: Meta.WitAi.Dictation.WitDictation Class Reference
Meta.WitAi.Dictation.WitDictation Class Reference
Public Member Functions
WitRequest CreateWitRequest (WitConfiguration config, WitRequestOptions requestOptions, VoiceServiceRequestEvents requestEvents, IDynamicEntitiesProvider[] additionalEntityProviders=null)
override VoiceServiceRequest Activate (WitRequestOptions requestOptions, VoiceServiceRequestEvents requestEvents)
Activates and waits for the user to exceed the min wake threshold before data is sent to the server.
override VoiceServiceRequest ActivateImmediately (WitRequestOptions requestOptions, VoiceServiceRequestEvents requestEvents)
Activates immediately and starts sending data to the server. This will not wait for min wake threshold.
override void Deactivate ()
Deactivates. If a transcription is in progress the network request will complete and any additional transcription values will be returned.
override void Cancel ()
Deactivates and ignores any pending transcription content.
void TranscribeFile (string fileName)
Public Member Functions inherited from Meta.WitAi.Dictation.DictationService
void Activate ()
Activate the microphone and send data for NLU processing. Includes optional additional request parameters like dynamic entities and maximum results.
void Activate (WitRequestOptions requestOptions)
Activate the microphone and send data for NLU processing. Includes optional additional request parameters like dynamic entities and maximum results.
VoiceServiceRequest Activate (VoiceServiceRequestEvents requestEvents)
Activate the microphone and send data for NLU processing. Includes optional additional request parameters like dynamic entities and maximum results.
VoiceServiceRequest Activate (WitRequestOptions requestOptions, VoiceServiceRequestEvents requestEvents)
Activate the microphone and send data for NLU processing. Includes optional additional request parameters like dynamic entities and maximum results.
void ActivateImmediately ()
Activate the microphone and send data for NLU processing immediately without waiting for sound/speech from the user to begin. Includes optional additional request parameters like dynamic entities and maximum results.
void ActivateImmediately (WitRequestOptions requestOptions)
Activate the microphone and send data for NLU processing immediately without waiting for sound/speech from the user to begin. Includes optional additional request parameters like dynamic entities and maximum results.
VoiceServiceRequest ActivateImmediately (VoiceServiceRequestEvents requestEvents)
Activate the microphone and send data for NLU processing immediately without waiting for sound/speech from the user to begin. Includes optional additional request parameters like dynamic entities and maximum results.
VoiceServiceRequest ActivateImmediately (WitRequestOptions requestOptions, VoiceServiceRequestEvents requestEvents)
Activate the microphone and send data for NLU processing immediately without waiting for sound/speech from the user to begin. Includes optional additional request parameters like dynamic entities and maximum results.
void Deactivate ()
Stop listening and submit any remaining buffered microphone data for processing.
void Cancel ()
Cancels the current transcription. No FullTranscription event will fire.
Protected Member Functions
override void Awake ()
override void OnEnable ()
override void OnDisable ()
Properties
WitRuntimeConfiguration RuntimeConfiguration [get, set]
WitConfiguration Configuration [get]
override bool Active [get]
override bool IsRequestActive [get]
override ITranscriptionProvider TranscriptionProvider [get, set]
override bool MicActive [get]
override bool ShouldSendMicData [get]
VoiceEvents VoiceEvents [get]
Events specific to wit voice activation.
override DictationEvents DictationEvents [get, set]
Properties inherited from Meta.WitAi.Dictation.DictationService
bool Active [get]
Returns true if this voice service is currently active and listening with the mic.
bool IsRequestActive [get]
Returns true if the service is actively communicating with Wit.ai during an Activation. The mic may or may not still be active while this is true.
ITranscriptionProvider TranscriptionProvider [get, set]
Gets/Sets a custom transcription provider. This can be used to replace any built in asr with an on device model or other provided source.
bool MicActive [get]
Returns true if this voice service is currently reading data from the microphone.
virtual DictationEvents DictationEvents [get, set]
TelemetryEvents TelemetryEvents [get, set]
IAudioInputEvents AudioEvents [get]
A subset of events around collection of audio data.
ITranscriptionEvent TranscriptionEvents [get]
A subset of events around receiving transcriptions.
bool ShouldSendMicData [get]
Returns true if the audio input should be read in an activation.
Properties inherited from Meta.WitAi.Dictation.IDictationService
Properties inherited from Meta.WitAi.ITelemetryEventsProvider
Properties inherited from Meta.WitAi.Interfaces.IAudioEventProvider
Properties inherited from Meta.WitAi.Interfaces.ITranscriptionEventProvider
Properties inherited from Meta.WitAi.IWitRuntimeConfigProvider
Properties inherited from Meta.WitAi.IVoiceEventProvider
Properties inherited from Meta.WitAi.Interfaces.IWitConfigurationProvider
Private Attributes
WitRuntimeConfiguration witRuntimeConfiguration
WitService witService
readonly VoiceEvents _voiceEvents = new VoiceEvents()
Additional Inherited Members
Protected Attributes inherited from Meta.WitAi.Dictation.DictationService
DictationEvents dictationEvents = new DictationEvents()
TelemetryEvents telemetryEvents = new TelemetryEvents()
Detailed Description
Definition at line 20 of file WitDictation.cs.
Member Function Documentation
Activate()
override VoiceServiceRequest Meta.WitAi.Dictation.WitDictation.Activate (WitRequestOptions requestOptions, VoiceServiceRequestEvents requestEvents)
Activates and waits for the user to exceed the min wake threshold before data is sent to the server.
Parameters
requestOptions Additional options such as custom request id
requestEvents Events specific to the request's lifecycle
Implements Meta.WitAi.Dictation.IDictationService.
Definition at line 90 of file WitDictation.cs.
        {
            return witService.Activate(requestOptions, requestEvents);
        }
References Meta.WitAi.WitService.Activate().
ActivateImmediately()
override VoiceServiceRequest Meta.WitAi.Dictation.WitDictation.ActivateImmediately (WitRequestOptions requestOptions, VoiceServiceRequestEvents requestEvents)
Activates immediately and starts sending data to the server. This will not wait for min wake threshold.
Parameters
requestOptions Additional options such as custom request id
requestEvents Events specific to the request's lifecycle
Implements Meta.WitAi.Dictation.IDictationService.
Definition at line 100 of file WitDictation.cs.
        {
            return witService.ActivateImmediately(requestOptions, requestEvents);
        }
References Meta.WitAi.WitService.ActivateImmediately().
Awake()
override void Meta.WitAi.Dictation.WitDictation.Awake () protected virtual
Reimplemented from Meta.WitAi.Dictation.DictationService.
Definition at line 123 of file WitDictation.cs.
        {
            base.Awake();
            witService = gameObject.AddComponent<WitService>();
            witService.VoiceEventProvider = this;
            witService.ConfigurationProvider = this;
            witService.WitRequestProvider = this;
            witService.TelemetryEventsProvider = this;
        }
Cancel()
override void Meta.WitAi.Dictation.WitDictation.Cancel ()
Deactivates and ignores any pending transcription content.
Implements Meta.WitAi.Dictation.IDictationService.
Definition at line 117 of file WitDictation.cs.
        {
            witService.DeactivateAndAbortRequest();
        }
References Meta.WitAi.WitService.DeactivateAndAbortRequest().
CreateWitRequest()
WitRequest Meta.WitAi.Dictation.WitDictation.CreateWitRequest (WitConfiguration config, WitRequestOptions requestOptions, VoiceServiceRequestEvents requestEvents, IDynamicEntitiesProvider[] additionalEntityProviders = null)
Implements Meta.WitAi.Interfaces.IWitRequestProvider.
Definition at line 75 of file WitDictation.cs.
        {
            return config.CreateDictationRequest(requestOptions, requestEvents);
        }
Deactivate()
override void Meta.WitAi.Dictation.WitDictation.Deactivate ()
Deactivates. If a transcription is in progress the network request will complete and any additional transcription values will be returned.
Implements Meta.WitAi.Dictation.IDictationService.
Definition at line 109 of file WitDictation.cs.
        {
            witService.Deactivate();
        }
References Meta.WitAi.WitService.Deactivate().
OnDisable()
override void Meta.WitAi.Dictation.WitDictation.OnDisable () protected virtual
Reimplemented from Meta.WitAi.Dictation.DictationService.
Definition at line 139 of file WitDictation.cs.
        {
            base.OnDisable();
            VoiceEvents.RemoveListener(DictationEvents);
        }
OnEnable()
override void Meta.WitAi.Dictation.WitDictation.OnEnable () protected virtual
Reimplemented from Meta.WitAi.Dictation.DictationService.
Definition at line 133 of file WitDictation.cs.
        {
            base.OnEnable();
            VoiceEvents.AddListener(DictationEvents);
        }
TranscribeFile()
void Meta.WitAi.Dictation.WitDictation.TranscribeFile (string fileName)
Definition at line 145 of file WitDictation.cs.
        {
            var request = CreateWitRequest(witRuntimeConfiguration.witConfiguration, new WitRequestOptions(), new VoiceServiceRequestEvents());
            var data = File.ReadAllBytes(fileName);
            request.postData = data;
            witService.ExecuteRequest(request);
        }
Member Data Documentation
_voiceEvents
readonly VoiceEvents Meta.WitAi.Dictation.WitDictation._voiceEvents = new VoiceEvents() private
Definition at line 55 of file WitDictation.cs.
witRuntimeConfiguration
WitRuntimeConfiguration Meta.WitAi.Dictation.WitDictation.witRuntimeConfiguration private
Definition at line 22 of file WitDictation.cs.
witService
WitService Meta.WitAi.Dictation.WitDictation.witService private
Definition at line 24 of file WitDictation.cs.
Property Documentation
Active
override bool Meta.WitAi.Dictation.WitDictation.Active get
Implements Meta.WitAi.Dictation.IDictationService.
Definition at line 35 of file WitDictation.cs.
Configuration
WitConfiguration Meta.WitAi.Dictation.WitDictation.Configuration get
Implements Meta.WitAi.Interfaces.IWitConfigurationProvider.
Definition at line 31 of file WitDictation.cs.
DictationEvents
override DictationEvents Meta.WitAi.Dictation.WitDictation.DictationEvents get set
Implements Meta.WitAi.Dictation.IDictationService.
Definition at line 57 of file WitDictation.cs.
        {
            get => dictationEvents;
            set
            {
                DictationEvents oldEvents = dictationEvents;
                dictationEvents = value;
                if (gameObject.activeSelf)
                {
                    VoiceEvents.RemoveListener(oldEvents);
                    VoiceEvents.AddListener(dictationEvents);
                }
            }
        }
IsRequestActive
override bool Meta.WitAi.Dictation.WitDictation.IsRequestActive get
Implements Meta.WitAi.Dictation.IDictationService.
Definition at line 36 of file WitDictation.cs.
MicActive
override bool Meta.WitAi.Dictation.WitDictation.MicActive get
Implements Meta.WitAi.Dictation.IDictationService.
Definition at line 45 of file WitDictation.cs.
RuntimeConfiguration
WitRuntimeConfiguration Meta.WitAi.Dictation.WitDictation.RuntimeConfiguration get set
Implements Meta.WitAi.IWitRuntimeConfigProvider.
Definition at line 26 of file WitDictation.cs.
        {
            get => witRuntimeConfiguration;
            set => witRuntimeConfiguration = value;
        }
ShouldSendMicData
override bool Meta.WitAi.Dictation.WitDictation.ShouldSendMicData get protected
Definition at line 47 of file WitDictation.cs.
TranscriptionProvider
override ITranscriptionProvider Meta.WitAi.Dictation.WitDictation.TranscriptionProvider get set
Implements Meta.WitAi.Dictation.IDictationService.
Definition at line 38 of file WitDictation.cs.
        {
            get => witService.TranscriptionProvider;
            set => witService.TranscriptionProvider = value;
        }
VoiceEvents
VoiceEvents Meta.WitAi.Dictation.WitDictation.VoiceEvents get
Events specific to wit voice activation.
Implements Meta.WitAi.IVoiceEventProvider.
Definition at line 54 of file WitDictation.cs.
The documentation for this class was generated from the following file:
Assets/Oculus/Voice/Lib/Wit.ai/Features/Dictation/Scripts/Runtime/Dictation/WitDictation.cs