VR_Test: Meta.WitAi.VoiceService Class Reference
Meta.WitAi.VoiceService Class Reference abstract
Public Member Functions
void Activate (string text)
Send text data for NLU processing. Results will return the same way a voice based activation would.
void Activate (string text, WitRequestOptions requestOptions)
Send text data for NLU processing. Results will return the same way a voice based activation would.
VoiceServiceRequest Activate (string text, VoiceServiceRequestEvents requestEvents)
Send text data for NLU processing. Results will return the same way a voice based activation would.
VoiceServiceRequest Activate (string text, WitRequestOptions requestOptions, VoiceServiceRequestEvents requestEvents)
Send text data for NLU processing with custom request options.
virtual bool CanSend ()
Whether voice requests can be sent or not.
virtual bool CanActivateAudio ()
Whether audio can be activated or not.
void Activate ()
Start listening for sound or speech from the user and start sending data to Wit.ai once sound or speech has been detected.
void Activate (WitRequestOptions requestOptions)
Start listening for sound or speech from the user and start sending data to Wit.ai once sound or speech has been detected.
VoiceServiceRequest Activate (VoiceServiceRequestEvents requestEvents)
Start listening for sound or speech from the user and start sending data to Wit.ai once sound or speech has been detected.
VoiceServiceRequest Activate (WitRequestOptions requestOptions, VoiceServiceRequestEvents requestEvents)
Start listening for sound or speech from the user and start sending data to Wit.ai once sound or speech has been detected.
void ActivateImmediately ()
Activate the microphone and send data for NLU processing immediately without waiting for sound/speech from the user to begin.
void ActivateImmediately (WitRequestOptions requestOptions)
Activate the microphone and send data for NLU processing immediately without waiting for sound/speech from the user to begin.
VoiceServiceRequest ActivateImmediately (VoiceServiceRequestEvents requestEvents)
Activate the microphone and send data for NLU processing immediately without waiting for sound/speech from the user to begin.
VoiceServiceRequest ActivateImmediately (WitRequestOptions requestOptions, VoiceServiceRequestEvents requestEvents)
Activate the microphone and send data for NLU processing immediately without waiting for sound/speech from the user to begin.
void Deactivate ()
Stop listening and submit any remaining buffered microphone data for processing.
void DeactivateAndAbortRequest ()
Stop listening and abort any requests that may be active without waiting for a response.
virtual void DeactivateAndAbortRequest (VoiceServiceRequest request)
Abort a specific request.
IEnumerable< object > GetObjectsOfType (Type type)
Returns objects of the specified type.
Protected Member Functions
VoiceService ()
Constructs a VoiceService
virtual void OnTextRequestCreated (VoiceServiceRequest textRequest)
Called on text request creation.
virtual string GetSendError ()
Check for error that will occur if attempting to send data.
virtual void HandleRequestResults (VoiceServiceRequest request)
Called after request cancellation, failure or success.
string GetActivateAudioError ()
Check for error that will occur if attempting to read an audio source.
virtual void OnAudioRequestCreated (VoiceServiceRequest audioRequest)
Called on creation.
virtual void OnAudioPartialResponse (VoiceServiceRequest audioRequest)
virtual void Awake ()
virtual void OnEnable ()
virtual void OnDisable ()
virtual void OnFinalTranscription (string transcription)
Activate message if transcription provider returns a final transcription.
virtual void HandleResponse (WitResponseNode response)
Protected Attributes
VoiceEvents events = new VoiceEvents()
This field should not be accessed outside the Wit-Unity library. If you need access to events you should be using the VoiceService.VoiceEvents property instead.
TelemetryEvents telemetryEvents = new TelemetryEvents()
Properties
bool UseConduit [get]
When set to true, Conduit will be used. Otherwise, the legacy dispatching will be used.
WitConfiguration WitConfiguration [get]
Wit configuration accessor via IWitConfigurationProvider.
virtual bool Active [get]
Returns true if this voice service is currently active and listening with the mic.
virtual bool IsRequestActive [get]
Returns true if the service is actively communicating with Wit.ai during an Activation. The mic may or may not still be active while this is true.
ITranscriptionProvider TranscriptionProvider [get, set]
Gets/Sets a custom transcription provider. This can be used to replace any built in asr with an on device model or other provided source.
bool MicActive [get]
Returns true if this voice service is currently reading data from the microphone.
virtual VoiceEvents VoiceEvents [get, set]
All events used for a voice service.
virtual TelemetryEvents TelemetryEvents [get, set]
All events used for a voice service telemetry.
IAudioInputEvents AudioEvents [get]
A subset of events around collection of audio data.
ITranscriptionEvent TranscriptionEvents [get]
A subset of events around receiving transcriptions.
bool ShouldSendMicData [get]
Returns true if the audio input should be read in an activation.
HashSet< VoiceServiceRequest > Requests = new HashSet<VoiceServiceRequest>() [get]
All currently running requests.
Properties inherited from Meta.WitAi.IVoiceService
Properties inherited from Meta.WitAi.IVoiceEventProvider
Properties inherited from Meta.WitAi.ITelemetryEventsProvider
Properties inherited from Meta.WitAi.IVoiceActivationHandler
Properties inherited from Meta.WitAi.Interfaces.IAudioEventProvider
Private Member Functions
void InitializeEventListeners ()
VoiceSession GetVoiceSession (WitResponseNode response)
void HandleIntents (WitResponseNode response)
void HandleIntent (WitIntentData intent, WitResponseNode response)
void ExecuteRegisteredMatch (RegisteredMatchIntent registeredMethod, WitIntentData intent, WitResponseNode response)
Private Attributes
WitConfiguration _witConfiguration
readonly IParameterProvider _conduitParameterProvider = new ParameterProvider()
The Conduit parameter provider.
Detailed Description
Definition at line 27 of file VoiceService.cs.
Constructor & Destructor Documentation
VoiceService()
Meta.WitAi.VoiceService.VoiceService () protected
Constructs a VoiceService
Definition at line 129 of file VoiceService.cs.
        {
            _conduitParameterProvider.SetSpecializedParameter(ParameterProvider.WitResponseNodeReservedName, typeof(WitResponseNode));
            _conduitParameterProvider.SetSpecializedParameter(ParameterProvider.VoiceSessionReservedName, typeof(VoiceSession));
            var conduitDispatcherFactory = new ConduitDispatcherFactory(this);
            ConduitDispatcher = conduitDispatcherFactory.GetDispatcher();
        }
References Meta.WitAi.VoiceService._conduitParameterProvider.
Member Function Documentation
Activate() [1/7]
void Meta.WitAi.VoiceService.Activate (string text)
Send text data for NLU processing. Results will return the same way a voice based activation would.
Parameters
text Text to be used for NLU processing
Activate() [2/7]
VoiceServiceRequest Meta.WitAi.VoiceService.Activate (string text, VoiceServiceRequestEvents requestEvents)
Send text data for NLU processing. Results will return the same way a voice based activation would.
Parameters
text Text to be used for NLU processing
requestEvents Events specific to the request's lifecycle
Activate() [3/7]
void Meta.WitAi.VoiceService.Activate (string text, WitRequestOptions requestOptions)
Send text data for NLU processing. Results will return the same way a voice based activation would.
Parameters
text Text to be used for NLU processing
requestOptions Additional options such as dynamic entities
Activate() [4/7]
VoiceServiceRequest Meta.WitAi.VoiceService.Activate (string text, WitRequestOptions requestOptions, VoiceServiceRequestEvents requestEvents) abstract
Send text data for NLU processing with custom request options.
Parameters
text Text to be used for NLU processing
requestOptions Additional options such as dynamic entities
requestEvents Events specific to the request's lifecycle
Implements Meta.WitAi.IVoiceActivationHandler.
Activate() [5/7]
VoiceServiceRequest Meta.WitAi.VoiceService.Activate (VoiceServiceRequestEvents requestEvents)
Start listening for sound or speech from the user and start sending data to Wit.ai once sound or speech has been detected.
Parameters
requestEvents Events specific to the request's lifecycle
Activate() [6/7]
void Meta.WitAi.VoiceService.Activate (WitRequestOptions requestOptions)
Start listening for sound or speech from the user and start sending data to Wit.ai once sound or speech has been detected.
Parameters
requestOptions Additional options such as dynamic entities
Activate() [7/7]
VoiceServiceRequest Meta.WitAi.VoiceService.Activate (WitRequestOptions requestOptions, VoiceServiceRequestEvents requestEvents) abstract
Start listening for sound or speech from the user and start sending data to Wit.ai once sound or speech has been detected.
Parameters
requestOptions Additional options such as dynamic entities
requestEvents Events specific to the request's lifecycle
Implements Meta.WitAi.IVoiceActivationHandler.
ActivateImmediately() [1/3]
VoiceServiceRequest Meta.WitAi.VoiceService.ActivateImmediately (VoiceServiceRequestEvents requestEvents)
Activate the microphone and send data for NLU processing immediately without waiting for sound/speech from the user to begin.
Parameters
requestEvents Events specific to the request's lifecycle
ActivateImmediately() [2/3]
void Meta.WitAi.VoiceService.ActivateImmediately (WitRequestOptions requestOptions)
Activate the microphone and send data for NLU processing immediately without waiting for sound/speech from the user to begin.
Parameters
requestOptions Additional options such as dynamic entities
ActivateImmediately() [3/3]
VoiceServiceRequest Meta.WitAi.VoiceService.ActivateImmediately (WitRequestOptions requestOptions, VoiceServiceRequestEvents requestEvents) abstract
Activate the microphone and send data for NLU processing immediately without waiting for sound/speech from the user to begin.
Parameters
requestOptions Additional options such as dynamic entities
requestEvents Events specific to the request's lifecycle
Implements Meta.WitAi.IVoiceActivationHandler.
Awake()
virtual void Meta.WitAi.VoiceService.Awake () protected virtual
Definition at line 364 of file VoiceService.cs.
        {
            InitializeEventListeners();
            if (!UseConduit)
            {
                MatchIntentRegistry.Initialize();
            }
        }
CanActivateAudio()
virtual bool Meta.WitAi.VoiceService.CanActivateAudio () virtual
Whether audio can be activated or not.
Returns
Implements Meta.WitAi.IVoiceService.
Reimplemented in Oculus.Voice.AppVoiceExperience.
CanSend()
virtual bool Meta.WitAi.VoiceService.CanSend () virtual
Whether voice requests can be sent or not.
Returns
Implements Meta.WitAi.IVoiceService.
Reimplemented in Oculus.Voice.AppVoiceExperience.
Deactivate()
void Meta.WitAi.VoiceService.Deactivate () abstract
Stop listening and submit any remaining buffered microphone data for processing.
Implements Meta.WitAi.IVoiceActivationHandler.
DeactivateAndAbortRequest() [1/2]
void Meta.WitAi.VoiceService.DeactivateAndAbortRequest () abstract
Stop listening and abort any requests that may be active without waiting for a response.
Implements Meta.WitAi.IVoiceActivationHandler.
DeactivateAndAbortRequest() [2/2]
virtual void Meta.WitAi.VoiceService.DeactivateAndAbortRequest (VoiceServiceRequest request) virtual
Abort a specific request.
Implements Meta.WitAi.IVoiceActivationHandler.
ExecuteRegisteredMatch()
void Meta.WitAi.VoiceService.ExecuteRegisteredMatch (RegisteredMatchIntent registeredMethod, WitIntentData intent, WitResponseNode response) private
Definition at line 473 of file VoiceService.cs.
        {
            if (intent.confidence >= registeredMethod.matchIntent.MinConfidence &&
                intent.confidence <= registeredMethod.matchIntent.MaxConfidence)
            {
                foreach (var obj in GetObjectsOfType(registeredMethod.type))
                {
                    var parameters = registeredMethod.method.GetParameters();
                    if (parameters.Length == 0)
                    {
                        registeredMethod.method.Invoke(obj, Array.Empty<object>());
                        continue;
                    }
                    if (parameters[0].ParameterType != typeof(WitResponseNode) || parameters.Length > 2)
                    {
                        VLog.E("Match intent only supports methods with no parameters or with a WitResponseNode parameter. Enable Conduit or adjust the parameters");
                        continue;
                    }
                    if (parameters.Length == 1)
                    {
                        registeredMethod.method.Invoke(obj, new object[] {response});
                    }
                }
            }
        }
GetActivateAudioError()
string Meta.WitAi.VoiceService.GetActivateAudioError () abstract protected
Check for error that will occur if attempting to read an audio source.
Returns
Returns an error if audio cannot be read.
GetObjectsOfType()
IEnumerable< object > Meta.WitAi.VoiceService.GetObjectsOfType (Type type)
Returns objects of the specified type.
Parameters
type The type.
Returns
Objects of the specified type.
Definition at line 359 of file VoiceService.cs.
        {
            return FindObjectsOfType(type);
        }
GetSendError()
virtual string Meta.WitAi.VoiceService.GetSendError () protected virtual
Check for error that will occur if attempting to send data.
Returns
Returns an error if send will not be allowed.
Reimplemented in Meta.WitAi.Wit.
Definition at line 198 of file VoiceService.cs.
        {
            // Cannot send if internet is not reachable (Only works on Mobile)
            if (Application.internetReachability == NetworkReachability.NotReachable)
            {
                return "Unable to reach the internet.  Check your connection.";
            }
            // No error
            return string.Empty;
        }
GetVoiceSession()
VoiceSession Meta.WitAi.VoiceService.GetVoiceSession (WitResponseNode response) private
Definition at line 428 of file VoiceService.cs.
        {
            return new VoiceSession
            {
                service = this,
                response = response,
                validResponse = false
            };
        }
HandleIntent()
void Meta.WitAi.VoiceService.HandleIntent (WitIntentData intent, WitResponseNode response) private
Definition at line 452 of file VoiceService.cs.
        {
            if (UseConduit)
            {
                _conduitParameterProvider.PopulateParametersFromNode(response);
                _conduitParameterProvider.AddParameter(ParameterProvider.WitResponseNodeReservedName, response);
                ConduitDispatcher.InvokeAction(_conduitParameterProvider, intent.name,
                    _witConfiguration.relaxedResolution, intent.confidence, false);
            }
            else
            {
                var methods = MatchIntentRegistry.RegisteredMethods[intent.name];
                foreach (var method in methods)
                {
                    ExecuteRegisteredMatch(method, intent, response);
                }
            }
        }
HandleIntents()
void Meta.WitAi.VoiceService.HandleIntents (WitResponseNode response) private
Definition at line 443 of file VoiceService.cs.
        {
            var intents = response.GetIntents();
            foreach (var intent in intents)
            {
                HandleIntent(intent, response);
            }
        }
HandleRequestResults()
virtual void Meta.WitAi.VoiceService.HandleRequestResults (VoiceServiceRequest request) protected virtual
Called after request cancellation, failure or success.
Definition at line 211 of file VoiceService.cs.
        {
            // Remove request from requests list
            if (Requests.Contains(request))
            {
                Requests.Remove(request);
            }
        }
References Meta.WitAi.VoiceService.Requests.
HandleResponse()
virtual void Meta.WitAi.VoiceService.HandleResponse (WitResponseNode response) protected virtual
Definition at line 438 of file VoiceService.cs.
        {
            HandleIntents(response);
        }
InitializeEventListeners()
void Meta.WitAi.VoiceService.InitializeEventListeners () private
Definition at line 374 of file VoiceService.cs.
        {
            var audioEventListener = GetComponent<AudioEventListener>();
            if (!audioEventListener)
            {
                gameObject.AddComponent<AudioEventListener>();
            }
            var transcriptionEventListener = GetComponent<TranscriptionEventListener>();
            if (!transcriptionEventListener)
            {
                gameObject.AddComponent<TranscriptionEventListener>();
            }
        }
OnAudioPartialResponse()
virtual void Meta.WitAi.VoiceService.OnAudioPartialResponse (VoiceServiceRequest audioRequest) protected virtual
Definition at line 301 of file VoiceService.cs.
        {
            // Ignore unless can be validated
            if (VoiceEvents.OnValidatePartialResponse == null || audioRequest == null || audioRequest.State != VoiceRequestState.Transmitting)
            {
                return;
            }
            // Create short response data
            WitResponseNode response = audioRequest?.Results?.ResponseData;
            VoiceSession validationData = GetVoiceSession(response);
            // Call short response
            VoiceEvents.OnValidatePartialResponse.Invoke(validationData);
            // Invoke
            if (UseConduit)
            {
                // Ignore without an intent
                WitIntentData intent = response.GetFirstIntentData();
                if (intent != null)
                {
                    _conduitParameterProvider.PopulateParametersFromNode(response);
                    _conduitParameterProvider.AddParameter(ParameterProvider.VoiceSessionReservedName,
                        validationData);
                    _conduitParameterProvider.AddParameter(ParameterProvider.WitResponseNodeReservedName, response);
                    ConduitDispatcher.InvokeAction(_conduitParameterProvider, intent.name, _witConfiguration.relaxedResolution, intent.confidence, true);
                }
            }
            // Deactivate & abort immediately but use the response data as results
            if (validationData.validResponse)
            {
                VLog.D("Validated Early");
                audioRequest.CompleteEarly();
            }
        }
OnAudioRequestCreated()
virtual void Meta.WitAi.VoiceService.OnAudioRequestCreated (VoiceServiceRequest audioRequest) protected virtual
Called on creation.
Parameters
request
Definition at line 283 of file VoiceService.cs.
        {
            if (audioRequest == null)
            {
                return;
            }
            if (!audioRequest.IsActive)
            {
                HandleRequestResults(audioRequest);
                return;
            }
            audioRequest.Events.OnPartialResponse.AddListener((response) => OnAudioPartialResponse(audioRequest));
            audioRequest.Events.OnCancel.AddListener(HandleRequestResults);
            audioRequest.Events.OnFailed.AddListener(HandleRequestResults);
            audioRequest.Events.OnSuccess.AddListener(HandleRequestResults);
            Requests.Add(audioRequest);
        }
References Meta.WitAi.VoiceService.HandleRequestResults(), and Meta.WitAi.VoiceService.Requests.
OnDisable()
virtual void Meta.WitAi.VoiceService.OnDisable () protected virtual
Definition at line 411 of file VoiceService.cs.
        {
            TranscriptionProvider?.OnFullTranscription.RemoveListener(OnFinalTranscription);
            VoiceEvents.OnResponse.RemoveListener(HandleResponse);
        }
OnEnable()
virtual void Meta.WitAi.VoiceService.OnEnable () protected virtual
Definition at line 389 of file VoiceService.cs.
        {
            if (UseConduit)
            {
                ConduitDispatcher.Initialize(_witConfiguration.ManifestLocalPath);
                if (_witConfiguration.relaxedResolution)
                {
                    if (!ConduitDispatcher.Manifest.ResolveEntities())
                    {
                        VLog.E("Failed to resolve Conduit entities");
                    }
                    foreach (var entity in ConduitDispatcher.Manifest.CustomEntityTypes)
                    {
                        _conduitParameterProvider.AddCustomType(entity.Key, entity.Value);
                    }
                }
            }
            TranscriptionProvider?.OnFullTranscription.AddListener(OnFinalTranscription);
            VoiceEvents.OnResponse.AddListener(HandleResponse);
        }
OnFinalTranscription()
virtual void Meta.WitAi.VoiceService.OnFinalTranscription (string transcription) protected virtual
Activate message if transcription provider returns a final transcription.
Definition at line 420 of file VoiceService.cs.
        {
            if (TranscriptionProvider != null)
            {
                Activate(transcription);
            }
        }
References Meta.WitAi.VoiceService.Activate(), and Meta.WitAi.VoiceService.TranscriptionProvider.
OnTextRequestCreated()
virtual void Meta.WitAi.VoiceService.OnTextRequestCreated (VoiceServiceRequest textRequest) protected virtual
Called on text request creation.
Parameters
request
Definition at line 170 of file VoiceService.cs.
        {
            if (textRequest == null)
            {
                return;
            }
            if (!textRequest.IsActive)
            {
                HandleRequestResults(textRequest);
                return;
            }
            textRequest.Events.OnCancel.AddListener(HandleRequestResults);
            textRequest.Events.OnFailed.AddListener(HandleRequestResults);
            textRequest.Events.OnSuccess.AddListener(HandleRequestResults);
            Requests.Add(textRequest);
        }
References Meta.WitAi.VoiceService.HandleRequestResults(), and Meta.WitAi.VoiceService.Requests.
Member Data Documentation
_conduitParameterProvider
readonly IParameterProvider Meta.WitAi.VoiceService._conduitParameterProvider = new ParameterProvider() private
The Conduit parameter provider.
Definition at line 53 of file VoiceService.cs.
_witConfiguration
WitConfiguration Meta.WitAi.VoiceService._witConfiguration private
Definition at line 48 of file VoiceService.cs.
events
VoiceEvents Meta.WitAi.VoiceService.events = new VoiceEvents() protected
This field should not be accessed outside the Wit-Unity library. If you need access to events you should be using the VoiceService.VoiceEvents property instead.
summary> Internal events used to report telemetry. These events are reserved for internal use only and should not be used for any other purpose.
Definition at line 60 of file VoiceService.cs.
telemetryEvents
TelemetryEvents Meta.WitAi.VoiceService.telemetryEvents = new TelemetryEvents() protected
Definition at line 66 of file VoiceService.cs.
Property Documentation
Active
virtual bool Meta.WitAi.VoiceService.Active get
Returns true if this voice service is currently active and listening with the mic.
Implements Meta.WitAi.IVoiceActivationHandler.
Definition at line 71 of file VoiceService.cs.
AudioEvents
IAudioInputEvents Meta.WitAi.VoiceService.AudioEvents get
A subset of events around collection of audio data.
Implements Meta.WitAi.Interfaces.IAudioEventProvider.
Definition at line 109 of file VoiceService.cs.
IsRequestActive
virtual bool Meta.WitAi.VoiceService.IsRequestActive get
Returns true if the service is actively communicating with Wit.ai during an Activation. The mic may or may not still be active while this is true.
Implements Meta.WitAi.IVoiceService.
Definition at line 81 of file VoiceService.cs.
MicActive
bool Meta.WitAi.VoiceService.MicActive get abstract
Returns true if this voice service is currently reading data from the microphone.
Implements Meta.WitAi.IVoiceService.
Definition at line 92 of file VoiceService.cs.
{ get; }
Requests
HashSet<VoiceServiceRequest> Meta.WitAi.VoiceService.Requests = new HashSet<VoiceServiceRequest>() get
All currently running requests.
Implements Meta.WitAi.IVoiceService.
Definition at line 124 of file VoiceService.cs.
{ get; } = new HashSet<VoiceServiceRequest>();
ShouldSendMicData
bool Meta.WitAi.VoiceService.ShouldSendMicData get abstract protected
Returns true if the audio input should be read in an activation.
Definition at line 119 of file VoiceService.cs.
{ get; }
TelemetryEvents
virtual TelemetryEvents Meta.WitAi.VoiceService.TelemetryEvents get set
All events used for a voice service telemetry.
Implements Meta.WitAi.IVoiceService.
Definition at line 100 of file VoiceService.cs.
        {
            get => telemetryEvents;
            set => telemetryEvents = value;
        }
TranscriptionEvents
ITranscriptionEvent Meta.WitAi.VoiceService.TranscriptionEvents get
A subset of events around receiving transcriptions.
Definition at line 114 of file VoiceService.cs.
TranscriptionProvider
ITranscriptionProvider Meta.WitAi.VoiceService.TranscriptionProvider get set abstract
Gets/Sets a custom transcription provider. This can be used to replace any built in asr with an on device model or other provided source.
Implements Meta.WitAi.IVoiceService.
Definition at line 87 of file VoiceService.cs.
{ get; set; }
UseConduit
bool Meta.WitAi.VoiceService.UseConduit get private
When set to true, Conduit will be used. Otherwise, the legacy dispatching will be used.
Definition at line 32 of file VoiceService.cs.
VoiceEvents
virtual VoiceEvents Meta.WitAi.VoiceService.VoiceEvents get set
All events used for a voice service.
Implements Meta.WitAi.IVoiceService.
Definition at line 94 of file VoiceService.cs.
        {
            get => events;
            set => events = value;
        }
WitConfiguration
WitConfiguration Meta.WitAi.VoiceService.WitConfiguration get
Wit configuration accessor via IWitConfigurationProvider.
Definition at line 37 of file VoiceService.cs.
        {
            get
            {
                if (_witConfiguration == null)
                {
                    _witConfiguration = GetComponent<IWitConfigurationProvider>()?.Configuration;
                }
                return _witConfiguration;
            }
        }
The documentation for this class was generated from the following file:
Assets/Oculus/Voice/Lib/Wit.ai/Scripts/Runtime/VoiceService.cs