VR_Test: Oculus.Interaction.Surfaces.CylinderSurface Class Reference
Oculus.Interaction.Surfaces.CylinderSurface Class Reference
Public Types
enum NormalFacing { Any , In , Out }
Public Member Functions
bool ClosestSurfacePoint (in Vector3 point, out SurfaceHit hit, float maxDistance)
Find nearest point to surface.
bool Raycast (in Ray ray, out SurfaceHit hit, float maxDistance)
Raycast to the surface with an optional maximum distance value.
void InjectAllCylinderSurface (NormalFacing facing, Cylinder cylinder, float height)
void InjectNormalFacing (NormalFacing facing)
void InjectCylinder (Cylinder cylinder)
void InjectHeight (float height)
Protected Member Functions
virtual void Start ()
Protected Attributes
bool _started = false
Properties
bool IsValid [get]
float Radius [get]
Cylinder Cylinder [get]
Transform Transform [get]
A transform for the surface.
Bounds Bounds [get]
The world space axis-aligned bounding box (AABB)
NormalFacing Facing [get, set]
float Height [get, set]
Properties inherited from Oculus.Interaction.Surfaces.ISurface
Properties inherited from Oculus.Interaction.Surfaces.IBounds
Private Member Functions
float TransformScale (float val)
Local to world transformation of a float, assuming uniform scale.
Static Private Member Functions
static Vector3 CancelY (in Vector3 vector)
Cancel the Y component of a vector.
Private Attributes
Cylinder _cylinder
NormalFacing _facing = NormalFacing.Out
float _height = 1f
Detailed Description
Definition at line 26 of file CylinderSurface.cs.
Member Enumeration Documentation
NormalFacing
enum Oculus.Interaction.Surfaces.CylinderSurface.NormalFacing
Enumerator
Any
Raycast hit will register on the outside or inside of the cylinder, whichever is hit first.
In
Raycasts will pass through the outside of the cylinder and hit the inside wall.
Out
Raycast against the outside wall of the cylinder. In this mode, raycasts with an origin inside the cylinder will always fail.
Definition at line 28 of file CylinderSurface.cs.
        {
            Any,
            In,
            Out,
        }
Member Function Documentation
CancelY()
static Vector3 Oculus.Interaction.Surfaces.CylinderSurface.CancelY (in Vector3 vector) static private
Cancel the Y component of a vector.
Definition at line 239 of file CylinderSurface.cs.
        {
            return new Vector3(vector.x, 0, vector.z);
        }
ClosestSurfacePoint()
bool Oculus.Interaction.Surfaces.CylinderSurface.ClosestSurfacePoint (in Vector3 point, out SurfaceHit hit, float maxDistance)
Find nearest point to surface.
Parameters
ray Point to check
hit The returned hit data
maxDistance If greater than zero, maximum distance of check
Returns
true if nearest point was found
Implements Oculus.Interaction.Surfaces.ISurface.
Definition at line 105 of file CylinderSurface.cs.
        {
            hit = new SurfaceHit();
            if (!IsValid)
            {
                return false;
            }
            Vector3 localPoint = _cylinder.transform.InverseTransformPoint(point);
            Vector3 clampedOrigin = localPoint;
            if (_height > 0)
            {
                clampedOrigin.y = Mathf.Clamp(clampedOrigin.y, -_height / 2f, _height / 2f);
            }
            Vector3 nearestPointOnCenterAxis = Vector3.Project(clampedOrigin, Vector3.up);
            Vector3 direction = (clampedOrigin == nearestPointOnCenterAxis) ?
                Vector3.forward : (clampedOrigin - nearestPointOnCenterAxis).normalized;
            bool isOutside = (clampedOrigin - nearestPointOnCenterAxis).magnitude > Radius;
            Vector3 hitPoint = nearestPointOnCenterAxis + direction * Radius;
            float hitDistance = Vector3.Distance(localPoint, hitPoint);
            if (maxDistance > 0 && TransformScale(hitDistance) > maxDistance)
            {
                return false;
            }
            Vector3 normal;
            switch (_facing)
            {
                default:
                case NormalFacing.Any:
                    normal = isOutside ? direction : -direction;
                    break;
                case NormalFacing.In:
                    normal = -direction;
                    break;
                case NormalFacing.Out:
                    normal = direction;
                    break;
            }
            hit.Point = _cylinder.transform.TransformPoint(nearestPointOnCenterAxis + direction * Radius);
            hit.Normal = _cylinder.transform.TransformDirection(normal);
            hit.Distance = TransformScale(hitDistance);
            return true;
        }
References Oculus.Interaction.Surfaces.CylinderSurface.TransformScale().
InjectAllCylinderSurface()
void Oculus.Interaction.Surfaces.CylinderSurface.InjectAllCylinderSurface (NormalFacing facing, Cylinder cylinder, float height)
Definition at line 246 of file CylinderSurface.cs.
        {
            InjectNormalFacing(facing);
            InjectCylinder(cylinder);
            InjectHeight(height);
        }
InjectCylinder()
void Oculus.Interaction.Surfaces.CylinderSurface.InjectCylinder (Cylinder cylinder)
Definition at line 260 of file CylinderSurface.cs.
        {
            _cylinder = cylinder;
        }
InjectHeight()
void Oculus.Interaction.Surfaces.CylinderSurface.InjectHeight (float height)
Definition at line 265 of file CylinderSurface.cs.
        {
            _height = height;
        }
InjectNormalFacing()
void Oculus.Interaction.Surfaces.CylinderSurface.InjectNormalFacing (NormalFacing facing)
Definition at line 255 of file CylinderSurface.cs.
        {
            _facing = facing;
        }
Raycast()
bool Oculus.Interaction.Surfaces.CylinderSurface.Raycast (in Ray ray, out SurfaceHit hit, float maxDistance)
Raycast to the surface with an optional maximum distance value.
Parameters
ray The ray to cast
hit The returned hit data
maxDistance If greater than zero, maximum distance of raycast
Returns
true if surface was hit
Implements Oculus.Interaction.Surfaces.ISurface.
Definition at line 158 of file CylinderSurface.cs.
        {
            // Flatten to 2D and find intersection point with circle in local space,
            // then convert back into 3D world space
            hit = new SurfaceHit();
            if (!IsValid)
            {
                return false;
            }
            Ray localRay3D = new Ray(_cylinder.transform.InverseTransformPoint(ray.origin),
                                     _cylinder.transform.InverseTransformDirection(ray.direction).normalized);
            Ray localRay2D = new Ray(CancelY(localRay3D.origin), CancelY(localRay3D.direction).normalized);
            Vector3 originToCenter2D = -localRay2D.origin;
            Vector3 projPoint2D = localRay2D.origin + Vector3.Project(originToCenter2D, localRay2D.direction);
            float magDir2D = Vector3.Magnitude(CancelY(localRay3D.direction));
            float magProj = Vector3.Magnitude(projPoint2D);
            bool isOutside = originToCenter2D.magnitude > Radius;
            NormalFacing effectiveFacing = _facing == NormalFacing.Any && !isOutside ? NormalFacing.In : _facing;
            bool hasMissed = magProj > Radius || // Aiming toward but missing
                             Mathf.Approximately(magDir2D, 0f) || // Aiming up or down
                             (isOutside && Vector3.Dot(originToCenter2D, localRay2D.direction) < 0) || // Aiming away
                             (!isOutside && effectiveFacing == NormalFacing.Out); // Origin inside with normals out
            if (hasMissed)
            {
                return false;
            }
            float projToWall = Mathf.Sqrt(Mathf.Pow(Radius, 2) - Mathf.Pow(magProj, 2));
            float tOuter = Vector3.Distance(localRay2D.origin, projPoint2D - localRay2D.direction * projToWall) / magDir2D;
            float tInner = Vector3.Distance(localRay2D.origin, projPoint2D + localRay2D.direction * projToWall) / magDir2D;
            Vector3 localHitpointOuter = localRay3D.GetPoint(tOuter);
            Vector3 localHitpointInner = localRay3D.GetPoint(tInner);
            bool hasOuter = (maxDistance <= 0 || TransformScale(tOuter) <= maxDistance) &&
                            (_height <= 0 || Mathf.Abs(localHitpointOuter.y) <= _height / 2f);
            bool hasInner = (maxDistance <= 0 || TransformScale(tInner) <= maxDistance) &&
                            (_height <= 0 || Mathf.Abs(localHitpointInner.y) <= _height / 2f);
            if (effectiveFacing != NormalFacing.In && hasOuter)
            {
                hit.Point = _cylinder.transform.TransformPoint(localHitpointOuter);
                hit.Normal = _cylinder.transform.TransformDirection(CancelY(localHitpointOuter).normalized);
                hit.Distance = TransformScale(tOuter);
            }
            else if (hasInner)
            {
                hit.Point = _cylinder.transform.TransformPoint(localHitpointInner);
                hit.Normal = _cylinder.transform.TransformDirection(CancelY(-localHitpointInner).normalized);
                hit.Distance = TransformScale(tInner);
            }
            else
            {
                return false;
            }
            return true;
        }
References Oculus.Interaction.Surfaces.CylinderSurface.CancelY(), and Oculus.Interaction.Surfaces.CylinderSurface.TransformScale().
Start()
virtual void Oculus.Interaction.Surfaces.CylinderSurface.Start () protected virtual
Definition at line 98 of file CylinderSurface.cs.
        {
            this.BeginStart(ref _started);
            this.AssertField(Cylinder, nameof(Cylinder));
            this.EndStart(ref _started);
        }
TransformScale()
float Oculus.Interaction.Surfaces.CylinderSurface.TransformScale (float val) private
Local to world transformation of a float, assuming uniform scale.
Definition at line 231 of file CylinderSurface.cs.
        {
            return val * _cylinder.transform.lossyScale.x;
        }
Member Data Documentation
_cylinder
Cylinder Oculus.Interaction.Surfaces.CylinderSurface._cylinder private
Definition at line 50 of file CylinderSurface.cs.
_facing
NormalFacing Oculus.Interaction.Surfaces.CylinderSurface._facing = NormalFacing.Out private
Definition at line 56 of file CylinderSurface.cs.
_height
float Oculus.Interaction.Surfaces.CylinderSurface._height = 1f private
Definition at line 61 of file CylinderSurface.cs.
_started
bool Oculus.Interaction.Surfaces.CylinderSurface._started = false protected
Definition at line 96 of file CylinderSurface.cs.
Property Documentation
Bounds
Bounds Oculus.Interaction.Surfaces.CylinderSurface.Bounds get
The world space axis-aligned bounding box (AABB)
Implements Oculus.Interaction.Surfaces.IBounds.
Definition at line 72 of file CylinderSurface.cs.
        {
            get
            {
                float maxScale = Mathf.Max(Transform.lossyScale.x,
                    Mathf.Max(Transform.lossyScale.y, Transform.lossyScale.z));
                float maxSize = maxScale * (Height + Radius);
                return new Bounds(Transform.position,
                    new Vector3(maxSize, maxSize, maxSize));
            }
        }
Cylinder
Cylinder Oculus.Interaction.Surfaces.CylinderSurface.Cylinder get
Definition at line 67 of file CylinderSurface.cs.
Facing
NormalFacing Oculus.Interaction.Surfaces.CylinderSurface.Facing get set
Definition at line 84 of file CylinderSurface.cs.
        {
            get => _facing;
            set => _facing = value;
        }
Height
float Oculus.Interaction.Surfaces.CylinderSurface.Height get set
Definition at line 90 of file CylinderSurface.cs.
        {
            get => _height;
            set => _height = value;
        }
IsValid
bool Oculus.Interaction.Surfaces.CylinderSurface.IsValid get
Definition at line 63 of file CylinderSurface.cs.
Radius
float Oculus.Interaction.Surfaces.CylinderSurface.Radius get
Definition at line 65 of file CylinderSurface.cs.
Transform
Transform Oculus.Interaction.Surfaces.CylinderSurface.Transform get
A transform for the surface.
Implements Oculus.Interaction.Surfaces.ISurface.
Definition at line 69 of file CylinderSurface.cs.
The documentation for this class was generated from the following file:
Assets/Oculus/Interaction/Runtime/Scripts/Interaction/Surfaces/CylinderSurface.cs