VR_Test: GroupPresenceSample Class Reference
GroupPresenceSample Class Reference
Public Attributes
bool IsJoinable = true
string LobbySessionID
string MatchSessionID
UInt64 SuggestedUserID
Text InVRConsole
Text DestinationsConsole
Private Member Functions
void Start ()
void SetPresence ()
void ClearPresence ()
void LaunchInvitePanel ()
void LaunchRosterPanel ()
void OnJoinIntentChangeNotif (Message< Oculus.Platform.Models.GroupPresenceJoinIntent > message)
void OnLeaveIntentChangeNotif (Message< Oculus.Platform.Models.GroupPresenceLeaveIntent > message)
void OnInviteSentNotif (Message< Oculus.Platform.Models.LaunchInvitePanelFlowResult > message)
void OnGetDestinations (Message< Oculus.Platform.Models.DestinationList > message)
void Update ()
void ScrollThroughDestinations ()
void UpdateDestinationsConsole ()
void OnLoggedInUser (Message< Oculus.Platform.Models.User > message)
void UpdateConsole (string value)
bool PressAButton ()
bool PressBButton ()
bool PressXButton ()
bool PressYButton ()
bool PressUp ()
bool PressDown ()
Private Attributes
List< string > DestinationAPINames = new List<string>()
ulong LoggedInUserID = 0
int DestinationIndex = 0
bool OnlyPushUpOnce = false
Detailed Description
This class shows a very simple way to integrate setting the Group Presence with a destination and how to respond to a user's app launch details that include the destination they wish to travel to.
Definition at line 15 of file GroupPresenceSample.cs.
Member Function Documentation
ClearPresence()
void GroupPresenceSample.ClearPresence () private
Clearing the rich presence
Definition at line 134 of file GroupPresenceSample.cs.
  {
    UpdateConsole("Clearing Group Presence...");
    GroupPresence.Clear().OnComplete(message => {
      if (message.IsError)
      {
        UpdateConsole(message.GetError().Message);
      }
      else
      {
        // Clearing the rich presence then fetching the user's presence afterwards
        Users.Get(LoggedInUserID).OnComplete(message2 =>
        {
          if (message2.IsError)
          {
            UpdateConsole("Group Presence cleared! But rich presence is unknown!");
          }
          else
          {
            UpdateConsole("Group Presence cleared!\n" + message2.Data.Presence + "\n");
          }
        });
      }
    });
  }
References Oculus.Platform.GroupPresence.Clear().
LaunchInvitePanel()
void GroupPresenceSample.LaunchInvitePanel () private
Launch the invite panel
Definition at line 163 of file GroupPresenceSample.cs.
  {
    UpdateConsole("Launching Invite Panel...");
    var options = new InviteOptions();
    if (SuggestedUserID != 0)
    {
      options.AddSuggestedUser(SuggestedUserID);
    }
    GroupPresence.LaunchInvitePanel(options).OnComplete(message =>
    {
      if (message.IsError)
      {
        UpdateConsole(message.GetError().Message);
      }
    });
  }
References Oculus.Platform.GroupPresence.LaunchInvitePanel().
LaunchRosterPanel()
void GroupPresenceSample.LaunchRosterPanel () private
Launch the roster panel
Definition at line 183 of file GroupPresenceSample.cs.
  {
    UpdateConsole("Launching Roster Panel...");
    var options = new RosterOptions();
    if (SuggestedUserID != 0)
    {
      options.AddSuggestedUser(SuggestedUserID);
    }
    GroupPresence.LaunchRosterPanel(options).OnComplete(message =>
    {
      if (message.IsError)
      {
        UpdateConsole(message.GetError().Message);
      }
    });
  }
References Oculus.Platform.GroupPresence.LaunchRosterPanel().
OnGetDestinations()
void GroupPresenceSample.OnGetDestinations (Message< Oculus::Platform::Models::DestinationList > message) private
Definition at line 294 of file GroupPresenceSample.cs.
  {
    if (message.IsError)
    {
      UpdateConsole("Could not get the list of destinations!");
    }
    else
    {
      foreach(Oculus.Platform.Models.Destination destination in message.Data)
      {
        DestinationAPINames.Add(destination.ApiName);
        UpdateDestinationsConsole();
      }
    }
  }
OnInviteSentNotif()
void GroupPresenceSample.OnInviteSentNotif (Message< Oculus::Platform::Models::LaunchInvitePanelFlowResult > message) private
Definition at line 268 of file GroupPresenceSample.cs.
  {
    if (message.IsError)
    {
      UpdateConsole(message.GetError().Message);
    } else
    {
      var users = message.Data.InvitedUsers;
      var usersCount = users.Count;
      var usersInvitedString = "-Users:\n";
      if (usersCount > 0)
      {
        foreach(var user in users)
        {
          usersInvitedString += user.OculusID + "\n";
        }
      } else
      {
        usersInvitedString += "none\n";
      }
      UpdateConsole("Users sent invite to:\n" + usersInvitedString);
    }
  }
OnJoinIntentChangeNotif()
void GroupPresenceSample.OnJoinIntentChangeNotif (Message< Oculus::Platform::Models::GroupPresenceJoinIntent > message) private
Definition at line 201 of file GroupPresenceSample.cs.
  {
    if (message.IsError)
    {
      UpdateConsole(message.GetError().Message);
    } else
    {
      var joinIntent = message.Data;
      // The deeplink message, this should give enough info on how to go the
      // destination in the app.
      var deeplinkMessage = joinIntent.DeeplinkMessage;
      // The API Name of the destination. You can set the user to this after
      // navigating to the app
      var destinationApiName = joinIntent.DestinationApiName;
      var matchSessionID = joinIntent.MatchSessionId;
      var lobbySessionID = joinIntent.LobbySessionId;
      var detailsString = "-Deeplink Message:\n" + deeplinkMessage + "\n-Api Name:\n" + destinationApiName + "\n-Lobby Session Id:\n" + lobbySessionID + "\n-Match Session Id:\n" + matchSessionID;
      detailsString += "\n";
      UpdateConsole("Got updated Join Intent & setting the user's presence:\n" + detailsString);
      var options = new GroupPresenceOptions();
      if (!string.IsNullOrEmpty(destinationApiName))
      {
        options.SetDestinationApiName(destinationApiName);
      }
      if (!string.IsNullOrEmpty(matchSessionID))
      {
        options.SetMatchSessionId(matchSessionID);
      }
      if (!string.IsNullOrEmpty(lobbySessionID))
      {
        options.SetLobbySessionId(lobbySessionID);
      }
      GroupPresence.Set(options);
    }
  }
OnLeaveIntentChangeNotif()
void GroupPresenceSample.OnLeaveIntentChangeNotif (Message< Oculus::Platform::Models::GroupPresenceLeaveIntent > message) private
Definition at line 245 of file GroupPresenceSample.cs.
  {
    if (message.IsError)
    {
      UpdateConsole(message.GetError().Message);
    } else
    {
      var leaveIntent = message.Data;
      var destinationApiName = leaveIntent.DestinationApiName;
      MatchSessionID = leaveIntent.MatchSessionId;
      LobbySessionID = leaveIntent.LobbySessionId;
      var detailsString = "-Api Name:\n" + destinationApiName + "\n-Lobby Session Id:\n" + LobbySessionID + "\n-Match Session Id:\n" + MatchSessionID;
      detailsString += "\n";
      UpdateConsole("Clearing presence because user wishes to leave:\n" + detailsString);
      // User left
      GroupPresence.Clear();
    }
  }
OnLoggedInUser()
void GroupPresenceSample.OnLoggedInUser (Message< Oculus::Platform::Models::User > message) private
Definition at line 397 of file GroupPresenceSample.cs.
  {
    if (message.IsError)
    {
      Debug.LogError("Cannot get logged in user");
    }
    else
    {
      LoggedInUserID = message.Data.ID;
    }
  }
PressAButton()
bool GroupPresenceSample.PressAButton () private
Definition at line 420 of file GroupPresenceSample.cs.
  {
#if USE_OVRINPUT
    return OVRInput.GetUp(OVRInput.Button.One) || Input.GetKeyUp(KeyCode.A);
#else
    return Input.GetKeyUp(KeyCode.A);
#endif
  }
PressBButton()
bool GroupPresenceSample.PressBButton () private
Definition at line 429 of file GroupPresenceSample.cs.
  {
#if USE_OVRINPUT
    return OVRInput.GetUp(OVRInput.Button.Two) || Input.GetKeyUp(KeyCode.B);
#else
    return Input.GetKeyUp(KeyCode.B);
#endif
  }
PressDown()
bool GroupPresenceSample.PressDown () private
Definition at line 466 of file GroupPresenceSample.cs.
  {
#if USE_OVRINPUT
    Vector2 axis = OVRInput.Get(OVRInput.Axis2D.SecondaryThumbstick);
    return (axis.y < -0.2 || Input.GetKeyUp(KeyCode.DownArrow));
#else
    return Input.GetKeyUp(KeyCode.DownArrow);
#endif
  }
PressUp()
bool GroupPresenceSample.PressUp () private
Definition at line 456 of file GroupPresenceSample.cs.
  {
#if USE_OVRINPUT
    Vector2 axis = OVRInput.Get(OVRInput.Axis2D.SecondaryThumbstick);
    return (axis.y > 0.2 || Input.GetKeyUp(KeyCode.UpArrow));
#else
    return Input.GetKeyUp(KeyCode.UpArrow);
#endif
  }
PressXButton()
bool GroupPresenceSample.PressXButton () private
Definition at line 438 of file GroupPresenceSample.cs.
  {
#if USE_OVRINPUT
    return OVRInput.GetUp(OVRInput.Button.Three) || Input.GetKeyUp(KeyCode.X);
#else
    return Input.GetKeyUp(KeyCode.X);
#endif
  }
PressYButton()
bool GroupPresenceSample.PressYButton () private
Definition at line 447 of file GroupPresenceSample.cs.
  {
#if USE_OVRINPUT
    return OVRInput.GetUp(OVRInput.Button.Four) || Input.GetKeyUp(KeyCode.Y);
#else
    return Input.GetKeyUp(KeyCode.Y);
#endif
  }
ScrollThroughDestinations()
void GroupPresenceSample.ScrollThroughDestinations () private
Definition at line 345 of file GroupPresenceSample.cs.
  {
    if (PressUp())
    {
      if (!OnlyPushUpOnce)
      {
        DestinationIndex--;
        if (DestinationIndex < 0)
        {
          DestinationIndex = DestinationAPINames.Count - 1;
        }
        OnlyPushUpOnce = true;
        UpdateDestinationsConsole();
      }
    }
    else if (PressDown())
    {
      if (!OnlyPushUpOnce)
      {
        DestinationIndex++;
        if (DestinationIndex >= DestinationAPINames.Count)
        {
          DestinationIndex = 0;
        }
        OnlyPushUpOnce = true;
        UpdateDestinationsConsole();
      }
    }
    else
    {
      OnlyPushUpOnce = false;
    }
  }
SetPresence()
void GroupPresenceSample.SetPresence () private
Setting the group presence
Definition at line 85 of file GroupPresenceSample.cs.
  {
    var options = new GroupPresenceOptions();
    options.SetDestinationApiName(DestinationAPINames[DestinationIndex]);
    if (!string.IsNullOrEmpty(MatchSessionID))
    {
      options.SetMatchSessionId(MatchSessionID);
    }
    if (!string.IsNullOrEmpty(LobbySessionID))
    {
      options.SetLobbySessionId(LobbySessionID);
    }
    // Set is Joinable to let other players deeplink and join this user via the presence
    options.SetIsJoinable(IsJoinable);
    UpdateConsole("Setting Group Presence to " + DestinationAPINames[DestinationIndex] + " ...");
    // Here we are setting the group presence then fetching it after we successfully set it
    GroupPresence.Set(options).OnComplete(message => {
      if (message.IsError)
      {
        UpdateConsole(message.GetError().Message);
      }
      else
      {
        // Note that Users.GetLoggedInUser() does not do a server fetch and will
        // not get an updated presence status
        Users.Get(LoggedInUserID).OnComplete(message2 =>
        {
          if (message2.IsError)
          {
            UpdateConsole("Success! But presence is unknown!");
          }
          else
          {
            UpdateConsole("Group Presence set to:\n" + message2.Data.Presence + "\n" + message2.Data.PresenceDeeplinkMessage + "\n" + message2.Data.PresenceDestinationApiName);
          }
        });
      }
    });
  }
References IsJoinable, and Oculus.Platform.GroupPresence.Set().
Start()
void GroupPresenceSample.Start () private
Get and cache the Logged in User ID for future queries
Get the list of destinations defined for this app from the developer portal
Listen for future join intents that might come in
Listen for future leave that might come in
Listen for the list of users that the current users have invitted
Definition at line 41 of file GroupPresenceSample.cs.
  {
    UpdateConsole("Init Oculus Platform SDK...");
    Core.AsyncInitialize().OnComplete(message => {
      if (message.IsError)
      {
        // Init failed, nothing will work
        UpdateConsole(message.GetError().Message);
      }
      else
      {
        UpdateConsole("Init complete!");
        Users.GetLoggedInUser().OnComplete(OnLoggedInUser);
        RichPresence.GetDestinations().OnComplete(OnGetDestinations);
        GroupPresence.SetJoinIntentReceivedNotificationCallback(OnJoinIntentChangeNotif);
        GroupPresence.SetLeaveIntentReceivedNotificationCallback(OnLeaveIntentChangeNotif);
        GroupPresence.SetInvitationsSentNotificationCallback(OnInviteSentNotif);
      }
    });
  }
Update()
void GroupPresenceSample.Update () private
Definition at line 315 of file GroupPresenceSample.cs.
  {
    if (PressAButton())
    {
      if (DestinationAPINames.Count > 0)
      {
        SetPresence();
      }
      else
      {
        UpdateConsole("No destinations to set to!");
        return;
      }
    }
    else if (PressBButton())
    {
      ClearPresence();
    }
    else if (PressXButton())
    {
      LaunchInvitePanel();
    }
    else if (PressYButton())
    {
      LaunchRosterPanel();
    }
    ScrollThroughDestinations();
  }
UpdateConsole()
void GroupPresenceSample.UpdateConsole (string value) private
Definition at line 409 of file GroupPresenceSample.cs.
  {
    Debug.Log(value);
    InVRConsole.text =
      "Scroll Up/Down on Right Thumbstick\n(A) - Set Group Presence to selected\n(B) - Clear Group Presence\n(X) - Launch Invite Panel\n(Y) - Launch Roster Panel\n\n" + value;
  }
UpdateDestinationsConsole()
void GroupPresenceSample.UpdateDestinationsConsole () private
Definition at line 379 of file GroupPresenceSample.cs.
  {
    if (DestinationAPINames.Count == 0)
    {
      DestinationsConsole.text = "Add some destinations to the developer dashboard first!";
    }
    string destinations = "Destination API Names:\n";
    for (int i = 0; i < DestinationAPINames.Count; i++)
    {
      if (i == DestinationIndex)
      {
        destinations += "==>";
      }
      destinations += DestinationAPINames[i] + "\n";
    }
    DestinationsConsole.text = destinations;
  }
Member Data Documentation
DestinationAPINames
List<string> GroupPresenceSample.DestinationAPINames = new List<string>() private
Definition at line 37 of file GroupPresenceSample.cs.
DestinationIndex
int GroupPresenceSample.DestinationIndex = 0 private
Definition at line 312 of file GroupPresenceSample.cs.
DestinationsConsole
Text GroupPresenceSample.DestinationsConsole
Definition at line 35 of file GroupPresenceSample.cs.
InVRConsole
Text GroupPresenceSample.InVRConsole
Definition at line 34 of file GroupPresenceSample.cs.
IsJoinable
bool GroupPresenceSample.IsJoinable = true
Sets extra fields on the rich presence
Definition at line 24 of file GroupPresenceSample.cs.
LobbySessionID
string GroupPresenceSample.LobbySessionID
Definition at line 28 of file GroupPresenceSample.cs.
LoggedInUserID
ulong GroupPresenceSample.LoggedInUserID = 0 private
Definition at line 38 of file GroupPresenceSample.cs.
MatchSessionID
string GroupPresenceSample.MatchSessionID
Definition at line 29 of file GroupPresenceSample.cs.
OnlyPushUpOnce
bool GroupPresenceSample.OnlyPushUpOnce = false private
Definition at line 313 of file GroupPresenceSample.cs.
SuggestedUserID
UInt64 GroupPresenceSample.SuggestedUserID
Definition at line 32 of file GroupPresenceSample.cs.
The documentation for this class was generated from the following file:
Assets/Oculus/Platform/Samples/GroupPresenceSample/Scripts/GroupPresenceSample.cs