VR_Test: OVRSceneSampleController Class Reference
OVRSceneSampleController Class Reference
Sample that allows you to play with various VR settings.
Public Attributes
KeyCode quitKey = KeyCode.Escape
The key that quits the application.
Texture fadeInTexture = null
An optional texture that appears before the menu fades in.
float speedRotationIncrement = 0.05f
Controls how quickly the player's speed and rotation change based on input.
string layerName = "Default"
We can set the layer to be anything we want to, this allows a specific camera to render it.
Private Member Functions
void Awake ()
Awake this instance.
void Start ()
Start this instance.
void Update ()
Update this instance.
void UpdateVisionMode ()
Updates the vision mode.
void UpdateSpeedAndRotationScaleMultiplier ()
Updates the speed and rotation scale multiplier.
void UpdateRecenterPose ()
Recenter pose.
Private Attributes
OVRPlayerController playerController = null
OVRCameraRig cameraController = null
bool visionMode = true
OVRGridCube gridCube = null
Detailed Description
Sample that allows you to play with various VR settings.
Definition at line 27 of file OVRSceneSampleController.cs.
Member Function Documentation
Awake()
void OVRSceneSampleController.Awake () private
Awake this instance.
Definition at line 71 of file OVRSceneSampleController.cs.
    {
        // Find camera controller
        OVRCameraRig[] cameraControllers;
        cameraControllers = gameObject.GetComponentsInChildren<OVRCameraRig>();
        if (cameraControllers.Length == 0)
        {
            Debug.LogWarning("OVRMainMenu: No OVRCameraRig attached.");
        }
        else if (cameraControllers.Length > 1)
        {
            Debug.LogWarning("OVRMainMenu: More then 1 OVRCameraRig attached.");
        }
        else
        {
            cameraController = cameraControllers[0];
        }
        // Find player controller
        OVRPlayerController[] playerControllers;
        playerControllers = gameObject.GetComponentsInChildren<OVRPlayerController>();
        if (playerControllers.Length == 0)
        {
            Debug.LogWarning("OVRMainMenu: No OVRPlayerController attached.");
        }
        else if (playerControllers.Length > 1)
        {
            Debug.LogWarning("OVRMainMenu: More then 1 OVRPlayerController attached.");
        }
        else
        {
            playerController = playerControllers[0];
        }
    }
Start()
void OVRSceneSampleController.Start () private
Start this instance.
Definition at line 111 of file OVRSceneSampleController.cs.
    {
        // Make sure to hide cursor
        if (Application.isEditor == false)
        {
            Cursor.visible = false;
            Cursor.lockState = CursorLockMode.Locked;
        }
        // CameraController updates
        if (cameraController != null)
        {
            // Add a GridCube component to this object
            gridCube = gameObject.AddComponent<OVRGridCube>();
            gridCube.SetOVRCameraController(ref cameraController);
        }
    }
References OVRGridCube.SetOVRCameraController().
Update()
void OVRSceneSampleController.Update () private
Update this instance.
Definition at line 133 of file OVRSceneSampleController.cs.
    {
        // Recenter pose
        UpdateRecenterPose();
        // Turn On/Off Vision Mode
        UpdateVisionMode();
        // Update Speed and Rotation Scale
        if (playerController != null)
            UpdateSpeedAndRotationScaleMultiplier();
        //todo: enable for Unity Input System
#if ENABLE_LEGACY_INPUT_MANAGER
        // Toggle Fullscreen
        if (Input.GetKeyDown(KeyCode.F11))
            Screen.fullScreen = !Screen.fullScreen;
        if (Input.GetKeyDown(KeyCode.M))
            UnityEngine.XR.XRSettings.showDeviceView = !UnityEngine.XR.XRSettings.showDeviceView;
#if !UNITY_ANDROID || UNITY_EDITOR
        // Escape Application
        if (Input.GetKeyDown(quitKey))
            Application.Quit();
#endif
#endif
    }
References quitKey, UpdateRecenterPose(), UpdateSpeedAndRotationScaleMultiplier(), and UpdateVisionMode().
UpdateRecenterPose()
void OVRSceneSampleController.UpdateRecenterPose () private
Recenter pose.
Definition at line 222 of file OVRSceneSampleController.cs.
    {
        //todo: enable for Unity Input System
#if ENABLE_LEGACY_INPUT_MANAGER
        if (Input.GetKeyDown(KeyCode.R))
            OVRManager.display.RecenterPose();
#endif
    }
References OVRManager.display, and OVRDisplay.RecenterPose().
UpdateSpeedAndRotationScaleMultiplier()
void OVRSceneSampleController.UpdateSpeedAndRotationScaleMultiplier () private
Updates the speed and rotation scale multiplier.
Definition at line 182 of file OVRSceneSampleController.cs.
    {
        float moveScaleMultiplier = 0.0f;
        playerController.GetMoveScaleMultiplier(ref moveScaleMultiplier);
        //todo: enable for Unity Input System
#if ENABLE_LEGACY_INPUT_MANAGER
        if (Input.GetKeyDown(KeyCode.Alpha7))
        {
            moveScaleMultiplier -= speedRotationIncrement;
        }
        else if (Input.GetKeyDown(KeyCode.Alpha8))
        {
            moveScaleMultiplier += speedRotationIncrement;
        }
#endif
        playerController.SetMoveScaleMultiplier(moveScaleMultiplier);
        float rotationScaleMultiplier = 0.0f;
        playerController.GetRotationScaleMultiplier(ref rotationScaleMultiplier);
        //todo: enable for Unity Input System
#if ENABLE_LEGACY_INPUT_MANAGER
        if (Input.GetKeyDown(KeyCode.Alpha9))
        {
            rotationScaleMultiplier -= speedRotationIncrement;
        }
        else if (Input.GetKeyDown(KeyCode.Alpha0))
        {
            rotationScaleMultiplier += speedRotationIncrement;
        }
#endif
        playerController.SetRotationScaleMultiplier(rotationScaleMultiplier);
    }
References OVRPlayerController.GetMoveScaleMultiplier(), OVRPlayerController.GetRotationScaleMultiplier(), OVRPlayerController.SetMoveScaleMultiplier(), OVRPlayerController.SetRotationScaleMultiplier(), and speedRotationIncrement.
UpdateVisionMode()
void OVRSceneSampleController.UpdateVisionMode () private
Updates the vision mode.
Definition at line 167 of file OVRSceneSampleController.cs.
    {
        //todo: enable for Unity Input System
#if ENABLE_LEGACY_INPUT_MANAGER
        if (Input.GetKeyDown(KeyCode.F2))
        {
            visionMode ^= visionMode;
            OVRManager.tracker.isEnabled = visionMode;
        }
#endif
    }
Member Data Documentation
cameraController
OVRCameraRig OVRSceneSampleController.cameraController = null private
Definition at line 47 of file OVRSceneSampleController.cs.
fadeInTexture
Texture OVRSceneSampleController.fadeInTexture = null
An optional texture that appears before the menu fades in.
Definition at line 37 of file OVRSceneSampleController.cs.
gridCube
OVRGridCube OVRSceneSampleController.gridCube = null private
Definition at line 60 of file OVRSceneSampleController.cs.
layerName
string OVRSceneSampleController.layerName = "Default"
We can set the layer to be anything we want to, this allows a specific camera to render it.
Definition at line 53 of file OVRSceneSampleController.cs.
playerController
OVRPlayerController OVRSceneSampleController.playerController = null private
Definition at line 44 of file OVRSceneSampleController.cs.
quitKey
KeyCode OVRSceneSampleController.quitKey = KeyCode.Escape
The key that quits the application.
Definition at line 32 of file OVRSceneSampleController.cs.
speedRotationIncrement
float OVRSceneSampleController.speedRotationIncrement = 0.05f
Controls how quickly the player's speed and rotation change based on input.
Definition at line 42 of file OVRSceneSampleController.cs.
visionMode
bool OVRSceneSampleController.visionMode = true private
Definition at line 56 of file OVRSceneSampleController.cs.
The documentation for this class was generated from the following file:
Assets/Oculus/VR/Scripts/Util/OVRSceneSampleController.cs