VR_Test: OculusSampleFramework.InteractableToolsInputRouter Class Reference
OculusSampleFramework.InteractableToolsInputRouter Class Reference
Routes all collisions from interactable tools to the interactables themselves. We want to do this in a top-down fashion, because we might want to disable far-field interactions if near-field interactions take precendence (for instance).
Public Member Functions
void RegisterInteractableTool (InteractableTool interactableTool)
void UnregisterInteractableTool (InteractableTool interactableTool)
Properties
static InteractableToolsInputRouter Instance [get]
Private Member Functions
void Update ()
bool UpdateToolsAndEnableState (HashSet< InteractableTool > tools, bool toolsAreEnabledThisFrame)
bool UpdateTools (HashSet< InteractableTool > tools, bool resetCollisionData=false)
Update tools specified based on new collisions.
void ToggleToolsEnableState (HashSet< InteractableTool > tools, bool enableState)
Private Attributes
bool _leftPinch
bool _rightPinch
HashSet< InteractableTool > _leftHandNearTools = new HashSet<InteractableTool>()
HashSet< InteractableTool > _leftHandFarTools = new HashSet<InteractableTool>()
HashSet< InteractableTool > _rightHandNearTools = new HashSet<InteractableTool>()
HashSet< InteractableTool > _rightHandFarTools = new HashSet<InteractableTool>()
Static Private Attributes
static InteractableToolsInputRouter _instance
Detailed Description
Routes all collisions from interactable tools to the interactables themselves. We want to do this in a top-down fashion, because we might want to disable far-field interactions if near-field interactions take precendence (for instance).
Definition at line 32 of file InteractableToolsInputRouter.cs.
Member Function Documentation
RegisterInteractableTool()
void OculusSampleFramework.InteractableToolsInputRouter.RegisterInteractableTool (InteractableTool interactableTool)
Definition at line 64 of file InteractableToolsInputRouter.cs.
        {
            if (interactableTool.IsRightHandedTool)
            {
                if (interactableTool.IsFarFieldTool)
                {
                    _rightHandFarTools.Add(interactableTool);
                }
                else
                {
                    _rightHandNearTools.Add(interactableTool);
                }
            }
            else
            {
                if (interactableTool.IsFarFieldTool)
                {
                    _leftHandFarTools.Add(interactableTool);
                }
                else
                {
                    _leftHandNearTools.Add(interactableTool);
                }
            }
        }
ToggleToolsEnableState()
void OculusSampleFramework.InteractableToolsInputRouter.ToggleToolsEnableState (HashSet< InteractableTool > tools, bool enableState) private
Definition at line 207 of file InteractableToolsInputRouter.cs.
        {
            foreach (InteractableTool tool in tools)
            {
                if (tool.EnableState != enableState)
                {
                    tool.EnableState = enableState;
                }
            }
        }
UnregisterInteractableTool()
void OculusSampleFramework.InteractableToolsInputRouter.UnregisterInteractableTool (InteractableTool interactableTool)
Definition at line 90 of file InteractableToolsInputRouter.cs.
        {
            if (interactableTool.IsRightHandedTool)
            {
                if (interactableTool.IsFarFieldTool)
                {
                    _rightHandFarTools.Remove(interactableTool);
                }
                else
                {
                    _rightHandNearTools.Remove(interactableTool);
                }
            }
            else
            {
                if (interactableTool.IsFarFieldTool)
                {
                    _leftHandFarTools.Remove(interactableTool);
                }
                else
                {
                    _leftHandNearTools.Remove(interactableTool);
                }
            }
        }
Update()
void OculusSampleFramework.InteractableToolsInputRouter.Update () private
Definition at line 116 of file InteractableToolsInputRouter.cs.
        {
            if (!HandsManager.Instance.IsInitialized())
            {
                return;
            }
            bool leftHandIsReliable = HandsManager.Instance.LeftHand.IsTracked &&
                                      HandsManager.Instance.LeftHand.HandConfidence == OVRHand.TrackingConfidence.High;
            bool rightHandIsReliable = HandsManager.Instance.RightHand.IsTracked &&
                                       HandsManager.Instance.RightHand.HandConfidence ==
                                       OVRHand.TrackingConfidence.High;
            bool leftHandProperlyTracked = HandsManager.Instance.LeftHand.IsPointerPoseValid;
            bool rightHandProperlyTracked = HandsManager.Instance.RightHand.IsPointerPoseValid;
            bool encounteredNearObjectsLeftHand = UpdateToolsAndEnableState(_leftHandNearTools, leftHandIsReliable);
            // don't interact with far field if near field is touching something
            UpdateToolsAndEnableState(_leftHandFarTools, !encounteredNearObjectsLeftHand && leftHandIsReliable &&
                                                         leftHandProperlyTracked);
            bool encounteredNearObjectsRightHand = UpdateToolsAndEnableState(_rightHandNearTools, rightHandIsReliable);
            // don't interact with far field if near field is touching something
            UpdateToolsAndEnableState(_rightHandFarTools, !encounteredNearObjectsRightHand && rightHandIsReliable &&
                                                          rightHandProperlyTracked);
        }
UpdateTools()
bool OculusSampleFramework.InteractableToolsInputRouter.UpdateTools (HashSet< InteractableTool > tools, bool resetCollisionData = false) private
Update tools specified based on new collisions.
Parameters
tools Tools to update.
resetCollisionData True if we want the tool to be disabled. This can happen if near field tools take precedence over far-field tools, for instance.
Returns
Definition at line 156 of file InteractableToolsInputRouter.cs.
        {
            bool toolsEncounteredObjects = false;
            foreach (InteractableTool currentInteractableTool in tools)
            {
                List<InteractableCollisionInfo> intersectingObjectsFound =
                    currentInteractableTool.GetNextIntersectingObjects();
                if (intersectingObjectsFound.Count > 0 && !resetCollisionData)
                {
                    if (!toolsEncounteredObjects)
                    {
                        toolsEncounteredObjects = intersectingObjectsFound.Count > 0;
                    }
                    // create map that indicates the furthest collider encountered per interactable element
                    currentInteractableTool.UpdateCurrentCollisionsBasedOnDepth();
                    if (currentInteractableTool.IsFarFieldTool)
                    {
                        var firstInteractable = currentInteractableTool.GetFirstCurrentCollisionInfo();
                        // if our tool is activated, make sure depth is set to "action"
                        if (currentInteractableTool.ToolInputState == ToolInputState.PrimaryInputUp)
{
                            firstInteractable.Value.InteractableCollider = firstInteractable.Key.ActionCollider;
                            firstInteractable.Value.CollisionDepth = InteractableCollisionDepth.Action;
                        }
                        else
{
                            firstInteractable.Value.InteractableCollider = firstInteractable.Key.ContactCollider;
                            firstInteractable.Value.CollisionDepth = InteractableCollisionDepth.Contact;
                        }
                        // far field tools only can focus elements -- pick first (for now)
                        currentInteractableTool.FocusOnInteractable(firstInteractable.Key,
                            firstInteractable.Value.InteractableCollider);
                    }
                }
                else
                {
                    currentInteractableTool.DeFocus();
                    currentInteractableTool.ClearAllCurrentCollisionInfos();
                }
                currentInteractableTool.UpdateLatestCollisionData();
            }
            return toolsEncounteredObjects;
        }
References OculusSampleFramework.InteractableTool.FocusOnInteractable(), OculusSampleFramework.InteractableTool.UpdateCurrentCollisionsBasedOnDepth(), and OculusSampleFramework.InteractableTool.UpdateLatestCollisionData().
UpdateToolsAndEnableState()
bool OculusSampleFramework.InteractableToolsInputRouter.UpdateToolsAndEnableState (HashSet< InteractableTool > tools, bool toolsAreEnabledThisFrame) private
Definition at line 142 of file InteractableToolsInputRouter.cs.
        {
            bool encounteredObjects = UpdateTools(tools, resetCollisionData: !toolsAreEnabledThisFrame);
            ToggleToolsEnableState(tools, toolsAreEnabledThisFrame);
            return encounteredObjects;
        }
Member Data Documentation
_instance
InteractableToolsInputRouter OculusSampleFramework.InteractableToolsInputRouter._instance static private
Definition at line 34 of file InteractableToolsInputRouter.cs.
_leftHandFarTools
HashSet<InteractableTool> OculusSampleFramework.InteractableToolsInputRouter._leftHandFarTools = new HashSet<InteractableTool>() private
Definition at line 60 of file InteractableToolsInputRouter.cs.
_leftHandNearTools
HashSet<InteractableTool> OculusSampleFramework.InteractableToolsInputRouter._leftHandNearTools = new HashSet<InteractableTool>() private
Definition at line 59 of file InteractableToolsInputRouter.cs.
_leftPinch
bool OculusSampleFramework.InteractableToolsInputRouter._leftPinch private
Definition at line 35 of file InteractableToolsInputRouter.cs.
_rightHandFarTools
HashSet<InteractableTool> OculusSampleFramework.InteractableToolsInputRouter._rightHandFarTools = new HashSet<InteractableTool>() private
Definition at line 62 of file InteractableToolsInputRouter.cs.
_rightHandNearTools
HashSet<InteractableTool> OculusSampleFramework.InteractableToolsInputRouter._rightHandNearTools = new HashSet<InteractableTool>() private
Definition at line 61 of file InteractableToolsInputRouter.cs.
_rightPinch
bool OculusSampleFramework.InteractableToolsInputRouter._rightPinch private
Definition at line 35 of file InteractableToolsInputRouter.cs.
Property Documentation
Instance
InteractableToolsInputRouter OculusSampleFramework.InteractableToolsInputRouter.Instance static get
Definition at line 37 of file InteractableToolsInputRouter.cs.
        {
            get
            {
                if (_instance == null)
                {
                    var instances = FindObjectsOfType<InteractableToolsInputRouter>();
                    if (instances.Length > 0)
                    {
                        _instance = instances[0];
                        // remove extras, if any
                        for (int i = 1; i < instances.Length; i++)
{
                            GameObject.Destroy(instances[i].gameObject);
                        }
                    }
                }
                return _instance;
            }
        }
The documentation for this class was generated from the following file:
Assets/Oculus/SampleFramework/Core/HandsInteraction/Scripts/InteractableToolsInputRouter.cs