VR_Test: OVRHaptics.OVRHapticsChannel Class Reference
OVRHaptics.OVRHapticsChannel Class Reference
A track of haptics data that can be mixed or sequenced with another track.
Public Member Functions
OVRHapticsChannel (uint outputIndex)
Constructs a channel targeting the specified output.
void Preempt (OVRHapticsClip clip)
Cancels any currently-playing clips and immediatly plays the specified clip instead.
void Queue (OVRHapticsClip clip)
Enqueues the specified clip to play after any currently-playing clips finish.
void Mix (OVRHapticsClip clip)
Adds the specified clip to play simultaneously to the currently-playing clip(s).
void Clear ()
Cancels any currently-playing clips.
Private Attributes
OVRHapticsOutput m_output
Detailed Description
A track of haptics data that can be mixed or sequenced with another track.
Definition at line 89 of file OVRHaptics.cs.
Constructor & Destructor Documentation
OVRHapticsChannel()
OVRHaptics.OVRHapticsChannel.OVRHapticsChannel (uint outputIndex)
Constructs a channel targeting the specified output.
Definition at line 96 of file OVRHaptics.cs.
        {
            m_output = m_outputs[outputIndex];
        }
Member Function Documentation
Clear()
void OVRHaptics.OVRHapticsChannel.Clear ()
Cancels any currently-playing clips.
Definition at line 128 of file OVRHaptics.cs.
        {
            m_output.Clear();
        }
Mix()
void OVRHaptics.OVRHapticsChannel.Mix (OVRHapticsClip clip)
Adds the specified clip to play simultaneously to the currently-playing clip(s).
Definition at line 120 of file OVRHaptics.cs.
        {
            m_output.Mix(clip);
        }
References OVRHaptics.OVRHapticsOutput.Mix().
Preempt()
void OVRHaptics.OVRHapticsChannel.Preempt (OVRHapticsClip clip)
Cancels any currently-playing clips and immediatly plays the specified clip instead.
Definition at line 104 of file OVRHaptics.cs.
        {
            m_output.Preempt(clip);
        }
References OVRHaptics.OVRHapticsOutput.Preempt().
Queue()
void OVRHaptics.OVRHapticsChannel.Queue (OVRHapticsClip clip)
Enqueues the specified clip to play after any currently-playing clips finish.
Definition at line 112 of file OVRHaptics.cs.
        {
            m_output.Queue(clip);
        }
References OVRHaptics.OVRHapticsOutput.Queue().
Member Data Documentation
m_output
OVRHapticsOutput OVRHaptics.OVRHapticsChannel.m_output private
Definition at line 91 of file OVRHaptics.cs.
The documentation for this class was generated from the following file:
Assets/Oculus/VR/Scripts/OVRHaptics.cs