VR_Test: OVRLipSyncContextBase Class Reference
OVRLipSyncContextBase Class Reference
OVRLipSyncContextBase interfaces into the Oculus phoneme recognizer. This component should be added into the scene once for each Audio Source.
Public Member Functions
OVRLipSync.Frame GetCurrentPhonemeFrame ()
Gets the current phoneme frame (lock and copy current frame to caller frame)
void SetVisemeBlend (int viseme, int amount)
Sets a given viseme id blend weight to a given amount.
void SetLaughterBlend (int amount)
Sets a given viseme id blend weight to a given amount.
OVRLipSync.Result ResetContext ()
Resets the context.
Public Attributes
AudioSource audioSource = null
OVRLipSync.ContextProviders provider = OVRLipSync.ContextProviders.Enhanced
bool enableAcceleration = true
Properties
int Smoothing [get, set]
uint Context [get]
OVRLipSync.Frame Frame [get]
Private Member Functions
void Awake ()
Awake this instance.
void OnDestroy ()
Raises the destroy event.
Private Attributes
OVRLipSync.Frame frame = new OVRLipSync.Frame()
uint context = 0
int _smoothing
Detailed Description
OVRLipSyncContextBase interfaces into the Oculus phoneme recognizer. This component should be added into the scene once for each Audio Source.
Definition at line 36 of file OVRLipSyncContextBase.cs.
Member Function Documentation
Awake()
void OVRLipSyncContextBase.Awake () private
Awake this instance.
Definition at line 101 of file OVRLipSyncContextBase.cs.
    {
        // Cache the audio source we are going to be using to pump data to the SR
        if (!audioSource)
        {
            audioSource = GetComponent<AudioSource>();
        }
        lock (this)
        {
            if (context == 0)
            {
                if (OVRLipSync.CreateContext(ref context, provider, 0, enableAcceleration)
                    != OVRLipSync.Result.Success)
                {
                    Debug.LogError("OVRLipSyncContextBase.Start ERROR: Could not create" +
                        " Phoneme context.");
                    return;
                }
            }
        }
    }
References OVRLipSync.CreateContext().
GetCurrentPhonemeFrame()
OVRLipSync.Frame OVRLipSyncContextBase.GetCurrentPhonemeFrame ()
Gets the current phoneme frame (lock and copy current frame to caller frame)
Returns
error code
Parameters
inFrame In frame.
Definition at line 152 of file OVRLipSyncContextBase.cs.
    {
        return frame;
    }
OnDestroy()
void OVRLipSyncContextBase.OnDestroy () private
Raises the destroy event.
Definition at line 128 of file OVRLipSyncContextBase.cs.
    {
        // Create the context that we will feed into the audio buffer
        lock (this)
        {
            if (context != 0)
            {
                if (OVRLipSync.DestroyContext(context) != OVRLipSync.Result.Success)
                {
                    Debug.LogError("OVRLipSyncContextBase.OnDestroy ERROR: Could not delete" +
                        " Phoneme context.");
                }
            }
        }
    }
References OVRLipSync.DestroyContext().
ResetContext()
OVRLipSync.Result OVRLipSyncContextBase.ResetContext ()
Resets the context.
Returns
error code
Definition at line 201 of file OVRLipSyncContextBase.cs.
    {
        // Reset visemes to silence etc.
        frame.Reset();
        return OVRLipSync.ResetContext(context);
    }
References OVRLipSync.ResetContext().
SetLaughterBlend()
void OVRLipSyncContextBase.SetLaughterBlend (int amount)
Sets a given viseme id blend weight to a given amount.
Parameters
amount Integer viseme amount
Definition at line 185 of file OVRLipSyncContextBase.cs.
    {
        OVRLipSync.Result result =
            OVRLipSync.SendSignal(context, OVRLipSync.Signals.LaughterAmount, amount, 0);
        if (result != OVRLipSync.Result.Success)
        {
            Debug.LogError("OVRLipSyncContextBase.SetLaughterBlend: An unexpected" +
                " error occured.");
        }
    }
References OVRLipSync.SendSignal().
SetVisemeBlend()
void OVRLipSyncContextBase.SetVisemeBlend (int viseme, int amount)
Sets a given viseme id blend weight to a given amount.
Parameters
viseme Integer viseme ID
amount Integer viseme amount
Definition at line 162 of file OVRLipSyncContextBase.cs.
    {
        OVRLipSync.Result result =
            OVRLipSync.SendSignal(context, OVRLipSync.Signals.VisemeAmount, viseme, amount);
        if (result != OVRLipSync.Result.Success)
        {
            if (result == OVRLipSync.Result.InvalidParam)
            {
                Debug.LogError("OVRLipSyncContextBase.SetVisemeBlend: Viseme ID is invalid.");
            }
            else
            {
                Debug.LogError("OVRLipSyncContextBase.SetVisemeBlend: An unexpected" +
                    " error occured.");
            }
        }
    }
References OVRLipSync.SendSignal().
Member Data Documentation
_smoothing
int OVRLipSyncContextBase._smoothing private
Definition at line 52 of file OVRLipSyncContextBase.cs.
audioSource
AudioSource OVRLipSyncContextBase.audioSource = null
Definition at line 40 of file OVRLipSyncContextBase.cs.
context
uint OVRLipSyncContextBase.context = 0 private
Definition at line 50 of file OVRLipSyncContextBase.cs.
enableAcceleration
bool OVRLipSyncContextBase.enableAcceleration = true
Definition at line 45 of file OVRLipSyncContextBase.cs.
frame
OVRLipSync.Frame OVRLipSyncContextBase.frame = new OVRLipSync.Frame() private
Definition at line 49 of file OVRLipSyncContextBase.cs.
provider
OVRLipSync.ContextProviders OVRLipSyncContextBase.provider = OVRLipSync.ContextProviders.Enhanced
Definition at line 43 of file OVRLipSyncContextBase.cs.
Property Documentation
Context
uint OVRLipSyncContextBase.Context get
Definition at line 82 of file OVRLipSyncContextBase.cs.
    {
        get
        {
            return context;
        }
    }
Frame
OVRLipSync.Frame OVRLipSyncContextBase.Frame get protected
Definition at line 90 of file OVRLipSyncContextBase.cs.
    {
        get
        {
            return frame;
        }
    }
Smoothing
int OVRLipSyncContextBase.Smoothing get set
Definition at line 53 of file OVRLipSyncContextBase.cs.
    {
        set
        {
            OVRLipSync.Result result =
                OVRLipSync.SendSignal(context, OVRLipSync.Signals.VisemeSmoothing, value, 0);
            if (result != OVRLipSync.Result.Success)
            {
                if (result == OVRLipSync.Result.InvalidParam)
                {
                    Debug.LogError("OVRLipSyncContextBase.SetSmoothing: A viseme smoothing" +
                        " parameter is invalid, it should be between 1 and 100!");
                }
                else
                {
                    Debug.LogError("OVRLipSyncContextBase.SetSmoothing: An unexpected" +
                        " error occured.");
                }
            }
            _smoothing = value;
        }
        get
        {
            return _smoothing;
        }
    }
The documentation for this class was generated from the following file:
Assets/Oculus/LipSync/Scripts/OVRLipSyncContextBase.cs