VR_Test: Oculus.Interaction.Grab.GrabSurfaces.BoxGrabSurface Class Reference
Oculus.Interaction.Grab.GrabSurfaces.BoxGrabSurface Class Reference
This GrabSurface defines a Rectangle around which the grip point is valid. Since the grip point might be offset from the fingers, a valid range for each opposite side of the rectangle can be set so the grabbing fingers are constrained to the object bounds.
Public Member Functions
Pose GetReferencePose (Transform relativeTo)
The origin pose of the surface. This is the point from which the base of the box must start.
float GetWidthOffset (Transform relativeTo)
The lateral displacement of the grip point in the main side.
void SetWidthOffset (float widthOffset, Transform relativeTo)
Vector4 GetSnapOffset (Transform relativeTo)
The range at which the sides are constrained. X,Y for the back and forward sides range. Z,W for the left and right sides range.
void SetSnapOffset (Vector4 snapOffset, Transform relativeTo)
Vector3 GetSize (Transform relativeTo)
The size of the rectangle. Y is ignored.
void SetSize (Vector3 size, Transform relativeTo)
Quaternion GetRotation (Transform relativeTo)
The rotation of the rectangle from the Grip point.
void SetRotation (Quaternion rotation, Transform relativeTo)
Vector3 GetDirection (Transform relativeTo)
The forward direction of the rectangle (based on its rotation)
Pose MirrorPose (in Pose pose, Transform relativeTo)
Method for mirroring a Pose around the surface. Different surfaces will prefer mirroring along different axis.
IGrabSurface CreateMirroredSurface (GameObject gameObject)
Creates a new IGrabSurface under the selected gameobject that is a mirror version of the current.
IGrabSurface CreateDuplicatedSurface (GameObject gameObject)
Creates a new IGrabSurface under the selected gameobject with the same data as this one.
GrabPoseScore CalculateBestPoseAtSurface (in Pose targetPose, out Pose bestPose, in PoseMeasureParameters scoringModifier, Transform relativeTo)
Finds the Pose at the surface that is the closest to the given pose.
bool CalculateBestPoseAtSurface (Ray targetRay, out Pose bestPose, Transform relativeTo)
Finds the Pose at the surface that is the closest to the given ray.
void InjectAllBoxSurface (BoxGrabSurfaceData data, Transform relativeTo)
void InjectData (BoxGrabSurfaceData data)
void InjectRelativeTo (Transform relativeTo)
Protected Member Functions
virtual void Reset ()
virtual void Start ()
Vector3 NearestPointInSurface (Vector3 targetPosition, Transform relativeTo)
Pose MinimalRotationPoseAtSurface (in Pose userPose, Transform relativeTo)
Pose MinimalTranslationPoseAtSurface (in Pose userPose, Transform relativeTo)
Protected Attributes
BoxGrabSurfaceData _data = new BoxGrabSurfaceData()
Properties
Pose RelativePose [get]
Private Member Functions
void CalculateCorners (out Vector3 bottomLeft, out Vector3 bottomRight, out Vector3 topLeft, out Vector3 topRight, Transform relativeTo)
Vector3 ProjectOnSegment (Vector3 point,(Vector3, Vector3) segment)
void NearestPointAndAngleInSurface (Vector3 targetPosition, out Vector3 surfacePoint, out float angle, Transform relativeTo)
Static Private Member Functions
static float RotationalScore (in Quaternion from, in Quaternion to)
Private Attributes
Transform _relativeTo
Detailed Description
This GrabSurface defines a Rectangle around which the grip point is valid. Since the grip point might be offset from the fingers, a valid range for each opposite side of the rectangle can be set so the grabbing fingers are constrained to the object bounds.
Definition at line 62 of file BoxGrabSurface.cs.
Member Function Documentation
CalculateBestPoseAtSurface() [1/2]
GrabPoseScore Oculus.Interaction.Grab.GrabSurfaces.BoxGrabSurface.CalculateBestPoseAtSurface (in Pose targetPose, out Pose bestPose, in PoseMeasureParameters scoringModifier, Transform relativeTo)
Finds the Pose at the surface that is the closest to the given pose.
Parameters
targetPose The pose to find the nearest to.
bestPose The best found pose at the surface.<
scoringModifier Weight used to decide which target pose to select
relativeTo Reference transform to measure the poses against
Returns
The score indicating how good the found pose was, -1 for invalid result.
Implements Oculus.Interaction.Grab.GrabSurfaces.IGrabSurface.
Definition at line 187 of file BoxGrabSurface.cs.
        {
            return GrabPoseHelper.CalculateBestPoseAtSurface(targetPose, out bestPose,
                scoringModifier, relativeTo,
                MinimalTranslationPoseAtSurface, MinimalRotationPoseAtSurface);
        }
References Oculus.Interaction.Grab.GrabPoseHelper.CalculateBestPoseAtSurface().
CalculateBestPoseAtSurface() [2/2]
bool Oculus.Interaction.Grab.GrabSurfaces.BoxGrabSurface.CalculateBestPoseAtSurface (Ray targetRay, out Pose bestPose, Transform relativeTo)
Finds the Pose at the surface that is the closest to the given ray.
Parameters
targetRay Ray searching for the nearest snap pose
bestPose The best found pose at the surface.
relativeTo Reference transform to measure the poses against
Returns
True if the pose was found
Implements Oculus.Interaction.Grab.GrabSurfaces.IGrabSurface.
Definition at line 228 of file BoxGrabSurface.cs.
        {
            Pose recordedPose = GetReferencePose(relativeTo);
            Plane plane = new Plane(GetRotation(relativeTo) * Vector3.up, this.transform.position);
            plane.Raycast(targetRay, out float rayDistance);
            Vector3 proximalPoint = targetRay.origin + targetRay.direction * rayDistance;
            Vector3 surfacePoint = NearestPointInSurface(proximalPoint, relativeTo);
            Pose desiredPose = new Pose(surfacePoint, recordedPose.rotation);
            bestPose = MinimalTranslationPoseAtSurface(desiredPose, relativeTo);
            return true;
        }
References Oculus.Interaction.Grab.GrabSurfaces.BoxGrabSurface.GetReferencePose(), and Oculus.Interaction.Grab.GrabSurfaces.BoxGrabSurface.GetRotation().
CalculateCorners()
void Oculus.Interaction.Grab.GrabSurfaces.BoxGrabSurface.CalculateCorners (out Vector3 bottomLeft, out Vector3 bottomRight, out Vector3 topLeft, out Vector3 topRight, Transform relativeTo) private
Definition at line 195 of file BoxGrabSurface.cs.
        {
            Pose referencePose = GetReferencePose(relativeTo);
            Vector3 size = GetSize(relativeTo);
            float widthOffset = GetWidthOffset(relativeTo);
            Vector3 rightRot = GetRotation(relativeTo) * Vector3.right;
            bottomLeft = referencePose.position - rightRot * size.x * (1f - widthOffset);
            bottomRight = referencePose.position + rightRot * size.x * (widthOffset);
            Vector3 forwardOffset = GetRotation(relativeTo) * Vector3.forward * size.z;
            topLeft = bottomLeft + forwardOffset;
            topRight = bottomRight + forwardOffset;
        }
CreateDuplicatedSurface()
IGrabSurface Oculus.Interaction.Grab.GrabSurfaces.BoxGrabSurface.CreateDuplicatedSurface (GameObject gameObject)
Creates a new IGrabSurface under the selected gameobject with the same data as this one.
Parameters
gameObject The gameobject in which to place the new IGrabSurface.
Returns
A clone of this IGrabSurface.
Implements Oculus.Interaction.Grab.GrabSurfaces.IGrabSurface.
Definition at line 180 of file BoxGrabSurface.cs.
        {
            BoxGrabSurface surface = gameObject.AddComponent<BoxGrabSurface>();
            surface._data = _data;
            return surface;
        }
CreateMirroredSurface()
IGrabSurface Oculus.Interaction.Grab.GrabSurfaces.BoxGrabSurface.CreateMirroredSurface (GameObject gameObject)
Creates a new IGrabSurface under the selected gameobject that is a mirror version of the current.
Parameters
gameObject The gameobject in which to place the new IGrabSurface.
Returns
A mirror of this IGrabSurface.
Implements Oculus.Interaction.Grab.GrabSurfaces.IGrabSurface.
Definition at line 173 of file BoxGrabSurface.cs.
        {
            BoxGrabSurface surface = gameObject.AddComponent<BoxGrabSurface>();
            surface._data = _data.Mirror();
            return surface;
        }
GetDirection()
Vector3 Oculus.Interaction.Grab.GrabSurfaces.BoxGrabSurface.GetDirection (Transform relativeTo)
The forward direction of the rectangle (based on its rotation)
Parameters
relativeTo The reference transform to apply the surface to
Returns
Direction in world space
Definition at line 147 of file BoxGrabSurface.cs.
        {
            return GetRotation(relativeTo) * Vector3.forward;
        }
References Oculus.Interaction.Grab.GrabSurfaces.BoxGrabSurface.GetRotation().
GetReferencePose()
Pose Oculus.Interaction.Grab.GrabSurfaces.BoxGrabSurface.GetReferencePose (Transform relativeTo)
The origin pose of the surface. This is the point from which the base of the box must start.
Parameters
relativeTo The reference transform to apply the surface to
Returns
Pose in world space
Definition at line 79 of file BoxGrabSurface.cs.
        {
            return PoseUtils.GlobalPoseScaled(relativeTo, RelativePose);
        }
References Oculus.Interaction.PoseUtils.GlobalPoseScaled().
GetRotation()
Quaternion Oculus.Interaction.Grab.GrabSurfaces.BoxGrabSurface.GetRotation (Transform relativeTo)
The rotation of the rectangle from the Grip point.
Parameters
relativeTo The reference transform to apply the surface to
Returns
Rotation in world space
Definition at line 133 of file BoxGrabSurface.cs.
        {
            return relativeTo.rotation * Quaternion.Euler(_data.eulerAngles);
        }
GetSize()
Vector3 Oculus.Interaction.Grab.GrabSurfaces.BoxGrabSurface.GetSize (Transform relativeTo)
The size of the rectangle. Y is ignored.
Parameters
relativeTo The reference transform to apply the surface to
Returns
Size in world space
Definition at line 119 of file BoxGrabSurface.cs.
        {
            return _data.size * relativeTo.lossyScale.x;
        }
GetSnapOffset()
Vector4 Oculus.Interaction.Grab.GrabSurfaces.BoxGrabSurface.GetSnapOffset (Transform relativeTo)
The range at which the sides are constrained. X,Y for the back and forward sides range. Z,W for the left and right sides range.
Parameters
relativeTo The reference transform to apply the surface to
Returns
Offsets in world space
Definition at line 105 of file BoxGrabSurface.cs.
        {
            return _data.snapOffset * relativeTo.lossyScale.x;
        }
GetWidthOffset()
float Oculus.Interaction.Grab.GrabSurfaces.BoxGrabSurface.GetWidthOffset (Transform relativeTo)
The lateral displacement of the grip point in the main side.
Parameters
relativeTo The reference transform to apply the surface to
Returns
Lateral displacement in world space
Definition at line 89 of file BoxGrabSurface.cs.
        {
            return _data.widthOffset * relativeTo.lossyScale.x;
        }
InjectAllBoxSurface()
void Oculus.Interaction.Grab.GrabSurfaces.BoxGrabSurface.InjectAllBoxSurface (BoxGrabSurfaceData data, Transform relativeTo)
Definition at line 360 of file BoxGrabSurface.cs.
        {
            InjectData(data);
            InjectRelativeTo(relativeTo);
        }
InjectData()
void Oculus.Interaction.Grab.GrabSurfaces.BoxGrabSurface.InjectData (BoxGrabSurfaceData data)
Definition at line 366 of file BoxGrabSurface.cs.
        {
            _data = data;
        }
InjectRelativeTo()
void Oculus.Interaction.Grab.GrabSurfaces.BoxGrabSurface.InjectRelativeTo (Transform relativeTo)
Definition at line 371 of file BoxGrabSurface.cs.
        {
            _relativeTo = relativeTo;
        }
MinimalRotationPoseAtSurface()
Pose Oculus.Interaction.Grab.GrabSurfaces.BoxGrabSurface.MinimalRotationPoseAtSurface (in Pose userPose, Transform relativeTo) protected
Definition at line 295 of file BoxGrabSurface.cs.
        {
            Quaternion rotation = GetRotation(relativeTo);
            Pose referencePose = GetReferencePose(relativeTo);
            Vector4 snappOffset = GetSnapOffset(relativeTo);
            Vector3 desiredPos = userPose.position;
            Quaternion baseRot = referencePose.rotation;
            Quaternion desiredRot = userPose.rotation;
            Vector3 up = rotation * Vector3.up;
            Quaternion bottomRot = baseRot;
            Quaternion topRot = Quaternion.AngleAxis(180f, up) * baseRot;
            Quaternion leftRot = Quaternion.AngleAxis(90f, up) * baseRot;
            Quaternion rightRot = Quaternion.AngleAxis(-90f, up) * baseRot;
            float bottomDot = RotationalScore(bottomRot, desiredRot);
            float topDot = RotationalScore(topRot, desiredRot);
            float leftDot = RotationalScore(leftRot, desiredRot);
            float rightDot = RotationalScore(rightRot, desiredRot);
            Vector3 rightDir = rotation * Vector3.right;
            Vector3 forwardDir = rotation * Vector3.forward;
            Vector3 bottomLeft, bottomRight, topLeft, topRight;
            CalculateCorners(out bottomLeft, out bottomRight, out topLeft, out topRight, relativeTo);
            float maxDot = Mathf.Max(bottomDot, Mathf.Max(topDot, Mathf.Max(leftDot, rightDot)));
            if (bottomDot == maxDot)
            {
                Vector3 projBottom = ProjectOnSegment(desiredPos, (bottomLeft + rightDir * snappOffset.y, bottomRight + rightDir * snappOffset.x));
                return new Pose(projBottom, bottomRot);
            }
            if (topDot == maxDot)
            {
                Vector3 projTop = ProjectOnSegment(desiredPos, (topLeft - rightDir * snappOffset.x, topRight - rightDir * snappOffset.y));
                return new Pose(projTop, topRot);
            }
            if (leftDot == maxDot)
            {
                Vector3 projLeft = ProjectOnSegment(desiredPos, (bottomLeft - forwardDir * snappOffset.z, topLeft - forwardDir * snappOffset.w));
                return new Pose(projLeft, leftRot);
            }
            Vector3 projRight = ProjectOnSegment(desiredPos, (bottomRight + forwardDir * snappOffset.w, topRight + forwardDir * snappOffset.z));
            return new Pose(projRight, rightRot);
        }
MinimalTranslationPoseAtSurface()
Pose Oculus.Interaction.Grab.GrabSurfaces.BoxGrabSurface.MinimalTranslationPoseAtSurface (in Pose userPose, Transform relativeTo) protected
Definition at line 340 of file BoxGrabSurface.cs.
        {
            Pose referencePose = GetReferencePose(relativeTo);
            Quaternion rotation = GetRotation(relativeTo);
            Vector3 desiredPos = userPose.position;
            Quaternion baseRot = referencePose.rotation;
            NearestPointAndAngleInSurface(desiredPos, out Vector3 surfacePoint, out float surfaceAngle, relativeTo);
            Quaternion surfaceRotation = Quaternion.AngleAxis(surfaceAngle, rotation * Vector3.up) * baseRot;
            return new Pose(surfacePoint, surfaceRotation);
        }
MirrorPose()
Pose Oculus.Interaction.Grab.GrabSurfaces.BoxGrabSurface.MirrorPose (in Pose gripPose, Transform relativeTo)
Method for mirroring a Pose around the surface. Different surfaces will prefer mirroring along different axis.
Parameters
gripPose The Pose to be mirrored.
relativeTo Reference transform to mirror the pose around
Returns
A new pose mirrored at this surface.
Implements Oculus.Interaction.Grab.GrabSurfaces.IGrabSurface.
Definition at line 165 of file BoxGrabSurface.cs.
        {
            Quaternion rotation = GetRotation(relativeTo);
            Vector3 normal = Quaternion.Inverse(relativeTo.rotation) * rotation * Vector3.forward;
            Vector3 tangent = Quaternion.Inverse(relativeTo.rotation) * (rotation * Vector3.up);
            return pose.MirrorPoseRotation(normal, tangent);
        }
References Oculus.Interaction.Grab.GrabSurfaces.BoxGrabSurface.GetRotation().
NearestPointAndAngleInSurface()
void Oculus.Interaction.Grab.GrabSurfaces.BoxGrabSurface.NearestPointAndAngleInSurface (Vector3 targetPosition, out Vector3 surfacePoint, out float angle, Transform relativeTo) private
Definition at line 247 of file BoxGrabSurface.cs.
        {
            Quaternion rotation = GetRotation(relativeTo);
            Vector4 snappOffset = GetSnapOffset(relativeTo);
            Vector3 rightDir = rotation * Vector3.right;
            Vector3 forwardDir = rotation * Vector3.forward;
            Vector3 bottomLeft, bottomRight, topLeft, topRight;
            CalculateCorners(out bottomLeft, out bottomRight, out topLeft, out topRight, relativeTo);
            Vector3 bottomP = ProjectOnSegment(targetPosition,
                (bottomLeft + rightDir * snappOffset.y, bottomRight + rightDir * snappOffset.x));
            Vector3 topP = ProjectOnSegment(targetPosition,
                (topLeft - rightDir * snappOffset.x, topRight - rightDir * snappOffset.y));
            Vector3 leftP = ProjectOnSegment(targetPosition,
                (bottomLeft - forwardDir * snappOffset.z, topLeft - forwardDir * snappOffset.w));
            Vector3 rightP = ProjectOnSegment(targetPosition,
                (bottomRight + forwardDir * snappOffset.w, topRight + forwardDir * snappOffset.z));
            float bottomDistance = (bottomP - targetPosition).sqrMagnitude;
            float topDistance = (topP - targetPosition).sqrMagnitude;
            float leftDistance = (leftP - targetPosition).sqrMagnitude;
            float rightDistance = (rightP - targetPosition).sqrMagnitude;
            float minDistance = Mathf.Min(bottomDistance,
                Mathf.Min(topDistance,
                Mathf.Min(leftDistance, rightDistance)));
            if (bottomDistance == minDistance)
            {
                surfacePoint = bottomP;
                angle = 0f;
                return;
            }
            if (topDistance == minDistance)
            {
                surfacePoint = topP;
                angle = 180f;
                return;
            }
            if (leftDistance == minDistance)
            {
                surfacePoint = leftP;
                angle = 90f;
                return;
            }
            surfacePoint = rightP;
            angle = -90f;
        }
NearestPointInSurface()
Vector3 Oculus.Interaction.Grab.GrabSurfaces.BoxGrabSurface.NearestPointInSurface (Vector3 targetPosition, Transform relativeTo) protected
Definition at line 241 of file BoxGrabSurface.cs.
        {
            NearestPointAndAngleInSurface(targetPosition, out Vector3 surfacePoint, out float angle, relativeTo);
            return surfacePoint;
        }
ProjectOnSegment()
Vector3 Oculus.Interaction.Grab.GrabSurfaces.BoxGrabSurface.ProjectOnSegment (Vector3 point, (Vector3, Vector3) segment) private
Definition at line 209 of file BoxGrabSurface.cs.
        {
            Vector3 line = segment.Item2 - segment.Item1;
            Vector3 projection = Vector3.Project(point - segment.Item1, line);
            if (Vector3.Dot(projection, line) < 0f)
            {
                projection = segment.Item1;
            }
            else if (projection.magnitude > line.magnitude)
            {
                projection = segment.Item2;
            }
            else
            {
                projection += segment.Item1;
            }
            return projection;
        }
Reset()
virtual void Oculus.Interaction.Grab.GrabSurfaces.BoxGrabSurface.Reset () protected virtual
Definition at line 153 of file BoxGrabSurface.cs.
        {
            _relativeTo = this.GetComponentInParent<IRelativeToRef>()?.RelativeTo;
        }
RotationalScore()
static float Oculus.Interaction.Grab.GrabSurfaces.BoxGrabSurface.RotationalScore (in Quaternion from, in Quaternion to) static private
Definition at line 351 of file BoxGrabSurface.cs.
        {
            float forwardDifference = Vector3.Dot(from * Vector3.forward, to * Vector3.forward) * 0.5f + 0.5f;
            float upDifference = Vector3.Dot(from * Vector3.up, to * Vector3.up) * 0.5f + 0.5f;
            return (forwardDifference * upDifference);
        }
SetRotation()
void Oculus.Interaction.Grab.GrabSurfaces.BoxGrabSurface.SetRotation (Quaternion rotation, Transform relativeTo)
Definition at line 137 of file BoxGrabSurface.cs.
        {
            _data.eulerAngles = (Quaternion.Inverse(relativeTo.rotation) * rotation).eulerAngles;
        }
SetSize()
void Oculus.Interaction.Grab.GrabSurfaces.BoxGrabSurface.SetSize (Vector3 size, Transform relativeTo)
Definition at line 123 of file BoxGrabSurface.cs.
        {
            _data.size = size / relativeTo.lossyScale.x;
        }
SetSnapOffset()
void Oculus.Interaction.Grab.GrabSurfaces.BoxGrabSurface.SetSnapOffset (Vector4 snapOffset, Transform relativeTo)
Definition at line 109 of file BoxGrabSurface.cs.
        {
            _data.snapOffset = snapOffset / relativeTo.lossyScale.x;
        }
SetWidthOffset()
void Oculus.Interaction.Grab.GrabSurfaces.BoxGrabSurface.SetWidthOffset (float widthOffset, Transform relativeTo)
Definition at line 93 of file BoxGrabSurface.cs.
        {
            _data.widthOffset = widthOffset / relativeTo.lossyScale.x;
        }
Start()
virtual void Oculus.Interaction.Grab.GrabSurfaces.BoxGrabSurface.Start () protected virtual
Definition at line 159 of file BoxGrabSurface.cs.
        {
            this.AssertField(_data, nameof(_data));
            this.AssertField(_relativeTo, nameof(_relativeTo));
        }
Member Data Documentation
_data
BoxGrabSurfaceData Oculus.Interaction.Grab.GrabSurfaces.BoxGrabSurface._data = new BoxGrabSurfaceData() protected
Definition at line 65 of file BoxGrabSurface.cs.
_relativeTo
Transform Oculus.Interaction.Grab.GrabSurfaces.BoxGrabSurface._relativeTo private
Definition at line 69 of file BoxGrabSurface.cs.
Property Documentation
RelativePose
Pose Oculus.Interaction.Grab.GrabSurfaces.BoxGrabSurface.RelativePose get private
Definition at line 71 of file BoxGrabSurface.cs.
The documentation for this class was generated from the following file:
Assets/Oculus/Interaction/Runtime/Scripts/Grab/SnapSurfaces/BoxGrabSurface.cs