VR_Test: Meta.WitAi.Requests.VRequest Class Reference
Meta.WitAi.Requests.VRequest Class Reference
Class for performing web requests using UnityWebRequest.
Public Member Functions
delegate void RequestProgressDelegate (float progress)
delegate void RequestFirstResponseDelegate ()
delegate void RequestCompleteDelegate< TResult > (TResult result, string error)
VRequest (RequestProgressDelegate onDownloadProgress=null, RequestFirstResponseDelegate onFirstResponse=null)
A constructor that takes in download progress delegate & first response delegate.
virtual bool Request (UnityWebRequest unityRequest, RequestCompleteDelegate< UnityWebRequest > onComplete)
Initialize with a request and an on completion callback.
virtual string CleanUrl (string url)
Clean the url prior to use.
virtual void Cancel ()
bool RequestFileHeaders (Uri uri, RequestCompleteDelegate< Dictionary< string, string > > onComplete)
Performs a simple http header request.
bool RequestFile (Uri uri, RequestCompleteDelegate< byte[]> onComplete)
Performs a simple http header request.
bool RequestFileDownload (string downloadPath, UnityWebRequest unityRequest, RequestCompleteDelegate< bool > onComplete)
Download a file using a unityrequest.
bool RequestFileExists (string checkPath, RequestCompleteDelegate< bool > onComplete)
Checks if a file exists at a specified location.
bool RequestText (UnityWebRequest unityRequest, RequestCompleteDelegate< string > onComplete)
Performs a text request & handles the resultant text.
bool RequestJson< TData > (UnityWebRequest unityRequest, RequestCompleteDelegate< TData > onComplete)
Performs a json request & handles the resultant text.
bool RequestJsonGet< TData > (Uri uri, RequestCompleteDelegate< TData > onComplete)
Perform a json get request with a specified uri.
bool RequestJsonPost< TData > (Uri uri, byte[] postData, RequestCompleteDelegate< TData > onComplete)
Performs a json request by posting byte data.
bool RequestJsonPost< TData > (Uri uri, string postText, RequestCompleteDelegate< TData > onComplete)
Performs a json request by posting a string.
bool RequestJsonPut< TData > (Uri uri, byte[] putData, RequestCompleteDelegate< TData > onComplete)
Performs a json put request with byte data.
bool RequestJsonPut< TData > (Uri uri, string putText, RequestCompleteDelegate< TData > onComplete)
Performs a json put request with a string.
bool RequestAudioStream (IAudioClipStream clipStream, UnityWebRequest unityRequest, RequestCompleteDelegate< IAudioClipStream > onClipStreamReady, AudioType audioType, bool audioStream)
Request audio clip with url, type, progress delegate & ready delegate.
bool RequestAudioStream (IAudioClipStream clipStream, Uri uri, RequestCompleteDelegate< IAudioClipStream > onClipReady, AudioType audioType, bool audioStream)
Request audio clip with url, type, progress delegate & ready delegate.
Static Public Member Functions
static string GetSpecificRequestError (UnityWebRequest request)
Static Public Attributes
static int MaxConcurrentRequests = 3
Will only start new requests if there are less than this number If <= 0, then all requests will run immediately.
Protected Member Functions
virtual Dictionary< string, string > GetHeaders ()
virtual IEnumerator PerformUpdate ()
virtual void Begin ()
virtual bool IsRequestComplete ()
virtual void Complete ()
virtual void Unload ()
Properties
int Timeout = 5 [get, set]
Timeout in seconds.
bool IsPerforming = false [get, private set]
If request is currently being performed.
bool IsComplete = false [get, private set]
Whether or not the completion delegate has been called.
int ResponseCode = 0 [get, set]
Response Code if applicable.
float UploadProgress = 0f [get, private set]
Current progress for get requests.
float DownloadProgress = 0f [get, private set]
Current progress for download.
Private Member Functions
void OnRequestAudioReady (IAudioClipStream clipStream, AudioType audioType, UnityWebRequest request, string error, RequestCompleteDelegate< IAudioClipStream > onClipStreamReady)
Private Attributes
UnityWebRequest _request
RequestProgressDelegate _onDownloadProgress
RequestFirstResponseDelegate _onFirstResponse
RequestCompleteDelegate< UnityWebRequest > _onComplete
CoroutineUtility.CoroutinePerformer _coroutine
Static Private Attributes
static int _requestCount = 0
Detailed Description
Class for performing web requests using UnityWebRequest.
Definition at line 36 of file VRequest.cs.
Constructor & Destructor Documentation
VRequest()
Meta.WitAi.Requests.VRequest.VRequest (RequestProgressDelegate onDownloadProgress = null, RequestFirstResponseDelegate onFirstResponse = null)
A constructor that takes in download progress delegate & first response delegate.
Parameters
onDownloadProgress The callback for progress related to downloading
onFirstResponse The callback for the first response of data from a request
Definition at line 97 of file VRequest.cs.
        {
            _onDownloadProgress = onDownloadProgress;
            _onFirstResponse = onFirstResponse;
        }
Member Function Documentation
Begin()
virtual void Meta.WitAi.Requests.VRequest.Begin () protected virtual
Definition at line 227 of file VRequest.cs.
        {
            IsPerforming = true;
            UploadProgress = 0f;
            DownloadProgress = 0f;
            _onDownloadProgress?.Invoke(DownloadProgress);
            _request.SendWebRequest();
        }
Cancel()
virtual void Meta.WitAi.Requests.VRequest.Cancel () virtual
Definition at line 284 of file VRequest.cs.
        {
            // Cancel
            if (_onComplete != null && _request != null)
            {
                DownloadProgress = 1f;
                _onDownloadProgress?.Invoke(DownloadProgress);
                _onComplete?.Invoke(_request, WitConstants.CANCEL_ERROR);
            }
            // Unload
            Unload();
        }
CleanUrl()
virtual string Meta.WitAi.Requests.VRequest.CleanUrl (string url) virtual
Clean the url prior to use.
Definition at line 154 of file VRequest.cs.
        {
            // Get url
            string result = url;
            // Add file:// if needed
            if (!Regex.IsMatch(result, "(http:|https:|file:|jar:).*"))
            {
                result = $"file://{result}";
            }
            // Return url
            return result;
        }
Complete()
virtual void Meta.WitAi.Requests.VRequest.Complete () protected virtual
Definition at line 269 of file VRequest.cs.
        {
            // Perform callback
            if (IsPerforming && IsRequestComplete())
            {
                DownloadProgress = 1f;
                ResponseCode = (int)_request.responseCode;
                _onDownloadProgress?.Invoke(DownloadProgress);
                _onComplete?.Invoke(_request, GetSpecificRequestError(_request));
            }
            // Unload
            Unload();
        }
GetSpecificRequestError()
static string Meta.WitAi.Requests.VRequest.GetSpecificRequestError (UnityWebRequest request) static
Definition at line 339 of file VRequest.cs.
        {
            // Get error & return if empty
            string error = request.error;
            string result = error;
            if (string.IsNullOrEmpty(result))
            {
                return result;
            }
            // Ignore without download handler
            if (request.downloadHandler == null)
            {
                return result;
            }
            // Ignore without downloaded json
            string downloadedJson = string.Empty;
            try
            {
                byte[] downloadedBytes = request.downloadHandler.data;
                if (downloadedBytes != null)
                {
                    downloadedJson = Encoding.UTF8.GetString(downloadedBytes);
                }
            }
            catch (Exception e)
            {
                VLog.W($"VRequest failed to parse downloaded text\n{e}");
            }
            if (string.IsNullOrEmpty(downloadedJson))
            {
                return result;
            }
            // Set error to json
            result = $"{error}\nServer Response: {downloadedJson}";
            // Decode
            WitResponseNode downloadedNode = WitResponseNode.Parse(downloadedJson);
            if (downloadedNode == null)
            {
                return result;
            }
            // Check for error
            WitResponseClass downloadedClass = downloadedNode.AsObject;
            if (!downloadedClass.HasChild(WitConstants.ENDPOINT_ERROR_PARAM))
            {
                return result;
            }
            // Get final result
            return $"{request.error}\nServer Response Message: {downloadedClass[WitConstants.ENDPOINT_ERROR_PARAM].Value}";
        }
IsRequestComplete()
virtual bool Meta.WitAi.Requests.VRequest.IsRequestComplete () protected virtual
Definition at line 236 of file VRequest.cs.
        {
            // No request
            if (_request == null)
            {
                return true;
            }
            // Request still in progress
            if (!_request.isDone)
            {
                return false;
            }
            // No error & download handler
            if (string.IsNullOrEmpty(_request.error) && _request.downloadHandler != null)
            {
                // Stream is still finishing
                if (_request.downloadHandler is IVRequestStreamable streamHandler)
                {
                    if (!streamHandler.IsStreamComplete)
                    {
                        return false;
                    }
                }
                // Download handler not complete
                else if (!_request.downloadHandler.isDone)
                {
                    return false;
                }
            }
            // Complete
            return true;
        }
OnRequestAudioReady()
void Meta.WitAi.Requests.VRequest.OnRequestAudioReady (IAudioClipStream clipStream, AudioType audioType, UnityWebRequest request, string error, RequestCompleteDelegate< IAudioClipStream > onClipStreamReady) private
Definition at line 803 of file VRequest.cs.
        {
            // Check error
            if (!string.IsNullOrEmpty(error))
            {
                onClipStreamReady?.Invoke(null, error);
                return;
            }
            // Get clip
            try
            {
                // Custom Raw PCM streaming
                if (request.downloadHandler is AudioStreamHandler downloadHandlerRaw)
                {
                    clipStream = downloadHandlerRaw.ClipStream;
                }
                // Unity audio clip stream with existing clip
                else if (request.downloadHandler is DownloadHandlerBuffer rawDownloader)
                {
                    byte[] data = rawDownloader.data;
                    float[] samples = AudioStreamHandler.DecodeAudio(data,
                        AudioStreamHandler.GetDecodeType(audioType));
                    clipStream.SetTotalSamples(samples.Length);
                    clipStream.AddSamples(samples);
                }
                // Unity audio clip stream with existing clip
                else if (request.downloadHandler is DownloadHandlerAudioClip audioDownloader)
                {
                    clipStream?.Unload();
                    AudioClip clip = audioDownloader.audioClip;
                    clipStream = new UnityAudioClipStream(clip);
                    clipStream.UpdateState();
                }
                // Failed to decode audio clip
                else if (request.downloadHandler != null)
                {
                    onClipStreamReady?.Invoke(null, $"Invalid download handler: {request.downloadHandler.GetType()}");
                    return;
                }
                // Failed to decode audio clip
                else
                {
                    onClipStreamReady?.Invoke(null, $"Missing download handler");
                    return;
                }
            }
            catch (Exception e)
            {
                // Failed to decode audio clip
                onClipStreamReady?.Invoke(null, $"Failed to decode audio clip\n{e}");
                return;
            }
            // Invalid clip
            if (clipStream != null && clipStream.TotalSamples == 0)
            {
                clipStream.Unload();
                onClipStreamReady?.Invoke(null, "Clip has no samples");
                return;
            }
            // Clip is still missing
            if (clipStream == null)
            {
                onClipStreamReady?.Invoke(null, "Failed to decode audio clip stream");
                return;
            }
            // Success
            onClipStreamReady?.Invoke(clipStream, string.Empty);
        }
PerformUpdate()
virtual IEnumerator Meta.WitAi.Requests.VRequest.PerformUpdate () protected virtual
Definition at line 169 of file VRequest.cs.
        {
            // Continue while request exists & is not complete
            while (!IsRequestComplete())
            {
                // Wait
                yield return null;
                // Waiting to begin
                if (!IsPerforming)
                {
                    // Can start
                    if (MaxConcurrentRequests <= 0 || _requestCount < MaxConcurrentRequests)
                    {
                        _requestCount++;
                        Begin();
                    }
                }
                // Update progresses
                else
                {
                    // Set upload progress
                    float newProgress = _request.uploadProgress;
                    if (!UploadProgress.Equals(newProgress))
                    {
                        UploadProgress = newProgress;
                    }
                    // Set download progress
                    newProgress = _request.downloadProgress;
                    if (!DownloadProgress.Equals(newProgress))
                    {
                        DownloadProgress = newProgress;
                        _onDownloadProgress?.Invoke(DownloadProgress);
                    }
                    // First response received
                    if (_onFirstResponse != null && _request.downloadedBytes > 0)
                    {
                        _onFirstResponse.Invoke();
                        _onFirstResponse = null;
                    }
                    // Stream is ready
                    if (_onComplete != null && _request.downloadHandler is IVRequestStreamable streamHandler)
                    {
                        if (streamHandler.IsStreamReady)
{
                            _onComplete.Invoke(_request, string.Empty);
                            _onComplete = null;
                        }
                    }
                }
            }
            // Complete
            Complete();
        }
Request()
virtual bool Meta.WitAi.Requests.VRequest.Request (UnityWebRequest unityRequest, RequestCompleteDelegate< UnityWebRequest > onComplete) virtual
Initialize with a request and an on completion callback.
Parameters
unityRequest The unity request to be performed
onProgress
onComplete The callback on completion, returns the request & error string
Returns
False if the request cannot be performed
Reimplemented in Meta.WitAi.Requests.WitVRequest.
Definition at line 111 of file VRequest.cs.
        {
            // Already setup
            if (_request != null)
            {
                onComplete?.Invoke(unityRequest, "Request is already being performed");
                return false;
            }
            // Setup
            _request = unityRequest;
            _onComplete = onComplete;
            IsPerforming = false;
            IsComplete = false;
            UploadProgress = 0f;
            DownloadProgress = 0f;
            // Add all headers
            Dictionary<string, string> headers = GetHeaders();
            if (headers != null)
            {
                foreach (var key in headers.Keys)
                {
                    _request.SetRequestHeader(key, headers[key]);
                }
            }
            // Use request's timeout value
            _request.timeout = Timeout;
            // Dispose handlers automatically
            _request.disposeUploadHandlerOnDispose = true;
            _request.disposeDownloadHandlerOnDispose = true;
            // Begin
            _coroutine = CoroutineUtility.StartCoroutine(PerformUpdate());
            // Success
            return true;
        }
References Meta.WitAi.Requests.VRequest.DownloadProgress, Meta.WitAi.Requests.VRequest.IsComplete, Meta.WitAi.Requests.VRequest.IsPerforming, Meta.WitAi.Requests.VRequest.Timeout, and Meta.WitAi.Requests.VRequest.UploadProgress.
RequestAudioStream() [1/2]
bool Meta.WitAi.Requests.VRequest.RequestAudioStream (IAudioClipStream clipStream, UnityWebRequest unityRequest, RequestCompleteDelegate< IAudioClipStream > onClipStreamReady, AudioType audioType, bool audioStream)
Request audio clip with url, type, progress delegate & ready delegate.
Parameters
clipStream The clip audio stream handler, if null one will be generated
unityRequest The unity request to add a download handler to
onClipStreamReady Called when the clip is ready for playback or has failed to load
audioType The audio type requested (Wav, MP3, etc.)
audioStream Whether or not audio should be streamed
Definition at line 749 of file VRequest.cs.
        {
            // Audio streaming
#if UNITY_WEBGL
            if (audioStream && audioType != AudioType.OGGVORBIS)
#else
            if (audioStream && !AudioStreamHandler.CanDecodeType(audioType))
#endif
            {
                VLog.W($"Audio streaming not currently supported by for {(audioType == AudioType.UNKNOWN ? "PCM" : audioType.ToString())}");
                audioStream = false;
            }
            // Add audio download handler
            if (unityRequest.downloadHandler == null)
            {
                if (AudioStreamHandler.CanDecodeType(audioType))
                {
                    // Cannot download without clip stream info
                    if (clipStream == null)
                    {
                        onClipStreamReady?.Invoke(null, "No clip stream provided");
                        return false;
                    }
                    // Use custom audio stream handler
                    if (audioStream)
                    {
                        unityRequest.downloadHandler = new AudioStreamHandler(clipStream, audioType);
                    }
                    // Use buffer stream handler
                    else
                    {
                        unityRequest.downloadHandler = new DownloadHandlerBuffer();
                    }
                }
                else
                {
                    unityRequest.downloadHandler = new DownloadHandlerAudioClip(unityRequest.uri, audioType);
                }
            }
            // Set stream settings if applicable
            if (unityRequest.downloadHandler is DownloadHandlerAudioClip audioDownloader)
            {
                audioDownloader.streamAudio = audioStream;
            }
            // Perform default request operation
            return Request(unityRequest, (response, error) => OnRequestAudioReady(clipStream, audioType, response, error, onClipStreamReady));
        }
References Meta.WitAi.Requests.AudioStreamHandler.CanDecodeType(), and Meta.WitAi.VLog.W().
RequestAudioStream() [2/2]
bool Meta.WitAi.Requests.VRequest.RequestAudioStream (IAudioClipStream clipStream, Uri uri, RequestCompleteDelegate< IAudioClipStream > onClipReady, AudioType audioType, bool audioStream)
Request audio clip with url, type, progress delegate & ready delegate.
Parameters
clipStream The clip audio stream handler, if null one will be generated
uri The url to be called
onClipReady Called when the clip is ready for playback or has failed to load
audioType The audio type requested (Wav, MP3, etc.)
audioStream Whether or not audio should be streamed
Definition at line 885 of file VRequest.cs.
        {
            return RequestAudioStream(clipStream, new UnityWebRequest(uri, UnityWebRequest.kHttpVerbGET), onClipReady, audioType, audioStream);
        }
RequestFile()
bool Meta.WitAi.Requests.VRequest.RequestFile (Uri uri, RequestCompleteDelegate< byte[]> onComplete)
Performs a simple http header request.
Parameters
uri Uri to get a file
onComplete Called once file data has been loaded
Returns
False if cannot begin request
Definition at line 438 of file VRequest.cs.
        {
            // Get unity request
            UnityWebRequest unityRequest = UnityWebRequest.Get(uri);
            // Perform request
            return Request(unityRequest, (response, error) =>
            {
                // Error
                if (!string.IsNullOrEmpty(error))
                {
                    onComplete?.Invoke(null, error);
                    return;
                }
                // File data
                byte[] fileData = response?.downloadHandler?.data;
                if (fileData == null)
                {
                    onComplete?.Invoke(null, "No data in response");
                    return;
                }
                // Success
                onComplete?.Invoke(fileData, string.Empty);
            });
        }
References Meta.WitAi.Requests.VRequest.Request().
RequestFileDownload()
bool Meta.WitAi.Requests.VRequest.RequestFileDownload (string downloadPath, UnityWebRequest unityRequest, RequestCompleteDelegate< bool > onComplete)
Download a file using a unityrequest.
Parameters
unityRequest The unity request to add a download handler to
onComplete Called once download has completed
Definition at line 471 of file VRequest.cs.
        {
            // Get temporary path for download
            string tempDownloadPath = downloadPath + ".tmp";
            try
            {
                // Delete temporary file if it already exists
                if (File.Exists(tempDownloadPath))
                {
                    File.Delete(tempDownloadPath);
                }
            }
            catch (Exception e)
            {
                // Failed to delete file
                string error = $"Deleting Download File Failed\nPath: {tempDownloadPath}\n\n{e}";
                VLog.W(error);
                onComplete?.Invoke(false, error);
                return false;
            }
            // Add file download handler
            DownloadHandlerFile fileHandler = new DownloadHandlerFile(tempDownloadPath, true);
            unityRequest.downloadHandler = fileHandler;
            unityRequest.disposeDownloadHandlerOnDispose = true;
            // Perform request
            return Request(unityRequest, (response, error) =>
            {
                try
                {
                    // Handle existing temp file
                    if (File.Exists(tempDownloadPath))
                    {
                        // For error, remove
                        if (!string.IsNullOrEmpty(error))
{
                            File.Delete(tempDownloadPath);
                        }
                        // For success, move to final path
                        else
{
                            // File already at download path, delete it
                            if (File.Exists(downloadPath))
{
                                File.Delete(downloadPath);
                            }
                            // Move to final path
                            File.Move(tempDownloadPath, downloadPath);
                        }
                    }
                }
                catch (Exception e)
                {
                    VLog.W($"Moving Download File Failed\nFrom: {tempDownloadPath}\nTo: {downloadPath}\n\n{e}");
                }
                // Complete
                onComplete?.Invoke(string.IsNullOrEmpty(error), error);
            });
        }
References Meta.WitAi.Requests.VRequest.Request(), and Meta.WitAi.VLog.W().
RequestFileExists()
bool Meta.WitAi.Requests.VRequest.RequestFileExists (string checkPath, RequestCompleteDelegate< bool > onComplete)
Checks if a file exists at a specified location.
Parameters
checkPath The local file path to be checked
onComplete Called once check has completed. Returns true if file exists
Definition at line 540 of file VRequest.cs.
        {
            // WebGL & web files, perform a header lookup
            if (checkPath.StartsWith("http"))
            {
                Uri uri = new Uri(CleanUrl(checkPath));
                return RequestFileHeaders(uri, (headers, error) =>
                {
                    onComplete?.Invoke(headers != null, error);
                });
            }
#if FAKE_JAR_LOAD
            // Android editor: simulate jar handling
            if (Application.isPlaying && checkPath.StartsWith(Application.streamingAssetsPath))
#else
            // Jar file
            if (checkPath.StartsWith("jar"))
#endif
            {
                Uri uri = new Uri(CleanUrl(checkPath));
                _onDownloadProgress = (progress) =>
                {
                    // Stop as early as possible
                    if (progress > 0f && progress < 1f)
                    {
                        var localHandle = onComplete;
                        onComplete = null;
                        Cancel();
                        localHandle?.Invoke(true, String.Empty);
                        VLog.D("Async Check File Exists Success");
                    }
                };
                return RequestFile(uri, (response, error) =>
                {
                    // If getting here, most likely failed but double check anyway
                    onComplete?.Invoke(string.IsNullOrEmpty(error), error);
                });
            }
            // Can simply use File.IO otherwise
            bool found = File.Exists(checkPath);
            onComplete?.Invoke(found, string.Empty);
            return true;
        }
References Meta.WitAi.VLog.D().
RequestFileHeaders()
bool Meta.WitAi.Requests.VRequest.RequestFileHeaders (Uri uri, RequestCompleteDelegate< Dictionary< string, string > > onComplete)
Performs a simple http header request.
Parameters
uri
onComplete Called once header lookup has completed
Returns
Definition at line 403 of file VRequest.cs.
        {
            // Header unity request
            UnityWebRequest unityRequest = UnityWebRequest.Head(uri);
            // Perform request
            return Request(unityRequest, (response, error) =>
            {
                // Error
                if (!string.IsNullOrEmpty(error))
                {
                    onComplete?.Invoke(null, error);
                    return;
                }
                // Headers dictionary if possible
                Dictionary<string, string> headers = response.GetResponseHeaders();
                if (headers == null)
                {
                    onComplete?.Invoke(null, "No headers in response.");
                    return;
                }
                // Success
                onComplete?.Invoke(headers, string.Empty);
            });
        }
References Meta.WitAi.Requests.VRequest.Request().
RequestJson< TData >()
bool Meta.WitAi.Requests.VRequest.RequestJson< TData > (UnityWebRequest unityRequest, RequestCompleteDelegate< TData > onComplete)
Performs a json request & handles the resultant text.
Parameters
unityRequest The unity request performing the post or get
onComplete The delegate upon completion
Template Parameters
TData The struct or class to be deserialized to
Returns
False if the request cannot be performed
Definition at line 626 of file VRequest.cs.
        {
            // Set request header for json
            unityRequest.SetRequestHeader("Content-Type", "application/json");
            // Perform text request
            return RequestText(unityRequest, (text, error) =>
            {
                // Request error
                if (!string.IsNullOrEmpty(error) && string.IsNullOrEmpty(text))
                {
                    onComplete?.Invoke(default(TData), error);
                    return;
                }
                // Deserialize
                JsonConvert.DeserializeObjectAsync<TData>(text, (result, deserializeSuccess) =>
                {
                    // Return parsed error
                    if (!string.IsNullOrEmpty(error))
                    {
                        onComplete?.Invoke(result, error);
                    }
                    // Parse failed
                    else if (!deserializeSuccess)
                    {
                        onComplete?.Invoke(result, $"Failed to parse json\n{text}");
                    }
                    // Success
                    else
                    {
                        onComplete?.Invoke(result, string.Empty);
                    }
                });
            });
        }
RequestJsonGet< TData >()
bool Meta.WitAi.Requests.VRequest.RequestJsonGet< TData > (Uri uri, RequestCompleteDelegate< TData > onComplete)
Perform a json get request with a specified uri.
Parameters
uri The uri to be requested
onComplete The delegate upon completion
onProgress The text download progress
Template Parameters
TData The struct or class to be deserialized to
Returns
False if the request cannot be performed
Definition at line 673 of file VRequest.cs.
        {
            return RequestJson(UnityWebRequest.Get(uri), onComplete);
        }
RequestJsonPost< TData >() [1/2]
bool Meta.WitAi.Requests.VRequest.RequestJsonPost< TData > (Uri uri, byte[] postData, RequestCompleteDelegate< TData > onComplete)
Performs a json request by posting byte data.
Parameters
uri The uri to be requested
postData The data to be uploaded
onComplete The delegate upon completion
Template Parameters
TData The struct or class to be deserialized to
Returns
False if the request cannot be performed
Definition at line 687 of file VRequest.cs.
        {
            var unityRequest = new UnityWebRequest(uri, UnityWebRequest.kHttpVerbPOST);
            unityRequest.uploadHandler = new UploadHandlerRaw(postData);
            unityRequest.downloadHandler = new DownloadHandlerBuffer();
            return RequestJson(unityRequest, onComplete);
        }
RequestJsonPost< TData >() [2/2]
bool Meta.WitAi.Requests.VRequest.RequestJsonPost< TData > (Uri uri, string postText, RequestCompleteDelegate< TData > onComplete)
Performs a json request by posting a string.
Parameters
uri The uri to be requested
postText The string to be uploaded
onComplete The delegate upon completion
Template Parameters
TData The struct or class to be deserialized to
Returns
False if the request cannot be performed
Definition at line 703 of file VRequest.cs.
        {
            return RequestJsonPost(uri, Encoding.UTF8.GetBytes(postText), onComplete);
        }
RequestJsonPut< TData >() [1/2]
bool Meta.WitAi.Requests.VRequest.RequestJsonPut< TData > (Uri uri, byte[] putData, RequestCompleteDelegate< TData > onComplete)
Performs a json put request with byte data.
Parameters
uri The uri to be requested
putData The data to be uploaded
onComplete The delegate upon completion
Template Parameters
TData The struct or class to be deserialized to
Returns
False if the request cannot be performed
Definition at line 717 of file VRequest.cs.
        {
            var unityRequest = new UnityWebRequest(uri, UnityWebRequest.kHttpVerbPUT);
            unityRequest.uploadHandler = new UploadHandlerRaw(putData);
            unityRequest.downloadHandler = new DownloadHandlerBuffer();
            return RequestJson(unityRequest, onComplete);
        }
RequestJsonPut< TData >() [2/2]
bool Meta.WitAi.Requests.VRequest.RequestJsonPut< TData > (Uri uri, string putText, RequestCompleteDelegate< TData > onComplete)
Performs a json put request with a string.
Parameters
uri The uri to be requested
putText The string to be uploaded
onComplete The delegate upon completion
Template Parameters
TData The struct or class to be deserialized to
Returns
False if the request cannot be performed
Definition at line 733 of file VRequest.cs.
        {
            return RequestJsonPut(uri, Encoding.UTF8.GetBytes(putText), onComplete);
        }
RequestText()
bool Meta.WitAi.Requests.VRequest.RequestText (UnityWebRequest unityRequest, RequestCompleteDelegate< string > onComplete)
Performs a text request & handles the resultant text.
Parameters
unityRequest The unity request performing the post or get
onComplete The delegate upon completion
Definition at line 594 of file VRequest.cs.
        {
            return Request(unityRequest, (response, error) =>
            {
                // Request error
                string text = response?.downloadHandler?.text;
                if (!string.IsNullOrEmpty(error))
                {
                    onComplete?.Invoke(text, error);
                    return;
                }
                // No text returned
                if (string.IsNullOrEmpty(text))
                {
                    onComplete?.Invoke(string.Empty, "No response contents found");
                    return;
                }
                // Success
                onComplete?.Invoke(text, string.Empty);
            });
        }
Unload()
virtual void Meta.WitAi.Requests.VRequest.Unload () protected virtual
Definition at line 298 of file VRequest.cs.
        {
            // Cancel coroutine
            if (_coroutine != null)
            {
                _coroutine.CoroutineCancel();
                _coroutine = null;
            }
            // Complete
            if (IsPerforming)
            {
                IsPerforming = false;
                _requestCount--;
            }
            // Remove delegates
            _onDownloadProgress = null;
            _onFirstResponse = null;
            _onComplete = null;
            // Dispose
            if (_request != null)
            {
                // Additional cleanup
                if (_request.downloadHandler is AudioStreamHandler audioStreamer)
                {
                    audioStreamer.CleanUp();
                }
                // Dispose handlers
                _request.uploadHandler?.Dispose();
                _request.downloadHandler?.Dispose();
                // Dispose request
                _request.Dispose();
                _request = null;
            }
            // Officially complete
            IsComplete = true;
        }
Member Data Documentation
_coroutine
CoroutineUtility.CoroutinePerformer Meta.WitAi.Requests.VRequest._coroutine private
Definition at line 90 of file VRequest.cs.
_onComplete
RequestCompleteDelegate<UnityWebRequest> Meta.WitAi.Requests.VRequest._onComplete private
Definition at line 87 of file VRequest.cs.
_onDownloadProgress
RequestProgressDelegate Meta.WitAi.Requests.VRequest._onDownloadProgress private
Definition at line 85 of file VRequest.cs.
_onFirstResponse
RequestFirstResponseDelegate Meta.WitAi.Requests.VRequest._onFirstResponse private
Definition at line 86 of file VRequest.cs.
_request
UnityWebRequest Meta.WitAi.Requests.VRequest._request private
Definition at line 83 of file VRequest.cs.
_requestCount
int Meta.WitAi.Requests.VRequest._requestCount = 0 static private
Definition at line 44 of file VRequest.cs.
MaxConcurrentRequests
int Meta.WitAi.Requests.VRequest.MaxConcurrentRequests = 3 static
Will only start new requests if there are less than this number If <= 0, then all requests will run immediately.
Definition at line 42 of file VRequest.cs.
Property Documentation
DownloadProgress
float Meta.WitAi.Requests.VRequest.DownloadProgress = 0f get private set
Current progress for download.
Definition at line 80 of file VRequest.cs.
{ get; private set; } = 0f;
IsComplete
bool Meta.WitAi.Requests.VRequest.IsComplete = false get private set
Whether or not the completion delegate has been called.
Definition at line 67 of file VRequest.cs.
{ get; private set; } = false;
IsPerforming
bool Meta.WitAi.Requests.VRequest.IsPerforming = false get private set
If request is currently being performed.
Definition at line 62 of file VRequest.cs.
{ get; private set; } = false;
ResponseCode
int Meta.WitAi.Requests.VRequest.ResponseCode = 0 get set
Response Code if applicable.
Definition at line 71 of file VRequest.cs.
{ get; set; } = 0;
Timeout
int Meta.WitAi.Requests.VRequest.Timeout = 5 get set
Timeout in seconds.
Definition at line 57 of file VRequest.cs.
{ get; set; } = 5;
UploadProgress
float Meta.WitAi.Requests.VRequest.UploadProgress = 0f get private set
Current progress for get requests.
Definition at line 76 of file VRequest.cs.
{ get; private set; } = 0f;
The documentation for this class was generated from the following file:
Assets/Oculus/Voice/Lib/Wit.ai/Lib/Wit/Runtime/Requests/UnityRequests/VRequest.cs