VR_Test: Oculus.Interaction.Grab.GrabSurfaces.SphereGrabSurface Class Reference
Oculus.Interaction.Grab.GrabSurfaces.SphereGrabSurface Class Reference
Specifies an entire sphere around an object in which the grip point is valid. One of the main advantages of spheres is that the rotation of the hand pose does not really matters, as it will always fit the surface correctly.
Public Member Functions
Pose GetReferencePose (Transform relativeTo)
The reference pose of the surface. It defines the radius of the sphere as the point from the relative transform to the reference pose to ensure that the sphere covers this pose.
Vector3 GetCentre (Transform relativeTo)
The center of the sphere in world coordinates.
void SetCentre (Vector3 point, Transform relativeTo)
float GetRadius (Transform relativeTo)
The radius of the sphere, this is automatically calculated as the distance between the center and the original grip pose.
Vector3 GetDirection (Transform relativeTo)
The direction of the sphere, measured from the center to the original grip position.
Pose MirrorPose (in Pose pose, Transform relativeTo)
Method for mirroring a Pose around the surface. Different surfaces will prefer mirroring along different axis.
bool CalculateBestPoseAtSurface (Ray targetRay, out Pose bestPose, Transform relativeTo)
Finds the Pose at the surface that is the closest to the given ray.
GrabPoseScore CalculateBestPoseAtSurface (in Pose targetPose, out Pose bestPose, in PoseMeasureParameters scoringModifier, Transform relativeTo)
Finds the Pose at the surface that is the closest to the given pose.
IGrabSurface CreateMirroredSurface (GameObject gameObject)
Creates a new IGrabSurface under the selected gameobject that is a mirror version of the current.
IGrabSurface CreateDuplicatedSurface (GameObject gameObject)
Creates a new IGrabSurface under the selected gameobject with the same data as this one.
void InjectAllSphereSurface (SphereGrabSurfaceData data, Transform relativeTo)
void InjectData (SphereGrabSurfaceData data)
void InjectRelativeTo (Transform relativeTo)
Protected Member Functions
virtual void Reset ()
virtual void Start ()
Vector3 NearestPointInSurface (Vector3 targetPosition, Transform relativeTo)
Pose MinimalRotationPoseAtSurface (in Pose userPose, Transform relativeTo)
Pose MinimalTranslationPoseAtSurface (in Pose userPose, Transform relativeTo)
Quaternion RotationAtPoint (Vector3 surfacePoint, Quaternion baseRot, Quaternion desiredRotation, Transform relativeTo)
Protected Attributes
SphereGrabSurfaceData _data = new SphereGrabSurfaceData()
Properties
Pose RelativePose [get]
Private Attributes
Transform _relativeTo
Detailed Description
Specifies an entire sphere around an object in which the grip point is valid. One of the main advantages of spheres is that the rotation of the hand pose does not really matters, as it will always fit the surface correctly.
Definition at line 51 of file SphereGrabSurface.cs.
Member Function Documentation
CalculateBestPoseAtSurface() [1/2]
GrabPoseScore Oculus.Interaction.Grab.GrabSurfaces.SphereGrabSurface.CalculateBestPoseAtSurface (in Pose targetPose, out Pose bestPose, in PoseMeasureParameters scoringModifier, Transform relativeTo)
Finds the Pose at the surface that is the closest to the given pose.
Parameters
targetPose The pose to find the nearest to.
bestPose The best found pose at the surface.<
scoringModifier Weight used to decide which target pose to select
relativeTo Reference transform to measure the poses against
Returns
The score indicating how good the found pose was, -1 for invalid result.
Implements Oculus.Interaction.Grab.GrabSurfaces.IGrabSurface.
Definition at line 153 of file SphereGrabSurface.cs.
        {
            return GrabPoseHelper.CalculateBestPoseAtSurface(targetPose, out bestPose,
                scoringModifier, relativeTo,
                MinimalTranslationPoseAtSurface,
                MinimalRotationPoseAtSurface);
        }
References Oculus.Interaction.Grab.GrabPoseHelper.CalculateBestPoseAtSurface().
CalculateBestPoseAtSurface() [2/2]
bool Oculus.Interaction.Grab.GrabSurfaces.SphereGrabSurface.CalculateBestPoseAtSurface (Ray targetRay, out Pose bestPose, Transform relativeTo)
Finds the Pose at the surface that is the closest to the given ray.
Parameters
targetRay Ray searching for the nearest snap pose
bestPose The best found pose at the surface.
relativeTo Reference transform to measure the poses against
Returns
True if the pose was found
Implements Oculus.Interaction.Grab.GrabSurfaces.IGrabSurface.
Definition at line 133 of file SphereGrabSurface.cs.
        {
            Vector3 centre = GetCentre(relativeTo);
            Vector3 projection = Vector3.Project(centre - targetRay.origin, targetRay.direction);
            Vector3 nearestCentre = targetRay.origin + projection;
            float radius = GetRadius(relativeTo);
            float distanceToSurface = Mathf.Max(Vector3.Distance(centre, nearestCentre) - radius);
            if (distanceToSurface < radius)
            {
                float adjustedDistance = Mathf.Sqrt(radius * radius - distanceToSurface * distanceToSurface);
                nearestCentre -= targetRay.direction * adjustedDistance;
            }
            Pose recordedPose = GetReferencePose(relativeTo);
            Vector3 surfacePoint = NearestPointInSurface(nearestCentre, relativeTo);
            Pose desiredPose = new Pose(surfacePoint, recordedPose.rotation);
            bestPose = MinimalTranslationPoseAtSurface(desiredPose, relativeTo);
            return true;
        }
References Oculus.Interaction.Grab.GrabSurfaces.SphereGrabSurface.GetCentre(), Oculus.Interaction.Grab.GrabSurfaces.SphereGrabSurface.GetRadius(), and Oculus.Interaction.Grab.GrabSurfaces.SphereGrabSurface.GetReferencePose().
CreateDuplicatedSurface()
IGrabSurface Oculus.Interaction.Grab.GrabSurfaces.SphereGrabSurface.CreateDuplicatedSurface (GameObject gameObject)
Creates a new IGrabSurface under the selected gameobject with the same data as this one.
Parameters
gameObject The gameobject in which to place the new IGrabSurface.
Returns
A clone of this IGrabSurface.
Implements Oculus.Interaction.Grab.GrabSurfaces.IGrabSurface.
Definition at line 169 of file SphereGrabSurface.cs.
        {
            SphereGrabSurface surface = gameObject.AddComponent<SphereGrabSurface>();
            surface._data = _data;
            return surface;
        }
CreateMirroredSurface()
IGrabSurface Oculus.Interaction.Grab.GrabSurfaces.SphereGrabSurface.CreateMirroredSurface (GameObject gameObject)
Creates a new IGrabSurface under the selected gameobject that is a mirror version of the current.
Parameters
gameObject The gameobject in which to place the new IGrabSurface.
Returns
A mirror of this IGrabSurface.
Implements Oculus.Interaction.Grab.GrabSurfaces.IGrabSurface.
Definition at line 162 of file SphereGrabSurface.cs.
        {
            SphereGrabSurface surface = gameObject.AddComponent<SphereGrabSurface>();
            surface._data = _data.Mirror();
            return surface;
        }
GetCentre()
Vector3 Oculus.Interaction.Grab.GrabSurfaces.SphereGrabSurface.GetCentre (Transform relativeTo)
The center of the sphere in world coordinates.
Parameters
relativeTo The reference transform to apply the surface to
Returns
Position in world space
Definition at line 79 of file SphereGrabSurface.cs.
        {
            return relativeTo.TransformPoint(_data.centre);
        }
GetDirection()
Vector3 Oculus.Interaction.Grab.GrabSurfaces.SphereGrabSurface.GetDirection (Transform relativeTo)
The direction of the sphere, measured from the center to the original grip position.
Parameters
relativeTo The reference transform to apply the surface to
Returns
Direction in world space
Definition at line 106 of file SphereGrabSurface.cs.
        {
            Vector3 centre = GetCentre(relativeTo);
            Pose referencePose = GetReferencePose(relativeTo);
            return (referencePose.position - centre).normalized;
        }
References Oculus.Interaction.Grab.GrabSurfaces.SphereGrabSurface.GetCentre(), and Oculus.Interaction.Grab.GrabSurfaces.SphereGrabSurface.GetReferencePose().
GetRadius()
float Oculus.Interaction.Grab.GrabSurfaces.SphereGrabSurface.GetRadius (Transform relativeTo)
The radius of the sphere, this is automatically calculated as the distance between the center and the original grip pose.
Parameters
relativeTo The reference transform to apply the surface to
Returns
Distance in world space
Definition at line 94 of file SphereGrabSurface.cs.
        {
            Vector3 centre = GetCentre(relativeTo);
            Pose referencePose = GetReferencePose(relativeTo);
            return Vector3.Distance(centre, referencePose.position);
        }
References Oculus.Interaction.Grab.GrabSurfaces.SphereGrabSurface.GetCentre(), and Oculus.Interaction.Grab.GrabSurfaces.SphereGrabSurface.GetReferencePose().
GetReferencePose()
Pose Oculus.Interaction.Grab.GrabSurfaces.SphereGrabSurface.GetReferencePose (Transform relativeTo)
The reference pose of the surface. It defines the radius of the sphere as the point from the relative transform to the reference pose to ensure that the sphere covers this pose.
Parameters
relativeTo The reference transform to apply the surface to
Returns
Pose in world space
Definition at line 69 of file SphereGrabSurface.cs.
        {
            return PoseUtils.GlobalPoseScaled(relativeTo, RelativePose);
        }
References Oculus.Interaction.PoseUtils.GlobalPoseScaled().
InjectAllSphereSurface()
void Oculus.Interaction.Grab.GrabSurfaces.SphereGrabSurface.InjectAllSphereSurface (SphereGrabSurfaceData data, Transform relativeTo)
Definition at line 221 of file SphereGrabSurface.cs.
        {
            InjectData(data);
            InjectRelativeTo(relativeTo);
        }
InjectData()
void Oculus.Interaction.Grab.GrabSurfaces.SphereGrabSurface.InjectData (SphereGrabSurfaceData data)
Definition at line 227 of file SphereGrabSurface.cs.
        {
            _data = data;
        }
InjectRelativeTo()
void Oculus.Interaction.Grab.GrabSurfaces.SphereGrabSurface.InjectRelativeTo (Transform relativeTo)
Definition at line 232 of file SphereGrabSurface.cs.
        {
            _relativeTo = relativeTo;
        }
MinimalRotationPoseAtSurface()
Pose Oculus.Interaction.Grab.GrabSurfaces.SphereGrabSurface.MinimalRotationPoseAtSurface (in Pose userPose, Transform relativeTo) protected
Definition at line 184 of file SphereGrabSurface.cs.
        {
            Vector3 centre = GetCentre(relativeTo);
            Pose referencePose = GetReferencePose(relativeTo);
            float radius = GetRadius(relativeTo);
            Quaternion rotCorrection = userPose.rotation * Quaternion.Inverse(referencePose.rotation);
            Vector3 correctedDir = rotCorrection * GetDirection(relativeTo);
            Vector3 surfacePoint = NearestPointInSurface(centre + correctedDir * radius, relativeTo);
            Quaternion surfaceRotation = RotationAtPoint(surfacePoint, referencePose.rotation, userPose.rotation, relativeTo);
            return new Pose(surfacePoint, surfaceRotation);
        }
MinimalTranslationPoseAtSurface()
Pose Oculus.Interaction.Grab.GrabSurfaces.SphereGrabSurface.MinimalTranslationPoseAtSurface (in Pose userPose, Transform relativeTo) protected
Definition at line 197 of file SphereGrabSurface.cs.
        {
            Pose referencePose = GetReferencePose(relativeTo);
            Vector3 desiredPos = userPose.position;
            Quaternion baseRot = referencePose.rotation;
            Vector3 surfacePoint = NearestPointInSurface(desiredPos, relativeTo);
            Quaternion surfaceRotation = RotationAtPoint(surfacePoint, baseRot, userPose.rotation, relativeTo);
            return new Pose(surfacePoint, surfaceRotation);
        }
MirrorPose()
Pose Oculus.Interaction.Grab.GrabSurfaces.SphereGrabSurface.MirrorPose (in Pose gripPose, Transform relativeTo)
Method for mirroring a Pose around the surface. Different surfaces will prefer mirroring along different axis.
Parameters
gripPose The Pose to be mirrored.
relativeTo Reference transform to mirror the pose around
Returns
A new pose mirrored at this surface.
Implements Oculus.Interaction.Grab.GrabSurfaces.IGrabSurface.
Definition at line 126 of file SphereGrabSurface.cs.
        {
            Vector3 normal = Quaternion.Inverse(relativeTo.rotation) * GetDirection(relativeTo);
            Vector3 tangent = Vector3.Cross(normal, Vector3.up);
            return pose.MirrorPoseRotation(normal, tangent);
        }
References Oculus.Interaction.Grab.GrabSurfaces.SphereGrabSurface.GetDirection().
NearestPointInSurface()
Vector3 Oculus.Interaction.Grab.GrabSurfaces.SphereGrabSurface.NearestPointInSurface (Vector3 targetPosition, Transform relativeTo) protected
Definition at line 176 of file SphereGrabSurface.cs.
        {
            Vector3 centre = GetCentre(relativeTo);
            Vector3 direction = (targetPosition - centre).normalized;
            float radius = GetRadius(relativeTo);
            return centre + direction * radius;
        }
Reset()
virtual void Oculus.Interaction.Grab.GrabSurfaces.SphereGrabSurface.Reset () protected virtual
Definition at line 114 of file SphereGrabSurface.cs.
        {
            _relativeTo = this.GetComponentInParent<IRelativeToRef>()?.RelativeTo;
        }
RotationAtPoint()
Quaternion Oculus.Interaction.Grab.GrabSurfaces.SphereGrabSurface.RotationAtPoint (Vector3 surfacePoint, Quaternion baseRot, Quaternion desiredRotation, Transform relativeTo) protected
Definition at line 207 of file SphereGrabSurface.cs.
        {
            Vector3 desiredDirection = (surfacePoint - GetCentre(relativeTo)).normalized;
            Quaternion targetRotation = Quaternion.FromToRotation(GetDirection(relativeTo), desiredDirection) * baseRot;
            Vector3 targetProjected = Vector3.ProjectOnPlane(targetRotation * Vector3.forward, desiredDirection).normalized;
            Vector3 desiredProjected = Vector3.ProjectOnPlane(desiredRotation * Vector3.forward, desiredDirection).normalized;
            Quaternion rotCorrection = Quaternion.FromToRotation(targetProjected, desiredProjected);
            return rotCorrection * targetRotation;
        }
SetCentre()
void Oculus.Interaction.Grab.GrabSurfaces.SphereGrabSurface.SetCentre (Vector3 point, Transform relativeTo)
Definition at line 83 of file SphereGrabSurface.cs.
        {
            _data.centre = relativeTo.InverseTransformPoint(point);
        }
Start()
virtual void Oculus.Interaction.Grab.GrabSurfaces.SphereGrabSurface.Start () protected virtual
Definition at line 120 of file SphereGrabSurface.cs.
        {
            this.AssertField(_data, nameof(_data));
            this.AssertField(_relativeTo, nameof(_relativeTo));
        }
Member Data Documentation
_data
SphereGrabSurfaceData Oculus.Interaction.Grab.GrabSurfaces.SphereGrabSurface._data = new SphereGrabSurfaceData() protected
Definition at line 54 of file SphereGrabSurface.cs.
_relativeTo
Transform Oculus.Interaction.Grab.GrabSurfaces.SphereGrabSurface._relativeTo private
Definition at line 58 of file SphereGrabSurface.cs.
Property Documentation
RelativePose
Pose Oculus.Interaction.Grab.GrabSurfaces.SphereGrabSurface.RelativePose get private
Definition at line 60 of file SphereGrabSurface.cs.
The documentation for this class was generated from the following file:
Assets/Oculus/Interaction/Runtime/Scripts/Grab/SnapSurfaces/SphereGrabSurface.cs