VR_Test: OVRLipSync Class Reference
OVRLipSync Class Reference
OVRLipSync interfaces into the Oculus lip sync engine. This component should be added into the scene once.
Classes
class Frame
NOTE: Opaque typedef for lip-sync context is an unsigned int (uint)
Public Types
enum Result {
Success = 0 , Unknown = -2200 , CannotCreateContext = -2201 , InvalidParam = -2202 ,
BadSampleRate = -2203 , MissingDLL = -2204 , BadVersion = -2205 , UndefinedFunction = -2206
}
enum AudioDataType { S16_Mono , S16_Stereo , F32_Mono , F32_Stereo }
enum Viseme {
sil , PP , FF , TH ,
DD , kk , CH , SS ,
nn , RR , aa , E ,
ih , oh , ou
}
enum Signals {
VisemeOn , VisemeOff , VisemeAmount , VisemeSmoothing ,
LaughterAmount
}
enum ContextProviders { Original , Enhanced , Enhanced_with_Laughter }
Static Public Member Functions
static Result Initialize ()
static Result Initialize (int sampleRate, int bufferSize)
static void Shutdown ()
static Result IsInitialized ()
Determines if is initialized.
static Result CreateContext (ref uint context, ContextProviders provider, int sampleRate=0, bool enableAcceleration=false)
Creates a lip-sync context.
static Result CreateContextWithModelFile (ref uint context, ContextProviders provider, string modelPath, int sampleRate=0, bool enableAcceleration=false)
Creates a lip-sync context with specified model file.
static Result DestroyContext (uint context)
Destroy a lip-sync context.
static Result ResetContext (uint context)
Resets the context.
static Result SendSignal (uint context, Signals signal, int arg1, int arg2)
Sends a signal to the lip-sync engine.
static Result ProcessFrame (uint context, float[] audioBuffer, Frame frame, bool stereo=true)
Process float[] audio buffer by lip-sync engine.
static Result ProcessFrame (uint context, short[] audioBuffer, Frame frame, bool stereo=true)
Process short[] audio buffer by lip-sync engine.
Static Public Attributes
static readonly int VisemeCount = Enum.GetNames(typeof(Viseme)).Length
static readonly int SignalCount = Enum.GetNames(typeof(Signals)).Length
const string strOVRLS = "OVRLipSync"
static OVRLipSync sInstance = null
Private Member Functions
static int ovrLipSyncDll_Initialize (int samplerate, int buffersize)
static void ovrLipSyncDll_Shutdown ()
static IntPtr ovrLipSyncDll_GetVersion (ref int Major, ref int Minor, ref int Patch)
static int ovrLipSyncDll_CreateContextEx (ref uint context, ContextProviders provider, int sampleRate, bool enableAcceleration)
static int ovrLipSyncDll_CreateContextWithModelFile (ref uint context, ContextProviders provider, string modelPath, int sampleRate, bool enableAcceleration)
static int ovrLipSyncDll_DestroyContext (uint context)
static int ovrLipSyncDll_ResetContext (uint context)
static int ovrLipSyncDll_SendSignal (uint context, Signals signal, int arg1, int arg2)
static int ovrLipSyncDll_ProcessFrameEx (uint context, IntPtr audioBuffer, uint bufferSize, AudioDataType dataType, ref int frameNumber, ref int frameDelay, float[] visemes, int visemeCount, ref float laughterScore, float[] laughterCategories, int laughterCategoriesLength)
void Awake ()
Awake this instance.
void OnDestroy ()
Raises the destroy event.
Static Private Attributes
static Result sInitialized = Result.Unknown
Detailed Description
OVRLipSync interfaces into the Oculus lip sync engine. This component should be added into the scene once.
Definition at line 35 of file OVRLipSync.cs.
Member Enumeration Documentation
AudioDataType
enum OVRLipSync.AudioDataType
Definition at line 51 of file OVRLipSync.cs.
    {
        // Signed 16-bit integer mono audio stream
        S16_Mono,
        // Signed 16-bit integer stereo audio stream
        S16_Stereo,
        // Signed 32-bit float mono audio stream
        F32_Mono,
        // Signed 32-bit float stereo audio stream
        F32_Stereo
    };
ContextProviders
enum OVRLipSync.ContextProviders
Definition at line 98 of file OVRLipSync.cs.
    {
        Original,
        Enhanced,
        Enhanced_with_Laughter,
    };
Result
enum OVRLipSync.Result
Definition at line 38 of file OVRLipSync.cs.
    {
        Success = 0,
        Unknown = -2200,  //< An unknown error has occurred
        CannotCreateContext = -2201,  //< Unable to create a context
        InvalidParam = -2202,  //< An invalid parameter, e.g. NULL pointer or out of range
        BadSampleRate = -2203,  //< An unsupported sample rate was declared
        MissingDLL = -2204,  //< The DLL or shared library could not be found
        BadVersion = -2205,  //< Mismatched versions between header and libs
        UndefinedFunction = -2206   //< An undefined function
    };
Signals
enum OVRLipSync.Signals
Definition at line 86 of file OVRLipSync.cs.
    {
        VisemeOn,
        VisemeOff,
        VisemeAmount,
        VisemeSmoothing,
        LaughterAmount
    };
Viseme
enum OVRLipSync.Viseme
Definition at line 64 of file OVRLipSync.cs.
    {
        sil,
        PP,
        FF,
        TH,
        DD,
        kk,
        CH,
        SS,
        nn,
        RR,
        aa,
        E,
        ih,
        oh,
        ou
    };
Member Function Documentation
Awake()
void OVRLipSync.Awake () private
Awake this instance.
Definition at line 202 of file OVRLipSync.cs.
    {
        // We can only have one instance of OVRLipSync in a scene (use this for local property query)
        if (sInstance == null)
        {
            sInstance = this;
        }
        else
        {
            Debug.LogWarning(System.String.Format("OVRLipSync Awake: Only one instance of OVRPLipSync can exist in the scene."));
            return;
        }
        if (IsInitialized() != Result.Success)
        {
            sInitialized = Initialize();
            if (sInitialized != Result.Success)
            {
                Debug.LogWarning(System.String.Format
                ("OvrLipSync Awake: Failed to init Speech Rec library"));
            }
        }
        // Important: Use the touchpad mechanism for input, call Create on the OVRTouchpad helper class
        OVRTouchpad.Create();
    }
References IsInitialized().
CreateContext()
static Result OVRLipSync.CreateContext (ref uint context, ContextProviders provider, int sampleRate = 0, bool enableAcceleration = false) static
Creates a lip-sync context.
Returns
error code
Parameters
context Context.
provider Provider.
enableAcceleration Enable DSP Acceleration.
Definition at line 303 of file OVRLipSync.cs.
    {
        if (IsInitialized() != Result.Success && Initialize() != Result.Success)
            return Result.CannotCreateContext;
        return (Result)ovrLipSyncDll_CreateContextEx(ref context, provider, sampleRate, enableAcceleration);
    }
References IsInitialized().
CreateContextWithModelFile()
static Result OVRLipSync.CreateContextWithModelFile (ref uint context, ContextProviders provider, string modelPath, int sampleRate = 0, bool enableAcceleration = false) static
Creates a lip-sync context with specified model file.
Returns
error code
Parameters
context Context.
provider Provider.
modelPath Model Dir.
sampleRate Sampling Rate.
enableAcceleration Enable DSP Acceleration.
Definition at line 324 of file OVRLipSync.cs.
    {
        if (IsInitialized() != Result.Success && Initialize() != Result.Success)
            return Result.CannotCreateContext;
        return (Result)ovrLipSyncDll_CreateContextWithModelFile(
            ref context,
            provider,
            modelPath,
            sampleRate,
            enableAcceleration);
    }
References IsInitialized().
DestroyContext()
static Result OVRLipSync.DestroyContext (uint context) static
Destroy a lip-sync context.
Returns
The context.
Parameters
context Context.
Definition at line 347 of file OVRLipSync.cs.
    {
        if (IsInitialized() != Result.Success)
            return Result.Unknown;
        return (Result)ovrLipSyncDll_DestroyContext(context);
    }
References IsInitialized().
Initialize() [1/2]
static Result OVRLipSync.Initialize () static
Definition at line 252 of file OVRLipSync.cs.
    {
        int sampleRate;
        int bufferSize;
        int numbuf;
        // Get the current sample rate
        sampleRate = AudioSettings.outputSampleRate;
        // Get the current buffer size and number of buffers
        AudioSettings.GetDSPBufferSize(out bufferSize, out numbuf);
        String str = System.String.Format
        ("OvrLipSync Awake: Queried SampleRate: {0:F0} BufferSize: {1:F0}", sampleRate, bufferSize);
        Debug.LogWarning(str);
        sInitialized = (Result)ovrLipSyncDll_Initialize(sampleRate, bufferSize);
        return sInitialized;
    }
Initialize() [2/2]
static Result OVRLipSync.Initialize (int sampleRate, int bufferSize) static
Definition at line 271 of file OVRLipSync.cs.
    {
        String str = System.String.Format
        ("OvrLipSync Awake: Queried SampleRate: {0:F0} BufferSize: {1:F0}", sampleRate, bufferSize);
        Debug.LogWarning(str);
        sInitialized = (Result)ovrLipSyncDll_Initialize(sampleRate, bufferSize);
        return sInitialized;
    }
IsInitialized()
static Result OVRLipSync.IsInitialized () static
Determines if is initialized.
Returns
true if is initialized; otherwise, false.
Definition at line 291 of file OVRLipSync.cs.
    {
        return sInitialized;
    }
OnDestroy()
void OVRLipSync.OnDestroy () private
Raises the destroy event.
Definition at line 234 of file OVRLipSync.cs.
    {
        if (sInstance != this)
        {
            Debug.LogWarning(
            "OVRLipSync OnDestroy: This is not the correct OVRLipSync instance.");
            return;
        }
        // Do not shut down at this time
        //      ovrLipSyncDll_Shutdown();
        //      sInitialized = (int)Result.Unknown;
    }
ProcessFrame() [1/2]
static Result OVRLipSync.ProcessFrame (uint context, float[] audioBuffer, Frame frame, bool stereo = true) static
Process float[] audio buffer by lip-sync engine.
Returns
error code
Parameters
context Context.
audioBuffer PCM audio buffer.
frame Lip-sync Frame.
stereo Whether buffer is part of stereo or mono stream.
Definition at line 392 of file OVRLipSync.cs.
    {
        if (IsInitialized() != Result.Success)
            return Result.Unknown;
        var dataType = stereo ? AudioDataType.F32_Stereo : AudioDataType.F32_Mono;
        var numSamples = (uint)(stereo ? audioBuffer.Length / 2 : audioBuffer.Length);
        var handle = GCHandle.Alloc(audioBuffer, GCHandleType.Pinned);
        var rc = ovrLipSyncDll_ProcessFrameEx(context,
                                              handle.AddrOfPinnedObject(), numSamples, dataType,
                                              ref frame.frameNumber, ref frame.frameDelay,
                                              frame.Visemes, frame.Visemes.Length,
                                              ref frame.laughterScore,
                                              null, 0
                                              );
        handle.Free();
        return (Result)rc;
    }
References IsInitialized().
ProcessFrame() [2/2]
static Result OVRLipSync.ProcessFrame (uint context, short[] audioBuffer, Frame frame, bool stereo = true) static
Process short[] audio buffer by lip-sync engine.
Returns
error code
Parameters
context Context.
audioBuffer PCM audio buffer.
frame Lip-sync Frame.
stereo Whether buffer is part of stereo or mono stream.
Definition at line 421 of file OVRLipSync.cs.
    {
        if (IsInitialized() != Result.Success)
            return Result.Unknown;
        var dataType = stereo ? AudioDataType.S16_Stereo : AudioDataType.S16_Mono;
        var numSamples = (uint)(stereo ? audioBuffer.Length / 2 : audioBuffer.Length);
        var handle = GCHandle.Alloc(audioBuffer, GCHandleType.Pinned);
        var rc = ovrLipSyncDll_ProcessFrameEx(context,
                                              handle.AddrOfPinnedObject(), numSamples, dataType,
                                              ref frame.frameNumber, ref frame.frameDelay,
                                              frame.Visemes, frame.Visemes.Length,
                                              ref frame.laughterScore,
                                              null, 0
                                              );
        handle.Free();
        return (Result)rc;
    }
References IsInitialized().
ResetContext()
static Result OVRLipSync.ResetContext (uint context) static
Resets the context.
Returns
error code
Parameters
context Context.
Definition at line 360 of file OVRLipSync.cs.
    {
        if (IsInitialized() != Result.Success)
            return Result.Unknown;
        return (Result)ovrLipSyncDll_ResetContext(context);
    }
References IsInitialized().
SendSignal()
static Result OVRLipSync.SendSignal (uint context, Signals signal, int arg1, int arg2) static
Sends a signal to the lip-sync engine.
Returns
error code
Parameters
context Context.
signal Signal.
arg1 Arg1.
arg2 Arg2.
Definition at line 376 of file OVRLipSync.cs.
    {
        if (IsInitialized() != Result.Success)
            return Result.Unknown;
        return (Result)ovrLipSyncDll_SendSignal(context, signal, arg1, arg2);
    }
References IsInitialized().
Shutdown()
static void OVRLipSync.Shutdown () static
Definition at line 281 of file OVRLipSync.cs.
    {
        ovrLipSyncDll_Shutdown();
        sInitialized = Result.Unknown;
    }
Member Data Documentation
SignalCount
readonly int OVRLipSync.SignalCount = Enum.GetNames(typeof(Signals)).Length static
Definition at line 95 of file OVRLipSync.cs.
sInitialized
Result OVRLipSync.sInitialized = Result.Unknown static private
Definition at line 190 of file OVRLipSync.cs.
sInstance
OVRLipSync OVRLipSync.sInstance = null static
Definition at line 193 of file OVRLipSync.cs.
strOVRLS
const string OVRLipSync.strOVRLS = "OVRLipSync" static
Definition at line 136 of file OVRLipSync.cs.
VisemeCount
readonly int OVRLipSync.VisemeCount = Enum.GetNames(typeof(Viseme)).Length static
Definition at line 83 of file OVRLipSync.cs.
The documentation for this class was generated from the following file:
Assets/Oculus/LipSync/Scripts/OVRLipSync.cs