VR_Test: Meta.WitAi.Wit Class Reference
Meta.WitAi.Wit Class Reference
Public Member Functions
override VoiceServiceRequest Activate (string text, WitRequestOptions requestOptions, VoiceServiceRequestEvents requestEvents)
Send text data for NLU processing with custom request options & events.
override VoiceServiceRequest Activate (WitRequestOptions requestOptions, VoiceServiceRequestEvents requestEvents)
Activate the microphone and wait for threshold and then send data.
override VoiceServiceRequest ActivateImmediately (WitRequestOptions requestOptions, VoiceServiceRequestEvents requestEvents)
Activate the microphone and send data for NLU processing with custom request options.
override void Deactivate ()
Stop listening and submit the collected microphone data for processing.
override void DeactivateAndAbortRequest ()
Stop listening and abort any requests that may be active without waiting for a response.
Public Member Functions inherited from Meta.WitAi.VoiceService
void Activate (string text)
Send text data for NLU processing. Results will return the same way a voice based activation would.
void Activate (string text, WitRequestOptions requestOptions)
Send text data for NLU processing. Results will return the same way a voice based activation would.
VoiceServiceRequest Activate (string text, VoiceServiceRequestEvents requestEvents)
Send text data for NLU processing. Results will return the same way a voice based activation would.
VoiceServiceRequest Activate (string text, WitRequestOptions requestOptions, VoiceServiceRequestEvents requestEvents)
Send text data for NLU processing with custom request options.
virtual bool CanSend ()
Whether voice requests can be sent or not.
virtual bool CanActivateAudio ()
Whether audio can be activated or not.
void Activate ()
Start listening for sound or speech from the user and start sending data to Wit.ai once sound or speech has been detected.
void Activate (WitRequestOptions requestOptions)
Start listening for sound or speech from the user and start sending data to Wit.ai once sound or speech has been detected.
VoiceServiceRequest Activate (VoiceServiceRequestEvents requestEvents)
Start listening for sound or speech from the user and start sending data to Wit.ai once sound or speech has been detected.
VoiceServiceRequest Activate (WitRequestOptions requestOptions, VoiceServiceRequestEvents requestEvents)
Start listening for sound or speech from the user and start sending data to Wit.ai once sound or speech has been detected.
void ActivateImmediately ()
Activate the microphone and send data for NLU processing immediately without waiting for sound/speech from the user to begin.
void ActivateImmediately (WitRequestOptions requestOptions)
Activate the microphone and send data for NLU processing immediately without waiting for sound/speech from the user to begin.
VoiceServiceRequest ActivateImmediately (VoiceServiceRequestEvents requestEvents)
Activate the microphone and send data for NLU processing immediately without waiting for sound/speech from the user to begin.
VoiceServiceRequest ActivateImmediately (WitRequestOptions requestOptions, VoiceServiceRequestEvents requestEvents)
Activate the microphone and send data for NLU processing immediately without waiting for sound/speech from the user to begin.
void Deactivate ()
Stop listening and submit any remaining buffered microphone data for processing.
void DeactivateAndAbortRequest ()
Stop listening and abort any requests that may be active without waiting for a response.
virtual void DeactivateAndAbortRequest (VoiceServiceRequest request)
Abort a specific request.
IEnumerable< object > GetObjectsOfType (Type type)
Returns objects of the specified type.
Protected Member Functions
override string GetSendError ()
Check for error that will occur if attempting to send data.
override string GetActivateAudioError ()
override void Awake ()
Protected Member Functions inherited from Meta.WitAi.VoiceService
VoiceService ()
Constructs a VoiceService
virtual void OnTextRequestCreated (VoiceServiceRequest textRequest)
Called on text request creation.
virtual void HandleRequestResults (VoiceServiceRequest request)
Called after request cancellation, failure or success.
string GetActivateAudioError ()
Check for error that will occur if attempting to read an audio source.
virtual void OnAudioRequestCreated (VoiceServiceRequest audioRequest)
Called on creation.
virtual void OnAudioPartialResponse (VoiceServiceRequest audioRequest)
virtual void OnEnable ()
virtual void OnDisable ()
virtual void OnFinalTranscription (string transcription)
Activate message if transcription provider returns a final transcription.
virtual void HandleResponse (WitResponseNode response)
Properties
WitRuntimeConfiguration RuntimeConfiguration [get, set]
override bool Active [get]
Returns true if this voice service is currently active and listening with the mic.
override bool IsRequestActive [get]
Returns true if voice service is currently active or request is transmitting.
override ITranscriptionProvider TranscriptionProvider [get, set]
Easy acccess for transcription.
override bool MicActive [get]
Returns true Mic is still enabled.
override bool ShouldSendMicData [get]
Properties inherited from Meta.WitAi.VoiceService
bool UseConduit [get]
When set to true, Conduit will be used. Otherwise, the legacy dispatching will be used.
WitConfiguration WitConfiguration [get]
Wit configuration accessor via IWitConfigurationProvider.
virtual bool Active [get]
Returns true if this voice service is currently active and listening with the mic.
virtual bool IsRequestActive [get]
Returns true if the service is actively communicating with Wit.ai during an Activation. The mic may or may not still be active while this is true.
ITranscriptionProvider TranscriptionProvider [get, set]
Gets/Sets a custom transcription provider. This can be used to replace any built in asr with an on device model or other provided source.
bool MicActive [get]
Returns true if this voice service is currently reading data from the microphone.
virtual VoiceEvents VoiceEvents [get, set]
All events used for a voice service.
virtual TelemetryEvents TelemetryEvents [get, set]
All events used for a voice service telemetry.
IAudioInputEvents AudioEvents [get]
A subset of events around collection of audio data.
ITranscriptionEvent TranscriptionEvents [get]
A subset of events around receiving transcriptions.
bool ShouldSendMicData [get]
Returns true if the audio input should be read in an activation.
HashSet< VoiceServiceRequest > Requests = new HashSet<VoiceServiceRequest>() [get]
All currently running requests.
Properties inherited from Meta.WitAi.IVoiceService
Properties inherited from Meta.WitAi.IVoiceEventProvider
Properties inherited from Meta.WitAi.ITelemetryEventsProvider
Properties inherited from Meta.WitAi.IVoiceActivationHandler
Properties inherited from Meta.WitAi.Interfaces.IAudioEventProvider
Properties inherited from Meta.WitAi.IWitRuntimeConfigProvider
Private Attributes
WitRuntimeConfiguration witRuntimeConfiguration
WitService witService
Additional Inherited Members
Protected Attributes inherited from Meta.WitAi.VoiceService
VoiceEvents events = new VoiceEvents()
This field should not be accessed outside the Wit-Unity library. If you need access to events you should be using the VoiceService.VoiceEvents property instead.
TelemetryEvents telemetryEvents = new TelemetryEvents()
Detailed Description
Definition at line 17 of file Wit.cs.
Member Function Documentation
Activate() [1/2]
override VoiceServiceRequest Meta.WitAi.Wit.Activate (string text, WitRequestOptions requestOptions, VoiceServiceRequestEvents requestEvents)
Send text data for NLU processing with custom request options & events.
Parameters
text Text to be used for NLU processing
requestOptions Additional options such as dynamic entities
requestEvents Events specific to the request's lifecycle
Implements Meta.WitAi.IVoiceActivationHandler.
Definition at line 66 of file Wit.cs.
        {
            VoiceServiceRequest request = witService.Activate(text, requestOptions, requestEvents);
            OnTextRequestCreated(request);
            return request;
        }
References Meta.WitAi.WitService.Activate(), and Meta.WitAi.VoiceService.OnTextRequestCreated().
Activate() [2/2]
override VoiceServiceRequest Meta.WitAi.Wit.Activate (WitRequestOptions requestOptions, VoiceServiceRequestEvents requestEvents)
Activate the microphone and wait for threshold and then send data.
Parameters
requestOptions Additional options such as dynamic entities
requestEvents Events specific to the request's lifecycle
Implements Meta.WitAi.IVoiceActivationHandler.
Definition at line 73 of file Wit.cs.
        {
            VoiceServiceRequest request = witService.Activate(requestOptions, requestEvents);
            OnAudioRequestCreated(request);
            return request;
        }
References Meta.WitAi.WitService.Activate(), and Meta.WitAi.VoiceService.OnAudioRequestCreated().
ActivateImmediately()
override VoiceServiceRequest Meta.WitAi.Wit.ActivateImmediately (WitRequestOptions requestOptions, VoiceServiceRequestEvents requestEvents)
Activate the microphone and send data for NLU processing with custom request options.
Parameters
requestOptions Additional options such as dynamic entities
requestEvents Events specific to the request's lifecycle
Implements Meta.WitAi.IVoiceActivationHandler.
Definition at line 80 of file Wit.cs.
        {
            VoiceServiceRequest request = witService.ActivateImmediately(requestOptions, requestEvents);
            OnAudioRequestCreated(request);
            return request;
        }
References Meta.WitAi.WitService.ActivateImmediately(), and Meta.WitAi.VoiceService.OnAudioRequestCreated().
Awake()
override void Meta.WitAi.Wit.Awake () protected virtual
Reimplemented from Meta.WitAi.VoiceService.
Definition at line 99 of file Wit.cs.
        {
            base.Awake();
            // WitService is 1:1 tied to a VoiceService. In the event there
            // are multiple voice services on a game object this will ensure
            // that this component has its own dedicated WitService
            witService = gameObject.AddComponent<WitService>();
            witService.VoiceEventProvider = this;
            witService.TelemetryEventsProvider = this;
            witService.ConfigurationProvider = this;
        }
Deactivate()
override void Meta.WitAi.Wit.Deactivate ()
Stop listening and submit the collected microphone data for processing.
Implements Meta.WitAi.IVoiceActivationHandler.
Definition at line 87 of file Wit.cs.
        {
            witService.Deactivate();
        }
References Meta.WitAi.WitService.Deactivate().
DeactivateAndAbortRequest()
override void Meta.WitAi.Wit.DeactivateAndAbortRequest ()
Stop listening and abort any requests that may be active without waiting for a response.
Implements Meta.WitAi.IVoiceActivationHandler.
Definition at line 92 of file Wit.cs.
        {
            witService.DeactivateAndAbortRequest();
        }
References Meta.WitAi.WitService.DeactivateAndAbortRequest().
GetActivateAudioError()
override string Meta.WitAi.Wit.GetActivateAudioError () protected
Definition at line 57 of file Wit.cs.
        {
            if (!AudioBuffer.Instance.IsInputAvailable)
            {
                return "No Microphone(s)/recording devices found.  You will be unable to capture audio on this device.";
            }
            return string.Empty;
        }
GetSendError()
override string Meta.WitAi.Wit.GetSendError () protected virtual
Check for error that will occur if attempting to send data.
Returns
Returns an error if send will not be allowed.
Reimplemented from Meta.WitAi.VoiceService.
Definition at line 44 of file Wit.cs.
        {
            if (!RuntimeConfiguration?.witConfiguration)
            {
                return $"Your {GetType().Name} \"{gameObject.name}\" does not have a wit configuration assigned.   Voice interactions are not possible without the configuration.";
            }
            if (string.IsNullOrEmpty(RuntimeConfiguration.witConfiguration.GetClientAccessToken()))
            {
                return $"The configuration \"{RuntimeConfiguration.witConfiguration.name}\" is not setup with a valid client access token.   Voice interactions are not possible without the token.";
            }
            return base.GetSendError();
        }
Member Data Documentation
witRuntimeConfiguration
WitRuntimeConfiguration Meta.WitAi.Wit.witRuntimeConfiguration private
Definition at line 19 of file Wit.cs.
witService
WitService Meta.WitAi.Wit.witService private
Definition at line 27 of file Wit.cs.
Property Documentation
Active
override bool Meta.WitAi.Wit.Active get
Returns true if this voice service is currently active and listening with the mic.
Implements Meta.WitAi.IVoiceActivationHandler.
Definition at line 30 of file Wit.cs.
IsRequestActive
override bool Meta.WitAi.Wit.IsRequestActive get
Returns true if voice service is currently active or request is transmitting.
Implements Meta.WitAi.IVoiceService.
Definition at line 31 of file Wit.cs.
MicActive
override bool Meta.WitAi.Wit.MicActive get
Returns true Mic is still enabled.
Implements Meta.WitAi.IVoiceService.
Definition at line 37 of file Wit.cs.
RuntimeConfiguration
WitRuntimeConfiguration Meta.WitAi.Wit.RuntimeConfiguration get set
Implements Meta.WitAi.IWitRuntimeConfigProvider.
Definition at line 21 of file Wit.cs.
        {
            get => witRuntimeConfiguration;
            set => witRuntimeConfiguration = value;
        }
ShouldSendMicData
override bool Meta.WitAi.Wit.ShouldSendMicData get protected
Definition at line 38 of file Wit.cs.
TranscriptionProvider
override ITranscriptionProvider Meta.WitAi.Wit.TranscriptionProvider get set
Easy acccess for transcription.
Implements Meta.WitAi.IVoiceService.
Definition at line 32 of file Wit.cs.
        {
            get => witService.TranscriptionProvider;
            set => witService.TranscriptionProvider = value;
        }
The documentation for this class was generated from the following file:
Assets/Oculus/Voice/Lib/Wit.ai/Scripts/Runtime/Wit.cs