VR_Test: OVRScreenFade Class Reference
OVRScreenFade Class Reference
Fades the screen from black after a new scene is loaded. Fade can also be controlled mid-scene using SetUIFade and SetFadeLevel.
Public Member Functions
void FadeIn ()
Start a fade in.
void FadeOut ()
Start a fade out.
void SetUIFade (float level)
Set the UI fade level - fade due to UI in foreground.
void SetExplicitFade (float level)
Override current fade level.
Public Attributes
float fadeTime = 2.0f
Color fadeColor = new Color(0.01f, 0.01f, 0.01f, 1.0f)
bool fadeOnStart = true
int renderQueue = 5000
The render queue used by the fade mesh. Reduce this if you need to render on top of it.
Properties
static OVRScreenFade instance [get, private set]
float currentAlpha [get]
Renders the current alpha value being used to fade the screen.
Private Member Functions
void Start ()
Automatically starts a fade in.
void OnLevelFinishedLoading (int level)
Starts a fade in when a new level is loaded.
void OnEnable ()
void OnDestroy ()
Cleans up the fade material.
IEnumerator Fade (float startAlpha, float endAlpha)
Fades alpha from 1.0 to 0.0.
void SetMaterialAlpha ()
Update material alpha. UI fade and the current fade due to fade in/out animations (or explicit control) both affect the fade. (The max is taken)
Private Attributes
float explicitFadeAlpha = 0.0f
float animatedFadeAlpha = 0.0f
float uiFadeAlpha = 0.0f
MeshRenderer fadeRenderer
MeshFilter fadeMesh
Material fadeMaterial = null
bool isFading = false
Detailed Description
Fades the screen from black after a new scene is loaded. Fade can also be controlled mid-scene using SetUIFade and SetFadeLevel.
Definition at line 27 of file OVRScreenFade.cs.
Member Function Documentation
Fade()
IEnumerator OVRScreenFade.Fade (float startAlpha, float endAlpha) private
Fades alpha from 1.0 to 0.0.
Definition at line 208 of file OVRScreenFade.cs.
    {
        float elapsedTime = 0.0f;
        while (elapsedTime < fadeTime)
        {
            elapsedTime += Time.deltaTime;
            animatedFadeAlpha = Mathf.Lerp(startAlpha, endAlpha, Mathf.Clamp01(elapsedTime / fadeTime));
            SetMaterialAlpha();
            yield return new WaitForEndOfFrame();
        }
        animatedFadeAlpha = endAlpha;
        SetMaterialAlpha();
    }
References SetMaterialAlpha().
FadeIn()
void OVRScreenFade.FadeIn ()
Start a fade in.
Definition at line 138 of file OVRScreenFade.cs.
    {
        StartCoroutine(Fade(1.0f, 0.0f));
    }
References Fade().
FadeOut()
void OVRScreenFade.FadeOut ()
Start a fade out.
Definition at line 146 of file OVRScreenFade.cs.
    {
        StartCoroutine(Fade(0, 1));
    }
References Fade().
OnDestroy()
void OVRScreenFade.OnDestroy () private
Cleans up the fade material.
Definition at line 172 of file OVRScreenFade.cs.
    {
        instance = null;
        if (fadeRenderer != null)
            Destroy(fadeRenderer);
        if (fadeMaterial != null)
            Destroy(fadeMaterial);
        if (fadeMesh != null)
            Destroy(fadeMesh);
    }
OnEnable()
void OVRScreenFade.OnEnable () private
Definition at line 159 of file OVRScreenFade.cs.
    {
        if (!fadeOnStart)
        {
            explicitFadeAlpha = 0.0f;
            animatedFadeAlpha = 0.0f;
            uiFadeAlpha = 0.0f;
        }
    }
OnLevelFinishedLoading()
void OVRScreenFade.OnLevelFinishedLoading (int level) private
Starts a fade in when a new level is loaded.
Definition at line 154 of file OVRScreenFade.cs.
    {
        FadeIn();
    }
References FadeIn().
SetExplicitFade()
void OVRScreenFade.SetExplicitFade (float level)
Override current fade level.
Parameters
level
Definition at line 199 of file OVRScreenFade.cs.
    {
        explicitFadeAlpha = level;
        SetMaterialAlpha();
    }
References SetMaterialAlpha().
SetMaterialAlpha()
void OVRScreenFade.SetMaterialAlpha () private
Update material alpha. UI fade and the current fade due to fade in/out animations (or explicit control) both affect the fade. (The max is taken)
Definition at line 227 of file OVRScreenFade.cs.
    {
        Color color = fadeColor;
        color.a = currentAlpha;
        isFading = color.a > 0;
        if (fadeMaterial != null)
        {
            fadeMaterial.color = color;
            fadeMaterial.renderQueue = renderQueue;
            fadeRenderer.material = fadeMaterial;
            fadeRenderer.enabled = isFading;
        }
    }
References currentAlpha, and renderQueue.
SetUIFade()
void OVRScreenFade.SetUIFade (float level)
Set the UI fade level - fade due to UI in foreground.
Definition at line 189 of file OVRScreenFade.cs.
    {
        uiFadeAlpha = Mathf.Clamp01(level);
        SetMaterialAlpha();
    }
References SetMaterialAlpha().
Start()
void OVRScreenFade.Start () private
Automatically starts a fade in.
Definition at line 64 of file OVRScreenFade.cs.
    {
        if (gameObject.name.StartsWith("OculusMRC_"))
        {
            Destroy(this);
            return;
        }
        // create the fade material
        fadeMaterial = new Material(Shader.Find("Oculus/Unlit Transparent Color"));
        fadeMesh = gameObject.AddComponent<MeshFilter>();
        fadeRenderer = gameObject.AddComponent<MeshRenderer>();
        var mesh = new Mesh();
        fadeMesh.mesh = mesh;
        Vector3[] vertices = new Vector3[4];
        float width = 2f;
        float height = 2f;
        float depth = 1f;
        vertices[0] = new Vector3(-width, -height, depth);
        vertices[1] = new Vector3(width, -height, depth);
        vertices[2] = new Vector3(-width, height, depth);
        vertices[3] = new Vector3(width, height, depth);
        mesh.vertices = vertices;
        int[] tri = new int[6];
        tri[0] = 0;
        tri[1] = 2;
        tri[2] = 1;
        tri[3] = 2;
        tri[4] = 3;
        tri[5] = 1;
        mesh.triangles = tri;
        Vector3[] normals = new Vector3[4];
        normals[0] = -Vector3.forward;
        normals[1] = -Vector3.forward;
        normals[2] = -Vector3.forward;
        normals[3] = -Vector3.forward;
        mesh.normals = normals;
        Vector2[] uv = new Vector2[4];
        uv[0] = new Vector2(0, 0);
        uv[1] = new Vector2(1, 0);
        uv[2] = new Vector2(0, 1);
        uv[3] = new Vector2(1, 1);
        mesh.uv = uv;
        explicitFadeAlpha = 0.0f;
        animatedFadeAlpha = 0.0f;
        uiFadeAlpha = 0.0f;
        if (fadeOnStart)
        {
            FadeIn();
        }
        instance = this;
    }
References FadeIn().
Member Data Documentation
animatedFadeAlpha
float OVRScreenFade.animatedFadeAlpha = 0.0f private
Definition at line 53 of file OVRScreenFade.cs.
explicitFadeAlpha
float OVRScreenFade.explicitFadeAlpha = 0.0f private
Definition at line 52 of file OVRScreenFade.cs.
fadeColor
Color OVRScreenFade.fadeColor = new Color(0.01f, 0.01f, 0.01f, 1.0f)
Definition at line 35 of file OVRScreenFade.cs.
fadeMaterial
Material OVRScreenFade.fadeMaterial = null private
Definition at line 58 of file OVRScreenFade.cs.
fadeMesh
MeshFilter OVRScreenFade.fadeMesh private
Definition at line 57 of file OVRScreenFade.cs.
fadeOnStart
bool OVRScreenFade.fadeOnStart = true
Definition at line 37 of file OVRScreenFade.cs.
fadeRenderer
MeshRenderer OVRScreenFade.fadeRenderer private
Definition at line 56 of file OVRScreenFade.cs.
fadeTime
float OVRScreenFade.fadeTime = 2.0f
Definition at line 32 of file OVRScreenFade.cs.
isFading
bool OVRScreenFade.isFading = false private
Definition at line 59 of file OVRScreenFade.cs.
renderQueue
int OVRScreenFade.renderQueue = 5000
The render queue used by the fade mesh. Reduce this if you need to render on top of it.
Definition at line 42 of file OVRScreenFade.cs.
uiFadeAlpha
float OVRScreenFade.uiFadeAlpha = 0.0f private
Definition at line 54 of file OVRScreenFade.cs.
Property Documentation
currentAlpha
float OVRScreenFade.currentAlpha get
Renders the current alpha value being used to fade the screen.
Definition at line 47 of file OVRScreenFade.cs.
    {
        get { return Mathf.Max(explicitFadeAlpha, animatedFadeAlpha, uiFadeAlpha); }
    }
instance
OVRScreenFade OVRScreenFade.instance static get private set
Definition at line 29 of file OVRScreenFade.cs.
{ get; private set; }
The documentation for this class was generated from the following file:
Assets/Oculus/VR/Scripts/Util/OVRScreenFade.cs