VR_Test: Oculus.Interaction.HandGrab.Editor.HandGrabPoseWizard Class Reference
Oculus.Interaction.HandGrab.Editor.HandGrabPoseWizard Class Reference
Public Member Functions
void RecordPose ()
Finds the nearest object that can be snapped to and adds a new HandGrabInteractable to it with the user hand representation.
void GenerateCollectionAsset ()
Properties
Hand Hand [get, set]
Private Member Functions
void OnEnable ()
void OnGUI ()
void GenerateObjectField< T > (ref T obj)
HandPose TrackedPose ()
void AttachGhost (HandGrabPose point)
HandGrabPose AddHandGrabPose (HandPose rawPose, Pose snapPoint)
Creates a new HandGrabInteractable at the exact pose of a given hand. Mostly used with Hand-Tracking at Play-Mode.
HandGrabInteractable LoadHandGrabInteractable (HandGrabUtils.HandGrabInteractableData data)
Creates a new HandGrabInteractable from the stored data. Mostly used to restore a HandGrabInteractable that was stored during Play-Mode.
void SaveToAsset ()
Stores the interactables to a SerializedObject (the empty object must be provided in the inspector or one will be auto-generated). First it translates the HandGrabInteractable to a serialized form HandGrabbableData). This method is called from a button in the Inspector.
void LoadFromAsset ()
Load the HandGrabInteractable from a Collection. This method is called from a button in the Inspector and will load the posesCollection.
Static Private Member Functions
static void CreateWizard ()
Private Attributes
Hand _hand
The Hand being used for recording HandGrabPoses.
int _handID = 0
Rigidbody _item
The Gameobject that the user is recording the HandGrabPose for. e.g. a key.
HandGhostProvider _ghostProvider
References the hand prototypes used to represent the HandGrabInteractables. These are the static hands placed around the interactable to visualize the different holding hand-poses. Not mandatory.
HandGrabInteractableDataCollection _posesCollection
This ScriptableObject stores the HandGrabInteractables generated at Play-Mode so it survives the Play-Edit cycle. Create a collection and assign it even in Play Mode and make sure to store here the interactables, then restore it in Edit-Mode to be serialized.
KeyCode _recordKey = KeyCode.Space
The keyboard key that can be pressed for recording a hand grab pose.
GUIStyle _richTextStyle
Vector2 _scrollPos = Vector2.zero
Detailed Description
Definition at line 30 of file HandGrabPoseWizard.cs.
Member Function Documentation
AddHandGrabPose()
HandGrabPose Oculus.Interaction.HandGrab.Editor.HandGrabPoseWizard.AddHandGrabPose (HandPose rawPose, Pose snapPoint) private
Creates a new HandGrabInteractable at the exact pose of a given hand. Mostly used with Hand-Tracking at Play-Mode.
Parameters
rawPose The user controlled hand pose.
snapPoint The user controlled hand pose.
Returns
The generated HandGrabPose.
Definition at line 241 of file HandGrabPoseWizard.cs.
        {
            HandGrabInteractable interactable = HandGrabUtils.CreateHandGrabInteractable(_item.transform);
            var pointData = new HandGrabUtils.HandGrabPoseData()
            {
                handPose = rawPose,
                scale = Hand.Scale / interactable.RelativeTo.lossyScale.x,
                gripPose = snapPoint,
            };
            return HandGrabUtils.LoadHandGrabPose(interactable, pointData);
        }
References Oculus.Interaction.HandGrab.Editor.HandGrabPoseWizard._item, Oculus.Interaction.HandGrab.HandGrabUtils.CreateHandGrabInteractable(), and Oculus.Interaction.HandGrab.HandGrabInteractable.RelativeTo.
AttachGhost()
void Oculus.Interaction.HandGrab.Editor.HandGrabPoseWizard.AttachGhost (HandGrabPose point) private
Definition at line 223 of file HandGrabPoseWizard.cs.
        {
            if (_ghostProvider == null)
            {
                return;
            }
            HandGhost ghostPrefab = _ghostProvider.GetHand(Hand.Handedness);
            HandGhost ghost = GameObject.Instantiate(ghostPrefab, point.transform);
            ghost.SetPose(point);
        }
CreateWizard()
static void Oculus.Interaction.HandGrab.Editor.HandGrabPoseWizard.CreateWizard () static private
Definition at line 96 of file HandGrabPoseWizard.cs.
        {
            HandGrabPoseWizard window = EditorWindow.GetWindow<HandGrabPoseWizard>();
            window.titleContent = new GUIContent("Hand Grab Pose Recorder");
            window.Show();
        }
GenerateCollectionAsset()
void Oculus.Interaction.HandGrab.Editor.HandGrabPoseWizard.GenerateCollectionAsset ()
Definition at line 303 of file HandGrabPoseWizard.cs.
        {
            _posesCollection = ScriptableObject.CreateInstance<HandGrabInteractableDataCollection>();
            string parentDir = Path.Combine("Assets", "HandGrabInteractableDataCollection");
            if (!Directory.Exists(parentDir))
            {
                Directory.CreateDirectory(parentDir);
            }
            string name = _item != null ? _item.name : "Auto";
            AssetDatabase.CreateAsset(_posesCollection, Path.Combine(parentDir, $"{name}_HandGrabCollection.asset"));
            AssetDatabase.SaveAssets();
        }
GenerateObjectField< T >()
void Oculus.Interaction.HandGrab.Editor.HandGrabPoseWizard.GenerateObjectField< T > (ref T obj) private
Type Constraints
T : Object
Definition at line 161 of file HandGrabPoseWizard.cs.
                                                               : Object
        {
            obj = EditorGUILayout.ObjectField(obj, typeof(T), true) as T;
        }
LoadFromAsset()
void Oculus.Interaction.HandGrab.Editor.HandGrabPoseWizard.LoadFromAsset () private
Load the HandGrabInteractable from a Collection. This method is called from a button in the Inspector and will load the posesCollection.
Definition at line 290 of file HandGrabPoseWizard.cs.
        {
            if (_posesCollection == null)
            {
                return;
            }
            foreach (var handPose in _posesCollection.InteractablesData)
            {
                LoadHandGrabInteractable(handPose);
            }
        }
References Oculus.Interaction.HandGrab.Editor.HandGrabPoseWizard._posesCollection, Oculus.Interaction.HandGrab.HandGrabInteractableDataCollection.InteractablesData, and Oculus.Interaction.HandGrab.Editor.HandGrabPoseWizard.LoadHandGrabInteractable().
LoadHandGrabInteractable()
HandGrabInteractable Oculus.Interaction.HandGrab.Editor.HandGrabPoseWizard.LoadHandGrabInteractable (HandGrabUtils::HandGrabInteractableData data) private
Creates a new HandGrabInteractable from the stored data. Mostly used to restore a HandGrabInteractable that was stored during Play-Mode.
Parameters
data The data of the HandGrabInteractable.
Returns
The generated HandGrabInteractable.
Definition at line 259 of file HandGrabPoseWizard.cs.
        {
            HandGrabInteractable interactable = HandGrabUtils.CreateHandGrabInteractable(_item.transform);
            HandGrabUtils.LoadData(interactable, data);
            return interactable;
        }
References Oculus.Interaction.HandGrab.Editor.HandGrabPoseWizard._item, Oculus.Interaction.HandGrab.HandGrabUtils.CreateHandGrabInteractable(), and Oculus.Interaction.HandGrab.HandGrabUtils.LoadData().
OnEnable()
void Oculus.Interaction.HandGrab.Editor.HandGrabPoseWizard.OnEnable () private
Definition at line 103 of file HandGrabPoseWizard.cs.
        {
            _richTextStyle = EditorGUIUtility.GetBuiltinSkin(EditorGUIUtility.isProSkin ? EditorSkin.Scene : EditorSkin.Inspector).label;
            _richTextStyle.richText = true;
            _richTextStyle.wordWrap = true;
            if (_ghostProvider == null)
            {
                HandGhostProviderUtils.TryGetDefaultProvider(out _ghostProvider);
            }
        }
OnGUI()
void Oculus.Interaction.HandGrab.Editor.HandGrabPoseWizard.OnGUI () private
Definition at line 114 of file HandGrabPoseWizard.cs.
        {
            Event e = Event.current;
            if (e.type == EventType.KeyDown
                && e.keyCode == _recordKey)
            {
                RecordPose();
                e.Use();
            }
            GUILayout.Label("Generate HandGrabPoses for grabbing an item <b>using your Hand in Play Mode</b>.\nThen Store and retrieve them in Edit Mode to persist and tweak them.", _richTextStyle);
            _scrollPos = GUILayout.BeginScrollView(_scrollPos);
            GUILayout.Space(20);
            GUILayout.Label("<size=20>1</size>\nAssign the hand that will be tracked and the item for which you want to record HandGrabPoses", _richTextStyle);
            GUILayout.Label("Hand used for recording poses:");
            Hand = EditorGUILayout.ObjectField(Hand, typeof(Hand), true) as Hand;
            GUILayout.Label("GameObject to record the hand grab poses for:");
            GenerateObjectField(ref _item);
            GUILayout.Label("Prefabs provider for the hands (ghosts) to visualize the recorded poses:");
            GenerateObjectField(ref _ghostProvider);
            GUILayout.Space(20);
            GUILayout.Label("<size=20>2</size>\nGo to <b>Play Mode</b> and record as many poses as you need.", _richTextStyle);
            GUILayout.Label($"Press the big <b>Record</b> button with your free hand\nor the <b>{_recordKey}</b> key to record a HandGrabPose <b>(requires focus on this window)</b>.", _richTextStyle);
            _recordKey = (KeyCode)EditorGUILayout.EnumPopup(_recordKey);
            if (GUILayout.Button("Record HandGrabPose", GUILayout.Height(100)))
            {
                RecordPose();
            }
            GUILayout.Space(20);
            GUILayout.Label("<size=20>3</size>\nStore your poses before exiting <b>Play Mode</b>.\nIf no collection is provided <b>it will autogenerate one</b>", _richTextStyle);
            GenerateObjectField(ref _posesCollection);
            if (GUILayout.Button("Save To Collection"))
            {
                SaveToAsset();
            }
            GUILayout.Space(20);
            GUILayout.Label("<size=20>4</size>\nNow load the poses from the PosesCollection in <b>Edit Mode</b> to tweak and persist them as gameobjects", _richTextStyle);
            if (GUILayout.Button("Load From Collection"))
            {
                LoadFromAsset();
            }
            GUILayout.EndScrollView();
        }
RecordPose()
void Oculus.Interaction.HandGrab.Editor.HandGrabPoseWizard.RecordPose ()
Finds the nearest object that can be snapped to and adds a new HandGrabInteractable to it with the user hand representation.
Definition at line 170 of file HandGrabPoseWizard.cs.
        {
            if (!Application.isPlaying)
            {
                Debug.LogError("Recording tracked hands only works in Play Mode!", this);
                return;
            }
            if (Hand == null)
            {
                Debug.LogError("Missing Hand reference.", this);
                return;
            }
            if (_item == null)
            {
                Debug.LogError("Missing recordable item", this);
                return;
            }
            HandPose trackedHandPose = TrackedPose();
            if (trackedHandPose == null)
            {
                Debug.LogError("Tracked Pose could not be retrieved", this);
                return;
            }
            if (!Hand.GetRootPose(out Pose handRoot))
            {
                Debug.LogError("Hand Root pose could not be retrieved", this);
                return;
            }
            Pose gripPoint = PoseUtils.DeltaScaled(_item.transform, handRoot);
            HandGrabPose point = AddHandGrabPose(trackedHandPose, gripPoint);
            AttachGhost(point);
        }
References Oculus.Interaction.HandGrab.Editor.HandGrabPoseWizard._item, Oculus.Interaction.HandGrab.Editor.HandGrabPoseWizard.AddHandGrabPose(), Oculus.Interaction.PoseUtils.DeltaScaled(), and Oculus.Interaction.Input.Hand.GetRootPose().
SaveToAsset()
void Oculus.Interaction.HandGrab.Editor.HandGrabPoseWizard.SaveToAsset () private
Stores the interactables to a SerializedObject (the empty object must be provided in the inspector or one will be auto-generated). First it translates the HandGrabInteractable to a serialized form HandGrabbableData). This method is called from a button in the Inspector.
Definition at line 272 of file HandGrabPoseWizard.cs.
        {
            if (_posesCollection == null)
            {
                GenerateCollectionAsset();
            }
            var savedPoses = new List<HandGrabUtils.HandGrabInteractableData>();
            foreach (HandGrabInteractable snap in _item.GetComponentsInChildren<HandGrabInteractable>(false))
            {
                savedPoses.Add(HandGrabUtils.SaveData(snap));
            }
            _posesCollection.StoreInteractables(savedPoses);
        }
References Oculus.Interaction.HandGrab.Editor.HandGrabPoseWizard._item, Oculus.Interaction.HandGrab.Editor.HandGrabPoseWizard._posesCollection, Oculus.Interaction.HandGrab.HandGrabUtils.SaveData(), and Oculus.Interaction.HandGrab.HandGrabInteractableDataCollection.StoreInteractables().
TrackedPose()
HandPose Oculus.Interaction.HandGrab.Editor.HandGrabPoseWizard.TrackedPose () private
Definition at line 208 of file HandGrabPoseWizard.cs.
        {
            if (!Hand.GetJointPosesLocal(out ReadOnlyHandJointPoses localJoints))
            {
                return null;
            }
            HandPose result = new HandPose(Hand.Handedness);
            for (int i = 0; i < FingersMetadata.HAND_JOINT_IDS.Length; ++i)
            {
                HandJointId jointID = FingersMetadata.HAND_JOINT_IDS[i];
                result.JointRotations[i] = localJoints[jointID].rotation;
            }
            return result;
        }
Member Data Documentation
_ghostProvider
HandGhostProvider Oculus.Interaction.HandGrab.Editor.HandGrabPoseWizard._ghostProvider private
References the hand prototypes used to represent the HandGrabInteractables. These are the static hands placed around the interactable to visualize the different holding hand-poses. Not mandatory.
Definition at line 75 of file HandGrabPoseWizard.cs.
_hand
Hand Oculus.Interaction.HandGrab.Editor.HandGrabPoseWizard._hand private
The Hand being used for recording HandGrabPoses.
Definition at line 35 of file HandGrabPoseWizard.cs.
_handID
int Oculus.Interaction.HandGrab.Editor.HandGrabPoseWizard._handID = 0 private
Definition at line 37 of file HandGrabPoseWizard.cs.
_item
Rigidbody Oculus.Interaction.HandGrab.Editor.HandGrabPoseWizard._item private
The Gameobject that the user is recording the HandGrabPose for. e.g. a key.
Definition at line 67 of file HandGrabPoseWizard.cs.
_posesCollection
HandGrabInteractableDataCollection Oculus.Interaction.HandGrab.Editor.HandGrabPoseWizard._posesCollection private
This ScriptableObject stores the HandGrabInteractables generated at Play-Mode so it survives the Play-Edit cycle. Create a collection and assign it even in Play Mode and make sure to store here the interactables, then restore it in Edit-Mode to be serialized.
Definition at line 84 of file HandGrabPoseWizard.cs.
_recordKey
KeyCode Oculus.Interaction.HandGrab.Editor.HandGrabPoseWizard._recordKey = KeyCode.Space private
The keyboard key that can be pressed for recording a hand grab pose.
Definition at line 90 of file HandGrabPoseWizard.cs.
_richTextStyle
GUIStyle Oculus.Interaction.HandGrab.Editor.HandGrabPoseWizard._richTextStyle private
Definition at line 92 of file HandGrabPoseWizard.cs.
_scrollPos
Vector2 Oculus.Interaction.HandGrab.Editor.HandGrabPoseWizard._scrollPos = Vector2.zero private
Definition at line 93 of file HandGrabPoseWizard.cs.
Property Documentation
Hand
Hand Oculus.Interaction.HandGrab.Editor.HandGrabPoseWizard.Hand get set
Definition at line 38 of file HandGrabPoseWizard.cs.
        {
            get
            {
                if (_hand == null && _handID != 0)
                {
                    _hand = EditorUtility.InstanceIDToObject(_handID) as Hand;
                    _handID = 0;
                }
                return _hand;
            }
            set
            {
                _hand = value;
                if (_hand != null)
                {
                    _handID = value.GetInstanceID();
                }
                else
                {
                    _handID = 0;
                }
            }
        }
The documentation for this class was generated from the following file:
Assets/Oculus/Interaction/Editor/Utils/HandGrabPoseWizard.cs