VR_Test: OVRDebugInfo Class Reference
OVRDebugInfo Class Reference
Shows debug information on a heads-up display.
Private Member Functions
void Awake ()
Initialization.
void Update ()
Updating VR variables and managing UI present.
void OnDestroy ()
Initialize isInited value on OnDestroy.
void InitUIComponents ()
Initialize UI GameObjects.
void UpdateVariable ()
Update VR Variables.
void UpdateStrings ()
Update Strings.
void RiftPresentGUI (GameObject guiMainOBj)
It's for rift present GUI.
void UpdateDeviceDetection ()
Updates the device detection.
GameObject VariableObjectManager (GameObject gameObject, string name, float posY, string str, int fontSize)
Object Manager for Variables.
GameObject ComponentComposition (GameObject GO)
Component composition.
void UpdateIPD ()
Updates the IPD.
void UpdateEyeHeightOffset ()
Updates the eye height offset.
void UpdateEyeDepthOffset ()
Updates the eye depth offset.
void UpdateFOV ()
Updates the FOV.
void UpdateResolutionEyeTexture ()
Updates resolution of eye texture.
void UpdateLatencyValues ()
Updates latency values.
void UpdateFPS ()
Updates the FPS.
Private Attributes
GameObject debugUIManager
GameObject debugUIObject
GameObject riftPresent
GameObject fps
GameObject ipd
GameObject fov
GameObject height
GameObject depth
GameObject resolutionEyeTexture
GameObject latencies
GameObject texts
string strRiftPresent = null
string strFPS = null
string strIPD = null
string strFOV = null
string strHeight = null
string strDepth = null
string strResolutionEyeTexture = null
string strLatencies = null
float updateInterval = 0.5f
Variables for FPS.
float accum = 0.0f
int frames = 0
float timeLeft = 0.0f
bool initUIComponent = false
Managing for UI initialization.
bool isInited = false
float offsetY = 55.0f
UIs Y offset.
float riftPresentTimeout = 0.0f
Managing for rift detection UI.
bool showVRVars = false
Turn on / off VR variables.
Detailed Description
Shows debug information on a heads-up display.
Definition at line 29 of file OVRDebugInfo.cs.
Member Function Documentation
Awake()
void OVRDebugInfo.Awake () private
Initialization.
Definition at line 96 of file OVRDebugInfo.cs.
    {
        // Create canvas for using new GUI
        debugUIManager = new GameObject();
        debugUIManager.name = "DebugUIManager";
        debugUIManager.transform.parent = GameObject.Find("LeftEyeAnchor").transform;
        RectTransform rectTransform = debugUIManager.AddComponent<RectTransform>();
        rectTransform.sizeDelta = new Vector2(100f, 100f);
        rectTransform.localScale = new Vector3(0.001f, 0.001f, 0.001f);
        rectTransform.localPosition = new Vector3(0.01f, 0.17f, 0.53f);
        rectTransform.localEulerAngles = Vector3.zero;
        Canvas canvas = debugUIManager.AddComponent<Canvas>();
        canvas.renderMode = RenderMode.WorldSpace;
        canvas.pixelPerfect = false;
    }
ComponentComposition()
GameObject OVRDebugInfo.ComponentComposition (GameObject GO) private
Component composition.
Returns
Composed gameobject.
Definition at line 321 of file OVRDebugInfo.cs.
    {
        GO = new GameObject();
        GO.AddComponent<RectTransform>();
        GO.AddComponent<CanvasRenderer>();
        GO.AddComponent<Image>();
        GO.GetComponent<RectTransform>().sizeDelta = new Vector2(350f, 50f);
        GO.GetComponent<Image>().color = new Color(7f / 255f, 45f / 255f, 71f / 255f, 200f / 255f);
        texts = new GameObject();
        texts.AddComponent<RectTransform>();
        texts.AddComponent<CanvasRenderer>();
        texts.AddComponent<Text>();
        texts.GetComponent<RectTransform>().sizeDelta = new Vector2(350f, 50f);
        texts.GetComponent<Text>().font = Resources.GetBuiltinResource(typeof(Font), "Arial.ttf") as Font;
        texts.GetComponent<Text>().alignment = TextAnchor.MiddleCenter;
        texts.transform.SetParent(GO.transform);
        texts.name = "TextBox";
        return GO;
    }
InitUIComponents()
void OVRDebugInfo.InitUIComponents () private
Initialize UI GameObjects.
Definition at line 163 of file OVRDebugInfo.cs.
    {
        float posY = 0.0f;
        int fontSize = 20;
        debugUIObject = new GameObject();
        debugUIObject.name = "DebugInfo";
        debugUIObject.transform.parent = GameObject.Find("DebugUIManager").transform;
        debugUIObject.transform.localPosition = new Vector3(0.0f, 100.0f, 0.0f);
        debugUIObject.transform.localEulerAngles = Vector3.zero;
        debugUIObject.transform.localScale = new Vector3(1.0f, 1.0f, 1.0f);
        // Print out for FPS
        if (!string.IsNullOrEmpty(strFPS))
        {
            fps = VariableObjectManager(fps, "FPS", posY -= offsetY, strFPS, fontSize);
        }
        // Print out for IPD
        if (!string.IsNullOrEmpty(strIPD))
        {
            ipd = VariableObjectManager(ipd, "IPD", posY -= offsetY, strIPD, fontSize);
        }
        // Print out for FOV
        if (!string.IsNullOrEmpty(strFOV))
        {
            fov = VariableObjectManager(fov, "FOV", posY -= offsetY, strFOV, fontSize);
        }
        // Print out for Height
        if (!string.IsNullOrEmpty(strHeight))
        {
            height = VariableObjectManager(height, "Height", posY -= offsetY, strHeight, fontSize);
        }
        // Print out for Depth
        if (!string.IsNullOrEmpty(strDepth))
        {
            depth = VariableObjectManager(depth, "Depth", posY -= offsetY, strDepth, fontSize);
        }
        // Print out for Resoulution of Eye Texture
        if (!string.IsNullOrEmpty(strResolutionEyeTexture))
        {
            resolutionEyeTexture = VariableObjectManager(resolutionEyeTexture, "Resolution", posY -= offsetY,
                strResolutionEyeTexture, fontSize);
        }
        // Print out for Latency
        if (!string.IsNullOrEmpty(strLatencies))
        {
            latencies = VariableObjectManager(latencies, "Latency", posY -= offsetY, strLatencies, 17);
            posY = 0.0f;
        }
        initUIComponent = false;
        isInited = true;
    }
References initUIComponent, offsetY, and VariableObjectManager().
OnDestroy()
void OVRDebugInfo.OnDestroy () private
Initialize isInited value on OnDestroy.
Definition at line 151 of file OVRDebugInfo.cs.
    {
        isInited = false;
    }
RiftPresentGUI()
void OVRDebugInfo.RiftPresentGUI (GameObject guiMainOBj) private
It's for rift present GUI.
Definition at line 268 of file OVRDebugInfo.cs.
    {
        riftPresent = ComponentComposition(riftPresent);
        riftPresent.transform.SetParent(guiMainOBj.transform);
        riftPresent.name = "RiftPresent";
        RectTransform rectTransform = riftPresent.GetComponent<RectTransform>();
        rectTransform.localPosition = new Vector3(0.0f, 0.0f, 0.0f);
        rectTransform.localScale = new Vector3(1.0f, 1.0f, 1.0f);
        rectTransform.localEulerAngles = Vector3.zero;
        Text text = riftPresent.GetComponentInChildren<Text>();
        text.text = strRiftPresent;
        text.fontSize = 20;
    }
References ComponentComposition().
Update()
void OVRDebugInfo.Update () private
Updating VR variables and managing UI present.
Definition at line 117 of file OVRDebugInfo.cs.
    {
        if (initUIComponent && !isInited)
        {
            InitUIComponents();
        }
        //todo: enable for Unity Input System
#if ENABLE_LEGACY_INPUT_MANAGER
        if (Input.GetKeyDown(KeyCode.Space) && riftPresentTimeout < 0.0f)
        {
            initUIComponent = true;
            showVRVars ^= true;
        }
#endif
        UpdateDeviceDetection();
        // Presenting VR variables
        if (showVRVars)
        {
            debugUIManager.SetActive(true);
            UpdateVariable();
            UpdateStrings();
        }
        else
        {
            debugUIManager.SetActive(false);
        }
    }
References initUIComponent, InitUIComponents(), riftPresentTimeout, showVRVars, UpdateDeviceDetection(), UpdateStrings(), and UpdateVariable().
UpdateDeviceDetection()
void OVRDebugInfo.UpdateDeviceDetection () private
Updates the device detection.
Definition at line 286 of file OVRDebugInfo.cs.
    {
        if (riftPresentTimeout >= 0.0f)
        {
            riftPresentTimeout -= Time.deltaTime;
        }
    }
References riftPresentTimeout.
UpdateEyeDepthOffset()
void OVRDebugInfo.UpdateEyeDepthOffset () private
Updates the eye depth offset.
Definition at line 368 of file OVRDebugInfo.cs.
    {
        float eyeDepth = OVRManager.profile.eyeDepth;
        strDepth = System.String.Format("Eye Depth (m): {0:F3}", eyeDepth);
    }
References OVRManager.profile.
UpdateEyeHeightOffset()
void OVRDebugInfo.UpdateEyeHeightOffset () private
Updates the eye height offset.
Definition at line 359 of file OVRDebugInfo.cs.
    {
        float eyeHeight = OVRManager.profile.eyeHeight;
        strHeight = System.String.Format("Eye Height (m): {0:F3}", eyeHeight);
    }
References OVRManager.profile.
UpdateFOV()
void OVRDebugInfo.UpdateFOV () private
Updates the FOV.
Definition at line 377 of file OVRDebugInfo.cs.
    {
        OVRDisplay.EyeRenderDesc eyeDesc = OVRManager.display.GetEyeRenderDesc(UnityEngine.XR.XRNode.LeftEye);
        strFOV = System.String.Format("FOV (deg): {0:F3}", eyeDesc.fov.y);
    }
References OVRManager.display, OVRDisplay.EyeRenderDesc.fov, and OVRDisplay.GetEyeRenderDesc().
UpdateFPS()
void OVRDebugInfo.UpdateFPS () private
Updates the FPS.
Definition at line 421 of file OVRDebugInfo.cs.
    {
        timeLeft -= Time.unscaledDeltaTime;
        accum += Time.unscaledDeltaTime;
        ++frames;
        // Interval ended - update GUI text and start new interval
        if (timeLeft <= 0.0)
        {
            // display two fractional digits (f2 format)
            float fps = frames / accum;
            strFPS = System.String.Format("FPS: {0:F2}", fps);
            timeLeft += updateInterval;
            accum = 0.0f;
            frames = 0;
        }
    }
References updateInterval.
UpdateIPD()
void OVRDebugInfo.UpdateIPD () private
Updates the IPD.
Definition at line 351 of file OVRDebugInfo.cs.
    {
        strIPD = System.String.Format("IPD (mm): {0:F4}", OVRManager.profile.ipd * 1000.0f);
    }
References OVRManager.profile.
UpdateLatencyValues()
void OVRDebugInfo.UpdateLatencyValues () private
Updates latency values.
Definition at line 401 of file OVRDebugInfo.cs.
    {
#if !UNITY_ANDROID || UNITY_EDITOR
        OVRDisplay.LatencyData latency = OVRManager.display.latency;
        if (latency.render < 0.000001f && latency.timeWarp < 0.000001f && latency.postPresent < 0.000001f)
            strLatencies = System.String.Format("Latency values are not available.");
        else
            strLatencies = System.String.Format(
                "Render: {0:F3} TimeWarp: {1:F3} Post-Present: {2:F3}\nRender Error: {3:F3} TimeWarp Error: {4:F3}",
                latency.render,
                latency.timeWarp,
                latency.postPresent,
                latency.renderError,
                latency.timeWarpError);
#endif
    }
References OVRManager.display, OVRDisplay.latency, OVRDisplay.LatencyData.postPresent, OVRDisplay.LatencyData.render, and OVRDisplay.LatencyData.timeWarp.
UpdateResolutionEyeTexture()
void OVRDebugInfo.UpdateResolutionEyeTexture () private
Updates resolution of eye texture.
Definition at line 386 of file OVRDebugInfo.cs.
    {
        OVRDisplay.EyeRenderDesc leftEyeDesc = OVRManager.display.GetEyeRenderDesc(UnityEngine.XR.XRNode.LeftEye);
        OVRDisplay.EyeRenderDesc rightEyeDesc = OVRManager.display.GetEyeRenderDesc(UnityEngine.XR.XRNode.RightEye);
        float scale = UnityEngine.XR.XRSettings.renderViewportScale;
        float w = (int)(scale * (float)(leftEyeDesc.resolution.x + rightEyeDesc.resolution.x));
        float h = (int)(scale * (float)Mathf.Max(leftEyeDesc.resolution.y, rightEyeDesc.resolution.y));
        strResolutionEyeTexture = System.String.Format("Resolution : {0} x {1}", w, h);
    }
References OVRManager.display, OVRDisplay.GetEyeRenderDesc(), and OVRDisplay.EyeRenderDesc.resolution.
UpdateStrings()
void OVRDebugInfo.UpdateStrings () private
Update Strings.
Definition at line 240 of file OVRDebugInfo.cs.
    {
        if (debugUIObject == null)
            return;
        if (!string.IsNullOrEmpty(strFPS))
            fps.GetComponentInChildren<Text>().text = strFPS;
        if (!string.IsNullOrEmpty(strIPD))
            ipd.GetComponentInChildren<Text>().text = strIPD;
        if (!string.IsNullOrEmpty(strFOV))
            fov.GetComponentInChildren<Text>().text = strFOV;
        if (!string.IsNullOrEmpty(strResolutionEyeTexture))
            resolutionEyeTexture.GetComponentInChildren<Text>().text = strResolutionEyeTexture;
        if (!string.IsNullOrEmpty(strLatencies))
        {
            latencies.GetComponentInChildren<Text>().text = strLatencies;
            latencies.GetComponentInChildren<Text>().fontSize = 14;
        }
        if (!string.IsNullOrEmpty(strHeight))
            height.GetComponentInChildren<Text>().text = strHeight;
        if (!string.IsNullOrEmpty(strDepth))
            depth.GetComponentInChildren<Text>().text = strDepth;
    }
UpdateVariable()
void OVRDebugInfo.UpdateVariable () private
Update VR Variables.
Definition at line 226 of file OVRDebugInfo.cs.
    {
        UpdateIPD();
        UpdateEyeHeightOffset();
        UpdateEyeDepthOffset();
        UpdateFOV();
        UpdateResolutionEyeTexture();
        UpdateLatencyValues();
        UpdateFPS();
    }
References UpdateEyeDepthOffset(), UpdateEyeHeightOffset(), UpdateFOV(), UpdateFPS(), UpdateIPD(), UpdateLatencyValues(), and UpdateResolutionEyeTexture().
VariableObjectManager()
GameObject OVRDebugInfo.VariableObjectManager (GameObject gameObject, string name, float posY, string str, int fontSize) private
Object Manager for Variables.
Returns
gameobject for each Variable
Definition at line 298 of file OVRDebugInfo.cs.
    {
        gameObject = ComponentComposition(gameObject);
        gameObject.name = name;
        gameObject.transform.SetParent(debugUIObject.transform);
        RectTransform rectTransform = gameObject.GetComponent<RectTransform>();
        rectTransform.localPosition = new Vector3(0.0f, posY -= offsetY, 0.0f);
        Text text = gameObject.GetComponentInChildren<Text>();
        text.text = str;
        text.fontSize = fontSize;
        gameObject.transform.localEulerAngles = Vector3.zero;
        rectTransform.localScale = new Vector3(1.0f, 1.0f, 1.0f);
        return gameObject;
    }
References ComponentComposition(), and offsetY.
Member Data Documentation
accum
float OVRDebugInfo.accum = 0.0f private
Definition at line 65 of file OVRDebugInfo.cs.
debugUIManager
GameObject OVRDebugInfo.debugUIManager private
Definition at line 33 of file OVRDebugInfo.cs.
debugUIObject
GameObject OVRDebugInfo.debugUIObject private
Definition at line 34 of file OVRDebugInfo.cs.
depth
GameObject OVRDebugInfo.depth private
Definition at line 40 of file OVRDebugInfo.cs.
fov
GameObject OVRDebugInfo.fov private
Definition at line 38 of file OVRDebugInfo.cs.
fps
GameObject OVRDebugInfo.fps private
Definition at line 36 of file OVRDebugInfo.cs.
frames
int OVRDebugInfo.frames = 0 private
Definition at line 66 of file OVRDebugInfo.cs.
height
GameObject OVRDebugInfo.height private
Definition at line 39 of file OVRDebugInfo.cs.
initUIComponent
bool OVRDebugInfo.initUIComponent = false private
Managing for UI initialization.
Definition at line 72 of file OVRDebugInfo.cs.
ipd
GameObject OVRDebugInfo.ipd private
Definition at line 37 of file OVRDebugInfo.cs.
isInited
bool OVRDebugInfo.isInited = false private
Definition at line 74 of file OVRDebugInfo.cs.
latencies
GameObject OVRDebugInfo.latencies private
Definition at line 42 of file OVRDebugInfo.cs.
offsetY
float OVRDebugInfo.offsetY = 55.0f private
UIs Y offset.
Definition at line 79 of file OVRDebugInfo.cs.
resolutionEyeTexture
GameObject OVRDebugInfo.resolutionEyeTexture private
Definition at line 41 of file OVRDebugInfo.cs.
riftPresent
GameObject OVRDebugInfo.riftPresent private
Definition at line 35 of file OVRDebugInfo.cs.
riftPresentTimeout
float OVRDebugInfo.riftPresentTimeout = 0.0f private
Managing for rift detection UI.
Definition at line 84 of file OVRDebugInfo.cs.
showVRVars
bool OVRDebugInfo.showVRVars = false private
Turn on / off VR variables.
Definition at line 89 of file OVRDebugInfo.cs.
strDepth
string OVRDebugInfo.strDepth = null private
Definition at line 54 of file OVRDebugInfo.cs.
strFOV
string OVRDebugInfo.strFOV = null private
Definition at line 52 of file OVRDebugInfo.cs.
strFPS
string OVRDebugInfo.strFPS = null private
Definition at line 50 of file OVRDebugInfo.cs.
strHeight
string OVRDebugInfo.strHeight = null private
Definition at line 53 of file OVRDebugInfo.cs.
strIPD
string OVRDebugInfo.strIPD = null private
Definition at line 51 of file OVRDebugInfo.cs.
strLatencies
string OVRDebugInfo.strLatencies = null private
Definition at line 56 of file OVRDebugInfo.cs.
strResolutionEyeTexture
string OVRDebugInfo.strResolutionEyeTexture = null private
Definition at line 55 of file OVRDebugInfo.cs.
strRiftPresent
string OVRDebugInfo.strRiftPresent = null private
Definition at line 49 of file OVRDebugInfo.cs.
texts
GameObject OVRDebugInfo.texts private
Definition at line 43 of file OVRDebugInfo.cs.
timeLeft
float OVRDebugInfo.timeLeft = 0.0f private
Definition at line 67 of file OVRDebugInfo.cs.
updateInterval
float OVRDebugInfo.updateInterval = 0.5f private
Variables for FPS.
Definition at line 63 of file OVRDebugInfo.cs.
The documentation for this class was generated from the following file:
Assets/Oculus/VR/Scripts/Util/OVRDebugInfo.cs