VR_Test: Oculus.Voice.AppVoiceExperience Class Reference
Oculus.Voice.AppVoiceExperience Class Reference
Public Member Functions
override bool CanSend ()
Whether voice requests can be sent or not.
override VoiceServiceRequest Activate (string text, WitRequestOptions requestOptions, VoiceServiceRequestEvents requestEvents)
Send text data for NLU processing with custom request options & events.
override bool CanActivateAudio ()
Whether audio can be activated or not.
override VoiceServiceRequest Activate (WitRequestOptions requestOptions, VoiceServiceRequestEvents requestEvents)
Activate the microphone and wait for threshold and then send data.
override VoiceServiceRequest ActivateImmediately (WitRequestOptions requestOptions, VoiceServiceRequestEvents requestEvents)
Activate the microphone and send data for NLU processing with custom request options.
override void Deactivate ()
Stop listening and submit the collected microphone data for processing.
override void DeactivateAndAbortRequest ()
Stop listening and abort any requests that may be active without waiting for a response.
Public Member Functions inherited from Meta.WitAi.VoiceService
void Activate (string text)
Send text data for NLU processing. Results will return the same way a voice based activation would.
void Activate (string text, WitRequestOptions requestOptions)
Send text data for NLU processing. Results will return the same way a voice based activation would.
VoiceServiceRequest Activate (string text, VoiceServiceRequestEvents requestEvents)
Send text data for NLU processing. Results will return the same way a voice based activation would.
VoiceServiceRequest Activate (string text, WitRequestOptions requestOptions, VoiceServiceRequestEvents requestEvents)
Send text data for NLU processing with custom request options.
void Activate ()
Start listening for sound or speech from the user and start sending data to Wit.ai once sound or speech has been detected.
void Activate (WitRequestOptions requestOptions)
Start listening for sound or speech from the user and start sending data to Wit.ai once sound or speech has been detected.
VoiceServiceRequest Activate (VoiceServiceRequestEvents requestEvents)
Start listening for sound or speech from the user and start sending data to Wit.ai once sound or speech has been detected.
VoiceServiceRequest Activate (WitRequestOptions requestOptions, VoiceServiceRequestEvents requestEvents)
Start listening for sound or speech from the user and start sending data to Wit.ai once sound or speech has been detected.
void ActivateImmediately ()
Activate the microphone and send data for NLU processing immediately without waiting for sound/speech from the user to begin.
void ActivateImmediately (WitRequestOptions requestOptions)
Activate the microphone and send data for NLU processing immediately without waiting for sound/speech from the user to begin.
VoiceServiceRequest ActivateImmediately (VoiceServiceRequestEvents requestEvents)
Activate the microphone and send data for NLU processing immediately without waiting for sound/speech from the user to begin.
VoiceServiceRequest ActivateImmediately (WitRequestOptions requestOptions, VoiceServiceRequestEvents requestEvents)
Activate the microphone and send data for NLU processing immediately without waiting for sound/speech from the user to begin.
void Deactivate ()
Stop listening and submit any remaining buffered microphone data for processing.
void DeactivateAndAbortRequest ()
Stop listening and abort any requests that may be active without waiting for a response.
virtual void DeactivateAndAbortRequest (VoiceServiceRequest request)
Abort a specific request.
IEnumerable< object > GetObjectsOfType (Type type)
Returns objects of the specified type.
Protected Member Functions
override string GetActivateAudioError ()
override void OnEnable ()
override void OnDisable ()
Protected Member Functions inherited from Meta.WitAi.VoiceService
VoiceService ()
Constructs a VoiceService
virtual void OnTextRequestCreated (VoiceServiceRequest textRequest)
Called on text request creation.
virtual string GetSendError ()
Check for error that will occur if attempting to send data.
virtual void HandleRequestResults (VoiceServiceRequest request)
Called after request cancellation, failure or success.
string GetActivateAudioError ()
Check for error that will occur if attempting to read an audio source.
virtual void OnAudioRequestCreated (VoiceServiceRequest audioRequest)
Called on creation.
virtual void OnAudioPartialResponse (VoiceServiceRequest audioRequest)
virtual void Awake ()
virtual void OnFinalTranscription (string transcription)
Activate message if transcription provider returns a final transcription.
virtual void HandleResponse (WitResponseNode response)
Properties
WitRuntimeConfiguration RuntimeConfiguration [get, set]
WitConfiguration Configuration [get]
static string PACKAGE_VERSION [get]
bool Initialized [get]
override bool Active [get]
Returns true if this voice service is currently active and listening with the mic.
override bool IsRequestActive [get]
Returns true if voice service is currently active or request is transmitting.
override ITranscriptionProvider TranscriptionProvider [get, set]
Easy acccess for transcription.
override bool MicActive [get]
Returns true Mic is still enabled.
override bool ShouldSendMicData [get]
bool HasPlatformIntegrations [get]
bool EnableConsoleLogging [get]
bool UsePlatformIntegrations [get, set]
Properties inherited from Meta.WitAi.VoiceService
bool UseConduit [get]
When set to true, Conduit will be used. Otherwise, the legacy dispatching will be used.
WitConfiguration WitConfiguration [get]
Wit configuration accessor via IWitConfigurationProvider.
virtual bool Active [get]
Returns true if this voice service is currently active and listening with the mic.
virtual bool IsRequestActive [get]
Returns true if the service is actively communicating with Wit.ai during an Activation. The mic may or may not still be active while this is true.
ITranscriptionProvider TranscriptionProvider [get, set]
Gets/Sets a custom transcription provider. This can be used to replace any built in asr with an on device model or other provided source.
bool MicActive [get]
Returns true if this voice service is currently reading data from the microphone.
virtual VoiceEvents VoiceEvents [get, set]
All events used for a voice service.
virtual TelemetryEvents TelemetryEvents [get, set]
All events used for a voice service telemetry.
IAudioInputEvents AudioEvents [get]
A subset of events around collection of audio data.
ITranscriptionEvent TranscriptionEvents [get]
A subset of events around receiving transcriptions.
bool ShouldSendMicData [get]
Returns true if the audio input should be read in an activation.
HashSet< VoiceServiceRequest > Requests = new HashSet<VoiceServiceRequest>() [get]
All currently running requests.
Properties inherited from Meta.WitAi.IVoiceService
Properties inherited from Meta.WitAi.IVoiceEventProvider
Properties inherited from Meta.WitAi.ITelemetryEventsProvider
Properties inherited from Meta.WitAi.IVoiceActivationHandler
Properties inherited from Meta.WitAi.Interfaces.IAudioEventProvider
Properties inherited from Meta.WitAi.IWitRuntimeConfigProvider
Properties inherited from Meta.WitAi.Interfaces.IWitConfigurationProvider
Events
Action OnInitialized
Private Member Functions
void InitVoiceSDK ()
void RevertToWitUnity ()
void OnApplicationFocus (bool hasFocus)
void OnRequestInit (VoiceServiceRequest request)
void OnWitResponseListener (WitResponseNode witResponseNode)
void OnStartedListening ()
void OnMinimumWakeThresholdHit ()
void OnStoppedListening ()
void OnStoppedListeningDueToTimeout ()
void OnStoppedListeningDueToInactivity ()
void OnStoppedListeningDueToDeactivation ()
void OnMicDataSent ()
void OnSend (VoiceServiceRequest request)
void OnAudioDurationTrackerFinished (long timestamp, double audioDuration)
void OnPartialTranscription (string text)
void OnFullTranscription (string text)
void OnRequestComplete (VoiceServiceRequest request)
Private Attributes
WitRuntimeConfiguration witRuntimeConfiguration
bool usePlatformServices
bool enableConsoleLogging
IPlatformVoiceService platformService
IVoiceService voiceServiceImpl
IVoiceSDKLogger voiceSDKLoggerImpl
Additional Inherited Members
Protected Attributes inherited from Meta.WitAi.VoiceService
VoiceEvents events = new VoiceEvents()
This field should not be accessed outside the Wit-Unity library. If you need access to events you should be using the VoiceService.VoiceEvents property instead.
TelemetryEvents telemetryEvents = new TelemetryEvents()
Detailed Description
Definition at line 41 of file AppVoiceExperience.cs.
Member Function Documentation
Activate() [1/2]
override VoiceServiceRequest Oculus.Voice.AppVoiceExperience.Activate (string text, WitRequestOptions requestOptions, VoiceServiceRequestEvents requestEvents)
Send text data for NLU processing with custom request options & events.
Parameters
text Text to be used for NLU processing
requestOptions Additional options such as dynamic entities
requestEvents Events specific to the request's lifecycle
Implements Meta.WitAi.IVoiceActivationHandler.
Definition at line 119 of file AppVoiceExperience.cs.
        {
            if (CanSend())
            {
                return voiceServiceImpl.Activate(text, requestOptions, requestEvents);
            }
            return null;
        }
References Meta.WitAi.IVoiceActivationHandler.Activate(), and Oculus.Voice.AppVoiceExperience.CanSend().
Activate() [2/2]
override VoiceServiceRequest Oculus.Voice.AppVoiceExperience.Activate (WitRequestOptions requestOptions, VoiceServiceRequestEvents requestEvents)
Activate the microphone and wait for threshold and then send data.
Parameters
requestOptions Additional options such as dynamic entities
requestEvents Events specific to the request's lifecycle
Implements Meta.WitAi.IVoiceActivationHandler.
Definition at line 144 of file AppVoiceExperience.cs.
        {
            if (CanActivateAudio() && CanSend())
            {
                return voiceServiceImpl.Activate(requestOptions, requestEvents);
            }
            return null;
        }
References Meta.WitAi.IVoiceActivationHandler.Activate(), Oculus.Voice.AppVoiceExperience.CanActivateAudio(), and Oculus.Voice.AppVoiceExperience.CanSend().
ActivateImmediately()
override VoiceServiceRequest Oculus.Voice.AppVoiceExperience.ActivateImmediately (WitRequestOptions requestOptions, VoiceServiceRequestEvents requestEvents)
Activate the microphone and send data for NLU processing with custom request options.
Parameters
requestOptions Additional options such as dynamic entities
requestEvents Events specific to the request's lifecycle
Implements Meta.WitAi.IVoiceActivationHandler.
Definition at line 153 of file AppVoiceExperience.cs.
        {
            if (CanActivateAudio() && CanSend())
            {
                return voiceServiceImpl.ActivateImmediately(requestOptions, requestEvents);
            }
            return null;
        }
References Meta.WitAi.IVoiceActivationHandler.ActivateImmediately(), Oculus.Voice.AppVoiceExperience.CanActivateAudio(), and Oculus.Voice.AppVoiceExperience.CanSend().
CanActivateAudio()
override bool Oculus.Voice.AppVoiceExperience.CanActivateAudio () virtual
Whether audio can be activated or not.
Returns
Reimplemented from Meta.WitAi.VoiceService.
Definition at line 130 of file AppVoiceExperience.cs.
        {
            return base.CanActivateAudio() && voiceServiceImpl.CanActivateAudio();
        }
References Meta.WitAi.IVoiceService.CanActivateAudio().
CanSend()
override bool Oculus.Voice.AppVoiceExperience.CanSend () virtual
Whether voice requests can be sent or not.
Returns
Reimplemented from Meta.WitAi.VoiceService.
Definition at line 114 of file AppVoiceExperience.cs.
        {
            return base.CanSend() && null != voiceServiceImpl && voiceServiceImpl.CanSend();
        }
References Meta.WitAi.IVoiceService.CanSend().
Deactivate()
override void Oculus.Voice.AppVoiceExperience.Deactivate ()
Stop listening and submit the collected microphone data for processing.
Implements Meta.WitAi.IVoiceActivationHandler.
Definition at line 162 of file AppVoiceExperience.cs.
        {
            voiceServiceImpl.Deactivate();
        }
References Meta.WitAi.IVoiceActivationHandler.Deactivate().
DeactivateAndAbortRequest()
override void Oculus.Voice.AppVoiceExperience.DeactivateAndAbortRequest ()
Stop listening and abort any requests that may be active without waiting for a response.
Implements Meta.WitAi.IVoiceActivationHandler.
Definition at line 167 of file AppVoiceExperience.cs.
        {
            voiceServiceImpl.DeactivateAndAbortRequest();
        }
References Meta.WitAi.IVoiceActivationHandler.DeactivateAndAbortRequest().
GetActivateAudioError()
override string Oculus.Voice.AppVoiceExperience.GetActivateAudioError () protected
Definition at line 135 of file AppVoiceExperience.cs.
        {
            if (!HasPlatformIntegrations && !AudioBuffer.Instance.IsInputAvailable)
            {
                return "No Microphone(s)/recording devices found.  You will be unable to capture audio on this device.";
            }
            return string.Empty;
        }
InitVoiceSDK()
void Oculus.Voice.AppVoiceExperience.InitVoiceSDK () private
Definition at line 174 of file AppVoiceExperience.cs.
        {
            // Check voice sdk version
            if (string.IsNullOrEmpty(PACKAGE_VERSION))
            {
                VLog.E("No SDK Version Set");
            }
            // Clean up if we're switching to native C# wit impl
            if (!UsePlatformIntegrations)
            {
                if (voiceServiceImpl is VoiceSDKImpl)
                {
                    ((VoiceSDKImpl) voiceServiceImpl).Disconnect();
                }
                if (voiceSDKLoggerImpl is VoiceSDKPlatformLoggerImpl)
                {
                    try
                    {
                        ((VoiceSDKPlatformLoggerImpl)voiceSDKLoggerImpl).Disconnect();
                    }
                    catch (Exception e)
                    {
                        VLog.E($"Disconnection error: {e.Message}");
                    }
                }
            }
#if UNITY_ANDROID && !UNITY_EDITOR
            var loggerImpl = new VoiceSDKPlatformLoggerImpl();
            loggerImpl.Connect(PACKAGE_VERSION);
            voiceSDKLoggerImpl = loggerImpl;
            if (UsePlatformIntegrations)
            {
                Debug.Log("Checking platform capabilities...");
                var platformImpl = new VoiceSDKImpl(this);
                platformImpl.OnServiceNotAvailableEvent += () => RevertToWitUnity();
                platformImpl.Connect(PACKAGE_VERSION);
                platformImpl.SetRuntimeConfiguration(RuntimeConfiguration);
                if (platformImpl.PlatformSupportsWit)
                {
                    voiceServiceImpl = platformImpl;
                    if (voiceServiceImpl is Wit wit)
                    {
                        wit.RuntimeConfiguration = witRuntimeConfiguration;
                    }
                    voiceServiceImpl.VoiceEvents = VoiceEvents;
                    voiceServiceImpl.TelemetryEvents = TelemetryEvents;
                    voiceSDKLoggerImpl.IsUsingPlatformIntegration = true;
                }
                else
                {
                    Debug.Log("Platform registration indicated platform support is not currently available.");
                    RevertToWitUnity();
                }
            }
            else
            {
                RevertToWitUnity();
            }
#else
            voiceSDKLoggerImpl = new VoiceSDKConsoleLoggerImpl();
            RevertToWitUnity();
#endif
            voiceSDKLoggerImpl.WitApplication = RuntimeConfiguration?.witConfiguration?.GetLoggerAppId();
            voiceSDKLoggerImpl.ShouldLogToConsole = EnableConsoleLogging;
            OnInitialized?.Invoke();
        }
OnApplicationFocus()
void Oculus.Voice.AppVoiceExperience.OnApplicationFocus (bool hasFocus) private
Definition at line 334 of file AppVoiceExperience.cs.
        {
            if (enabled && hasFocus && !Initialized)
            {
                if (MicPermissionsManager.HasMicPermission())
                {
                    InitVoiceSDK();
                }
            }
        }
OnAudioDurationTrackerFinished()
void Oculus.Voice.AppVoiceExperience.OnAudioDurationTrackerFinished (long timestamp, double audioDuration) private
Definition at line 418 of file AppVoiceExperience.cs.
        {
            voiceSDKLoggerImpl.LogAnnotation("adt_duration", audioDuration.ToString(CultureInfo.InvariantCulture));
            voiceSDKLoggerImpl.LogAnnotation("adt_finished", timestamp.ToString());
        }
OnDisable()
override void Oculus.Voice.AppVoiceExperience.OnDisable () protected virtual
Reimplemented from Meta.WitAi.VoiceService.
Definition at line 300 of file AppVoiceExperience.cs.
        {
            base.OnDisable();
            #if UNITY_ANDROID
            if (voiceServiceImpl is VoiceSDKImpl platformImpl)
            {
                platformImpl.Disconnect();
            }
            if (voiceSDKLoggerImpl is VoiceSDKPlatformLoggerImpl loggerImpl)
            {
                loggerImpl.Disconnect();
            }
            #endif
            voiceServiceImpl = null;
            voiceSDKLoggerImpl = null;
            // Listeners
            VoiceEvents.OnRequestInitialized?.RemoveListener(OnRequestInit);
            VoiceEvents.OnResponse?.RemoveListener(OnWitResponseListener);
            VoiceEvents.OnStartListening?.RemoveListener(OnStartedListening);
            VoiceEvents.OnMinimumWakeThresholdHit?.RemoveListener(OnMinimumWakeThresholdHit);
            VoiceEvents.OnStoppedListening?.RemoveListener(OnStoppedListening);
            VoiceEvents.OnMicDataSent?.RemoveListener(OnMicDataSent);
            VoiceEvents.OnSend?.RemoveListener(OnSend);
            VoiceEvents.OnPartialTranscription?.RemoveListener(OnPartialTranscription);
            VoiceEvents.OnFullTranscription?.RemoveListener(OnFullTranscription);
            VoiceEvents.OnStoppedListeningDueToTimeout?.RemoveListener(OnStoppedListeningDueToTimeout);
            VoiceEvents.OnStoppedListeningDueToInactivity?.RemoveListener(OnStoppedListeningDueToInactivity);
            VoiceEvents.OnStoppedListeningDueToDeactivation?.RemoveListener(OnStoppedListeningDueToDeactivation);
            VoiceEvents.OnComplete?.RemoveListener(OnRequestComplete);
            TelemetryEvents.OnAudioTrackerFinished?.RemoveListener(OnAudioDurationTrackerFinished);
        }
OnEnable()
override void Oculus.Voice.AppVoiceExperience.OnEnable () protected virtual
Reimplemented from Meta.WitAi.VoiceService.
Definition at line 267 of file AppVoiceExperience.cs.
        {
            base.OnEnable();
            if (MicPermissionsManager.HasMicPermission())
            {
                InitVoiceSDK();
            }
            else
            {
                MicPermissionsManager.RequestMicPermission();
            }
            #if UNITY_ANDROID && !UNITY_EDITOR
            platformService?.SetRuntimeConfiguration(witRuntimeConfiguration);
            #endif
            // Listeners
            VoiceEvents.OnRequestInitialized?.AddListener(OnRequestInit);
            VoiceEvents.OnResponse?.AddListener(OnWitResponseListener);
            VoiceEvents.OnStartListening?.AddListener(OnStartedListening);
            VoiceEvents.OnMinimumWakeThresholdHit?.AddListener(OnMinimumWakeThresholdHit);
            VoiceEvents.OnStoppedListening?.AddListener(OnStoppedListening);
            VoiceEvents.OnMicDataSent?.AddListener(OnMicDataSent);
            VoiceEvents.OnSend?.AddListener(OnSend);
            VoiceEvents.OnPartialTranscription?.AddListener(OnPartialTranscription);
            VoiceEvents.OnFullTranscription?.AddListener(OnFullTranscription);
            VoiceEvents.OnStoppedListeningDueToTimeout?.AddListener(OnStoppedListeningDueToTimeout);
            VoiceEvents.OnStoppedListeningDueToInactivity?.AddListener(OnStoppedListeningDueToInactivity);
            VoiceEvents.OnStoppedListeningDueToDeactivation?.AddListener(OnStoppedListeningDueToDeactivation);
            VoiceEvents.OnComplete?.AddListener(OnRequestComplete);
            TelemetryEvents.OnAudioTrackerFinished?.AddListener(OnAudioDurationTrackerFinished);
        }
OnFullTranscription()
void Oculus.Voice.AppVoiceExperience.OnFullTranscription (string text) private
Definition at line 429 of file AppVoiceExperience.cs.
        {
            voiceSDKLoggerImpl.LogInteractionPoint("fullTranscriptionTime");
        }
OnMicDataSent()
void Oculus.Voice.AppVoiceExperience.OnMicDataSent () private
Definition at line 404 of file AppVoiceExperience.cs.
        {
            voiceSDKLoggerImpl.LogInteractionPoint("micDataSent");
        }
OnMinimumWakeThresholdHit()
void Oculus.Voice.AppVoiceExperience.OnMinimumWakeThresholdHit () private
Definition at line 379 of file AppVoiceExperience.cs.
        {
            voiceSDKLoggerImpl.LogInteractionPoint("minWakeThresholdHit");
        }
OnPartialTranscription()
void Oculus.Voice.AppVoiceExperience.OnPartialTranscription (string text) private
Definition at line 424 of file AppVoiceExperience.cs.
        {
            voiceSDKLoggerImpl.LogFirstTranscriptionTime();
        }
OnRequestComplete()
void Oculus.Voice.AppVoiceExperience.OnRequestComplete (VoiceServiceRequest request) private
Definition at line 434 of file AppVoiceExperience.cs.
        {
            if (request.State == VoiceRequestState.Failed)
            {
                VLog.E($"Request Failed\nError: {request.Results.Message}\n{request.Results.ResponseData}");
                voiceSDKLoggerImpl.LogInteractionEndFailure(request.Results.Message);
            }
            else if (request.State == VoiceRequestState.Canceled)
            {
                VLog.D($"Request Canceled\nMessage: {request.Results.Message}");
                voiceSDKLoggerImpl.LogInteractionEndFailure("aborted");
            }
            else
            {
                VLog.D($"Request Success");
                voiceSDKLoggerImpl.LogInteractionEndSuccess();
            }
        }
OnRequestInit()
void Oculus.Voice.AppVoiceExperience.OnRequestInit (VoiceServiceRequest request) private
Definition at line 346 of file AppVoiceExperience.cs.
        {
            voiceSDKLoggerImpl.LogInteractionStart(request.Options?.RequestId, request.InputType == NLPRequestInputType.Text ? "message" : "speech");
#if UNITY_ANDROID && !UNITY_EDITOR
            voiceSDKLoggerImpl.LogAnnotation("clientSDKVersion", PACKAGE_VERSION);
#endif
            voiceSDKLoggerImpl.LogAnnotation("minWakeThreshold",
                RuntimeConfiguration?.soundWakeThreshold.ToString(CultureInfo.InvariantCulture));
            voiceSDKLoggerImpl.LogAnnotation("minKeepAliveTimeSec",
                RuntimeConfiguration?.minKeepAliveTimeInSeconds.ToString(CultureInfo.InvariantCulture));
            voiceSDKLoggerImpl.LogAnnotation("minTranscriptionKeepAliveTimeSec",
                RuntimeConfiguration?.minTranscriptionKeepAliveTimeInSeconds.ToString(CultureInfo.InvariantCulture));
            voiceSDKLoggerImpl.LogAnnotation("maxRecordingTime",
                RuntimeConfiguration?.maxRecordingTime.ToString(CultureInfo.InvariantCulture));
        }
OnSend()
void Oculus.Voice.AppVoiceExperience.OnSend (VoiceServiceRequest request) private
Definition at line 409 of file AppVoiceExperience.cs.
        {
            voiceSDKLoggerImpl.LogInteractionPoint("witRequestCreated");
            if (request != null)
            {
                voiceSDKLoggerImpl.LogAnnotation("requestIdOverride", request.Options?.RequestId);
            }
        }
OnStartedListening()
void Oculus.Voice.AppVoiceExperience.OnStartedListening () private
Definition at line 374 of file AppVoiceExperience.cs.
        {
            voiceSDKLoggerImpl.LogInteractionPoint("startedListening");
        }
OnStoppedListening()
void Oculus.Voice.AppVoiceExperience.OnStoppedListening () private
Definition at line 384 of file AppVoiceExperience.cs.
        {
            voiceSDKLoggerImpl.LogInteractionPoint("stoppedListening");
        }
OnStoppedListeningDueToDeactivation()
void Oculus.Voice.AppVoiceExperience.OnStoppedListeningDueToDeactivation () private
Definition at line 399 of file AppVoiceExperience.cs.
        {
            voiceSDKLoggerImpl.LogInteractionPoint("stoppedListeningDeactivate");
        }
OnStoppedListeningDueToInactivity()
void Oculus.Voice.AppVoiceExperience.OnStoppedListeningDueToInactivity () private
Definition at line 394 of file AppVoiceExperience.cs.
        {
            voiceSDKLoggerImpl.LogInteractionPoint("stoppedListeningInactivity");
        }
OnStoppedListeningDueToTimeout()
void Oculus.Voice.AppVoiceExperience.OnStoppedListeningDueToTimeout () private
Definition at line 389 of file AppVoiceExperience.cs.
        {
            voiceSDKLoggerImpl.LogInteractionPoint("stoppedListeningTimeout");
        }
OnWitResponseListener()
void Oculus.Voice.AppVoiceExperience.OnWitResponseListener (WitResponseNode witResponseNode) private
Definition at line 363 of file AppVoiceExperience.cs.
        {
            var tokens = witResponseNode?["speech"]?["tokens"];
            if (tokens != null)
            {
                int speechTokensLength = tokens.Count;
                string speechLength = witResponseNode["speech"]["tokens"][speechTokensLength - 1]?["end"]?.Value;
                voiceSDKLoggerImpl.LogAnnotation("audioLength", speechLength);
            }
        }
RevertToWitUnity()
void Oculus.Voice.AppVoiceExperience.RevertToWitUnity () private
Definition at line 247 of file AppVoiceExperience.cs.
        {
            Wit w = GetComponent<Wit>();
            if (null == w)
            {
                w = gameObject.AddComponent<Wit>();
                w.hideFlags = HideFlags.HideInInspector;
            }
            voiceServiceImpl = w;
            if (voiceServiceImpl is Wit wit)
            {
                wit.RuntimeConfiguration = witRuntimeConfiguration;
            }
            voiceServiceImpl.VoiceEvents = VoiceEvents;
            voiceServiceImpl.TelemetryEvents = TelemetryEvents;
            voiceSDKLoggerImpl.IsUsingPlatformIntegration = false;
        }
Member Data Documentation
enableConsoleLogging
bool Oculus.Voice.AppVoiceExperience.enableConsoleLogging private
Definition at line 48 of file AppVoiceExperience.cs.
platformService
IPlatformVoiceService Oculus.Voice.AppVoiceExperience.platformService private
Definition at line 58 of file AppVoiceExperience.cs.
usePlatformServices
bool Oculus.Voice.AppVoiceExperience.usePlatformServices private
Definition at line 45 of file AppVoiceExperience.cs.
voiceSDKLoggerImpl
IVoiceSDKLogger Oculus.Voice.AppVoiceExperience.voiceSDKLoggerImpl private
Definition at line 60 of file AppVoiceExperience.cs.
voiceServiceImpl
IVoiceService Oculus.Voice.AppVoiceExperience.voiceServiceImpl private
Definition at line 59 of file AppVoiceExperience.cs.
witRuntimeConfiguration
WitRuntimeConfiguration Oculus.Voice.AppVoiceExperience.witRuntimeConfiguration private
Definition at line 43 of file AppVoiceExperience.cs.
Property Documentation
Active
override bool Oculus.Voice.AppVoiceExperience.Active get
Returns true if this voice service is currently active and listening with the mic.
Implements Meta.WitAi.IVoiceActivationHandler.
Definition at line 69 of file AppVoiceExperience.cs.
Configuration
WitConfiguration Oculus.Voice.AppVoiceExperience.Configuration get
Implements Meta.WitAi.Interfaces.IWitConfigurationProvider.
Definition at line 56 of file AppVoiceExperience.cs.
EnableConsoleLogging
bool Oculus.Voice.AppVoiceExperience.EnableConsoleLogging get
Definition at line 93 of file AppVoiceExperience.cs.
HasPlatformIntegrations
bool Oculus.Voice.AppVoiceExperience.HasPlatformIntegrations get
Definition at line 90 of file AppVoiceExperience.cs.
Initialized
bool Oculus.Voice.AppVoiceExperience.Initialized get private
Definition at line 64 of file AppVoiceExperience.cs.
IsRequestActive
override bool Oculus.Voice.AppVoiceExperience.IsRequestActive get
Returns true if voice service is currently active or request is transmitting.
Implements Meta.WitAi.IVoiceService.
Definition at line 70 of file AppVoiceExperience.cs.
MicActive
override bool Oculus.Voice.AppVoiceExperience.MicActive get
Returns true Mic is still enabled.
Implements Meta.WitAi.IVoiceService.
Definition at line 82 of file AppVoiceExperience.cs.
PACKAGE_VERSION
string Oculus.Voice.AppVoiceExperience.PACKAGE_VERSION static get private
Definition at line 62 of file AppVoiceExperience.cs.
RuntimeConfiguration
WitRuntimeConfiguration Oculus.Voice.AppVoiceExperience.RuntimeConfiguration get set
Implements Meta.WitAi.IWitRuntimeConfigProvider.
Definition at line 50 of file AppVoiceExperience.cs.
        {
            get => witRuntimeConfiguration;
            set => witRuntimeConfiguration = value;
        }
ShouldSendMicData
override bool Oculus.Voice.AppVoiceExperience.ShouldSendMicData get protected
Definition at line 83 of file AppVoiceExperience.cs.
TranscriptionProvider
override ITranscriptionProvider Oculus.Voice.AppVoiceExperience.TranscriptionProvider get set
Easy acccess for transcription.
Implements Meta.WitAi.IVoiceService.
Definition at line 71 of file AppVoiceExperience.cs.
        {
            get => voiceServiceImpl?.TranscriptionProvider;
            set
            {
                if (voiceServiceImpl != null)
                {
                    voiceServiceImpl.TranscriptionProvider = value;
                }
            }
        }
UsePlatformIntegrations
bool Oculus.Voice.AppVoiceExperience.UsePlatformIntegrations get set
Definition at line 95 of file AppVoiceExperience.cs.
        {
            get => usePlatformServices;
            set
            {
                // If we're trying to turn on platform services and they're not currently active we
                // will forcibly reinit and try to set the state.
                if (usePlatformServices != value || HasPlatformIntegrations != value)
                {
                    usePlatformServices = value;
#if UNITY_ANDROID && !UNITY_EDITOR
                    Debug.Log($"{(usePlatformServices ? "Enabling" : "Disabling")} platform integration.");
                    InitVoiceSDK();
#endif
                }
            }
        }
Event Documentation
OnInitialized
Action Oculus.Voice.AppVoiceExperience.OnInitialized
Definition at line 66 of file AppVoiceExperience.cs.
The documentation for this class was generated from the following file:
Assets/Oculus/Voice/Scripts/Runtime/Service/AppVoiceExperience.cs