VR_Test: Oculus.Interaction.Grab.GrabSurfaces.BezierGrabSurface Class Reference
Oculus.Interaction.Grab.GrabSurfaces.BezierGrabSurface Class Reference
Defines a series of points that specify paths along with the snapping pose is valid. The points can be connected to the previous and/or next one, even looping, or completely isolated. When two or more consecutive points are connected, they define a continuous path. The Tangent can be used to specify the curve between two points. It is also possible to connect the last point with the first one to create a closed loop. The rotation at a point in the path is specified by interpolating the rotation of the starting and ending point of the current segment. When a point is not connected to any other point, it is considered as a single point in space.
Public Member Functions
GrabPoseScore CalculateBestPoseAtSurface (in Pose targetPose, out Pose bestPose, in PoseMeasureParameters scoringModifier, Transform relativeTo)
Finds the Pose at the surface that is the closest to the given pose.
bool CalculateBestPoseAtSurface (Ray targetRay, out Pose bestPose, Transform relativeTo)
Finds the Pose at the surface that is the closest to the given ray.
IGrabSurface CreateDuplicatedSurface (GameObject gameObject)
Creates a new IGrabSurface under the selected gameobject with the same data as this one.
IGrabSurface CreateMirroredSurface (GameObject gameObject)
Creates a new IGrabSurface under the selected gameobject that is a mirror version of the current.
Pose MirrorPose (in Pose gripPose, Transform relativeTo)
Method for mirroring a Pose around the surface. Different surfaces will prefer mirroring along different axis.
void InjectAllBezierSurface (List< BezierControlPoint > controlPoints, Transform relativeTo)
void InjectControlPoints (List< BezierControlPoint > controlPoints)
void InjectRelativeTo (Transform relativeTo)
Static Public Member Functions
static Vector3 EvaluateBezier (Vector3 start, Vector3 middle, Vector3 end, float t)
Protected Member Functions
virtual void Reset ()
virtual void Start ()
Properties
List< BezierControlPoint > ControlPoints [get]
Private Member Functions
Plane GenerateRaycastPlane (Vector3 p0, Vector3 p1, Vector3 p2, Vector3 fallbackDir)
float ProgressForRotation (Quaternion targetRotation, Quaternion from, Quaternion to)
Vector3 NearestPointInTriangle (Vector3 point, Vector3 p0, Vector3 p1, Vector3 p2, out float t)
Vector3 NearestPointToSegment (Vector3 point, Vector3 start, Vector3 end, out float progress)
Private Attributes
List< BezierControlPoint > _controlPoints = new List<BezierControlPoint>()
Transform _relativeTo
Static Private Attributes
const float MAX_PLANE_DOT = 0.95f
Detailed Description
Defines a series of points that specify paths along with the snapping pose is valid. The points can be connected to the previous and/or next one, even looping, or completely isolated. When two or more consecutive points are connected, they define a continuous path. The Tangent can be used to specify the curve between two points. It is also possible to connect the last point with the first one to create a closed loop. The rotation at a point in the path is specified by interpolating the rotation of the starting and ending point of the current segment. When a point is not connected to any other point, it is considered as a single point in space.
Definition at line 38 of file BezierGrabSurface.cs.
Member Function Documentation
CalculateBestPoseAtSurface() [1/2]
GrabPoseScore Oculus.Interaction.Grab.GrabSurfaces.BezierGrabSurface.CalculateBestPoseAtSurface (in Pose targetPose, out Pose bestPose, in PoseMeasureParameters scoringModifier, Transform relativeTo)
Finds the Pose at the surface that is the closest to the given pose.
Parameters
targetPose The pose to find the nearest to.
bestPose The best found pose at the surface.<
scoringModifier Weight used to decide which target pose to select
relativeTo Reference transform to measure the poses against
Returns
The score indicating how good the found pose was, -1 for invalid result.
Implements Oculus.Interaction.Grab.GrabSurfaces.IGrabSurface.
Definition at line 64 of file BezierGrabSurface.cs.
        {
            Pose testPose = Pose.identity;
            Pose smallestRotationPose = Pose.identity;
            bestPose = targetPose;
            GrabPoseScore bestScore = GrabPoseScore.Max;
            for (int i = 0; i < _controlPoints.Count; i++)
            {
                BezierControlPoint currentControlPoint = _controlPoints[i];
                BezierControlPoint nextControlPoint = _controlPoints[(i + 1) % _controlPoints.Count];
                if (!currentControlPoint.Disconnected
                    && nextControlPoint.Disconnected)
                {
                    continue;
                }
                GrabPoseScore score;
                if ((currentControlPoint.Disconnected && nextControlPoint.Disconnected)
                    || _controlPoints.Count == 1)
                {
                    Pose worldPose = currentControlPoint.GetPose(relativeTo);
                    testPose.CopyFrom(worldPose);
                    score = new GrabPoseScore(targetPose, testPose, scoringModifier.PositionRotationWeight);
                }
                else
                {
                    Pose start = currentControlPoint.GetPose(relativeTo);
                    Pose end = nextControlPoint.GetPose(relativeTo);
                    Vector3 tangent = currentControlPoint.GetTangent(relativeTo);
                    NearestPointInTriangle(targetPose.position, start.position, tangent, end.position, out float positionT);
                    float rotationT = ProgressForRotation(targetPose.rotation, start.rotation, end.rotation);
                    score = GrabPoseHelper.CalculateBestPoseAtSurface(targetPose, out testPose, scoringModifier, relativeTo,
                        (in Pose target, Transform relativeTo) =>
{
                            Pose result;
                            result.position = EvaluateBezier(start.position, tangent, end.position, positionT);
                            result.rotation = Quaternion.Slerp(start.rotation, end.rotation, positionT);
                            return result;
                        },
                        (in Pose target, Transform relativeTo) =>
{
                            Pose result;
                            result.position = EvaluateBezier(start.position, tangent, end.position, rotationT);
                            result.rotation = Quaternion.Slerp(start.rotation, end.rotation, rotationT);
                            return result;
                        });
                }
                if (score.IsBetterThan(bestScore))
                {
                    bestScore = score;
                    bestPose.CopyFrom(testPose);
                }
            }
            return bestScore;
        }
References Oculus.Interaction.Grab.GrabPoseHelper.CalculateBestPoseAtSurface(), and Oculus.Interaction.Grab.GrabPoseScore.IsBetterThan().
CalculateBestPoseAtSurface() [2/2]
bool Oculus.Interaction.Grab.GrabSurfaces.BezierGrabSurface.CalculateBestPoseAtSurface (Ray targetRay, out Pose bestPose, Transform relativeTo)
Finds the Pose at the surface that is the closest to the given ray.
Parameters
targetRay Ray searching for the nearest snap pose
bestPose The best found pose at the surface.
relativeTo Reference transform to measure the poses against
Returns
True if the pose was found
Implements Oculus.Interaction.Grab.GrabSurfaces.IGrabSurface.
Definition at line 126 of file BezierGrabSurface.cs.
        {
            Pose testPose = Pose.identity;
            Pose targetPose = Pose.identity;
            bestPose = Pose.identity;
            bool poseFound = false;
            GrabPoseScore bestScore = GrabPoseScore.Max;
            for (int i = 0; i < _controlPoints.Count; i++)
            {
                BezierControlPoint currentControlPoint = _controlPoints[i];
                BezierControlPoint nextControlPoint = _controlPoints[(i + 1) % _controlPoints.Count];
                if (!currentControlPoint.Disconnected
                    && nextControlPoint.Disconnected)
                {
                    continue;
                }
                if ((currentControlPoint.Disconnected && nextControlPoint.Disconnected)
                    || _controlPoints.Count == 1)
                {
                    Pose worldPose = currentControlPoint.GetPose(relativeTo);
                    Plane plane = new Plane(-targetRay.direction, worldPose.position);
                    if (!plane.Raycast(targetRay, out float enter))
                    {
                        continue;
                    }
                    targetPose.position = targetRay.GetPoint(enter);
                    testPose.CopyFrom(worldPose);
                }
                else
                {
                    Pose start = currentControlPoint.GetPose(relativeTo);
                    Pose end = nextControlPoint.GetPose(relativeTo);
                    Vector3 tangent = currentControlPoint.GetTangent(relativeTo);
                    Plane plane = GenerateRaycastPlane(start.position, tangent, end.position, -targetRay.direction);
                    if (!plane.Raycast(targetRay, out float enter))
                    {
                        continue;
                    }
                    targetPose.position = targetRay.GetPoint(enter);
                    NearestPointInTriangle(targetPose.position, start.position, tangent, end.position, out float t);
                    testPose.position = EvaluateBezier(start.position, tangent, end.position, t);
                    testPose.rotation = Quaternion.Slerp(start.rotation, end.rotation, t);
                }
                GrabPoseScore score = new GrabPoseScore(targetPose.position, testPose.position);
                if (score.IsBetterThan(bestScore))
                {
                    bestScore = score;
                    bestPose.CopyFrom(testPose);
                    poseFound = true;
                }
            }
            return poseFound;
        }
References Oculus.Interaction.Grab.GrabPoseScore.IsBetterThan().
CreateDuplicatedSurface()
IGrabSurface Oculus.Interaction.Grab.GrabSurfaces.BezierGrabSurface.CreateDuplicatedSurface (GameObject gameObject)
Creates a new IGrabSurface under the selected gameobject with the same data as this one.
Parameters
gameObject The gameobject in which to place the new IGrabSurface.
Returns
A clone of this IGrabSurface.
Implements Oculus.Interaction.Grab.GrabSurfaces.IGrabSurface.
Definition at line 270 of file BezierGrabSurface.cs.
        {
            BezierGrabSurface surface = gameObject.AddComponent<BezierGrabSurface>();
            surface._controlPoints = new List<BezierControlPoint>(_controlPoints);
            return surface;
        }
CreateMirroredSurface()
IGrabSurface Oculus.Interaction.Grab.GrabSurfaces.BezierGrabSurface.CreateMirroredSurface (GameObject gameObject)
Creates a new IGrabSurface under the selected gameobject that is a mirror version of the current.
Parameters
gameObject The gameobject in which to place the new IGrabSurface.
Returns
A mirror of this IGrabSurface.
Implements Oculus.Interaction.Grab.GrabSurfaces.IGrabSurface.
Definition at line 277 of file BezierGrabSurface.cs.
        {
            BezierGrabSurface mirroredSurface = gameObject.AddComponent<BezierGrabSurface>();
            mirroredSurface._controlPoints = new List<BezierControlPoint>();
            foreach (BezierControlPoint controlPoint in _controlPoints)
            {
                Pose pose = controlPoint.GetPose(_relativeTo);
                pose.rotation = pose.rotation * Quaternion.Euler(180f, 180f, 0f);
                controlPoint.SetPose(pose, _relativeTo);
                mirroredSurface._controlPoints.Add(controlPoint);
            }
            return mirroredSurface;
        }
EvaluateBezier()
static Vector3 Oculus.Interaction.Grab.GrabSurfaces.BezierGrabSurface.EvaluateBezier (Vector3 start, Vector3 middle, Vector3 end, float t) static
Definition at line 297 of file BezierGrabSurface.cs.
        {
            t = Mathf.Clamp01(t);
            float oneMinusT = 1f - t;
            return (oneMinusT * oneMinusT * start)
                + (2f * oneMinusT * t * middle)
                + (t * t * end);
        }
GenerateRaycastPlane()
Plane Oculus.Interaction.Grab.GrabSurfaces.BezierGrabSurface.GenerateRaycastPlane (Vector3 p0, Vector3 p1, Vector3 p2, Vector3 fallbackDir) private
Definition at line 183 of file BezierGrabSurface.cs.
        {
            Vector3 line0 = (p1 - p0).normalized;
            Vector3 line1 = (p2 - p0).normalized;
            Plane plane;
            if (Mathf.Abs(Vector3.Dot(line0, line1)) > MAX_PLANE_DOT)
            {
                plane = new Plane(fallbackDir, (p0 + p2 + p1) / 3f);
            }
            else
            {
                plane = new Plane(p0, p1, p2);
            }
            return plane;
        }
InjectAllBezierSurface()
void Oculus.Interaction.Grab.GrabSurfaces.BezierGrabSurface.InjectAllBezierSurface (List< BezierControlPoint > controlPoints, Transform relativeTo)
Definition at line 307 of file BezierGrabSurface.cs.
        {
            InjectControlPoints(controlPoints);
            InjectRelativeTo(relativeTo);
        }
InjectControlPoints()
void Oculus.Interaction.Grab.GrabSurfaces.BezierGrabSurface.InjectControlPoints (List< BezierControlPoint > controlPoints)
Definition at line 314 of file BezierGrabSurface.cs.
        {
            _controlPoints = controlPoints;
        }
InjectRelativeTo()
void Oculus.Interaction.Grab.GrabSurfaces.BezierGrabSurface.InjectRelativeTo (Transform relativeTo)
Definition at line 319 of file BezierGrabSurface.cs.
        {
            _relativeTo = relativeTo;
        }
MirrorPose()
Pose Oculus.Interaction.Grab.GrabSurfaces.BezierGrabSurface.MirrorPose (in Pose gripPose, Transform relativeTo)
Method for mirroring a Pose around the surface. Different surfaces will prefer mirroring along different axis.
Parameters
gripPose The Pose to be mirrored.
relativeTo Reference transform to mirror the pose around
Returns
A new pose mirrored at this surface.
Implements Oculus.Interaction.Grab.GrabSurfaces.IGrabSurface.
Definition at line 292 of file BezierGrabSurface.cs.
        {
            return gripPose;
        }
NearestPointInTriangle()
Vector3 Oculus.Interaction.Grab.GrabSurfaces.BezierGrabSurface.NearestPointInTriangle (Vector3 point, Vector3 p0, Vector3 p1, Vector3 p2, out float t) private
Definition at line 221 of file BezierGrabSurface.cs.
        {
            Vector3 centroid = (p0 + p1 + p2) / 3f;
            Vector3 pointInMedian0 = NearestPointToSegment(point, p0, centroid, out float t0);
            Vector3 pointInMedian1 = NearestPointToSegment(point, centroid, p2, out float t1);
            float median0 = Vector3.Distance(p0, centroid);
            float median2 = Vector3.Distance(p2, centroid);
            float alpha = median2 / (median0 + median2);
            float distance0 = (pointInMedian0 - point).sqrMagnitude;
            float distance1 = (pointInMedian1 - point).sqrMagnitude;
            if (distance0 < distance1)
            {
                t = t0 * alpha;
                return pointInMedian0;
            }
            else
            {
                t = alpha + t1 * (1f - alpha);
                return pointInMedian1;
            }
        }
NearestPointToSegment()
Vector3 Oculus.Interaction.Grab.GrabSurfaces.BezierGrabSurface.NearestPointToSegment (Vector3 point, Vector3 start, Vector3 end, out float progress) private
Definition at line 246 of file BezierGrabSurface.cs.
        {
            Vector3 segment = end - start;
            Vector3 projection = Vector3.Project(point - start, segment.normalized);
            Vector3 pointInSegment;
            if (Vector3.Dot(segment, projection) <= 0)
            {
                pointInSegment = start;
                progress = 0;
            }
            else if (projection.sqrMagnitude >= segment.sqrMagnitude)
            {
                pointInSegment = end;
                progress = 1;
            }
            else
            {
                pointInSegment = start + projection;
                progress = projection.magnitude / segment.magnitude;
            }
            return pointInSegment;
        }
ProgressForRotation()
float Oculus.Interaction.Grab.GrabSurfaces.BezierGrabSurface.ProgressForRotation (Quaternion targetRotation, Quaternion from, Quaternion to) private
Definition at line 200 of file BezierGrabSurface.cs.
        {
            Vector3 targetForward = targetRotation * Vector3.forward;
            Vector3 fromForward = from * Vector3.forward;
            Vector3 toForward = to * Vector3.forward;
            Vector3 axis = Vector3.Cross(fromForward, toForward).normalized;
            float angleFrom = Vector3.SignedAngle(targetForward, fromForward, axis);
            float angleTo = Vector3.SignedAngle(targetForward, toForward, axis);
            if (angleFrom < 0 && angleTo < 0)
            {
                return 1f;
            }
            if (angleFrom > 0 && angleTo > 0)
            {
                return 0f;
            }
            return Mathf.Abs(angleFrom) / Vector3.Angle(fromForward, toForward);
        }
Reset()
virtual void Oculus.Interaction.Grab.GrabSurfaces.BezierGrabSurface.Reset () protected virtual
Definition at line 52 of file BezierGrabSurface.cs.
        {
            _relativeTo = this.GetComponentInParent<IRelativeToRef>()?.RelativeTo;
        }
Start()
virtual void Oculus.Interaction.Grab.GrabSurfaces.BezierGrabSurface.Start () protected virtual
Definition at line 58 of file BezierGrabSurface.cs.
        {
            this.AssertCollectionField(ControlPoints, nameof(ControlPoints));
            this.AssertField(_relativeTo, nameof(_relativeTo));
        }
Member Data Documentation
_controlPoints
List<BezierControlPoint> Oculus.Interaction.Grab.GrabSurfaces.BezierGrabSurface._controlPoints = new List<BezierControlPoint>() private
Definition at line 41 of file BezierGrabSurface.cs.
_relativeTo
Transform Oculus.Interaction.Grab.GrabSurfaces.BezierGrabSurface._relativeTo private
Definition at line 45 of file BezierGrabSurface.cs.
MAX_PLANE_DOT
const float Oculus.Interaction.Grab.GrabSurfaces.BezierGrabSurface.MAX_PLANE_DOT = 0.95f static private
Definition at line 49 of file BezierGrabSurface.cs.
Property Documentation
ControlPoints
List<BezierControlPoint> Oculus.Interaction.Grab.GrabSurfaces.BezierGrabSurface.ControlPoints get
Definition at line 47 of file BezierGrabSurface.cs.
The documentation for this class was generated from the following file:
Assets/Oculus/Interaction/Runtime/Scripts/Grab/SnapSurfaces/BezierGrabSurface.cs