VR_Test: OVRLipSyncContext Class Reference
OVRLipSyncContext Class Reference
OVRLipSyncContext interfaces into the Oculus phoneme recognizer. This component should be added into the scene once for each Audio Source.
Public Member Functions
void PreprocessAudioSamples (float[] data, int channels)
Preprocess F32 PCM audio buffer.
void PostprocessAudioSamples (float[] data, int channels)
Postprocess F32 PCM audio buffer.
void ProcessAudioSamplesRaw (float[] data, int channels)
Pass F32 PCM audio buffer to the lip sync module.
void ProcessAudioSamplesRaw (short[] data, int channels)
Pass S16 PCM audio buffer to the lip sync module.
void ProcessAudioSamples (float[] data, int channels)
Process F32 audio sample and pass it to the lip sync module for computation.
Public Member Functions inherited from OVRLipSyncContextBase
OVRLipSync.Frame GetCurrentPhonemeFrame ()
Gets the current phoneme frame (lock and copy current frame to caller frame)
void SetVisemeBlend (int viseme, int amount)
Sets a given viseme id blend weight to a given amount.
void SetLaughterBlend (int amount)
Sets a given viseme id blend weight to a given amount.
OVRLipSync.Result ResetContext ()
Resets the context.
Public Attributes
bool enableKeyboardInput = false
bool enableTouchInput = false
bool audioLoopback = false
KeyCode loopbackKey = KeyCode.L
bool showVisemes = false
KeyCode debugVisemesKey = KeyCode.D
bool skipAudioSource = false
float gain = 1.0f
KeyCode debugLaughterKey = KeyCode.H
bool showLaughter = false
float laughterScore = 0.0f
Public Attributes inherited from OVRLipSyncContextBase
AudioSource audioSource = null
OVRLipSync.ContextProviders provider = OVRLipSync.ContextProviders.Enhanced
bool enableAcceleration = true
Private Member Functions
void Start ()
Start this instance. Note: make sure to always have a Start function for classes that have editor scripts.
void HandleKeyboard ()
Handle keyboard input.
void Update ()
Run processes that need to be updated in our game thread.
void OnAudioFilterRead (float[] data, int channels)
Raises the audio filter read event.
void DebugShowVisemesAndLaughter ()
Print the visemes and laughter score to game window.
void ToggleAudioLoopback ()
void LocalTouchEventCallback (OVRTouchpad.TouchEvent touchEvent)
Private Attributes
bool hasDebugConsole = false
Additional Inherited Members
Properties inherited from OVRLipSyncContextBase
int Smoothing [get, set]
uint Context [get]
OVRLipSync.Frame Frame [get]
Detailed Description
OVRLipSyncContext interfaces into the Oculus phoneme recognizer. This component should be added into the scene once for each Audio Source.
Definition at line 35 of file OVRLipSyncContext.cs.
Member Function Documentation
DebugShowVisemesAndLaughter()
void OVRLipSyncContext.DebugShowVisemesAndLaughter () private
Print the visemes and laughter score to game window.
Definition at line 295 of file OVRLipSyncContext.cs.
    {
        if (hasDebugConsole)
        {
            string seq = "";
            if (showLaughter)
            {
                seq += "Laughter:";
                int count = (int)(50.0f * this.Frame.laughterScore);
                for (int c = 0; c < count; c++)
                    seq += "*";
                seq += "\n";
            }
            if (showVisemes)
            {
                for (int i = 0; i < this.Frame.Visemes.Length; i++)
                {
                    seq += ((OVRLipSync.Viseme)i).ToString();
                    seq += ":";
                    int count = (int)(50.0f * this.Frame.Visemes[i]);
                    for (int c = 0; c < count; c++)
                        seq += "*";
                    seq += "\n";
                }
            }
            OVRLipSyncDebugConsole.Clear();
            if (seq != "")
            {
                OVRLipSyncDebugConsole.Log(seq);
            }
        }
    }
References OVRLipSyncDebugConsole.Clear(), and OVRLipSyncDebugConsole.Log().
HandleKeyboard()
void OVRLipSyncContext.HandleKeyboard () private
Handle keyboard input.
Definition at line 90 of file OVRLipSyncContext.cs.
    {
        // Turn loopback on/off
        if (Input.GetKeyDown(loopbackKey))
        {
            ToggleAudioLoopback();
        }
        else if (Input.GetKeyDown(debugVisemesKey))
        {
            showVisemes = !showVisemes;
            if (showVisemes)
            {
                if (hasDebugConsole)
                {
                    Debug.Log("DEBUG SHOW VISEMES: ENABLED");
                }
                else
                {
                    Debug.LogWarning("Warning: No OVRLipSyncDebugConsole in the scene!");
                    showVisemes = false;
                }
            }
            else
            {
                if (hasDebugConsole)
                {
                    OVRLipSyncDebugConsole.Clear();
                }
                Debug.Log("DEBUG SHOW VISEMES: DISABLED");
            }
        }
        else if (Input.GetKeyDown(debugLaughterKey))
        {
            showLaughter = !showLaughter;
            if (showLaughter)
            {
                if (hasDebugConsole)
                {
                    Debug.Log("DEBUG SHOW LAUGHTER: ENABLED");
                }
                else
                {
                    Debug.LogWarning("Warning: No OVRLipSyncDebugConsole in the scene!");
                    showLaughter = false;
                }
            }
            else
            {
                if (hasDebugConsole)
                {
                    OVRLipSyncDebugConsole.Clear();
                }
                Debug.Log("DEBUG SHOW LAUGHTER: DISABLED");
            }
        }
        else if (Input.GetKeyDown(KeyCode.LeftArrow))
        {
            gain -= 1.0f;
            if (gain < 1.0f) gain = 1.0f;
            string g = "LINEAR GAIN: ";
            g += gain;
            if (hasDebugConsole)
            {
                OVRLipSyncDebugConsole.Clear();
                OVRLipSyncDebugConsole.Log(g);
                OVRLipSyncDebugConsole.ClearTimeout(1.5f);
            }
        }
        else if (Input.GetKeyDown(KeyCode.RightArrow))
        {
            gain += 1.0f;
            if (gain > 15.0f)
                gain = 15.0f;
            string g = "LINEAR GAIN: ";
            g += gain;
            if (hasDebugConsole)
            {
                OVRLipSyncDebugConsole.Clear();
                OVRLipSyncDebugConsole.Log(g);
                OVRLipSyncDebugConsole.ClearTimeout(1.5f);
            }
        }
    }
References OVRLipSyncDebugConsole.Clear(), OVRLipSyncDebugConsole.ClearTimeout(), and OVRLipSyncDebugConsole.Log().
LocalTouchEventCallback()
void OVRLipSyncContext.LocalTouchEventCallback (OVRTouchpad::TouchEvent touchEvent) private
Definition at line 349 of file OVRLipSyncContext.cs.
    {
        string g = "LINEAR GAIN: ";
        switch (touchEvent)
        {
            case (OVRTouchpad.TouchEvent.SingleTap):
                ToggleAudioLoopback();
                break;
            case (OVRTouchpad.TouchEvent.Up):
                gain += 1.0f;
                if (gain > 15.0f)
                    gain = 15.0f;
                g += gain;
                if (hasDebugConsole)
                {
                    OVRLipSyncDebugConsole.Clear();
                    OVRLipSyncDebugConsole.Log(g);
                    OVRLipSyncDebugConsole.ClearTimeout(1.5f);
                }
                break;
            case (OVRTouchpad.TouchEvent.Down):
                gain -= 1.0f;
                if (gain < 1.0f) gain = 1.0f;
                g += gain;
                if (hasDebugConsole)
                {
                    OVRLipSyncDebugConsole.Clear();
                    OVRLipSyncDebugConsole.Log(g);
                    OVRLipSyncDebugConsole.ClearTimeout(1.5f);
                }
                break;
        }
    }
OnAudioFilterRead()
void OVRLipSyncContext.OnAudioFilterRead (float[] data, int channels) private
Raises the audio filter read event.
Parameters
data Data.
channels Channels.
Definition at line 284 of file OVRLipSyncContext.cs.
    {
        if (!skipAudioSource)
        {
            ProcessAudioSamples(data, channels);
        }
    }
References ProcessAudioSamples().
PostprocessAudioSamples()
void OVRLipSyncContext.PostprocessAudioSamples (float[] data, int channels)
Postprocess F32 PCM audio buffer.
Parameters
data Data.
channels Channels.
Definition at line 212 of file OVRLipSyncContext.cs.
    {
        // Turn off output (so that we don't get feedback from mics too close to speakers)
        if (!audioLoopback)
        {
            for (int i = 0; i < data.Length; ++i)
                data[i] = data[i] * 0.0f;
        }
    }
PreprocessAudioSamples()
void OVRLipSyncContext.PreprocessAudioSamples (float[] data, int channels)
Preprocess F32 PCM audio buffer.
Parameters
data Data.
channels Channels.
Definition at line 198 of file OVRLipSyncContext.cs.
    {
        // Increase the gain of the input
        for (int i = 0; i < data.Length; ++i)
        {
            data[i] = data[i] * gain;
        }
    }
ProcessAudioSamples()
void OVRLipSyncContext.ProcessAudioSamples (float[] data, int channels)
Process F32 audio sample and pass it to the lip sync module for computation.
Parameters
data Data.
channels Channels.
Definition at line 266 of file OVRLipSyncContext.cs.
    {
        // Do not process if we are not initialized, or if there is no
        // audio source attached to game object
        if ((OVRLipSync.IsInitialized() != OVRLipSync.Result.Success) || audioSource == null)
        {
            return;
        }
        PreprocessAudioSamples(data, channels);
        ProcessAudioSamplesRaw(data, channels);
        PostprocessAudioSamples(data, channels);
    }
References OVRLipSync.IsInitialized(), PostprocessAudioSamples(), PreprocessAudioSamples(), and ProcessAudioSamplesRaw().
ProcessAudioSamplesRaw() [1/2]
void OVRLipSyncContext.ProcessAudioSamplesRaw (float[] data, int channels)
Pass F32 PCM audio buffer to the lip sync module.
Parameters
data Data.
channels Channels.
Definition at line 227 of file OVRLipSyncContext.cs.
    {
        // Send data into Phoneme context for processing (if context is not 0)
        lock (this)
        {
            if (Context == 0 || OVRLipSync.IsInitialized() != OVRLipSync.Result.Success)
            {
                return;
            }
            var frame = this.Frame;
            OVRLipSync.ProcessFrame(Context, data, frame, channels == 2);
        }
    }
References OVRLipSync.IsInitialized(), and OVRLipSync.ProcessFrame().
ProcessAudioSamplesRaw() [2/2]
void OVRLipSyncContext.ProcessAudioSamplesRaw (short[] data, int channels)
Pass S16 PCM audio buffer to the lip sync module.
Parameters
data Data.
channels Channels.
Definition at line 246 of file OVRLipSyncContext.cs.
    {
        // Send data into Phoneme context for processing (if context is not 0)
        lock (this)
        {
            if (Context == 0 || OVRLipSync.IsInitialized() != OVRLipSync.Result.Success)
            {
                return;
            }
            var frame = this.Frame;
            OVRLipSync.ProcessFrame(Context, data, frame, channels == 2);
        }
    }
References OVRLipSync.IsInitialized(), and OVRLipSync.ProcessFrame().
Start()
void OVRLipSyncContext.Start () private
Start this instance. Note: make sure to always have a Start function for classes that have editor scripts.
Definition at line 71 of file OVRLipSyncContext.cs.
    {
        // Add a listener to the OVRTouchpad for touch events
        if (enableTouchInput)
        {
            OVRTouchpad.AddListener(LocalTouchEventCallback);
        }
        // Find console
        OVRLipSyncDebugConsole[] consoles = FindObjectsOfType<OVRLipSyncDebugConsole>();
        if (consoles.Length > 0)
        {
            hasDebugConsole = consoles[0];
        }
    }
ToggleAudioLoopback()
void OVRLipSyncContext.ToggleAudioLoopback () private
Definition at line 332 of file OVRLipSyncContext.cs.
    {
        audioLoopback = !audioLoopback;
        if (hasDebugConsole)
        {
            OVRLipSyncDebugConsole.Clear();
            OVRLipSyncDebugConsole.ClearTimeout(1.5f);
            if (audioLoopback)
                OVRLipSyncDebugConsole.Log("LOOPBACK MODE: ENABLED");
            else
                OVRLipSyncDebugConsole.Log("LOOPBACK MODE: DISABLED");
        }
    }
Update()
void OVRLipSyncContext.Update () private
Run processes that need to be updated in our game thread.
Definition at line 183 of file OVRLipSyncContext.cs.
    {
        if (enableKeyboardInput)
        {
            HandleKeyboard();
        }
        laughterScore = this.Frame.laughterScore;
        DebugShowVisemesAndLaughter();
    }
References DebugShowVisemesAndLaughter(), and HandleKeyboard().
Member Data Documentation
audioLoopback
bool OVRLipSyncContext.audioLoopback = false
Definition at line 46 of file OVRLipSyncContext.cs.
debugLaughterKey
KeyCode OVRLipSyncContext.debugLaughterKey = KeyCode.H
Definition at line 60 of file OVRLipSyncContext.cs.
debugVisemesKey
KeyCode OVRLipSyncContext.debugVisemesKey = KeyCode.D
Definition at line 52 of file OVRLipSyncContext.cs.
enableKeyboardInput
bool OVRLipSyncContext.enableKeyboardInput = false
Definition at line 42 of file OVRLipSyncContext.cs.
enableTouchInput
bool OVRLipSyncContext.enableTouchInput = false
Definition at line 44 of file OVRLipSyncContext.cs.
gain
float OVRLipSyncContext.gain = 1.0f
Definition at line 56 of file OVRLipSyncContext.cs.
hasDebugConsole
bool OVRLipSyncContext.hasDebugConsole = false private
Definition at line 58 of file OVRLipSyncContext.cs.
laughterScore
float OVRLipSyncContext.laughterScore = 0.0f
Definition at line 62 of file OVRLipSyncContext.cs.
loopbackKey
KeyCode OVRLipSyncContext.loopbackKey = KeyCode.L
Definition at line 48 of file OVRLipSyncContext.cs.
showLaughter
bool OVRLipSyncContext.showLaughter = false
Definition at line 61 of file OVRLipSyncContext.cs.
showVisemes
bool OVRLipSyncContext.showVisemes = false
Definition at line 50 of file OVRLipSyncContext.cs.
skipAudioSource
bool OVRLipSyncContext.skipAudioSource = false
Definition at line 54 of file OVRLipSyncContext.cs.
The documentation for this class was generated from the following file:
Assets/Oculus/LipSync/Scripts/OVRLipSyncContext.cs