VR_Test: Meta.WitAi.VLog Class Reference
Meta.WitAi.VLog Class Reference
Static Public Member Functions
static void D (object log)
Performs a Debug.Log with custom categorization and using the global log level.
static void D (string logCategory, object log)
static void W (object log)
Performs a Debug.LogWarning with custom categorization and using the global log level.
static void W (string logCategory, object log)
static void E (object log)
Performs a Debug.LogError with custom categorization and using the global log level.
static void E (string logCategory, object log)
Properties
static bool SuppressLogs = false [get, set]
Hides all errors from the console.
Events
static Action< StringBuilder, string, LogType > OnPreLog
Event for appending custom data to a log before logging to console.
Static Private Member Functions
static void Log (LogType logType, string logCategory, object log)
Filters out unwanted logs, appends category information and performs UnityEngine.Debug.Log as desired.
static string GetCallingCategory ()
Determines a category from the script name that called the previous method.
static void WrapWithCallingLink (StringBuilder builder, int startIndex)
Determines a category from the script name that called the previous method.
static void WrapWithLogColor (StringBuilder builder, int startIndex, LogType logType)
Get hex value for each log type.
Detailed Description
Definition at line 16 of file VLog.cs.
Member Function Documentation
D()
static void Meta.WitAi.VLog.D (object log) static
Performs a Debug.Log with custom categorization and using the global log level.
Parameters
log The text to be debugged
logCategory The category of the log
E()
static void Meta.WitAi.VLog.E (object log) static
Performs a Debug.LogError with custom categorization and using the global log level.
Parameters
log The text to be debugged
logCategory The category of the log
GetCallingCategory()
static string Meta.WitAi.VLog.GetCallingCategory () static private
Determines a category from the script name that called the previous method.
Returns
Assembly name
Definition at line 161 of file VLog.cs.
        {
            // Get stack trace method
            string path = new StackTrace()?.GetFrame(3)?.GetMethod().DeclaringType.Name;
            if (string.IsNullOrEmpty(path))
            {
                return "NoStacktrace";
            }
            // Return path
            return path;
        }
Log()
static void Meta.WitAi.VLog.Log (LogType logType, string logCategory, object log) static private
Filters out unwanted logs, appends category information and performs UnityEngine.Debug.Log as desired.
Parameters
logType
log
category
Definition at line 88 of file VLog.cs.
        {
            #if UNITY_EDITOR
            // Skip logs with higher log type then global log level
            if ((int) logType > (int)EditorLogLevel)
            {
                return;
            }
            #endif
            // Suppress logs if desired
            if (SuppressLogs)
            {
                return;
            }
            // Use calling category if null
            string category = logCategory;
            if (string.IsNullOrEmpty(category))
            {
                category = GetCallingCategory();
            }
            // String builder
            StringBuilder result = new StringBuilder();
            #if !UNITY_EDITOR && !UNITY_ANDROID
            {
                // Start with datetime if not done so automatically
                DateTime now = DateTime.Now;
                result.Append($"[{now.ToShortDateString()} {now.ToShortTimeString()}] ");
            }
            #endif
            // Insert log type
            int start = result.Length;
            result.Append($"[{logType.ToString().ToUpper()}] ");
            WrapWithLogColor(result, start, logType);
            // Append VDSK & Category
            start = result.Length;
            result.Append("[VSDK");
            if (!string.IsNullOrEmpty(category))
            {
                result.Append($" {category}");
            }
            result.Append("] ");
            WrapWithCallingLink(result, start);
            // Append the actual log
            result.Append(log == null ? string.Empty : log.ToString());
            // Final log append
            OnPreLog?.Invoke(result, logCategory, logType);
            // Log
            switch (logType)
            {
                case LogType.Error:
                    UnityEngine.Debug.LogError(result);
                    break;
                case LogType.Warning:
                    UnityEngine.Debug.LogWarning(result);
                    break;
                default:
                    UnityEngine.Debug.Log(result);
                    break;
            }
        }
References Meta.WitAi.VLog.GetCallingCategory(), Meta.WitAi.VLog.OnPreLog, Meta.WitAi.VLog.SuppressLogs, Meta.WitAi.VLog.WrapWithCallingLink(), and Meta.WitAi.VLog.WrapWithLogColor().
W()
static void Meta.WitAi.VLog.W (object log) static
Performs a Debug.LogWarning with custom categorization and using the global log level.
Parameters
log The text to be debugged
logCategory The category of the log
WrapWithCallingLink()
static void Meta.WitAi.VLog.WrapWithCallingLink (StringBuilder builder, int startIndex) static private
Determines a category from the script name that called the previous method.
Returns
Assembly name
Definition at line 177 of file VLog.cs.
        {
            #if UNITY_EDITOR && UNITY_2021_2_OR_NEWER
            StackTrace stackTrace = new StackTrace(true);
            StackFrame stackFrame = stackTrace.GetFrame(3);
            string callingFileName = stackFrame.GetFileName().Replace('\\', '/');
            int callingFileLine = stackFrame.GetFileLineNumber();
            builder.Insert(startIndex, $"<a href=\"{callingFileName}\" line=\"{callingFileLine}\">");
            builder.Append("</a>");
            #endif
        }
WrapWithLogColor()
static void Meta.WitAi.VLog.WrapWithLogColor (StringBuilder builder, int startIndex, LogType logType) static private
Get hex value for each log type.
Definition at line 192 of file VLog.cs.
        {
            #if UNITY_EDITOR
            string hex;
            switch (logType)
            {
                case LogType.Error:
                    hex = "FF0000";
                    break;
                case LogType.Warning:
                    hex = "FFFF00";
                    break;
                default:
                    hex = "00FF00";
                    break;
            }
            builder.Insert(startIndex, $"<color=#{hex}>");
            builder.Append("</color>");
            #endif
        }
Property Documentation
SuppressLogs
bool Meta.WitAi.VLog.SuppressLogs = false static get set
Hides all errors from the console.
Definition at line 50 of file VLog.cs.
{ get; set; } = false;
Event Documentation
OnPreLog
Action<StringBuilder, string, LogType> Meta.WitAi.VLog.OnPreLog static
Event for appending custom data to a log before logging to console.
Definition at line 55 of file VLog.cs.
The documentation for this class was generated from the following file:
Assets/Oculus/Voice/Lib/Wit.ai/Lib/Wit/Runtime/Utilities/VLog.cs