VR_Test: Oculus.Interaction.Input.HandRef Class Reference
Oculus.Interaction.Input.HandRef Class Reference
HandRef is a utility component that delegates all of its IHand implementation to the provided Hand object.
Public Member Functions
bool GetFingerIsPinching (HandFinger finger)
bool GetIndexFingerIsPinching ()
bool GetPointerPose (out Pose pose)
Attempts to calculate the pose that can be used as a root for raycasting, in world space Returns false if there is no valid tracking data.
bool GetJointPose (HandJointId handJointId, out Pose pose)
Attempts to calculate the pose of the requested hand joint, in world space. Returns false if the skeleton is not yet initialized, or there is no valid tracking data.
bool GetJointPoseLocal (HandJointId handJointId, out Pose pose)
Attempts to calculate the pose of the requested hand joint, in local space. Returns false if the skeleton is not yet initialized, or there is no valid tracking data.
bool GetJointPosesLocal (out ReadOnlyHandJointPoses jointPosesLocal)
Returns an array containing the local pose of each joint. The poses do not have the root pose applied, nor the hand scale. It is in the same coordinate system as the hand skeleton.
bool GetJointPoseFromWrist (HandJointId handJointId, out Pose pose)
Attempts to calculate the pose of the requested hand joint relative to the wrist. Returns false if the skeleton is not yet initialized, or there is no valid tracking data.
bool GetJointPosesFromWrist (out ReadOnlyHandJointPoses jointPosesFromWrist)
Returns an array containing the pose of each joint relative to the wrist. The poses do not have the root pose applied, nor the hand scale. It is in the same coordinate system as the hand skeleton.
bool GetPalmPoseLocal (out Pose pose)
Obtains palm pose in local space.
bool GetFingerIsHighConfidence (HandFinger finger)
float GetFingerPinchStrength (HandFinger finger)
bool GetRootPose (out Pose pose)
Gets the root pose of the wrist, in world space. Will return true if a pose was available; false otherwise. Confidence level of the pose is exposed via IsHighConfidence.
void InjectAllHandRef (IHand hand)
void InjectHand (IHand hand)
Protected Member Functions
virtual void Awake ()
virtual void Start ()
Properties
IHand Hand [get, private set]
Handedness Handedness [get]
bool IsConnected [get]
bool IsHighConfidence [get]
The hand is connected and tracked, and the root pose's tracking data is marked as high confidence. If this is true, then it implies that IsConnected and IsRootPoseValid are also true, so they don't need to be checked in addition to this.
bool IsDominantHand [get]
float Scale [get]
bool IsPointerPoseValid [get]
Will return true if a pointer pose is available, that can be retrieved via GetPointerPose
bool IsTrackedDataValid [get]
True if the hand is currently tracked, thus tracking poses are available for the hand root and finger joints. This property does not indicate pointing pose validity, which has its own property: IsPointerPoseValid.
int CurrentDataVersion [get]
Incremented every time the source tracking or state data changes.
Action WhenHandUpdated
bool Active [get]
Properties inherited from Oculus.Interaction.Input.IHand
Properties inherited from Oculus.Interaction.IActiveState
Private Attributes
UnityEngine.Object _hand
Additional Inherited Members
Events inherited from Oculus.Interaction.Input.IHand
Detailed Description
HandRef is a utility component that delegates all of its IHand implementation to the provided Hand object.
Definition at line 30 of file HandRef.cs.
Member Function Documentation
Awake()
virtual void Oculus.Interaction.Input.HandRef.Awake () protected virtual
Definition at line 61 of file HandRef.cs.
        {
            Hand = _hand as IHand;
        }
GetFingerIsHighConfidence()
bool Oculus.Interaction.Input.HandRef.GetFingerIsHighConfidence (HandFinger finger)
Implements Oculus.Interaction.Input.IHand.
Definition at line 116 of file HandRef.cs.
        {
            return Hand.GetFingerIsHighConfidence(finger);
        }
GetFingerIsPinching()
bool Oculus.Interaction.Input.HandRef.GetFingerIsPinching (HandFinger finger)
Implements Oculus.Interaction.Input.IHand.
Definition at line 71 of file HandRef.cs.
        {
            return Hand.GetFingerIsPinching(finger);
        }
GetFingerPinchStrength()
float Oculus.Interaction.Input.HandRef.GetFingerPinchStrength (HandFinger finger)
Implements Oculus.Interaction.Input.IHand.
Definition at line 121 of file HandRef.cs.
        {
            return Hand.GetFingerPinchStrength(finger);
        }
GetIndexFingerIsPinching()
bool Oculus.Interaction.Input.HandRef.GetIndexFingerIsPinching ()
Implements Oculus.Interaction.Input.IHand.
Definition at line 76 of file HandRef.cs.
        {
            return Hand.GetIndexFingerIsPinching();
        }
GetJointPose()
bool Oculus.Interaction.Input.HandRef.GetJointPose (HandJointId handJointId, out Pose pose)
Attempts to calculate the pose of the requested hand joint, in world space. Returns false if the skeleton is not yet initialized, or there is no valid tracking data.
Implements Oculus.Interaction.Input.IHand.
Definition at line 86 of file HandRef.cs.
        {
            return Hand.GetJointPose(handJointId, out pose);
        }
References Oculus.Interaction.Input.Hand.GetJointPose().
GetJointPoseFromWrist()
bool Oculus.Interaction.Input.HandRef.GetJointPoseFromWrist (HandJointId handJointId, out Pose pose)
Attempts to calculate the pose of the requested hand joint relative to the wrist. Returns false if the skeleton is not yet initialized, or there is no valid tracking data.
Implements Oculus.Interaction.Input.IHand.
Definition at line 101 of file HandRef.cs.
        {
            return Hand.GetJointPoseFromWrist(handJointId, out pose);
        }
References Oculus.Interaction.Input.Hand.GetJointPoseFromWrist().
GetJointPoseLocal()
bool Oculus.Interaction.Input.HandRef.GetJointPoseLocal (HandJointId handJointId, out Pose pose)
Attempts to calculate the pose of the requested hand joint, in local space. Returns false if the skeleton is not yet initialized, or there is no valid tracking data.
Implements Oculus.Interaction.Input.IHand.
Definition at line 91 of file HandRef.cs.
        {
            return Hand.GetJointPoseLocal(handJointId, out pose);
        }
References Oculus.Interaction.Input.Hand.GetJointPoseLocal().
GetJointPosesFromWrist()
bool Oculus.Interaction.Input.HandRef.GetJointPosesFromWrist (out ReadOnlyHandJointPoses jointPosesFromWrist)
Returns an array containing the pose of each joint relative to the wrist. The poses do not have the root pose applied, nor the hand scale. It is in the same coordinate system as the hand skeleton.
Parameters
jointPosesFromWrist The array with the joint poses from the wrist. It will be empty if no poses where found
Returns
True if the poses collection was correctly populated. False otherwise.
Implements Oculus.Interaction.Input.IHand.
Definition at line 106 of file HandRef.cs.
        {
            return Hand.GetJointPosesFromWrist(out jointPosesFromWrist);
        }
References Oculus.Interaction.Input.Hand.GetJointPosesFromWrist().
GetJointPosesLocal()
bool Oculus.Interaction.Input.HandRef.GetJointPosesLocal (out ReadOnlyHandJointPoses localJointPoses)
Returns an array containing the local pose of each joint. The poses do not have the root pose applied, nor the hand scale. It is in the same coordinate system as the hand skeleton.
Parameters
localJointPoses The array with the local joint poses. It will be empty if no poses where found
Returns
True if the poses collection was correctly populated. False otherwise.
Implements Oculus.Interaction.Input.IHand.
Definition at line 96 of file HandRef.cs.
        {
            return Hand.GetJointPosesLocal(out jointPosesLocal);
        }
References Oculus.Interaction.Input.Hand.GetJointPosesLocal().
GetPalmPoseLocal()
bool Oculus.Interaction.Input.HandRef.GetPalmPoseLocal (out Pose pose)
Obtains palm pose in local space.
Parameters
pose The pose to populate
Returns
True if pose was obtained.
Implements Oculus.Interaction.Input.IHand.
Definition at line 111 of file HandRef.cs.
        {
            return Hand.GetPalmPoseLocal(out pose);
        }
References Oculus.Interaction.Input.Hand.GetPalmPoseLocal().
GetPointerPose()
bool Oculus.Interaction.Input.HandRef.GetPointerPose (out Pose pose)
Attempts to calculate the pose that can be used as a root for raycasting, in world space Returns false if there is no valid tracking data.
Implements Oculus.Interaction.Input.IHand.
Definition at line 81 of file HandRef.cs.
        {
            return Hand.GetPointerPose(out pose);
        }
References Oculus.Interaction.Input.Hand.GetPointerPose().
GetRootPose()
bool Oculus.Interaction.Input.HandRef.GetRootPose (out Pose pose)
Gets the root pose of the wrist, in world space. Will return true if a pose was available; false otherwise. Confidence level of the pose is exposed via IsHighConfidence.
Implements Oculus.Interaction.Input.IHand.
Definition at line 126 of file HandRef.cs.
        {
            return Hand.GetRootPose(out pose);
        }
References Oculus.Interaction.Input.Hand.GetRootPose().
InjectAllHandRef()
void Oculus.Interaction.Input.HandRef.InjectAllHandRef (IHand hand)
Definition at line 132 of file HandRef.cs.
        {
            InjectHand(hand);
        }
InjectHand()
void Oculus.Interaction.Input.HandRef.InjectHand (IHand hand)
Definition at line 137 of file HandRef.cs.
        {
            _hand = hand as UnityEngine.Object;
            Hand = hand;
        }
Start()
virtual void Oculus.Interaction.Input.HandRef.Start () protected virtual
Definition at line 66 of file HandRef.cs.
        {
            this.AssertField(Hand, nameof(Hand));
        }
Member Data Documentation
_hand
UnityEngine.Object Oculus.Interaction.Input.HandRef._hand private
Definition at line 33 of file HandRef.cs.
Property Documentation
Active
bool Oculus.Interaction.Input.HandRef.Active get
Implements Oculus.Interaction.IActiveState.
Definition at line 59 of file HandRef.cs.
CurrentDataVersion
int Oculus.Interaction.Input.HandRef.CurrentDataVersion get
Incremented every time the source tracking or state data changes.
Implements Oculus.Interaction.Input.IHand.
Definition at line 51 of file HandRef.cs.
Hand
IHand Oculus.Interaction.Input.HandRef.Hand get private set
Definition at line 35 of file HandRef.cs.
{ get; private set; }
Handedness
Handedness Oculus.Interaction.Input.HandRef.Handedness get
Implements Oculus.Interaction.Input.IHand.
Definition at line 37 of file HandRef.cs.
IsConnected
bool Oculus.Interaction.Input.HandRef.IsConnected get
Implements Oculus.Interaction.Input.IHand.
Definition at line 39 of file HandRef.cs.
IsDominantHand
bool Oculus.Interaction.Input.HandRef.IsDominantHand get
Implements Oculus.Interaction.Input.IHand.
Definition at line 43 of file HandRef.cs.
IsHighConfidence
bool Oculus.Interaction.Input.HandRef.IsHighConfidence get
The hand is connected and tracked, and the root pose's tracking data is marked as high confidence. If this is true, then it implies that IsConnected and IsRootPoseValid are also true, so they don't need to be checked in addition to this.
Implements Oculus.Interaction.Input.IHand.
Definition at line 41 of file HandRef.cs.
IsPointerPoseValid
bool Oculus.Interaction.Input.HandRef.IsPointerPoseValid get
Will return true if a pointer pose is available, that can be retrieved via GetPointerPose
Implements Oculus.Interaction.Input.IHand.
Definition at line 47 of file HandRef.cs.
IsTrackedDataValid
bool Oculus.Interaction.Input.HandRef.IsTrackedDataValid get
True if the hand is currently tracked, thus tracking poses are available for the hand root and finger joints. This property does not indicate pointing pose validity, which has its own property: IsPointerPoseValid.
Implements Oculus.Interaction.Input.IHand.
Definition at line 49 of file HandRef.cs.
Scale
float Oculus.Interaction.Input.HandRef.Scale get
Implements Oculus.Interaction.Input.IHand.
Definition at line 45 of file HandRef.cs.
WhenHandUpdated
Action Oculus.Interaction.Input.HandRef.WhenHandUpdated add remove
Implements Oculus.Interaction.Input.IHand.
Definition at line 53 of file HandRef.cs.
        {
            add => Hand.WhenHandUpdated += value;
            remove => Hand.WhenHandUpdated -= value;
        }
The documentation for this class was generated from the following file:
Assets/Oculus/Interaction/Runtime/Scripts/Input/Hands/HandRef.cs