VR_Test: Oculus.Interaction.SurfaceUtils Class Reference
Oculus.Interaction.SurfaceUtils Class Reference
Tools for working Surfaces on Interactables.
Static Public Member Functions
static float ComputeDistanceAbove (ISurfacePatch surfacePatch, Vector3 point, float radius)
The distance above a surface along the closest normal. Returns 0 for where the sphere touches the surface along the normal.
static float ComputeTangentDistance (ISurfacePatch surfacePatch, Vector3 point, float radius)
The distance to a surface along the tangent.
static float ComputeDepth (ISurfacePatch surfacePatch, Vector3 point, float radius)
The distance below a surface along the closest normal. always positive.
static float ComputeDistanceFrom (ISurfacePatch surfacePatch, Vector3 point, float radius)
The distance from the closest point as computed by the proximity field and surface. Returns the distance to the point without taking into account the surface normal.
Detailed Description
Tools for working Surfaces on Interactables.
Definition at line 29 of file SurfaceUtils.cs.
Member Function Documentation
ComputeDepth()
static float Oculus.Interaction.SurfaceUtils.ComputeDepth (ISurfacePatch surfacePatch, Vector3 point, float radius) static
The distance below a surface along the closest normal. always positive.
Parameters
interactable the pokeinteractable surface to test
point the origin point to compute distance from the surface
radius the radius of the sphere positioned at the origin point
Definition at line 68 of file SurfaceUtils.cs.
        {
            return Mathf.Max(0f, -ComputeDistanceAbove(surfacePatch, point, radius));
        }
References Oculus.Interaction.SurfaceUtils.ComputeDistanceAbove().
ComputeDistanceAbove()
static float Oculus.Interaction.SurfaceUtils.ComputeDistanceAbove (ISurfacePatch surfacePatch, Vector3 point, float radius) static
The distance above a surface along the closest normal. Returns 0 for where the sphere touches the surface along the normal.
Parameters
interactable The PokeInteractable surface to test
point The origin point to compute distance from the surface
radius The radius of the sphere positioned at the origin point
Definition at line 38 of file SurfaceUtils.cs.
        {
            surfacePatch.BackingSurface.ClosestSurfacePoint(point, out SurfaceHit hit);
            Vector3 surfaceToPoint = point - hit.Point;
            return Vector3.Dot(surfaceToPoint, hit.Normal) - radius;
        }
References Oculus.Interaction.Surfaces.ISurfacePatch.BackingSurface, and Oculus.Interaction.Surfaces.ISurface.ClosestSurfacePoint().
ComputeDistanceFrom()
static float Oculus.Interaction.SurfaceUtils.ComputeDistanceFrom (ISurfacePatch surfacePatch, Vector3 point, float radius) static
The distance from the closest point as computed by the proximity field and surface. Returns the distance to the point without taking into account the surface normal.
Parameters
interactable the pokeinteractable surface to test
point the origin point to compute distance from the surface
radius the radius of the sphere positioned at the origin point
Definition at line 80 of file SurfaceUtils.cs.
        {
            surfacePatch.ClosestSurfacePoint(point, out SurfaceHit hit);
            Vector3 surfaceToPoint = point - hit.Point;
            return surfaceToPoint.magnitude - radius;
        }
References Oculus.Interaction.Surfaces.ISurface.ClosestSurfacePoint().
ComputeTangentDistance()
static float Oculus.Interaction.SurfaceUtils.ComputeTangentDistance (ISurfacePatch surfacePatch, Vector3 point, float radius) static
The distance to a surface along the tangent.
Parameters
interactable The PokeInteractable surface to test
point The origin point to compute distance from the surface
radius The radius of the sphere positioned at the origin point
Definition at line 51 of file SurfaceUtils.cs.
        {
            surfacePatch.ClosestSurfacePoint(point, out SurfaceHit patchHit);
            surfacePatch.BackingSurface.ClosestSurfacePoint(point, out SurfaceHit backingHit);
            Vector3 proximityToPoint = point - patchHit.Point;
            Vector3 projOnNormal = Vector3.Dot(proximityToPoint, backingHit.Normal) *
                backingHit.Normal;
            Vector3 lateralVec = proximityToPoint - projOnNormal;
            return lateralVec.magnitude - radius;
        }
References Oculus.Interaction.Surfaces.ISurfacePatch.BackingSurface, and Oculus.Interaction.Surfaces.ISurface.ClosestSurfacePoint().
The documentation for this class was generated from the following file:
Assets/Oculus/Interaction/Runtime/Scripts/Utils/SurfaceUtils.cs