VR_Test: TeleportTargetHandler Class Reference
TeleportTargetHandler Class Reference abstract
The TeleportTargetHandler's main purpose is to determine when the current aim target is valid and to update the teleport destination as required by the design. This allows specialized versions that can simply update the destination to any arbitrary location, or update only when a teleport node is being pointed at, or anything else that fits the design for limiting when & where a teleport is valid.
Public Member Functions
virtual ? Vector3 ConsiderDestination (Vector3 location)
Adjust the provided located to account for character height and perform any checks that might invalidate the target position of the character controller, such as collision with scene geometry or other actors.
Public Attributes
LayerMask AimCollisionLayerMask
This bitmask controls which game object layers will be included in the targeting collision tests.
Protected Member Functions
override void AddEventHandlers ()
Derived classes that need to use event handlers need to override this method and call the base class to ensure all event handlers are added as intended.
override void RemoveEventHandlers ()
Derived classes that need to use event handlers need to override this method and call the base class to ensure all event handlers are removed as intended.
virtual void ResetAimData ()
bool ConsiderTeleport (Vector3 start, ref Vector3 end)
This method will be called while the LocmotionTeleport component is in the aiming state, once for each line segment that the targeting beam requires. The function should return true whenever an actual target location has been selected.
Protected Member Functions inherited from TeleportSupport
virtual void OnEnable ()
OnEnable is virtual so that derived classes can set up references to objects before AddEventHandlers is called, as is required by TeleportSupport derivations.
virtual void OnDisable ()
Protected Attributes
readonly LocomotionTeleport.AimData AimData = new LocomotionTeleport.AimData()
Private Member Functions
IEnumerator TargetAimCoroutine ()
This coroutine is active while the teleport system is in the aiming state.
Private Attributes
readonly Action _startAimAction
readonly List< Vector3 > _aimPoints = new List<Vector3>()
Static Private Attributes
const float ERROR_MARGIN = 0.1f
Additional Inherited Members
Properties inherited from TeleportSupport
LocomotionTeleport LocomotionTeleport [get, private set]
Detailed Description
The TeleportTargetHandler's main purpose is to determine when the current aim target is valid and to update the teleport destination as required by the design. This allows specialized versions that can simply update the destination to any arbitrary location, or update only when a teleport node is being pointed at, or anything else that fits the design for limiting when & where a teleport is valid.
Definition at line 25 of file TeleportTargetHandler.cs.
Constructor & Destructor Documentation
TeleportTargetHandler()
TeleportTargetHandler.TeleportTargetHandler () protected
Definition at line 36 of file TeleportTargetHandler.cs.
    {
        _startAimAction = () => { StartCoroutine(TargetAimCoroutine()); };
    }
Member Function Documentation
AddEventHandlers()
override void TeleportTargetHandler.AddEventHandlers () protected virtual
Derived classes that need to use event handlers need to override this method and call the base class to ensure all event handlers are added as intended.
Reimplemented from TeleportSupport.
Definition at line 41 of file TeleportTargetHandler.cs.
    {
        base.AddEventHandlers();
        LocomotionTeleport.EnterStateAim += _startAimAction;
    }
ConsiderDestination()
virtual ? Vector3 TeleportTargetHandler.ConsiderDestination (Vector3 location) virtual
Adjust the provided located to account for character height and perform any checks that might invalidate the target position of the character controller, such as collision with scene geometry or other actors.
Parameters
location
Returns
Reimplemented in TeleportTargetHandlerNavMesh.
Definition at line 126 of file TeleportTargetHandler.cs.
    {
        var character = LocomotionTeleport.LocomotionController.CharacterController;
        var radius = character.radius - ERROR_MARGIN;
        var start = location;
        start.y += radius + ERROR_MARGIN;
        var end = start;
        end.y += character.height - ERROR_MARGIN;
        var result = Physics.CheckCapsule(start, end, radius,
            AimCollisionLayerMask, QueryTriggerInteraction.Ignore);
        if (result)
        {
            return null;
        }
        return location;
    }
References AimCollisionLayerMask, and LocomotionTeleport.LocomotionController.
ConsiderTeleport()
bool TeleportTargetHandler.ConsiderTeleport (Vector3 start, ref Vector3 end) abstract protected
This method will be called while the LocmotionTeleport component is in the aiming state, once for each line segment that the targeting beam requires. The function should return true whenever an actual target location has been selected.
Parameters
start
end
RemoveEventHandlers()
override void TeleportTargetHandler.RemoveEventHandlers () protected virtual
Derived classes that need to use event handlers need to override this method and call the base class to ensure all event handlers are removed as intended.
Reimplemented from TeleportSupport.
Definition at line 47 of file TeleportTargetHandler.cs.
    {
        base.RemoveEventHandlers();
        LocomotionTeleport.EnterStateAim -= _startAimAction;
    }
ResetAimData()
virtual void TeleportTargetHandler.ResetAimData () protected virtual
When a parabolic or other aiming method that consists of many line segments is being used, ConsiderTeleport will be called once for each segment so if there is expensive work that can be cached in advance, override the ResetAimData method to prepare that data.
Definition at line 103 of file TeleportTargetHandler.cs.
    {
        AimData.Reset();
    }
TargetAimCoroutine()
IEnumerator TeleportTargetHandler.TargetAimCoroutine () private
This coroutine is active while the teleport system is in the aiming state.
Returns
Definition at line 59 of file TeleportTargetHandler.cs.
    {
        // While the teleport system is in the aim state, perform the aim logic and consider teleporting.
        while (LocomotionTeleport.CurrentState == LocomotionTeleport.States.Aim)
        {
            // With each targeting test, we need to reset the AimData to clear the point list and reset flags.
            ResetAimData();
            // Start the testing with the character's current position to the aiming origin to ensure they
            // haven't just stuck their hand through something that should have prevented movement.
            //
            // The first test won't be added to the aim data results because the visual effects should be from
            // the aiming origin.
            var current = LocomotionTeleport.transform.position;
            // Enumerate through all the line segments provided by the aim handler, checking for a valid target on each segment,
            // stopping at the first valid target or when the enumerable runs out of line segments.
            _aimPoints.Clear();
            LocomotionTeleport.AimHandler.GetPoints(_aimPoints);
            for (int i = 0; i < _aimPoints.Count; i++)
            {
                var adjustedPoint = _aimPoints[i];
                AimData.TargetValid = ConsiderTeleport(current, ref adjustedPoint);
                AimData.Points.Add(adjustedPoint);
                if (AimData.TargetValid)
                {
                    AimData.Destination = ConsiderDestination(adjustedPoint);
                    AimData.TargetValid = AimData.Destination.HasValue;
                    break;
                }
                current = _aimPoints[i];
            }
            LocomotionTeleport.OnUpdateAimData(AimData);
            yield return null;
        }
    }
References LocomotionTeleport.AimHandler, ConsiderDestination(), ConsiderTeleport(), LocomotionTeleport.CurrentState, TeleportAimHandler.GetPoints(), LocomotionTeleport.OnUpdateAimData(), and ResetAimData().
Member Data Documentation
_aimPoints
readonly List<Vector3> TeleportTargetHandler._aimPoints = new List<Vector3>() private
Definition at line 53 of file TeleportTargetHandler.cs.
_startAimAction
readonly Action TeleportTargetHandler._startAimAction private
Definition at line 34 of file TeleportTargetHandler.cs.
AimCollisionLayerMask
LayerMask TeleportTargetHandler.AimCollisionLayerMask
This bitmask controls which game object layers will be included in the targeting collision tests.
Definition at line 31 of file TeleportTargetHandler.cs.
AimData
readonly LocomotionTeleport.AimData TeleportTargetHandler.AimData = new LocomotionTeleport.AimData() protected
Definition at line 33 of file TeleportTargetHandler.cs.
ERROR_MARGIN
const float TeleportTargetHandler.ERROR_MARGIN = 0.1f static private
Definition at line 117 of file TeleportTargetHandler.cs.
The documentation for this class was generated from the following file:
Assets/Oculus/SampleFramework/Core/Locomotion/Scripts/TeleportTargetHandler.cs