VR_Test: Meta.WitAi.TTS.Utilities.TTSSpeaker Class Reference
Meta.WitAi.TTS.Utilities.TTSSpeaker Class Reference
Classes
struct TTSSpeakerRequestData
Public Member Functions
virtual List< string > GetFinalText (string textToSpeak)
Gets final text following prepending/appending & any special formatting.
virtual List< string > GetFinalTextFormatted (string format, params string[] textsToSpeak)
Obtain final text list from format & text list.
string GetFormattedText (string format, params string[] textsToSpeak)
Formats text using an initial format string parameter and additional text items to be inserted into the format.
void Speak (string textToSpeak, TTSDiskCacheSettings diskCacheSettings, TTSSpeakerClipEvents playbackEvents)
Load a tts clip using the specified text, disk cache settings & playback events. Cancels all previous clips when loaded & then plays.
void Speak (string textToSpeak, TTSSpeakerClipEvents playbackEvents)
Load a tts clip using the specified text & playback events. Cancels all previous clips when loaded & then plays.
void Speak (string textToSpeak, TTSDiskCacheSettings diskCacheSettings)
Load a tts clip using the specified text & disk cache settings. Cancels all previous clips when loaded & then plays.
void Speak (string textToSpeak)
Load a tts clip using the specified text. Cancels all previous clips when loaded & then plays.
void SpeakFormat (string format, params string[] textsToSpeak)
Loads a formated phrase to be spoken. Cancels all previous clips when loaded & then plays.
IEnumerator SpeakAsync (string textToSpeak, TTSDiskCacheSettings diskCacheSettings, TTSSpeakerClipEvents playbackEvents)
Load a tts clip using the specified text, disk cache settings & playback events and then waits for the file to load & play. Cancels all previous clips when loaded & then plays.
IEnumerator SpeakAsync (string textToSpeak, TTSSpeakerClipEvents playbackEvents)
Load a tts clip using the specified text & playback events and then waits for the file to load & play. Cancels all previous clips when loaded & then plays.
IEnumerator SpeakAsync (string textToSpeak, TTSDiskCacheSettings diskCacheSettings)
Load a tts clip using the specified text & disk cache settings and then waits for the file to load & play. Cancels all previous clips when loaded & then plays.
IEnumerator SpeakAsync (string textToSpeak)
Load a tts clip using the specified text and then waits for the file to load & play. Cancels all previous clips when loaded & then plays.
void SpeakQueued (string textToSpeak, TTSDiskCacheSettings diskCacheSettings, TTSSpeakerClipEvents playbackEvents)
Load a tts clip using the specified text, disk cache settings & playback events. Adds clip to playback queue and will speak once queue has completed all playback.
void SpeakQueued (string textToSpeak, TTSSpeakerClipEvents playbackEvents)
Load a tts clip using the specified text & playback events. Adds clip to playback queue and will speak once queue has completed all playback.
void SpeakQueued (string textToSpeak, TTSDiskCacheSettings diskCacheSettings)
Load a tts clip using the specified text & disk cache settings events. Adds clip to playback queue and will speak once queue has completed all playback.
void SpeakQueued (string textToSpeak)
Load a tts clip using the specified text. Adds clip to playback queue and will speak once queue has completed all playback.
void SpeakFormatQueued (string format, params string[] textsToSpeak)
Loads a formated phrase to be spoken. Adds clip to playback queue and will speak once queue has completed all playback.
IEnumerator SpeakQueuedAsync (string[] textsToSpeak, TTSDiskCacheSettings diskCacheSettings, TTSSpeakerClipEvents playbackEvents)
Load a tts clip using the specified text phrases, disk cache settings & playback events and then waits for the files to load & play. Adds clip to playback queue and will speak once queue has completed all playback.
IEnumerator SpeakQueuedAsync (string[] textsToSpeak, TTSSpeakerClipEvents playbackEvents)
Load a tts clip using the specified text phrases & playback events and then waits for the files to load & play. Adds clip to playback queue and will speak once queue has completed all playback.
IEnumerator SpeakQueuedAsync (string[] textsToSpeak, TTSDiskCacheSettings diskCacheSettings)
Load a tts clip using the specified text phrases & disk cache settings and then waits for the files to load & play. Adds clip to playback queue and will speak once queue has completed all playback.
IEnumerator SpeakQueuedAsync (string[] textsToSpeak)
Load a tts clip using the specified text phrases and then waits for the files to load & play. Adds clip to playback queue and will speak once queue has completed all playback.
virtual void Stop (string textToSpeak, bool allInstances=false)
Stop load & playback of a specific clip.
virtual void Stop (TTSClipData clipData, bool allInstances=false)
Stop load & playback of a specific clip.
virtual void StopLoading ()
Abort loading of all items in the load queue.
virtual void StopSpeaking ()
Stop playback of currently played audio clip.
virtual void Stop ()
Stops loading & playback immediately.
void SetVoiceOverride (TTSVoiceSettings overrideVoiceSettings)
Set a voice override for future requests.
void ClearVoiceOverride ()
Clears the current voice override.
void Speak (string textToSpeak, TTSVoiceSettings overrideVoiceSettings, TTSDiskCacheSettings diskCacheSettings, TTSSpeakerClipEvents playbackEvents)
Load a tts clip using the specified response node, disk cache settings & playback events. Cancels all previous clips when loaded & then plays.
bool Speak (WitResponseNode responseNode, TTSDiskCacheSettings diskCacheSettings, TTSSpeakerClipEvents playbackEvents)
Load a tts clip using the specified response node, disk cache settings & playback events. Cancels all previous clips when loaded & then plays.
bool Speak (WitResponseNode responseNode, TTSDiskCacheSettings diskCacheSettings)
Load a tts clip using the specified response node & disk cache settings Cancels all previous clips when loaded & then plays.
bool Speak (WitResponseNode responseNode, TTSSpeakerClipEvents playbackEvents)
Load a tts clip using the specified response node & playback events Cancels all previous clips when loaded & then plays.
bool Speak (WitResponseNode responseNode)
Load a tts clip using the specified response node & playback events Cancels all previous clips when loaded & then plays.
IEnumerator SpeakAsync (string textToSpeak, TTSVoiceSettings overrideVoiceSettings, TTSDiskCacheSettings diskCacheSettings, TTSSpeakerClipEvents playbackEvents)
Load a tts clip using the specified text, disk cache settings & playback events and then waits for the file to load & play. Cancels all previous clips when loaded & then plays.
IEnumerator SpeakAsync (WitResponseNode responseNode, TTSDiskCacheSettings diskCacheSettings, TTSSpeakerClipEvents playbackEvents)
Load a tts clip using the specified text, disk cache settings & playback events and then waits for the file to load & play. Cancels all previous clips when loaded & then plays.
IEnumerator SpeakAsync (WitResponseNode responseNode, TTSSpeakerClipEvents playbackEvents)
Load a tts clip using the specified text & playback events and then waits for the file to load & play. Cancels all previous clips when loaded & then plays.
IEnumerator SpeakAsync (WitResponseNode responseNode, TTSDiskCacheSettings diskCacheSettings)
Load a tts clip using the specified text & disk cache settings and then waits for the file to load & play. Cancels all previous clips when loaded & then plays.
void SpeakQueued (string textToSpeak, TTSVoiceSettings overrideVoiceSettings, TTSDiskCacheSettings diskCacheSettings, TTSSpeakerClipEvents playbackEvents)
Load a tts clip using the specified response node, disk cache settings & playback events. Adds clip to playback queue and will speak once queue has completed all playback.
bool SpeakQueued (WitResponseNode responseNode, TTSDiskCacheSettings diskCacheSettings, TTSSpeakerClipEvents playbackEvents)
Load a tts clip using the specified text, disk cache settings & playback events. Adds clip to playback queue and will speak once queue has completed all playback.
bool SpeakQueued (WitResponseNode responseNode, TTSSpeakerClipEvents playbackEvents)
Load a tts clip using the specified text & playback events. Adds clip to playback queue and will speak once queue has completed all playback.
bool SpeakQueued (WitResponseNode responseNode, TTSDiskCacheSettings diskCacheSettings)
Load a tts clip using the specified text & disk cache settings events. Adds clip to playback queue and will speak once queue has completed all playback.
bool SpeakQueued (WitResponseNode responseNode)
Load a tts clip using the specified text. Adds clip to playback queue and will speak once queue has completed all playback.
IEnumerator SpeakQueuedAsync (string[] textsToSpeak, TTSVoiceSettings overrideVoiceSettings, TTSDiskCacheSettings diskCacheSettings, TTSSpeakerClipEvents playbackEvents)
Load a tts clip using the specified text phrases, disk cache settings & playback events and then waits for the files to load & play. Adds clip to playback queue and will speak once queue has completed all playback.
IEnumerator SpeakQueuedAsync (WitResponseNode responseNode, TTSDiskCacheSettings diskCacheSettings, TTSSpeakerClipEvents playbackEvents)
Load a tts clip using the specified text phrases, disk cache settings & playback events and then waits for the files to load & play. Adds clip to playback queue and will speak once queue has completed all playback.
IEnumerator SpeakQueuedAsync (WitResponseNode responseNode, TTSSpeakerClipEvents playbackEvents)
Load a tts clip using the specified text phrases & playback events and then waits for the files to load & play. Adds clip to playback queue and will speak once queue has completed all playback.
IEnumerator SpeakQueuedAsync (WitResponseNode responseNode, TTSDiskCacheSettings diskCacheSettings)
Load a tts clip using the specified text phrases & disk cache settings and then waits for the files to load & play. Adds clip to playback queue and will speak once queue has completed all playback.
IEnumerator SpeakQueuedAsync (WitResponseNode responseNode)
Load a tts clip using the specified text phrases and then waits for the files to load & play. Adds clip to playback queue and will speak once queue has completed all playback.
void Pause ()
Pause any current or future loaded audio playback.
void Resume ()
Resume playback for current and future audio clips.
Public Attributes
string PrependedText
string AppendedText
string presetVoiceID
TTSWitVoiceSettings customWitVoiceSettings
Protected Member Functions
virtual void Start ()
virtual void RefreshProcessors ()
virtual void OnDestroy ()
virtual void OnEnable ()
virtual void OnDisable ()
virtual void HandleClipUnload (TTSClipData clipData)
virtual void HandleClipUpdate (TTSClipData clipData)
bool IsClipRequestActive (TTSSpeakerRequestData requestData)
bool IsClipRequestLoading (TTSSpeakerRequestData requestData)
bool IsClipRequestSpeaking (TTSSpeakerRequestData requestData)
IEnumerator WaitForCompletion (List< TTSSpeakerRequestData > requestData)
virtual bool IsPlaybackComplete (float elapsedTime)
virtual void HandlePlaybackComplete (bool stopped)
virtual void SetPause (bool toPaused)
virtual void Log (string comment)
virtual void OnPlaybackQueueBegin ()
virtual void OnPlaybackQueueComplete ()
virtual void LogRequestData (string comment, TTSSpeakerRequestData requestData, bool warning=false)
virtual void OnInit (TTSSpeakerRequestData requestData)
virtual void OnLoadBegin (TTSSpeakerRequestData requestData)
virtual void OnLoadAborted (TTSSpeakerRequestData requestData)
virtual void OnLoadFailed (TTSSpeakerRequestData requestData, string error)
virtual void OnLoadSuccess (TTSSpeakerRequestData requestData)
virtual void OnPlaybackReady (TTSSpeakerRequestData requestData)
virtual void OnPlaybackStart (TTSSpeakerRequestData requestData)
virtual void OnPlaybackCancelled (TTSSpeakerRequestData requestData, string reason)
virtual void OnPlaybackClipUpdated (TTSSpeakerRequestData requestData)
virtual void OnPlaybackComplete (TTSSpeakerRequestData requestData)
virtual void OnComplete (TTSSpeakerRequestData requestData)
Protected Attributes
TTSSpeakerRequestData _speakingRequest
Properties
TTSSpeakerEvents Events [get]
VoiceSpeechEvents SpeechEvents [get]
TTSService TTSService [get]
TTSVoiceSettings VoiceSettings [get]
The voice settings to be used for this TTSSpeaker.
virtual string LogCategory [get]
bool IsSpeaking [get]
Whether a clip is currently playing for this speaker.
TTSClipData SpeakingClip [get]
The data for the currently playing clip.
bool IsLoading [get]
Whether there are any clips in the loading queue.
bool IsPreparing [get]
Whether any queued clips are still not ready for playback.
List< TTSClipData > QueuedClips [get]
bool IsActive [get]
Whether the speaker currently has currently speaking clip or a playback queue.
IAudioPlayer AudioPlayer [get]
The script used to perform audio playback of IAudioClipStreams.
AudioSource AudioSource [get]
bool IsPaused [get, private set]
Whether playback is currently paused or not.
Properties inherited from Meta.WitAi.Speech.ISpeechEventProvider
Private Member Functions
TTSSpeakerRequestData GetQueuedRequest (TTSClipData clipData)
bool QueueContainsClip (TTSClipData clipData)
void RefreshQueueEvents ()
List< TTSSpeakerRequestData > Speak (string textToSpeak, TTSDiskCacheSettings diskCacheSettings, TTSSpeakerClipEvents playbackEvents, bool addToQueue)
Loads a tts clip & handles playback.
bool DecodeResponse (WitResponseNode responseNode, out string textToSpeak, out TTSVoiceSettings voiceSettings)
Decode a response node into text to be spoken or a specific voice setting Example Data: { "q": "Text to be spoken" "voice": "Charlie }.
TTSSpeakerRequestData HandleLoad (string textToSpeak, TTSVoiceSettings voiceSettings, TTSDiskCacheSettings diskCacheSettings, TTSSpeakerClipEvents playbackEvents, bool addToQueue)
void HandleLoadComplete (TTSSpeakerRequestData requestData, string error)
void RefreshPlayback ()
Refreshes playback queue to play next available clip if possible.
IEnumerator WaitForPlaybackComplete ()
void HandleUnload (TTSClipData clipData, string error)
void HandleUnload (TTSSpeakerRequestData requestData, string error)
void HandleUnload (Func< TTSSpeakerRequestData, bool > shouldKeep, string error)
Private Attributes
TTSSpeakerEvents _events = new TTSSpeakerEvents()
TTSService _ttsService
TTSVoiceSettings _overrideVoiceSettings
Queue< TTSSpeakerRequestData > _queuedRequests = new Queue<TTSSpeakerRequestData>()
bool _hasQueue = false
bool _willHaveQueue = false
ISpeakerTextPreprocessor[] _textPreprocessors
ISpeakerTextPostprocessor[] _textPostprocessors
IAudioPlayer _audioPlayer
Coroutine _waitForCompletion
Detailed Description
Definition at line 25 of file TTSSpeaker.cs.
Member Function Documentation
DecodeResponse()
bool Meta.WitAi.TTS.Utilities.TTSSpeaker.DecodeResponse (WitResponseNode responseNode, out string textToSpeak, out TTSVoiceSettings voiceSettings) private
Decode a response node into text to be spoken or a specific voice setting Example Data: { "q": "Text to be spoken" "voice": "Charlie }.
Parameters
responseNode Parsed data that includes text to be spoken & voice settings
textToSpeak The text to be spoken output
voiceSettings The output for voice settings
Returns
True if decode was successful
Definition at line 839 of file TTSSpeaker.cs.
        {
            // Wit settings
            if (TTSWitVoiceSettings.CanDecode(responseNode))
            {
                TTSWitVoiceSettings witVoice = JsonConvert.DeserializeObject<TTSWitVoiceSettings>(responseNode);
                if (witVoice != null)
                {
                    textToSpeak = responseNode[WitConstants.ENDPOINT_TTS_PARAM];
                    voiceSettings = witVoice;
                    voiceSettings.SettingsId = "OVERRIDE";
                    return true;
                }
            }
            // Default application
            textToSpeak = null;
            voiceSettings = null;
            return false;
        }
References Meta.WitAi.TTS.Integrations.TTSWitVoiceSettings.CanDecode().
GetFinalText()
virtual List< string > Meta.WitAi.TTS.Utilities.TTSSpeaker.GetFinalText (string textToSpeak) virtual
Gets final text following prepending/appending & any special formatting.
Parameters
textToSpeak The base text to be spoken
Returns
Returns an array of split texts to be spoken
Definition at line 394 of file TTSSpeaker.cs.
        {
            // Get processors
            RefreshProcessors();
            // Get results
            List<string> phrases = new List<string>();
            phrases.Add(textToSpeak);
            // Pre-processor
            if (_textPreprocessors != null)
            {
                foreach (var preprocessor in _textPreprocessors)
                {
                    preprocessor.OnPreprocessTTS(this, phrases);
                }
            }
            // Add prepend & appended text to each item
            for (int i = 0; i < phrases.Count; i++)
            {
                string phrase = phrases[i];
                phrase = $"{PrependedText}{phrase}{AppendedText}".Trim();
                phrases[i] = phrase;
            }
            // Post-processors
            if (_textPostprocessors != null)
            {
                foreach (var postprocessor in _textPostprocessors)
                {
                    postprocessor.OnPostprocessTTS(this, phrases);
                }
            }
            // Return all text items
            return phrases;
        }
GetFinalTextFormatted()
virtual List< string > Meta.WitAi.TTS.Utilities.TTSSpeaker.GetFinalTextFormatted (string format, params string[] textsToSpeak) virtual
Obtain final text list from format & text list.
Parameters
format The format to be used
textsToSpeak The array of strings to be inserted into the format
Returns
Returns a list of formatted texts
Definition at line 438 of file TTSSpeaker.cs.
        {
            return GetFinalText(GetFormattedText(format, textsToSpeak));
        }
References Meta.WitAi.TTS.Utilities.TTSSpeaker.GetFinalText(), and Meta.WitAi.TTS.Utilities.TTSSpeaker.GetFormattedText().
GetFormattedText()
string Meta.WitAi.TTS.Utilities.TTSSpeaker.GetFormattedText (string format, params string[] textsToSpeak)
Formats text using an initial format string parameter and additional text items to be inserted into the format.
Parameters
format The format to be used
textsToSpeak The array of strings to be inserted into the format
Returns
A formatted text string
Definition at line 449 of file TTSSpeaker.cs.
        {
            if (textsToSpeak != null && !string.IsNullOrEmpty(format))
            {
                object[] objects = new object[textsToSpeak.Length];
                textsToSpeak.CopyTo(objects, 0);
                return string.Format(format, objects);
            }
            return null;
        }
GetQueuedRequest()
TTSSpeakerRequestData Meta.WitAi.TTS.Utilities.TTSSpeaker.GetQueuedRequest (TTSClipData clipData) private
Definition at line 298 of file TTSSpeaker.cs.
        {
            if (_queuedRequests != null)
            {
                foreach (var requestData in _queuedRequests)
                {
                    if (string.Equals(clipData?.clipID, requestData.ClipData?.clipID))
                    {
                        return requestData;
                    }
                }
            }
            return new TTSSpeakerRequestData();
        }
HandleClipUnload()
virtual void Meta.WitAi.TTS.Utilities.TTSSpeaker.HandleClipUnload (TTSClipData clipData) protected virtual
Definition at line 268 of file TTSSpeaker.cs.
        {
            Stop(clipData, true);
        }
HandleClipUpdate()
virtual void Meta.WitAi.TTS.Utilities.TTSSpeaker.HandleClipUpdate (TTSClipData clipData) protected virtual
Definition at line 273 of file TTSSpeaker.cs.
        {
            // Ignore if not speaking clip
            if (!clipData.Equals(SpeakingClip))
            {
                return;
            }
            // Apply new clip data
            _speakingRequest.ClipData = clipData;
            // Get current elapsed samples
            int elapsedSamples = AudioPlayer.ElapsedSamples;
            // Begin playback from elapsed sample
            AudioPlayer.Play(_speakingRequest.ClipData.clipStream, elapsedSamples);
            // Pause if desired
            if (IsPaused)
            {
                AudioPlayer.Pause();
            }
            // Clip updated callback
            OnPlaybackClipUpdated(_speakingRequest);
        }
HandleLoad()
TTSSpeakerRequestData Meta.WitAi.TTS.Utilities.TTSSpeaker.HandleLoad (string textToSpeak, TTSVoiceSettings voiceSettings, TTSDiskCacheSettings diskCacheSettings, TTSSpeakerClipEvents playbackEvents, bool addToQueue) private
Definition at line 1123 of file TTSSpeaker.cs.
        {
            // Generate request data
            TTSSpeakerRequestData requestData = new TTSSpeakerRequestData();
            requestData.StartTime = DateTime.Now;
            requestData.StopQueueOnLoad = !addToQueue;
            requestData.PlaybackEvents = playbackEvents ?? new TTSSpeakerClipEvents();
            // Perform load request (Always waits a frame to ensure callbacks occur first)
            string clipId = TTSService.GetClipID(textToSpeak, voiceSettings);
            requestData.ClipData = TTSService.Load(textToSpeak, clipId, voiceSettings, diskCacheSettings, (clipData, error) => HandleLoadComplete(requestData, error));
            // Ignore without clip
            if (requestData.ClipData == null)
            {
                return requestData;
            }
            // Enqueue
            _queuedRequests.Enqueue(requestData);
            // Initialized, possibly started queue & load began
            OnInit(requestData);
            RefreshQueueEvents();
            OnLoadBegin(requestData);
            // Return data
            return requestData;
        }
HandleLoadComplete()
void Meta.WitAi.TTS.Utilities.TTSSpeaker.HandleLoadComplete (TTSSpeakerRequestData requestData, string error) private
Definition at line 1155 of file TTSSpeaker.cs.
        {
            // Not queued
            if (_queuedRequests != null && !_queuedRequests.Contains(requestData))
            {
                return;
            }
            // Check for other errors
            if (string.IsNullOrEmpty(error) && !string.IsNullOrEmpty(requestData.ClipData.textToSpeak))
            {
                if (requestData.ClipData == null)
                {
                    error = "No TTSClipData found";
                }
                else if (requestData.ClipData.clipStream == null)
                {
                    error = "No AudioClip found";
                }
                else if (requestData.ClipData.loadState == TTSClipLoadState.Error)
                {
                    error = "Error without message";
                }
                else if (requestData.ClipData.loadState == TTSClipLoadState.Unloaded)
                {
                    error = WitConstants.CANCEL_ERROR;
                }
            }
            // Load failed
            if (!string.IsNullOrEmpty(error))
            {
                // Remove clip
                HandleUnload(requestData, error);
            }
            // Load success
            else
            {
                // Load success event
                OnLoadSuccess(requestData);
                // Playback is ready
                OnPlaybackReady(requestData);
            }
            // Stop previously spoken clip & play next
            if (requestData.StopQueueOnLoad && IsSpeaking)
            {
                StopSpeaking();
            }
            // Attempt to play next in queue
            else
            {
                RefreshPlayback();
            }
        }
HandlePlaybackComplete()
virtual void Meta.WitAi.TTS.Utilities.TTSSpeaker.HandlePlaybackComplete (bool stopped) protected virtual
Definition at line 1332 of file TTSSpeaker.cs.
        {
            // Stop playback handler
            if (_waitForCompletion != null)
            {
                StopCoroutine(_waitForCompletion);
                _waitForCompletion = null;
            }
            // Keep last request data
            TTSSpeakerRequestData lastRequestData = _speakingRequest;
            // Clear speaking request
            _speakingRequest = new TTSSpeakerRequestData();
            // Stop audio source playback
            AudioPlayer.Stop();
            // Stopped
            if (stopped)
            {
                OnPlaybackCancelled(lastRequestData, "Playback stopped manually");
            }
            // No clip found
            else if (lastRequestData.ClipData == null)
            {
                OnPlaybackCancelled(lastRequestData, "TTSClipData no longer exists");
            }
            // Clip unloaded
            else if (lastRequestData.ClipData.loadState == TTSClipLoadState.Unloaded)
            {
                OnPlaybackCancelled(lastRequestData, "TTSClipData was unloaded");
            }
            // Clip destroyed
            else if (lastRequestData.ClipData.clipStream == null)
            {
                OnPlaybackCancelled(lastRequestData, "AudioClip no longer exists");
            }
            // Success
            else
            {
                OnPlaybackComplete(lastRequestData);
            }
            // Refresh in queue check
            RefreshQueueEvents();
            // Attempt to play next in queue if all playback was not just stopped
            RefreshPlayback();
        }
HandleUnload() [1/3]
void Meta.WitAi.TTS.Utilities.TTSSpeaker.HandleUnload (Func< TTSSpeakerRequestData, bool > shouldKeep, string error) private
Definition at line 1439 of file TTSSpeaker.cs.
        {
            // Ignore if destroyed
            if (_queuedRequests == null)
            {
                return;
            }
            // Otherwise create discard queue
            Queue<TTSSpeakerRequestData> discard = _queuedRequests;
            _queuedRequests = new Queue<TTSSpeakerRequestData>();
            // Iterate all items
            while (discard.Count > 0)
            {
                // Dequeue from discard
                TTSSpeakerRequestData check = discard.Dequeue();
                // Clip data missing
                if (check.ClipData == null)
                {
                    OnLoadFailed(check, "TTSClipData missing");
                }
                // Do not keep
                else if (shouldKeep != null && !shouldKeep(check))
                {
                    // Cancelled
                    if (string.IsNullOrEmpty(error) || string.Equals(error, WitConstants.CANCEL_ERROR))
                    {
                        OnLoadAborted(check);
                    }
                    // Failure
                    else
                    {
                        OnLoadFailed(check, error);
                    }
                }
                // Keep all others
                else
                {
                    _queuedRequests.Enqueue(check);
                }
            }
            // Refresh in queue check
            RefreshQueueEvents();
        }
HandleUnload() [2/3]
void Meta.WitAi.TTS.Utilities.TTSSpeaker.HandleUnload (TTSClipData clipData, string error) private
Definition at line 1429 of file TTSSpeaker.cs.
        {
            HandleUnload((checkRequest) => !string.Equals(checkRequest.ClipData.clipID, clipData?.clipID), error);
        }
HandleUnload() [3/3]
void Meta.WitAi.TTS.Utilities.TTSSpeaker.HandleUnload (TTSSpeakerRequestData requestData, string error) private
Definition at line 1434 of file TTSSpeaker.cs.
        {
            HandleUnload((checkRequest) => !checkRequest.Equals(requestData), error);
        }
IsClipRequestActive()
bool Meta.WitAi.TTS.Utilities.TTSSpeaker.IsClipRequestActive (TTSSpeakerRequestData requestData) protected
Definition at line 336 of file TTSSpeaker.cs.
        {
            return IsClipRequestLoading(requestData) || IsClipRequestSpeaking(requestData);
        }
IsClipRequestLoading()
bool Meta.WitAi.TTS.Utilities.TTSSpeaker.IsClipRequestLoading (TTSSpeakerRequestData requestData) protected
Definition at line 341 of file TTSSpeaker.cs.
        {
            return _queuedRequests.Contains(requestData);
        }
IsClipRequestSpeaking()
bool Meta.WitAi.TTS.Utilities.TTSSpeaker.IsClipRequestSpeaking (TTSSpeakerRequestData requestData) protected
Definition at line 346 of file TTSSpeaker.cs.
        {
            return _speakingRequest.Equals(requestData);
        }
IsPlaybackComplete()
virtual bool Meta.WitAi.TTS.Utilities.TTSSpeaker.IsPlaybackComplete (float elapsedTime) protected virtual
Definition at line 1327 of file TTSSpeaker.cs.
        {
            return elapsedTime >= AudioPlayer?.ClipStream.Length || (!AudioPlayer.IsPlaying && !IsPaused);
        }
Log()
virtual void Meta.WitAi.TTS.Utilities.TTSSpeaker.Log (string comment) protected virtual
Definition at line 1490 of file TTSSpeaker.cs.
        {
            StringBuilder log = new StringBuilder();
            log.AppendLine(comment);
            log.AppendLine($"Voice: {presetVoiceID}");
            VLog.D(LogCategory, log);
        }
LogRequestData()
virtual void Meta.WitAi.TTS.Utilities.TTSSpeaker.LogRequestData (string comment, TTSSpeakerRequestData requestData, bool warning = false) protected virtual
Definition at line 1513 of file TTSSpeaker.cs.
        {
            StringBuilder log = new StringBuilder();
            log.AppendLine(comment);
            log.AppendLine($"Voice: {requestData.ClipData?.voiceSettings?.SettingsId}");
            log.AppendLine($"Cache: {requestData.ClipData?.diskCacheSettings?.DiskCacheLocation.ToString()}");
            log.AppendLine($"Text: {requestData.ClipData?.textToSpeak}");
            log.AppendLine($"Audio Player Type: {(_audioPlayer == null ? "NULL" : _audioPlayer.GetType().ToString())}");
            log.AppendLine($"Audio Clip Stream Type: {(requestData.ClipData?.clipStream == null ? "NULL" : requestData.ClipData?.clipStream.GetType().ToString())}");
            log.AppendLine($"Elapsed: {(DateTime.Now - requestData.StartTime).TotalMilliseconds:0.0}ms");
            if (warning)
            {
                VLog.W(LogCategory, log);
            }
            else
            {
                VLog.D(LogCategory, log);
            }
        }
OnComplete()
virtual void Meta.WitAi.TTS.Utilities.TTSSpeaker.OnComplete (TTSSpeakerRequestData requestData) protected virtual
Definition at line 1702 of file TTSSpeaker.cs.
        {
            Events?.OnComplete?.Invoke(this, requestData.ClipData);
            requestData.PlaybackEvents?.OnComplete?.Invoke(this, requestData.ClipData);
        }
OnDestroy()
virtual void Meta.WitAi.TTS.Utilities.TTSSpeaker.OnDestroy () protected virtual
Definition at line 240 of file TTSSpeaker.cs.
        {
            Stop();
            _queuedRequests = null;
            _speakingRequest = new TTSSpeakerRequestData();
        }
OnDisable()
virtual void Meta.WitAi.TTS.Utilities.TTSSpeaker.OnDisable () protected virtual
Definition at line 257 of file TTSSpeaker.cs.
        {
            Stop();
            if (!TTSService)
            {
                return;
            }
            TTSService.Events.OnClipUnloaded.RemoveListener(HandleClipUnload);
            TTSService.Events.Stream.OnStreamClipUpdate.RemoveListener(HandleClipUpdate);
        }
OnEnable()
virtual void Meta.WitAi.TTS.Utilities.TTSSpeaker.OnEnable () protected virtual
Definition at line 247 of file TTSSpeaker.cs.
        {
            if (!TTSService)
            {
                return;
            }
            TTSService.Events.OnClipUnloaded.AddListener(HandleClipUnload);
            TTSService.Events.Stream.OnStreamClipUpdate.AddListener(HandleClipUpdate);
        }
OnInit()
virtual void Meta.WitAi.TTS.Utilities.TTSSpeaker.OnInit (TTSSpeakerRequestData requestData) protected virtual
Definition at line 1533 of file TTSSpeaker.cs.
        {
            Events?.OnInit?.Invoke(this, requestData.ClipData);
            requestData.PlaybackEvents?.OnInit?.Invoke(this, requestData.ClipData);
        }
OnLoadAborted()
virtual void Meta.WitAi.TTS.Utilities.TTSSpeaker.OnLoadAborted (TTSSpeakerRequestData requestData) protected virtual
Definition at line 1556 of file TTSSpeaker.cs.
        {
            LogRequestData("Load Aborted", requestData);
            // Deprecated speaker events
#pragma warning disable CS0618
            Events?.OnClipDataLoadAbort?.Invoke(requestData.ClipData);
#pragma warning disable CS0618
            Events?.OnClipLoadAbort?.Invoke(this, requestData.ClipData?.textToSpeak);
            // Speaker clip events
            Events?.OnLoadAbort?.Invoke(this, requestData.ClipData);
            requestData.PlaybackEvents?.OnLoadAbort?.Invoke(this, requestData.ClipData);
            // Complete
            OnComplete(requestData);
        }
OnLoadBegin()
virtual void Meta.WitAi.TTS.Utilities.TTSSpeaker.OnLoadBegin (TTSSpeakerRequestData requestData) protected virtual
Definition at line 1539 of file TTSSpeaker.cs.
        {
            LogRequestData("Load Begin", requestData);
            // Deprecated speaker events
#pragma warning disable CS0618
            Events?.OnClipDataQueued?.Invoke(requestData.ClipData);
#pragma warning disable CS0618
            Events?.OnClipDataLoadBegin?.Invoke(requestData.ClipData);
#pragma warning disable CS0618
            Events?.OnClipLoadBegin?.Invoke(this, requestData.ClipData?.textToSpeak);
            // Speaker clip events
            Events?.OnLoadBegin?.Invoke(this, requestData.ClipData);
            requestData.PlaybackEvents?.OnLoadBegin?.Invoke(this, requestData.ClipData);
        }
OnLoadFailed()
virtual void Meta.WitAi.TTS.Utilities.TTSSpeaker.OnLoadFailed (TTSSpeakerRequestData requestData, string error) protected virtual
Definition at line 1574 of file TTSSpeaker.cs.
        {
            LogRequestData($"Load Failed\nError: {error}", requestData, true);
            // Deprecated speaker events
#pragma warning disable CS0618
            Events?.OnClipDataLoadFailed?.Invoke(requestData.ClipData);
#pragma warning disable CS0618
            Events?.OnClipLoadFailed?.Invoke(this, requestData.ClipData?.textToSpeak);
            // Speaker clip events
            Events?.OnLoadFailed?.Invoke(this, requestData.ClipData, error);
            requestData.PlaybackEvents?.OnLoadFailed?.Invoke(this, requestData.ClipData, error);
            // Complete
            OnComplete(requestData);
        }
OnLoadSuccess()
virtual void Meta.WitAi.TTS.Utilities.TTSSpeaker.OnLoadSuccess (TTSSpeakerRequestData requestData) protected virtual
Definition at line 1592 of file TTSSpeaker.cs.
        {
            LogRequestData("Load Success", requestData);
            // Deprecated speaker events
#pragma warning disable CS0618
            Events?.OnClipDataLoadSuccess?.Invoke(requestData.ClipData);
#pragma warning disable CS0618
            Events?.OnClipLoadSuccess?.Invoke(this, requestData.ClipData?.textToSpeak);
            // Speaker clip events
            Events?.OnLoadSuccess?.Invoke(this, requestData.ClipData);
            requestData.PlaybackEvents?.OnLoadSuccess?.Invoke(this, requestData.ClipData);
        }
OnPlaybackCancelled()
virtual void Meta.WitAi.TTS.Utilities.TTSSpeaker.OnPlaybackCancelled (TTSSpeakerRequestData requestData, string reason) protected virtual
Definition at line 1645 of file TTSSpeaker.cs.
        {
            LogRequestData($"Playback Cancelled\nReason: {reason}", requestData);
            // Speaker playback events
            Events?.OnTextPlaybackCancelled?.Invoke(requestData.ClipData?.textToSpeak);
            requestData.PlaybackEvents?.OnTextPlaybackCancelled?.Invoke(requestData.ClipData?.textToSpeak);
            Events?.OnAudioClipPlaybackCancelled?.Invoke(requestData.ClipData?.clip);
            requestData.PlaybackEvents?.OnAudioClipPlaybackCancelled?.Invoke(requestData.ClipData?.clip);
            // Deprecated speaker events
#pragma warning disable CS0618
            Events?.OnClipDataPlaybackCancelled?.Invoke(requestData.ClipData);
#pragma warning disable CS0618
            Events?.OnCancelledSpeaking?.Invoke(this, requestData.ClipData?.textToSpeak);
            // Speaker clip events
            Events?.OnPlaybackCancelled?.Invoke(this, requestData.ClipData, reason);
            requestData.PlaybackEvents?.OnPlaybackCancelled?.Invoke(this, requestData.ClipData, reason);
            // Complete
            OnComplete(requestData);
        }
OnPlaybackClipUpdated()
virtual void Meta.WitAi.TTS.Utilities.TTSSpeaker.OnPlaybackClipUpdated (TTSSpeakerRequestData requestData) protected virtual
Definition at line 1669 of file TTSSpeaker.cs.
        {
            LogRequestData("Playback Clip Updated", requestData);
            // Speaker clip events
            Events?.OnPlaybackClipUpdated?.Invoke(this, requestData.ClipData);
            requestData.PlaybackEvents?.OnPlaybackClipUpdated?.Invoke(this, requestData.ClipData);
        }
OnPlaybackComplete()
virtual void Meta.WitAi.TTS.Utilities.TTSSpeaker.OnPlaybackComplete (TTSSpeakerRequestData requestData) protected virtual
Definition at line 1678 of file TTSSpeaker.cs.
        {
            LogRequestData("Playback Complete", requestData);
            // Speaker playback events
            Events?.OnTextPlaybackFinished?.Invoke(requestData.ClipData?.textToSpeak);
            requestData.PlaybackEvents?.OnTextPlaybackFinished?.Invoke(requestData.ClipData?.textToSpeak);
            Events?.OnAudioClipPlaybackFinished?.Invoke(requestData.ClipData?.clip);
            requestData.PlaybackEvents?.OnAudioClipPlaybackFinished?.Invoke(requestData.ClipData?.clip);
            // Deprecated speaker events
#pragma warning disable CS0618
            Events?.OnClipDataPlaybackFinished?.Invoke(requestData.ClipData);
#pragma warning disable CS0618
            Events?.OnFinishedSpeaking?.Invoke(this, requestData.ClipData?.textToSpeak);
            // Speaker clip events
            Events?.OnPlaybackComplete?.Invoke(this, requestData.ClipData);
            requestData.PlaybackEvents?.OnPlaybackComplete?.Invoke(this, requestData.ClipData);
            // Complete
            OnComplete(requestData);
        }
OnPlaybackQueueBegin()
virtual void Meta.WitAi.TTS.Utilities.TTSSpeaker.OnPlaybackQueueBegin () protected virtual
Definition at line 1498 of file TTSSpeaker.cs.
        {
            Log("Playback Queue Begin");
            Events?.OnPlaybackQueueBegin?.Invoke();
        }
OnPlaybackQueueComplete()
virtual void Meta.WitAi.TTS.Utilities.TTSSpeaker.OnPlaybackQueueComplete () protected virtual
Definition at line 1504 of file TTSSpeaker.cs.
        {
            Log("Playback Queue Complete");
            Events?.OnPlaybackQueueComplete?.Invoke();
        }
OnPlaybackReady()
virtual void Meta.WitAi.TTS.Utilities.TTSSpeaker.OnPlaybackReady (TTSSpeakerRequestData requestData) protected virtual
Definition at line 1607 of file TTSSpeaker.cs.
        {
            LogRequestData("Playback Ready", requestData);
            // Speaker playback events
            Events?.OnAudioClipPlaybackReady?.Invoke(requestData.ClipData?.clip);
            requestData.PlaybackEvents?.OnAudioClipPlaybackReady?.Invoke(requestData.ClipData?.clip);
            // Deprecated speaker events
#pragma warning disable CS0618
            Events?.OnClipDataPlaybackReady?.Invoke(requestData.ClipData);
            // Speaker clip events
            Events?.OnPlaybackReady?.Invoke(this, requestData.ClipData);
            requestData.PlaybackEvents?.OnPlaybackReady?.Invoke(this, requestData.ClipData);
        }
OnPlaybackStart()
virtual void Meta.WitAi.TTS.Utilities.TTSSpeaker.OnPlaybackStart (TTSSpeakerRequestData requestData) protected virtual
Definition at line 1624 of file TTSSpeaker.cs.
        {
            LogRequestData("Playback Begin", requestData);
            // Speaker playback events
            Events?.OnTextPlaybackStart?.Invoke(requestData.ClipData?.textToSpeak);
            requestData.PlaybackEvents?.OnTextPlaybackStart?.Invoke(requestData.ClipData?.textToSpeak);
            Events?.OnAudioClipPlaybackStart?.Invoke(requestData.ClipData?.clip);
            requestData.PlaybackEvents?.OnAudioClipPlaybackStart?.Invoke(requestData.ClipData?.clip);
            // Deprecated speaker events
#pragma warning disable CS0618
            Events?.OnClipDataPlaybackStart?.Invoke(requestData.ClipData);
#pragma warning disable CS0618
            Events?.OnStartSpeaking?.Invoke(this, requestData.ClipData?.textToSpeak);
            // Speaker clip events
            Events?.OnPlaybackStart?.Invoke(this, requestData.ClipData);
            requestData.PlaybackEvents?.OnPlaybackStart?.Invoke(this, requestData.ClipData);
        }
QueueContainsClip()
bool Meta.WitAi.TTS.Utilities.TTSSpeaker.QueueContainsClip (TTSClipData clipData) private
Definition at line 313 of file TTSSpeaker.cs.
        {
            TTSSpeakerRequestData requestData = GetQueuedRequest(clipData);
            return requestData.ClipData != null;
        }
RefreshPlayback()
void Meta.WitAi.TTS.Utilities.TTSSpeaker.RefreshPlayback () private
Refreshes playback queue to play next available clip if possible.
Definition at line 1220 of file TTSSpeaker.cs.
        {
            // Ignore if currently playing or nothing in uque
            if (SpeakingClip != null ||  _queuedRequests == null || _queuedRequests.Count == 0 || _audioPlayer == null)
            {
                return;
            }
            // Peek next request
            TTSSpeakerRequestData requestData = _queuedRequests.Peek();
            if (requestData.ClipData == null)
            {
                HandleLoadComplete(requestData, "TTSClipData no longer exists");
                return;
            }
            // Still preparing
            if (requestData.ClipData.loadState == TTSClipLoadState.Preparing)
            {
                return;
            }
            if (requestData.ClipData.loadState != TTSClipLoadState.Loaded)
            {
                HandleLoadComplete(requestData, $"TTSClipData is {requestData.ClipData.loadState}");
                return;
            }
            // No audio source
            string errors = AudioPlayer.GetPlaybackErrors();
            if (!string.IsNullOrEmpty(errors))
            {
                HandleLoadComplete(requestData, errors);
                return;
            }
            // Resume prior to playback
            if (requestData.StopQueueOnLoad && IsPaused)
            {
                Resume();
            }
            if (!string.IsNullOrEmpty(requestData.ClipData.textToSpeak))
            {
                // Somehow clip unloaded
                if (requestData.ClipData.clipStream == null)
                {
                    HandleLoadComplete(requestData, "AudioClipStream no longer exists");
                    return;
                }
                // Dequeue & apply
                _speakingRequest = _queuedRequests.Dequeue();
                // Started speaking
                AudioPlayer.Play(_speakingRequest.ClipData.clipStream, 0);
                // Call playback start events
                OnPlaybackStart(_speakingRequest);
                // Wait for completion
                if (_waitForCompletion != null)
                {
                    StopCoroutine(_waitForCompletion);
                    _waitForCompletion = null;
                }
                _waitForCompletion = StartCoroutine(WaitForPlaybackComplete());
            }
            else
            {
                // If we're sending an empty string we're really just potentially queuing an event so we can trigger it
                // between audio clips. Trigger start/stop events.
                _speakingRequest = _queuedRequests.Dequeue();
                OnPlaybackStart(_speakingRequest);
                HandlePlaybackComplete(false);
            }
        }
References Meta.Voice.Audio.AudioPlayer.GetPlaybackErrors(), Meta.WitAi.TTS.Utilities.TTSSpeaker.IsPaused, Meta.Voice.Audio.AudioPlayer.Play(), Meta.WitAi.TTS.Utilities.TTSSpeaker.Resume(), and Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeakingClip.
RefreshProcessors()
virtual void Meta.WitAi.TTS.Utilities.TTSSpeaker.RefreshProcessors () protected virtual
Definition at line 216 of file TTSSpeaker.cs.
        {
            // Get preprocessors
            if (_textPreprocessors == null)
            {
                _textPreprocessors = GetComponents<ISpeakerTextPreprocessor>();
            }
            // Get postprocessors
            if (_textPostprocessors == null)
            {
                _textPostprocessors = GetComponents<ISpeakerTextPostprocessor>();
            }
            // Fix prepend text to ensure it has a space
            if (!string.IsNullOrEmpty(PrependedText) && PrependedText.Length > 0 && !PrependedText.EndsWith(" "))
            {
                PrependedText = PrependedText + " ";
            }
            // Fix append text to ensure it is spaced correctly
            if (!string.IsNullOrEmpty(AppendedText) && AppendedText.Length > 0 && !AppendedText.StartsWith(" "))
            {
                AppendedText = " " + AppendedText;
            }
        }
RefreshQueueEvents()
void Meta.WitAi.TTS.Utilities.TTSSpeaker.RefreshQueueEvents () private
Definition at line 319 of file TTSSpeaker.cs.
        {
            bool newHasQueueStatus = IsActive || _willHaveQueue;
            if (_hasQueue != newHasQueueStatus)
            {
                _hasQueue = newHasQueueStatus;
                if (_hasQueue)
                {
                    OnPlaybackQueueBegin();
                }
                else
                {
                    OnPlaybackQueueComplete();
                }
            }
        }
SetPause()
virtual void Meta.WitAi.TTS.Utilities.TTSSpeaker.SetPause (bool toPaused) protected virtual
Definition at line 1400 of file TTSSpeaker.cs.
        {
            // Ignore if same
            if (IsPaused == toPaused)
            {
                return;
            }
            // Apply
            IsPaused = toPaused;
            VLog.D($"Speak Audio {(IsPaused ? "Paused" : "Resumed")}");
            // Adjust if speaking
            if (IsSpeaking)
            {
                if (IsPaused)
                {
                    AudioPlayer.Pause();
                }
                else if (!IsPaused)
                {
                    AudioPlayer.Resume();
                }
            }
        }
SetVoiceOverride()
void Meta.WitAi.TTS.Utilities.TTSSpeaker.SetVoiceOverride (TTSVoiceSettings overrideVoiceSettings)
Set a voice override for future requests.
Parameters
overrideSettings The settings to be applied to upcoming requests
Definition at line 817 of file TTSSpeaker.cs.
        {
            _overrideVoiceSettings = overrideVoiceSettings;
        }
Speak() [1/10]
void Meta.WitAi.TTS.Utilities.TTSSpeaker.Speak (string textToSpeak)
Load a tts clip using the specified text. Cancels all previous clips when loaded & then plays.
Parameters
textToSpeak The text to be spoken
Speak() [2/10]
void Meta.WitAi.TTS.Utilities.TTSSpeaker.Speak (string textToSpeak, TTSDiskCacheSettings diskCacheSettings)
Load a tts clip using the specified text & disk cache settings. Cancels all previous clips when loaded & then plays.
Parameters
textToSpeak The text to be spoken
diskCacheSettings Specific tts load caching settings
Speak() [3/10]
void Meta.WitAi.TTS.Utilities.TTSSpeaker.Speak (string textToSpeak, TTSDiskCacheSettings diskCacheSettings, TTSSpeakerClipEvents playbackEvents)
Load a tts clip using the specified text, disk cache settings & playback events. Cancels all previous clips when loaded & then plays.
Parameters
textToSpeak The text to be spoken
diskCacheSettings Specific tts load caching settings
playbackEvents Events to be called for this specific tts playback request
Speak() [4/10]
List< TTSSpeakerRequestData > Meta.WitAi.TTS.Utilities.TTSSpeaker.Speak (string textToSpeak, TTSDiskCacheSettings diskCacheSettings, TTSSpeakerClipEvents playbackEvents, bool addToQueue) private
Loads a tts clip & handles playback.
Parameters
textToSpeak The text to be spoken
diskCacheSettings Specific tts load caching settings
playbackEvents Events to be called for this specific tts playback request
addToQueue Whether or not this phrase should be enqueued into the playback queue
Returns
Speaker request data for request
Definition at line 661 of file TTSSpeaker.cs.
        {
            // Ensure voice settings exist
            TTSVoiceSettings voiceSettings = VoiceSettings;
            if (voiceSettings == null)
            {
                VLog.E($"No voice found with preset id: {presetVoiceID}");
                return null;
            }
            // Get final text phrases to be spoken
            List<string> phrases = GetFinalText(textToSpeak);
            if (phrases == null || phrases.Count == 0)
            {
                VLog.W($"All phrases removed\nSource Phrase: {textToSpeak}");
                return null;
            }
            // Cancel previous loading queue
            if (!addToQueue)
            {
                _willHaveQueue = true;
                StopLoading();
                _willHaveQueue = false;
            }
            // Iterate voices
            List<TTSSpeakerRequestData> results = new List<TTSSpeakerRequestData>();
            foreach (var phrase in phrases)
            {
                TTSSpeakerRequestData requestData = HandleLoad(phrase, voiceSettings, diskCacheSettings, playbackEvents, addToQueue);
                results.Add(requestData);
                // Add additional to queue
                if (!addToQueue)
                {
                    addToQueue = true;
                }
            }
            return results;
        }
References Meta.WitAi.VLog.E(), Meta.WitAi.TTS.Utilities.TTSSpeaker.GetFinalText(), Meta.WitAi.TTS.Utilities.TTSSpeaker.StopLoading(), Meta.WitAi.TTS.Utilities.TTSSpeaker.VoiceSettings, and Meta.WitAi.VLog.W().
Speak() [5/10]
void Meta.WitAi.TTS.Utilities.TTSSpeaker.Speak (string textToSpeak, TTSSpeakerClipEvents playbackEvents)
Load a tts clip using the specified text & playback events. Cancels all previous clips when loaded & then plays.
Parameters
textToSpeak The text to be spoken
playbackEvents Events to be called for this specific tts playback request
Speak() [6/10]
void Meta.WitAi.TTS.Utilities.TTSSpeaker.Speak (string textToSpeak, TTSVoiceSettings overrideVoiceSettings, TTSDiskCacheSettings diskCacheSettings, TTSSpeakerClipEvents playbackEvents)
Load a tts clip using the specified response node, disk cache settings & playback events. Cancels all previous clips when loaded & then plays.
Parameters
textToSpeak The text to be spoken
overrideVoiceSettings Custom voice settings to be used for this and upcoming requests
diskCacheSettings Specific tts load caching settings
playbackEvents Events to be called for this specific tts playback request
Definition at line 868 of file TTSSpeaker.cs.
        {
            // Apply voice override
            SetVoiceOverride(overrideVoiceSettings);
            // Speak
            Speak(textToSpeak, diskCacheSettings, playbackEvents);
        }
References Meta.WitAi.TTS.Utilities.TTSSpeaker.SetVoiceOverride(), and Meta.WitAi.TTS.Utilities.TTSSpeaker.Speak().
Speak() [7/10]
bool Meta.WitAi.TTS.Utilities.TTSSpeaker.Speak (WitResponseNode responseNode)
Load a tts clip using the specified response node & playback events Cancels all previous clips when loaded & then plays.
Parameters
responseNode Parsed data that includes text to be spoken & voice settings
Returns
True if responseNode is decoded successfully
Speak() [8/10]
bool Meta.WitAi.TTS.Utilities.TTSSpeaker.Speak (WitResponseNode responseNode, TTSDiskCacheSettings diskCacheSettings)
Load a tts clip using the specified response node & disk cache settings Cancels all previous clips when loaded & then plays.
Parameters
responseNode Parsed data that includes text to be spoken & voice settings
diskCacheSettings Specific tts load caching settings
Returns
True if responseNode is decoded successfully
Speak() [9/10]
bool Meta.WitAi.TTS.Utilities.TTSSpeaker.Speak (WitResponseNode responseNode, TTSDiskCacheSettings diskCacheSettings, TTSSpeakerClipEvents playbackEvents)
Load a tts clip using the specified response node, disk cache settings & playback events. Cancels all previous clips when loaded & then plays.
Parameters
responseNode Parsed data that includes text to be spoken & voice settings
diskCacheSettings Specific tts load caching settings
playbackEvents Events to be called for this specific tts playback request
Returns
True if responseNode is decoded successfully
Definition at line 886 of file TTSSpeaker.cs.
        {
            // Decode text to speak & voice settings
            if (!DecodeResponse(responseNode, out var textToSpeak, out var voiceSettings))
            {
                return false;
            }
            // Speak
            Speak(textToSpeak, voiceSettings, diskCacheSettings, playbackEvents);
            return true;
        }
References Meta.WitAi.TTS.Utilities.TTSSpeaker.DecodeResponse(), and Meta.WitAi.TTS.Utilities.TTSSpeaker.Speak().
Speak() [10/10]
bool Meta.WitAi.TTS.Utilities.TTSSpeaker.Speak (WitResponseNode responseNode, TTSSpeakerClipEvents playbackEvents)
Load a tts clip using the specified response node & playback events Cancels all previous clips when loaded & then plays.
Parameters
responseNode Parsed data that includes text to be spoken & voice settings
playbackEvents Events to be called for this specific tts playback request
Returns
True if responseNode is decoded successfully
SpeakAsync() [1/8]
IEnumerator Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeakAsync (string textToSpeak)
Load a tts clip using the specified text and then waits for the file to load & play. Cancels all previous clips when loaded & then plays.
Parameters
textToSpeak The text to be spoken
Definition at line 547 of file TTSSpeaker.cs.
        {
            yield return SpeakAsync(textToSpeak, null, null);
        }
References Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeakAsync().
SpeakAsync() [2/8]
IEnumerator Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeakAsync (string textToSpeak, TTSDiskCacheSettings diskCacheSettings)
Load a tts clip using the specified text & disk cache settings and then waits for the file to load & play. Cancels all previous clips when loaded & then plays.
Parameters
textToSpeak The text to be spoken
diskCacheSettings Specific tts load caching settings
Definition at line 537 of file TTSSpeaker.cs.
        {
            yield return SpeakAsync(textToSpeak, diskCacheSettings, null);
        }
References Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeakAsync().
SpeakAsync() [3/8]
IEnumerator Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeakAsync (string textToSpeak, TTSDiskCacheSettings diskCacheSettings, TTSSpeakerClipEvents playbackEvents)
Load a tts clip using the specified text, disk cache settings & playback events and then waits for the file to load & play. Cancels all previous clips when loaded & then plays.
Parameters
textToSpeak The text to be spoken
diskCacheSettings Specific tts load caching settings
playbackEvents Events to be called for this specific tts playback request
Definition at line 512 of file TTSSpeaker.cs.
        {
            // Speak text
            List<TTSSpeakerRequestData> requests = Speak(textToSpeak, diskCacheSettings, playbackEvents, false);
            // Wait while loading/speaking
            yield return WaitForCompletion(requests);
        }
References Meta.WitAi.TTS.Utilities.TTSSpeaker.Speak().
SpeakAsync() [4/8]
IEnumerator Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeakAsync (string textToSpeak, TTSSpeakerClipEvents playbackEvents)
Load a tts clip using the specified text & playback events and then waits for the file to load & play. Cancels all previous clips when loaded & then plays.
Parameters
textToSpeak The text to be spoken
playbackEvents Events to be called for this specific tts playback request
Definition at line 526 of file TTSSpeaker.cs.
        {
            yield return SpeakAsync(textToSpeak, null, playbackEvents);
        }
References Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeakAsync().
SpeakAsync() [5/8]
IEnumerator Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeakAsync (string textToSpeak, TTSVoiceSettings overrideVoiceSettings, TTSDiskCacheSettings diskCacheSettings, TTSSpeakerClipEvents playbackEvents)
Load a tts clip using the specified text, disk cache settings & playback events and then waits for the file to load & play. Cancels all previous clips when loaded & then plays.
Parameters
textToSpeak The text to be spoken
overrideVoiceSettings Custom voice settings to be used for this and upcoming requests
diskCacheSettings Specific tts load caching settings
playbackEvents Events to be called for this specific tts playback request
Definition at line 935 of file TTSSpeaker.cs.
        {
            // Set voice override
            SetVoiceOverride(overrideVoiceSettings);
            // Wait while loading/speaking
            yield return SpeakAsync(textToSpeak, diskCacheSettings, playbackEvents);
        }
References Meta.WitAi.TTS.Utilities.TTSSpeaker.SetVoiceOverride(), and Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeakAsync().
SpeakAsync() [6/8]
IEnumerator Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeakAsync (WitResponseNode responseNode, TTSDiskCacheSettings diskCacheSettings)
Load a tts clip using the specified text & disk cache settings and then waits for the file to load & play. Cancels all previous clips when loaded & then plays.
Parameters
responseNode Parsed data that includes text to be spoken & voice settings
diskCacheSettings Specific tts load caching settings
Definition at line 980 of file TTSSpeaker.cs.
        {
            yield return SpeakAsync(responseNode, diskCacheSettings, null);
        }
References Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeakAsync().
SpeakAsync() [7/8]
IEnumerator Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeakAsync (WitResponseNode responseNode, TTSDiskCacheSettings diskCacheSettings, TTSSpeakerClipEvents playbackEvents)
Load a tts clip using the specified text, disk cache settings & playback events and then waits for the file to load & play. Cancels all previous clips when loaded & then plays.
Parameters
responseNode Parsed data that includes text to be spoken & voice settings
diskCacheSettings Specific tts load caching settings
playbackEvents Events to be called for this specific tts playback request
Definition at line 951 of file TTSSpeaker.cs.
        {
            // Decode text to speak & voice settings
            if (!DecodeResponse(responseNode, out var textToSpeak, out var voiceSettings))
            {
                yield break;
            }
            // Wait while loading/speaking
            yield return SpeakAsync(textToSpeak, voiceSettings, diskCacheSettings, playbackEvents);
        }
References Meta.WitAi.TTS.Utilities.TTSSpeaker.DecodeResponse(), and Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeakAsync().
SpeakAsync() [8/8]
IEnumerator Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeakAsync (WitResponseNode responseNode, TTSSpeakerClipEvents playbackEvents)
Load a tts clip using the specified text & playback events and then waits for the file to load & play. Cancels all previous clips when loaded & then plays.
Parameters
responseNode Parsed data that includes text to be spoken & voice settings
playbackEvents Events to be called for this specific tts playback request
Definition at line 969 of file TTSSpeaker.cs.
        {
            yield return SpeakAsync(responseNode, null, playbackEvents);
        }
References Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeakAsync().
SpeakFormat()
void Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeakFormat (string format, params string[] textsToSpeak)
Loads a formated phrase to be spoken. Cancels all previous clips when loaded & then plays.
Parameters
format Format string to be filled in with texts
textsToSpeak Texts to be inserted into the formatter
SpeakFormatQueued()
void Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeakFormatQueued (string format, params string[] textsToSpeak)
Loads a formated phrase to be spoken. Adds clip to playback queue and will speak once queue has completed all playback.
Parameters
format Format string to be filled in with texts
textsToSpeak Texts to be inserted into the formatter
SpeakQueued() [1/9]
void Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeakQueued (string textToSpeak)
Load a tts clip using the specified text. Adds clip to playback queue and will speak once queue has completed all playback.
Parameters
textToSpeak The text to be spoken
SpeakQueued() [2/9]
void Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeakQueued (string textToSpeak, TTSDiskCacheSettings diskCacheSettings)
Load a tts clip using the specified text & disk cache settings events. Adds clip to playback queue and will speak once queue has completed all playback.
Parameters
textToSpeak The text to be spoken
diskCacheSettings Specific tts load caching settings
SpeakQueued() [3/9]
void Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeakQueued (string textToSpeak, TTSDiskCacheSettings diskCacheSettings, TTSSpeakerClipEvents playbackEvents)
Load a tts clip using the specified text, disk cache settings & playback events. Adds clip to playback queue and will speak once queue has completed all playback.
Parameters
textToSpeak The text to be spoken
diskCacheSettings Specific tts load caching settings
playbackEvents Events to be called for this specific tts playback request
SpeakQueued() [4/9]
void Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeakQueued (string textToSpeak, TTSSpeakerClipEvents playbackEvents)
Load a tts clip using the specified text & playback events. Adds clip to playback queue and will speak once queue has completed all playback.
Parameters
textToSpeak The text to be spoken
playbackEvents Events to be called for this specific tts playback request
SpeakQueued() [5/9]
void Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeakQueued (string textToSpeak, TTSVoiceSettings overrideVoiceSettings, TTSDiskCacheSettings diskCacheSettings, TTSSpeakerClipEvents playbackEvents)
Load a tts clip using the specified response node, disk cache settings & playback events. Adds clip to playback queue and will speak once queue has completed all playback.
Parameters
textToSpeak The text to be spoken
overrideVoiceSettings Custom voice settings to be used for this and upcoming requests
diskCacheSettings Specific tts load caching settings
playbackEvents Events to be called for this specific tts playback request
Definition at line 993 of file TTSSpeaker.cs.
        {
            // Apply voice override
            SetVoiceOverride(overrideVoiceSettings);
            // Speak
            SpeakQueued(textToSpeak, diskCacheSettings, playbackEvents);
        }
References Meta.WitAi.TTS.Utilities.TTSSpeaker.SetVoiceOverride(), and Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeakQueued().
SpeakQueued() [6/9]
bool Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeakQueued (WitResponseNode responseNode)
Load a tts clip using the specified text. Adds clip to playback queue and will speak once queue has completed all playback.
Parameters
responseNode Parsed data that includes text to be spoken & voice settings
Returns
True if responseNode is decoded successfully
SpeakQueued() [7/9]
bool Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeakQueued (WitResponseNode responseNode, TTSDiskCacheSettings diskCacheSettings)
Load a tts clip using the specified text & disk cache settings events. Adds clip to playback queue and will speak once queue has completed all playback.
Parameters
responseNode Parsed data that includes text to be spoken & voice settings
diskCacheSettings Specific tts load caching settings
Returns
True if responseNode is decoded successfully
SpeakQueued() [8/9]
bool Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeakQueued (WitResponseNode responseNode, TTSDiskCacheSettings diskCacheSettings, TTSSpeakerClipEvents playbackEvents)
Load a tts clip using the specified text, disk cache settings & playback events. Adds clip to playback queue and will speak once queue has completed all playback.
Parameters
responseNode Parsed data that includes text to be spoken & voice settings
diskCacheSettings Specific tts load caching settings
playbackEvents Events to be called for this specific tts playback request
Returns
True if responseNode is decoded successfully
Definition at line 1011 of file TTSSpeaker.cs.
        {
            // Decode text to speak & voice settings
            if (!DecodeResponse(responseNode, out var textToSpeak, out var voiceSettings))
            {
                return false;
            }
            // Speak queued
            SpeakQueued(textToSpeak, voiceSettings, diskCacheSettings, playbackEvents);
            return true;
        }
References Meta.WitAi.TTS.Utilities.TTSSpeaker.DecodeResponse(), and Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeakQueued().
SpeakQueued() [9/9]
bool Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeakQueued (WitResponseNode responseNode, TTSSpeakerClipEvents playbackEvents)
Load a tts clip using the specified text & playback events. Adds clip to playback queue and will speak once queue has completed all playback.
Parameters
responseNode Parsed data that includes text to be spoken & voice settings
playbackEvents Events to be called for this specific tts playback request
Returns
True if responseNode is decoded successfully
SpeakQueuedAsync() [1/9]
IEnumerator Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeakQueuedAsync (string[] textsToSpeak)
Load a tts clip using the specified text phrases and then waits for the files to load & play. Adds clip to playback queue and will speak once queue has completed all playback.
Parameters
textsToSpeak Multiple texts to be spoken
Definition at line 648 of file TTSSpeaker.cs.
        {
            yield return SpeakQueuedAsync(textsToSpeak, null, null);
        }
References Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeakQueuedAsync().
SpeakQueuedAsync() [2/9]
IEnumerator Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeakQueuedAsync (string[] textsToSpeak, TTSDiskCacheSettings diskCacheSettings)
Load a tts clip using the specified text phrases & disk cache settings and then waits for the files to load & play. Adds clip to playback queue and will speak once queue has completed all playback.
Parameters
textsToSpeak Multiple texts to be spoken
diskCacheSettings Specific tts load caching settings
Definition at line 638 of file TTSSpeaker.cs.
        {
            yield return SpeakQueuedAsync(textsToSpeak, diskCacheSettings, null);
        }
References Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeakQueuedAsync().
SpeakQueuedAsync() [3/9]
IEnumerator Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeakQueuedAsync (string[] textsToSpeak, TTSDiskCacheSettings diskCacheSettings, TTSSpeakerClipEvents playbackEvents)
Load a tts clip using the specified text phrases, disk cache settings & playback events and then waits for the files to load & play. Adds clip to playback queue and will speak once queue has completed all playback.
Parameters
textsToSpeak Multiple texts to be spoken
diskCacheSettings Specific tts load caching settings
playbackEvents Events to be called for this specific tts playback request
Definition at line 605 of file TTSSpeaker.cs.
        {
            // Speak each queued
            List<TTSSpeakerRequestData> requestList = new List<TTSSpeakerRequestData>();
            foreach (var textToSpeak in textsToSpeak)
            {
                List<TTSSpeakerRequestData> newRequests = Speak(textToSpeak, diskCacheSettings, playbackEvents, true);
                if (newRequests != null && newRequests.Count > 0)
                {
                    requestList.AddRange(newRequests);
                }
            }
            // Wait while loading/speaking
            yield return WaitForCompletion(requestList);
        }
References Meta.WitAi.TTS.Utilities.TTSSpeaker.Speak().
SpeakQueuedAsync() [4/9]
IEnumerator Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeakQueuedAsync (string[] textsToSpeak, TTSSpeakerClipEvents playbackEvents)
Load a tts clip using the specified text phrases & playback events and then waits for the files to load & play. Adds clip to playback queue and will speak once queue has completed all playback.
Parameters
textsToSpeak Multiple texts to be spoken
playbackEvents Events to be called for this specific tts playback request
Definition at line 627 of file TTSSpeaker.cs.
        {
            yield return SpeakQueuedAsync(textsToSpeak, null, playbackEvents);
        }
References Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeakQueuedAsync().
SpeakQueuedAsync() [5/9]
IEnumerator Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeakQueuedAsync (string[] textsToSpeak, TTSVoiceSettings overrideVoiceSettings, TTSDiskCacheSettings diskCacheSettings, TTSSpeakerClipEvents playbackEvents)
Load a tts clip using the specified text phrases, disk cache settings & playback events and then waits for the files to load & play. Adds clip to playback queue and will speak once queue has completed all playback.
Parameters
textsToSpeak Multiple texts to be spoken
diskCacheSettings Specific tts load caching settings
playbackEvents Events to be called for this specific tts playback request
Definition at line 1061 of file TTSSpeaker.cs.
        {
            // Set override
            SetVoiceOverride(overrideVoiceSettings);
            // Wait while loading/speaking
            yield return SpeakQueuedAsync(textsToSpeak, diskCacheSettings, playbackEvents);
        }
References Meta.WitAi.TTS.Utilities.TTSSpeaker.SetVoiceOverride(), and Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeakQueuedAsync().
SpeakQueuedAsync() [6/9]
IEnumerator Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeakQueuedAsync (WitResponseNode responseNode)
Load a tts clip using the specified text phrases and then waits for the files to load & play. Adds clip to playback queue and will speak once queue has completed all playback.
Parameters
responseNode Parsed data that includes text to be spoken & voice settings
Definition at line 1115 of file TTSSpeaker.cs.
        {
            yield return SpeakQueuedAsync(responseNode, null, null);
        }
References Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeakQueuedAsync().
SpeakQueuedAsync() [7/9]
IEnumerator Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeakQueuedAsync (WitResponseNode responseNode, TTSDiskCacheSettings diskCacheSettings)
Load a tts clip using the specified text phrases & disk cache settings and then waits for the files to load & play. Adds clip to playback queue and will speak once queue has completed all playback.
Parameters
responseNode Parsed data that includes text to be spoken & voice settings
diskCacheSettings Specific tts load caching settings
Definition at line 1105 of file TTSSpeaker.cs.
        {
            yield return SpeakQueuedAsync(responseNode, diskCacheSettings, null);
        }
References Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeakQueuedAsync().
SpeakQueuedAsync() [8/9]
IEnumerator Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeakQueuedAsync (WitResponseNode responseNode, TTSDiskCacheSettings diskCacheSettings, TTSSpeakerClipEvents playbackEvents)
Load a tts clip using the specified text phrases, disk cache settings & playback events and then waits for the files to load & play. Adds clip to playback queue and will speak once queue has completed all playback.
Parameters
responseNode Parsed data that includes text to be spoken & voice settings
diskCacheSettings Specific tts load caching settings
playbackEvents Events to be called for this specific tts playback request
Definition at line 1077 of file TTSSpeaker.cs.
        {
            // Decode text to speak & voice settings
            if (!DecodeResponse(responseNode, out var textToSpeak, out var voiceSettings))
            {
                yield break;
            }
            // Wait while loading/speaking
            yield return SpeakQueuedAsync(new string[] {textToSpeak}, voiceSettings, diskCacheSettings, playbackEvents);
        }
References Meta.WitAi.TTS.Utilities.TTSSpeaker.DecodeResponse(), and Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeakQueuedAsync().
SpeakQueuedAsync() [9/9]
IEnumerator Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeakQueuedAsync (WitResponseNode responseNode, TTSSpeakerClipEvents playbackEvents)
Load a tts clip using the specified text phrases & playback events and then waits for the files to load & play. Adds clip to playback queue and will speak once queue has completed all playback.
Parameters
responseNode Parsed data that includes text to be spoken & voice settings
playbackEvents Events to be called for this specific tts playback request
Definition at line 1094 of file TTSSpeaker.cs.
        {
            yield return SpeakQueuedAsync(responseNode, null, playbackEvents);
        }
References Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeakQueuedAsync().
Start()
virtual void Meta.WitAi.TTS.Utilities.TTSSpeaker.Start () protected virtual
Definition at line 207 of file TTSSpeaker.cs.
        {
            // Initialize audio
            AudioPlayer.Init();
            // Get text processors
            RefreshProcessors();
        }
Stop() [1/3]
virtual void Meta.WitAi.TTS.Utilities.TTSSpeaker.Stop () virtual
Stops loading & playback immediately.
Definition at line 805 of file TTSSpeaker.cs.
        {
            StopLoading();
            StopSpeaking();
        }
References Meta.WitAi.TTS.Utilities.TTSSpeaker.StopLoading(), and Meta.WitAi.TTS.Utilities.TTSSpeaker.StopSpeaking().
Stop() [2/3]
virtual void Meta.WitAi.TTS.Utilities.TTSSpeaker.Stop (string textToSpeak, bool allInstances = false) virtual
Stop load & playback of a specific clip.
Parameters
clipData The clip to be stopped & removed from the queue
allInstances Whether to remove the first instance of this clip or all instances
Definition at line 708 of file TTSSpeaker.cs.
        {
            // Found speaking clip
            if (string.Equals(SpeakingClip?.textToSpeak, textToSpeak))
            {
                Stop(SpeakingClip, allInstances);
                return;
            }
            // Find all clips that match & stop them
            foreach (var clipData in QueuedClips)
            {
                if (string.Equals(clipData?.textToSpeak, textToSpeak))
                {
                    Stop(clipData, allInstances);
                    if (!allInstances)
                    {
                        return;
                    }
                }
            }
        }
References Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeakingClip, and Meta.WitAi.TTS.Utilities.TTSSpeaker.Stop().
Stop() [3/3]
virtual void Meta.WitAi.TTS.Utilities.TTSSpeaker.Stop (TTSClipData clipData, bool allInstances = false) virtual
Stop load & playback of a specific clip.
Parameters
clipData The clip to be stopped & removed from the queue
allInstances Whether to remove the first instance of this clip or all instances
Definition at line 736 of file TTSSpeaker.cs.
        {
            // Check if speaking
            bool isSpeakingClip = SpeakingClip != null && clipData.Equals(SpeakingClip);
            // Cancel queue
            if (!isSpeakingClip || allInstances)
            {
                // Unload all instances
                if (allInstances)
                {
                    if (QueueContainsClip(clipData))
                    {
                        HandleUnload(clipData, string.Empty);
                    }
                }
                // Unload a single request
                else
                {
                    HandleUnload(GetQueuedRequest(clipData), string.Empty);
                }
            }
            // Cancel playback
            if (isSpeakingClip)
            {
                StopSpeaking();
            }
        }
References Meta.WitAi.TTS.Data.TTSClipData.Equals(), Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeakingClip, and Meta.WitAi.TTS.Utilities.TTSSpeaker.StopSpeaking().
StopLoading()
virtual void Meta.WitAi.TTS.Utilities.TTSSpeaker.StopLoading () virtual
Abort loading of all items in the load queue.
Definition at line 769 of file TTSSpeaker.cs.
        {
            // Ignore if not loading
            if (!IsLoading)
            {
                return;
            }
            // Cancel each clip from loading
            while (_queuedRequests.Count > 0)
            {
                OnLoadAborted(_queuedRequests.Dequeue());
            }
            // Refresh in queue check
            RefreshQueueEvents();
        }
References Meta.WitAi.TTS.Utilities.TTSSpeaker.IsLoading.
StopSpeaking()
virtual void Meta.WitAi.TTS.Utilities.TTSSpeaker.StopSpeaking () virtual
Stop playback of currently played audio clip.
Definition at line 790 of file TTSSpeaker.cs.
        {
            // Cannot stop speaking when not currently speaking
            if (!IsSpeaking)
            {
                return;
            }
            // Cancel playback
            HandlePlaybackComplete(true);
        }
References Meta.WitAi.TTS.Utilities.TTSSpeaker.IsSpeaking.
WaitForCompletion()
IEnumerator Meta.WitAi.TTS.Utilities.TTSSpeaker.WaitForCompletion (List< TTSSpeakerRequestData > requestData) protected
Definition at line 351 of file TTSSpeaker.cs.
        {
            // All done
            int count = requestData?.Count ?? 0;
            if (count == 0)
            {
                yield break;
            }
            // Current active requests
            int activeRequests = 0;
            UnityAction<TTSSpeaker, TTSClipData> onComplete = (speaker, clip) => activeRequests--;
            // Add event delegates
            for (int r = 0; r < count; r++)
            {
                TTSSpeakerRequestData request = requestData[r];
                if (!IsClipRequestActive(request))
                {
                    continue;
                }
                activeRequests++;
                request.PlaybackEvents.OnComplete.AddListener(onComplete);
            }
            // Wait for active requests to be complete
            yield return new WaitWhile(() => activeRequests > 0);
            // Remove event delegates
            for (int r = 0; r < count; r++)
            {
                TTSSpeakerRequestData request = requestData[r];
                request.PlaybackEvents?.OnComplete.RemoveListener(onComplete);
            }
        }
WaitForPlaybackComplete()
IEnumerator Meta.WitAi.TTS.Utilities.TTSSpeaker.WaitForPlaybackComplete () private
Definition at line 1294 of file TTSSpeaker.cs.
        {
            // Use delta time to wait for completion
            float elapsedTime = 0f;
            while (!IsPlaybackComplete(elapsedTime))
            {
                yield return new WaitForEndOfFrame();
                // Fix audio source, paused/resumed externally
                bool playerPaused = !AudioPlayer.IsPlaying;
                if (IsPaused != playerPaused)
                {
                    if (IsPaused)
                    {
                        AudioPlayer.Pause();
                    }
                    else
                    {
                        AudioPlayer.Resume();
                    }
                }
                // Only increment if playing
                if (!IsPaused)
                {
                    elapsedTime += Time.deltaTime;
                }
            }
            // Playback completed
            HandlePlaybackComplete(false);
        }
Member Data Documentation
_audioPlayer
IAudioPlayer Meta.WitAi.TTS.Utilities.TTSSpeaker._audioPlayer private
Definition at line 190 of file TTSSpeaker.cs.
_events
TTSSpeakerEvents Meta.WitAi.TTS.Utilities.TTSSpeaker._events = new TTSSpeakerEvents() private
Definition at line 29 of file TTSSpeaker.cs.
_hasQueue
bool Meta.WitAi.TTS.Utilities.TTSSpeaker._hasQueue = false private
Definition at line 157 of file TTSSpeaker.cs.
_overrideVoiceSettings
TTSVoiceSettings Meta.WitAi.TTS.Utilities.TTSSpeaker._overrideVoiceSettings private
Definition at line 68 of file TTSSpeaker.cs.
_queuedRequests
Queue<TTSSpeakerRequestData> Meta.WitAi.TTS.Utilities.TTSSpeaker._queuedRequests = new Queue<TTSSpeakerRequestData>() private
Definition at line 147 of file TTSSpeaker.cs.
_speakingRequest
TTSSpeakerRequestData Meta.WitAi.TTS.Utilities.TTSSpeaker._speakingRequest protected
Definition at line 145 of file TTSSpeaker.cs.
_textPostprocessors
ISpeakerTextPostprocessor [] Meta.WitAi.TTS.Utilities.TTSSpeaker._textPostprocessors private
Definition at line 162 of file TTSSpeaker.cs.
_textPreprocessors
ISpeakerTextPreprocessor [] Meta.WitAi.TTS.Utilities.TTSSpeaker._textPreprocessors private
Definition at line 161 of file TTSSpeaker.cs.
_ttsService
TTSService Meta.WitAi.TTS.Utilities.TTSSpeaker._ttsService private
Definition at line 44 of file TTSSpeaker.cs.
_waitForCompletion
Coroutine Meta.WitAi.TTS.Utilities.TTSSpeaker._waitForCompletion private
Definition at line 1215 of file TTSSpeaker.cs.
_willHaveQueue
bool Meta.WitAi.TTS.Utilities.TTSSpeaker._willHaveQueue = false private
Definition at line 158 of file TTSSpeaker.cs.
AppendedText
string Meta.WitAi.TTS.Utilities.TTSSpeaker.AppendedText
Definition at line 40 of file TTSSpeaker.cs.
customWitVoiceSettings
TTSWitVoiceSettings Meta.WitAi.TTS.Utilities.TTSSpeaker.customWitVoiceSettings
Definition at line 65 of file TTSSpeaker.cs.
PrependedText
string Meta.WitAi.TTS.Utilities.TTSSpeaker.PrependedText
Definition at line 36 of file TTSSpeaker.cs.
presetVoiceID
string Meta.WitAi.TTS.Utilities.TTSSpeaker.presetVoiceID
Definition at line 62 of file TTSSpeaker.cs.
Property Documentation
AudioPlayer
IAudioPlayer Meta.WitAi.TTS.Utilities.TTSSpeaker.AudioPlayer get
The script used to perform audio playback of IAudioClipStreams.
Gets IAudioPlayer component if applied to this speaker
If no IAudioPlayer component is found, the TTSService's audio system will be used to generate an audio player.
If still not found, adds a UnityAudioPlayer.
Definition at line 171 of file TTSSpeaker.cs.
        {
            get
            {
                if (_audioPlayer == null)
                {
                    _audioPlayer = gameObject.GetComponent<IAudioPlayer>();
                    if (_audioPlayer == null)
                    {
                        _audioPlayer = TTSService?.AudioSystem?.GetAudioPlayer(gameObject);
                        if (_audioPlayer == null)
{
                            _audioPlayer = gameObject.AddComponent<UnityAudioPlayer>();
                        }
                    }
                }
                return _audioPlayer;
            }
        }
AudioSource
AudioSource Meta.WitAi.TTS.Utilities.TTSSpeaker.AudioSource get
Definition at line 193 of file TTSSpeaker.cs.
        {
            get
            {
                if (AudioPlayer is IAudioSourceProvider uap)
                {
                    return uap.AudioSource;
                }
                return null;
            }
        }
Events
TTSSpeakerEvents Meta.WitAi.TTS.Utilities.TTSSpeaker.Events get
Definition at line 30 of file TTSSpeaker.cs.
IsActive
bool Meta.WitAi.TTS.Utilities.TTSSpeaker.IsActive get
Whether the speaker currently has currently speaking clip or a playback queue.
Definition at line 142 of file TTSSpeaker.cs.
IsLoading
bool Meta.WitAi.TTS.Utilities.TTSSpeaker.IsLoading get
Whether there are any clips in the loading queue.
Definition at line 107 of file TTSSpeaker.cs.
IsPaused
bool Meta.WitAi.TTS.Utilities.TTSSpeaker.IsPaused get private set
Whether playback is currently paused or not.
Definition at line 1387 of file TTSSpeaker.cs.
{ get; private set; }
IsPreparing
bool Meta.WitAi.TTS.Utilities.TTSSpeaker.IsPreparing get
Whether any queued clips are still not ready for playback.
Definition at line 111 of file TTSSpeaker.cs.
        {
            get
            {
                foreach (var request in _queuedRequests)
                {
                    if (request.ClipData != null && request.ClipData.loadState == TTSClipLoadState.Preparing)
                    {
                        return true;
                    }
                }
                return false;
            }
        }
IsSpeaking
bool Meta.WitAi.TTS.Utilities.TTSSpeaker.IsSpeaking get
Whether a clip is currently playing for this speaker.
Definition at line 98 of file TTSSpeaker.cs.
LogCategory
virtual string Meta.WitAi.TTS.Utilities.TTSSpeaker.LogCategory get protected
Definition at line 93 of file TTSSpeaker.cs.
QueuedClips
List<TTSClipData> Meta.WitAi.TTS.Utilities.TTSSpeaker.QueuedClips get
Definition at line 126 of file TTSSpeaker.cs.
        {
            get
            {
                List<TTSClipData> clips = new List<TTSClipData>();
                foreach (var request in _queuedRequests)
                {
                    clips.Add(request.ClipData);
                }
                return clips;
            }
        }
SpeakingClip
TTSClipData Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeakingClip get
The data for the currently playing clip.
Definition at line 102 of file TTSSpeaker.cs.
SpeechEvents
VoiceSpeechEvents Meta.WitAi.TTS.Utilities.TTSSpeaker.SpeechEvents get
Implements Meta.WitAi.Speech.ISpeechEventProvider.
Definition at line 31 of file TTSSpeaker.cs.
TTSService
TTSService Meta.WitAi.TTS.Utilities.TTSSpeaker.TTSService get
Definition at line 45 of file TTSSpeaker.cs.
        {
            get
            {
                if (!_ttsService)
                {
                    _ttsService = GetComponent<TTSService>();
                    if (!_ttsService)
                    {
                        _ttsService = TTSService.Instance;
                    }
                }
                return _ttsService;
            }
        }
VoiceSettings
TTSVoiceSettings Meta.WitAi.TTS.Utilities.TTSSpeaker.VoiceSettings get
The voice settings to be used for this TTSSpeaker.
Definition at line 73 of file TTSSpeaker.cs.
        {
            get
            {
                // Use override if exists & runtime
                if (Application.isPlaying && _overrideVoiceSettings != null)
                {
                    return _overrideVoiceSettings;
                }
                // Attempts to use custom voice settings
                if (string.IsNullOrEmpty(presetVoiceID) && customWitVoiceSettings != null)
                {
                    return customWitVoiceSettings;
                }
                // Uses preset voice id
                return TTSService.GetPresetVoiceSettings(presetVoiceID);
            }
        }
The documentation for this class was generated from the following file:
Assets/Oculus/Voice/Lib/Wit.ai/Features/TTS/Scripts/Runtime/Utilities/TTSSpeaker.cs