VR_Test: Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface Class Reference
Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface Class Reference
This type of surface defines a cylinder in which the grip pose is valid around an object. An angle and offset can be used to constrain the cylinder and not use a full circle. The radius is automatically specified as the distance from the axis of the cylinder to the original grip position.
Public Member Functions
Pose GetReferencePose (Transform relativeTo)
The reference pose of the surface. It defines the radius of the cylinder as the point from the relative transform to the reference pose to ensure that the cylinder covers this pose.
Vector3 GetPerpendicularDir (Transform relativeTo)
Direction from the axis of the cylinder to the original grip position.
Vector3 GetStartArcDir (Transform relativeTo)
Direction from the axis of the cylinder to the minimum angle allowance.
Vector3 GetEndArcDir (Transform relativeTo)
Direction from the axis of the cylinder to the maximum angle allowance.
Vector3 GetStartPoint (Transform relativeTo)
Base cap of the cylinder, in world coordinates.
void SetStartPoint (Vector3 point, Transform relativeTo)
Vector3 GetEndPoint (Transform relativeTo)
End cap of the cylinder, in world coordinates.
void SetEndPoint (Vector3 point, Transform relativeTo)
float GetRadius (Transform relativeTo)
The generated radius of the cylinder. Represents the distance from the axis of the cylinder to the original grip position.
Vector3 GetDirection (Transform relativeTo)
Direction of the cylinder, from the start cap to the end cap.
Pose MirrorPose (in Pose pose, Transform relativeTo)
Method for mirroring a Pose around the surface. Different surfaces will prefer mirroring along different axis.
GrabPoseScore CalculateBestPoseAtSurface (in Pose targetPose, out Pose bestPose, in PoseMeasureParameters scoringModifier, Transform relativeTo)
Finds the Pose at the surface that is the closest to the given pose.
IGrabSurface CreateMirroredSurface (GameObject gameObject)
Creates a new IGrabSurface under the selected gameobject that is a mirror version of the current.
IGrabSurface CreateDuplicatedSurface (GameObject gameObject)
Creates a new IGrabSurface under the selected gameobject with the same data as this one.
bool CalculateBestPoseAtSurface (Ray targetRay, out Pose bestPose, Transform relativeTo)
Finds the Pose at the surface that is the closest to the given ray.
void InjectAllCylinderSurface (CylinderSurfaceData data, Transform relativeTo)
void InjectData (CylinderSurfaceData data)
void InjectRelativeTo (Transform relativeTo)
Protected Member Functions
virtual void Reset ()
virtual void Start ()
Vector3 NearestPointInSurface (Vector3 targetPosition, Transform relativeTo)
Pose MinimalRotationPoseAtSurface (in Pose userPose, Transform relativeTo)
Pose MinimalTranslationPoseAtSurface (in Pose userPose, Transform relativeTo)
Quaternion CalculateRotationOffset (Vector3 surfacePoint, Transform relativeTo)
Protected Attributes
CylinderSurfaceData _data = new CylinderSurfaceData()
Properties
Pose RelativePose [get]
float ArcOffset [get, set]
Degrees from the starting radius from which the arc section starts.
float ArcLength [get, set]
The maximum angle for the surface of the cylinder, starting from the ArcOffset. To invert the direction of the angle, swap the caps order.
Vector3 LocalPerpendicularDir [get]
The direction of the main radius of the cylinder. This is the radius from the center of the cylinder to the reference position.
Vector3 LocalDirection [get]
The direction of the central axis of the cylinder in local space.
Private Member Functions
float GetHeight (Transform relativeTo)
Length of the cylinder, from the start cap to the end cap.
Quaternion GetRotation (Transform relativeTo)
The rotation of the central axis of the cylinder.
Vector3 PointAltitude (Vector3 point, Transform relativeTo)
Private Attributes
Transform _relativeTo
Static Private Attributes
const float Epsilon = 0.000001f
Detailed Description
This type of surface defines a cylinder in which the grip pose is valid around an object. An angle and offset can be used to constrain the cylinder and not use a full circle. The radius is automatically specified as the distance from the axis of the cylinder to the original grip position.
Definition at line 62 of file CylinderGrabSurface.cs.
Member Function Documentation
CalculateBestPoseAtSurface() [1/2]
GrabPoseScore Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.CalculateBestPoseAtSurface (in Pose targetPose, out Pose bestPose, in PoseMeasureParameters scoringModifier, Transform relativeTo)
Finds the Pose at the surface that is the closest to the given pose.
Parameters
targetPose The pose to find the nearest to.
bestPose The best found pose at the surface.<
scoringModifier Weight used to decide which target pose to select
relativeTo Reference transform to measure the poses against
Returns
The score indicating how good the found pose was, -1 for invalid result.
Implements Oculus.Interaction.Grab.GrabSurfaces.IGrabSurface.
Definition at line 300 of file CylinderGrabSurface.cs.
        {
            return GrabPoseHelper.CalculateBestPoseAtSurface(targetPose, out bestPose,
                scoringModifier, relativeTo,
                MinimalTranslationPoseAtSurface,
                MinimalRotationPoseAtSurface);
        }
References Oculus.Interaction.Grab.GrabPoseHelper.CalculateBestPoseAtSurface().
CalculateBestPoseAtSurface() [2/2]
bool Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.CalculateBestPoseAtSurface (Ray targetRay, out Pose bestPose, Transform relativeTo)
Finds the Pose at the surface that is the closest to the given ray.
Parameters
targetRay Ray searching for the nearest snap pose
bestPose The best found pose at the surface.
relativeTo Reference transform to measure the poses against
Returns
True if the pose was found
Implements Oculus.Interaction.Grab.GrabSurfaces.IGrabSurface.
Definition at line 358 of file CylinderGrabSurface.cs.
        {
            Pose recordedPose = GetReferencePose(relativeTo);
            Vector3 start = GetStartPoint(relativeTo);
            Vector3 direction = GetDirection(relativeTo);
            Vector3 lineToCylinder = start - targetRay.origin;
            float perpendiculiarity = Vector3.Dot(targetRay.direction, direction);
            float rayToLineDiff = Vector3.Dot(lineToCylinder, targetRay.direction);
            float cylinderToLineDiff = Vector3.Dot(lineToCylinder, direction);
            float determinant = 1f / (perpendiculiarity * perpendiculiarity - 1f);
            float lineOffset = (perpendiculiarity * cylinderToLineDiff - rayToLineDiff) * determinant;
            float cylinderOffset = (cylinderToLineDiff - perpendiculiarity * rayToLineDiff) * determinant;
            float radius = GetRadius(relativeTo);
            Vector3 pointInLine = targetRay.origin + targetRay.direction * lineOffset;
            Vector3 pointInCylinder = start + direction * cylinderOffset;
            float distanceToSurface = Mathf.Max(Vector3.Distance(pointInCylinder, pointInLine) - radius);
            if (distanceToSurface < radius)
            {
                float adjustedDistance = Mathf.Sqrt(radius * radius - distanceToSurface * distanceToSurface);
                pointInLine -= targetRay.direction * adjustedDistance;
            }
            Vector3 surfacePoint = NearestPointInSurface(pointInLine, relativeTo);
            Pose desiredPose = new Pose(surfacePoint, recordedPose.rotation);
            bestPose = MinimalTranslationPoseAtSurface(desiredPose, relativeTo);
            return true;
        }
References Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.GetDirection(), Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.GetRadius(), Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.GetReferencePose(), and Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.GetStartPoint().
CalculateRotationOffset()
Quaternion Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.CalculateRotationOffset (Vector3 surfacePoint, Transform relativeTo) protected
Definition at line 420 of file CylinderGrabSurface.cs.
        {
            Vector3 start = GetStartPoint(relativeTo);
            Vector3 direction = GetDirection(relativeTo);
            Vector3 referenceDir = GetPerpendicularDir(relativeTo);
            Vector3 recordedDirection = Vector3.ProjectOnPlane(referenceDir, direction);
            Vector3 desiredDirection = Vector3.ProjectOnPlane(surfacePoint - start, direction);
            return Quaternion.FromToRotation(recordedDirection, desiredDirection);
        }
CreateDuplicatedSurface()
IGrabSurface Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.CreateDuplicatedSurface (GameObject gameObject)
Creates a new IGrabSurface under the selected gameobject with the same data as this one.
Parameters
gameObject The gameobject in which to place the new IGrabSurface.
Returns
A clone of this IGrabSurface.
Implements Oculus.Interaction.Grab.GrabSurfaces.IGrabSurface.
Definition at line 316 of file CylinderGrabSurface.cs.
        {
            CylinderGrabSurface surface = gameObject.AddComponent<CylinderGrabSurface>();
            surface._data = _data.Clone() as CylinderSurfaceData;
            return surface;
        }
CreateMirroredSurface()
IGrabSurface Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.CreateMirroredSurface (GameObject gameObject)
Creates a new IGrabSurface under the selected gameobject that is a mirror version of the current.
Parameters
gameObject The gameobject in which to place the new IGrabSurface.
Returns
A mirror of this IGrabSurface.
Implements Oculus.Interaction.Grab.GrabSurfaces.IGrabSurface.
Definition at line 309 of file CylinderGrabSurface.cs.
        {
            CylinderGrabSurface surface = gameObject.AddComponent<CylinderGrabSurface>();
            surface._data = _data.Mirror();
            return surface;
        }
GetDirection()
Vector3 Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.GetDirection (Transform relativeTo)
Direction of the cylinder, from the start cap to the end cap.
Parameters
relativeTo The reference transform to apply the surface to
Returns
Direction in world space
Definition at line 239 of file CylinderGrabSurface.cs.
        {
            return relativeTo.TransformDirection(LocalDirection);
        }
References Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.LocalDirection.
GetEndArcDir()
Vector3 Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.GetEndArcDir (Transform relativeTo)
Direction from the axis of the cylinder to the maximum angle allowance.
Parameters
relativeTo The reference transform to apply the surface to
Returns
Direction in world space
Definition at line 184 of file CylinderGrabSurface.cs.
        {
            Vector3 localEndArcDir = Quaternion.AngleAxis(ArcLength, LocalDirection) *
                Quaternion.AngleAxis(ArcOffset, LocalDirection) * LocalPerpendicularDir;
            return relativeTo.TransformDirection(localEndArcDir);
        }
References Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.ArcLength, Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.ArcOffset, Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.LocalDirection, and Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.LocalPerpendicularDir.
GetEndPoint()
Vector3 Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.GetEndPoint (Transform relativeTo)
End cap of the cylinder, in world coordinates.
Parameters
relativeTo The reference transform to apply the surface to
Returns
Position in world space
Definition at line 210 of file CylinderGrabSurface.cs.
        {
            return relativeTo.TransformPoint(_data.endPoint);
        }
GetHeight()
float Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.GetHeight (Transform relativeTo) private
Length of the cylinder, from the start cap to the end cap.
Parameters
relativeTo The reference transform to apply the surface to
Returns
Distance in world space
Definition at line 249 of file CylinderGrabSurface.cs.
        {
            Vector3 start = GetStartPoint(relativeTo);
            Vector3 end = GetEndPoint(relativeTo);
            return Vector3.Distance(start, end);
        }
References Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.GetEndPoint(), and Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.GetStartPoint().
GetPerpendicularDir()
Vector3 Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.GetPerpendicularDir (Transform relativeTo)
Direction from the axis of the cylinder to the original grip position.
Parameters
relativeTo The reference transform to apply the surface to
Returns
Direction in world space
Definition at line 163 of file CylinderGrabSurface.cs.
        {
            return relativeTo.TransformDirection(LocalPerpendicularDir);
        }
References Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.LocalPerpendicularDir.
GetRadius()
float Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.GetRadius (Transform relativeTo)
The generated radius of the cylinder. Represents the distance from the axis of the cylinder to the original grip position.
Parameters
relativeTo The reference transform to apply the surface to
Returns
Distance in world space
Definition at line 225 of file CylinderGrabSurface.cs.
        {
            Vector3 start = GetStartPoint(relativeTo);
            Pose referencePose = GetReferencePose(relativeTo);
            Vector3 direction = GetDirection(relativeTo);
            Vector3 projectedPoint = start + Vector3.Project(referencePose.position - start, direction);
            return Vector3.Distance(projectedPoint, referencePose.position);
        }
References Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.GetDirection(), Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.GetReferencePose(), and Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.GetStartPoint().
GetReferencePose()
Pose Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.GetReferencePose (Transform relativeTo)
The reference pose of the surface. It defines the radius of the cylinder as the point from the relative transform to the reference pose to ensure that the cylinder covers this pose.
Parameters
relativeTo The reference transform to apply the surface to
Returns
Pose in world space
Definition at line 80 of file CylinderGrabSurface.cs.
        {
            return PoseUtils.GlobalPoseScaled(relativeTo, RelativePose);
        }
References Oculus.Interaction.PoseUtils.GlobalPoseScaled().
GetRotation()
Quaternion Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.GetRotation (Transform relativeTo) private
The rotation of the central axis of the cylinder.
Parameters
relativeTo The reference transform to apply the surface to
Returns
Rotation in world space
Definition at line 261 of file CylinderGrabSurface.cs.
        {
            if (_data.startPoint == _data.endPoint)
            {
                return relativeTo.rotation;
            }
            return relativeTo.rotation * Quaternion.LookRotation(LocalPerpendicularDir, LocalDirection);
        }
References Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.LocalDirection, and Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.LocalPerpendicularDir.
GetStartArcDir()
Vector3 Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.GetStartArcDir (Transform relativeTo)
Direction from the axis of the cylinder to the minimum angle allowance.
Parameters
relativeTo The reference transform to apply the surface to
Returns
Direction in world space
Definition at line 173 of file CylinderGrabSurface.cs.
        {
            Vector3 localStartArcDir = Quaternion.AngleAxis(ArcOffset, LocalDirection) * LocalPerpendicularDir;
            return relativeTo.TransformDirection(localStartArcDir);
        }
References Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.ArcOffset, Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.LocalDirection, and Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.LocalPerpendicularDir.
GetStartPoint()
Vector3 Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.GetStartPoint (Transform relativeTo)
Base cap of the cylinder, in world coordinates.
Parameters
relativeTo The reference transform to apply the surface to
Returns
Position in world space
Definition at line 196 of file CylinderGrabSurface.cs.
        {
            return relativeTo.TransformPoint(_data.startPoint);
        }
InjectAllCylinderSurface()
void Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.InjectAllCylinderSurface (CylinderSurfaceData data, Transform relativeTo)
Definition at line 432 of file CylinderGrabSurface.cs.
        {
            InjectData(data);
            InjectRelativeTo(relativeTo);
        }
InjectData()
void Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.InjectData (CylinderSurfaceData data)
Definition at line 439 of file CylinderGrabSurface.cs.
        {
            _data = data;
        }
InjectRelativeTo()
void Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.InjectRelativeTo (Transform relativeTo)
Definition at line 444 of file CylinderGrabSurface.cs.
        {
            _relativeTo = relativeTo;
        }
MinimalRotationPoseAtSurface()
Pose Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.MinimalRotationPoseAtSurface (in Pose userPose, Transform relativeTo) protected
Definition at line 391 of file CylinderGrabSurface.cs.
        {
            Pose referencePose = GetReferencePose(relativeTo);
            Vector3 direction = GetDirection(relativeTo);
            Quaternion rotation = GetRotation(relativeTo);
            float radius = GetRadius(relativeTo);
            Vector3 desiredPos = userPose.position;
            Quaternion desiredRot = userPose.rotation;
            Quaternion baseRot = referencePose.rotation;
            Quaternion rotDif = (desiredRot) * Quaternion.Inverse(baseRot);
            Vector3 desiredDirection = (rotDif * rotation) * Vector3.forward;
            Vector3 projectedDirection = Vector3.ProjectOnPlane(desiredDirection, direction).normalized;
            Vector3 altitudePoint = PointAltitude(desiredPos, relativeTo);
            Vector3 surfacePoint = NearestPointInSurface(altitudePoint + projectedDirection * radius, relativeTo);
            Quaternion surfaceRotation = CalculateRotationOffset(surfacePoint, relativeTo) * baseRot;
            return new Pose(surfacePoint, surfaceRotation);
        }
MinimalTranslationPoseAtSurface()
Pose Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.MinimalTranslationPoseAtSurface (in Pose userPose, Transform relativeTo) protected
Definition at line 409 of file CylinderGrabSurface.cs.
        {
            Pose referencePose = GetReferencePose(relativeTo);
            Vector3 desiredPos = userPose.position;
            Quaternion baseRot = referencePose.rotation;
            Vector3 surfacePoint = NearestPointInSurface(desiredPos, relativeTo);
            Quaternion surfaceRotation = CalculateRotationOffset(surfacePoint, relativeTo) * baseRot;
            return new Pose(surfacePoint, surfaceRotation);
        }
MirrorPose()
Pose Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.MirrorPose (in Pose gripPose, Transform relativeTo)
Method for mirroring a Pose around the surface. Different surfaces will prefer mirroring along different axis.
Parameters
gripPose The Pose to be mirrored.
relativeTo Reference transform to mirror the pose around
Returns
A new pose mirrored at this surface.
Implements Oculus.Interaction.Grab.GrabSurfaces.IGrabSurface.
Definition at line 283 of file CylinderGrabSurface.cs.
        {
            Vector3 normal = Quaternion.Inverse(relativeTo.rotation) * GetPerpendicularDir(relativeTo);
            Vector3 tangent = Quaternion.Inverse(relativeTo.rotation) * GetDirection(relativeTo);
            return pose.MirrorPoseRotation(normal, tangent);
        }
References Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.GetDirection(), and Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.GetPerpendicularDir().
NearestPointInSurface()
Vector3 Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.NearestPointInSurface (Vector3 targetPosition, Transform relativeTo) protected
Definition at line 323 of file CylinderGrabSurface.cs.
        {
            Vector3 start = GetStartPoint(relativeTo);
            Vector3 dir = GetDirection(relativeTo);
            Vector3 projectedVector = Vector3.Project(targetPosition - start, dir);
            float height = GetHeight(relativeTo);
            if (projectedVector.magnitude > height)
            {
                projectedVector = projectedVector.normalized * height;
            }
            if (Vector3.Dot(projectedVector, dir) < 0f)
            {
                projectedVector = Vector3.zero;
            }
            Vector3 projectedPoint = start + projectedVector;
            Vector3 targetDirection = Vector3.ProjectOnPlane((targetPosition - projectedPoint), dir).normalized;
            Vector3 startArcDir = GetStartArcDir(relativeTo);
            float desiredAngle = Mathf.Repeat(Vector3.SignedAngle(startArcDir, targetDirection, dir), 360f);
            if (desiredAngle > ArcLength)
            {
                if (Mathf.Abs(desiredAngle - ArcLength) >= Mathf.Abs(360f - desiredAngle))
                {
                    targetDirection = startArcDir;
                }
                else
                {
                    targetDirection = GetEndArcDir(relativeTo);
                }
            }
            Vector3 surfacePoint = projectedPoint + targetDirection * GetRadius(relativeTo);
            return surfacePoint;
        }
PointAltitude()
Vector3 Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.PointAltitude (Vector3 point, Transform relativeTo) private
Definition at line 291 of file CylinderGrabSurface.cs.
        {
            Vector3 start = GetStartPoint(relativeTo);
            Vector3 direction = GetDirection(relativeTo);
            Vector3 projectedPoint = start + Vector3.Project(point - start, direction);
            return projectedPoint;
        }
Reset()
virtual void Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.Reset () protected virtual
Definition at line 271 of file CylinderGrabSurface.cs.
        {
            _relativeTo = this.GetComponentInParent<IRelativeToRef>()?.RelativeTo;
        }
SetEndPoint()
void Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.SetEndPoint (Vector3 point, Transform relativeTo)
Definition at line 214 of file CylinderGrabSurface.cs.
        {
            _data.endPoint = relativeTo.InverseTransformPoint(point);
        }
SetStartPoint()
void Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.SetStartPoint (Vector3 point, Transform relativeTo)
Definition at line 200 of file CylinderGrabSurface.cs.
        {
            _data.startPoint = relativeTo.InverseTransformPoint(point);
        }
Start()
virtual void Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.Start () protected virtual
Definition at line 277 of file CylinderGrabSurface.cs.
        {
            this.AssertField(_data, nameof(_data));
            this.AssertField(_relativeTo, nameof(_relativeTo));
        }
Member Data Documentation
_data
CylinderSurfaceData Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface._data = new CylinderSurfaceData() protected
Definition at line 65 of file CylinderGrabSurface.cs.
_relativeTo
Transform Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface._relativeTo private
Definition at line 69 of file CylinderGrabSurface.cs.
Epsilon
const float Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.Epsilon = 0.000001f static private
Definition at line 72 of file CylinderGrabSurface.cs.
Property Documentation
ArcLength
float Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.ArcLength get set
The maximum angle for the surface of the cylinder, starting from the ArcOffset. To invert the direction of the angle, swap the caps order.
Definition at line 111 of file CylinderGrabSurface.cs.
        {
            get
            {
                return _data.arcLength;
            }
            set
            {
                if (value != 0 && value % 360f == 0)
                {
                    _data.arcLength = 360f;
                }
                else
                {
                    _data.arcLength = Mathf.Repeat(value, 360f);
                }
            }
        }
ArcOffset
float Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.ArcOffset get set
Degrees from the starting radius from which the arc section starts.
Definition at line 88 of file CylinderGrabSurface.cs.
        {
            get
            {
                return _data.arcOffset;
            }
            set
            {
                if (value != 0 && value % 360f == 0)
                {
                    _data.arcOffset = 360f;
                }
                else
                {
                    _data.arcOffset = Mathf.Repeat(value, 360f);
                }
            }
        }
LocalDirection
Vector3 Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.LocalDirection get private
The direction of the central axis of the cylinder in local space.
Definition at line 145 of file CylinderGrabSurface.cs.
        {
            get
            {
                Vector3 dir = (_data.endPoint - _data.startPoint);
                if (dir.sqrMagnitude <= Epsilon)
                {
                    return Vector3.up;
                }
                return dir.normalized;
            }
        }
LocalPerpendicularDir
Vector3 Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.LocalPerpendicularDir get private
The direction of the main radius of the cylinder. This is the radius from the center of the cylinder to the reference position.
Definition at line 134 of file CylinderGrabSurface.cs.
        {
            get
            {
                return Vector3.ProjectOnPlane(RelativePose.position - _data.startPoint, LocalDirection).normalized;
            }
        }
RelativePose
Pose Oculus.Interaction.Grab.GrabSurfaces.CylinderGrabSurface.RelativePose get private
Definition at line 71 of file CylinderGrabSurface.cs.
The documentation for this class was generated from the following file:
Assets/Oculus/Interaction/Runtime/Scripts/Grab/SnapSurfaces/CylinderGrabSurface.cs