VR_Test: Oculus.Interaction.Editor.EditorBase Class Reference
Oculus.Interaction.Editor.EditorBase Class Reference
A utility class for building custom editors with less work required.
Classes
class Section
Public Member Functions
EditorBase (SerializedObject serializedObject)
Section CreateSection (string sectionName, bool isFoldout)
void CreateSections (Dictionary< string, string[]> sections, bool isFoldout)
void AddToSection (string sectionName, params string[] properties)
void Hide (params string[] properties)
Call in OnEnable with one or more property names to hide them from the inspector.
void Draw (string property, Action< SerializedProperty > drawer)
Call in OnInit to specify a custom drawer for a single property. Whenever the property is drawn, it will use the provided property drawer instead of the default one.
void Draw (string property, string withExtra0, Action< SerializedProperty, SerializedProperty > drawer)
Call in OnInit to specify a custom drawer for a single property. Include an extra property that gets lumped in with the primary property. The extra property is not drawn normally, and is instead grouped in with the primary property. Can be used in situations where a collection of properties need to be drawn together.
void Draw (string property, string withExtra0, string withExtra1, Action< SerializedProperty, SerializedProperty, SerializedProperty > drawer)
void Draw (string property, string withExtra0, string withExtra1, string withExtra2, Action< SerializedProperty, SerializedProperty, SerializedProperty, SerializedProperty > drawer)
void Draw (string property, string withExtra0, string withExtra1, string withExtra2, string withExtra3, Action< SerializedProperty, SerializedProperty, SerializedProperty, SerializedProperty, SerializedProperty > drawer)
bool IsInSection (string property)
Indicates if the property in the serializedObject has been assigned to a section.
bool IsHidden (string property)
Indicates if the property in the serializedObject needs to be hidden. Hidden properties are typically drawn in a custom way so they don't need to be drawn with the default methods.
void DrawFullInspector ()
Draws all the visible (non hidden)properties in the serialized object following this order: First all properties that has not been added to sections, in the order they appear in the Component. Then all the sections (indented and in foldouts) in the order they were created, with the internal properties ordered in the order the properties were added to the section.
void DrawSection (string sectionName)
Draws all the properties in the section in the order they were added.
Private Member Functions
Section GetOrCreateSection (string sectionName)
void DrawSection (Section section)
void DrawProperty (SerializedProperty property)
bool ValidateProperties (params string[] properties)
Private Attributes
SerializedObject _serializedObject
HashSet< string > _hiddenProperties = new HashSet<string>()
HashSet< string > _skipProperties = new HashSet<string>()
Dictionary< string, Action< SerializedProperty > > _customDrawers
Dictionary< string, Section > _sections
List< string > _orderedSections = new List<string>()
Detailed Description
A utility class for building custom editors with less work required.
Definition at line 32 of file EditorBase.cs.
Constructor & Destructor Documentation
EditorBase()
Oculus.Interaction.Editor.EditorBase.EditorBase (SerializedObject serializedObject)
Definition at line 59 of file EditorBase.cs.
        {
            _serializedObject = serializedObject;
        }
Member Function Documentation
AddToSection()
void Oculus.Interaction.Editor.EditorBase.AddToSection (string sectionName, params string[] properties)
Definition at line 99 of file EditorBase.cs.
        {
            if (properties.Length == 0
                || !ValidateProperties(properties))
            {
                return;
            }
            Section section = GetOrCreateSection(sectionName);
            foreach (var property in properties)
            {
                section.properties.Add(property);
                _skipProperties.Add(property);
            }
        }
CreateSection()
Section Oculus.Interaction.Editor.EditorBase.CreateSection (string sectionName, bool isFoldout)
Definition at line 76 of file EditorBase.cs.
        {
            if (_sections.TryGetValue(sectionName, out Section existingSection))
            {
                Debug.LogError($"Section {sectionName} already exists");
                return null;
            }
            Section section = new Section() { title = sectionName, isFoldout = isFoldout };
            _sections.Add(sectionName, section);
            _orderedSections.Add(sectionName);
            return section;
        }
CreateSections()
void Oculus.Interaction.Editor.EditorBase.CreateSections (Dictionary< string, string[]> sections, bool isFoldout)
Definition at line 90 of file EditorBase.cs.
        {
            foreach (var sectionData in sections)
            {
                CreateSection(sectionData.Key, isFoldout);
                AddToSection(sectionData.Key, sectionData.Value);
            }
        }
Draw() [1/5]
void Oculus.Interaction.Editor.EditorBase.Draw (string property, Action< SerializedProperty > drawer)
Call in OnInit to specify a custom drawer for a single property. Whenever the property is drawn, it will use the provided property drawer instead of the default one.
Definition at line 140 of file EditorBase.cs.
        {
            if (!ValidateProperties(property))
            {
                return;
            }
            _customDrawers.Add(property, drawer);
        }
Draw() [2/5]
void Oculus.Interaction.Editor.EditorBase.Draw (string property, string withExtra0, Action< SerializedProperty, SerializedProperty > drawer)
Call in OnInit to specify a custom drawer for a single property. Include an extra property that gets lumped in with the primary property. The extra property is not drawn normally, and is instead grouped in with the primary property. Can be used in situations where a collection of properties need to be drawn together.
Definition at line 155 of file EditorBase.cs.
        {
            if (!ValidateProperties(property, withExtra0))
            {
                return;
            }
            Hide(withExtra0);
            Draw(property, p =>
            {
                drawer(p,
                    _serializedObject.FindProperty(withExtra0));
            });
        }
References Oculus.Interaction.Editor.EditorBase.Draw(), and Oculus.Interaction.Editor.EditorBase.Hide().
Draw() [3/5]
void Oculus.Interaction.Editor.EditorBase.Draw (string property, string withExtra0, string withExtra1, Action< SerializedProperty, SerializedProperty, SerializedProperty > drawer)
Definition at line 172 of file EditorBase.cs.
        {
            if (!ValidateProperties(property, withExtra0, withExtra1))
            {
                return;
            }
            Hide(withExtra0);
            Hide(withExtra1);
            Draw(property, p =>
            {
                drawer(p,
                    _serializedObject.FindProperty(withExtra0),
                    _serializedObject.FindProperty(withExtra1));
            });
        }
Draw() [4/5]
void Oculus.Interaction.Editor.EditorBase.Draw (string property, string withExtra0, string withExtra1, string withExtra2, Action< SerializedProperty, SerializedProperty, SerializedProperty, SerializedProperty > drawer)
Definition at line 192 of file EditorBase.cs.
        {
            if (!ValidateProperties(property, withExtra0, withExtra1, withExtra2))
            {
                return;
            }
            Hide(withExtra0);
            Hide(withExtra1);
            Hide(withExtra2);
            Draw(property, p =>
            {
                drawer(p,
                    _serializedObject.FindProperty(withExtra0),
                    _serializedObject.FindProperty(withExtra1),
                    _serializedObject.FindProperty(withExtra2));
            });
        }
Draw() [5/5]
void Oculus.Interaction.Editor.EditorBase.Draw (string property, string withExtra0, string withExtra1, string withExtra2, string withExtra3, Action< SerializedProperty, SerializedProperty, SerializedProperty, SerializedProperty, SerializedProperty > drawer)
Definition at line 216 of file EditorBase.cs.
        {
            if (!ValidateProperties(property, withExtra0, withExtra1, withExtra2, withExtra3))
            {
                return;
            }
            Hide(withExtra0);
            Hide(withExtra1);
            Hide(withExtra2);
            Hide(withExtra3);
            Draw(property, p =>
            {
                drawer(p,
                    _serializedObject.FindProperty(withExtra0),
                    _serializedObject.FindProperty(withExtra1),
                    _serializedObject.FindProperty(withExtra2),
                    _serializedObject.FindProperty(withExtra3));
            });
        }
DrawFullInspector()
void Oculus.Interaction.Editor.EditorBase.DrawFullInspector ()
Draws all the visible (non hidden)properties in the serialized object following this order: First all properties that has not been added to sections, in the order they appear in the Component. Then all the sections (indented and in foldouts) in the order they were created, with the internal properties ordered in the order the properties were added to the section.
If a special property drawer was specified it will use it when drawing said property.
If a property was hidden, it will not present it in any section.
Definition at line 285 of file EditorBase.cs.
        {
            SerializedProperty it = _serializedObject.GetIterator();
            it.NextVisible(enterChildren: true);
            //Draw script header
            EditorGUI.BeginDisabledGroup(true);
            EditorGUILayout.PropertyField(it);
            EditorGUI.EndDisabledGroup();
            EditorGUI.BeginChangeCheck();
            while (it.NextVisible(enterChildren: false))
            {
                //Don't draw skip properties in this pass, we will draw them after everything else
                if (IsInSection(it.name))
                {
                    continue;
                }
                DrawProperty(it);
            }
            foreach (string sectionKey in _orderedSections)
            {
                DrawSection(sectionKey);
            }
            _serializedObject.ApplyModifiedProperties();
        }
References Oculus.Interaction.Editor.EditorBase.DrawSection(), and Oculus.Interaction.Editor.EditorBase.IsInSection().
DrawProperty()
void Oculus.Interaction.Editor.EditorBase.DrawProperty (SerializedProperty property) private
Definition at line 355 of file EditorBase.cs.
        {
            try
            {
                //Don't draw hidden properties
                if (IsHidden(property.name))
                {
                    return;
                }
                //Then draw the property itself, using a custom drawer if needed
                Action<SerializedProperty> customDrawer;
                if (_customDrawers.TryGetValue(property.name, out customDrawer))
                {
                    customDrawer(property);
                }
                else
                {
                    EditorGUILayout.PropertyField(property, includeChildren: true);
                }
            }
            catch (Exception e)
            {
                Debug.LogError($"Error drawing property {e.Message}");
            }
        }
DrawSection() [1/2]
void Oculus.Interaction.Editor.EditorBase.DrawSection (Section section) private
Definition at line 327 of file EditorBase.cs.
        {
            if (!section.HasSomethingToDraw())
            {
                return;
            }
            if (section.isFoldout)
            {
                section.foldout = EditorGUILayout.Foldout(section.foldout, section.title);
                if (!section.foldout)
                {
                    return;
                }
                EditorGUI.indentLevel++;
            }
            foreach (string prop in section.properties)
            {
                DrawProperty(_serializedObject.FindProperty(prop));
            }
            if (section.isFoldout)
            {
                EditorGUI.indentLevel--;
            }
        }
DrawSection() [2/2]
void Oculus.Interaction.Editor.EditorBase.DrawSection (string sectionName)
Draws all the properties in the section in the order they were added.
Parameters
sectionName The name of the section
Definition at line 321 of file EditorBase.cs.
        {
            Section section = _sections[sectionName];
            DrawSection(section);
        }
References Oculus.Interaction.Editor.EditorBase.DrawSection().
GetOrCreateSection()
Section Oculus.Interaction.Editor.EditorBase.GetOrCreateSection (string sectionName) private
Definition at line 65 of file EditorBase.cs.
        {
            if (_sections.TryGetValue(sectionName, out Section existingSection))
            {
                return existingSection;
            }
            Section section = CreateSection(sectionName, false);
            return section;
        }
Hide()
void Oculus.Interaction.Editor.EditorBase.Hide (params string[] properties)
Call in OnEnable with one or more property names to hide them from the inspector.
This is preferable to using [HideInInspector] because it still allows the property to be viewed when using the Inspector debug mode.
Definition at line 125 of file EditorBase.cs.
        {
            Assert.IsTrue(properties.Length > 0, "Should always hide at least one property.");
            if (!ValidateProperties(properties))
            {
                return;
            }
            _hiddenProperties.UnionWith(properties);
        }
IsHidden()
bool Oculus.Interaction.Editor.EditorBase.IsHidden (string property)
Indicates if the property in the serializedObject needs to be hidden. Hidden properties are typically drawn in a custom way so they don't need to be drawn with the default methods.
Parameters
property The name of the property in the serialized object
Returns
True if the property has been hidden
Definition at line 266 of file EditorBase.cs.
        {
            return _hiddenProperties.Contains(property);
        }
IsInSection()
bool Oculus.Interaction.Editor.EditorBase.IsInSection (string property)
Indicates if the property in the serializedObject has been assigned to a section.
Parameters
property The name of the property in the serialized object
Returns
True if the property has been added to a section
Definition at line 253 of file EditorBase.cs.
        {
            return _skipProperties.Contains(property);
        }
ValidateProperties()
bool Oculus.Interaction.Editor.EditorBase.ValidateProperties (params string[] properties) private
Definition at line 382 of file EditorBase.cs.
        {
            foreach (var property in properties)
            {
                if (_serializedObject.FindProperty(property) == null)
                {
                    Debug.LogWarning(
                        $"Could not find property {property}, maybe it was deleted or renamed?");
                    return false;
                }
            }
            return true;
        }
Member Data Documentation
_customDrawers
Dictionary<string, Action<SerializedProperty> > Oculus.Interaction.Editor.EditorBase._customDrawers private
Initial value:
=
            new Dictionary<string, Action<SerializedProperty>>()
Definition at line 39 of file EditorBase.cs.
_hiddenProperties
HashSet<string> Oculus.Interaction.Editor.EditorBase._hiddenProperties = new HashSet<string>() private
Definition at line 36 of file EditorBase.cs.
_orderedSections
List<string> Oculus.Interaction.Editor.EditorBase._orderedSections = new List<string>() private
Definition at line 44 of file EditorBase.cs.
_sections
Dictionary<string, Section> Oculus.Interaction.Editor.EditorBase._sections private
Initial value:
=
            new Dictionary<string, Section>()
Definition at line 42 of file EditorBase.cs.
_serializedObject
SerializedObject Oculus.Interaction.Editor.EditorBase._serializedObject private
Definition at line 34 of file EditorBase.cs.
_skipProperties
HashSet<string> Oculus.Interaction.Editor.EditorBase._skipProperties = new HashSet<string>() private
Definition at line 37 of file EditorBase.cs.
The documentation for this class was generated from the following file:
Assets/Oculus/Interaction/Editor/EditorBase.cs