VR_Test: Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults > Class Template Reference
Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults > Class Template Reference abstract
Abstract class for all voice requests.
Public Member Functions
VoiceRequest (TOptions newOptions, TEvents newEvents)
Constructor class for voice requests.
virtual void Send ()
Public request to transmit data.
virtual void Cancel (string reason=WitConstants.CANCEL_MESSAGE_DEFAULT)
Cancel the request immediately.
Protected Member Functions
virtual void OnInit ()
Call after initialization.
virtual void SetState (VoiceRequestState newState)
Apply the voice request state.
void SetDownloadProgress (float newProgress)
Set current request download progress.
void SetUploadProgress (float newProgress)
Set current request upload progress.
void RaiseEvent (TUnityEvent requestEvent)
Raises a voice request event.
void Log (string log, bool warning=false)
Internal method for.
void LogW (string log)
virtual void AppendLogData (StringBuilder log, bool warning)
Append request specific data to log.
virtual string GetSendError ()
Internal way to determine send error.
virtual void OnSend ()
Call after transmission begins.
void HandleSend ()
Child class send implementation Call HandleFailure, HandleCancel from this class.
TResults GetResultsWithMessage (string newMessage)
Returns an empty result object with a specific message.
virtual void HandleFailure (string error)
Method for handling failure with only an error string.
virtual void HandleFailure (TResults results)
Method for handling failure with a full result object.
virtual void OnFailed ()
Call after failure state set.
virtual void HandleSuccess (TResults results)
Method for handling success with a full result object.
virtual void OnSuccess ()
Call after success state set.
void HandleCancel ()
Handle cancelation in subclass.
virtual void OnCancel ()
Call after cancellation state set.
virtual void OnComplete ()
Call after failure, success or cancellation.
Properties
VoiceRequestState State = (VoiceRequestState) (-1) [get, private set]
The states of a voice request.
bool IsActive [get]
Active if not currently canceled, failed or successful.
float DownloadProgress = 0f [get, private set]
Download progress of the current request transmission if available.
float UploadProgress = 0f [get, private set]
Upload progress of the current request transmission if available.
TOptions Options [get, private set]
Options sent as the request parameters.
TEvents Events [get, private set]
Events specific to this voice request.
TResults Results [get, protected set]
Results returned from the request.
bool CanSend [get]
Whether request can currently transmit data.
Properties inherited from Meta.Voice.IVoiceRequest< TUnityEvent, TOptions, TEvents, TResults >
Detailed Description
Abstract class for all voice requests.
Template Parameters
TRequest The type of request to be returned in event callbacks
TOptions The type containing all specific options to be passed to the end service.
TEvents The type containing all events of TSession to be called throughout the lifecycle of the request.
TResults The type containing all data that can be returned from the end service.
Type Constraints
TUnityEvent : UnityEventBase
TOptions : IVoiceRequestOptions
TEvents : VoiceRequestEvents<TUnityEvent>
TResults : IVoiceRequestResults
Definition at line 24 of file VoiceRequest.cs.
Constructor & Destructor Documentation
VoiceRequest()
Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.VoiceRequest (TOptions newOptions, TEvents newEvents)
Constructor class for voice requests.
Parameters
newOptions The request parameters to be used
newEvents The request events to be called throughout it's lifecycle
Definition at line 74 of file VoiceRequest.cs.
        {
            // Apply options if they exist, otherwise generate
            Options = newOptions != null ? newOptions : Activator.CreateInstance<TOptions>();
            // Apply events if they exist, otherwise generate
            Events = newEvents != null ? newEvents : Activator.CreateInstance<TEvents>();
            // Initialized
            SetState(VoiceRequestState.Initialized);
        }
References Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.Events, Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.Options, and Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.SetState().
Member Function Documentation
AppendLogData()
virtual void Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.AppendLogData (StringBuilder log, bool warning) protected virtual
Append request specific data to log.
Parameters
log Building log
warning True if this is a warning log
Reimplemented in Meta.Voice.NLPRequest< TUnityEvent, TOptions, TEvents, TResults >, and Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.
Definition at line 203 of file VoiceRequest.cs.
        {
            #if UNITY_EDITOR
            // Append request id
            log.AppendLine($"Request Id: {Options?.RequestId}");
            #endif
            // Append request state
            log.AppendLine($"Request State: {State}");
        }
Cancel()
virtual void Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.Cancel (string reason = WitConstants::CANCEL_MESSAGE_DEFAULT) virtual
Cancel the request immediately.
Implements Meta.Voice.IVoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.
Reimplemented in Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.
Definition at line 349 of file VoiceRequest.cs.
        {
            // Ignore if cannot cancel
            if (State != VoiceRequestState.Initialized && State != VoiceRequestState.Transmitting)
            {
                LogW($"Request Cancel Ignored\nReason: Request is already complete");
                return;
            }
            // Set cancellation reason
            Results = GetResultsWithMessage(reason);
            // Set cancellation state
            SetState(VoiceRequestState.Canceled);
        }
References Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.GetResultsWithMessage(), Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.Results, Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.SetState(), and Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.State.
GetResultsWithMessage()
TResults Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.GetResultsWithMessage (string newMessage) abstract protected
Returns an empty result object with a specific message.
Parameters
newMessage The message to be set on the results
GetSendError()
virtual string Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.GetSendError () protected virtual
Internal way to determine send error.
Reimplemented in Meta.Voice.NLPRequest< TUnityEvent, TOptions, TEvents, TResults >.
Definition at line 218 of file VoiceRequest.cs.
        {
            // Cannot send if not initialized
            if (State != VoiceRequestState.Initialized)
            {
                return $"Cannot send request in '{State}' state.";
            }
            // Cannot send without valid request id
            if (string.IsNullOrEmpty(Options?.RequestId))
            {
                return $"Cannot send request without a request id.";
            }
            // Send allowed
            return string.Empty;
        }
References Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.Options, and Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.State.
HandleFailure() [1/2]
virtual void Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.HandleFailure (string error) protected virtual
Method for handling failure with only an error string.
Parameters
error The error to be returned
HandleFailure() [2/2]
virtual void Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.HandleFailure (TResults results) protected virtual
Method for handling failure with a full result object.
Parameters
error The error to be returned
Definition at line 289 of file VoiceRequest.cs.
        {
            // Ignore if not in correct state
            if (State != VoiceRequestState.Initialized && State != VoiceRequestState.Transmitting)
            {
                LogW($"Request Failure Ignored\nReason: Request is already complete");
                return;
            }
            // Apply results with error
            Results = results;
            // Set failure state
            SetState(VoiceRequestState.Failed);
        }
References Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.Results, Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.SetState(), and Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.State.
HandleSuccess()
virtual void Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.HandleSuccess (TResults results) protected virtual
Method for handling success with a full result object.
Parameters
error The error to be returned
Definition at line 317 of file VoiceRequest.cs.
        {
            // Ignore if not in correct state
            if (State != VoiceRequestState.Initialized && State != VoiceRequestState.Transmitting)
            {
                LogW($"Request Success Ignored\nReason: Request is already complete");
                return;
            }
            // Generate results if needed
            if (results == null)
            {
                results = Activator.CreateInstance<TResults>();
            }
            // Apply results
            Results = results;
            // Set success state
            SetState(VoiceRequestState.Successful);
        }
References Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.Results, Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.SetState(), and Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.State.
Log()
void Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.Log (string log, bool warning = false) protected
Internal method for.
Definition at line 174 of file VoiceRequest.cs.
        {
            // Start log
            StringBuilder requestLog = new StringBuilder();
            // Append type of request
            requestLog.Append($"{GetType().Name} ");
            // Append sent log
            requestLog.AppendLine(log);
            // Append any request specific data
            AppendLogData(requestLog, warning);
            // Log warning
            if (warning)
            {
                VLog.W(requestLog);
            }
            // Log debug
            else
            {
                VLog.D(requestLog);
            }
        }
References Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.AppendLogData(), Meta.WitAi.VLog.D(), and Meta.WitAi.VLog.W().
OnCancel()
virtual void Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.OnCancel () protected virtual
Call after cancellation state set.
Definition at line 373 of file VoiceRequest.cs.
        {
            // Log & callbacks
            Log($"Request Cancelled\nReason: {Results?.Message}");
            RaiseEvent(Events?.OnCancel);
        }
References Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.Events, Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.Log(), Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.OnCancel(), and Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.RaiseEvent().
OnComplete()
virtual void Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.OnComplete () protected virtual
Call after failure, success or cancellation.
Definition at line 383 of file VoiceRequest.cs.
        {
            RaiseEvent(Events?.OnComplete);
        }
References Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.Events, Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.OnComplete(), and Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.RaiseEvent().
OnFailed()
virtual void Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.OnFailed () protected virtual
Call after failure state set.
Definition at line 307 of file VoiceRequest.cs.
        {
            LogW($"Request Failed\nError: {Results?.Message}");
            RaiseEvent(Events?.OnFailed);
        }
References Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.Events, Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.OnFailed(), and Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.RaiseEvent().
OnInit()
virtual void Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.OnInit () protected virtual
Call after initialization.
Reimplemented in Meta.Voice.NLPAudioRequest< TUnityEvent, TOptions, TEvents, TResults >.
Definition at line 87 of file VoiceRequest.cs.
        {
            RaiseEvent(Events?.OnInit);
            SetUploadProgress(0f);
            SetDownloadProgress(0f);
        }
References Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.Events, Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.OnInit(), Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.RaiseEvent(), Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.SetDownloadProgress(), and Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.SetUploadProgress().
OnSend()
virtual void Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.OnSend () protected virtual
Call after transmission begins.
Definition at line 260 of file VoiceRequest.cs.
        {
            // Call send event
            Log($"Request Transmitting");
            RaiseEvent(Events?.OnSend);
        }
References Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.Events, Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.Log(), Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.OnSend(), and Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.RaiseEvent().
OnSuccess()
virtual void Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.OnSuccess () protected virtual
Call after success state set.
Reimplemented in Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.
Definition at line 340 of file VoiceRequest.cs.
        {
            Log($"Request Success\nResults: {Results != null}");
            RaiseEvent(Events?.OnSuccess);
        }
References Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.Events, Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.Log(), Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.OnSuccess(), and Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.RaiseEvent().
RaiseEvent()
void Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.RaiseEvent (TUnityEvent requestEvent) abstract protected
Raises a voice request event.
Parameters
requestEvent Event to be performed
Send()
virtual void Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.Send () virtual
Public request to transmit data.
Implements Meta.Voice.IVoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.
Reimplemented in Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.
Definition at line 236 of file VoiceRequest.cs.
        {
            // Warn & ignore
            if (State != VoiceRequestState.Initialized)
            {
                LogW($"Request Send Ignored\nReason: Invalid state");
                return;
            }
            // Fail if cannot send
            string sendError = GetSendError();
            if (!string.IsNullOrEmpty(sendError))
            {
                HandleFailure(sendError);
                return;
            }
            // Set to transmitting state
            SetState(VoiceRequestState.Transmitting);
        }
References Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.GetSendError(), Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.HandleFailure(), Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.SetState(), and Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.State.
SetDownloadProgress()
void Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.SetDownloadProgress (float newProgress) protected
Set current request download progress.
Parameters
newProgress New progress value
Definition at line 137 of file VoiceRequest.cs.
        {
            // Ignore same progress
            if (DownloadProgress.Equals(newProgress))
            {
                return;
            }
            // Set progress & update event
            DownloadProgress = newProgress;
            RaiseEvent(Events?.OnDownloadProgressChange);
        }
References Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.DownloadProgress, Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.Events, and Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.RaiseEvent().
SetState()
virtual void Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.SetState (VoiceRequestState newState) protected virtual
Apply the voice request state.
Reimplemented in Meta.Voice.NLPRequest< TUnityEvent, TOptions, TEvents, TResults >.
Definition at line 96 of file VoiceRequest.cs.
        {
            // Ignore same state
            if (State == newState)
            {
                return;
            }
            // Set state & update event
            State = newState;
            RaiseEvent(Events?.OnStateChange);
            // Perform state specific event
            switch (State)
            {
                case VoiceRequestState.Initialized:
                    OnInit();
                    break;
                case VoiceRequestState.Transmitting:
                    OnSend();
                    HandleSend();
                    break;
                case VoiceRequestState.Canceled:
                    HandleCancel();
                    OnCancel();
                    OnComplete();
                    break;
                case VoiceRequestState.Failed:
                    OnFailed();
                    OnComplete();
                    break;
                case VoiceRequestState.Successful:
                    OnSuccess();
                    OnComplete();
                    break;
            }
        }
References Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.Events, Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.HandleCancel(), Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.HandleSend(), Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.OnCancel(), Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.OnComplete(), Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.OnFailed(), Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.OnInit(), Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.OnSend(), Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.OnSuccess(), Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.RaiseEvent(), and Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.State.
SetUploadProgress()
void Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.SetUploadProgress (float newProgress) protected
Set current request upload progress.
Parameters
newProgress New progress value
Definition at line 153 of file VoiceRequest.cs.
        {
            // Ignore same progress
            if (UploadProgress.Equals(newProgress))
            {
                return;
            }
            // Set progress & update event
            UploadProgress = newProgress;
            RaiseEvent(Events?.OnUploadProgressChange);
        }
References Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.Events, Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.RaiseEvent(), and Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.UploadProgress.
Property Documentation
CanSend
bool Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.CanSend get
Whether request can currently transmit data.
Implements Meta.Voice.IVoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.
Definition at line 66 of file VoiceRequest.cs.
DownloadProgress
float Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.DownloadProgress = 0f get private set
Download progress of the current request transmission if available.
Implements Meta.Voice.IVoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.
Definition at line 43 of file VoiceRequest.cs.
{ get; private set; } = 0f;
Events
TEvents Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.Events get private set
Events specific to this voice request.
Implements Meta.Voice.IVoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.
Definition at line 57 of file VoiceRequest.cs.
{ get; private set; }
IsActive
bool Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.IsActive get
Active if not currently canceled, failed or successful.
Definition at line 38 of file VoiceRequest.cs.
Options
TOptions Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.Options get private set
Options sent as the request parameters.
Implements Meta.Voice.IVoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.
Definition at line 53 of file VoiceRequest.cs.
{ get; private set; }
Results
TResults Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.Results get protected set
Results returned from the request.
Implements Meta.Voice.IVoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.
Definition at line 61 of file VoiceRequest.cs.
{ get; protected set; }
State
VoiceRequestState Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.State = (VoiceRequestState) (-1) get private set
The states of a voice request.
Implements Meta.Voice.IVoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.
Definition at line 34 of file VoiceRequest.cs.
{ get; private set; } = (VoiceRequestState) (-1);
UploadProgress
float Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.UploadProgress = 0f get private set
Upload progress of the current request transmission if available.
Implements Meta.Voice.IVoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.
Definition at line 48 of file VoiceRequest.cs.
{ get; private set; } = 0f;
The documentation for this class was generated from the following file:
Assets/Oculus/Voice/Lib/Wit.ai/Lib/Wit/Runtime/Requests/VoiceRequest.cs