VR_Test: Meta.WitAi.TTS.Integrations.TTSWit Class Reference
Meta.WitAi.TTS.Integrations.TTSWit Class Reference
Public Member Functions
override string GetInvalidError ()
Returns error if invalid.
string IsTextValid (string textToSpeak)
Method for determining if text to speak is valid.
void RequestStreamFromWeb (TTSClipData clipData)
Method for performing a web load request.
bool CancelWebStream (TTSClipData clipData)
Cancel web stream.
void RequestDownloadFromWeb (TTSClipData clipData, string downloadPath)
Method for performing a web load request.
bool CancelWebDownload (TTSClipData clipData, string downloadPath)
Method for cancelling a running load request.
Dictionary< string, string > EncodeVoiceSettings (TTSVoiceSettings voiceSettings)
Encode voice data to be transmitted.
Public Member Functions inherited from Meta.WitAi.TTS.TTSService
string GetFinalText (string textToSpeak, TTSVoiceSettings voiceSettings)
Gets the text to be spoken after applying all relevant voice settings.
virtual string GetClipID (string textToSpeak, TTSVoiceSettings voiceSettings)
Obtain unique id for clip data.
TTSClipData Load (string textToSpeak, Action< TTSClipData, string > onStreamReady=null)
TTSClipData Load (string textToSpeak, string presetVoiceId, Action< TTSClipData, string > onStreamReady=null)
TTSClipData Load (string textToSpeak, string presetVoiceId, TTSDiskCacheSettings diskCacheSettings, Action< TTSClipData, string > onStreamReady=null)
TTSClipData Load (string textToSpeak, TTSVoiceSettings voiceSettings, TTSDiskCacheSettings diskCacheSettings, Action< TTSClipData, string > onStreamReady=null)
virtual TTSClipData Load (string textToSpeak, string clipID, TTSVoiceSettings voiceSettings, TTSDiskCacheSettings diskCacheSettings, Action< TTSClipData, string > onStreamReady)
Perform a request for a TTS audio clip.
void UnloadAll ()
Unload all audio clips from the runtime cache.
void Unload (TTSClipData clipData)
Force a runtime cache unload.
TTSClipData GetRuntimeCachedClip (string clipID)
Obtain a clip from the runtime cache, if applicable.
TTSClipData[] GetAllRuntimeCachedClips ()
Obtain all clips from the runtime cache, if applicable.
bool ShouldCacheToDisk (TTSClipData clipData)
Whether a specific clip should be cached.
string GetDiskCachePath (string textToSpeak, string clipID, TTSVoiceSettings voiceSettings, TTSDiskCacheSettings diskCacheSettings)
Get disk cache.
TTSClipData DownloadToDiskCache (string textToSpeak, Action< TTSClipData, string, string > onDownloadComplete=null)
TTSClipData DownloadToDiskCache (string textToSpeak, string presetVoiceId, Action< TTSClipData, string, string > onDownloadComplete=null)
TTSClipData DownloadToDiskCache (string textToSpeak, string presetVoiceId, TTSDiskCacheSettings diskCacheSettings, Action< TTSClipData, string, string > onDownloadComplete=null)
TTSClipData DownloadToDiskCache (string textToSpeak, TTSVoiceSettings voiceSettings, TTSDiskCacheSettings diskCacheSettings, Action< TTSClipData, string, string > onDownloadComplete=null)
TTSClipData DownloadToDiskCache (string textToSpeak, string clipID, TTSVoiceSettings voiceSettings, TTSDiskCacheSettings diskCacheSettings, Action< TTSClipData, string, string > onDownloadComplete=null)
Perform a download for a TTS audio clip.
TTSVoiceSettings[] GetAllPresetVoiceSettings ()
Return all preset voice settings.
TTSVoiceSettings GetPresetVoiceSettings (string presetVoiceId)
Return preset voice settings for a specific id.
Public Attributes
TTSWitRequestSettings RequestSettings
Protected Member Functions
override AudioType GetAudioType ()
Protected Member Functions inherited from Meta.WitAi.TTS.TTSService
virtual void Awake ()
virtual void Start ()
virtual void OnEnable ()
virtual void OnDisable ()
virtual void AddDelegates ()
virtual void RemoveDelegates ()
virtual void OnDestroy ()
virtual string GetClipLog (string logMessage, TTSClipData clipData)
Get clip log data.
virtual void AppendFinalText (StringBuilder builder, string textToSpeak, TTSVoiceSettings voiceSettings)
virtual TTSClipData CreateClipData (string textToSpeak, string clipID, TTSVoiceSettings voiceSettings, TTSDiskCacheSettings diskCacheSettings)
Creates new clip data or returns existing cached clip.
virtual IAudioClipStream CreateClipStream ()
virtual void SetClipLoadState (TTSClipData clipData, TTSClipLoadState loadState)
virtual void OnUnloadBegin (TTSClipData clipData)
Perform clip unload.
virtual void OnRuntimeClipAdded (TTSClipData clipData)
Called when runtime cache adds a clip.
virtual void OnRuntimeClipRemoved (TTSClipData clipData)
Called when runtime cache unloads a clip.
virtual void DownloadToDiskCache (TTSClipData clipData, Action< TTSClipData, string, string > onDownloadComplete)
Properties
override ITTSVoiceProvider VoiceProvider [get]
override ITTSWebHandler WebHandler [get]
override ITTSRuntimeCacheHandler RuntimeCacheHandler [get]
override ITTSDiskCacheHandler DiskCacheHandler [get]
TTSWebRequestEvents WebRequestEvents [get]
Any web request performs this event.
WitConfiguration Configuration [get]
TTSStreamEvents WebStreamEvents = new TTSStreamEvents() [get, set]
Streaming events.
TTSDownloadEvents WebDownloadEvents = new TTSDownloadEvents() [get, set]
Download events.
TTSWitVoiceSettings[] PresetWitVoiceSettings [get]
TTSVoiceSettings[] PresetVoiceSettings [get]
Returns all preset voice settings.
TTSVoiceSettings VoiceDefaultSettings [get]
Returns preset voice data if no voice data is selected. Useful for menu ai, etc.
Properties inherited from Meta.WitAi.TTS.TTSService
static TTSService Instance [get]
IAudioSystem AudioSystem [get, set]
Audio system to be used for streaming & playback.
ITTSRuntimeCacheHandler RuntimeCacheHandler [get]
ITTSDiskCacheHandler DiskCacheHandler [get]
ITTSWebHandler WebHandler [get]
ITTSVoiceProvider VoiceProvider [get]
TTSServiceEvents Events [get]
Properties inherited from Meta.WitAi.TTS.Interfaces.ITTSVoiceProvider
Properties inherited from Meta.WitAi.TTS.Interfaces.ITTSWebHandler
Properties inherited from Meta.WitAi.Interfaces.IWitConfigurationProvider
Private Member Functions
WitTTSVRequest GetTtsRequest (TTSClipData clipData)
void OnRequestProgressUpdated (TTSClipData clipData, float newProgress)
void OnRequestFirstResponse (TTSClipData clipData)
string IsRequestValid (TTSClipData clipData, WitConfiguration configuration)
Static Private Member Functions
static FieldInfo[] GetVoiceSettingsFields (TTSVoiceSettings voiceSettings)
Private Attributes
ITTSRuntimeCacheHandler _runtimeCache
ITTSDiskCacheHandler _diskCache
Dictionary< string, VRequest > _webStreams = new Dictionary<string, VRequest>()
Dictionary< string, WitVRequest > _webDownloads = new Dictionary<string, WitVRequest>()
TTSWitVoiceSettings[] _presetVoiceSettings
Static Private Attributes
const string VOICE_KEY = "voice"
const string STYLE_KEY = "style"
static readonly Dictionary< Type, FieldInfo[]> _settingsFields = new Dictionary<Type, FieldInfo[]>()
Additional Inherited Members
Events inherited from Meta.WitAi.TTS.TTSService
static Action< TTSService > OnServiceStart
Static event called whenever any TTSService.Awake is called.
static Action< TTSService > OnServiceDestroy
Static event called whenever any TTSService.OnDestroy is called.
Detailed Description
Definition at line 80 of file TTSWit.cs.
Member Function Documentation
CancelWebDownload()
bool Meta.WitAi.TTS.Integrations.TTSWit.CancelWebDownload (TTSClipData clipData, string downloadPath)
Method for cancelling a running load request.
Parameters
clipData Clip request data
Implements Meta.WitAi.TTS.Interfaces.ITTSWebHandler.
Definition at line 356 of file TTSWit.cs.
        {
            // Ignore if not performing
            if (!_webDownloads.ContainsKey(clipData.clipID))
            {
                return false;
            }
            // Get request
            WitVRequest request = _webDownloads[clipData.clipID];
            _webDownloads.Remove(clipData.clipID);
            // Destroy immediately
            request?.Cancel();
            request = null;
            // Download cancelled
            WebDownloadEvents?.OnDownloadCancel?.Invoke(clipData, downloadPath);
            WebRequestEvents?.OnRequestCancel?.Invoke(clipData);
            // Success
            return true;
        }
CancelWebStream()
bool Meta.WitAi.TTS.Integrations.TTSWit.CancelWebStream (TTSClipData clipData)
Cancel web stream.
Parameters
clipID Unique clip id
Implements Meta.WitAi.TTS.Interfaces.ITTSWebHandler.
Definition at line 274 of file TTSWit.cs.
        {
            // Ignore without
            if (!_webStreams.ContainsKey(clipData.clipID))
            {
                return false;
            }
            // Get request
            VRequest request = _webStreams[clipData.clipID];
            _webStreams.Remove(clipData.clipID);
            // Destroy immediately
            request?.Cancel();
            request = null;
            // Call delegate
            WebStreamEvents?.OnStreamCancel?.Invoke(clipData);
            WebRequestEvents?.OnRequestCancel?.Invoke(clipData);
            // Success
            return true;
        }
EncodeVoiceSettings()
Dictionary< string, string > Meta.WitAi.TTS.Integrations.TTSWit.EncodeVoiceSettings (TTSVoiceSettings voiceSettings)
Encode voice data to be transmitted.
Parameters
voiceSettings The voice settings class
Returns
Returns a dictionary with all variables
Implements Meta.WitAi.TTS.Interfaces.ITTSVoiceProvider.
Definition at line 416 of file TTSWit.cs.
        {
            Dictionary<string, string> parameters = new Dictionary<string, string>();
            if (voiceSettings != null)
            {
                foreach (FieldInfo field in GetVoiceSettingsFields(voiceSettings))
                {
                    // Ensure field value exists
                    object fieldVal = field.GetValue(voiceSettings);
                    if (fieldVal != null)
                    {
                        // Clamp in between range
                        RangeAttribute range = field.GetCustomAttribute<RangeAttribute>();
                        if (range != null && field.FieldType == typeof(int))
{
                            int oldFloat = (int) fieldVal;
                            int newFloat = Mathf.Clamp(oldFloat, (int)range.min, (int)range.max);
                            if (oldFloat != newFloat)
{
                                fieldVal = newFloat;
                            }
                        }
                        // Apply
                        parameters[field.Name] = fieldVal.ToString();
                    }
                }
                // Set default if no voice is provided
                if (!parameters.ContainsKey(VOICE_KEY) || string.IsNullOrEmpty(parameters[VOICE_KEY]))
                {
                    parameters[VOICE_KEY] = TTSWitVoiceSettings.DEFAULT_VOICE;
                }
                // Set default if no style is given
                if (!parameters.ContainsKey(STYLE_KEY) || string.IsNullOrEmpty(parameters[STYLE_KEY]))
                {
                    parameters[STYLE_KEY] = TTSWitVoiceSettings.DEFAULT_STYLE;
                }
            }
            return parameters;
        }
References Meta.WitAi.TTS.Integrations.TTSWitVoiceSettings.DEFAULT_STYLE, and Meta.WitAi.TTS.Integrations.TTSWitVoiceSettings.DEFAULT_VOICE.
GetAudioType()
override AudioType Meta.WitAi.TTS.Integrations.TTSWit.GetAudioType () protected virtual
Reimplemented from Meta.WitAi.TTS.TTSService.
Definition at line 120 of file TTSWit.cs.
        {
            return WitTTSVRequest.GetAudioType(RequestSettings.audioType);
        }
GetInvalidError()
override string Meta.WitAi.TTS.Integrations.TTSWit.GetInvalidError () virtual
Returns error if invalid.
Reimplemented from Meta.WitAi.TTS.TTSService.
Definition at line 175 of file TTSWit.cs.
        {
            string invalidError = base.GetInvalidError();
            if (!string.IsNullOrEmpty(invalidError))
            {
                return invalidError;
            }
            if (RequestSettings.configuration == null)
            {
                return "No WitConfiguration Set";
            }
            if (string.IsNullOrEmpty(RequestSettings.configuration.GetClientAccessToken()))
            {
                return "No WitConfiguration Client Token";
            }
            return string.Empty;
        }
GetTtsRequest()
WitTTSVRequest Meta.WitAi.TTS.Integrations.TTSWit.GetTtsRequest (TTSClipData clipData) private
Definition at line 125 of file TTSWit.cs.
        {
            // Apply audio type
            clipData.audioType = GetAudioType();
            clipData.queryStream = RequestSettings.audioStream;
            // Return request
            return new WitTTSVRequest(RequestSettings.configuration, clipData.queryRequestId,
                clipData.textToSpeak, clipData.queryParameters,
                RequestSettings.audioType, clipData.queryStream,
                (progress) => OnRequestProgressUpdated(clipData, progress),
                () => OnRequestFirstResponse(clipData));
        }
GetVoiceSettingsFields()
static FieldInfo[] Meta.WitAi.TTS.Integrations.TTSWit.GetVoiceSettingsFields (TTSVoiceSettings voiceSettings) static private
Definition at line 459 of file TTSWit.cs.
        {
            // Return fields if already found
            Type settingsType = voiceSettings.GetType();
            if (_settingsFields.ContainsKey(settingsType))
            {
                return _settingsFields[settingsType];
            }
            // Get public/instance fields
            FieldInfo[] fields = settingsType.GetFields(BindingFlags.Public | BindingFlags.Instance);
            // Remove fields from TTSVoiceSettings
            Type baseType = typeof(TTSVoiceSettings);
            fields = fields.ToList().FindAll((field) => field.DeclaringType != baseType).ToArray();
            // Apply & return
            _settingsFields[settingsType] = fields;
            return fields;
        }
IsRequestValid()
string Meta.WitAi.TTS.Integrations.TTSWit.IsRequestValid (TTSClipData clipData, WitConfiguration configuration) private
Definition at line 480 of file TTSWit.cs.
        {
            // Invalid tts
            string invalidError = GetInvalidError();
            if (!string.IsNullOrEmpty(invalidError))
            {
                return invalidError;
            }
            // Invalid clip
            if (clipData == null)
            {
                return "No clip data provided";
            }
            // Success
            return string.Empty;
        }
IsTextValid()
string Meta.WitAi.TTS.Integrations.TTSWit.IsTextValid (string textToSpeak)
Method for determining if text to speak is valid.
Parameters
textToSpeak Text to be spoken by TTS
Returns
Invalid error
Implements Meta.WitAi.TTS.Interfaces.ITTSWebHandler.
OnRequestFirstResponse()
void Meta.WitAi.TTS.Integrations.TTSWit.OnRequestFirstResponse (TTSClipData clipData) private
Definition at line 149 of file TTSWit.cs.
        {
            if (clipData != null)
            {
                WebRequestEvents?.OnRequestFirstResponse?.Invoke(clipData);
            }
        }
OnRequestProgressUpdated()
void Meta.WitAi.TTS.Integrations.TTSWit.OnRequestProgressUpdated (TTSClipData clipData, float newProgress) private
Definition at line 140 of file TTSWit.cs.
        {
            if (clipData != null)
            {
                clipData.loadProgress = newProgress;
            }
        }
RequestDownloadFromWeb()
void Meta.WitAi.TTS.Integrations.TTSWit.RequestDownloadFromWeb (TTSClipData clipData, string downloadPath)
Method for performing a web load request.
Parameters
clipData Clip request data
downloadPath Path to save clip
Implements Meta.WitAi.TTS.Interfaces.ITTSWebHandler.
Definition at line 311 of file TTSWit.cs.
        {
            // Begin
            WebDownloadEvents?.OnDownloadBegin?.Invoke(clipData, downloadPath);
            // Ensure valid
            string validError = IsRequestValid(clipData, RequestSettings.configuration);
            if (!string.IsNullOrEmpty(validError))
            {
                WebDownloadEvents?.OnDownloadError?.Invoke(clipData, downloadPath, validError);
                return;
            }
            // Abort if already performing
            if (_webDownloads.ContainsKey(clipData.clipID))
            {
                CancelWebDownload(clipData, downloadPath);
            }
            // Begin request
            WebRequestEvents?.OnRequestBegin?.Invoke(clipData);
            // Request tts
            WitTTSVRequest request = GetTtsRequest(clipData);
            request.RequestDownload(downloadPath,
                (success, error) =>
                {
                    _webDownloads.Remove(clipData.clipID);
                    if (string.IsNullOrEmpty(error))
                    {
                        WebDownloadEvents?.OnDownloadSuccess?.Invoke(clipData, downloadPath);
                        WebRequestEvents?.OnRequestReady?.Invoke(clipData);
                    }
                    else
                    {
                        WebDownloadEvents?.OnDownloadError?.Invoke(clipData, downloadPath, error);
                        WebRequestEvents?.OnRequestError?.Invoke(clipData, error);
                    }
                    WebRequestEvents?.OnRequestComplete?.Invoke(clipData);
                });
            _webDownloads[clipData.clipID] = request;
        }
References Meta.WitAi.Requests.WitTTSVRequest.RequestDownload().
RequestStreamFromWeb()
void Meta.WitAi.TTS.Integrations.TTSWit.RequestStreamFromWeb (TTSClipData clipData)
Method for performing a web load request.
Parameters
clipData Clip request data
onStreamSetupComplete Stream setup complete: returns clip and error if applicable
Implements Meta.WitAi.TTS.Interfaces.ITTSWebHandler.
Definition at line 200 of file TTSWit.cs.
        {
            // Stream begin
            WebStreamEvents?.OnStreamBegin?.Invoke(clipData);
            // Check if valid
            string validError = IsRequestValid(clipData, RequestSettings.configuration);
            if (!string.IsNullOrEmpty(validError))
            {
                WebStreamEvents?.OnStreamError?.Invoke(clipData, validError);
                return;
            }
            // Ignore if already performing
            if (_webStreams.ContainsKey(clipData.clipID))
            {
                CancelWebStream(clipData);
            }
            // Begin request
            WebRequestEvents?.OnRequestBegin?.Invoke(clipData);
            // Whether to stream
            bool stream = Application.isPlaying && RequestSettings.audioStream;
            // Request tts
            WitTTSVRequest request = GetTtsRequest(clipData);
            request.RequestStream(clipData.clipStream,
                (clipStream, error) =>
                {
                    // Apply
                    _webStreams.Remove(clipData.clipID);
                    // Set new clip stream
                    clipData.clipStream = clipStream;
                    // Unloaded
                    if (clipData.loadState == TTSClipLoadState.Unloaded)
                    {
                        error = WitConstants.CANCEL_ERROR;
                        clipStream?.Unload();
                    }
                    // Error
                    if (!string.IsNullOrEmpty(error))
                    {
                        if (string.Equals(error, WitConstants.CANCEL_ERROR, StringComparison.CurrentCultureIgnoreCase))
{
                            WebStreamEvents?.OnStreamCancel?.Invoke(clipData);
                            WebRequestEvents?.OnRequestCancel?.Invoke(clipData);
                        }
                        else
{
                            WebStreamEvents?.OnStreamError?.Invoke(clipData, error);
                            WebRequestEvents?.OnRequestError?.Invoke(clipData, error);
                        }
                    }
                    // Success
                    else
                    {
                        WebStreamEvents?.OnStreamReady?.Invoke(clipData);
                        WebRequestEvents?.OnRequestReady?.Invoke(clipData);
                        if (!RequestSettings.audioStream || !WitTTSVRequest.CanStreamAudio(RequestSettings.audioType))
{
                            WebStreamEvents?.OnStreamComplete?.Invoke(clipData);
                            WebRequestEvents?.OnRequestComplete?.Invoke(clipData);
                        }
                    }
                });
            _webStreams[clipData.clipID] = request;
        }
References Meta.WitAi.TTS.Integrations.TTSWit.CancelWebStream(), Meta.WitAi.Requests.WitTTSVRequest.RequestStream(), Meta.WitAi.TTS.Integrations.TTSWit.WebRequestEvents, and Meta.WitAi.TTS.Integrations.TTSWit.WebStreamEvents.
Member Data Documentation
_diskCache
ITTSDiskCacheHandler Meta.WitAi.TTS.Integrations.TTSWit._diskCache private
Definition at line 112 of file TTSWit.cs.
_presetVoiceSettings
TTSWitVoiceSettings [] Meta.WitAi.TTS.Integrations.TTSWit._presetVoiceSettings private
Definition at line 387 of file TTSWit.cs.
_runtimeCache
ITTSRuntimeCacheHandler Meta.WitAi.TTS.Integrations.TTSWit._runtimeCache private
Definition at line 99 of file TTSWit.cs.
_settingsFields
readonly Dictionary<Type, FieldInfo[]> Meta.WitAi.TTS.Integrations.TTSWit._settingsFields = new Dictionary<Type, FieldInfo[]>() static private
Definition at line 458 of file TTSWit.cs.
_webDownloads
Dictionary<string, WitVRequest> Meta.WitAi.TTS.Integrations.TTSWit._webDownloads = new Dictionary<string, WitVRequest>() private
Definition at line 304 of file TTSWit.cs.
_webStreams
Dictionary<string, VRequest> Meta.WitAi.TTS.Integrations.TTSWit._webStreams = new Dictionary<string, VRequest>() private
Definition at line 172 of file TTSWit.cs.
RequestSettings
TTSWitRequestSettings Meta.WitAi.TTS.Integrations.TTSWit.RequestSettings
Initial value:
= new TTSWitRequestSettings
        {
            audioType = TTSWitAudioType.PCM,
            audioStream = true,
        }
Definition at line 162 of file TTSWit.cs.
        {
            audioType = TTSWitAudioType.PCM,
            audioStream = true,
        };
STYLE_KEY
const string Meta.WitAi.TTS.Integrations.TTSWit.STYLE_KEY = "style" static private
Definition at line 415 of file TTSWit.cs.
VOICE_KEY
const string Meta.WitAi.TTS.Integrations.TTSWit.VOICE_KEY = "voice" static private
Definition at line 414 of file TTSWit.cs.
Property Documentation
Configuration
WitConfiguration Meta.WitAi.TTS.Integrations.TTSWit.Configuration get
Implements Meta.WitAi.Interfaces.IWitConfigurationProvider.
Definition at line 117 of file TTSWit.cs.
DiskCacheHandler
override ITTSDiskCacheHandler Meta.WitAi.TTS.Integrations.TTSWit.DiskCacheHandler get
Definition at line 101 of file TTSWit.cs.
        {
            get
            {
                if (_diskCache == null)
                {
                    _diskCache = gameObject.GetComponent<ITTSDiskCacheHandler>();
                }
                return _diskCache;
            }
        }
PresetVoiceSettings
TTSVoiceSettings [] Meta.WitAi.TTS.Integrations.TTSWit.PresetVoiceSettings get
Returns all preset voice settings.
Implements Meta.WitAi.TTS.Interfaces.ITTSVoiceProvider.
Definition at line 391 of file TTSWit.cs.
        {
            get
            {
                if (_presetVoiceSettings == null)
                {
                    _presetVoiceSettings = new TTSWitVoiceSettings[] { };
                }
                return _presetVoiceSettings;
            }
        }
PresetWitVoiceSettings
TTSWitVoiceSettings [] Meta.WitAi.TTS.Integrations.TTSWit.PresetWitVoiceSettings get
Definition at line 388 of file TTSWit.cs.
RuntimeCacheHandler
override ITTSRuntimeCacheHandler Meta.WitAi.TTS.Integrations.TTSWit.RuntimeCacheHandler get
Definition at line 88 of file TTSWit.cs.
        {
            get
            {
                if (_runtimeCache == null)
                {
                    _runtimeCache = gameObject.GetComponent<ITTSRuntimeCacheHandler>();
                }
                return _runtimeCache;
            }
        }
VoiceDefaultSettings
TTSVoiceSettings Meta.WitAi.TTS.Integrations.TTSWit.VoiceDefaultSettings get
Returns preset voice data if no voice data is selected. Useful for menu ai, etc.
Implements Meta.WitAi.TTS.Interfaces.ITTSVoiceProvider.
Definition at line 403 of file TTSWit.cs.
VoiceProvider
override ITTSVoiceProvider Meta.WitAi.TTS.Integrations.TTSWit.VoiceProvider get
Definition at line 84 of file TTSWit.cs.
WebDownloadEvents
TTSDownloadEvents Meta.WitAi.TTS.Integrations.TTSWit.WebDownloadEvents = new TTSDownloadEvents() get set
Download events.
Implements Meta.WitAi.TTS.Interfaces.ITTSWebHandler.
Definition at line 301 of file TTSWit.cs.
{ get; set; } = new TTSDownloadEvents();
WebHandler
override ITTSWebHandler Meta.WitAi.TTS.Integrations.TTSWit.WebHandler get
Definition at line 86 of file TTSWit.cs.
WebRequestEvents
TTSWebRequestEvents Meta.WitAi.TTS.Integrations.TTSWit.WebRequestEvents get
Any web request performs this event.
Implements Meta.WitAi.TTS.Interfaces.ITTSWebHandler.
Definition at line 115 of file TTSWit.cs.
WebStreamEvents
TTSStreamEvents Meta.WitAi.TTS.Integrations.TTSWit.WebStreamEvents = new TTSStreamEvents() get set
Streaming events.
Implements Meta.WitAi.TTS.Interfaces.ITTSWebHandler.
Definition at line 169 of file TTSWit.cs.
{ get; set; } = new TTSStreamEvents();
The documentation for this class was generated from the following file:
Assets/Oculus/Voice/Lib/Wit.ai/Features/TTS/Scripts/Runtime/Integrations/TTSWit.cs