VR_Test: OVRExtensions Class Reference
OVRExtensions Class Reference
Miscellaneous extension methods that any script can use.
Static Public Member Functions
static OVRPose ToTrackingSpacePose (this Transform transform, Camera camera)
Converts the given world-space transform to an OVRPose in tracking space.
static OVRPose ToWorldSpacePose (this OVRPose trackingSpacePose)
Converts the given pose from tracking-space to world-space.
static OVRPose ToWorldSpacePose (this OVRPose trackingSpacePose, Camera mainCamera)
Converts the given pose from tracking-space to world-space.
static OVRPose ToHeadSpacePose (this OVRPose trackingSpacePose)
Converts the given pose from tracking-space to head-space.
static OVRPose ToHeadSpacePose (this Transform transform, Camera camera)
Converts the given world-space transform to an OVRPose in head space.
static OVRPose ToOVRPose (this Transform t, bool isLocal=false)
static void FromOVRPose (this Transform t, OVRPose pose, bool isLocal=false)
static OVRPose ToOVRPose (this OVRPlugin.Posef p)
static OVRTracker.Frustum ToFrustum (this OVRPlugin.Frustumf f)
static Color FromColorf (this OVRPlugin.Colorf c)
static OVRPlugin.Colorf ToColorf (this Color c)
static Vector2 FromSizef (this OVRPlugin.Sizef v)
static OVRPlugin.Sizef ToSizef (this Vector2 v)
static Vector2 FromVector2f (this OVRPlugin.Vector2f v)
static Vector2 FromFlippedXVector2f (this OVRPlugin.Vector2f v)
static OVRPlugin.Vector2f ToVector2f (this Vector2 v)
static Vector3 FromSize3f (this OVRPlugin.Size3f v)
static OVRPlugin.Size3f ToSize3f (this Vector3 v)
static Vector3 FromVector3f (this OVRPlugin.Vector3f v)
static Vector3 FromFlippedXVector3f (this OVRPlugin.Vector3f v)
static Vector3 FromFlippedZVector3f (this OVRPlugin.Vector3f v)
static OVRPlugin.Vector3f ToVector3f (this Vector3 v)
static OVRPlugin.Vector3f ToFlippedXVector3f (this Vector3 v)
static OVRPlugin.Vector3f ToFlippedZVector3f (this Vector3 v)
static Vector4 FromVector4f (this OVRPlugin.Vector4f v)
static OVRPlugin.Vector4f ToVector4f (this Vector4 v)
static Quaternion FromQuatf (this OVRPlugin.Quatf q)
static Quaternion FromFlippedXQuatf (this OVRPlugin.Quatf q)
static Quaternion FromFlippedZQuatf (this OVRPlugin.Quatf q)
static OVRPlugin.Quatf ToQuatf (this Quaternion q)
static OVRPlugin.Quatf ToFlippedXQuatf (this Quaternion q)
static OVRPlugin.Quatf ToFlippedZQuatf (this Quaternion q)
static OVR.OpenVR.HmdMatrix34_t ConvertToHMDMatrix34 (this Matrix4x4 m)
static Transform FindChildRecursive (this Transform parent, string name)
static bool Equals (this Gradient gradient, Gradient otherGradient)
static void CopyFrom (this Gradient gradient, Gradient otherGradient)
Detailed Description
Miscellaneous extension methods that any script can use.
Definition at line 47 of file OVRCommon.cs.
Member Function Documentation
ConvertToHMDMatrix34()
static OVR.OpenVR.HmdMatrix34_t OVRExtensions.ConvertToHMDMatrix34 (this Matrix4x4 m) static
Definition at line 297 of file OVRCommon.cs.
    {
        OVR.OpenVR.HmdMatrix34_t pose = new OVR.OpenVR.HmdMatrix34_t();
        pose.m0 = m[0, 0];
        pose.m1 = m[0, 1];
        pose.m2 = -m[0, 2];
        pose.m3 = m[0, 3];
        pose.m4 = m[1, 0];
        pose.m5 = m[1, 1];
        pose.m6 = -m[1, 2];
        pose.m7 = m[1, 3];
        pose.m8 = -m[2, 0];
        pose.m9 = -m[2, 1];
        pose.m10 = m[2, 2];
        pose.m11 = -m[2, 3];
        return pose;
    }
CopyFrom()
static void OVRExtensions.CopyFrom (this Gradient gradient, Gradient otherGradient) static
Definition at line 360 of file OVRCommon.cs.
    {
        GradientColorKey[] colorKeys = new GradientColorKey[otherGradient.colorKeys.Length];
        for (int i = 0; i < colorKeys.Length; i++)
        {
            Color col = otherGradient.colorKeys[i].color;
            colorKeys[i].color = new Color(col.r, col.g, col.b, col.a);
            colorKeys[i].time = otherGradient.colorKeys[i].time;
        }
        GradientAlphaKey[] alphaKeys = new GradientAlphaKey[otherGradient.alphaKeys.Length];
        for (int i = 0; i < alphaKeys.Length; i++)
        {
            alphaKeys[i].alpha = otherGradient.alphaKeys[i].alpha;
            alphaKeys[i].time = otherGradient.alphaKeys[i].time;
        }
        gradient.SetKeys(colorKeys, alphaKeys);
    }
Equals()
static bool OVRExtensions.Equals (this Gradient gradient, Gradient otherGradient) static
Definition at line 335 of file OVRCommon.cs.
    {
        if (gradient.colorKeys.Length != otherGradient.colorKeys.Length ||
            gradient.alphaKeys.Length != otherGradient.alphaKeys.Length)
            return false;
        for (int i = 0; i < gradient.colorKeys.Length; i++)
        {
            GradientColorKey key = gradient.colorKeys[i];
            GradientColorKey otherKey = otherGradient.colorKeys[i];
            if (key.color != otherKey.color || key.time != otherKey.time)
                return false;
        }
        for (int i = 0; i < gradient.alphaKeys.Length; i++)
        {
            GradientAlphaKey key = gradient.alphaKeys[i];
            GradientAlphaKey otherKey = otherGradient.alphaKeys[i];
            if (key.alpha != otherKey.alpha || key.time != otherKey.time)
                return false;
        }
        return true;
    }
FindChildRecursive()
static Transform OVRExtensions.FindChildRecursive (this Transform parent, string name) static
Definition at line 319 of file OVRCommon.cs.
    {
        for (int i = 0; i < parent.childCount; i++)
        {
            var child = parent.GetChild(i);
            if (child.name.Contains(name))
                return child;
            var result = child.FindChildRecursive(name);
            if (result != null)
                return result;
        }
        return null;
    }
FromColorf()
static Color OVRExtensions.FromColorf (this OVRPlugin::Colorf c) static
Definition at line 182 of file OVRCommon.cs.
    {
        return new Color() { r = c.r, g = c.g, b = c.b, a = c.a };
    }
FromFlippedXQuatf()
static Quaternion OVRExtensions.FromFlippedXQuatf (this OVRPlugin::Quatf q) static
Definition at line 272 of file OVRCommon.cs.
    {
        return new Quaternion() { x = q.x, y = -q.y, z = -q.z, w = q.w };
    }
FromFlippedXVector2f()
static Vector2 OVRExtensions.FromFlippedXVector2f (this OVRPlugin::Vector2f v) static
Definition at line 207 of file OVRCommon.cs.
    {
        return new Vector2() { x = -v.x, y = v.y };
    }
FromFlippedXVector3f()
static Vector3 OVRExtensions.FromFlippedXVector3f (this OVRPlugin::Vector3f v) static
Definition at line 232 of file OVRCommon.cs.
    {
        return new Vector3() { x = -v.x, y = v.y, z = v.z };
    }
FromFlippedZQuatf()
static Quaternion OVRExtensions.FromFlippedZQuatf (this OVRPlugin::Quatf q) static
Definition at line 277 of file OVRCommon.cs.
    {
        return new Quaternion() { x = -q.x, y = -q.y, z = q.z, w = q.w };
    }
FromFlippedZVector3f()
static Vector3 OVRExtensions.FromFlippedZVector3f (this OVRPlugin::Vector3f v) static
Definition at line 237 of file OVRCommon.cs.
    {
        return new Vector3() { x = v.x, y = v.y, z = -v.z };
    }
FromOVRPose()
static void OVRExtensions.FromOVRPose (this Transform t, OVRPose pose, bool isLocal = false) static
Definition at line 144 of file OVRCommon.cs.
    {
        if (isLocal)
        {
            t.localRotation = pose.orientation;
            t.localPosition = pose.position;
        }
        else
        {
            t.rotation = pose.orientation;
            t.position = pose.position;
        }
    }
FromQuatf()
static Quaternion OVRExtensions.FromQuatf (this OVRPlugin::Quatf q) static
Definition at line 267 of file OVRCommon.cs.
    {
        return new Quaternion() { x = q.x, y = q.y, z = q.z, w = q.w };
    }
FromSize3f()
static Vector3 OVRExtensions.FromSize3f (this OVRPlugin::Size3f v) static
Definition at line 217 of file OVRCommon.cs.
    {
        return new Vector3() { x = v.w, y = v.h, z = v.d };
    }
FromSizef()
static Vector2 OVRExtensions.FromSizef (this OVRPlugin::Sizef v) static
Definition at line 192 of file OVRCommon.cs.
    {
        return new Vector2() { x = v.w, y = v.h };
    }
FromVector2f()
static Vector2 OVRExtensions.FromVector2f (this OVRPlugin::Vector2f v) static
Definition at line 202 of file OVRCommon.cs.
    {
        return new Vector2() { x = v.x, y = v.y };
    }
FromVector3f()
static Vector3 OVRExtensions.FromVector3f (this OVRPlugin::Vector3f v) static
Definition at line 227 of file OVRCommon.cs.
    {
        return new Vector3() { x = v.x, y = v.y, z = v.z };
    }
FromVector4f()
static Vector4 OVRExtensions.FromVector4f (this OVRPlugin::Vector4f v) static
Definition at line 257 of file OVRCommon.cs.
    {
        return new Vector4() { x = v.x, y = v.y, z = v.z, w = v.w };
    }
ToColorf()
static OVRPlugin.Colorf OVRExtensions.ToColorf (this Color c) static
Definition at line 187 of file OVRCommon.cs.
    {
        return new OVRPlugin.Colorf() { r = c.r, g = c.g, b = c.b, a = c.a };
    }
ToFlippedXQuatf()
static OVRPlugin.Quatf OVRExtensions.ToFlippedXQuatf (this Quaternion q) static
Definition at line 287 of file OVRCommon.cs.
    {
        return new OVRPlugin.Quatf() { x = q.x, y = -q.y, z = -q.z, w = q.w };
    }
ToFlippedXVector3f()
static OVRPlugin.Vector3f OVRExtensions.ToFlippedXVector3f (this Vector3 v) static
Definition at line 247 of file OVRCommon.cs.
    {
        return new OVRPlugin.Vector3f() { x = -v.x, y = v.y, z = v.z };
    }
ToFlippedZQuatf()
static OVRPlugin.Quatf OVRExtensions.ToFlippedZQuatf (this Quaternion q) static
Definition at line 292 of file OVRCommon.cs.
    {
        return new OVRPlugin.Quatf() { x = -q.x, y = -q.y, z = q.z, w = q.w };
    }
ToFlippedZVector3f()
static OVRPlugin.Vector3f OVRExtensions.ToFlippedZVector3f (this Vector3 v) static
Definition at line 252 of file OVRCommon.cs.
    {
        return new OVRPlugin.Vector3f() { x = v.x, y = v.y, z = -v.z };
    }
ToFrustum()
static OVRTracker.Frustum OVRExtensions.ToFrustum (this OVRPlugin::Frustumf f) static
Definition at line 167 of file OVRCommon.cs.
    {
        return new OVRTracker.Frustum()
        {
            nearZ = f.zNear,
            farZ = f.zFar,
            fov = new Vector2()
            {
                x = Mathf.Rad2Deg * f.fovX,
                y = Mathf.Rad2Deg * f.fovY
            }
        };
    }
ToHeadSpacePose() [1/2]
static OVRPose OVRExtensions.ToHeadSpacePose (this OVRPose trackingSpacePose) static
Converts the given pose from tracking-space to head-space.
Definition at line 103 of file OVRCommon.cs.
    {
        OVRPose headPose = OVRPose.identity;
        Vector3 pos;
        Quaternion rot;
        if (OVRNodeStateProperties.GetNodeStatePropertyVector3(UnityEngine.XR.XRNode.Head,
                NodeStatePropertyType.Position, OVRPlugin.Node.Head, OVRPlugin.Step.Render, out pos))
            headPose.position = pos;
        if (OVRNodeStateProperties.GetNodeStatePropertyQuaternion(UnityEngine.XR.XRNode.Head,
                NodeStatePropertyType.Orientation, OVRPlugin.Node.Head, OVRPlugin.Step.Render, out rot))
            headPose.orientation = rot;
        OVRPose poseInHeadSpace = headPose.Inverse() * trackingSpacePose;
        return poseInHeadSpace;
    }
References OVRPose.identity, and OVRPose.Inverse().
ToHeadSpacePose() [2/2]
static OVRPose OVRExtensions.ToHeadSpacePose (this Transform transform, Camera camera) static
Converts the given world-space transform to an OVRPose in head space.
Definition at line 124 of file OVRCommon.cs.
    {
        // The Quaternion used in OVRPose is not 1-1 mapped with the Transform[0:3,0:3] (which is Scale * Rotation), need to calculate rotation and position separately.
        Quaternion rotation = Quaternion.Inverse(camera.transform.rotation) * transform.rotation;
        var position = (camera.transform.worldToLocalMatrix * transform.localToWorldMatrix).GetColumn(3);
        return new OVRPose
        {
            orientation = rotation,
            position = position
        };
    }
References OVRPose.Inverse().
ToOVRPose() [1/2]
static OVRPose OVRExtensions.ToOVRPose (this OVRPlugin::Posef p) static
Definition at line 158 of file OVRCommon.cs.
    {
        return new OVRPose()
        {
            position = new Vector3(p.Position.x, p.Position.y, -p.Position.z),
            orientation = new Quaternion(-p.Orientation.x, -p.Orientation.y, p.Orientation.z, p.Orientation.w)
        };
    }
ToOVRPose() [2/2]
static OVRPose OVRExtensions.ToOVRPose (this Transform t, bool isLocal = false) static
Definition at line 136 of file OVRCommon.cs.
    {
        OVRPose pose;
        pose.orientation = (isLocal) ? t.localRotation : t.rotation;
        pose.position = (isLocal) ? t.localPosition : t.position;
        return pose;
    }
ToQuatf()
static OVRPlugin.Quatf OVRExtensions.ToQuatf (this Quaternion q) static
Definition at line 282 of file OVRCommon.cs.
    {
        return new OVRPlugin.Quatf() { x = q.x, y = q.y, z = q.z, w = q.w };
    }
ToSize3f()
static OVRPlugin.Size3f OVRExtensions.ToSize3f (this Vector3 v) static
Definition at line 222 of file OVRCommon.cs.
    {
        return new OVRPlugin.Size3f() { w = v.x, h = v.y, d = v.z };
    }
ToSizef()
static OVRPlugin.Sizef OVRExtensions.ToSizef (this Vector2 v) static
Definition at line 197 of file OVRCommon.cs.
    {
        return new OVRPlugin.Sizef() { w = v.x, h = v.y };
    }
ToTrackingSpacePose()
static OVRPose OVRExtensions.ToTrackingSpacePose (this Transform transform, Camera camera) static
Converts the given world-space transform to an OVRPose in tracking space.
Definition at line 52 of file OVRCommon.cs.
    {
        // Initializing to identity, but for all Oculus headsets, down below the pose will be initialized to the runtime's pose value, so identity will never be returned.
        OVRPose headPose = OVRPose.identity;
        Vector3 pos;
        Quaternion rot;
        if (OVRNodeStateProperties.GetNodeStatePropertyVector3(Node.Head, NodeStatePropertyType.Position,
                OVRPlugin.Node.Head, OVRPlugin.Step.Render, out pos))
            headPose.position = pos;
        if (OVRNodeStateProperties.GetNodeStatePropertyQuaternion(Node.Head, NodeStatePropertyType.Orientation,
                OVRPlugin.Node.Head, OVRPlugin.Step.Render, out rot))
            headPose.orientation = rot;
        var ret = headPose * transform.ToHeadSpacePose(camera);
        return ret;
    }
References OVRPose.identity.
ToVector2f()
static OVRPlugin.Vector2f OVRExtensions.ToVector2f (this Vector2 v) static
Definition at line 212 of file OVRCommon.cs.
    {
        return new OVRPlugin.Vector2f() { x = v.x, y = v.y };
    }
ToVector3f()
static OVRPlugin.Vector3f OVRExtensions.ToVector3f (this Vector3 v) static
Definition at line 242 of file OVRCommon.cs.
    {
        return new OVRPlugin.Vector3f() { x = v.x, y = v.y, z = v.z };
    }
ToVector4f()
static OVRPlugin.Vector4f OVRExtensions.ToVector4f (this Vector4 v) static
Definition at line 262 of file OVRCommon.cs.
    {
        return new OVRPlugin.Vector4f() { x = v.x, y = v.y, z = v.z, w = v.w };
    }
ToWorldSpacePose() [1/2]
static OVRPose OVRExtensions.ToWorldSpacePose (this OVRPose trackingSpacePose) static
Converts the given pose from tracking-space to world-space.
Definition at line 75 of file OVRCommon.cs.
    {
        return ToWorldSpacePose(trackingSpacePose, Camera.main);
    }
References ToWorldSpacePose().
ToWorldSpacePose() [2/2]
static OVRPose OVRExtensions.ToWorldSpacePose (this OVRPose trackingSpacePose, Camera mainCamera) static
Converts the given pose from tracking-space to world-space.
Definition at line 83 of file OVRCommon.cs.
    {
        // Transform from tracking-Space to head-Space
        OVRPose poseInHeadSpace = trackingSpacePose.ToHeadSpacePose();
        // Transform from head space to world space
        var cameraTransform = mainCamera.transform.localToWorldMatrix;
        var headSpaceTransform = Matrix4x4.TRS(
            poseInHeadSpace.position, poseInHeadSpace.orientation, Vector3.one);
        var worldSpaceTransform = cameraTransform * headSpaceTransform;
        return new OVRPose
        {
            position = worldSpaceTransform.GetColumn(3),
            orientation = worldSpaceTransform.rotation
        };
    }
References OVRPose.orientation, and OVRPose.position.
The documentation for this class was generated from the following files:
Assets/Oculus/VR/Scripts/OVRCommon.cs
Assets/Oculus/VR/Scripts/OVRSpace.cs
Assets/Oculus/VR/Scripts/Util/OVREnumerable.cs