VR_Test: Meta.WitAi.Lib.ExportParser Class Reference
Meta.WitAi.Lib.ExportParser Class Reference
Parses the Wit.ai Export zip file.
Classes
class ModuleType
class PathValues
List-based class to process nodes more easily.
Public Member Functions
ExportParser (ZipArchive zip)
WitComposerInfo ImportComposerInfo ()
Parses the provided zip export and extracts the context map values used within the composer graphs.
WitCharacterInfo[] ImportCharacterInfo ()
Private Member Functions
List< ZipArchiveEntry > GetJsonFileNames (string folder)
Finds all the Json files canvases in the zip archive under the given folder.
WitComposerInfo ExtractCanvases (WitComposerInfo info, List< ZipArchiveEntry > jsonCanvases)
Parses the given zip archives and adds them to the.
WitResponseNode ExtractJson (ZipArchive zip, string fileName)
Extracts a Wit JSON object representing the given json file.
ContextMapPaths ParseModules (WitResponseNode json)
Parses the Composer Map for context map variables.
void GatherMapValuesFromResponse (WitResponseNode module)
Parses a Response module in the composer graph, adding any context map values to the correct list.
void GatherMapValuesFromDecision (WitResponseNode module)
Parses a Decision module in the composer graph, adding any context map values to the correct list.
bool MoveToShared (string path)
Moves a path/value item from server to shared list.
bool IsPathAlreadyDiscovered (string path)
Whether the given path has already been saved in one of the given lists.
void GatherMapValuesFromContext (WitResponseNode module)
Parses the given context node and places any context map variables in the correct list.
ContextMapPaths ConvertToContextMapValues ()
Takes all three lists of variables and aggregate them into a single object.
WitCharacterInfo[] ExtractCharacters (List< ZipArchiveEntry > jsonFiles)
Private Attributes
readonly ZipArchive _zip
readonly List< PathValues > _sharedVariables = new List<PathValues>()
readonly List< PathValues > _serverVariables = new List<PathValues>()
readonly ArrayList _clientVariables = new ArrayList()
readonly HashSet< string > _actions = new HashSet<string>()
Static Private Attributes
const string ComposerFolderName = "/composer/"
const string CharacterFolderName = "/characters/"
const string ResponseFieldsName = "response_fields"
const string ContextFieldsName = "context_fields"
const string ModulesName = "modules"
const string TypeName = "type"
const string TextName = "text"
const string PathName = "path"
Detailed Description
Parses the Wit.ai Export zip file.
Definition at line 25 of file ExportParser.cs.
Constructor & Destructor Documentation
ExportParser()
Meta.WitAi.Lib.ExportParser.ExportParser (ZipArchive zip)
Definition at line 48 of file ExportParser.cs.
        {
            _zip = zip;
        }
Member Function Documentation
ConvertToContextMapValues()
ContextMapPaths Meta.WitAi.Lib.ExportParser.ConvertToContextMapValues () private
Takes all three lists of variables and aggregate them into a single object.
Definition at line 312 of file ExportParser.cs.
        {
            var result = new ContextMapPaths();
            result.client = (string[])_clientVariables.ToArray(typeof(string));
            result.server = new ComposerGraphValues[_serverVariables.Count];
            for (var i = 0; i < _serverVariables.Count; i++) result.server[i] = _serverVariables[i].ConvertToStruct();
            result.shared = new ComposerGraphValues[_sharedVariables.Count];
            for (var i = 0; i < _sharedVariables.Count; i++) result.shared[i] = _sharedVariables[i].ConvertToStruct();
            _sharedVariables.Clear();
            _serverVariables.Clear();
            _clientVariables.Clear();
            return result;
        }
ExtractCanvases()
WitComposerInfo Meta.WitAi.Lib.ExportParser.ExtractCanvases (WitComposerInfo info, List< ZipArchiveEntry > jsonCanvases) private
Parses the given zip archives and adds them to the.
Parameters
jsonCanvases
Returns
Definition at line 83 of file ExportParser.cs.
        {
            info.canvases = new ComposerGraph[jsonCanvases.Count];
            for (var i = 0; i < jsonCanvases.Count; i++)
            {
                var jsonNode = ExtractJson(_zip, jsonCanvases[i].Name);
                info.canvases[i].contextMap = ParseModules(jsonNode);
                info.canvases[i].actions = _actions.ToArray();
                Array.Sort(info.canvases[i].actions);
                var name = System.IO.Path.GetFileNameWithoutExtension(jsonCanvases[i].Name);
                name = name.Substring(0, 1).ToUpper() + name.Substring(1, name.Length - 1); //capitalize 1st letter
                info.canvases[i].canvasName = name;
            }
            return info;
        }
References Meta.WitAi.Data.Info.WitComposerInfo.canvases, Meta.WitAi.Lib.ExportParser.ExtractJson(), and Meta.WitAi.Lib.ExportParser.ParseModules().
ExtractCharacters()
WitCharacterInfo[] Meta.WitAi.Lib.ExportParser.ExtractCharacters (List< ZipArchiveEntry > jsonFiles) private
Definition at line 337 of file ExportParser.cs.
        {
            const string voiceConfigName = "voice_config";
            WitCharacterInfo[] characters = new WitCharacterInfo[jsonFiles.Count];
            for (var i = 0; i < jsonFiles.Count; i++)
            {
                var jsonNode = ExtractJson(_zip, jsonFiles[i].Name);
                var voiceConfig = jsonNode[voiceConfigName];
                characters[i] = JsonConvert.DeserializeObject<WitCharacterInfo>(jsonNode);
                characters[i].voiceConfig = JsonConvert.DeserializeObject<WitVoiceConfig>(voiceConfig);
            }
            return characters;
        }
ExtractJson()
WitResponseNode Meta.WitAi.Lib.ExportParser.ExtractJson (ZipArchive zip, string fileName) private
Extracts a Wit JSON object representing the given json file.
Parameters
zip zip archive from Wit.ai export
fileName one of the file names
Returns
The entire canvas structure as nested JSON objects
Definition at line 106 of file ExportParser.cs.
        {
            var entry = zip.Entries.First((v) => v.Name.EndsWith(fileName));
            if (entry.Name.EndsWith(fileName))
            {
                var stream = entry.Open();
                var json = new StreamReader(stream).ReadToEnd();
                return JsonConvert.DeserializeToken(json);
            }
            VLog.W("Could not open file named "+ fileName);
            return null;
        }
References Meta.WitAi.Json.JsonConvert.DeserializeToken(), and Meta.WitAi.VLog.W().
GatherMapValuesFromContext()
void Meta.WitAi.Lib.ExportParser.GatherMapValuesFromContext (WitResponseNode module) private
Parses the given context node and places any context map variables in the correct list.
Definition at line 254 of file ExportParser.cs.
        {
            const string contextTypeName = "context_type";
            const string setFieldsName = "set_fields";
            const string saveFieldsName = "save_fields";
            const string saveName = "save";
            const string setName = "set";
            const string entityName = "entity";
            const string valueName = "value";
            string path, value;
            var saves = module[ContextFieldsName]?[saveFieldsName];
            var sets = module[ContextFieldsName]?[setFieldsName];
            switch (module[ContextFieldsName]?[contextTypeName])
            {
                case saveName:
                    path = saves?[PathName].ToString();
                    value = saves?[entityName].ToString();
                    break;
                case setName:
                    path = module[ContextFieldsName]?[setFieldsName]?[PathName].ToString();
                    value = sets?[valueName].ToString();
                    break;
                default:
                    return;
            }
            path = path?.Replace("\"", "");
            value = value?.Replace("\"", "");
            //check if we have the same path and value in readwrite
            var foundWritable = _sharedVariables.Find((item) => item.Path == path);
            if (foundWritable != null && !foundWritable.Values.Contains(value))
            {
                foundWritable?.Values.Add(value);
                return;
            }
            //check if we have the same path and value in basic read
            var foundReadable = _serverVariables.Find((item) => item.Path == path);
            if (foundReadable != null && !foundReadable.Values.Contains(value))
            {
                foundReadable?.Values.Add(value);
                return;
            }
            var newReadable = new PathValues(path, value);
            if (_clientVariables.Contains(path)) //move to readWrite if would be in both.
            {
                _clientVariables.Remove(path);
                _sharedVariables.Add(newReadable);
                return;
            }
            _serverVariables.Add(newReadable);
        }
GatherMapValuesFromDecision()
void Meta.WitAi.Lib.ExportParser.GatherMapValuesFromDecision (WitResponseNode module) private
Parses a Decision module in the composer graph, adding any context map values to the correct list.
Parameters
module
Definition at line 208 of file ExportParser.cs.
        {
            const string decisionFieldsName = "decision_fields";
            const string conditionNodesName = "condition_nodes";
            const string contextWithValueFieldsName = "context_with_value_fields";
            var nodes = module[decisionFieldsName]?[conditionNodesName];
            for (var i = 0; i < nodes?.Count; i++)
            {
                var path = nodes[i][contextWithValueFieldsName]?[PathName].Value;
                if (IsPathAlreadyDiscovered(path))
                    continue;
                if (MoveToShared(path))
                    continue;
                _clientVariables.Add(path);
            }
        }
References Meta.WitAi.Lib.ExportParser.IsPathAlreadyDiscovered(), and Meta.WitAi.Lib.ExportParser.MoveToShared().
GatherMapValuesFromResponse()
void Meta.WitAi.Lib.ExportParser.GatherMapValuesFromResponse (WitResponseNode module) private
Parses a Response module in the composer graph, adding any context map values to the correct list.
Parameters
module the JSON representation of the module
Definition at line 179 of file ExportParser.cs.
        {
            const string actionName = "action";
            var responseText = module[ResponseFieldsName][TextName].ToString();
            var matches = Regex.Match(responseText, @"{.*}");
            foreach (Group match in matches.Groups)
            {
                if (string.IsNullOrEmpty(match.Value)) continue;
                var path = match.Value.Substring(1, match.Value.Length - 2);
                if (IsPathAlreadyDiscovered(path))
                    continue;
                if (MoveToShared(path))
                    continue;
                _clientVariables.Add(path);
            }
            string action = module[ResponseFieldsName][actionName].ToString();
            if (String.IsNullOrEmpty(action)) return;
            _actions.Add(action);
        }
References Meta.WitAi.Lib.ExportParser.IsPathAlreadyDiscovered(), and Meta.WitAi.Lib.ExportParser.MoveToShared().
GetJsonFileNames()
List< ZipArchiveEntry > Meta.WitAi.Lib.ExportParser.GetJsonFileNames (string folder) private
Finds all the Json files canvases in the zip archive under the given folder.
Returns
new list of entries which represent json files
Definition at line 66 of file ExportParser.cs.
        {
            var jsonCanvases = new List<ZipArchiveEntry>();
            foreach (var entry in _zip.Entries)
            {
                if (entry.FullName.Contains(folder))
                {
                    jsonCanvases.Add(entry);
                }
            }
            return jsonCanvases;
        }
ImportCharacterInfo()
WitCharacterInfo[] Meta.WitAi.Lib.ExportParser.ImportCharacterInfo ()
Definition at line 331 of file ExportParser.cs.
        {
            WitCharacterInfo[] info = ExtractCharacters(GetJsonFileNames(CharacterFolderName));
            return info;
        }
ImportComposerInfo()
WitComposerInfo Meta.WitAi.Lib.ExportParser.ImportComposerInfo ()
Parses the provided zip export and extracts the context map values used within the composer graphs.
Definition at line 56 of file ExportParser.cs.
        {
            WitComposerInfo info = new WitComposerInfo();
            info = ExtractCanvases(info, GetJsonFileNames(ComposerFolderName));
            return info;
        }
References Meta.WitAi.Lib.ExportParser.ExtractCanvases(), and Meta.WitAi.Lib.ExportParser.GetJsonFileNames().
IsPathAlreadyDiscovered()
bool Meta.WitAi.Lib.ExportParser.IsPathAlreadyDiscovered (string path) private
Whether the given path has already been saved in one of the given lists.
Definition at line 244 of file ExportParser.cs.
        {
            return string.IsNullOrEmpty(path) ||
                _clientVariables.Contains(path) ||
                _sharedVariables.Exists((readable) => readable.Path == path);
        }
MoveToShared()
bool Meta.WitAi.Lib.ExportParser.MoveToShared (string path) private
Moves a path/value item from server to shared list.
Returns
true if the item was found and moved; false otherwise.
Definition at line 230 of file ExportParser.cs.
        {
            var found = _serverVariables.Find((item) => item.Path == path);
            if (found != null)
            {
                _serverVariables.Remove(found);
                _sharedVariables.Add(found);
                return true;
            }
            return false;
        }
ParseModules()
ContextMapPaths Meta.WitAi.Lib.ExportParser.ParseModules (WitResponseNode json) private
Parses the Composer Map for context map variables.
Definition at line 152 of file ExportParser.cs.
        {
            foreach (var module in json[ModulesName].Childs)
            {
                switch (module[TypeName].Value)
                {
                    case ModuleType.Response: // read on server, written in Unity
                        GatherMapValuesFromResponse(module);
                        break;
                    case ModuleType.Decision: // read on server, written in Unity
                        GatherMapValuesFromDecision(module);
                        break;
                    case ModuleType.Context: // readable in Unity, written on server
                        GatherMapValuesFromContext(module);
                        continue;
                }
            }
            ContextMapPaths result = ConvertToContextMapValues();
            return result;
        }
References Meta.WitAi.Lib.ExportParser.ConvertToContextMapValues(), Meta.WitAi.Lib.ExportParser.GatherMapValuesFromContext(), Meta.WitAi.Lib.ExportParser.GatherMapValuesFromDecision(), and Meta.WitAi.Lib.ExportParser.GatherMapValuesFromResponse().
Member Data Documentation
_actions
readonly HashSet<string> Meta.WitAi.Lib.ExportParser._actions = new HashSet<string>() private
Definition at line 31 of file ExportParser.cs.
_clientVariables
readonly ArrayList Meta.WitAi.Lib.ExportParser._clientVariables = new ArrayList() private
Definition at line 30 of file ExportParser.cs.
_serverVariables
readonly List<PathValues> Meta.WitAi.Lib.ExportParser._serverVariables = new List<PathValues>() private
Definition at line 29 of file ExportParser.cs.
_sharedVariables
readonly List<PathValues> Meta.WitAi.Lib.ExportParser._sharedVariables = new List<PathValues>() private
Definition at line 28 of file ExportParser.cs.
_zip
readonly ZipArchive Meta.WitAi.Lib.ExportParser._zip private
Definition at line 27 of file ExportParser.cs.
CharacterFolderName
const string Meta.WitAi.Lib.ExportParser.CharacterFolderName = "/characters/" static private
Definition at line 34 of file ExportParser.cs.
ComposerFolderName
const string Meta.WitAi.Lib.ExportParser.ComposerFolderName = "/composer/" static private
Definition at line 33 of file ExportParser.cs.
ContextFieldsName
const string Meta.WitAi.Lib.ExportParser.ContextFieldsName = "context_fields" static private
Definition at line 36 of file ExportParser.cs.
ModulesName
const string Meta.WitAi.Lib.ExportParser.ModulesName = "modules" static private
Definition at line 37 of file ExportParser.cs.
PathName
const string Meta.WitAi.Lib.ExportParser.PathName = "path" static private
Definition at line 40 of file ExportParser.cs.
ResponseFieldsName
const string Meta.WitAi.Lib.ExportParser.ResponseFieldsName = "response_fields" static private
Definition at line 35 of file ExportParser.cs.
TextName
const string Meta.WitAi.Lib.ExportParser.TextName = "text" static private
Definition at line 39 of file ExportParser.cs.
TypeName
const string Meta.WitAi.Lib.ExportParser.TypeName = "type" static private
Definition at line 38 of file ExportParser.cs.
The documentation for this class was generated from the following file:
Assets/Oculus/Voice/Lib/Wit.ai/Lib/Wit/Editor/ExportParser.cs