VR_Test: UnityEngine.EventSystems.OVRInputModule Class Reference
UnityEngine.EventSystems.OVRInputModule Class Reference
VR extension of PointerInputModule which supports gaze and controller pointing.
Public Types
enum InputMode { Mouse , Buttons }
Public Member Functions
override void UpdateModule ()
override bool IsModuleSupported ()
override bool ShouldActivateModule ()
override void ActivateModule ()
override void DeactivateModule ()
override void Process ()
Process this InputModule. Same as the StandaloneInputModule version, except that it calls ProcessMouseEvent twice, once for gaze pointers, and once for mouse pointers.
Public Attributes
Transform rayTransform
OVRCursor m_Cursor
OVRInput.Button joyPadClickButton = OVRInput.Button.One
KeyCode gazeClickKey = KeyCode.Space
bool performSphereCastForGazepointer
bool useRightStickScroll = true
float rightStickDeadZone = 0.15f
bool useSwipeScroll = true
float swipeDragThreshold = 2
float swipeDragScale = 1f
bool InvertSwipeXAxis = false
OVRRaycaster activeGraphicRaycaster
float angleDragThreshold = 1
Protected Member Functions
void CopyFromTo (OVRPointerEventData @from, OVRPointerEventData @to)
Convenience function for cloning PointerEventData.
new void CopyFromTo (PointerEventData @from, PointerEventData @to)
Convenience function for cloning PointerEventData.
bool GetPointerData (int id, out OVRPointerEventData data, bool create)
new void ClearSelection ()
Clear pointer state for both types of pointer.
virtual MouseState GetGazePointerData ()
State for a pointer controlled by a world space ray. E.g. gaze pointer.
MouseState GetCanvasPointerData ()
Get state for pointer which is a pointer moving in world space across the surface of a world space canvas.
Vector2 SwipeAdjustedPosition (Vector2 originalPosition, PointerEventData pointerEvent)
override void ProcessDrag (PointerEventData pointerEvent)
Exactly the same as the code from PointerInputModule, except that we call our own IsPointerMoving.
virtual PointerEventData.FramePressState GetGazeButtonState ()
Get state of button corresponding to gaze pointer.
Vector2 GetExtraScrollDelta ()
Get extra scroll delta from gamepad.
Protected Attributes
Dictionary< int, OVRPointerEventData > m_VRRayPointerData = new Dictionary<int, OVRPointerEventData>()
Properties
InputMode inputMode [get]
bool allowActivationOnMobileDevice [get, set]
float inputActionsPerSecond [get, set]
string horizontalAxis [get, set]
Name of the horizontal axis for movement (if axis events are used).
string verticalAxis [get, set]
Name of the vertical axis for movement (if axis events are used).
string submitButton [get, set]
string cancelButton [get, set]
Private Member Functions
bool SendSubmitEventToSelectedObject ()
Process submit keys.
bool AllowMoveEventProcessing (float time)
Vector2 GetRawMoveVector ()
bool SendMoveEventToSelectedObject ()
Process keyboard events.
bool SendUpdateEventToSelectedObject ()
void ProcessMousePress (MouseButtonEventData data)
Process the current mouse press.
void ProcessMouseEvent (MouseState mouseData)
Process all mouse events. This is the same as the StandaloneInputModule version except that it takes MouseState as a parameter, allowing it to be used for both Gaze and Mouse pointerss.
bool ShouldStartDrag (PointerEventData pointerEvent)
New version of ShouldStartDrag implemented first in PointerInputModule. This version differs in that for ray based pointers it makes a decision about whether a drag should start based on the angular change the pointer has made so far, as seen from the camera. This also works when the world space ray is translated rather than rotated, since the beginning and end of the movement are considered as angle from the same point.
Static Private Member Functions
static bool UseMouse (bool pressed, bool released, PointerEventData pointerData)
Decide if mouse events need to be processed this frame. Same as StandloneInputModule except that the IsPointerMoving method from this class is used, instead of the method on PointerEventData.
static Vector3 GetRectTransformNormal (RectTransform rectTransform)
For RectTransform, calculate it's normal in world space.
static bool IsPointerMoving (PointerEventData pointerEvent)
The purpose of this function is to allow us to switch between using the standard IsPointerMoving method for mouse driven pointers, but to always return true when it's a ray based pointer. All real-world ray-based input devices are always moving so for simplicity we just return true for them.
Private Attributes
float m_SpherecastRadius = 1.0f
float m_NextAction
Vector2 m_LastMousePosition
Vector2 m_MousePosition
string m_HorizontalAxis = "Horizontal"
string m_VerticalAxis = "Vertical"
Name of the vertical axis for movement (if axis events are used).
string m_SubmitButton = "Submit"
Name of the submit button.
string m_CancelButton = "Cancel"
Name of the submit button.
float m_InputActionsPerSecond = 10
bool m_AllowActivationOnMobileDevice
readonly MouseState m_MouseState = new MouseState()
Detailed Description
VR extension of PointerInputModule which supports gaze and controller pointing.
Definition at line 29 of file OVRInputModule.cs.
Member Enumeration Documentation
InputMode
enum UnityEngine.EventSystems.OVRInputModule.InputMode
Definition at line 111 of file OVRInputModule.cs.
        {
            Mouse,
            Buttons
        }
Constructor & Destructor Documentation
OVRInputModule()
UnityEngine.EventSystems.OVRInputModule.OVRInputModule () protected
Definition at line 98 of file OVRInputModule.cs.
        {
        }
Member Function Documentation
ActivateModule()
override void UnityEngine.EventSystems.OVRInputModule.ActivateModule ()
Definition at line 228 of file OVRInputModule.cs.
        {
            base.ActivateModule();
#if ENABLE_LEGACY_INPUT_MANAGER
            m_MousePosition = Input.mousePosition;
            m_LastMousePosition = Input.mousePosition;
#endif
            var toSelect = eventSystem.currentSelectedGameObject;
            if (toSelect == null)
                toSelect = eventSystem.firstSelectedGameObject;
            eventSystem.SetSelectedGameObject(toSelect, GetBaseEventData());
        }
AllowMoveEventProcessing()
bool UnityEngine.EventSystems.OVRInputModule.AllowMoveEventProcessing (float time) private
Definition at line 269 of file OVRInputModule.cs.
        {
#if ENABLE_LEGACY_INPUT_MANAGER
            bool allow = Input.GetButtonDown(m_HorizontalAxis);
            allow |= Input.GetButtonDown(m_VerticalAxis);
            allow |= (time > m_NextAction);
            return allow;
#else
            return false;
#endif
        }
ClearSelection()
new void UnityEngine.EventSystems.OVRInputModule.ClearSelection () protected
Clear pointer state for both types of pointer.
Definition at line 587 of file OVRInputModule.cs.
        {
            var baseEventData = GetBaseEventData();
            foreach (var pointer in m_PointerData.Values)
            {
                // clear all selection
                HandlePointerExitAndEnter(pointer, null);
            }
            foreach (var pointer in m_VRRayPointerData.Values)
            {
                // clear all selection
                HandlePointerExitAndEnter(pointer, null);
            }
            m_PointerData.Clear();
            eventSystem.SetSelectedGameObject(null, baseEventData);
        }
CopyFromTo() [1/2]
void UnityEngine.EventSystems.OVRInputModule.CopyFromTo (OVRPointerEventData @ from, OVRPointerEventData @ to) protected
Convenience function for cloning PointerEventData.
Parameters
from Copy this value
to to this object
Definition at line 533 of file OVRInputModule.cs.
        {
            @to.position = @from.position;
            @to.delta = @from.delta;
            @to.scrollDelta = @from.scrollDelta;
            @to.pointerCurrentRaycast = @from.pointerCurrentRaycast;
            @to.pointerEnter = @from.pointerEnter;
            @to.worldSpaceRay = @from.worldSpaceRay;
        }
CopyFromTo() [2/2]
new void UnityEngine.EventSystems.OVRInputModule.CopyFromTo (PointerEventData @ from, PointerEventData @ to) protected
Convenience function for cloning PointerEventData.
Parameters
from Copy this value
to to this object
Definition at line 548 of file OVRInputModule.cs.
        {
            @to.position = @from.position;
            @to.delta = @from.delta;
            @to.scrollDelta = @from.scrollDelta;
            @to.pointerCurrentRaycast = @from.pointerCurrentRaycast;
            @to.pointerEnter = @from.pointerEnter;
        }
DeactivateModule()
override void UnityEngine.EventSystems.OVRInputModule.DeactivateModule ()
Definition at line 243 of file OVRInputModule.cs.
        {
            base.DeactivateModule();
            ClearSelection();
        }
GetCanvasPointerData()
MouseState UnityEngine.EventSystems.OVRInputModule.GetCanvasPointerData () protected
Get state for pointer which is a pointer moving in world space across the surface of a world space canvas.
Returns
Definition at line 724 of file OVRInputModule.cs.
        {
            // Get the OVRRayPointerEventData reference
            PointerEventData leftData;
            GetPointerData(kMouseLeftId, out leftData, true);
            leftData.Reset();
            // Setup default values here. Set position to zero because we don't actually know the pointer
            // positions. Each canvas knows the position of its canvas pointer.
            leftData.position = Vector2.zero;
#if ENABLE_LEGACY_INPUT_MANAGER
            leftData.scrollDelta = Input.mouseScrollDelta;
#endif
            leftData.button = PointerEventData.InputButton.Left;
            if (activeGraphicRaycaster)
            {
                // Let the active raycaster find intersections on its canvas
                activeGraphicRaycaster.RaycastPointer(leftData, m_RaycastResultCache);
                var raycast = FindFirstRaycast(m_RaycastResultCache);
                leftData.pointerCurrentRaycast = raycast;
                m_RaycastResultCache.Clear();
                OVRRaycaster ovrRaycaster = raycast.module as OVRRaycaster;
                if (ovrRaycaster) // raycast may not actually contain a result
                {
                    // The Unity UI system expects event data to have a screen position
                    // so even though this raycast came from a world space ray we must get a screen
                    // space position for the camera attached to this raycaster for compatability
                    Vector2 position = ovrRaycaster.GetScreenPosition(raycast);
                    leftData.delta = position - leftData.position;
                    leftData.position = position;
                }
            }
            // copy the apropriate data into right and middle slots
            PointerEventData rightData;
            GetPointerData(kMouseRightId, out rightData, true);
            CopyFromTo(leftData, rightData);
            rightData.button = PointerEventData.InputButton.Right;
            PointerEventData middleData;
            GetPointerData(kMouseMiddleId, out middleData, true);
            CopyFromTo(leftData, middleData);
            middleData.button = PointerEventData.InputButton.Middle;
#if ENABLE_LEGACY_INPUT_MANAGER
            m_MouseState.SetButtonState(PointerEventData.InputButton.Left, StateForMouseButton(0), leftData);
            m_MouseState.SetButtonState(PointerEventData.InputButton.Right, StateForMouseButton(1), rightData);
            m_MouseState.SetButtonState(PointerEventData.InputButton.Middle, StateForMouseButton(2), middleData);
#endif
            return m_MouseState;
        }
References UnityEngine.EventSystems.OVRInputModule.CopyFromTo(), OVRRaycaster.GetScreenPosition(), and OVRRaycaster.RaycastPointer().
GetExtraScrollDelta()
Vector2 UnityEngine.EventSystems.OVRInputModule.GetExtraScrollDelta () protected
Get extra scroll delta from gamepad.
Definition at line 931 of file OVRInputModule.cs.
        {
            Vector2 scrollDelta = new Vector2();
            if (useRightStickScroll)
            {
                Vector2 s = OVRInput.Get(OVRInput.Axis2D.SecondaryThumbstick);
                if (Mathf.Abs(s.x) < rightStickDeadZone) s.x = 0;
                if (Mathf.Abs(s.y) < rightStickDeadZone) s.y = 0;
                scrollDelta = s;
            }
            return scrollDelta;
        }
References OVRInput.Get().
GetGazeButtonState()
virtual PointerEventData.FramePressState UnityEngine.EventSystems.OVRInputModule.GetGazeButtonState () protected virtual
Get state of button corresponding to gaze pointer.
Returns
Definition at line 903 of file OVRInputModule.cs.
        {
            //todo: enable for Unity Input System
#if ENABLE_LEGACY_INPUT_MANAGER
            var pressed = Input.GetKeyDown(gazeClickKey) || OVRInput.GetDown(joyPadClickButton);
            var released = Input.GetKeyUp(gazeClickKey) || OVRInput.GetUp(joyPadClickButton);
#if UNITY_ANDROID && !UNITY_EDITOR
            pressed |= Input.GetMouseButtonDown(0);
            released |= Input.GetMouseButtonUp(0);
#endif
#else
            var pressed = OVRInput.GetDown(joyPadClickButton);
            var released = OVRInput.GetUp(joyPadClickButton);
#endif
            if (pressed && released)
                return PointerEventData.FramePressState.PressedAndReleased;
            if (pressed)
                return PointerEventData.FramePressState.Pressed;
            if (released)
                return PointerEventData.FramePressState.Released;
            return PointerEventData.FramePressState.NotChanged;
        }
References OVRInput.GetDown(), and OVRInput.GetUp().
GetGazePointerData()
virtual MouseState UnityEngine.EventSystems.OVRInputModule.GetGazePointerData () protected virtual
State for a pointer controlled by a world space ray. E.g. gaze pointer.
Returns
Definition at line 632 of file OVRInputModule.cs.
        {
            // Get the OVRRayPointerEventData reference
            OVRPointerEventData leftData;
            GetPointerData(kMouseLeftId, out leftData, true);
            leftData.Reset();
            //Now set the world space ray. This ray is what the user uses to point at UI elements
            leftData.worldSpaceRay = new Ray(rayTransform.position, rayTransform.forward);
            leftData.scrollDelta = GetExtraScrollDelta();
            //Populate some default values
            leftData.button = PointerEventData.InputButton.Left;
            leftData.useDragThreshold = true;
            // Perform raycast to find intersections with world
            eventSystem.RaycastAll(leftData, m_RaycastResultCache);
            var raycast = FindFirstRaycast(m_RaycastResultCache);
            leftData.pointerCurrentRaycast = raycast;
            m_RaycastResultCache.Clear();
            m_Cursor.SetCursorRay(rayTransform);
            OVRRaycaster ovrRaycaster = raycast.module as OVRRaycaster;
            // We're only interested in intersections from OVRRaycasters
            if (ovrRaycaster)
            {
                // The Unity UI system expects event data to have a screen position
                // so even though this raycast came from a world space ray we must get a screen
                // space position for the camera attached to this raycaster for compatability
                leftData.position = ovrRaycaster.GetScreenPosition(raycast);
                // Find the world position and normal the Graphic the ray intersected
                RectTransform graphicRect = raycast.gameObject.GetComponent<RectTransform>();
                if (graphicRect != null)
                {
                    // Set are gaze indicator with this world position and normal
                    Vector3 worldPos = raycast.worldPosition;
                    Vector3 normal = GetRectTransformNormal(graphicRect);
                    m_Cursor.SetCursorStartDest(rayTransform.position, worldPos, normal);
                }
            }
            // Now process physical raycast intersections
            OVRPhysicsRaycaster physicsRaycaster = raycast.module as OVRPhysicsRaycaster;
            if (physicsRaycaster)
            {
                Vector3 position = raycast.worldPosition;
                if (performSphereCastForGazepointer)
                {
                    // Here we cast a sphere into the scene rather than a ray. This gives a more accurate depth
                    // for positioning a circular gaze pointer
                    List<RaycastResult> results = new List<RaycastResult>();
                    physicsRaycaster.Spherecast(leftData, results, m_SpherecastRadius);
                    if (results.Count > 0 && results[0].distance < raycast.distance)
                    {
                        position = results[0].worldPosition;
                    }
                }
                leftData.position = physicsRaycaster.GetScreenPos(raycast.worldPosition);
                m_Cursor.SetCursorStartDest(rayTransform.position, position, raycast.worldNormal);
            }
            // Stick default data values in right and middle slots for compatability
            // copy the apropriate data into right and middle slots
            OVRPointerEventData rightData;
            GetPointerData(kMouseRightId, out rightData, true);
            CopyFromTo(leftData, rightData);
            rightData.button = PointerEventData.InputButton.Right;
            OVRPointerEventData middleData;
            GetPointerData(kMouseMiddleId, out middleData, true);
            CopyFromTo(leftData, middleData);
            middleData.button = PointerEventData.InputButton.Middle;
            m_MouseState.SetButtonState(PointerEventData.InputButton.Left,
                GetGazeButtonState(), leftData);
            m_MouseState.SetButtonState(PointerEventData.InputButton.Right,
                PointerEventData.FramePressState.NotChanged, rightData);
            m_MouseState.SetButtonState(PointerEventData.InputButton.Middle,
                PointerEventData.FramePressState.NotChanged, middleData);
            return m_MouseState;
        }
References UnityEngine.EventSystems.OVRInputModule.CopyFromTo(), UnityEngine.EventSystems.OVRInputModule.GetExtraScrollDelta(), UnityEngine.EventSystems.OVRInputModule.GetGazeButtonState(), UnityEngine.EventSystems.OVRInputModule.GetRectTransformNormal(), UnityEngine.EventSystems.OVRPhysicsRaycaster.GetScreenPos(), OVRRaycaster.GetScreenPosition(), and UnityEngine.EventSystems.OVRPhysicsRaycaster.Spherecast().
GetPointerData()
bool UnityEngine.EventSystems.OVRInputModule.GetPointerData (int id, out OVRPointerEventData data, bool create) protected
Definition at line 568 of file OVRInputModule.cs.
        {
            if (!m_VRRayPointerData.TryGetValue(id, out data) && create)
            {
                data = new OVRPointerEventData(eventSystem)
                {
                    pointerId = id,
                };
                m_VRRayPointerData.Add(id, data);
                return true;
            }
            return false;
        }
GetRawMoveVector()
Vector2 UnityEngine.EventSystems.OVRInputModule.GetRawMoveVector () private
Definition at line 281 of file OVRInputModule.cs.
        {
            Vector2 move = Vector2.zero;
            move.x = Input.GetAxisRaw(m_HorizontalAxis);
            move.y = Input.GetAxisRaw(m_VerticalAxis);
            if (Input.GetButtonDown(m_HorizontalAxis))
            {
                if (move.x < 0)
                    move.x = -1f;
                if (move.x > 0)
                    move.x = 1f;
            }
            if (Input.GetButtonDown(m_VerticalAxis))
            {
                if (move.y < 0)
                    move.y = -1f;
                if (move.y > 0)
                    move.y = 1f;
            }
            return move;
        }
GetRectTransformNormal()
static Vector3 UnityEngine.EventSystems.OVRInputModule.GetRectTransformNormal (RectTransform rectTransform) static private
For RectTransform, calculate it's normal in world space.
Definition at line 612 of file OVRInputModule.cs.
        {
            Vector3[] corners = new Vector3[4];
            rectTransform.GetWorldCorners(corners);
            Vector3 BottomEdge = corners[3] - corners[0];
            Vector3 LeftEdge = corners[1] - corners[0];
            rectTransform.GetWorldCorners(corners);
            return Vector3.Cross(BottomEdge, LeftEdge).normalized;
        }
IsModuleSupported()
override bool UnityEngine.EventSystems.OVRInputModule.IsModuleSupported ()
Definition at line 202 of file OVRInputModule.cs.
        {
            // Check for mouse presence instead of whether touch is supported,
            // as you can connect mouse to a tablet and in that case we'd want
            // to use StandaloneInputModule for non-touch input events.
            return m_AllowActivationOnMobileDevice || Input.mousePresent;
        }
IsPointerMoving()
static bool UnityEngine.EventSystems.OVRInputModule.IsPointerMoving (PointerEventData pointerEvent) static private
The purpose of this function is to allow us to switch between using the standard IsPointerMoving method for mouse driven pointers, but to always return true when it's a ray based pointer. All real-world ray-based input devices are always moving so for simplicity we just return true for them.
If PointerEventData.IsPointerMoving was virtual we could just override that in OVRRayPointerEventData.
Parameters
pointerEvent
Returns
Definition at line 825 of file OVRInputModule.cs.
        {
            if (pointerEvent.IsVRPointer())
                return true;
            else
                return pointerEvent.IsPointerMoving();
        }
Process()
override void UnityEngine.EventSystems.OVRInputModule.Process ()
Process this InputModule. Same as the StandaloneInputModule version, except that it calls ProcessMouseEvent twice, once for gaze pointers, and once for mouse pointers.
Definition at line 494 of file OVRInputModule.cs.
        {
            bool usedEvent = SendUpdateEventToSelectedObject();
            if (eventSystem.sendNavigationEvents)
            {
                if (!usedEvent)
                    usedEvent |= SendMoveEventToSelectedObject();
                if (!usedEvent)
                    SendSubmitEventToSelectedObject();
            }
            ProcessMouseEvent(GetGazePointerData());
#if !UNITY_ANDROID
            ProcessMouseEvent(GetCanvasPointerData());
#endif
        }
References UnityEngine.EventSystems.OVRInputModule.GetCanvasPointerData(), UnityEngine.EventSystems.OVRInputModule.GetGazePointerData(), UnityEngine.EventSystems.OVRInputModule.ProcessMouseEvent(), UnityEngine.EventSystems.OVRInputModule.SendMoveEventToSelectedObject(), and UnityEngine.EventSystems.OVRInputModule.SendSubmitEventToSelectedObject().
ProcessDrag()
override void UnityEngine.EventSystems.OVRInputModule.ProcessDrag (PointerEventData pointerEvent) protected
Exactly the same as the code from PointerInputModule, except that we call our own IsPointerMoving.
This would also not be necessary if PointerEventData.IsPointerMoving was virtual
Parameters
pointerEvent
Definition at line 857 of file OVRInputModule.cs.
        {
            Vector2 originalPosition = pointerEvent.position;
            bool moving = IsPointerMoving(pointerEvent);
            if (moving && pointerEvent.pointerDrag != null
                       && !pointerEvent.dragging
                       && ShouldStartDrag(pointerEvent))
            {
                if (pointerEvent.IsVRPointer())
                {
                    //adjust the position used based on swiping action. Allowing the user to
                    //drag items by swiping on the touchpad
                    pointerEvent.position = SwipeAdjustedPosition(originalPosition, pointerEvent);
                }
                ExecuteEvents.Execute(pointerEvent.pointerDrag, pointerEvent, ExecuteEvents.beginDragHandler);
                pointerEvent.dragging = true;
            }
            // Drag notification
            if (pointerEvent.dragging && moving && pointerEvent.pointerDrag != null)
            {
                if (pointerEvent.IsVRPointer())
                {
                    pointerEvent.position = SwipeAdjustedPosition(originalPosition, pointerEvent);
                }
                // Before doing drag we should cancel any pointer down state
                // And clear selection!
                if (pointerEvent.pointerPress != pointerEvent.pointerDrag)
                {
                    ExecuteEvents.Execute(pointerEvent.pointerPress, pointerEvent, ExecuteEvents.pointerUpHandler);
                    pointerEvent.eligibleForClick = false;
                    pointerEvent.pointerPress = null;
                    pointerEvent.rawPointerPress = null;
                }
                ExecuteEvents.Execute(pointerEvent.pointerDrag, pointerEvent, ExecuteEvents.dragHandler);
            }
        }
References UnityEngine.EventSystems.OVRInputModule.IsPointerMoving(), and UnityEngine.EventSystems.OVRInputModule.ShouldStartDrag().
ProcessMouseEvent()
void UnityEngine.EventSystems.OVRInputModule.ProcessMouseEvent (MouseState mouseData) private
Process all mouse events. This is the same as the StandaloneInputModule version except that it takes MouseState as a parameter, allowing it to be used for both Gaze and Mouse pointerss.
Definition at line 461 of file OVRInputModule.cs.
        {
            var pressed = mouseData.AnyPressesThisFrame();
            var released = mouseData.AnyReleasesThisFrame();
            var leftButtonData = mouseData.GetButtonState(PointerEventData.InputButton.Left).eventData;
            if (!UseMouse(pressed, released, leftButtonData.buttonData))
                return;
            // Process the first mouse button fully
            ProcessMousePress(leftButtonData);
            ProcessMove(leftButtonData.buttonData);
            ProcessDrag(leftButtonData.buttonData);
            // Now process right / middle clicks
            ProcessMousePress(mouseData.GetButtonState(PointerEventData.InputButton.Right).eventData);
            ProcessDrag(mouseData.GetButtonState(PointerEventData.InputButton.Right).eventData.buttonData);
            ProcessMousePress(mouseData.GetButtonState(PointerEventData.InputButton.Middle).eventData);
            ProcessDrag(mouseData.GetButtonState(PointerEventData.InputButton.Middle).eventData.buttonData);
            if (!Mathf.Approximately(leftButtonData.buttonData.scrollDelta.sqrMagnitude, 0.0f))
            {
                var scrollHandler = ExecuteEvents.GetEventHandler<IScrollHandler>(
                    leftButtonData.buttonData.pointerCurrentRaycast.gameObject);
                ExecuteEvents.ExecuteHierarchy(scrollHandler, leftButtonData.buttonData, ExecuteEvents.scrollHandler);
            }
        }
References UnityEngine.EventSystems.OVRInputModule.ProcessDrag(), UnityEngine.EventSystems.OVRInputModule.ProcessMousePress(), and UnityEngine.EventSystems.OVRInputModule.UseMouse().
ProcessMousePress()
void UnityEngine.EventSystems.OVRInputModule.ProcessMousePress (MouseButtonEventData data) private
Process the current mouse press.
Definition at line 343 of file OVRInputModule.cs.
        {
            var pointerEvent = data.buttonData;
            var currentOverGo = pointerEvent.pointerCurrentRaycast.gameObject;
            // PointerDown notification
            if (data.PressedThisFrame())
            {
                pointerEvent.eligibleForClick = true;
                pointerEvent.delta = Vector2.zero;
                pointerEvent.dragging = false;
                pointerEvent.useDragThreshold = true;
                pointerEvent.pressPosition = pointerEvent.position;
                if (pointerEvent.IsVRPointer())
                {
#if ENABLE_LEGACY_INPUT_MANAGER
                    pointerEvent.SetSwipeStart(Input.mousePosition);
#endif
                }
                pointerEvent.pointerPressRaycast = pointerEvent.pointerCurrentRaycast;
                DeselectIfSelectionChanged(currentOverGo, pointerEvent);
                // search for the control that will receive the press
                // if we can't find a press handler set the press
                // handler to be what would receive a click.
                var newPressed =
                    ExecuteEvents.ExecuteHierarchy(currentOverGo, pointerEvent, ExecuteEvents.pointerDownHandler);
                // didnt find a press handler... search for a click handler
                if (newPressed == null)
                    newPressed = ExecuteEvents.GetEventHandler<IPointerClickHandler>(currentOverGo);
                // Debug.Log("Pressed: " + newPressed);
                float time = Time.unscaledTime;
                if (newPressed == pointerEvent.lastPress)
                {
                    var diffTime = time - pointerEvent.clickTime;
                    if (diffTime < 0.3f)
                        ++pointerEvent.clickCount;
                    else
                        pointerEvent.clickCount = 1;
                    pointerEvent.clickTime = time;
                }
                else
                {
                    pointerEvent.clickCount = 1;
                }
                pointerEvent.pointerPress = newPressed;
                pointerEvent.rawPointerPress = currentOverGo;
                pointerEvent.clickTime = time;
                // Save the drag handler as well
                pointerEvent.pointerDrag = ExecuteEvents.GetEventHandler<IDragHandler>(currentOverGo);
                if (pointerEvent.pointerDrag != null)
                    ExecuteEvents.Execute(pointerEvent.pointerDrag, pointerEvent,
                        ExecuteEvents.initializePotentialDrag);
            }
            // PointerUp notification
            if (data.ReleasedThisFrame())
            {
                // Debug.Log("Executing pressup on: " + pointer.pointerPress);
                ExecuteEvents.Execute(pointerEvent.pointerPress, pointerEvent, ExecuteEvents.pointerUpHandler);
                // Debug.Log("KeyCode: " + pointer.eventData.keyCode);
                // see if we mouse up on the same element that we clicked on...
                var pointerUpHandler = ExecuteEvents.GetEventHandler<IPointerClickHandler>(currentOverGo);
                // PointerClick and Drop events
                if (pointerEvent.pointerPress == pointerUpHandler && pointerEvent.eligibleForClick)
                {
                    ExecuteEvents.Execute(pointerEvent.pointerPress, pointerEvent, ExecuteEvents.pointerClickHandler);
                }
                else if (pointerEvent.pointerDrag != null)
                {
                    ExecuteEvents.ExecuteHierarchy(currentOverGo, pointerEvent, ExecuteEvents.dropHandler);
                }
                pointerEvent.eligibleForClick = false;
                pointerEvent.pointerPress = null;
                pointerEvent.rawPointerPress = null;
                if (pointerEvent.pointerDrag != null && pointerEvent.dragging)
                    ExecuteEvents.Execute(pointerEvent.pointerDrag, pointerEvent, ExecuteEvents.endDragHandler);
                pointerEvent.dragging = false;
                pointerEvent.pointerDrag = null;
                // redo pointer enter / exit to refresh state
                // so that if we moused over somethign that ignored it before
                // due to having pressed on something else
                // it now gets it.
                if (currentOverGo != pointerEvent.pointerEnter)
                {
                    HandlePointerExitAndEnter(pointerEvent, null);
                    HandlePointerExitAndEnter(pointerEvent, currentOverGo);
                }
            }
        }
SendMoveEventToSelectedObject()
bool UnityEngine.EventSystems.OVRInputModule.SendMoveEventToSelectedObject () private
Process keyboard events.
Definition at line 309 of file OVRInputModule.cs.
        {
            float time = Time.unscaledTime;
            if (!AllowMoveEventProcessing(time))
                return false;
            Vector2 movement = GetRawMoveVector();
            // Debug.Log(m_ProcessingEvent.rawType + " axis:" + m_AllowAxisEvents + " value:" + "(" + x + "," + y + ")");
            var axisEventData = GetAxisEventData(movement.x, movement.y, 0.6f);
            if (!Mathf.Approximately(axisEventData.moveVector.x, 0f)
                || !Mathf.Approximately(axisEventData.moveVector.y, 0f))
            {
                ExecuteEvents.Execute(eventSystem.currentSelectedGameObject, axisEventData, ExecuteEvents.moveHandler);
            }
            m_NextAction = time + 1f / m_InputActionsPerSecond;
            return axisEventData.used;
        }
SendSubmitEventToSelectedObject()
bool UnityEngine.EventSystems.OVRInputModule.SendSubmitEventToSelectedObject () private
Process submit keys.
Definition at line 253 of file OVRInputModule.cs.
        {
            if (eventSystem.currentSelectedGameObject == null)
                return false;
            var data = GetBaseEventData();
#if ENABLE_LEGACY_INPUT_MANAGER
            if (Input.GetButtonDown(m_SubmitButton))
                ExecuteEvents.Execute(eventSystem.currentSelectedGameObject, data, ExecuteEvents.submitHandler);
            if (Input.GetButtonDown(m_CancelButton))
                ExecuteEvents.Execute(eventSystem.currentSelectedGameObject, data, ExecuteEvents.cancelHandler);
#endif
            return data.used;
        }
References UnityEngine.EventSystems.OVRInputModule.m_CancelButton, and UnityEngine.EventSystems.OVRInputModule.m_SubmitButton.
SendUpdateEventToSelectedObject()
bool UnityEngine.EventSystems.OVRInputModule.SendUpdateEventToSelectedObject () private
Definition at line 330 of file OVRInputModule.cs.
        {
            if (eventSystem.currentSelectedGameObject == null)
                return false;
            var data = GetBaseEventData();
            ExecuteEvents.Execute(eventSystem.currentSelectedGameObject, data, ExecuteEvents.updateSelectedHandler);
            return data.used;
        }
ShouldActivateModule()
override bool UnityEngine.EventSystems.OVRInputModule.ShouldActivateModule ()
Definition at line 210 of file OVRInputModule.cs.
        {
            if (!base.ShouldActivateModule())
                return false;
#if ENABLE_LEGACY_INPUT_MANAGER
            var shouldActivate = Input.GetButtonDown(m_SubmitButton);
            shouldActivate |= Input.GetButtonDown(m_CancelButton);
            shouldActivate |= !Mathf.Approximately(Input.GetAxisRaw(m_HorizontalAxis), 0.0f);
            shouldActivate |= !Mathf.Approximately(Input.GetAxisRaw(m_VerticalAxis), 0.0f);
            shouldActivate |= (m_MousePosition - m_LastMousePosition).sqrMagnitude > 0.0f;
            shouldActivate |= Input.GetMouseButtonDown(0);
            return shouldActivate;
#else
            return false;
#endif
        }
ShouldStartDrag()
bool UnityEngine.EventSystems.OVRInputModule.ShouldStartDrag (PointerEventData pointerEvent) private
New version of ShouldStartDrag implemented first in PointerInputModule. This version differs in that for ray based pointers it makes a decision about whether a drag should start based on the angular change the pointer has made so far, as seen from the camera. This also works when the world space ray is translated rather than rotated, since the beginning and end of the movement are considered as angle from the same point.
Definition at line 786 of file OVRInputModule.cs.
        {
            if (!pointerEvent.useDragThreshold)
                return true;
            if (!pointerEvent.IsVRPointer())
            {
                // Same as original behaviour for canvas based pointers
                return (pointerEvent.pressPosition - pointerEvent.position).sqrMagnitude >=
                       eventSystem.pixelDragThreshold * eventSystem.pixelDragThreshold;
            }
            else
            {
#if UNITY_ANDROID && !UNITY_EDITOR // On android allow swiping to start drag
                if (useSwipeScroll && ((Vector3)pointerEvent.GetSwipeStart() - Input.mousePosition).magnitude > swipeDragThreshold)
                {
                    return true;
                }
#endif
                // When it's not a screen space pointer we have to look at the angle it moved rather than the pixels distance
                // For gaze based pointing screen-space distance moved will always be near 0
                Vector3 cameraPos = pointerEvent.pressEventCamera.transform.position;
                Vector3 pressDir = (pointerEvent.pointerPressRaycast.worldPosition - cameraPos).normalized;
                Vector3 currentDir = (pointerEvent.pointerCurrentRaycast.worldPosition - cameraPos).normalized;
                return Vector3.Dot(pressDir, currentDir) < Mathf.Cos(Mathf.Deg2Rad * (angleDragThreshold));
            }
        }
SwipeAdjustedPosition()
Vector2 UnityEngine.EventSystems.OVRInputModule.SwipeAdjustedPosition (Vector2 originalPosition, PointerEventData pointerEvent) protected
Definition at line 833 of file OVRInputModule.cs.
        {
#if UNITY_ANDROID && !UNITY_EDITOR
            // On android we use the touchpad position (accessed through Input.mousePosition) to modify
            // the effective cursor position for events related to dragging. This allows the user to
            // use the touchpad to drag draggable UI elements
            if (useSwipeScroll)
            {
                Vector2 delta = (Vector2)Input.mousePosition - pointerEvent.GetSwipeStart();
                if (InvertSwipeXAxis)
                    delta.x *= -1;
                return originalPosition + delta * swipeDragScale;
            }
#endif
            return originalPosition;
        }
UpdateModule()
override void UnityEngine.EventSystems.OVRInputModule.UpdateModule ()
Definition at line 194 of file OVRInputModule.cs.
        {
#if ENABLE_LEGACY_INPUT_MANAGER
            m_LastMousePosition = m_MousePosition;
            m_MousePosition = Input.mousePosition;
#endif
        }
UseMouse()
static bool UnityEngine.EventSystems.OVRInputModule.UseMouse (bool pressed, bool released, PointerEventData pointerData) static private
Decide if mouse events need to be processed this frame. Same as StandloneInputModule except that the IsPointerMoving method from this class is used, instead of the method on PointerEventData.
Definition at line 517 of file OVRInputModule.cs.
        {
            if (pressed || released || IsPointerMoving(pointerData) || pointerData.IsScrolling())
                return true;
            return false;
        }
References UnityEngine.EventSystems.OVRInputModule.IsPointerMoving().
Member Data Documentation
activeGraphicRaycaster
OVRRaycaster UnityEngine.EventSystems.OVRInputModule.activeGraphicRaycaster
Definition at line 69 of file OVRInputModule.cs.
angleDragThreshold
float UnityEngine.EventSystems.OVRInputModule.angleDragThreshold = 1
Definition at line 73 of file OVRInputModule.cs.
gazeClickKey
KeyCode UnityEngine.EventSystems.OVRInputModule.gazeClickKey = KeyCode.Space
Definition at line 40 of file OVRInputModule.cs.
InvertSwipeXAxis
bool UnityEngine.EventSystems.OVRInputModule.InvertSwipeXAxis = false
Definition at line 64 of file OVRInputModule.cs.
joyPadClickButton
OVRInput.Button UnityEngine.EventSystems.OVRInputModule.joyPadClickButton = OVRInput.Button.One
Definition at line 37 of file OVRInputModule.cs.
m_AllowActivationOnMobileDevice
bool UnityEngine.EventSystems.OVRInputModule.m_AllowActivationOnMobileDevice private
Definition at line 150 of file OVRInputModule.cs.
m_CancelButton
string UnityEngine.EventSystems.OVRInputModule.m_CancelButton = "Cancel" private
Name of the submit button.
Definition at line 144 of file OVRInputModule.cs.
m_Cursor
OVRCursor UnityEngine.EventSystems.OVRInputModule.m_Cursor
Definition at line 34 of file OVRInputModule.cs.
m_HorizontalAxis
string UnityEngine.EventSystems.OVRInputModule.m_HorizontalAxis = "Horizontal" private
Definition at line 126 of file OVRInputModule.cs.
m_InputActionsPerSecond
float UnityEngine.EventSystems.OVRInputModule.m_InputActionsPerSecond = 10 private
Definition at line 147 of file OVRInputModule.cs.
m_LastMousePosition
Vector2 UnityEngine.EventSystems.OVRInputModule.m_LastMousePosition private
Definition at line 95 of file OVRInputModule.cs.
m_MousePosition
Vector2 UnityEngine.EventSystems.OVRInputModule.m_MousePosition private
Definition at line 96 of file OVRInputModule.cs.
m_MouseState
readonly MouseState UnityEngine.EventSystems.OVRInputModule.m_MouseState = new MouseState() private
Definition at line 622 of file OVRInputModule.cs.
m_NextAction
float UnityEngine.EventSystems.OVRInputModule.m_NextAction private
Definition at line 93 of file OVRInputModule.cs.
m_SpherecastRadius
float UnityEngine.EventSystems.OVRInputModule.m_SpherecastRadius = 1.0f private
Definition at line 76 of file OVRInputModule.cs.
m_SubmitButton
string UnityEngine.EventSystems.OVRInputModule.m_SubmitButton = "Submit" private
Name of the submit button.
Definition at line 138 of file OVRInputModule.cs.
m_VerticalAxis
string UnityEngine.EventSystems.OVRInputModule.m_VerticalAxis = "Vertical" private
Name of the vertical axis for movement (if axis events are used).
Definition at line 132 of file OVRInputModule.cs.
m_VRRayPointerData
Dictionary<int, OVRPointerEventData> UnityEngine.EventSystems.OVRInputModule.m_VRRayPointerData = new Dictionary<int, OVRPointerEventData>() protected
Definition at line 565 of file OVRInputModule.cs.
performSphereCastForGazepointer
bool UnityEngine.EventSystems.OVRInputModule.performSphereCastForGazepointer
Definition at line 44 of file OVRInputModule.cs.
rayTransform
Transform UnityEngine.EventSystems.OVRInputModule.rayTransform
Definition at line 32 of file OVRInputModule.cs.
rightStickDeadZone
float UnityEngine.EventSystems.OVRInputModule.rightStickDeadZone = 0.15f
Definition at line 51 of file OVRInputModule.cs.
swipeDragScale
float UnityEngine.EventSystems.OVRInputModule.swipeDragScale = 1f
Definition at line 61 of file OVRInputModule.cs.
swipeDragThreshold
float UnityEngine.EventSystems.OVRInputModule.swipeDragThreshold = 2
Definition at line 58 of file OVRInputModule.cs.
useRightStickScroll
bool UnityEngine.EventSystems.OVRInputModule.useRightStickScroll = true
Definition at line 48 of file OVRInputModule.cs.
useSwipeScroll
bool UnityEngine.EventSystems.OVRInputModule.useSwipeScroll = true
Definition at line 55 of file OVRInputModule.cs.
Property Documentation
allowActivationOnMobileDevice
bool UnityEngine.EventSystems.OVRInputModule.allowActivationOnMobileDevice get set
Definition at line 152 of file OVRInputModule.cs.
        {
            get { return m_AllowActivationOnMobileDevice; }
            set { m_AllowActivationOnMobileDevice = value; }
        }
cancelButton
string UnityEngine.EventSystems.OVRInputModule.cancelButton get set
Definition at line 188 of file OVRInputModule.cs.
        {
            get { return m_CancelButton; }
            set { m_CancelButton = value; }
        }
horizontalAxis
string UnityEngine.EventSystems.OVRInputModule.horizontalAxis get set
Name of the horizontal axis for movement (if axis events are used).
Definition at line 167 of file OVRInputModule.cs.
        {
            get { return m_HorizontalAxis; }
            set { m_HorizontalAxis = value; }
        }
inputActionsPerSecond
float UnityEngine.EventSystems.OVRInputModule.inputActionsPerSecond get set
Definition at line 158 of file OVRInputModule.cs.
        {
            get { return m_InputActionsPerSecond; }
            set { m_InputActionsPerSecond = value; }
        }
inputMode
InputMode UnityEngine.EventSystems.OVRInputModule.inputMode get
Definition at line 119 of file OVRInputModule.cs.
        {
            get { return InputMode.Mouse; }
        }
submitButton
string UnityEngine.EventSystems.OVRInputModule.submitButton get set
Definition at line 182 of file OVRInputModule.cs.
        {
            get { return m_SubmitButton; }
            set { m_SubmitButton = value; }
        }
verticalAxis
string UnityEngine.EventSystems.OVRInputModule.verticalAxis get set
Name of the vertical axis for movement (if axis events are used).
Definition at line 176 of file OVRInputModule.cs.
        {
            get { return m_VerticalAxis; }
            set { m_VerticalAxis = value; }
        }
The documentation for this class was generated from the following file:
Assets/Oculus/VR/Scripts/Util/OVRInputModule.cs