VR_Test: Meta.Voice.Samples.BuiltInTimer.TimerController Class Reference
Meta.Voice.Samples.BuiltInTimer.TimerController Class Reference
Represents a countdown timer.
Public Member Functions
void DeleteTimer ()
Deletes the timer. It corresponds to the wit intent "wit$delete_timer".
void CreateTimer (string[] entityValues)
Creates a timer. It corresponds to the wit intent "wit$create_timer".
void GetTimerIntent ()
Displays current timer value. It corresponds to "wit$get_timer".
void PauseTimer ()
Pauses the timer. It corresponds to the wit intent "wit$pause_timer".
void ResumeTimer ()
It corresponds to the wit intent "wit$resume_timer".
void SubtractTimeTimer (string[] entityValues)
Subtracts time from the timer. It corresponds to the wit intent "wit$subtract_time_timer".
void AddTimeToTimer (string[] entityValues)
Adds time to the timer. It corresponds to the wit intent "wit$add_time_timer".
double GetRemainingTime ()
Returns the remaining time (in sec) of the countdown timer.
string GetFormattedTimeFromSeconds ()
Returns time in the format of min:sec.
Public Attributes
Text logText
AudioClip[] timesUpSounds
Private Member Functions
void Update ()
void Log (string msg)
void OnElapsedTime ()
Buzzes and resets the timer.
bool ParseTime (string[] entityValues, out double time)
Parses entity values to get a resulting time value in seconds.
Private Attributes
double _time = 0
bool _timerExist = false
bool _timerRunning = false
Detailed Description
Represents a countdown timer.
Definition at line 31 of file TimerController.cs.
Member Function Documentation
AddTimeToTimer()
void Meta.Voice.Samples.BuiltInTimer.TimerController.AddTimeToTimer (string[] entityValues)
Adds time to the timer. It corresponds to the wit intent "wit$add_time_timer".
Parameters
entityValues
Definition at line 175 of file TimerController.cs.
        {
            if (!_timerExist)
            {
                Log("Error: No Timer is created.");
                return;
            }
            if (ParseTime(entityValues, out var time))
            {
                _time += time;
                var msg = $"{entityValues[0]} {entityValues[1]}(s) were added to the timer.";
                Log(msg);
            }
            else
            {
                Log("Error in AddTimeToTimer(): Could not parse with reply.");
            }
        }
References Meta.Voice.Samples.BuiltInTimer.TimerController.ParseTime().
CreateTimer()
void Meta.Voice.Samples.BuiltInTimer.TimerController.CreateTimer (string[] entityValues)
Creates a timer. It corresponds to the wit intent "wit$create_timer".
Parameters
entityValues countdown in minutes.
Definition at line 96 of file TimerController.cs.
        {
            if (_timerExist)
            {
                VLog.W("A timer already exist.");
                return;
            }
            if (ParseTime(entityValues, out _time))
            {
                _timerExist = true;
                _timerRunning = true;
                Log($"Countdown Timer is set for {entityValues[0]} {entityValues[1]}(s).");
            }
        }
References Meta.Voice.Samples.BuiltInTimer.TimerController.ParseTime(), and Meta.WitAi.VLog.W().
DeleteTimer()
void Meta.Voice.Samples.BuiltInTimer.TimerController.DeleteTimer ()
Deletes the timer. It corresponds to the wit intent "wit$delete_timer".
Definition at line 78 of file TimerController.cs.
        {
            if (!_timerExist)
            {
                Log("Error: There is no timer to delete.");
                return;
            }
            _timerExist = false;
            _time = 0;
            _timerRunning = false;
            Log("Timer deleted.");
        }
GetFormattedTimeFromSeconds()
string Meta.Voice.Samples.BuiltInTimer.TimerController.GetFormattedTimeFromSeconds ()
Returns time in the format of min:sec.
Returns
Definition at line 208 of file TimerController.cs.
        {
            if (_time >= TimeSpan.MaxValue.TotalSeconds)
            {
                _time = TimeSpan.MaxValue.TotalSeconds - 1;
                Log("Error: Hit max time");
            }
            TimeSpan span = TimeSpan.FromSeconds(_time);
            return $"{Math.Floor(span.TotalHours)}:{span.Minutes:00}:{span.Seconds:00}.{Math.Floor(span.Milliseconds/100f)}";
        }
GetRemainingTime()
double Meta.Voice.Samples.BuiltInTimer.TimerController.GetRemainingTime ()
Returns the remaining time (in sec) of the countdown timer.
Returns
Definition at line 199 of file TimerController.cs.
        {
            return _time;
        }
GetTimerIntent()
void Meta.Voice.Samples.BuiltInTimer.TimerController.GetTimerIntent ()
Displays current timer value. It corresponds to "wit$get_timer".
Definition at line 115 of file TimerController.cs.
        {
            // Show the remaining time of the countdown timer.
            var msg = GetFormattedTimeFromSeconds();
            //Log(msg);
        }
References Meta.Voice.Samples.BuiltInTimer.TimerController.GetFormattedTimeFromSeconds().
Log()
void Meta.Voice.Samples.BuiltInTimer.TimerController.Log (string msg) private
Definition at line 56 of file TimerController.cs.
        {
            Debug.Log(msg);
            logText.text = msg;
        }
OnElapsedTime()
void Meta.Voice.Samples.BuiltInTimer.TimerController.OnElapsedTime () private
Buzzes and resets the timer.
Definition at line 65 of file TimerController.cs.
        {
            _time = 0;
            _timerRunning = false;
            _timerExist = false;
            Log("Your timer is complete.");
            AudioClip timesUpSfx = timesUpSounds[UnityEngine.Random.Range(0, timesUpSounds.Length)];
            AudioSource.PlayClipAtPoint(timesUpSfx, Vector3.zero);
        }
ParseTime()
bool Meta.Voice.Samples.BuiltInTimer.TimerController.ParseTime (string[] entityValues, out double time) private
Parses entity values to get a resulting time value in seconds.
Parameters
entityValues The entity value results from a Response Handler
time The parsed time
Returns
The parsed time in seconds or the current value of _time
Exceptions
ArgumentException
Definition at line 226 of file TimerController.cs.
        {
            time = _time;
            if (entityValues.Length > 0 && double.TryParse(entityValues[0], out time))
            {
                if (entityValues.Length < 2)
                {
                    throw new ArgumentException("Entities being parsed must include time value and unit.");
                }
                // If entity was not included in the result it will be empty, but the array will still be size 2
                if (!string.IsNullOrEmpty(entityValues[1]))
                {
                    switch (entityValues[1])
                    {
                        case "minute":
                            time *= 60;
                            break;
                        case "hour":
                            time *= 60 * 60;
                            break;
                    }
                }
                return true;
            }
            return false;
        }
PauseTimer()
void Meta.Voice.Samples.BuiltInTimer.TimerController.PauseTimer ()
Pauses the timer. It corresponds to the wit intent "wit$pause_timer".
Definition at line 125 of file TimerController.cs.
        {
            _timerRunning = false;
            Log("Timer paused.");
        }
ResumeTimer()
void Meta.Voice.Samples.BuiltInTimer.TimerController.ResumeTimer ()
It corresponds to the wit intent "wit$resume_timer".
Definition at line 134 of file TimerController.cs.
        {
            _timerRunning = true;
            Log("Timer resumed.");
        }
SubtractTimeTimer()
void Meta.Voice.Samples.BuiltInTimer.TimerController.SubtractTimeTimer (string[] entityValues)
Subtracts time from the timer. It corresponds to the wit intent "wit$subtract_time_timer".
Parameters
entityValues
Definition at line 144 of file TimerController.cs.
        {
            if (!_timerExist)
            {
                Log("Error: No Timer is created.");
                return;
            }
            if (ParseTime(entityValues, out var time))
            {
                var msg = $"{entityValues[0]} {entityValues[1]}(s) were subtracted from the timer.";
                _time -= time;
                if (_time < 0)
                {
                    _time = 0;
                    Log(msg);
                    return;
                }
                Log(msg);
            }
            else
            {
                Log("Error in Subtract_time_timer(): Could not parse the wit reply.");
            }
        }
References Meta.Voice.Samples.BuiltInTimer.TimerController.ParseTime().
Update()
void Meta.Voice.Samples.BuiltInTimer.TimerController.Update () private
Definition at line 43 of file TimerController.cs.
        {
            if (_timerExist && _timerRunning)
            {
                _time -= Time.deltaTime;
                if (_time < 0)
                {
                    // Raise a ring.
                    OnElapsedTime();
                }
            }
        }
Member Data Documentation
_time
double Meta.Voice.Samples.BuiltInTimer.TimerController._time = 0 private
Definition at line 33 of file TimerController.cs.
_timerExist
bool Meta.Voice.Samples.BuiltInTimer.TimerController._timerExist = false private
Definition at line 34 of file TimerController.cs.
_timerRunning
bool Meta.Voice.Samples.BuiltInTimer.TimerController._timerRunning = false private
Definition at line 35 of file TimerController.cs.
logText
Text Meta.Voice.Samples.BuiltInTimer.TimerController.logText
Definition at line 38 of file TimerController.cs.
timesUpSounds
AudioClip [] Meta.Voice.Samples.BuiltInTimer.TimerController.timesUpSounds
Definition at line 40 of file TimerController.cs.
The documentation for this class was generated from the following file:
Assets/Oculus/Voice/Samples/BuiltInTimer/Scripts/TimerController.cs