VR_Test: ARAVRInput Class Reference
ARAVRInput Class Reference
ARAVRInput 클래스는 VR/AR에 대응하는 Input 기능을 구현하는 클래스다.
Public Types
enum Button
다양한 기기에서 사용할 버튼의 종류를 미리 정의해둔 것이다.
enum Controller
기기별로 다른 컨트롤러를 미리 정의해둔 것이다.
Static Public Member Functions
static bool Get (Button virtualMask, Controller hand=Controller.RTouch)
컨트롤러의 특정 버튼을 누르고 있는 동안 true를 반환하는 함수이다.
static bool GetDown (Button virtualMask, Controller hand=Controller.RTouch)
컨트롤러의 특정 버튼을 눌렀을 때 true를 반환하는 함수이다.
static bool GetUp (Button virtualMask, Controller hand=Controller.RTouch)
컨트롤러의 특정 버튼을 눌렀다 떼었을 때 true를 반환하는 함수이다.
static float GetAxis (string axis, Controller hand=Controller.LTouch)
컨트롤러의 Axis 입력을 반환하는 함수이다.
static void Recenter ()
VR 카메라가 바라보는 방향을 기준으로 센터를 잡는다.
static void Recenter (Transform target, Vector3 direction)
타겟이 바라보는 방향을 기준으로 센터를 잡는다.
static void DrawCrosshair (Transform crosshair, bool isHand=true, Controller hand=Controller.RTouch)
레이가 닿는 곳에 크로스헤어를 위치시키는 함수이다.
static void PlayVibration (Controller hand)
컨트롤러의 진동을 실행하는 함수이다.
static void PlayVibration (float duration, float frequency, float amplitude, Controller hand)
컨트롤러에 진동을 실행하는 함수이다.
Properties
static Vector3 RHandPosition [get]
오른쪽 컨트롤러의 위치를 얻어오는 프로퍼티이다.
static Vector3 RHandDirection [get]
오른쪽 컨트롤러의 방향를 얻어오는 프로퍼티이다.
static Vector3 LHandPosition [get]
왼쪽 컨트롤러의 위치를 얻어오는 프로퍼티이다.
static Vector3 LHandDirection [get]
왼쪽 컨트롤러의 방향를 얻어오는 프로퍼티이다.
static Transform RHand [get]
씬에 등록된 오른쪽 컨트롤러 찾아 반환하는 프로퍼티이다.
static Transform LHand [get]
씬에 등록된 오른쪽 컨트롤러 찾아 반환하는 프로퍼티이다.
Static Private Attributes
static Transform rHand
static Transform lHand
Detailed Description
ARAVRInput 클래스는 VR/AR에 대응하는 Input 기능을 구현하는 클래스다.
Definition at line 8 of file ARAVRInput.cs.
Member Enumeration Documentation
Button
enum ARAVRInput.Button
다양한 기기에서 사용할 버튼의 종류를 미리 정의해둔 것이다.
미리 정의해 놓은 버튼을 기기별로 다르게 매핑해둔 것이다.
Definition at line 22 of file ARAVRInput.cs.
    {
#if BUILD_PLATFORM_PC
        One = ButtonTarget.Fire1,
        Two = ButtonTarget.Jump,
        Thumbstick = ButtonTarget.Fire1,
        IndexTrigger = ButtonTarget.Fire3,
        HandTrigger = ButtonTarget.Fire2
#elif TARGET_DEVICE_OCULUS
        One = OVRInput.Button.One,
        Two = OVRInput.Button.Two,
        Thumbstick = OVRInput.Button.PrimaryThumbstick,
        IndexTrigger = OVRInput.Button.PrimaryIndexTrigger,
        HandTrigger = OVRInput.Button.PrimaryHandTrigger
#endif      // BUILD_PLATFORM_PC
    }       // Button
Controller
enum ARAVRInput.Controller
기기별로 다른 컨트롤러를 미리 정의해둔 것이다.
Definition at line 40 of file ARAVRInput.cs.
    {
#if BUILD_PLATFORM_PC
        LTouch,
        RTouch
#elif TARGET_DEVICE_OCULUS
        LTouch = OVRInput.Controller.LTouch,
        RTouch = OVRInput.Controller.RTouch
#endif      // BUILD_PLATFORM_PC
    }       // Controller
Member Function Documentation
DrawCrosshair()
static void ARAVRInput.DrawCrosshair (Transform crosshair, bool isHand = true, Controller hand = Controller::RTouch) static
레이가 닿는 곳에 크로스헤어를 위치시키는 함수이다.
Parameters
crosshair 컨트롤러에 정면에 그릴 크로스헤어 오브젝트의 Transform을 받아온다.
isHand 컨트롤러가 존재하는지 여부를 받아온다. @Param hand 여전히 잘 모르겠음.
Definition at line 327 of file ARAVRInput.cs.
    {
        Ray ray = default;
        // 컨트롤러의 위치와 방향을 이용해 레이 제작
        if (isHand)
        {
#if BUILD_PLATFORM_PC
            ray = Camera.main.ScreenPointToRay(Input.mousePosition);
#elif TARGET_DEVICE_OCULUS
            if(hand == Controller.RTouch)
            {
                ray = new Ray(RHandPosition, RHandDirection);
            }       // if : 오른쪽 컨트롤러에서 레이를 쏘는 경우
            else
            {
                ray = new Ray(LHandPosition, LHandDirection);
            }       // else : 왼쪽 컨트롤러에서 레이를 쏘는 경우
#endif      // BUILD_PLATFORM_PC
        }
        else
        {
            // 카메라를 기준으로 화면의 정중앙으로 레이를 제작
            ray = new Ray(Camera.main.transform.position, Camera.main.transform.forward);
        }
        // 눈에 안보이는 Plane을 만든다.
        Plane plane = new Plane(Vector3.up, 0);
        float distance = 0;
        // plane을 이용해 ray를 쏜다
        if (plane.Raycast(ray, out distance))
        {
            // 레이의 GetPoint 함수를 이용해 충돌 지점의 위치를 가져온다.
            crosshair.position = ray.GetPoint(distance);
            crosshair.forward = -Camera.main.transform.forward;
            // 크로스 헤어의 크기를 최소 기본 크기에서 거리에 따라 더 커지도록 한다.
            crosshair.localScale = originScale * Mathf.Max(1.0f, distance);
        }       // if : 레이에 충돌한 지점이 있는 경우
        else
        {
            crosshair.position = ray.origin + ray.direction * 100.0f;
            crosshair.forward = -Camera.main.transform.forward;
            distance = (crosshair.position - ray.origin).magnitude;
            crosshair.localScale = originScale * Mathf.Max(1.0f, distance);
        }       // else : 레이에 충돌한 지점이 없는 경우
    }       // DrawCrosshair
References LHandDirection, LHandPosition, RHandDirection, and RHandPosition.
Get()
static bool ARAVRInput.Get (Button virtualMask, Controller hand = Controller::RTouch) static
컨트롤러의 특정 버튼을 누르고 있는 동안 true를 반환하는 함수이다.
Parameters
virtualMask 미리 정의된 버튼의 종류를 받아온다.
hand 어느 컨트롤러의 버튼을 누를 것인지 받아온다.
Returns
virtualMask에 들어온 값을 ButtonTarget 타입으로 변환해서 리턴한다.
Definition at line 226 of file ARAVRInput.cs.
    {
#if BUILD_PLATFORM_PC
        return Input.GetButton(((ButtonTarget)virtualMask).ToString());
#elif TARGET_DEVICE_OCULUS
        return OVRInput.Get((OVRInput.Button)virtualMask, (OVRInput.Controller)hand);
#else
        return false;
#endif      // BUILD_PLATFORM_PC
    }       // Get
References OVRInput.Get().
GetAxis()
static float ARAVRInput.GetAxis (string axis, Controller hand = Controller::LTouch) static
컨트롤러의 Axis 입력을 반환하는 함수이다.
Parameters
axis Horizontal, Vertical 값을 받아온다.
hand 어느 컨트롤러의 버튼을 누를 것인지 받아온다.
Returns
컨트롤러의 Axis 입력을 실수 형태로 리턴한다.
Definition at line 278 of file ARAVRInput.cs.
    {
#if BUILD_PLATFORM_PC
        return Input.GetAxis(axis);
#elif TARGET_DEVICE_OCULUS
        if (axis == "Horizontal")
        {
            return OVRInput.Get(
                OVRInput.Axis2D.PrimaryThumbstick, (OVRInput.Controller)hand).x;
        }       // if : 수평 방향으로 힘을 받을 때
        else
        {
            return OVRInput.Get(
                OVRInput.Axis2D.PrimaryThumbstick, (OVRInput.Controller)hand).y;
        }       // else : 수직 방향으로 힘을 받을 때
#else
        return default;
#endif      // BUILD_PLATFORM_PC
    }       // GetAxis
References OVRInput.Get().
GetDown()
static bool ARAVRInput.GetDown (Button virtualMask, Controller hand = Controller::RTouch) static
컨트롤러의 특정 버튼을 눌렀을 때 true를 반환하는 함수이다.
Parameters
virtualMask 미리 정의된 버튼의 종류를 받아온다.
hand 어느 컨트롤러의 버튼을 누를 것인지 받아온다.
Returns
virtualMask에 들어온 값을 ButtonTarget 타입으로 변환해서 리턴한다.
Definition at line 244 of file ARAVRInput.cs.
    {
#if BUILD_PLATFORM_PC
        return Input.GetButtonDown(((ButtonTarget)virtualMask).ToString());
#elif TARGET_DEVICE_OCULUS
        return OVRInput.GetDown((OVRInput.Button)virtualMask, (OVRInput.Controller)hand);
#else
        return false;
#endif
    }       // GetDown
References OVRInput.GetDown().
GetUp()
static bool ARAVRInput.GetUp (Button virtualMask, Controller hand = Controller::RTouch) static
컨트롤러의 특정 버튼을 눌렀다 떼었을 때 true를 반환하는 함수이다.
Parameters
virtualMask 미리 정의된 버튼의 종류를 받아온다.
hand 어느 컨트롤러의 버튼을 누를 것인지 받아온다.
Returns
virtualMask에 들어온 값을 ButtonTarget 타입으로 변환해서 리턴한다.
Definition at line 261 of file ARAVRInput.cs.
    {
#if BUILD_PLATFORM_PC
        return Input.GetButtonUp(((ButtonTarget)virtualMask).ToString());
#elif TARGET_DEVICE_OCULUS
        return OVRInput.GetUp((OVRInput.Button)virtualMask, (OVRInput.Controller)hand);
#else
        return false;
#endif
    }       // GetUp
References OVRInput.GetUp().
PlayVibration() [1/2]
static void ARAVRInput.PlayVibration (Controller hand) static
컨트롤러의 진동을 실행하는 함수이다.
See also
PlayVibration()
Definition at line 380 of file ARAVRInput.cs.
    {
#if TARGET_DEVICE_OCULUS
        PlayVibration(0.06f, 1f, 1f, hand);
#endif      // TARGET_DEVICE_OCULUS
    }       // PlayVibration()
References PlayVibration().
PlayVibration() [2/2]
static void ARAVRInput.PlayVibration (float duration, float frequency, float amplitude, Controller hand) static
컨트롤러에 진동을 실행하는 함수이다.
Parameters
duration 얼마나 오래 진동할 것인지 받아온다.
frequency 얼마나 빠르게 진동할 것인지 받아온다.
amplitude 얼마나 세게 진동할 것인지 받아온다.
hand 어느 컨트롤러를 진동할 것인지 받아온다.
See also
VibrationCoroutine
Definition at line 395 of file ARAVRInput.cs.
    {
#if TARGET_DEVICE_OCULUS
        if(CoroutineInstance.coroutineInstance == null)
        {
            GameObject coroutineObj = new GameObject("CoroutineInsntace");
            coroutineObj.AddComponent<CoroutineInstance>();
        }       // if : 싱글턴 코루틴 인스턴스의 널 체크를 왜 여기서 함?
        // 이미 플레이중인 진동 코루틴은 정지
        CoroutineInstance.coroutineInstance.StopAllCoroutines();
        CoroutineInstance.coroutineInstance.StartCoroutine
            (VibrationCoroutine(duration, frequency, amplitude, hand));
#endif      // TARGET_DEVICE_OCULUS
    }       // PlayVibration()
References CoroutineInstance.coroutineInstance.
Recenter() [1/2]
static void ARAVRInput.Recenter () static
VR 카메라가 바라보는 방향을 기준으로 센터를 잡는다.
See also
Recenter()
Definition at line 304 of file ARAVRInput.cs.
    {
#if TARGET_DEVICE_OCULUS
        OVRManager.display.RecenterPose();
#endif      // TARGET_DEVICE_OCULUS
    }       // Recenter()
References OVRManager.display, and OVRDisplay.RecenterPose().
Recenter() [2/2]
static void ARAVRInput.Recenter (Transform target, Vector3 direction) static
타겟이 바라보는 방향을 기준으로 센터를 잡는다.
Parameters
target 바라보는 방향을 결정할 Target의 Transform을 받아온다.
direction 바라볼 방향을 받아온다.
Definition at line 316 of file ARAVRInput.cs.
    {
        target.forward = target.rotation * direction;
    }
Member Data Documentation
lHand
Transform ARAVRInput.lHand static private
씬에 등록된 왼쪽 컨트롤러를 캐싱하는 변수이다.
Definition at line 193 of file ARAVRInput.cs.
rHand
Transform ARAVRInput.rHand static private
씬에 등록된 오른쪽 컨트롤러를 캐싱하는 변수이다.
Definition at line 163 of file ARAVRInput.cs.
Property Documentation
LHand
Transform ARAVRInput.LHand static get
씬에 등록된 오른쪽 컨트롤러 찾아 반환하는 프로퍼티이다.
Returns
오른쪽 컨트롤러의 Transform을 리턴한다.
Definition at line 199 of file ARAVRInput.cs.
    {
        get
        {
            if(lHand == null)
            {
#if BUILD_PLATFORM_PC
                // LHand라는 이름으로 게임오브젝트를 만든다.
                GameObject handObj = new GameObject("LHand");
                // 만들어진 객체의 트랜스폼을 lHand에 할당
                lHand = handObj.transform;
                // 컨트롤러를 카메라의 자식 객체로 등록
                lHand.parent = Camera.main.transform;
#elif TARGET_DEVICE_OCULUS
                lHand = GameObject.Find("LeftControllerAnchor").transform;
#endif      // BUILD_PLATFORM_PC
            }
            return lHand;
        }
    }       // LHand
LHandDirection
Vector3 ARAVRInput.LHandDirection static get
왼쪽 컨트롤러의 방향를 얻어오는 프로퍼티이다.
Returns
카메라를 기준으로 컨트롤러의 정면 방향을 연산해서 리턴한다.
Definition at line 145 of file ARAVRInput.cs.
    {
        get
        {
#if BUILD_PLATFORM_PC
            Vector3 direction = LHandPosition - Camera.main.transform.position;
            LHand.forward = direction;
#elif TARGET_DEVICE_OCULUS
            Vector3 direction = OVRInput.GetLocalControllerRotation(OVRInput.Controller.LTouch) * Vector3.forward;
            direction = GetTransform().TransformDirection(direction);
#else
            Vector3 direction = default;
#endif      // BUILD_PLATFORM_PC
            return direction;
        }
    }       // LHandDirection
LHandPosition
Vector3 ARAVRInput.LHandPosition static get
왼쪽 컨트롤러의 위치를 얻어오는 프로퍼티이다.
Returns
스크린 좌표를 얻어서 월드 좌표로 변환한 값을 리턴한다.
Definition at line 119 of file ARAVRInput.cs.
    {
        get
        {
#if UNITY_STANDALONE
            // 마우스의 스크린 좌표 얻어오기
            Vector3 pos = Input.mousePosition;
            // z값은 0.7m로 설정
            pos.z = 0.7f;
            // 스크린 좌표를 월드 좌표로 변환
            pos = Camera.main.ScreenToWorldPoint(pos);
            LHand.position = pos;
#elif TARGET_DEVICE_OCULUS
            Vector3 pos = OVRInput.GetLocalControllerPosition(OVRInput, Controller.LTouch);
            pos = GetTransform().TransformPoint(pos);
#else
            Vector3 pos = default;
#endif      // UNITY_STANDALONE
            return pos;
        }
    }       // LHandPosition
RHand
Transform ARAVRInput.RHand static get
씬에 등록된 오른쪽 컨트롤러 찾아 반환하는 프로퍼티이다.
Returns
오른쪽 컨트롤러의 Transform을 리턴한다.
Definition at line 169 of file ARAVRInput.cs.
    {
        get
        {
            if (rHand == null)
            {
#if BUILD_PLATFORM_PC
                // LHand라는 이름으로 게임오브젝트를 만든다.
                GameObject handObj = new GameObject("RHand");
                // 만들어진 객체의 트랜스폼을 lHand에 할당
                rHand = handObj.transform;
                // 컨트롤러를 카메라의 자식 객체로 등록
                rHand.parent = Camera.main.transform;
#elif TARGET_DEVICE_OCULUS
                lHand = GameObject.Find("LeftControllerAnchor").transform;
#endif      // BUILD_PLATFORM_PC
            }
            return rHand;
        }
    }       // RHand
RHandDirection
Vector3 ARAVRInput.RHandDirection static get
오른쪽 컨트롤러의 방향를 얻어오는 프로퍼티이다.
Returns
카메라를 기준으로 컨트롤러의 정면 방향을 연산해서 리턴한다.
Definition at line 95 of file ARAVRInput.cs.
    {
        get
        {
#if BUILD_PLATFORM_PC
            Vector3 direction = RHandPosition - Camera.main.transform.position;
            RHand.forward = direction;
#elif TARGET_DEVICE_OCULUS
            Vector3 direction = OVRInput.GetLocalControllerRotation(OVRInput.Controller.RTouch) * Vector3.forward;
            direction = GetTransform().TransformDirection(direction);
#else
            Vector3 direction = default;
#endif      // BUILD_PLATFORM_PC
            return direction;
        }
    }       // RHandDirection
RHandPosition
Vector3 ARAVRInput.RHandPosition static get
오른쪽 컨트롤러의 위치를 얻어오는 프로퍼티이다.
Returns
스크린 좌표를 얻어서 월드 좌표로 변환한 값을 리턴한다.
Definition at line 67 of file ARAVRInput.cs.
    {
        get
        {
#if UNITY_STANDALONE
            // 마우스의 스크린 좌표 얻어오기
            Vector3 pos = Input.mousePosition;
            // z값은 0.7m로 설정
            pos.z = 0.7f;
            // 스크린 좌표를 월드 좌표로 변환
            pos = Camera.main.ScreenToWorldPoint(pos);
            RHand.position = pos;
#elif TARGET_DEVICE_OCULUS
            Vector3 pos = OVRInput.GetLocalControllerPosition(OVRInput, Controller.RTouch);
            pos = GetTransform().TransformPoint(pos);
#else
            Vector3 pos = default;
#endif      // UNITY_STANDALONE
            return pos;
        }
    }       // RHandPosition
The documentation for this class was generated from the following file:
Assets/01.MyFolder/Scripts/ARAVRInput.cs