VR_Test: Oculus.Interaction.Input.Hand Class Reference
Oculus.Interaction.Input.Hand Class Reference
Public Member Functions
override void MarkInputDataRequiresUpdate ()
bool GetFingerIsPinching (HandFinger finger)
bool GetIndexFingerIsPinching ()
bool GetPointerPose (out Pose pose)
Attempts to calculate the pose that can be used as a root for raycasting, in world space Returns false if there is no valid tracking data.
bool GetJointPose (HandJointId handJointId, out Pose pose)
Attempts to calculate the pose of the requested hand joint, in world space. Returns false if the skeleton is not yet initialized, or there is no valid tracking data.
bool GetJointPoseLocal (HandJointId handJointId, out Pose pose)
Attempts to calculate the pose of the requested hand joint, in local space. Returns false if the skeleton is not yet initialized, or there is no valid tracking data.
bool GetJointPosesLocal (out ReadOnlyHandJointPoses localJointPoses)
Returns an array containing the local pose of each joint. The poses do not have the root pose applied, nor the hand scale. It is in the same coordinate system as the hand skeleton.
bool GetJointPoseFromWrist (HandJointId handJointId, out Pose pose)
Attempts to calculate the pose of the requested hand joint relative to the wrist. Returns false if the skeleton is not yet initialized, or there is no valid tracking data.
bool GetJointPosesFromWrist (out ReadOnlyHandJointPoses jointPosesFromWrist)
Returns an array containing the pose of each joint relative to the wrist. The poses do not have the root pose applied, nor the hand scale. It is in the same coordinate system as the hand skeleton.
bool GetPalmPoseLocal (out Pose pose)
Obtains palm pose in local space.
bool GetFingerIsHighConfidence (HandFinger finger)
float GetFingerPinchStrength (HandFinger finger)
bool GetRootPose (out Pose pose)
Gets the root pose of the wrist, in world space. Will return true if a pose was available; false otherwise. Confidence level of the pose is exposed via IsHighConfidence.
void InjectAllHand (UpdateModeFlags updateMode, IDataSource updateAfter, DataModifier< HandDataAsset > modifyDataFromSource, bool applyModifier)
Public Member Functions inherited from Oculus.Interaction.Input.DataModifier< HandDataAsset >
void ResetSources (IDataSource< TData > modifyDataFromSource, IDataSource updateAfter, UpdateModeFlags updateMode)
void InjectAllDataModifier (UpdateModeFlags updateMode, IDataSource updateAfter, IDataSource< TData > modifyDataFromSource, bool applyModifier)
void InjectModifyDataFromSource (IDataSource< TData > modifyDataFromSource)
void InjectApplyModifier (bool applyModifier)
Protected Member Functions
override void Apply (HandDataAsset data)
Protected Member Functions inherited from Oculus.Interaction.Input.DataModifier< HandDataAsset >
override void UpdateData ()
void Apply (TData data)
override void Start ()
Properties
Handedness Handedness [get]
ITrackingToWorldTransformer TrackingToWorldTransformer [get]
HandSkeleton HandSkeleton [get]
bool IsConnected [get]
bool IsHighConfidence [get]
The hand is connected and tracked, and the root pose's tracking data is marked as high confidence. If this is true, then it implies that IsConnected and IsRootPoseValid are also true, so they don't need to be checked in addition to this.
bool IsDominantHand [get]
float Scale [get]
bool IsPointerPoseValid [get]
Will return true if a pointer pose is available, that can be retrieved via GetPointerPose
bool IsTrackedDataValid [get]
True if the hand is currently tracked, thus tracking poses are available for the hand root and finger joints. This property does not indicate pointing pose validity, which has its own property: IsPointerPoseValid.
Properties inherited from Oculus.Interaction.Input.DataModifier< HandDataAsset >
static TData InvalidAsset [get]
override TData DataAsset [get]
virtual IDataSource< TData > ModifyDataFromSource [get]
override int CurrentDataVersion [get]
Properties inherited from Oculus.Interaction.Input.IHand
int CurrentDataVersion [get]
Incremented every time the source tracking or state data changes.
Events
Action WhenHandUpdated = delegate { }
Events inherited from Oculus.Interaction.Input.IHand
Action WhenHandUpdated
Private Member Functions
void InitializeJointPosesCache ()
void CheckJointPosesCacheUpdate ()
bool ValidatePose (in Pose sourcePose, PoseOrigin sourcePoseOrigin, out Pose pose)
bool IsPoseOriginAllowed (PoseOrigin poseOrigin)
bool IsPoseOriginDisallowed (PoseOrigin poseOrigin)
Private Attributes
HandJointCache _jointPosesCache
Static Private Attributes
static readonly Vector3 PALM_LOCAL_OFFSET = new Vector3(0.08f, -0.01f, 0.0f)
Additional Inherited Members
Protected Attributes inherited from Oculus.Interaction.Input.DataModifier< HandDataAsset >
UnityEngine.Object _iModifyDataFromSourceMono
Detailed Description
Definition at line 30 of file Hand.cs.
Member Function Documentation
Apply()
override void Oculus.Interaction.Input.Hand.Apply (HandDataAsset data) protected
Definition at line 53 of file Hand.cs.
        {
            // Default implementation does nothing, to allow instantiation of this modifier directly
        }
CheckJointPosesCacheUpdate()
void Oculus.Interaction.Input.Hand.CheckJointPosesCacheUpdate () private
Definition at line 77 of file Hand.cs.
        {
            if (_jointPosesCache != null
                && CurrentDataVersion != _jointPosesCache.LocalDataVersion)
            {
                _jointPosesCache.Update(GetData(), CurrentDataVersion);
            }
        }
GetFingerIsHighConfidence()
bool Oculus.Interaction.Input.Hand.GetFingerIsHighConfidence (HandFinger finger)
Implements Oculus.Interaction.Input.IHand.
Definition at line 181 of file Hand.cs.
        {
            return GetData().IsFingerHighConfidence[(int)finger];
        }
GetFingerIsPinching()
bool Oculus.Interaction.Input.Hand.GetFingerIsPinching (HandFinger finger)
Implements Oculus.Interaction.Input.IHand.
Definition at line 88 of file Hand.cs.
        {
            HandDataAsset currentData = GetData();
            return currentData.IsConnected && currentData.IsFingerPinching[(int)finger];
        }
GetFingerPinchStrength()
float Oculus.Interaction.Input.Hand.GetFingerPinchStrength (HandFinger finger)
Implements Oculus.Interaction.Input.IHand.
Definition at line 186 of file Hand.cs.
        {
            return GetData().FingerPinchStrength[(int)finger];
        }
GetIndexFingerIsPinching()
bool Oculus.Interaction.Input.Hand.GetIndexFingerIsPinching ()
Implements Oculus.Interaction.Input.IHand.
Definition at line 94 of file Hand.cs.
        {
            return GetFingerIsPinching(HandFinger.Index);
        }
GetJointPose()
bool Oculus.Interaction.Input.Hand.GetJointPose (HandJointId handJointId, out Pose pose)
Attempts to calculate the pose of the requested hand joint, in world space. Returns false if the skeleton is not yet initialized, or there is no valid tracking data.
Implements Oculus.Interaction.Input.IHand.
Definition at line 108 of file Hand.cs.
        {
            pose = Pose.identity;
            if (!IsTrackedDataValid
                || _jointPosesCache == null
                || !GetRootPose(out Pose rootPose))
            {
                return false;
            }
            CheckJointPosesCacheUpdate();
            pose = _jointPosesCache.WorldJointPose(handJointId, rootPose, Scale);
            return true;
        }
References Oculus.Interaction.Input.Hand.GetRootPose(), and Oculus.Interaction.Input.Hand.IsTrackedDataValid.
GetJointPoseFromWrist()
bool Oculus.Interaction.Input.Hand.GetJointPoseFromWrist (HandJointId handJointId, out Pose pose)
Attempts to calculate the pose of the requested hand joint relative to the wrist. Returns false if the skeleton is not yet initialized, or there is no valid tracking data.
Implements Oculus.Interaction.Input.IHand.
Definition at line 146 of file Hand.cs.
        {
            pose = Pose.identity;
            if (!GetJointPosesFromWrist(out ReadOnlyHandJointPoses jointPosesFromWrist))
            {
                return false;
            }
            pose = jointPosesFromWrist[(int)handJointId];
            return true;
        }
References Oculus.Interaction.Input.Hand.GetJointPosesFromWrist().
GetJointPoseLocal()
bool Oculus.Interaction.Input.Hand.GetJointPoseLocal (HandJointId handJointId, out Pose pose)
Attempts to calculate the pose of the requested hand joint, in local space. Returns false if the skeleton is not yet initialized, or there is no valid tracking data.
Implements Oculus.Interaction.Input.IHand.
Definition at line 123 of file Hand.cs.
        {
            pose = Pose.identity;
            if (!GetJointPosesLocal(out ReadOnlyHandJointPoses localJointPoses))
            {
                return false;
            }
            pose = localJointPoses[(int)handJointId];
            return true;
        }
References Oculus.Interaction.Input.Hand.GetJointPosesLocal().
GetJointPosesFromWrist()
bool Oculus.Interaction.Input.Hand.GetJointPosesFromWrist (out ReadOnlyHandJointPoses jointPosesFromWrist)
Returns an array containing the pose of each joint relative to the wrist. The poses do not have the root pose applied, nor the hand scale. It is in the same coordinate system as the hand skeleton.
Parameters
jointPosesFromWrist The array with the joint poses from the wrist. It will be empty if no poses where found
Returns
True if the poses collection was correctly populated. False otherwise.
Implements Oculus.Interaction.Input.IHand.
Definition at line 158 of file Hand.cs.
        {
            if (!IsTrackedDataValid || _jointPosesCache == null)
            {
                jointPosesFromWrist = ReadOnlyHandJointPoses.Empty;
                return false;
            }
            CheckJointPosesCacheUpdate();
            return _jointPosesCache.GetAllPosesFromWrist(out jointPosesFromWrist);
        }
References Oculus.Interaction.Input.Hand.IsTrackedDataValid.
GetJointPosesLocal()
bool Oculus.Interaction.Input.Hand.GetJointPosesLocal (out ReadOnlyHandJointPoses localJointPoses)
Returns an array containing the local pose of each joint. The poses do not have the root pose applied, nor the hand scale. It is in the same coordinate system as the hand skeleton.
Parameters
localJointPoses The array with the local joint poses. It will be empty if no poses where found
Returns
True if the poses collection was correctly populated. False otherwise.
Implements Oculus.Interaction.Input.IHand.
Definition at line 135 of file Hand.cs.
        {
            if (!IsTrackedDataValid || _jointPosesCache == null)
            {
                localJointPoses = ReadOnlyHandJointPoses.Empty;
                return false;
            }
            CheckJointPosesCacheUpdate();
            return _jointPosesCache.GetAllLocalPoses(out localJointPoses);
        }
References Oculus.Interaction.Input.Hand.IsTrackedDataValid.
GetPalmPoseLocal()
bool Oculus.Interaction.Input.Hand.GetPalmPoseLocal (out Pose pose)
Obtains palm pose in local space.
Parameters
pose The pose to populate
Returns
True if pose was obtained.
Implements Oculus.Interaction.Input.IHand.
Definition at line 169 of file Hand.cs.
        {
            Quaternion rotationQuat = Quaternion.identity;
            Vector3 offset = PALM_LOCAL_OFFSET;
            if (Handedness == Handedness.Left)
            {
                offset = -offset;
            }
            pose = new Pose(offset * Scale, rotationQuat);
            return true;
        }
GetPointerPose()
bool Oculus.Interaction.Input.Hand.GetPointerPose (out Pose pose)
Attempts to calculate the pose that can be used as a root for raycasting, in world space Returns false if there is no valid tracking data.
Implements Oculus.Interaction.Input.IHand.
Definition at line 101 of file Hand.cs.
        {
            HandDataAsset currentData = GetData();
            return ValidatePose(currentData.PointerPose, currentData.PointerPoseOrigin,
                out pose);
        }
GetRootPose()
bool Oculus.Interaction.Input.Hand.GetRootPose (out Pose pose)
Gets the root pose of the wrist, in world space. Will return true if a pose was available; false otherwise. Confidence level of the pose is exposed via IsHighConfidence.
Implements Oculus.Interaction.Input.IHand.
Definition at line 193 of file Hand.cs.
        {
            HandDataAsset currentData = GetData();
            return ValidatePose(currentData.Root, currentData.RootPoseOrigin, out pose);
        }
InitializeJointPosesCache()
void Oculus.Interaction.Input.Hand.InitializeJointPosesCache () private
Definition at line 69 of file Hand.cs.
        {
            if (_jointPosesCache == null && GetData().IsDataValidAndConnected)
            {
                _jointPosesCache = new HandJointCache(HandSkeleton);
            }
        }
InjectAllHand()
void Oculus.Interaction.Input.Hand.InjectAllHand (UpdateModeFlags updateMode, IDataSource updateAfter, DataModifier< HandDataAsset > modifyDataFromSource, bool applyModifier)
Definition at line 229 of file Hand.cs.
        {
            base.InjectAllDataModifier(updateMode, updateAfter, modifyDataFromSource, applyModifier);
        }
IsPoseOriginAllowed()
bool Oculus.Interaction.Input.Hand.IsPoseOriginAllowed (PoseOrigin poseOrigin) private
Definition at line 217 of file Hand.cs.
        {
            return poseOrigin != PoseOrigin.None;
        }
IsPoseOriginDisallowed()
bool Oculus.Interaction.Input.Hand.IsPoseOriginDisallowed (PoseOrigin poseOrigin) private
Definition at line 222 of file Hand.cs.
        {
            return poseOrigin == PoseOrigin.None;
        }
MarkInputDataRequiresUpdate()
override void Oculus.Interaction.Input.Hand.MarkInputDataRequiresUpdate ()
Definition at line 58 of file Hand.cs.
        {
            base.MarkInputDataRequiresUpdate();
            if (Started)
            {
                InitializeJointPosesCache();
                WhenHandUpdated.Invoke();
            }
        }
ValidatePose()
bool Oculus.Interaction.Input.Hand.ValidatePose (in Pose sourcePose, PoseOrigin sourcePoseOrigin, out Pose pose) private
Definition at line 202 of file Hand.cs.
        {
            if (IsPoseOriginDisallowed(sourcePoseOrigin))
            {
                pose = Pose.identity;
                return false;
            }
            pose = TrackingToWorldTransformer != null
                ? TrackingToWorldTransformer.ToWorldPose(sourcePose)
                : sourcePose;
            return true;
        }
Member Data Documentation
_jointPosesCache
HandJointCache Oculus.Interaction.Input.Hand._jointPosesCache private
Definition at line 39 of file Hand.cs.
PALM_LOCAL_OFFSET
readonly Vector3 Oculus.Interaction.Input.Hand.PALM_LOCAL_OFFSET = new Vector3(0.08f, -0.01f, 0.0f) static private
Definition at line 51 of file Hand.cs.
Property Documentation
Handedness
Handedness Oculus.Interaction.Input.Hand.Handedness get
Implements Oculus.Interaction.Input.IHand.
Definition at line 32 of file Hand.cs.
HandSkeleton
HandSkeleton Oculus.Interaction.Input.Hand.HandSkeleton get
Definition at line 37 of file Hand.cs.
IsConnected
bool Oculus.Interaction.Input.Hand.IsConnected get
Implements Oculus.Interaction.Input.IHand.
Definition at line 43 of file Hand.cs.
IsDominantHand
bool Oculus.Interaction.Input.Hand.IsDominantHand get
Implements Oculus.Interaction.Input.IHand.
Definition at line 45 of file Hand.cs.
IsHighConfidence
bool Oculus.Interaction.Input.Hand.IsHighConfidence get
The hand is connected and tracked, and the root pose's tracking data is marked as high confidence. If this is true, then it implies that IsConnected and IsRootPoseValid are also true, so they don't need to be checked in addition to this.
Implements Oculus.Interaction.Input.IHand.
Definition at line 44 of file Hand.cs.
IsPointerPoseValid
bool Oculus.Interaction.Input.Hand.IsPointerPoseValid get
Will return true if a pointer pose is available, that can be retrieved via GetPointerPose
Implements Oculus.Interaction.Input.IHand.
Definition at line 99 of file Hand.cs.
IsTrackedDataValid
bool Oculus.Interaction.Input.Hand.IsTrackedDataValid get
True if the hand is currently tracked, thus tracking poses are available for the hand root and finger joints. This property does not indicate pointing pose validity, which has its own property: IsPointerPoseValid.
Implements Oculus.Interaction.Input.IHand.
Definition at line 191 of file Hand.cs.
Scale
float Oculus.Interaction.Input.Hand.Scale get
Implements Oculus.Interaction.Input.IHand.
Definition at line 47 of file Hand.cs.
TrackingToWorldTransformer
ITrackingToWorldTransformer Oculus.Interaction.Input.Hand.TrackingToWorldTransformer get
Definition at line 34 of file Hand.cs.
Event Documentation
WhenHandUpdated
Action Oculus.Interaction.Input.Hand.WhenHandUpdated = delegate { }
Definition at line 41 of file Hand.cs.
{ };
The documentation for this class was generated from the following file:
Assets/Oculus/Interaction/Runtime/Scripts/Input/Hands/Hand.cs