VR_Test: OVRLipSyncDebugConsole Class Reference
OVRLipSyncDebugConsole Class Reference
Public Member Functions
void Init ()
Init this instance.
void AddMessage (string message, Color color)
Adds the message.
void ClearMessages ()
Clears the messages.
void SetClearTimeout (float timeout)
Sets the clear timeout.
Static Public Member Functions
static void Log (string message)
Log the specified message.
static void Log (string message, Color color)
Log the specified message and color.
static void Clear ()
Clear this instance.
static void ClearTimeout (float timeToClear)
Calls clear after a certain time.
Public Attributes
ArrayList messages = new ArrayList()
int maxMessages = 15
Text textMsg
Properties
static OVRLipSyncDebugConsole instance [get]
Gets the instance.
Private Member Functions
void Awake ()
Awake this instance.
void Update ()
Update this instance.
void Prune ()
void Display ()
Display this instance.
Private Attributes
bool clearTimeoutOn = false
float clearTimeout = 0.0f
Static Private Attributes
static OVRLipSyncDebugConsole s_Instance = null
Detailed Description
Definition at line 27 of file OVRLipSyncDebugConsole.cs.
Member Function Documentation
AddMessage()
void OVRLipSyncDebugConsole.AddMessage (string message, Color color)
Adds the message.
Parameters
message Message.
color Color.
Definition at line 152 of file OVRLipSyncDebugConsole.cs.
    {
        messages.Add(message);
        if(textMsg != null)
            textMsg.color = color;
        Display();
    }
References Display().
Awake()
void OVRLipSyncDebugConsole.Awake () private
Awake this instance.
Definition at line 68 of file OVRLipSyncDebugConsole.cs.
    {
        s_Instance = this;
        Init();
    }
References Init().
Clear()
static void OVRLipSyncDebugConsole.Clear () static
Clear this instance.
Definition at line 130 of file OVRLipSyncDebugConsole.cs.
    {
        OVRLipSyncDebugConsole.instance.ClearMessages();
    }
References ClearMessages(), and instance.
ClearMessages()
void OVRLipSyncDebugConsole.ClearMessages ()
Clears the messages.
Definition at line 165 of file OVRLipSyncDebugConsole.cs.
    {
        messages.Clear();
        Display();
    }
References Display().
ClearTimeout()
static void OVRLipSyncDebugConsole.ClearTimeout (float timeToClear) static
Calls clear after a certain time.
Parameters
timeToClear Time to clear.
Definition at line 139 of file OVRLipSyncDebugConsole.cs.
    {
        OVRLipSyncDebugConsole.instance.SetClearTimeout(timeToClear);
    }
References instance, and SetClearTimeout().
Display()
void OVRLipSyncDebugConsole.Display () private
Display this instance.
Definition at line 204 of file OVRLipSyncDebugConsole.cs.
    {
        if (messages.Count > maxMessages)
        {
            Prune();
        }
        if(textMsg != null)
        {
            textMsg.text = ""; // Clear text out
            int x = 0;
            while (x < messages.Count)
            {
                     textMsg.text += (string)messages[x];
                    textMsg.text +='\n';
                    x += 1;
            }
        }
    }
Init()
void OVRLipSyncDebugConsole.Init ()
Init this instance.
Definition at line 95 of file OVRLipSyncDebugConsole.cs.
    {
        if(textMsg == null)
        {
            Debug.LogWarning("DebugConsole Init WARNING::UI text not set. Will not be able to display anything.");
        }
        Clear();
    }
References Clear().
Log() [1/2]
static void OVRLipSyncDebugConsole.Log (string message) static
Log the specified message.
Parameters
message Message.
Definition at line 112 of file OVRLipSyncDebugConsole.cs.
    {
        OVRLipSyncDebugConsole.instance.AddMessage(message, Color.white);
    }
References AddMessage(), and instance.
Log() [2/2]
static void OVRLipSyncDebugConsole.Log (string message, Color color) static
Log the specified message and color.
Parameters
message Message.
color Color.
Definition at line 122 of file OVRLipSyncDebugConsole.cs.
    {
        OVRLipSyncDebugConsole.instance.AddMessage(message, color);
    }
References AddMessage(), and instance.
Prune()
void OVRLipSyncDebugConsole.Prune () private
Definition at line 184 of file OVRLipSyncDebugConsole.cs.
    {
        int diff;
        if (messages.Count > maxMessages)
        {
            if (messages.Count <= 0)
            {
                diff = 0;
            }
            else
            {
                diff = messages.Count - maxMessages;
            }
            messages.RemoveRange(0, (int)diff);
        }
    }
SetClearTimeout()
void OVRLipSyncDebugConsole.SetClearTimeout (float timeout)
Sets the clear timeout.
Parameters
timeout Timeout.
Definition at line 175 of file OVRLipSyncDebugConsole.cs.
    {
        clearTimeout   = timeout;
        clearTimeoutOn = true;
    }
Update()
void OVRLipSyncDebugConsole.Update () private
Update this instance.
Definition at line 78 of file OVRLipSyncDebugConsole.cs.
    {
        if(clearTimeoutOn == true)
        {
            clearTimeout -= Time.deltaTime;
            if(clearTimeout < 0.0f)
            {
                Clear();
                clearTimeout = 0.0f;
                clearTimeoutOn = false;
            }
        }
    }
References Clear().
Member Data Documentation
clearTimeout
float OVRLipSyncDebugConsole.clearTimeout = 0.0f private
Definition at line 38 of file OVRLipSyncDebugConsole.cs.
clearTimeoutOn
bool OVRLipSyncDebugConsole.clearTimeoutOn = false private
Definition at line 37 of file OVRLipSyncDebugConsole.cs.
maxMessages
int OVRLipSyncDebugConsole.maxMessages = 15
Definition at line 30 of file OVRLipSyncDebugConsole.cs.
messages
ArrayList OVRLipSyncDebugConsole.messages = new ArrayList()
Definition at line 29 of file OVRLipSyncDebugConsole.cs.
s_Instance
OVRLipSyncDebugConsole OVRLipSyncDebugConsole.s_Instance = null static private
Definition at line 34 of file OVRLipSyncDebugConsole.cs.
textMsg
Text OVRLipSyncDebugConsole.textMsg
Definition at line 31 of file OVRLipSyncDebugConsole.cs.
Property Documentation
instance
OVRLipSyncDebugConsole OVRLipSyncDebugConsole.instance static get
Gets the instance.
The instance.
Definition at line 44 of file OVRLipSyncDebugConsole.cs.
    {
        get
        {
            if (s_Instance == null)
            {
                s_Instance = FindObjectOfType(typeof(OVRLipSyncDebugConsole)) as OVRLipSyncDebugConsole;
                if (s_Instance == null)
                {
                    GameObject console = new GameObject();
                    console.AddComponent<OVRLipSyncDebugConsole>();
                    console.name = "OVRLipSyncDebugConsole";
                    s_Instance = FindObjectOfType(typeof(OVRLipSyncDebugConsole)) as OVRLipSyncDebugConsole;
                }
            }
            return s_Instance;
        }
    }
The documentation for this class was generated from the following file:
Assets/Oculus/LipSync/Scripts/Helpers/OVRLipSyncDebugConsole.cs