VR_Test: TeleportTransitionWarp Class Reference
TeleportTransitionWarp Class Reference
This transition will move the player to the destination over the span of a fixed amount of time. It will not adjust the orientation of the player because this is very uncomfortable. Note there is custom editor for this behavior which is used to control the warp interpolation.
Public Attributes
float TransitionDuration = 0.5f
How much time the warp transition takes to complete.
AnimationCurve PositionLerp = AnimationCurve.Linear(0, 0, 1, 1)
Curve to control the position lerp between the current location and the destination. There is a custom editor for this field to avoid a problem where inspector curves don't update as expected. The custom inspector code is here: .\Editor\OVRTeleportTransitionWarpInspector.cs.
Protected Member Functions
override void LocomotionTeleportOnEnterStateTeleporting ()
When the teleport state is entered, quickly move the player to the new location over the duration of the teleport.
Protected Member Functions inherited from TeleportTransition
override void AddEventHandlers ()
Derived classes that need to use event handlers need to override this method and call the base class to ensure all event handlers are added as intended.
override void RemoveEventHandlers ()
Derived classes that need to use event handlers need to override this method and call the base class to ensure all event handlers are removed as intended.
void LocomotionTeleportOnEnterStateTeleporting ()
When the teleport state is entered, simply move the player to the new location without any delay or other side effects. If the transition is not immediate, the transition handler will need to set the LocomotionTeleport.IsTeleporting to true for the duration of the transition, setting it to false when the transition is finished which will then allow the teleport state machine to switch to the PostTeleport state.
Protected Member Functions inherited from TeleportSupport
virtual void OnEnable ()
OnEnable is virtual so that derived classes can set up references to objects before AddEventHandlers is called, as is required by TeleportSupport derivations.
virtual void OnDisable ()
Private Member Functions
IEnumerator DoWarp ()
This coroutine will be active during the teleport transition and will move the camera according to the PositionLerp curve.
Additional Inherited Members
Properties inherited from TeleportSupport
LocomotionTeleport LocomotionTeleport [get, private set]
Detailed Description
This transition will move the player to the destination over the span of a fixed amount of time. It will not adjust the orientation of the player because this is very uncomfortable. Note there is custom editor for this behavior which is used to control the warp interpolation.
Definition at line 18 of file TeleportTransitionWarp.cs.
Member Function Documentation
DoWarp()
IEnumerator TeleportTransitionWarp.DoWarp () private
This coroutine will be active during the teleport transition and will move the camera according to the PositionLerp curve.
Returns
Definition at line 49 of file TeleportTransitionWarp.cs.
    {
        LocomotionTeleport.IsTransitioning = true;
        var startPosition = LocomotionTeleport.GetCharacterPosition();
        float elapsedTime = 0;
        while (elapsedTime < TransitionDuration)
        {
            elapsedTime += Time.deltaTime;
            var t = elapsedTime / TransitionDuration;
            var pLerp = PositionLerp.Evaluate(t);
            LocomotionTeleport.DoWarp(startPosition, pLerp);
            yield return null;
        }
        LocomotionTeleport.DoWarp(startPosition, 1.0f);
        LocomotionTeleport.IsTransitioning = false;
    }
References LocomotionTeleport.DoWarp(), LocomotionTeleport.GetCharacterPosition(), PositionLerp, and TransitionDuration.
LocomotionTeleportOnEnterStateTeleporting()
override void TeleportTransitionWarp.LocomotionTeleportOnEnterStateTeleporting () protected
When the teleport state is entered, quickly move the player to the new location over the duration of the teleport.
Definition at line 39 of file TeleportTransitionWarp.cs.
    {
        StartCoroutine(DoWarp());
    }
References DoWarp().
Member Data Documentation
PositionLerp
AnimationCurve TeleportTransitionWarp.PositionLerp = AnimationCurve.Linear(0, 0, 1, 1)
Curve to control the position lerp between the current location and the destination. There is a custom editor for this field to avoid a problem where inspector curves don't update as expected. The custom inspector code is here: .\Editor\OVRTeleportTransitionWarpInspector.cs.
Definition at line 33 of file TeleportTransitionWarp.cs.
TransitionDuration
float TeleportTransitionWarp.TransitionDuration = 0.5f
How much time the warp transition takes to complete.
Definition at line 25 of file TeleportTransitionWarp.cs.
The documentation for this class was generated from the following file:
Assets/Oculus/SampleFramework/Core/Locomotion/Scripts/TeleportTransitionWarp.cs