VR_Test: Meta.WitAi.Windows.WitConfigurationEditor Class Reference
Meta.WitAi.Windows.WitConfigurationEditor Class Reference
Public Member Functions
void Initialize ()
void OnDisable ()
override void OnInspectorGUI ()
void ApplyServerToken (string newToken)
Public Attributes
bool drawHeader = true
Protected Member Functions
virtual void LayoutContent ()
virtual bool CanConfigurationRefresh (WitConfiguration configuration)
virtual void LayoutConfigurationData ()
virtual void LayoutConfigurationEndpoint ()
virtual void LayoutConfigurationRequestTabs ()
virtual void SafeRefresh ()
Properties
WitConfiguration Configuration [get, private set]
virtual bool _disableServerPost [get]
Whether or not server specific functionality like sync should be disabled for this configuration.
static ConduitStatistics Statistics [get]
virtual Texture2D HeaderIcon [get]
virtual string HeaderUrl [get]
virtual string DocsUrl [get]
virtual string OpenButtonLabel [get]
Private Member Functions
void GenerateManifestIfNeeded ()
void LayoutConduitContent ()
void ReloadAppData ()
void CheckAutoTrainAvailabilityIfNeeded ()
void PresentAssemblySelectionDialog ()
void SyncEntities (Action successCallback=null)
Static Private Member Functions
static void OnScriptsReloaded ()
static void GenerateManifest (WitConfiguration configuration, bool openManifest)
Generates a manifest and optionally opens it in the editor.
static void AutoTrainOnWitAi (WitConfiguration configuration)
static void CheckAutoTrainIsAvailable (WitConfiguration configuration, Action< bool > onComplete)
static string GetManifestPullPath (WitConfiguration configuration, bool shouldCreateDirectoryIfNotExist=false)
static Manifest LoadManifest (string manifestPath)
Private Attributes
string _serverToken
string _appName
string _appID
bool _initialized = false
bool _foldout = true
int _requestTab = 0
bool _manifestAvailable = false
bool _syncInProgress = false
bool _didCheckAutoTrainAvailability = false
bool _isAutoTrainAvailable = false
EnumSynchronizer _enumSynchronizer
WitConfigurationEditorTab[] _tabs
Static Private Attributes
static ConduitStatistics _statistics
static readonly AssemblyMiner AssemblyMiner = new AssemblyMiner(new WitParameterValidator())
static readonly ManifestGenerator ManifestGenerator = new ManifestGenerator(AssemblyWalker, AssemblyMiner)
static readonly ManifestLoader ManifestLoader = new ManifestLoader()
static readonly IWitVRequestFactory VRequestFactory = new WitVRequestFactory()
static Type[] _tabTypes
const string ENTITY_SYNC_CONSENT_KEY = "Conduit.EntitySync.Consent"
Detailed Description
Definition at line 29 of file WitConfigurationEditor.cs.
Member Function Documentation
ApplyServerToken()
void Meta.WitAi.Windows.WitConfigurationEditor.ApplyServerToken (string newToken)
Definition at line 351 of file WitConfigurationEditor.cs.
        {
            if (newToken != _serverToken)
            {
                _serverToken = newToken;
                Configuration.ResetData();
            }
            WitAuthUtility.ServerToken = _serverToken;
            Configuration.SetServerToken(_serverToken);
            GenerateManifestIfNeeded();
        }
AutoTrainOnWitAi()
static void Meta.WitAi.Windows.WitConfigurationEditor.AutoTrainOnWitAi (WitConfiguration configuration) static private
Definition at line 672 of file WitConfigurationEditor.cs.
        {
            var instanceKey = Telemetry.StartEvent(Telemetry.TelemetryEventId.AutoTrain);
            var manifest = LoadManifest(configuration.ManifestLocalPath);
            var intents = ManifestGenerator.ExtractManifestData();
            VLog.D($"Auto training on WIT.ai: {intents.Count} intents.");
            configuration.ImportData(manifest, (isSuccess, error) =>
            {
                if (isSuccess)
                {
                    Telemetry.EndEvent(instanceKey, Telemetry.ResultType.Success);
                    EditorUtility.DisplayDialog("Auto Train", "Successfully started auto train process on WIT.ai.",
                        "OK");
                }
                else
                {
                    var failureMessage =
                        $"Failed to import generated manifest JSON into WIT.ai: {error}. Manifest:\n{manifest}";
                    Telemetry.EndEventWithFailure(instanceKey, failureMessage);
                    VLog.E(failureMessage);
                    EditorUtility.DisplayDialog("Auto Train", "Failed to start auto train process on WIT.ai.", "OK");
                }
            });
        }
CanConfigurationRefresh()
virtual bool Meta.WitAi.Windows.WitConfigurationEditor.CanConfigurationRefresh (WitConfiguration configuration) protected virtual
Definition at line 365 of file WitConfigurationEditor.cs.
        {
            return configuration;
        }
CheckAutoTrainAvailabilityIfNeeded()
void Meta.WitAi.Windows.WitConfigurationEditor.CheckAutoTrainAvailabilityIfNeeded () private
Definition at line 499 of file WitConfigurationEditor.cs.
        {
            if (_didCheckAutoTrainAvailability || !WitConfigurationUtility.IsServerTokenValid(_serverToken)) {
                return;
            }
            _didCheckAutoTrainAvailability = true;
            CheckAutoTrainIsAvailable(Configuration, (isAvailable) => {
                _isAutoTrainAvailable = isAvailable;
                Telemetry.LogInstantEvent(Telemetry.TelemetryEventId.CheckAutoTrain, new Dictionary<Telemetry.AnnotationKey, string>
                {
                    { Telemetry.AnnotationKey.IsAvailable, isAvailable.ToString() }
                });
            });
        }
CheckAutoTrainIsAvailable()
static void Meta.WitAi.Windows.WitConfigurationEditor.CheckAutoTrainIsAvailable (WitConfiguration configuration, Action< bool > onComplete) static private
Definition at line 699 of file WitConfigurationEditor.cs.
        {
            var appInfo = configuration.GetApplicationInfo();
            var manifestText = ManifestGenerator.GenerateEmptyManifest(appInfo.name, appInfo.id);
            var manifest = ManifestLoader.LoadManifestFromString(manifestText);
            configuration.ImportData(manifest, (result, error) => onComplete(result), true);
        }
GenerateManifest()
static void Meta.WitAi.Windows.WitConfigurationEditor.GenerateManifest (WitConfiguration configuration, bool openManifest) static private
Generates a manifest and optionally opens it in the editor.
Parameters
configuration The configuration that we are generating the manifest for.
openManifest If true, will open the manifest file in the code editor.
Definition at line 531 of file WitConfigurationEditor.cs.
        {
            var instanceKey = Telemetry.StartEvent(Telemetry.TelemetryEventId.GenerateManifest);
            AssemblyWalker.AssembliesToIgnore = new HashSet<string>(configuration.excludedAssemblies);
            // Generate
            var startGenerationTime = DateTime.UtcNow;
            var appInfo = configuration.GetApplicationInfo();
            var manifest = ManifestGenerator.GenerateManifest(appInfo.name, appInfo.id);
            var endGenerationTime = DateTime.UtcNow;
            // Get file path
            var fullPath = configuration.GetManifestEditorPath();
            if (string.IsNullOrEmpty(fullPath) || !File.Exists(fullPath))
            {
                fullPath = GetManifestPullPath(configuration, true);
            }
            // Write to file
            try
            {
                var writer = new StreamWriter(fullPath);
                writer.NewLine = "\n";
                writer.WriteLine(manifest);
                writer.Close();
            }
            catch (Exception e)
            {
                VLog.E($"Conduit manifest failed to generate\nPath: {fullPath}\n{e}");
                Telemetry.EndEventWithFailure(instanceKey, e.Message);
                return;
            }
            try
            {
                var incompatibleSignatures = string.Join(" ", AssemblyMiner.IncompatibleSignatureFrequency.Keys);
                Telemetry.AnnotateEvent(instanceKey, Telemetry.AnnotationKey.IncompatibleSignatures, incompatibleSignatures);
                var compatibleSignatures = string.Join(" ", AssemblyMiner.SignatureFrequency.Keys);
                Telemetry.AnnotateEvent(instanceKey, Telemetry.AnnotationKey.CompatibleSignatures, compatibleSignatures);
            }
            catch (Exception e)
            {
                VLog.W($"Failed to collect signature telemetry. Exception: {e}");
            }
            Telemetry.EndEvent(instanceKey, Telemetry.ResultType.Success);
            Statistics.SuccessfulGenerations++;
            Statistics.AddFrequencies(AssemblyMiner.SignatureFrequency);
            Statistics.AddIncompatibleFrequencies(AssemblyMiner.IncompatibleSignatureFrequency);
            var generationTime = endGenerationTime - startGenerationTime;
            var unityPath = fullPath.Replace(Application.dataPath, "Assets");
            AssetDatabase.ImportAsset(unityPath);
            var configName = configuration.name;
            var manifestName = Path.GetFileNameWithoutExtension(unityPath);
            #if UNITY_2021_2_OR_NEWER
            var configPath = AssetDatabase.GetAssetPath(configuration);
            configName = $"<a href=\"{configPath}\">{configName}</a>";
            manifestName = $"<a href=\"{unityPath}\">{manifestName}</a>";
            #endif
            VLog.D($"Conduit manifest generated\nConfiguration: {configName}\nManifest: {manifestName}\nGeneration Time: {generationTime.TotalMilliseconds} ms");
            if (openManifest)
            {
                UnityEditorInternal.InternalEditorUtility.OpenFileAtLineExternal(fullPath, 1);
            }
        }
References Meta.WitAi.VLog.D(), Meta.WitAi.VLog.E(), Meta.WitAi.Data.Configuration.WitConfiguration.excludedAssemblies, Meta.WitAi.Data.Configuration.WitConfiguration.GetApplicationInfo(), and Meta.WitAi.VLog.W().
GenerateManifestIfNeeded()
void Meta.WitAi.Windows.WitConfigurationEditor.GenerateManifestIfNeeded () private
Definition at line 140 of file WitConfigurationEditor.cs.
        {
            if (!Configuration.useConduit || Configuration == null)
            {
                return;
            }
            // Get full manifest path & ensure it exists
            string manifestPath = Configuration.GetManifestEditorPath();
            _manifestAvailable = File.Exists(manifestPath);
            // Auto-generate manifest
            if (!_manifestAvailable)
            {
                GenerateManifest(Configuration, false);
            }
        }
GetManifestPullPath()
static string Meta.WitAi.Windows.WitConfigurationEditor.GetManifestPullPath (WitConfiguration configuration, bool shouldCreateDirectoryIfNotExist = false) static private
Definition at line 707 of file WitConfigurationEditor.cs.
        {
            string directory = Application.dataPath + "/Oculus/Voice/Resources";
            if (shouldCreateDirectoryIfNotExist)
            {
                IOUtility.CreateDirectory(directory, true);
            }
            return directory + "/" + configuration.ManifestLocalPath;
        }
Initialize()
void Meta.WitAi.Windows.WitConfigurationEditor.Initialize ()
Definition at line 82 of file WitConfigurationEditor.cs.
        {
            // Shared between all WitConfigurationEditors
            if (_tabTypes == null)
            {
                _tabTypes = typeof(WitConfigurationEditorTab).GetSubclassTypes().ToArray();
            }
            // Generate tab instances
            if (_tabs == null)
            {
                _tabs = _tabTypes.Select(type => (WitConfigurationEditorTab)Activator.CreateInstance(type))
                    .OrderBy(tab =>tab.TabOrder)
                    .ToArray();
            }
            // Refresh configuration & auth tokens
            Configuration = target as WitConfiguration;
            // Get app server token
            _serverToken = WitAuthUtility.GetAppServerToken(Configuration);
            if (CanConfigurationRefresh(Configuration) && WitConfigurationUtility.IsServerTokenValid(_serverToken))
            {
                // Get client token if needed
                _appID = Configuration.GetApplicationId();
                if (string.IsNullOrEmpty(_appID))
                {
                    Configuration.SetServerToken(_serverToken);
                }
                // Refresh additional data
                else
                {
                    SafeRefresh();
                }
            }
        }
LayoutConduitContent()
void Meta.WitAi.Windows.WitConfigurationEditor.LayoutConduitContent () private
Definition at line 158 of file WitConfigurationEditor.cs.
        {
            var isServerTokenValid = WitConfigurationUtility.IsServerTokenValid(_serverToken);
            if (!isServerTokenValid && !_disableServerPost)
            {
                GUILayout.TextArea(WitTexts.Texts.ConfigurationConduitMissingTokenLabel, WitStyles.LabelError);
            }
            EditorGUI.indentLevel++;
            // Set conduit
            var updated = false;
            WitEditorUI.LayoutToggle(new GUIContent(WitTexts.Texts.ConfigurationConduitUseConduitLabel), ref Configuration.useConduit, ref updated);
            if (updated)
            {
                EditorUtility.SetDirty(Configuration);
            }
            GenerateManifestIfNeeded();
            // Configuration buttons
            GUILayout.Space(EditorGUI.indentLevel * WitStyles.ButtonMargin);
            {
                GUI.enabled = Configuration.useConduit;
                updated = false;
                WitEditorUI.LayoutToggle(
                    new GUIContent(WitTexts.Texts.ConfigurationConduitRelaxedResolutionsLabel,
                        WitTexts.Texts.ConfigurationConduitRelaxedResolutionsTooltip),
                    ref Configuration.relaxedResolution, ref updated);
                if (updated)
                {
                    EditorUtility.SetDirty(Configuration);
                }
                GUILayout.BeginHorizontal();
                {
                    if (WitEditorUI.LayoutTextButton(_manifestAvailable ? WitTexts.Texts.ConfigurationConduitUpdateManifestLabel : WitTexts.Texts.ConfigurationConduitGenerateManifestLabel))
                    {
                        GenerateManifest(Configuration, true);
                    }
                    GUI.enabled = Configuration.useConduit && _manifestAvailable;
                    if (WitEditorUI.LayoutTextButton(WitTexts.Texts.ConfigurationConduitSelectManifestLabel) && _manifestAvailable)
                    {
                        Selection.activeObject =
                            AssetDatabase.LoadAssetAtPath<TextAsset>(Configuration.GetManifestEditorPath());
                    }
                    GUI.enabled = Configuration.useConduit;
                    if (WitEditorUI.LayoutTextButton(WitTexts.Texts.ConfigurationConduitSpecifyAssembliesLabel))
                    {
                        PresentAssemblySelectionDialog();
                    }
                    if (isServerTokenValid && !_disableServerPost)
                    {
                        GUI.enabled = Configuration.useConduit && _manifestAvailable && !_syncInProgress;
                        if (WitEditorUI.LayoutTextButton(WitTexts.Texts.ConfigurationConduitSyncEntitiesLabel))
{
                            SyncEntities();
                            GUIUtility.ExitGUI();
                            return;
                        }
                        if (_isAutoTrainAvailable)
{
                            if (WitEditorUI.LayoutTextButton(WitTexts.Texts.ConfigurationConduitAutoTrainLabel) && _manifestAvailable)
{
                                SyncEntities(() => { AutoTrainOnWitAi(Configuration); });
                            }
                        }
                    }
                    GUI.enabled = true;
                }
                GUILayout.EndHorizontal();
            }
            EditorGUI.indentLevel--;
        }
LayoutConfigurationData()
virtual void Meta.WitAi.Windows.WitConfigurationEditor.LayoutConfigurationData () protected virtual
Definition at line 370 of file WitConfigurationEditor.cs.
        {
            // Reset update
            bool updated = false;
            // Client access field
            string clientAccessToken = Configuration.GetClientAccessToken();
            WitEditorUI.LayoutPasswordField(WitTexts.ConfigurationClientTokenContent, ref clientAccessToken, ref updated);
            if (updated && string.IsNullOrEmpty(clientAccessToken))
            {
                VLog.E("Client access token is not defined. Cannot perform requests with '" + Configuration.name + "'.");
            }
            // Timeout field
            WitEditorUI.LayoutIntField(WitTexts.ConfigurationRequestTimeoutContent, ref Configuration.timeoutMS, ref updated);
            // Updated
            if (updated)
            {
                Configuration.SetClientAccessToken(clientAccessToken);
            }
            // Show configuration app data
            LayoutConfigurationEndpoint();
        }
LayoutConfigurationEndpoint()
virtual void Meta.WitAi.Windows.WitConfigurationEditor.LayoutConfigurationEndpoint () protected virtual
Definition at line 393 of file WitConfigurationEditor.cs.
        {
            // Generate if needed
            if (Configuration.endpointConfiguration == null)
            {
                Configuration.endpointConfiguration = new WitEndpointConfig();
                EditorUtility.SetDirty(Configuration);
            }
            // Handle via serialized object
            var serializedObj = new SerializedObject(Configuration);
            var serializedProp = serializedObj.FindProperty("endpointConfiguration");
            EditorGUILayout.PropertyField(serializedProp);
            serializedObj.ApplyModifiedProperties();
        }
LayoutConfigurationRequestTabs()
virtual void Meta.WitAi.Windows.WitConfigurationEditor.LayoutConfigurationRequestTabs () protected virtual
Definition at line 409 of file WitConfigurationEditor.cs.
        {
            // Application info
            Data.Info.WitAppInfo appInfo = Configuration.GetApplicationInfo();
            // Indent
            EditorGUI.indentLevel++;
            // Iterate tabs
            if (_tabs != null)
            {
                GUILayout.BeginHorizontal();
                for (int i = 0; i < _tabs.Length; i++)
                {
                    // Enable if not selected
                    GUI.enabled = _requestTab != i;
                    // If valid and clicked, begin selecting
                    if (null != appInfo.id &&_tabs[i].ShouldTabShow(appInfo))
                    {
                        if (WitEditorUI.LayoutTabButton(_tabs[i].GetTabText(true)))
{
                            _requestTab = i;
                        }
                    }
                    // If invalid, stop selecting
                    else if (_requestTab == i)
                    {
                        _requestTab = -1;
                    }
                }
                GUI.enabled = true;
                GUILayout.EndHorizontal();
                // Layout selected tab using property id
                string propertyID = _requestTab >= 0 && _requestTab < _tabs.Length
                    ? _tabs[_requestTab].TabID
                    : string.Empty;
                if (!string.IsNullOrEmpty(propertyID) && Configuration != null)
                {
                    SerializedObject serializedObj = new SerializedObject(Configuration);
                    SerializedProperty serializedProp = serializedObj.FindProperty(_tabs[_requestTab].GetPropertyName(propertyID));
                    if (serializedProp == null)
                    {
                        WitEditorUI.LayoutErrorLabel(_tabs[_requestTab].GetTabText(false));
                    }
                    else if (!serializedProp.isArray)
                    {
                        EditorGUILayout.PropertyField(serializedProp);
                    }
                    else if (serializedProp.arraySize == 0)
                    {
                        WitEditorUI.LayoutErrorLabel(_tabs[_requestTab].GetTabText(false));
                    }
                    else
                    {
                        for (int i = 0; i < serializedProp.arraySize; i++)
{
                            SerializedProperty serializedPropChild = serializedProp.GetArrayElementAtIndex(i);
                            EditorGUILayout.PropertyField(serializedPropChild);
                        }
                    }
                    serializedObj.ApplyModifiedProperties();
                }
            }
            // Undent
            EditorGUI.indentLevel--;
        }
LayoutContent()
virtual void Meta.WitAi.Windows.WitConfigurationEditor.LayoutContent () protected virtual
Definition at line 236 of file WitConfigurationEditor.cs.
        {
            // Begin vertical box
            GUILayout.BeginVertical(EditorStyles.helpBox);
            // Check for app name/id update
            ReloadAppData();
            // Title Foldout
            GUILayout.BeginHorizontal();
            string foldoutText = WitTexts.Texts.ConfigurationHeaderLabel;
            if (!string.IsNullOrEmpty(_appName))
            {
                foldoutText = foldoutText + " - " + _appName;
            }
            _foldout = WitEditorUI.LayoutFoldout(new GUIContent(foldoutText), _foldout);
            // Refresh button
            if (CanConfigurationRefresh(Configuration))
            {
                if (string.IsNullOrEmpty(_appName))
                {
                    bool isValid =  WitConfigurationUtility.IsServerTokenValid(_serverToken);
                    GUI.enabled = isValid;
                    if (WitEditorUI.LayoutTextButton(WitTexts.Texts.ConfigurationRefreshButtonLabel))
                    {
                        ApplyServerToken(_serverToken);
                    }
                }
                else
                {
                    bool isRefreshing = Configuration.IsUpdatingData();
                    GUI.enabled = !isRefreshing;
                    if (WitEditorUI.LayoutTextButton(isRefreshing ? WitTexts.Texts.ConfigurationRefreshingButtonLabel : WitTexts.Texts.ConfigurationRefreshButtonLabel))
                    {
                        SafeRefresh();
                    }
                }
            }
            GUI.enabled = true;
            GUILayout.EndHorizontal();
            GUILayout.Space(WitStyles.ButtonMargin);
            // Show configuration app data
            if (_foldout)
            {
                // Indent
                EditorGUI.indentLevel++;
                // Server access token
                bool updated = false;
                WitEditorUI.LayoutPasswordField(WitTexts.ConfigurationServerTokenContent, ref _serverToken, ref updated);
                if (updated && WitConfigurationUtility.IsServerTokenValid(_serverToken))
                {
                    ApplyServerToken(_serverToken);
                }
                // Additional data
                if (Configuration)
                {
                    LayoutConfigurationData();
                }
                // Undent
                EditorGUI.indentLevel--;
            }
            // End vertical box layout
            GUILayout.EndVertical();
            GUILayout.BeginVertical(EditorStyles.helpBox);
            LayoutConduitContent();
            GUILayout.EndVertical();
            // Layout configuration request tabs
            LayoutConfigurationRequestTabs();
            // Additional open wit button
            GUILayout.FlexibleSpace();
            if (GUILayout.Button(OpenButtonLabel, WitStyles.TextButton))
            {
                Application.OpenURL(HeaderUrl);
            }
        }
LoadManifest()
static Manifest Meta.WitAi.Windows.WitConfigurationEditor.LoadManifest (string manifestPath) static private
Definition at line 717 of file WitConfigurationEditor.cs.
        {
            var instanceKey = Telemetry.StartEvent(Telemetry.TelemetryEventId.LoadManifest);
            var manifest = ManifestLoader.LoadManifest(manifestPath);
            if (manifest == null)
            {
                Telemetry.EndEventWithFailure(instanceKey);
            }
            Telemetry.EndEvent(instanceKey, Telemetry.ResultType.Success);
            return manifest;
        }
OnDisable()
void Meta.WitAi.Windows.WitConfigurationEditor.OnDisable ()
Definition at line 118 of file WitConfigurationEditor.cs.
        {
            Statistics.Persist();
        }
OnInspectorGUI()
override void Meta.WitAi.Windows.WitConfigurationEditor.OnInspectorGUI ()
Definition at line 123 of file WitConfigurationEditor.cs.
        {
            // Init if needed
            if (!_initialized || Configuration != target)
            {
                Initialize();
                _initialized = true;
            }
            // Draw header
            WitEditorUI.LayoutHeaderText(target.name, HeaderUrl, DocsUrl);
            // Layout content
            LayoutContent();
        }
OnScriptsReloaded()
static void Meta.WitAi.Windows.WitConfigurationEditor.OnScriptsReloaded () static private
Definition at line 516 of file WitConfigurationEditor.cs.
{
            foreach (var configuration in WitConfigurationUtility.GetLoadedConfigurations())
            {
                if (configuration != null && configuration.useConduit)
                {
                    GenerateManifest(configuration, false);
                }
            }
        }
PresentAssemblySelectionDialog()
void Meta.WitAi.Windows.WitConfigurationEditor.PresentAssemblySelectionDialog () private
Definition at line 601 of file WitConfigurationEditor.cs.
        {
            var assemblyNames = AssemblyWalker.GetAllAssemblies().Select(a => a.FullName).ToList();
            AssemblyWalker.AssembliesToIgnore = new HashSet<string>(Configuration.excludedAssemblies);
            WitMultiSelectionPopup.Show(assemblyNames, AssemblyWalker.AssembliesToIgnore, (disabledAssemblies) => {
                AssemblyWalker.AssembliesToIgnore = new HashSet<string>(disabledAssemblies);
                Configuration.excludedAssemblies = new List<string>(AssemblyWalker.AssembliesToIgnore);
                GenerateManifestIfNeeded();
            });
        }
ReloadAppData()
void Meta.WitAi.Windows.WitConfigurationEditor.ReloadAppData () private
Definition at line 322 of file WitConfigurationEditor.cs.
        {
            // Check for changes
            string checkID = "";
            string checkName = "";
            if (Configuration != null)
            {
                checkID = Configuration.GetApplicationId();
                if (!string.IsNullOrEmpty(checkID))
                {
                    checkName = Configuration.GetApplicationInfo().name;
                }
            }
            // Reset
            if (!string.Equals(_appName, checkName) || !string.Equals(_appID, checkID))
            {
                // Refresh app data
                _appName = checkName;
                _appID = checkID;
                // Do not clear token if failed to set
                string newToken = WitAuthUtility.GetAppServerToken(Configuration);
                if (!string.IsNullOrEmpty(newToken))
                {
                    _serverToken = newToken;
                }
            }
        }
SafeRefresh()
virtual void Meta.WitAi.Windows.WitConfigurationEditor.SafeRefresh () protected virtual
Definition at line 481 of file WitConfigurationEditor.cs.
        {
            if (EditorApplication.isPlayingOrWillChangePlaymode) return;
            if (WitConfigurationUtility.IsServerTokenValid(_serverToken))
            {
                Configuration.SetServerToken(_serverToken);
            }
            else if (WitConfigurationUtility.IsClientTokenValid(Configuration.GetClientAccessToken()))
            {
                Configuration.RefreshAppInfo();
            }
            if (Configuration.useConduit)
            {
                CheckAutoTrainAvailabilityIfNeeded();
            }
        }
SyncEntities()
void Meta.WitAi.Windows.WitConfigurationEditor.SyncEntities (Action successCallback = null) private
Definition at line 613 of file WitConfigurationEditor.cs.
        {
            var instanceKey = Telemetry.StartEvent(Telemetry.TelemetryEventId.SyncEntities);
            if (!EditorUtility.DisplayDialog("Synchronizing with Wit.Ai entities", "This will synchronize local enums with Wit.Ai entities. Part of this process involves generating code locally and may result in overwriting existing code. Please make sure to backup your work before proceeding.", "Proceed", "Cancel", DialogOptOutDecisionType.ForThisSession, ENTITY_SYNC_CONSENT_KEY))
            {
                Telemetry.EndEvent(instanceKey, Telemetry.ResultType.Cancel);
                VLog.D("Entity Sync cancelled");
                return;
            }
            // Fail without server token
            var validServerToken = WitConfigurationUtility.IsServerTokenValid(_serverToken);
            if (!validServerToken)
            {
                Telemetry.EndEventWithFailure(instanceKey, "Invalid server token");
                VLog.E($"Conduit Sync Failed\nError: Invalid server token");
                return;
            }
            // Generate
            if (_enumSynchronizer == null)
            {
                _enumSynchronizer = new EnumSynchronizer(Configuration, AssemblyWalker, new FileIo(), VRequestFactory);
            }
            // Sync
            _syncInProgress = true;
            EditorUtility.DisplayProgressBar("Conduit Entity Sync", "Generating Manifest.", 0f );
            GenerateManifest(Configuration, false);
            var manifest = LoadManifest(Configuration.ManifestLocalPath);
            const float initializationProgress = 0.1f;
            EditorUtility.DisplayProgressBar("Conduit Entity Sync", "Synchronizing entities. Please wait...", initializationProgress);
            VLog.D("Synchronizing enums with Wit.Ai entities");
            CoroutineUtility.StartCoroutine(_enumSynchronizer.SyncWitEntities(manifest, (success, data) =>
                {
                    _syncInProgress = false;
                    EditorUtility.ClearProgressBar();
                    if (!success)
                    {
                        Telemetry.EndEventWithFailure(instanceKey, data);
                        VLog.E($"Conduit failed to synchronize entities\nError: {data}");
                    }
                    else
                    {
                        Telemetry.EndEvent(instanceKey, Telemetry.ResultType.Success);
                        VLog.D("Conduit successfully synchronized entities");
                        successCallback?.Invoke();
                    }
                },
                (status, progress) =>
                {
                    EditorUtility.DisplayProgressBar("Conduit Entity Sync", status,
                        initializationProgress + (1f - initializationProgress) * progress);
                }));
        }
Member Data Documentation
_appID
string Meta.WitAi.Windows.WitConfigurationEditor._appID private
Definition at line 34 of file WitConfigurationEditor.cs.
_appName
string Meta.WitAi.Windows.WitConfigurationEditor._appName private
Definition at line 33 of file WitConfigurationEditor.cs.
_didCheckAutoTrainAvailability
bool Meta.WitAi.Windows.WitConfigurationEditor._didCheckAutoTrainAvailability = false private
Definition at line 41 of file WitConfigurationEditor.cs.
_enumSynchronizer
EnumSynchronizer Meta.WitAi.Windows.WitConfigurationEditor._enumSynchronizer private
Definition at line 57 of file WitConfigurationEditor.cs.
_foldout
bool Meta.WitAi.Windows.WitConfigurationEditor._foldout = true private
Definition at line 37 of file WitConfigurationEditor.cs.
_initialized
bool Meta.WitAi.Windows.WitConfigurationEditor._initialized = false private
Definition at line 35 of file WitConfigurationEditor.cs.
_isAutoTrainAvailable
bool Meta.WitAi.Windows.WitConfigurationEditor._isAutoTrainAvailable = false private
Definition at line 42 of file WitConfigurationEditor.cs.
_manifestAvailable
bool Meta.WitAi.Windows.WitConfigurationEditor._manifestAvailable = false private
Definition at line 39 of file WitConfigurationEditor.cs.
_requestTab
int Meta.WitAi.Windows.WitConfigurationEditor._requestTab = 0 private
Definition at line 38 of file WitConfigurationEditor.cs.
_serverToken
string Meta.WitAi.Windows.WitConfigurationEditor._serverToken private
Definition at line 32 of file WitConfigurationEditor.cs.
_statistics
ConduitStatistics Meta.WitAi.Windows.WitConfigurationEditor._statistics static private
Definition at line 51 of file WitConfigurationEditor.cs.
_syncInProgress
bool Meta.WitAi.Windows.WitConfigurationEditor._syncInProgress = false private
Definition at line 40 of file WitConfigurationEditor.cs.
_tabs
WitConfigurationEditorTab [] Meta.WitAi.Windows.WitConfigurationEditor._tabs private
Definition at line 60 of file WitConfigurationEditor.cs.
_tabTypes
Type [] Meta.WitAi.Windows.WitConfigurationEditor._tabTypes static private
Definition at line 59 of file WitConfigurationEditor.cs.
AssemblyMiner
readonly AssemblyMiner Meta.WitAi.Windows.WitConfigurationEditor.AssemblyMiner = new AssemblyMiner(new WitParameterValidator()) static private
Definition at line 52 of file WitConfigurationEditor.cs.
drawHeader
bool Meta.WitAi.Windows.WitConfigurationEditor.drawHeader = true
Definition at line 36 of file WitConfigurationEditor.cs.
ENTITY_SYNC_CONSENT_KEY
const string Meta.WitAi.Windows.WitConfigurationEditor.ENTITY_SYNC_CONSENT_KEY = "Conduit.EntitySync.Consent" static private
Definition at line 62 of file WitConfigurationEditor.cs.
ManifestGenerator
readonly ManifestGenerator Meta.WitAi.Windows.WitConfigurationEditor.ManifestGenerator = new ManifestGenerator(AssemblyWalker, AssemblyMiner) static private
Definition at line 53 of file WitConfigurationEditor.cs.
ManifestLoader
readonly ManifestLoader Meta.WitAi.Windows.WitConfigurationEditor.ManifestLoader = new ManifestLoader() static private
Definition at line 54 of file WitConfigurationEditor.cs.
VRequestFactory
readonly IWitVRequestFactory Meta.WitAi.Windows.WitConfigurationEditor.VRequestFactory = new WitVRequestFactory() static private
Definition at line 55 of file WitConfigurationEditor.cs.
Property Documentation
_disableServerPost
virtual bool Meta.WitAi.Windows.WitConfigurationEditor._disableServerPost get protected
Whether or not server specific functionality like sync should be disabled for this configuration.
Definition at line 48 of file WitConfigurationEditor.cs.
Configuration
WitConfiguration Meta.WitAi.Windows.WitConfigurationEditor.Configuration get private set
Definition at line 31 of file WitConfigurationEditor.cs.
{ get; private set; }
DocsUrl
virtual string Meta.WitAi.Windows.WitConfigurationEditor.DocsUrl get protected
Definition at line 79 of file WitConfigurationEditor.cs.
HeaderIcon
virtual Texture2D Meta.WitAi.Windows.WitConfigurationEditor.HeaderIcon get protected
Definition at line 77 of file WitConfigurationEditor.cs.
HeaderUrl
virtual string Meta.WitAi.Windows.WitConfigurationEditor.HeaderUrl get
Definition at line 78 of file WitConfigurationEditor.cs.
OpenButtonLabel
virtual string Meta.WitAi.Windows.WitConfigurationEditor.OpenButtonLabel get protected
Definition at line 80 of file WitConfigurationEditor.cs.
Statistics
ConduitStatistics Meta.WitAi.Windows.WitConfigurationEditor.Statistics static get private
Definition at line 65 of file WitConfigurationEditor.cs.
        {
            get
            {
                if (_statistics == null)
                {
                    _statistics = new ConduitStatistics(new PersistenceLayer());
                }
                return _statistics;
            }
        }
The documentation for this class was generated from the following file:
Assets/Oculus/Voice/Lib/Wit.ai/Scripts/Editor/Data/Configuration/WitConfigurationEditor.cs