VR_Test: Oculus.Interaction.AssertUtils Class Reference
Oculus.Interaction.AssertUtils Class Reference
Static Public Member Functions
static void AssertIsTrue (this Component component, bool value, string whyItFailed=null, string whereItFailed=null, string howToFix=null)
Asserts that the expression is True. In case of failure, it will print an error showing where the failure happened.
static void AssertAspect< TValue > (this Component component, TValue aspect, string aspectLocation, string whyItFailed=null, string whereFailed=null, string howToFix=null)
Asserts that an Aspect exists. In case of failure, it will print an error showing why it failed, where it failed and suggest how to fix it.
static void AssertField< TValue > (this Component component, TValue value, string variableName, string whyItFailed=null, string whereItFailed=null, string howToFix=null)
Asserts that a Serialized Field in a Component is not null. In case of failure, it will print an error showing why it failed, where it failed and suggest how to fix it.
static void AssertCollectionField< TValue > (this Component component, IEnumerable< TValue > value, string variableName, string whyItFailed=null, string whereFailed=null, string howToFix=null)
Asserts that a Serialized collection in a Component is not null, is not empty and all of its items exist. In case of failure, it will print an error showing why it failed, where it failed and suggest how to fix it.
static void AssertCollectionItems< TValue > (this Component component, IEnumerable< TValue > value, string variableName, string whyItFailed=null, string whereItFailed=null, string howToFix=null)
Asserts that each item in a Serialized collection in a Component is not null. Note that the collection it might contain 0 items. In case of failure, it will print an error showing why it failed, where it failed and suggest how to fix it.
static string Nicify (string variableName)
Make a displayable name for a variable. This function will insert spaces before capital letters and remove optional m_, _ or k followed by uppercase letter in front of the name.
Static Public Attributes
const string HiglightColor = "#3366ff"
Detailed Description
Definition at line 30 of file AssertUtils.cs.
Member Function Documentation
AssertAspect< TValue >()
static void Oculus.Interaction.AssertUtils.AssertAspect< TValue > (this Component component, TValue aspect, string aspectLocation, string whyItFailed = null, string whereFailed = null, string howToFix = null) static
Asserts that an Aspect exists. In case of failure, it will print an error showing why it failed, where it failed and suggest how to fix it.
Template Parameters
TValue The type of Aspect to be checked
Parameters
component The component requiring this Aspect
aspect The Aspect to be checked
aspectLocation The expected location of the Aspect
whyItFailed Optional parameter specifying the reason the assert failed. If none is provided it will print the expected aspect type and location.
whereFailed Optional parameter specifying where the failure can be found. If none is provided it will print the component address (GameObject->Component).
howToFix Optional parameter suggesting how to fix the problem. If none is provided it will suggest assigning an Aspect of the required type to the expected location.
Type Constraints
TValue : class
Definition at line 74 of file AssertUtils.cs.
                         : class
        {
            string gameObjectName = component.name;
            string componentName = component.GetType().Name;
            string niceVariableName = Nicify(aspectLocation);
            string aspectType = typeof(TValue).Name;
            Assert.IsNotNull(aspect,
                (whereFailed ?? $"At GameObject <color={HiglightColor}><b>{gameObjectName}</b></color>, component <b>{componentName}</b>. ") +
                (whyItFailed ?? $"Could not find the required Aspect <b>{aspectType}</b> in the associated <b>{niceVariableName}</b>. ") +
                (howToFix ?? $"Assign an Aspect of type <b>{aspectType}</b> to the associated <b>{niceVariableName}</b>."));
        }
References Oculus.Interaction.AssertUtils.Nicify().
AssertCollectionField< TValue >()
static void Oculus.Interaction.AssertUtils.AssertCollectionField< TValue > (this Component component, IEnumerable< TValue > value, string variableName, string whyItFailed = null, string whereFailed = null, string howToFix = null) static
Asserts that a Serialized collection in a Component is not null, is not empty and all of its items exist. In case of failure, it will print an error showing why it failed, where it failed and suggest how to fix it.
Template Parameters
TValue The type of the items in the collection.
Parameters
component The component to which this collection belongs.
value The value of the collection.
variableName The printed name of the serialized collection.
whyItFailed Optional parameter specifying the reason the assert failed. If none is provided it will indicate that the collection value needs at least one valid item.
whereFailed Optional parameter specifying where the failure can be found. If none is provided it will print the component address (GameObject->Component->Collection Name).
howToFix Optional parameter suggesting how to fix the problem. If none is provided it will suggest assigning at least one valid item of the required type to the collection.
Definition at line 139 of file AssertUtils.cs.
        {
            string gameObjectName = component.name;
            string componentName = component.GetType().Name;
            string niceVariableName = Nicify(variableName);
            string variableType = typeof(TValue).Name;
            Assert.IsTrue(value != null && value.Count() > 0,
                (whereFailed ?? $"At GameObject <color={HiglightColor}><b>{gameObjectName}</b></color>: the <b>{componentName}</b> component has an missing or empty <b>{niceVariableName}</b> collection. ") +
                (whyItFailed ?? "") +
                (howToFix ?? $"Assign at least one <b>{variableType}</b> to the collection <b>{niceVariableName}</b>. "));
            component.AssertCollectionItems(value, variableName);
        }
References Oculus.Interaction.AssertUtils.Nicify().
AssertCollectionItems< TValue >()
static void Oculus.Interaction.AssertUtils.AssertCollectionItems< TValue > (this Component component, IEnumerable< TValue > value, string variableName, string whyItFailed = null, string whereItFailed = null, string howToFix = null) static
Asserts that each item in a Serialized collection in a Component is not null. Note that the collection it might contain 0 items. In case of failure, it will print an error showing why it failed, where it failed and suggest how to fix it.
Template Parameters
TValue The type of the items in the collection
Parameters
component The component to which the collection belongs.
value The value of the collection.
variableName The printed name of the serialized collection.
whyItFailed Optional parameter specifying the reason the assert failed. If none is provided it will indicate, for each failed item, that the item must not be null.
whereItFailed Optional parameter specifying where the failure can be found. If none is provided it will print the component address (GameObject->Component->Collection Name).
howToFix Optional parameter suggesting how to fix the problem. If none is provided it will suggest assigning a valid item of the required type to the collection at each missing index.
Definition at line 174 of file AssertUtils.cs.
        {
            string gameObjectName = component.name;
            string componentName = component.GetType().Name;
            string niceVariableName = Nicify(variableName);
            string variableType = typeof(TValue).Name;
            int index = 0;
            foreach (TValue item in value)
            {
                Assert.IsFalse(item is null,
                    (whereItFailed ?? $"At GameObject <color={HiglightColor}><b>{gameObjectName}</b></color>, component <b>{componentName}</b>. ") +
                    (whyItFailed ?? $"Invalid item in the collection <b>{niceVariableName}</b> at index <b>{index}</b>. ") +
                    (howToFix ?? $"Assign a <b>{variableType}</b> to the collection <b>{niceVariableName}</b> at index <b>{index}</b>. "));
                index++;
            }
        }
References Oculus.Interaction.AssertUtils.Nicify().
AssertField< TValue >()
static void Oculus.Interaction.AssertUtils.AssertField< TValue > (this Component component, TValue value, string variableName, string whyItFailed = null, string whereItFailed = null, string howToFix = null) static
Asserts that a Serialized Field in a Component is not null. In case of failure, it will print an error showing why it failed, where it failed and suggest how to fix it.
Template Parameters
TValue The type of field to be checked
Parameters
component The component to which this field belongs.
value The value of the field.
variableName The printed name of the serialized field.
whyItFailed Optional parameter specifying the reason the assert failed. If none is provided it will indicate that the field value was null.
whereItFailed Optional parameter specifying where the failure can be found. If none is provided it will print the component address (GameObject->Component->Field Name).
howToFix Optional parameter suggesting how to fix the problem. If none is provided it will suggest assigning a value of the required type to the field.
Type Constraints
TValue : class
Definition at line 106 of file AssertUtils.cs.
                         : class
        {
            string gameObjectName = component.name;
            string componentName = component.GetType().Name;
            string niceVariableName = Nicify(variableName);
            string variableType = typeof(TValue).Name;
            Assert.IsNotNull(value,
                (whereItFailed ?? $"At GameObject <color={HiglightColor}><b>{gameObjectName}</b></color>, component <b>{componentName}</b>. ") +
                (whyItFailed ?? $"Required <b>{niceVariableName}</b> reference is missing. ") +
                (howToFix ?? $"Assign a <b>{variableType}</b> to the field <b>{niceVariableName}</b>."));
        }
References Oculus.Interaction.AssertUtils.Nicify().
AssertIsTrue()
static void Oculus.Interaction.AssertUtils.AssertIsTrue (this Component component, bool value, string whyItFailed = null, string whereItFailed = null, string howToFix = null) static
Asserts that the expression is True. In case of failure, it will print an error showing where the failure happened.
Parameters
component The component to which the value expression belongs
value The expression that should be true
whyItFailed Optional parameter specifying the reason the assert failed
whereItFailed Optional parameter specifying where the failure can be found. If none is provided it will print the component address (GameObject->Component).
howToFix Optional parameter suggesting how to fix the problem.
Definition at line 45 of file AssertUtils.cs.
        {
            string gameObjectName = component.name;
            string componentName = component.GetType().Name;
            Assert.IsTrue(value,
                (whereItFailed ?? $"At GameObject <color={ HiglightColor}><b>{ gameObjectName}</b></color>, component <b>{ componentName}</b>. ") +
                (whyItFailed ?? "") +
                (howToFix ?? ""));
        }
Nicify()
static string Oculus.Interaction.AssertUtils.Nicify (string variableName) static
Make a displayable name for a variable. This function will insert spaces before capital letters and remove optional m_, _ or k followed by uppercase letter in front of the name.
Parameters
variableName The variable name as used in code
Returns
The nicified variable
Definition at line 200 of file AssertUtils.cs.
        {
            variableName = Regex.Replace(variableName, "_([a-z])", match => match.Value.ToUpper(), RegexOptions.Compiled);
            variableName = Regex.Replace(variableName, "m_|_", " ", RegexOptions.Compiled);
            variableName = Regex.Replace(variableName, "k([A-Z])", "$1", RegexOptions.Compiled);
            variableName = Regex.Replace(variableName, "([A-Z])", " $1", RegexOptions.Compiled);
            variableName = variableName.Trim();
            return variableName;
        }
Member Data Documentation
HiglightColor
const string Oculus.Interaction.AssertUtils.HiglightColor = "#3366ff" static
Definition at line 32 of file AssertUtils.cs.
The documentation for this class was generated from the following file:
Assets/Oculus/Interaction/Runtime/Scripts/Utils/AssertUtils.cs