VR_Test: Meta.WitAi.Requests.WitTTSVRequest Class Reference
Meta.WitAi.Requests.WitTTSVRequest Class Reference
Public Member Functions
WitTTSVRequest (IWitRequestConfiguration configuration, string requestId, string textToSpeak, Dictionary< string, string > ttsData, TTSWitAudioType audioFileType, bool audioStream=false, RequestProgressDelegate onDownloadProgress=null, RequestFirstResponseDelegate onFirstResponse=null)
Constructor for wit based text-to-speech VRequests.
bool RequestStream (IAudioClipStream clipStream, RequestCompleteDelegate< IAudioClipStream > onClipReady)
Streams text to speech audio clip.
bool RequestDownload (string downloadPath, RequestCompleteDelegate< bool > onComplete)
TTS streaming audio request.
Public Member Functions inherited from Meta.WitAi.Requests.WitVRequest
WitVRequest (IWitRequestConfiguration configuration, string requestId, bool useServerToken=false, RequestProgressDelegate onDownloadProgress=null, RequestFirstResponseDelegate onFirstResponse=null)
Constructor that takes in a configuration interface.
Uri GetUri (string path, Dictionary< string, string > queryParams=null)
override bool Request (UnityWebRequest unityRequest, RequestCompleteDelegate< UnityWebRequest > onComplete)
Perform a generic request.
bool RequestWitGet< TData > (string uriEndpoint, Dictionary< string, string > uriParams, RequestCompleteDelegate< TData > onComplete)
Get request to a wit endpoint.
bool RequestWitPost< TData > (string uriEndpoint, Dictionary< string, string > uriParams, string postText, RequestCompleteDelegate< TData > onComplete)
Post text request to a wit endpoint.
bool RequestWitPut< TData > (string uriEndpoint, Dictionary< string, string > uriParams, string putText, RequestCompleteDelegate< TData > onComplete)
Put text request to a wit endpoint.
Public Member Functions inherited from Meta.WitAi.Requests.VRequest
delegate void RequestProgressDelegate (float progress)
delegate void RequestFirstResponseDelegate ()
delegate void RequestCompleteDelegate< TResult > (TResult result, string error)
VRequest (RequestProgressDelegate onDownloadProgress=null, RequestFirstResponseDelegate onFirstResponse=null)
A constructor that takes in download progress delegate & first response delegate.
virtual string CleanUrl (string url)
Clean the url prior to use.
virtual void Cancel ()
bool RequestFileHeaders (Uri uri, RequestCompleteDelegate< Dictionary< string, string > > onComplete)
Performs a simple http header request.
bool RequestFile (Uri uri, RequestCompleteDelegate< byte[]> onComplete)
Performs a simple http header request.
bool RequestFileDownload (string downloadPath, UnityWebRequest unityRequest, RequestCompleteDelegate< bool > onComplete)
Download a file using a unityrequest.
bool RequestFileExists (string checkPath, RequestCompleteDelegate< bool > onComplete)
Checks if a file exists at a specified location.
bool RequestText (UnityWebRequest unityRequest, RequestCompleteDelegate< string > onComplete)
Performs a text request & handles the resultant text.
bool RequestJson< TData > (UnityWebRequest unityRequest, RequestCompleteDelegate< TData > onComplete)
Performs a json request & handles the resultant text.
bool RequestJsonGet< TData > (Uri uri, RequestCompleteDelegate< TData > onComplete)
Perform a json get request with a specified uri.
bool RequestJsonPost< TData > (Uri uri, byte[] postData, RequestCompleteDelegate< TData > onComplete)
Performs a json request by posting byte data.
bool RequestJsonPost< TData > (Uri uri, string postText, RequestCompleteDelegate< TData > onComplete)
Performs a json request by posting a string.
bool RequestJsonPut< TData > (Uri uri, byte[] putData, RequestCompleteDelegate< TData > onComplete)
Performs a json put request with byte data.
bool RequestJsonPut< TData > (Uri uri, string putText, RequestCompleteDelegate< TData > onComplete)
Performs a json put request with a string.
bool RequestAudioStream (IAudioClipStream clipStream, UnityWebRequest unityRequest, RequestCompleteDelegate< IAudioClipStream > onClipStreamReady, AudioType audioType, bool audioStream)
Request audio clip with url, type, progress delegate & ready delegate.
bool RequestAudioStream (IAudioClipStream clipStream, Uri uri, RequestCompleteDelegate< IAudioClipStream > onClipReady, AudioType audioType, bool audioStream)
Request audio clip with url, type, progress delegate & ready delegate.
Static Public Member Functions
static AudioType GetAudioType (TTSWitAudioType witAudioType)
static string GetAudioMimeType (TTSWitAudioType witAudioType)
static string GetAudioExtension (TTSWitAudioType witAudioType)
static string GetAudioExtension (AudioType audioType)
static bool CanStreamAudio (TTSWitAudioType witAudioType)
Static Public Member Functions inherited from Meta.WitAi.Requests.WitVRequest
static Uri GetWitUri (IWitRequestConfiguration configuration, string path, Dictionary< string, string > queryParams=null)
Get custom wit uri using a specific path & query parameters.
static Dictionary< string, string > GetWitHeaders (IWitRequestConfiguration configuration, string requestId, bool useServerToken)
Obtain headers to be used with every wit service.
Static Public Member Functions inherited from Meta.WitAi.Requests.VRequest
static string GetSpecificRequestError (UnityWebRequest request)
Protected Member Functions
override Dictionary< string, string > GetHeaders ()
Protected Member Functions inherited from Meta.WitAi.Requests.WitVRequest
override Dictionary< string, string > GetHeaders ()
Protected Member Functions inherited from Meta.WitAi.Requests.VRequest
virtual IEnumerator PerformUpdate ()
virtual void Begin ()
virtual bool IsRequestComplete ()
virtual void Complete ()
virtual void Unload ()
Properties
string TextToSpeak [get]
Dictionary< string, string > TtsData [get]
TTSWitAudioType FileType [get]
bool Stream [get]
Properties inherited from Meta.WitAi.Requests.WitVRequest
string RequestId [get, private set]
The unique identifier used by Wit to track requests.
IWitRequestConfiguration Configuration [get, private set]
The configuration used for voice requests.
Properties inherited from Meta.WitAi.Requests.VRequest
int Timeout = 5 [get, set]
Timeout in seconds.
bool IsPerforming = false [get, private set]
If request is currently being performed.
bool IsComplete = false [get, private set]
Whether or not the completion delegate has been called.
int ResponseCode = 0 [get, set]
Response Code if applicable.
float UploadProgress = 0f [get, private set]
Current progress for get requests.
float DownloadProgress = 0f [get, private set]
Current progress for download.
Private Member Functions
void EncodePostBytesAsync (string textToSpeak, Dictionary< string, string > ttsData, Action< byte[]> onEncoded)
byte[] EncodePostData (string textToSpeak, Dictionary< string, string > ttsData)
UnityWebRequest GetUnityRequest (TTSWitAudioType audioType, byte[] postData)
Additional Inherited Members
Static Public Attributes inherited from Meta.WitAi.Requests.VRequest
static int MaxConcurrentRequests = 3
Will only start new requests if there are less than this number If <= 0, then all requests will run immediately.
Events inherited from Meta.WitAi.Requests.WitVRequest
static Func< UriBuilder, UriBuilder > OnProvideCustomUri
Uri customization delegate.
static Action< Dictionary< string, string > > OnProvideCustomHeaders
Header customization delegate.
static Action< StringBuilder > OnProvideCustomUserAgent
User agent customization delegate.
Detailed Description
Definition at line 32 of file WitTTSVRequest.cs.
Constructor & Destructor Documentation
WitTTSVRequest()
Meta.WitAi.Requests.WitTTSVRequest.WitTTSVRequest (IWitRequestConfiguration configuration, string requestId, string textToSpeak, Dictionary< string, string > ttsData, TTSWitAudioType audioFileType, bool audioStream = false, RequestProgressDelegate onDownloadProgress = null, RequestFirstResponseDelegate onFirstResponse = null)
Constructor for wit based text-to-speech VRequests.
Parameters
configuration The configuration interface to be used
requestId A unique identifier that can be used to track the request
textToSpeak The text to be spoken by the request
ttsData The text parameters used for the request
audioFileType The expected audio file type of the request
audioStream Whether the audio should be played while streaming or should wait until completion.
onDownloadProgress The callback for progress related to downloading
onFirstResponse The callback for the first response of data from a request
Definition at line 55 of file WitTTSVRequest.cs.
            : base(configuration, requestId, false, onDownloadProgress, onFirstResponse)
        {
            TextToSpeak = textToSpeak;
            TtsData = ttsData;
            FileType = audioFileType;
            Stream = audioStream;
            Timeout = WitConstants.ENDPOINT_TTS_TIMEOUT;
        }
References Meta.WitAi.Requests.VRequest.Timeout.
Member Function Documentation
CanStreamAudio()
static bool Meta.WitAi.Requests.WitTTSVRequest.CanStreamAudio (TTSWitAudioType witAudioType) static
Definition at line 230 of file WitTTSVRequest.cs.
        {
            switch (witAudioType)
            {
                // Raw PCM: Supported by Wit.ai & custom unity implementation (DownloadHandlerRawPCM)
                case TTSWitAudioType.PCM:
                    return true;
                #if OGG_SUPPORT
                // OGG: Supported by Unity (DownloadHandlerAudioClip) but not by Wit.ai
                case TTSWitAudioType.OGG:
                    return true;
                #endif
                // MP3: Supported by Wit.ai but not by Unity (DownloadHandlerAudioClip)
                case TTSWitAudioType.MPEG:
                    return false;
                // WAV: does not support streaming
                case TTSWitAudioType.WAV:
                default:
                    return false;
            }
        }
EncodePostData()
byte[] Meta.WitAi.Requests.WitTTSVRequest.EncodePostData (string textToSpeak, Dictionary< string, string > ttsData) private
Definition at line 144 of file WitTTSVRequest.cs.
        {
            ttsData[WitConstants.ENDPOINT_TTS_PARAM] = textToSpeak;
            string jsonString = JsonConvert.SerializeObject(ttsData);
            return Encoding.UTF8.GetBytes(jsonString);
        }
GetAudioExtension()
static string Meta.WitAi.Requests.WitTTSVRequest.GetAudioExtension (AudioType audioType) static
Definition at line 208 of file WitTTSVRequest.cs.
        {
            switch (audioType)
            {
                // PCM
                case AudioType.UNKNOWN:
                    return "raw";
                // OGG
                case AudioType.OGGVORBIS:
                    return "ogg";
                // MP3
                case AudioType.MPEG:
                    return "mp3";
                // WAV
                case AudioType.WAV:
                    return "wav";
                default:
                    VLog.W($"Attempting to process unsupported audio type: {audioType}");
                    return audioType.ToString().ToLower();
            }
        }
GetAudioMimeType()
static string Meta.WitAi.Requests.WitTTSVRequest.GetAudioMimeType (TTSWitAudioType witAudioType) static
Definition at line 187 of file WitTTSVRequest.cs.
        {
            switch (witAudioType)
            {
                // PCM
                case TTSWitAudioType.PCM:
                    return "audio/raw";
                #if OGG_SUPPORT
                // OGG
                case TTSWitAudioType.OGG:
                #endif
                // MP3 & WAV
                case TTSWitAudioType.MPEG:
                case TTSWitAudioType.WAV:
                default:
                    return $"audio/{witAudioType.ToString().ToLower()}";
            }
        }
GetAudioType()
static AudioType Meta.WitAi.Requests.WitTTSVRequest.GetAudioType (TTSWitAudioType witAudioType) static
Definition at line 168 of file WitTTSVRequest.cs.
        {
            switch (witAudioType)
            {
                #if OGG_SUPPORT
                case TTSWitAudioType.OGG:
                    return AudioType.OGGVORBIS;
                #endif
                case TTSWitAudioType.MPEG:
                    return AudioType.MPEG;
                case TTSWitAudioType.WAV:
                    return AudioType.WAV;
                // Custom implementation
                case TTSWitAudioType.PCM:
                default:
                    return AudioType.UNKNOWN;
            }
        }
GetHeaders()
override Dictionary< string, string > Meta.WitAi.Requests.WitTTSVRequest.GetHeaders () protected virtual
Reimplemented from Meta.WitAi.Requests.VRequest.
Definition at line 69 of file WitTTSVRequest.cs.
        {
            Dictionary<string, string> headers = base.GetHeaders();
            headers[WitConstants.HEADER_POST_CONTENT] = "application/json";
            headers[WitConstants.HEADER_GET_CONTENT] = GetAudioMimeType(FileType);
            return headers;
        }
GetUnityRequest()
UnityWebRequest Meta.WitAi.Requests.WitTTSVRequest.GetUnityRequest (TTSWitAudioType audioType, byte[] postData) private
Definition at line 152 of file WitTTSVRequest.cs.
        {
            // Get uri
            Uri uri = GetUri(Configuration.GetEndpointInfo().Synthesize);
            // Generate request
            UnityWebRequest unityRequest = new UnityWebRequest(uri, UnityWebRequest.kHttpVerbPOST);
            // Add upload handler
            unityRequest.uploadHandler = new UploadHandlerRaw(postData);
            // Perform json request
            return unityRequest;
        }
RequestDownload()
bool Meta.WitAi.Requests.WitTTSVRequest.RequestDownload (string downloadPath, RequestCompleteDelegate< bool > onComplete)
TTS streaming audio request.
Parameters
downloadPath Download path
onComplete Clip completed download
Returns
False if request cannot be called
Definition at line 116 of file WitTTSVRequest.cs.
        {
            // Error
            if (string.IsNullOrEmpty(TextToSpeak))
            {
                onComplete?.Invoke(false, WitConstants.ENDPOINT_TTS_NO_TEXT);
                return false;
            }
            // Async encode
            EncodePostBytesAsync(TextToSpeak, TtsData, (bytes) =>
            {
                // Get tts unity request
                UnityWebRequest unityRequest = GetUnityRequest(FileType, bytes);
                // Perform an audio stream request
                RequestFileDownload(downloadPath, unityRequest, onComplete);
            });
            return true;
        }
References Meta.WitAi.Requests.VRequest.RequestFileDownload().
RequestStream()
bool Meta.WitAi.Requests.WitTTSVRequest.RequestStream (IAudioClipStream clipStream, RequestCompleteDelegate< IAudioClipStream > onClipReady)
Streams text to speech audio clip.
Parameters
onClipReady Clip ready to be played
onProgress Clip load progress
Returns
False if request cannot be called
Definition at line 83 of file WitTTSVRequest.cs.
        {
            // Error if no text is provided
            if (string.IsNullOrEmpty(TextToSpeak))
            {
                onClipReady?.Invoke(null, WitConstants.ENDPOINT_TTS_NO_TEXT);
                return false;
            }
            // Warn if incompatible with streaming
            if (Stream && !CanStreamAudio(FileType))
            {
                VLog.W($"Wit cannot stream {FileType} files please use {TTSWitAudioType.PCM} instead.");
            }
            // Async encode
            EncodePostBytesAsync(TextToSpeak, TtsData, (bytes) =>
            {
                // Get tts unity request
                UnityWebRequest unityRequest = GetUnityRequest(FileType, bytes);
                // Perform an audio stream request
                RequestAudioStream(clipStream, unityRequest, onClipReady, GetAudioType(FileType), Stream);
            });
            return true;
        }
References Meta.WitAi.Requests.VRequest.RequestAudioStream(), and Meta.WitAi.VLog.W().
Property Documentation
FileType
TTSWitAudioType Meta.WitAi.Requests.WitTTSVRequest.FileType get
Definition at line 40 of file WitTTSVRequest.cs.
{ get; }
Stream
bool Meta.WitAi.Requests.WitTTSVRequest.Stream get
Definition at line 42 of file WitTTSVRequest.cs.
{ get; }
TextToSpeak
string Meta.WitAi.Requests.WitTTSVRequest.TextToSpeak get
Definition at line 35 of file WitTTSVRequest.cs.
{ get; }
TtsData
Dictionary<string, string> Meta.WitAi.Requests.WitTTSVRequest.TtsData get
Definition at line 37 of file WitTTSVRequest.cs.
{ get; }
The documentation for this class was generated from the following file:
Assets/Oculus/Voice/Lib/Wit.ai/Lib/Wit/Runtime/Requests/UnityRequests/WitTTSVRequest.cs