VR_Test: Meta.Voice.NLPAudioRequest< TUnityEvent, TOptions, TEvents, TResults > Class Template Reference
Meta.Voice.NLPAudioRequest< TUnityEvent, TOptions, TEvents, TResults > Class Template Reference abstract
Abstract class for all NLP audio requests.
Public Member Functions
virtual void CompleteEarly ()
Cancels the current request but handles success immediately if possible.
Public Member Functions inherited from Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >
virtual void ActivateAudio ()
Public request to activate audio input.
virtual void DeactivateAudio ()
Public request to deactivate audio input.
override void Send ()
Ensure audio is activated prior to sending.
override void Cancel (string reason=WitConstants.CANCEL_MESSAGE_DEFAULT)
Ensure audio is deactivated prior to cancellation.
Public Member Functions inherited from Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >
VoiceRequest (TOptions newOptions, TEvents newEvents)
Constructor class for voice requests.
Protected Member Functions
NLPAudioRequest (TOptions newOptions, TEvents newEvents)
Constructor class for NLP audio requests.
override void OnInit ()
Initializes the request, and ensures that the request commences in a non-finalized state.
virtual void HandlePartialNlpResponse (WitResponseNode responseData)
Method to be called when an NLP request had completed.
void ApplyResultResponseData (WitResponseNode newData)
Applies response data to the current results.
virtual void OnPartialResponse ()
Called when response data has been updated.
virtual void HandleFinalNlpResponse (WitResponseNode responseData, string error)
Method to be called when an NLP request had completed.
virtual void OnFullResponse ()
Called when response data has been updated for the final time.
Protected Member Functions inherited from Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >
TranscriptionRequest (TOptions newOptions, TEvents newEvents)
Constructor class for transcription requests.
virtual void SetAudioInputState (VoiceAudioInputState newAudioInputState)
Set audio input state.
override void AppendLogData (StringBuilder log, bool warning)
Append request specific data to log.
void ApplyTranscription (string newTranscription, bool newIsFinal)
Applies a transcription to the current results.
virtual void OnTranscriptionChanged ()
Called when transcription has been set.
string GetActivateAudioError ()
Implementations need to provide errors when audio input is not found.
virtual void OnAudioActivation ()
Called when audio activation begins.
void HandleAudioActivation ()
Child class audio activation handler needs to call SetAudioInputState when complete.
virtual void OnStartListening ()
Called when audio activation is in effect and input is being listened to.
virtual void OnAudioDeactivation ()
Called when audio deactivation begins.
void HandleAudioDeactivation ()
Child class audio deactivation handler needs to call SetAudioInputState when complete.
virtual void OnStopListening ()
Called when audio input state is no longer being listened to.
override void OnSuccess ()
Method for subclass success handling.
Protected Member Functions inherited from Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >
virtual void SetState (VoiceRequestState newState)
Apply the voice request state.
void SetDownloadProgress (float newProgress)
Set current request download progress.
void SetUploadProgress (float newProgress)
Set current request upload progress.
void RaiseEvent (TUnityEvent requestEvent)
Raises a voice request event.
void Log (string log, bool warning=false)
Internal method for.
void LogW (string log)
virtual string GetSendError ()
Internal way to determine send error.
virtual void OnSend ()
Call after transmission begins.
void HandleSend ()
Child class send implementation Call HandleFailure, HandleCancel from this class.
TResults GetResultsWithMessage (string newMessage)
Returns an empty result object with a specific message.
virtual void HandleFailure (string error)
Method for handling failure with only an error string.
virtual void HandleFailure (TResults results)
Method for handling failure with a full result object.
virtual void OnFailed ()
Call after failure state set.
virtual void HandleSuccess (TResults results)
Method for handling success with a full result object.
void HandleCancel ()
Handle cancelation in subclass.
virtual void OnCancel ()
Call after cancellation state set.
virtual void OnComplete ()
Call after failure, success or cancellation.
Properties
WitResponseNode ResponseData [get]
Getter for response data.
Properties inherited from Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >
VoiceAudioInputState AudioInputState = VoiceAudioInputState.Off [get, private set]
The current audio input state.
bool IsAudioInputActivated [get]
Whether or not audio is currently activated.
bool IsListening [get]
Whether or not audio is currently being listened to.
bool CanActivateAudio [get]
Determine whether audio can be activated based on activation error existing.
bool CanDeactivateAudio [get]
Determine whether audio can be activated based on activation error existing.
string Transcription [get]
Transcription data.
bool IsFinalTranscription [get]
Whether the current transcription is a final transcription or not.
string[] FinalTranscriptions [get]
An array of all finalized transcriptions.
Properties inherited from Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >
VoiceRequestState State = (VoiceRequestState) (-1) [get, private set]
The states of a voice request.
bool IsActive [get]
Active if not currently canceled, failed or successful.
float DownloadProgress = 0f [get, private set]
Download progress of the current request transmission if available.
float UploadProgress = 0f [get, private set]
Upload progress of the current request transmission if available.
TOptions Options [get, private set]
Options sent as the request parameters.
TEvents Events [get, private set]
Events specific to this voice request.
TResults Results [get, protected set]
Results returned from the request.
bool CanSend [get]
Whether request can currently transmit data.
Properties inherited from Meta.Voice.IVoiceRequest< TUnityEvent, TOptions, TEvents, TResults >
Properties inherited from Meta.Voice.ITranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >
Private Attributes
bool _isFinalized = false
Detailed Description
Abstract class for all NLP audio requests.
Template Parameters
TUnityEvent The type of event callback performed by TEvents for all event callbacks
TOptions The type containing all specific options to be passed to the end service.
TEvents The type containing all events of TSession to be called throughout the lifecycle of the request.
TResults The type containing all data that can be returned from the end service.
Type Constraints
TUnityEvent : UnityEventBase
TOptions : INLPAudioRequestOptions
TEvents : NLPAudioRequestEvents<TUnityEvent>
TResults : INLPAudioRequestResults
Definition at line 22 of file NLPAudioRequest.cs.
Constructor & Destructor Documentation
NLPAudioRequest()
Meta.Voice.NLPAudioRequest< TUnityEvent, TOptions, TEvents, TResults >.NLPAudioRequest (TOptions newOptions, TEvents newEvents) protected
Constructor class for NLP audio requests.
Parameters
newOptions The request parameters to be used
newEvents The request events to be called throughout it's lifecycle
Definition at line 35 of file NLPAudioRequest.cs.
: base(newOptions, newEvents) {}
Member Function Documentation
ApplyResultResponseData()
void Meta.Voice.NLPAudioRequest< TUnityEvent, TOptions, TEvents, TResults >.ApplyResultResponseData (WitResponseNode newData) abstract protected
Applies response data to the current results.
Parameters
newData The returned response data
CompleteEarly()
virtual void Meta.Voice.NLPAudioRequest< TUnityEvent, TOptions, TEvents, TResults >.CompleteEarly () virtual
Cancels the current request but handles success immediately if possible.
Definition at line 140 of file NLPAudioRequest.cs.
        {
            // Ignore if not in correct state
            if (!IsActive || _isFinalized)
            {
                return;
            }
            // Cancel instead
            if (ResponseData == null)
            {
                Cancel("Cannot complete early without response data");
            }
            // Handle success
            else
            {
                HandleFinalNlpResponse(ResponseData, string.Empty);
            }
        }
References Meta.Voice.TranscriptionRequest< TUnityEvent, TOptions, TEvents, TResults >.Cancel(), Meta.Voice.NLPAudioRequest< TUnityEvent, TOptions, TEvents, TResults >.HandleFinalNlpResponse(), Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.IsActive, and Meta.Voice.NLPAudioRequest< TUnityEvent, TOptions, TEvents, TResults >.ResponseData.
HandleFinalNlpResponse()
virtual void Meta.Voice.NLPAudioRequest< TUnityEvent, TOptions, TEvents, TResults >.HandleFinalNlpResponse (WitResponseNode responseData, string error) protected virtual
Method to be called when an NLP request had completed.
Parameters
responseData Parsed json data returned from request
error Error returned from a request
Definition at line 93 of file NLPAudioRequest.cs.
        {
            // Ignore if not in correct state
            if (!IsActive || _isFinalized)
            {
                return;
            }
            _isFinalized = true;
            // Send partial data if not previously sent
            if (responseData != null && responseData != ResponseData)
            {
                HandlePartialNlpResponse(responseData);
            }
            // Error returned
            if (!string.IsNullOrEmpty(error))
            {
                HandleFailure(error);
            }
            // No response
            else if (responseData == null)
            {
                HandleFailure("No response returned");
            }
            // Success
            else
            {
                // Callback for final response
                OnFullResponse();
                // Handle success
                HandleSuccess(Results);
            }
        }
References Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.HandleFailure(), Meta.Voice.NLPAudioRequest< TUnityEvent, TOptions, TEvents, TResults >.HandlePartialNlpResponse(), Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.HandleSuccess(), Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.IsActive, Meta.Voice.NLPAudioRequest< TUnityEvent, TOptions, TEvents, TResults >.OnFullResponse(), Meta.Voice.NLPAudioRequest< TUnityEvent, TOptions, TEvents, TResults >.ResponseData, and Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.Results.
HandlePartialNlpResponse()
virtual void Meta.Voice.NLPAudioRequest< TUnityEvent, TOptions, TEvents, TResults >.HandlePartialNlpResponse (WitResponseNode responseData) protected virtual
Method to be called when an NLP request had completed.
Parameters
responseData Parsed json data returned from request
error Error returned from a request
Definition at line 59 of file NLPAudioRequest.cs.
        {
            // Ignore if not in correct state
            if (!IsActive)
            {
                return;
            }
            // Apply response data
            ApplyResultResponseData(responseData);
            // Partial response called
            OnPartialResponse();
        }
References Meta.Voice.NLPAudioRequest< TUnityEvent, TOptions, TEvents, TResults >.ApplyResultResponseData(), Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.IsActive, and Meta.Voice.NLPAudioRequest< TUnityEvent, TOptions, TEvents, TResults >.OnPartialResponse().
OnFullResponse()
virtual void Meta.Voice.NLPAudioRequest< TUnityEvent, TOptions, TEvents, TResults >.OnFullResponse () protected virtual
Called when response data has been updated for the final time.
Definition at line 132 of file NLPAudioRequest.cs.
        {
            Events?.OnFullResponse?.Invoke(ResponseData);
        }
References Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.Events, and Meta.Voice.NLPAudioRequest< TUnityEvent, TOptions, TEvents, TResults >.ResponseData.
OnInit()
override void Meta.Voice.NLPAudioRequest< TUnityEvent, TOptions, TEvents, TResults >.OnInit () protected virtual
Initializes the request, and ensures that the request commences in a non-finalized state.
Reimplemented from Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.
Definition at line 48 of file NLPAudioRequest.cs.
        {
            base.OnInit();
            _isFinalized = false;
        }
OnPartialResponse()
virtual void Meta.Voice.NLPAudioRequest< TUnityEvent, TOptions, TEvents, TResults >.OnPartialResponse () protected virtual
Called when response data has been updated.
Definition at line 83 of file NLPAudioRequest.cs.
        {
            Events?.OnPartialResponse?.Invoke(ResponseData);
        }
References Meta.Voice.VoiceRequest< TUnityEvent, TOptions, TEvents, TResults >.Events, and Meta.Voice.NLPAudioRequest< TUnityEvent, TOptions, TEvents, TResults >.ResponseData.
Member Data Documentation
_isFinalized
bool Meta.Voice.NLPAudioRequest< TUnityEvent, TOptions, TEvents, TResults >._isFinalized = false private
Definition at line 43 of file NLPAudioRequest.cs.
Property Documentation
ResponseData
WitResponseNode Meta.Voice.NLPAudioRequest< TUnityEvent, TOptions, TEvents, TResults >.ResponseData get
Getter for response data.
Definition at line 40 of file NLPAudioRequest.cs.
The documentation for this class was generated from the following file:
Assets/Oculus/Voice/Lib/Wit.ai/Lib/Wit/Runtime/Requests/NLP/NLPAudioRequest.cs