VR_Test: OVRScreenshotWizard Class Reference
OVRScreenshotWizard Class Reference
From the selected transform, takes a cubemap screenshot that can be submitted with the application as a screenshot (or additionally used for reflection shaders).
Public Types
enum TexFormat { JPEG , PNG }
enum SaveMode { SaveCubemapScreenshot , SaveUnityCubemap , SaveBoth }
Public Attributes
GameObject renderFrom = null
int size = 2048
SaveMode saveMode = SaveMode.SaveUnityCubemap
string cubeMapFolder = "Assets/Textures/Cubemaps"
TexFormat textureFormat = TexFormat.PNG
Private Member Functions
void OnWizardUpdate ()
Validates the user's input.
void OnWizardCreate ()
Renders the cubemap.
void GenerateTexture (Cubemap cubemap, string pathName)
Generates a NPOT 6x1 cubemap in the following format PX NX PY NY PZ NZ.
Static Private Member Functions
static bool CreateAssetPath (string newFolderPath)
Create the asset path if it is not available. Assuming the newFolderPath is stated with "Assets", which is a requirement.
static void TakeOVRScreenshot ()
Unity Editor menu option to take a screenshot.
Detailed Description
From the selected transform, takes a cubemap screenshot that can be submitted with the application as a screenshot (or additionally used for reflection shaders).
Definition at line 29 of file OVRScreenshotWizard.cs.
Member Enumeration Documentation
SaveMode
enum OVRScreenshotWizard.SaveMode
Definition at line 37 of file OVRScreenshotWizard.cs.
    {
        SaveCubemapScreenshot,
        SaveUnityCubemap,
        SaveBoth,
    }
TexFormat
enum OVRScreenshotWizard.TexFormat
Definition at line 31 of file OVRScreenshotWizard.cs.
    {
        JPEG, // 512kb at 1k x 1k resolution vs
        PNG, // 5.3mb
    }
Member Function Documentation
CreateAssetPath()
static bool OVRScreenshotWizard.CreateAssetPath (string newFolderPath) static private
Create the asset path if it is not available. Assuming the newFolderPath is stated with "Assets", which is a requirement.
Definition at line 64 of file OVRScreenshotWizard.cs.
    {
        const int maxFoldersCount = 32;
        string currentPath;
        string[] pathFolders;
        pathFolders = newFolderPath.Split(new char[] { '/' }, maxFoldersCount);
        if (!string.Equals("Assets", pathFolders[0], System.StringComparison.OrdinalIgnoreCase))
        {
            Debug.LogError("Folder path has to be started with \" Assets \" ");
            return false;
        }
        currentPath = "Assets";
        for (int i = 1; i < pathFolders.Length; i++)
        {
            if (!string.IsNullOrEmpty(pathFolders[i]))
            {
                string newPath = currentPath + "/" + pathFolders[i];
                if (!AssetDatabase.IsValidFolder(newPath))
                    AssetDatabase.CreateFolder(currentPath, pathFolders[i]);
                currentPath = newPath;
            }
        }
        Debug.Log("Created path: " + currentPath);
        return true;
    }
GenerateTexture()
void OVRScreenshotWizard.GenerateTexture (Cubemap cubemap, string pathName) private
Generates a NPOT 6x1 cubemap in the following format PX NX PY NY PZ NZ.
Definition at line 192 of file OVRScreenshotWizard.cs.
    {
        // Encode the texture and save it to disk
        pathName = pathName.Replace(".cubemap", (textureFormat == TexFormat.PNG) ? ".png" : ".jpg").ToLower();
        pathName = pathName.Replace(cubeMapFolder.ToLower(), "");
        string format = textureFormat.ToString();
        string fullPath = EditorUtility.SaveFilePanel(string.Format("Save Cubemap Screenshot as {0}", format), "",
            pathName, format.ToLower());
        if (!string.IsNullOrEmpty(fullPath))
        {
            Debug.Log("Saving: " + fullPath);
            OVRCubemapCapture.SaveCubemapCapture(cubemap, fullPath);
        }
    }
References OVRCubemapCapture.SaveCubemapCapture().
OnWizardCreate()
void OVRScreenshotWizard.OnWizardCreate () private
Renders the cubemap.
Definition at line 97 of file OVRScreenshotWizard.cs.
    {
        if (!AssetDatabase.IsValidFolder(cubeMapFolder))
        {
            if (!CreateAssetPath(cubeMapFolder))
            {
                Debug.LogError("Created path failed: " + cubeMapFolder);
                return;
            }
        }
        bool existingCamera = true;
        bool existingCameraStateSave = true;
        Camera camera = renderFrom.GetComponent<Camera>();
        if (camera == null)
        {
            camera = renderFrom.AddComponent<Camera>();
            camera.farClipPlane = 10000f;
            existingCamera = false;
        }
        else
        {
            existingCameraStateSave = camera.enabled;
            camera.enabled = true;
        }
        // find the last screenshot saved
        if (cubeMapFolder[cubeMapFolder.Length - 1] != '/')
        {
            cubeMapFolder += "/";
        }
        int idx = 0;
        string[] fileNames = Directory.GetFiles(cubeMapFolder);
        foreach (string fileName in fileNames)
        {
            if (!fileName.ToLower().EndsWith(".cubemap"))
            {
                continue;
            }
            string temp = fileName.Replace(cubeMapFolder + "vr_screenshot_", string.Empty);
            temp = temp.Replace(".cubemap", string.Empty);
            int tempIdx = 0;
            if (int.TryParse(temp, out tempIdx))
            {
                if (tempIdx > idx)
                {
                    idx = tempIdx;
                }
            }
        }
        string pathName = string.Format("{0}vr_screenshot_{1}.cubemap", cubeMapFolder, (++idx).ToString("d2"));
        Cubemap cubemap = new Cubemap(size, TextureFormat.RGB24, false);
        // render into cubemap
        if ((camera != null) && (cubemap != null))
        {
            // set up cubemap defaults
            OVRCubemapCapture.RenderIntoCubemap(camera, cubemap);
            if (existingCamera)
            {
                camera.enabled = existingCameraStateSave;
            }
            else
            {
                DestroyImmediate(camera);
            }
            // generate a regular texture as well?
            if ((saveMode == SaveMode.SaveCubemapScreenshot) || (saveMode == SaveMode.SaveBoth))
            {
                GenerateTexture(cubemap, pathName);
            }
            if ((saveMode == SaveMode.SaveUnityCubemap) || (saveMode == SaveMode.SaveBoth))
            {
                Debug.Log("Saving: " + pathName);
                // by default the unity cubemap isn't saved
                AssetDatabase.CreateAsset(cubemap, pathName);
                // reimport as necessary
                AssetDatabase.SaveAssets();
                // select it in the project tree so developers can find it
                EditorGUIUtility.PingObject(cubemap);
                Selection.activeObject = cubemap;
            }
            AssetDatabase.Refresh();
        }
    }
References CreateAssetPath(), and GenerateTexture().
OnWizardUpdate()
void OVRScreenshotWizard.OnWizardUpdate () private
Validates the user's input.
Definition at line 53 of file OVRScreenshotWizard.cs.
    {
        helpString =
            "Select a game object positioned in the place where\nyou want to render the cubemap screenshot from: ";
        isValid = (renderFrom != null);
    }
TakeOVRScreenshot()
static void OVRScreenshotWizard.TakeOVRScreenshot () static private
Unity Editor menu option to take a screenshot.
Definition at line 211 of file OVRScreenshotWizard.cs.
    {
        OVRScreenshotWizard wizard =
            ScriptableWizard.DisplayWizard<OVRScreenshotWizard>("OVR Screenshot Wizard", "Render Cubemap");
        if (wizard != null)
        {
            if (Selection.activeGameObject != null)
                wizard.renderFrom = Selection.activeGameObject;
            else
                wizard.renderFrom = Camera.main.gameObject;
            wizard.isValid = (wizard.renderFrom != null);
        }
    }
Member Data Documentation
cubeMapFolder
string OVRScreenshotWizard.cubeMapFolder = "Assets/Textures/Cubemaps"
Definition at line 47 of file OVRScreenshotWizard.cs.
renderFrom
GameObject OVRScreenshotWizard.renderFrom = null
Definition at line 44 of file OVRScreenshotWizard.cs.
saveMode
SaveMode OVRScreenshotWizard.saveMode = SaveMode.SaveUnityCubemap
Definition at line 46 of file OVRScreenshotWizard.cs.
size
int OVRScreenshotWizard.size = 2048
Definition at line 45 of file OVRScreenshotWizard.cs.
textureFormat
TexFormat OVRScreenshotWizard.textureFormat = TexFormat.PNG
Definition at line 48 of file OVRScreenshotWizard.cs.
The documentation for this class was generated from the following file:
Assets/Oculus/VR/Editor/OVRScreenshotWizard.cs