VR_Test: TeleportInputHandlerHMD Class Reference
TeleportInputHandlerHMD Class Reference
When this component is enabled, the player will be able to aim and trigger teleport behavior using HMD aiming.
Public Member Functions
override LocomotionTeleport.TeleportIntentions GetIntention ()
Based on the input mode, controller state, and current intention of the teleport controller, return the apparent intention of the user.
override void GetAimData (out Ray aimRay)
Public Member Functions inherited from TeleportInputHandler
LocomotionTeleport.TeleportIntentions GetIntention ()
One of the core functions of the TeleportInputHandler is to notify the LocomotionTeleport of the current intentions of the user with respect to aiming, teleporting, and abandoning a pending teleport. Derivations of this class will check buttons or whatever inputs they require to return values indicating what the user is trying to do.
void GetAimData (out Ray aimRay)
Returns the aim ray for pointing at targets, which is generally based on a touch controller or HMD pose.
Public Attributes
OVRInput.RawButton AimButton
The button used to begin aiming for a teleport.
OVRInput.RawButton TeleportButton
The button used to trigger the teleport after aiming. It can be the same button as the AimButton, however you cannot abort a teleport if it is.
bool FastTeleport
When true, the system will not use the PreTeleport intention which will allow a teleport to occur on a button downpress. When false, the button downpress will trigger the PreTeleport intention and the Teleport intention when the button is released.
Properties
Transform Pointer [get, private set]
Properties inherited from TeleportSupport
LocomotionTeleport LocomotionTeleport [get, private set]
Additional Inherited Members
Protected Member Functions inherited from TeleportInputHandler
override void AddEventHandlers ()
Derived classes that need to use event handlers need to override this method and call the base class to ensure all event handlers are added as intended.
override void RemoveEventHandlers ()
Derived classes that need to use event handlers need to override this method and call the base class to ensure all event handlers are removed as intended.
Protected Member Functions inherited from TeleportSupport
virtual void OnEnable ()
OnEnable is virtual so that derived classes can set up references to objects before AddEventHandlers is called, as is required by TeleportSupport derivations.
virtual void OnDisable ()
Detailed Description
When this component is enabled, the player will be able to aim and trigger teleport behavior using HMD aiming.
Definition at line 16 of file TeleportInputHandlerHMD.cs.
Member Function Documentation
GetAimData()
override void TeleportInputHandlerHMD.GetAimData (out Ray aimRay)
Definition at line 97 of file TeleportInputHandlerHMD.cs.
    {
        var t = LocomotionTeleport.LocomotionController.CameraRig.centerEyeAnchor;
        aimRay = new Ray(t.position, t.forward);
    }
GetIntention()
override LocomotionTeleport.TeleportIntentions TeleportInputHandlerHMD.GetIntention ()
Based on the input mode, controller state, and current intention of the teleport controller, return the apparent intention of the user.
Returns
Definition at line 47 of file TeleportInputHandlerHMD.cs.
    {
        if (!isActiveAndEnabled)
        {
            return global::LocomotionTeleport.TeleportIntentions.None;
        }
        if (LocomotionTeleport.CurrentIntention == global::LocomotionTeleport.TeleportIntentions.Aim)
        {
            // If the user has actually pressed the teleport button, enter the preteleport state.
            if (OVRInput.GetDown(TeleportButton))
            {
                return FastTeleport
                    ? global::LocomotionTeleport.TeleportIntentions.Teleport
                    : global::LocomotionTeleport.TeleportIntentions.PreTeleport;
            }
        }
        // If the user is already in the preteleport state, the intention will be to either remain in this state or switch to Teleport
        if (LocomotionTeleport.CurrentIntention == global::LocomotionTeleport.TeleportIntentions.PreTeleport)
        {
            // If they released the button, switch to Teleport.
            if (OVRInput.GetUp(TeleportButton))
            {
                // Button released, enter the teleport state.
                return global::LocomotionTeleport.TeleportIntentions.Teleport;
            }
            // Button still down, remain in PreTeleport so they can orient the destination if an orientation handler supports it.
            return global::LocomotionTeleport.TeleportIntentions.PreTeleport;
        }
        // Update the aim intention based on the button press state of the AimButton.
        if (OVRInput.Get(AimButton))
        {
            return global::LocomotionTeleport.TeleportIntentions.Aim;
        }
        // If the aim button is the same as the teleport button, then there is no way to abort the teleport.
        // Since the process of triggering the teleport is complete, returning the Teleport intention is necessary otherwise
        // the input handler would remain active.
        if (AimButton == TeleportButton)
        {
            return global::LocomotionTeleport.TeleportIntentions.Teleport;
        }
        return LocomotionTeleport.TeleportIntentions.None;
    }
References AimButton, LocomotionTeleport.CurrentIntention, FastTeleport, OVRInput.Get(), OVRInput.GetDown(), OVRInput.GetUp(), and TeleportButton.
Member Data Documentation
AimButton
OVRInput.RawButton TeleportInputHandlerHMD.AimButton
The button used to begin aiming for a teleport.
Definition at line 24 of file TeleportInputHandlerHMD.cs.
FastTeleport
bool TeleportInputHandlerHMD.FastTeleport
When true, the system will not use the PreTeleport intention which will allow a teleport to occur on a button downpress. When false, the button downpress will trigger the PreTeleport intention and the Teleport intention when the button is released.
Definition at line 41 of file TeleportInputHandlerHMD.cs.
TeleportButton
OVRInput.RawButton TeleportInputHandlerHMD.TeleportButton
The button used to trigger the teleport after aiming. It can be the same button as the AimButton, however you cannot abort a teleport if it is.
Definition at line 32 of file TeleportInputHandlerHMD.cs.
Property Documentation
Pointer
Transform TeleportInputHandlerHMD.Pointer get private set
Definition at line 18 of file TeleportInputHandlerHMD.cs.
{ get; private set; }
The documentation for this class was generated from the following file:
Assets/Oculus/SampleFramework/Core/Locomotion/Scripts/TeleportInputHandlerHMD.cs