VR_Test: LocomotionTeleport Class Reference
LocomotionTeleport Class Reference
The LocomotionTeleport class controls and centralizes functionality for the various types of teleports. The system is designed to work as a set of components that are each responsible for different aspects of the teleport process. This makes it possible for different kinds of teleport behaviors to be occur by simply enabling different combinations of components.
Classes
class AimData
The AimData contains data provided by the Aim Handler which represents the final set of points that were used for aiming the teleport. This is provided to the AimVisual for rendering an aim effect. Note that the set of points provided here can be different from the points used by the Aim Handler to determine the teleport destination. For instance, the aim handler might use a very long line segment for an aim laser but would provide a shorter line segment in the AimData representing the line from the player to the teleport destination.
Public Types
enum States {
Ready , Aim , CancelAim , PreTeleport ,
CancelTeleport , Teleporting , PostTeleport
}
The process of teleporting is represented by a simple state machine, and each of the possible states are represented by this enum.
enum TeleportIntentions { None , Aim , PreTeleport , Teleport }
TeleportIntentions track what the TeleportState should attempt to transition to.
enum AimCollisionTypes { Point , Sphere , Capsule }
The aiming system uses a common function for testing collision with the world, which can be configured to use different shapes for testing.
Public Member Functions
void EnableMovement (bool ready, bool aim, bool pre, bool post)
Helper function to enable linear movement during the various teleport states. Movement may not be desired at all states, for instance during aiming it may be preferred to prevent movement to allow a thumbstick to be used for choosing the landing orientation.
void EnableRotation (bool ready, bool aim, bool pre, bool post)
Helper function to enable rotation movement during the various teleport states. Rotation may not be desired at all states, for instance during aiming it may be preferred to prevent rotation (snap turn or linear) to prevent the camera from being rotated while preparing to teleport.
void OnUpdateTeleportDestination (bool isValidDestination, Vector3? position, Quaternion? rotation, Quaternion? landingRotation)
When the active aim and orientation handler finishes preparing the data for the teleport destination, this method will be called in order to raise the UpdateTeleportDestination event, which will in turn give any active teleport destination objects an opportunity to update their visual state accordingly.
bool AimCollisionTest (Vector3 start, Vector3 end, LayerMask aimCollisionLayerMask, out RaycastHit hitInfo)
AimCollisionTest is used by many of the aim handlers to standardize the testing of aiming beams. By choosing between the increasingly restrictive point, sphere and capsule tests, the aiming system can limit targeting to routes which are not physically blocked. For example, a sphere test is good for ensuring the player can't teleport through bars to get out of a jail cell.
void RecycleTeleportDestination (TeleportDestination oldDestination)
virtual void OnEnable ()
Start the state machine coroutines.
virtual void OnDisable ()
void OnUpdateAimData (AimData aimData)
The target handler will call this method when the aim data has been updated and is ready to be processed by anything that needs to be aware of any changes. This generally includes a visual indicator for the aiming and the active orientation handler.
void DoTeleport ()
Perform the actual teleport. Note that warp transitions do not call this function and instead moves the game object during the transition time time.
Vector3 GetCharacterPosition ()
Convenience method for finding the character's position.
Quaternion GetHeadRotationY ()
Return a quaternion for the Y axis of the HMD's orientation. Used by orientation handlers to track the current heading before processing user input to adjust it.
void DoWarp (Vector3 startPos, float positionPercent)
Warp just the position towards the destination.
Public Attributes
bool EnableMovementDuringReady = true
Allow linear movement prior to the teleport system being activated.
bool EnableMovementDuringAim = true
Allow linear movement while the teleport system is in the process of aiming for a teleport target.
bool EnableMovementDuringPreTeleport = true
Allow linear movement while the teleport system is in the process of configuring the landing orientation.
bool EnableMovementDuringPostTeleport = true
Allow linear movement after the teleport has occurred but before the system has returned to the ready state.
bool EnableRotationDuringReady = true
Allow rotation prior to the teleport system being activated.
bool EnableRotationDuringAim = true
Allow rotation while the teleport system is in the process of aiming for a teleport target.
bool EnableRotationDuringPreTeleport = true
Allow rotation while the teleport system is in the process of configuring the landing orientation.
bool EnableRotationDuringPostTeleport = true
Allow rotation after the teleport has occurred but before the system has returned to the ready state.
TeleportAimHandler AimHandler
Aiming is handled by one specific aim handler at a time. When the aim handler component is enabled, it will set this reference to the AimHandler so that other parts of the system which need access to the current aim handler can be sure to use the correct component.
TeleportDestination TeleportDestinationPrefab
This prefab will be instantiated as needed and updated to match the current aim target.
int TeleportDestinationLayer = 0
TeleportInputHandler InputHandler
The TeleportInputHandler is responsible for converting input events to TeleportIntentions.
TeleportIntentions CurrentIntention
The CurrentIntention is used by the state machine to know when it is time to switch to a new state.
bool IsPreTeleportRequested
The state machine will not exit the PreTeleport state while IsPreTeleportRequested is true. The sample doesn't currently use this, however this provides new components the ability to delay exiting the PreTeleport state until game logic is ready for it.
bool IsTransitioning
The state machine will not exit the Teleporting state while IsTransitioning is true. This is how the BlinkTransition and WarpTransition force the system to remain in the Teleporting state until the transition is complete.
bool IsPostTeleportRequested
The state machine will not exit the PostTeleport state while IsPostTeleportRequested is true. The sample doesn't currently use this, however this provides new components the ability to delay exiting the PostTeleport state until game logic is ready for it.
AimCollisionTypes AimCollisionType
When aiming at possible destinations, the aim collision type determines which shape to use for collision tests.
bool UseCharacterCollisionData
Use the character collision radius/height/skinwidth for sphere/capsule collision tests.
float AimCollisionRadius
Radius of the sphere or capsule used for collision testing when aiming to possible teleport destinations. Ignored if UseCharacterCollisionData is true.
float AimCollisionHeight
Height of the capsule used for collision testing when aiming to possible teleport destinations. Ignored if UseCharacterCollisionData is true.
Protected Member Functions
void LogState (string msg)
Internal logging function that is conditionally enabled via DEBUG_TELEPORT_STATES.
void CreateNewTeleportDestination ()
This is called whenever a new teleport destination is required. This might occur when rapidly switching between targets, or when teleporting multiple times in quick succession when the teleport destination requires additional time to complete any animations that are triggered by these actions.
IEnumerator ReadyStateCoroutine ()
This coroutine will be running while the component is in the Ready state.
IEnumerator AimStateCoroutine ()
This coroutine will be running while the aim state is active. The teleport destination will become active, and depending on the target and current intention of the user it might enter the CancelAim state or PreTeleport state when it is done.
IEnumerator CancelAimStateCoroutine ()
This coroutine will be executed when the aim state is cancelled.
IEnumerator PreTeleportStateCoroutine ()
This coroutine will be active while the system is in the PreTeleport state. At this point, the user has indicated they want to teleport however there is a possibility that the target they have chosen might be or become invalid so the next state will be either Teleporting or CancelTeleporting.
IEnumerator CancelTeleportStateCoroutine ()
This coroutine will be executed when the pre-teleport state is unabled to transition to the teleporting state.
IEnumerator TeleportingStateCoroutine ()
This coroutine will yield until IsTransitioning back to false, which will be immediately unless there is a transition handler that needs to take some time to move the player to the new location. This allows transition handlers to take as much (or little) time as they need to complete their task of moving the player to the teleport destination.
IEnumerator PostTeleportStateCoroutine ()
The PostTeleport coroutine is typically just a single frame state that deactivates the destination indicator and raises the EnterStatePostTeleport event which could be used for any number of gameplay purposes such as triggering a character animation, sound effect or possibly delaying the exit of the PostTeleport state for some gameplay reason such as a cooldown on teleports.
Properties
States CurrentState [get, private set]
The current state of the teleport state machine.
Quaternion DestinationRotation [get]
Returns the orientation of the current teleport destination's orientation indicator.
LocomotionController LocomotionController [get, private set]
The LocomotionController that is used by object to discover shared references.
Events
Action< bool, Vector3?, Quaternion?, Quaternion?> UpdateTeleportDestination
This event is raised when the teleport destination is in the process of being updated. It is used by the active TeleportDestination to update it's visual state, position and orientation indicator to match the results of the teleport aim and targeting system.
Action EnterStateReady
This event is raised when entering the Ready state. The initial use for this is for the input handler to start processing input in order to eventually set the TeleportIntention to Aim when the user requests it.
Action EnterStateAim
This event is raised when the user begins aiming for a target location for a teleport.
Action< AimData > UpdateAimData
Aim and Target handlers are responsible for populating the AimData with the relevant aim data, which is used for a number of purposes within the teleport system.
Action ExitStateAim
This event is raised when the aim state is exited. This is typically used by aim visualizers to deactivate any visual effects related to aiming.
Action EnterStateCancelAim
This event is raised when aiming for a teleport destination is aborted. It can be useful for cleaning up effects that may have been triggered when entering the Aim state.
Action EnterStatePreTeleport
This event is raised when the system enteres the PreTeleport state.
Action EnterStateCancelTeleport
This event will occur if the user cancels the teleport after the destination has been selected. Typically not much different than cancelling an aim state, however there may be some effect triggered by the target selection which needs to be cleaned up, or perhaps a different visual effect needs to be triggered when a teleport is aborted.
Action EnterStateTeleporting
This event will occur when the teleport actually occurs. There should be one Transition Handler enabled and attached to this event. There may be other handlers attached to this event to trigger sound effects or gameplay logic to respond to the teleport event.
Action EnterStatePostTeleport
This event will occur after the teleport has completed.
Action< Transform, Vector3, Quaternion > Teleported
This event is raised when the character actually teleports, which is typically triggered by the transition handler.
Private Member Functions
void DeactivateDestination ()
Notify the teleport destination that it needs to deactivate. If the destination has event handlers hooked up, the destination game object may not be immediately deactivated in order to allow it to trigger animated effects.
void EnableMotion (bool enableLinear, bool enableRotation)
Each state has booleans that determine if linear motion or rotational motion is enabled for that state. This method is called when entering each state with the appropriate values.
void Awake ()
When the component first wakes up, cache the LocomotionController and the initial TeleportDestination object.
Private Attributes
TeleportDestination _teleportDestination
Created at runtime, this gameobject is used to track where the player will teleport. The actual position depends on the type of Aim Handler and Target Handler that is active. Aim Handlers:
Detailed Description
The LocomotionTeleport class controls and centralizes functionality for the various types of teleports. The system is designed to work as a set of components that are each responsible for different aspects of the teleport process. This makes it possible for different kinds of teleport behaviors to be occur by simply enabling different combinations of components.
Definition at line 28 of file LocomotionTeleport.cs.
Member Enumeration Documentation
AimCollisionTypes
enum LocomotionTeleport.AimCollisionTypes
The aiming system uses a common function for testing collision with the world, which can be configured to use different shapes for testing.
Definition at line 264 of file LocomotionTeleport.cs.
    {
        Point, // ray casting
        Sphere, // swept sphere test
        Capsule // swept capsule test, optionally sized to match the character controller dimensions.
    }
States
enum LocomotionTeleport.States
The process of teleporting is represented by a simple state machine, and each of the possible states are represented by this enum.
Definition at line 34 of file LocomotionTeleport.cs.
    {
        Ready,
        Aim,
        CancelAim,
        PreTeleport,
        CancelTeleport,
        Teleporting,
        PostTeleport
    }
TeleportIntentions
enum LocomotionTeleport.TeleportIntentions
TeleportIntentions track what the TeleportState should attempt to transition to.
Definition at line 195 of file LocomotionTeleport.cs.
    {
        None, // No teleport is requested.
        Aim, // The user wants to aim for a teleport.
        PreTeleport, // The user has selected a location to teleport, and the input handler will now control how long it stays in PreTeleport.
        Teleport // The user has chosen to teleport. If the destination is valid, the state will transition to Teleporting, otherwise it will switch to CancelTeleport.
    }
Member Function Documentation
AimCollisionTest()
bool LocomotionTeleport.AimCollisionTest (Vector3 start, Vector3 end, LayerMask aimCollisionLayerMask, out RaycastHit hitInfo)
AimCollisionTest is used by many of the aim handlers to standardize the testing of aiming beams. By choosing between the increasingly restrictive point, sphere and capsule tests, the aiming system can limit targeting to routes which are not physically blocked. For example, a sphere test is good for ensuring the player can't teleport through bars to get out of a jail cell.
Parameters
start
end
aimCollisionLayerMask
hitInfo
Returns
Definition at line 311 of file LocomotionTeleport.cs.
    {
        var delta = end - start;
        var distance = delta.magnitude;
        var direction = delta / distance;
        switch (AimCollisionType)
        {
            case AimCollisionTypes.Capsule:
            {
                float r, h;
                if (UseCharacterCollisionData)
                {
                    var c = LocomotionController.CharacterController;
                    h = c.height;
                    r = c.radius;
                }
                else
                {
                    h = AimCollisionHeight;
                    r = AimCollisionRadius;
                }
                return Physics.CapsuleCast(start + new Vector3(0, r, 0),
                    start + new Vector3(0, h + r, 0), r, direction,
                    out hitInfo, distance, aimCollisionLayerMask, QueryTriggerInteraction.Ignore);
            }
            case AimCollisionTypes.Point:
                return Physics.Raycast(start, direction, out hitInfo, distance, aimCollisionLayerMask,
                    QueryTriggerInteraction.Ignore);
            case AimCollisionTypes.Sphere:
            {
                float r;
                if (UseCharacterCollisionData)
                {
                    var c = LocomotionController.CharacterController;
                    //r = c.radius - c.skinWidth;
                    r = c.radius;
                }
                else
                {
                    r = AimCollisionRadius;
                }
                return Physics.SphereCast(start, r, direction, out hitInfo, distance, aimCollisionLayerMask,
                    QueryTriggerInteraction.Ignore);
            }
        }
        // App should never get here.
        throw new Exception();
    }
References AimCollisionHeight, AimCollisionRadius, AimCollisionType, and UseCharacterCollisionData.
AimStateCoroutine()
IEnumerator LocomotionTeleport.AimStateCoroutine () protected
This coroutine will be running while the aim state is active. The teleport destination will become active, and depending on the target and current intention of the user it might enter the CancelAim state or PreTeleport state when it is done.
Returns
Definition at line 559 of file LocomotionTeleport.cs.
    {
        LogState("AimState: Start");
        CurrentState = States.Aim;
        EnableMotion(EnableMovementDuringAim, EnableRotationDuringAim);
        if (EnterStateAim != null)
        {
            EnterStateAim();
        }
        _teleportDestination.gameObject.SetActive(true);
        // Wait until the user is done aiming. The input system will turn this off when the button that triggered aiming is released.
        while (CurrentIntention == TeleportIntentions.Aim)
        {
            yield return null;
        }
        LogState("AimState: End. Intention: " + CurrentIntention);
        if (ExitStateAim != null)
        {
            ExitStateAim();
        }
        // Wait until the next frame to proceed to the next state's coroutine.
        yield return null;
        // If target is valid, enter pre-teleport otherwise cancel the teleport.
        LogState("AimState: Switch state. Intention: " + CurrentIntention);
        if ((CurrentIntention == TeleportIntentions.PreTeleport || CurrentIntention == TeleportIntentions.Teleport) &&
            _teleportDestination.IsValidDestination)
        {
            StartCoroutine(PreTeleportStateCoroutine());
        }
        else
        {
            StartCoroutine(CancelAimStateCoroutine());
        }
    }
References _teleportDestination, CancelAimStateCoroutine(), CurrentIntention, CurrentState, EnableMotion(), EnableMovementDuringAim, EnableRotationDuringAim, EnterStateAim, ExitStateAim, TeleportDestination.IsValidDestination, LogState(), and PreTeleportStateCoroutine().
Awake()
void LocomotionTeleport.Awake () private
When the component first wakes up, cache the LocomotionController and the initial TeleportDestination object.
Definition at line 430 of file LocomotionTeleport.cs.
    {
        LocomotionController = GetComponent<LocomotionController>();
        CreateNewTeleportDestination();
    }
References CreateNewTeleportDestination().
CancelAimStateCoroutine()
IEnumerator LocomotionTeleport.CancelAimStateCoroutine () protected
This coroutine will be executed when the aim state is cancelled.
Returns
Definition at line 609 of file LocomotionTeleport.cs.
    {
        LogState("CancelAimState: Start");
        CurrentState = States.CancelAim;
        if (EnterStateCancelAim != null)
        {
            EnterStateCancelAim();
        }
        LogState("CancelAimState: End");
        DeactivateDestination();
        // Wait until the next frame to proceed to the next state's coroutine.
        yield return null;
        StartCoroutine(ReadyStateCoroutine());
    }
References CurrentState, DeactivateDestination(), EnterStateCancelAim, LogState(), and ReadyStateCoroutine().
CancelTeleportStateCoroutine()
IEnumerator LocomotionTeleport.CancelTeleportStateCoroutine () protected
This coroutine will be executed when the pre-teleport state is unabled to transition to the teleporting state.
Returns
Definition at line 683 of file LocomotionTeleport.cs.
    {
        LogState("CancelTeleportState: Start");
        CurrentState = States.CancelTeleport;
        if (EnterStateCancelTeleport != null)
        {
            EnterStateCancelTeleport();
        }
        LogState("CancelTeleportState: End");
        // Teleport was cancelled, notify the teleport destination.
        DeactivateDestination();
        // Wait until the next frame to proceed to the next state's coroutine.
        yield return null;
        StartCoroutine(ReadyStateCoroutine());
    }
References CurrentState, DeactivateDestination(), EnterStateCancelTeleport, LogState(), and ReadyStateCoroutine().
CreateNewTeleportDestination()
void LocomotionTeleport.CreateNewTeleportDestination () protected
This is called whenever a new teleport destination is required. This might occur when rapidly switching between targets, or when teleporting multiple times in quick succession when the teleport destination requires additional time to complete any animations that are triggered by these actions.
Definition at line 382 of file LocomotionTeleport.cs.
    {
        // ensure the prefab isn't active in order to delay event handler setup until after it has been
        // configured with a reference to this object.
        TeleportDestinationPrefab.gameObject.SetActive(false);
        TeleportDestination td = GameObject.Instantiate(TeleportDestinationPrefab);
        td.LocomotionTeleport = this;
        td.gameObject.layer = TeleportDestinationLayer;
        _teleportDestination = td;
        _teleportDestination.LocomotionTeleport = this;
    }
References _teleportDestination, and TeleportDestinationPrefab.
DeactivateDestination()
void LocomotionTeleport.DeactivateDestination () private
Notify the teleport destination that it needs to deactivate. If the destination has event handlers hooked up, the destination game object may not be immediately deactivated in order to allow it to trigger animated effects.
Definition at line 399 of file LocomotionTeleport.cs.
    {
        _teleportDestination.OnDeactivated();
    }
References _teleportDestination.
DoTeleport()
void LocomotionTeleport.DoTeleport ()
Perform the actual teleport. Note that warp transitions do not call this function and instead moves the game object during the transition time time.
Definition at line 798 of file LocomotionTeleport.cs.
    {
        var character = LocomotionController.CharacterController;
        var characterTransform = character.transform;
        var destTransform = _teleportDestination.OrientationIndicator;
        Vector3 destPosition = destTransform.position;
        destPosition.y += character.height * 0.5f;
        Quaternion destRotation = _teleportDestination.LandingRotation; // destTransform.rotation;
#if false
        Quaternion destRotation = destTransform.rotation;
        //Debug.Log("Rots: " + destRotation + " " + destTransform.rotation * Quaternion.Euler(0, -LocomotionController.CameraRig.trackingSpace.localEulerAngles.y, 0));
        destRotation =
 destRotation * Quaternion.Euler(0, -LocomotionController.CameraRig.trackingSpace.localEulerAngles.y, 0);
#endif
        if (Teleported != null)
        {
            Teleported(characterTransform, destPosition, destRotation);
        }
        characterTransform.position = destPosition;
        characterTransform.rotation = destRotation;
    }
References _teleportDestination, Teleported, and OVRCameraRig.trackingSpace.
DoWarp()
void LocomotionTeleport.DoWarp (Vector3 startPos, float positionPercent)
Warp just the position towards the destination.
Parameters
startPos
positionPercent
Definition at line 873 of file LocomotionTeleport.cs.
    {
        var destTransform = _teleportDestination.OrientationIndicator;
        Vector3 destPosition = destTransform.position;
        destPosition.y += LocomotionController.CharacterController.height / 2.0f;
        var character = LocomotionController.CharacterController;
        var characterTransform = character.transform;
        var lerpPosition = Vector3.Lerp(startPos, destPosition, positionPercent);
        characterTransform.position = lerpPosition;
        //LocomotionController.PlayerController.Teleported = true;
    }
References _teleportDestination.
EnableMotion()
void LocomotionTeleport.EnableMotion (bool enableLinear, bool enableRotation) private
Each state has booleans that determine if linear motion or rotational motion is enabled for that state. This method is called when entering each state with the appropriate values.
Parameters
enableLinear
enableRotation
Definition at line 420 of file LocomotionTeleport.cs.
    {
        LocomotionController.PlayerController.EnableLinearMovement = enableLinear;
        LocomotionController.PlayerController.EnableRotation = enableRotation;
    }
EnableMovement()
void LocomotionTeleport.EnableMovement (bool ready, bool aim, bool pre, bool post)
Helper function to enable linear movement during the various teleport states. Movement may not be desired at all states, for instance during aiming it may be preferred to prevent movement to allow a thumbstick to be used for choosing the landing orientation.
Parameters
ready
aim
pre
post
Definition at line 84 of file LocomotionTeleport.cs.
    {
        EnableMovementDuringReady = ready;
        EnableMovementDuringAim = aim;
        EnableMovementDuringPreTeleport = pre;
        EnableMovementDuringPostTeleport = post;
    }
References EnableMovementDuringAim, EnableMovementDuringPostTeleport, EnableMovementDuringPreTeleport, and EnableMovementDuringReady.
EnableRotation()
void LocomotionTeleport.EnableRotation (bool ready, bool aim, bool pre, bool post)
Helper function to enable rotation movement during the various teleport states. Rotation may not be desired at all states, for instance during aiming it may be preferred to prevent rotation (snap turn or linear) to prevent the camera from being rotated while preparing to teleport.
Parameters
ready
aim
pre
post
Definition at line 129 of file LocomotionTeleport.cs.
    {
        EnableRotationDuringReady = ready;
        EnableRotationDuringAim = aim;
        EnableRotationDuringPreTeleport = pre;
        EnableRotationDuringPostTeleport = post;
    }
References EnableRotationDuringAim, EnableRotationDuringPostTeleport, EnableRotationDuringPreTeleport, and EnableRotationDuringReady.
GetCharacterPosition()
Vector3 LocomotionTeleport.GetCharacterPosition ()
Convenience method for finding the character's position.
Returns
Definition at line 828 of file LocomotionTeleport.cs.
    {
        return LocomotionController.CharacterController.transform.position;
    }
GetHeadRotationY()
Quaternion LocomotionTeleport.GetHeadRotationY ()
Return a quaternion for the Y axis of the HMD's orientation. Used by orientation handlers to track the current heading before processing user input to adjust it.
Returns
Definition at line 838 of file LocomotionTeleport.cs.
    {
        Quaternion headRotation = Quaternion.identity;
#if UNITY_2019_1_OR_NEWER
        UnityEngine.XR.InputDevice device = UnityEngine.XR.InputDevices.GetDeviceAtXRNode(UnityEngine.XR.XRNode.Head);
        if (device.isValid)
        {
            device.TryGetFeatureValue(UnityEngine.XR.CommonUsages.deviceRotation, out headRotation);
        }
#elif UNITY_2017_2_OR_NEWER
        List<UnityEngine.XR.XRNodeState> nodeStates = new List<UnityEngine.XR.XRNodeState>();
        UnityEngine.XR.InputTracking.GetNodeStates(nodeStates);
        foreach (UnityEngine.XR.XRNodeState n in nodeStates)
        {
            if (n.nodeType == UnityEngine.XR.XRNode.Head)
            {
                n.TryGetRotation(out headRotation);
                break;
            }
        }
#else
        headRotation = InputTracking.GetLocalRotation(VRNode.Head);
#endif
        Vector3 euler = headRotation.eulerAngles;
        euler.x = 0;
        euler.z = 0;
        headRotation = Quaternion.Euler(euler);
        return headRotation;
    }
LogState()
void LocomotionTeleport.LogState (string msg) protected
Internal logging function that is conditionally enabled via DEBUG_TELEPORT_STATES.
Parameters
msg
Definition at line 372 of file LocomotionTeleport.cs.
    {
        Debug.Log(Time.frameCount + ": " + msg);
    }
OnDisable()
virtual void LocomotionTeleport.OnDisable () virtual
Definition at line 445 of file LocomotionTeleport.cs.
    {
        StopAllCoroutines();
    }
OnEnable()
virtual void LocomotionTeleport.OnEnable () virtual
Start the state machine coroutines.
Definition at line 439 of file LocomotionTeleport.cs.
    {
        CurrentState = States.Ready;
        StartCoroutine(ReadyStateCoroutine());
    }
References CurrentState, and ReadyStateCoroutine().
OnUpdateAimData()
void LocomotionTeleport.OnUpdateAimData (AimData aimData)
The target handler will call this method when the aim data has been updated and is ready to be processed by anything that needs to be aware of any changes. This generally includes a visual indicator for the aiming and the active orientation handler.
Parameters
aimData
Definition at line 539 of file LocomotionTeleport.cs.
    {
        if (UpdateAimData != null)
        {
            UpdateAimData(aimData);
        }
    }
References UpdateAimData.
OnUpdateTeleportDestination()
void LocomotionTeleport.OnUpdateTeleportDestination (bool isValidDestination, Vector3? position, Quaternion? rotation, Quaternion? landingRotation)
When the active aim and orientation handler finishes preparing the data for the teleport destination, this method will be called in order to raise the UpdateTeleportDestination event, which will in turn give any active teleport destination objects an opportunity to update their visual state accordingly.
Parameters
isValidDestination
position
rotation
Definition at line 177 of file LocomotionTeleport.cs.
    {
        if (UpdateTeleportDestination != null)
        {
            UpdateTeleportDestination(isValidDestination, position, rotation, landingRotation);
        }
    }
References UpdateTeleportDestination.
PostTeleportStateCoroutine()
IEnumerator LocomotionTeleport.PostTeleportStateCoroutine () protected
The PostTeleport coroutine is typically just a single frame state that deactivates the destination indicator and raises the EnterStatePostTeleport event which could be used for any number of gameplay purposes such as triggering a character animation, sound effect or possibly delaying the exit of the PostTeleport state for some gameplay reason such as a cooldown on teleports.
Returns
Definition at line 758 of file LocomotionTeleport.cs.
    {
        LogState("PostTeleportState: Start");
        CurrentState = States.PostTeleport;
        EnableMotion(EnableMovementDuringPostTeleport, EnableRotationDuringPostTeleport);
        if (EnterStatePostTeleport != null)
        {
            EnterStatePostTeleport();
        }
        while (IsPostTeleportRequested)
        {
            yield return null;
        }
        LogState("PostTeleportState: End");
        DeactivateDestination();
        // Wait until the next frame to proceed to the next state's coroutine.
        yield return null;
        StartCoroutine(ReadyStateCoroutine());
    }
References CurrentState, DeactivateDestination(), EnableMotion(), EnableMovementDuringPostTeleport, EnableRotationDuringPostTeleport, EnterStatePostTeleport, IsPostTeleportRequested, LogState(), and ReadyStateCoroutine().
PreTeleportStateCoroutine()
IEnumerator LocomotionTeleport.PreTeleportStateCoroutine () protected
This coroutine will be active while the system is in the PreTeleport state. At this point, the user has indicated they want to teleport however there is a possibility that the target they have chosen might be or become invalid so the next state will be either Teleporting or CancelTeleporting.
Returns
Definition at line 640 of file LocomotionTeleport.cs.
    {
        LogState("PreTeleportState: Start");
        CurrentState = States.PreTeleport;
        EnableMotion(EnableMovementDuringPreTeleport, EnableRotationDuringPreTeleport);
        if (EnterStatePreTeleport != null)
        {
            EnterStatePreTeleport();
        }
        while (CurrentIntention == TeleportIntentions.PreTeleport || IsPreTeleportRequested)
        {
            yield return null;
        }
        LogState("PreTeleportState: End");
        // Most of the state coroutines will wait until the next frame to proceed to the next state's coroutine,
        // however the PreTeleportState may need to be processed quickly for situations where the teleport needs
        // to occur on the downpress of a button (AvatarTouch capactive touch for aim and teleport, for instance).
        if (_teleportDestination.IsValidDestination)
        {
            StartCoroutine(TeleportingStateCoroutine());
        }
        else
        {
            StartCoroutine(CancelTeleportStateCoroutine());
        }
    }
References _teleportDestination, CancelTeleportStateCoroutine(), CurrentIntention, CurrentState, EnableMotion(), EnableMovementDuringPreTeleport, EnableRotationDuringPreTeleport, EnterStatePreTeleport, IsPreTeleportRequested, TeleportDestination.IsValidDestination, LogState(), and TeleportingStateCoroutine().
ReadyStateCoroutine()
IEnumerator LocomotionTeleport.ReadyStateCoroutine () protected
This coroutine will be running while the component is in the Ready state.
Returns
Definition at line 460 of file LocomotionTeleport.cs.
    {
        LogState("ReadyState: Start");
        // yield once so that all the components will have time to process their OnEnable message before this
        // does work that relies on the events being hooked up.
        yield return null;
        LogState("ReadyState: Ready");
        CurrentState = States.Ready;
        EnableMotion(EnableMovementDuringReady, EnableRotationDuringReady);
        if (EnterStateReady != null)
        {
            EnterStateReady();
        }
        // Wait until a teleport is requested.
        while (CurrentIntention != TeleportIntentions.Aim)
        {
            yield return null;
        }
        LogState("ReadyState: End");
        // Wait until the next frame to proceed to the next state's coroutine.
        yield return null;
        StartCoroutine(AimStateCoroutine());
    }
References AimStateCoroutine(), CurrentIntention, CurrentState, EnableMotion(), EnableMovementDuringReady, EnableRotationDuringReady, EnterStateReady, and LogState().
RecycleTeleportDestination()
void LocomotionTeleport.RecycleTeleportDestination (TeleportDestination oldDestination)
Definition at line 404 of file LocomotionTeleport.cs.
    {
        if (oldDestination == _teleportDestination)
        {
            CreateNewTeleportDestination();
        }
        GameObject.Destroy(oldDestination.gameObject);
    }
TeleportingStateCoroutine()
IEnumerator LocomotionTeleport.TeleportingStateCoroutine () protected
This coroutine will yield until IsTransitioning back to false, which will be immediately unless there is a transition handler that needs to take some time to move the player to the new location. This allows transition handlers to take as much (or little) time as they need to complete their task of moving the player to the teleport destination.
Definition at line 722 of file LocomotionTeleport.cs.
    {
        LogState("TeleportingState: Start");
        CurrentState = States.Teleporting;
        EnableMotion(false, false); // movement is always disabled during teleport.
        if (EnterStateTeleporting != null)
        {
            EnterStateTeleporting();
        }
        // If a handler sets this, it needs to clear it when the transition completes.
        while (IsTransitioning)
        {
            yield return null;
        }
        LogState("TeleportingState: End");
        // Wait until the next frame to proceed to the next state's coroutine.
        yield return null;
        StartCoroutine(PostTeleportStateCoroutine());
    }
References CurrentState, EnableMotion(), EnterStateTeleporting, IsTransitioning, LogState(), and PostTeleportStateCoroutine().
Member Data Documentation
_teleportDestination
TeleportDestination LocomotionTeleport._teleportDestination private
Created at runtime, this gameobject is used to track where the player will teleport. The actual position depends on the type of Aim Handler and Target Handler that is active. Aim Handlers:
Laser: player capsule swept along aim ray until it hits terrain or valid target.
Parabolic: player capsule swept along a series of line segments approximating a parabolic curve until it hits terrain or valid target. Target Handlers:
NavMesh = Destination only valid if it lies within the nav mesh.
Node = Destination valid if within radius of a teleport node. Target is invalidated when aim leaves the node radius.
Physical = Any terrain is valid.
Definition at line 243 of file LocomotionTeleport.cs.
AimCollisionHeight
float LocomotionTeleport.AimCollisionHeight
Height of the capsule used for collision testing when aiming to possible teleport destinations. Ignored if UseCharacterCollisionData is true.
Definition at line 299 of file LocomotionTeleport.cs.
AimCollisionRadius
float LocomotionTeleport.AimCollisionRadius
Radius of the sphere or capsule used for collision testing when aiming to possible teleport destinations. Ignored if UseCharacterCollisionData is true.
Definition at line 291 of file LocomotionTeleport.cs.
AimCollisionType
AimCollisionTypes LocomotionTeleport.AimCollisionType
When aiming at possible destinations, the aim collision type determines which shape to use for collision tests.
Definition at line 277 of file LocomotionTeleport.cs.
AimHandler
TeleportAimHandler LocomotionTeleport.AimHandler
Aiming is handled by one specific aim handler at a time. When the aim handler component is enabled, it will set this reference to the AimHandler so that other parts of the system which need access to the current aim handler can be sure to use the correct component.
Definition at line 150 of file LocomotionTeleport.cs.
CurrentIntention
TeleportIntentions LocomotionTeleport.CurrentIntention
The CurrentIntention is used by the state machine to know when it is time to switch to a new state.
Definition at line 207 of file LocomotionTeleport.cs.
EnableMovementDuringAim
bool LocomotionTeleport.EnableMovementDuringAim = true
Allow linear movement while the teleport system is in the process of aiming for a teleport target.
Definition at line 57 of file LocomotionTeleport.cs.
EnableMovementDuringPostTeleport
bool LocomotionTeleport.EnableMovementDuringPostTeleport = true
Allow linear movement after the teleport has occurred but before the system has returned to the ready state.
Definition at line 73 of file LocomotionTeleport.cs.
EnableMovementDuringPreTeleport
bool LocomotionTeleport.EnableMovementDuringPreTeleport = true
Allow linear movement while the teleport system is in the process of configuring the landing orientation.
Definition at line 65 of file LocomotionTeleport.cs.
EnableMovementDuringReady
bool LocomotionTeleport.EnableMovementDuringReady = true
Allow linear movement prior to the teleport system being activated.
Definition at line 51 of file LocomotionTeleport.cs.
EnableRotationDuringAim
bool LocomotionTeleport.EnableRotationDuringAim = true
Allow rotation while the teleport system is in the process of aiming for a teleport target.
Definition at line 106 of file LocomotionTeleport.cs.
EnableRotationDuringPostTeleport
bool LocomotionTeleport.EnableRotationDuringPostTeleport = true
Allow rotation after the teleport has occurred but before the system has returned to the ready state.
Definition at line 118 of file LocomotionTeleport.cs.
EnableRotationDuringPreTeleport
bool LocomotionTeleport.EnableRotationDuringPreTeleport = true
Allow rotation while the teleport system is in the process of configuring the landing orientation.
Definition at line 112 of file LocomotionTeleport.cs.
EnableRotationDuringReady
bool LocomotionTeleport.EnableRotationDuringReady = true
Allow rotation prior to the teleport system being activated.
Definition at line 100 of file LocomotionTeleport.cs.
InputHandler
TeleportInputHandler LocomotionTeleport.InputHandler
The TeleportInputHandler is responsible for converting input events to TeleportIntentions.
Definition at line 190 of file LocomotionTeleport.cs.
IsPostTeleportRequested
bool LocomotionTeleport.IsPostTeleportRequested
The state machine will not exit the PostTeleport state while IsPostTeleportRequested is true. The sample doesn't currently use this, however this provides new components the ability to delay exiting the PostTeleport state until game logic is ready for it.
Definition at line 230 of file LocomotionTeleport.cs.
IsPreTeleportRequested
bool LocomotionTeleport.IsPreTeleportRequested
The state machine will not exit the PreTeleport state while IsPreTeleportRequested is true. The sample doesn't currently use this, however this provides new components the ability to delay exiting the PreTeleport state until game logic is ready for it.
Definition at line 215 of file LocomotionTeleport.cs.
IsTransitioning
bool LocomotionTeleport.IsTransitioning
The state machine will not exit the Teleporting state while IsTransitioning is true. This is how the BlinkTransition and WarpTransition force the system to remain in the Teleporting state until the transition is complete.
Definition at line 222 of file LocomotionTeleport.cs.
TeleportDestinationLayer
int LocomotionTeleport.TeleportDestinationLayer = 0
Definition at line 159 of file LocomotionTeleport.cs.
TeleportDestinationPrefab
TeleportDestination LocomotionTeleport.TeleportDestinationPrefab
This prefab will be instantiated as needed and updated to match the current aim target.
Definition at line 156 of file LocomotionTeleport.cs.
UseCharacterCollisionData
bool LocomotionTeleport.UseCharacterCollisionData
Use the character collision radius/height/skinwidth for sphere/capsule collision tests.
Definition at line 283 of file LocomotionTeleport.cs.
Property Documentation
CurrentState
States LocomotionTeleport.CurrentState get private set
The current state of the teleport state machine.
Definition at line 142 of file LocomotionTeleport.cs.
{ get; private set; }
DestinationRotation
Quaternion LocomotionTeleport.DestinationRotation get
Returns the orientation of the current teleport destination's orientation indicator.
Definition at line 248 of file LocomotionTeleport.cs.
    {
        get { return _teleportDestination.OrientationIndicator.rotation; }
    }
LocomotionController
LocomotionController LocomotionTeleport.LocomotionController get private set
The LocomotionController that is used by object to discover shared references.
Definition at line 258 of file LocomotionTeleport.cs.
{ get; private set; }
Event Documentation
EnterStateAim
Action LocomotionTeleport.EnterStateAim
This event is raised when the user begins aiming for a target location for a teleport.
Definition at line 525 of file LocomotionTeleport.cs.
EnterStateCancelAim
Action LocomotionTeleport.EnterStateCancelAim
This event is raised when aiming for a teleport destination is aborted. It can be useful for cleaning up effects that may have been triggered when entering the Aim state.
Definition at line 603 of file LocomotionTeleport.cs.
EnterStateCancelTeleport
Action LocomotionTeleport.EnterStateCancelTeleport
This event will occur if the user cancels the teleport after the destination has been selected. Typically not much different than cancelling an aim state, however there may be some effect triggered by the target selection which needs to be cleaned up, or perhaps a different visual effect needs to be triggered when a teleport is aborted.
Definition at line 677 of file LocomotionTeleport.cs.
EnterStatePostTeleport
Action LocomotionTeleport.EnterStatePostTeleport
This event will occur after the teleport has completed.
Definition at line 749 of file LocomotionTeleport.cs.
EnterStatePreTeleport
Action LocomotionTeleport.EnterStatePreTeleport
This event is raised when the system enteres the PreTeleport state.
Definition at line 631 of file LocomotionTeleport.cs.
EnterStateReady
Action LocomotionTeleport.EnterStateReady
This event is raised when entering the Ready state. The initial use for this is for the input handler to start processing input in order to eventually set the TeleportIntention to Aim when the user requests it.
Definition at line 454 of file LocomotionTeleport.cs.
EnterStateTeleporting
Action LocomotionTeleport.EnterStateTeleporting
This event will occur when the teleport actually occurs. There should be one Transition Handler enabled and attached to this event. There may be other handlers attached to this event to trigger sound effects or gameplay logic to respond to the teleport event.
The transition handler is responsible for actually moving the player to the destination, and can achieve this goal however it wants. Example teleport transition handlers include:
Instant - Just move the player with no delay or effect.
Blink - Fade the camera to black, teleport, then fade back up.
Warp - Translate the camera over some fixed amount of time to the new destination.
Definition at line 714 of file LocomotionTeleport.cs.
ExitStateAim
Action LocomotionTeleport.ExitStateAim
This event is raised when the aim state is exited. This is typically used by aim visualizers to deactivate any visual effects related to aiming.
Definition at line 551 of file LocomotionTeleport.cs.
Teleported
Action<Transform, Vector3, Quaternion> LocomotionTeleport.Teleported
This event is raised when the character actually teleports, which is typically triggered by the transition handler.
The first parameter is the character controller's transform. The second and third are the position and rotation, respectively, which the character controller will be assigned immediately after the event is raised.
Definition at line 791 of file LocomotionTeleport.cs.
UpdateAimData
Action<AimData> LocomotionTeleport.UpdateAimData
Aim and Target handlers are responsible for populating the AimData with the relevant aim data, which is used for a number of purposes within the teleport system.
Definition at line 531 of file LocomotionTeleport.cs.
UpdateTeleportDestination
Action<bool, Vector3?, Quaternion?, Quaternion?> LocomotionTeleport.UpdateTeleportDestination
This event is raised when the teleport destination is in the process of being updated. It is used by the active TeleportDestination to update it's visual state, position and orientation indicator to match the results of the teleport aim and targeting system.
Definition at line 167 of file LocomotionTeleport.cs.
The documentation for this class was generated from the following file:
Assets/Oculus/SampleFramework/Core/Locomotion/Scripts/LocomotionTeleport.cs