VR_Test: Meta.WitAi.TTS.Integrations.TTSDiskCache Class Reference
Meta.WitAi.TTS.Integrations.TTSDiskCache Class Reference
Public Member Functions
string GetDiskCachePath (TTSClipData clipData)
Builds full cache path.
bool ShouldCacheToDisk (TTSClipData clipData)
Determine if should cache to disk or not.
void CheckCachedToDisk (TTSClipData clipData, Action< TTSClipData, bool > onCheckComplete)
Determines if file is cached on disk.
void StreamFromDiskCache (TTSClipData clipData)
Performs async load request.
void CancelDiskCacheStream (TTSClipData clipData)
Cancels unity request.
Protected Member Functions
virtual void OnDestroy ()
virtual void OnStreamComplete (TTSClipData clipData, string error)
Properties
string DiskPath [get]
TTSDiskCacheSettings DiskCacheDefaultSettings [get]
The default cache settings.
TTSStreamEvents DiskStreamEvents [get, set]
All events for streaming from the disk cache.
Properties inherited from Meta.WitAi.TTS.Interfaces.ITTSDiskCacheHandler
Private Attributes
string _diskPath = "TTS/"
The relative path from the DiskCacheLocation in TTSDiskCacheSettings.
TTSDiskCacheSettings _defaultSettings = new TTSDiskCacheSettings()
The cache default settings.
TTSStreamEvents _events = new TTSStreamEvents()
The cache streaming events.
Dictionary< string, VRequest > _streamRequests = new Dictionary<string, VRequest>()
Detailed Description
Definition at line 22 of file TTSDiskCache.cs.
Member Function Documentation
CancelDiskCacheStream()
void Meta.WitAi.TTS.Integrations.TTSDiskCache.CancelDiskCacheStream (TTSClipData clipData)
Cancels unity request.
Implements Meta.WitAi.TTS.Interfaces.ITTSDiskCacheHandler.
Definition at line 181 of file TTSDiskCache.cs.
        {
            // Ignore if not currently streaming
            if (!_streamRequests.ContainsKey(clipData.clipID))
            {
                return;
            }
            // Get request
            VRequest request = _streamRequests[clipData.clipID];
            _streamRequests.Remove(clipData.clipID);
            // Cancel immediately
            request?.Cancel();
            request = null;
            // Call cancel
            DiskStreamEvents?.OnStreamCancel?.Invoke(clipData);
        }
References Meta.WitAi.TTS.Integrations.TTSDiskCache.DiskStreamEvents.
CheckCachedToDisk()
void Meta.WitAi.TTS.Integrations.TTSDiskCache.CheckCachedToDisk (TTSClipData clipData, Action< TTSClipData, bool > onCheckComplete)
Determines if file is cached on disk.
Parameters
clipData Request data
Returns
True if file is on disk
Implements Meta.WitAi.TTS.Interfaces.ITTSDiskCacheHandler.
Definition at line 126 of file TTSDiskCache.cs.
        {
            // Get path
            string cachePath = GetDiskCachePath(clipData);
            if (string.IsNullOrEmpty(cachePath))
            {
                onCheckComplete?.Invoke(clipData, false);
                return;
            }
            // Check if file exists
            VRequest request = new VRequest();
            bool canPerform = request.RequestFileExists(cachePath, (success, error) =>
            {
                // Remove
                if (_streamRequests.ContainsKey(clipData.clipID))
                {
                    _streamRequests.Remove(clipData.clipID);
                }
                // Complete
                onCheckComplete(clipData, success);
            });
            if (canPerform)
            {
                _streamRequests[clipData.clipID] = request;
            }
        }
References Meta.WitAi.TTS.Integrations.TTSDiskCache.GetDiskCachePath(), and Meta.WitAi.Requests.VRequest.RequestFileExists().
GetDiskCachePath()
string Meta.WitAi.TTS.Integrations.TTSDiskCache.GetDiskCachePath (TTSClipData clipData)
Builds full cache path.
Parameters
clipData
Returns
Implements Meta.WitAi.TTS.Interfaces.ITTSDiskCacheHandler.
Definition at line 66 of file TTSDiskCache.cs.
        {
            // Disabled
            if (!ShouldCacheToDisk(clipData))
            {
                return string.Empty;
            }
            // Get directory path
            TTSDiskCacheLocation location = clipData.diskCacheSettings.DiskCacheLocation;
            string directory = string.Empty;
            switch (location)
            {
                case TTSDiskCacheLocation.Persistent:
                    directory = Application.persistentDataPath;
                    break;
                case TTSDiskCacheLocation.Temporary:
                    directory = Application.temporaryCachePath;
                    break;
                case TTSDiskCacheLocation.Preload:
                    directory = Application.streamingAssetsPath;
                    break;
            }
            if (string.IsNullOrEmpty(directory))
            {
                return string.Empty;
            }
            // Add tts cache path & clean
            directory = Path.Combine(directory, DiskPath);
            // Generate tts directory if possible
            if (location != TTSDiskCacheLocation.Preload || !Application.isPlaying)
            {
                if (!IOUtility.CreateDirectory(directory, true))
                {
                    VLog.E($"Failed to create tts directory\nPath: {directory}\nLocation: {location}");
                    return string.Empty;
                }
            }
            // Return clip path
            return Path.Combine(directory, clipData.clipID + "." + WitTTSVRequest.GetAudioExtension(clipData.audioType));
        }
References Meta.WitAi.Utilities.IOUtility.CreateDirectory(), Meta.WitAi.TTS.Data.TTSDiskCacheSettings.DiskCacheLocation, Meta.WitAi.VLog.E(), and Meta.WitAi.TTS.Integrations.TTSDiskCache.ShouldCacheToDisk().
OnDestroy()
virtual void Meta.WitAi.TTS.Integrations.TTSDiskCache.OnDestroy () protected virtual
Definition at line 51 of file TTSDiskCache.cs.
        {
            Dictionary<string, VRequest> requests = _streamRequests;
            _streamRequests.Clear();
            foreach (var request in requests.Values)
            {
                request.Cancel();
            }
        }
OnStreamComplete()
virtual void Meta.WitAi.TTS.Integrations.TTSDiskCache.OnStreamComplete (TTSClipData clipData, string error) protected virtual
Definition at line 201 of file TTSDiskCache.cs.
        {
            // Ignore if not currently streaming
            if (!_streamRequests.ContainsKey(clipData.clipID))
            {
                return;
            }
            // Remove from list
            _streamRequests.Remove(clipData.clipID);
            // Error
            if (!string.IsNullOrEmpty(error))
            {
                DiskStreamEvents?.OnStreamError?.Invoke(clipData, error);
            }
            // Success
            else
            {
                DiskStreamEvents?.OnStreamReady?.Invoke(clipData);
            }
        }
ShouldCacheToDisk()
bool Meta.WitAi.TTS.Integrations.TTSDiskCache.ShouldCacheToDisk (TTSClipData clipData)
Determine if should cache to disk or not.
Parameters
clipData All clip data
Returns
Returns true if should cache to disk
Implements Meta.WitAi.TTS.Interfaces.ITTSDiskCacheHandler.
Definition at line 116 of file TTSDiskCache.cs.
        {
            return clipData != null && clipData.diskCacheSettings.DiskCacheLocation != TTSDiskCacheLocation.Stream && !string.IsNullOrEmpty(clipData.clipID);
        }
StreamFromDiskCache()
void Meta.WitAi.TTS.Integrations.TTSDiskCache.StreamFromDiskCache (TTSClipData clipData)
Performs async load request.
Implements Meta.WitAi.TTS.Interfaces.ITTSDiskCacheHandler.
Definition at line 157 of file TTSDiskCache.cs.
        {
            // Invoke begin
            DiskStreamEvents?.OnStreamBegin?.Invoke(clipData);
            // Get file path
            string filePath = GetDiskCachePath(clipData);
            // Load clip async
            VRequest request = new VRequest((progress) => clipData.loadProgress = progress);
            bool canPerform = request.RequestAudioStream(clipData.clipStream, new Uri(request.CleanUrl(filePath)),
                (clipStream, error) =>
                {
                    clipData.clipStream = clipStream;
                    OnStreamComplete(clipData, error);
                }, clipData.audioType, clipData.diskCacheSettings.StreamFromDisk);
            if (canPerform)
            {
                _streamRequests[clipData.clipID] = request;
            }
        }
References Meta.WitAi.Requests.VRequest.CleanUrl(), Meta.WitAi.TTS.Integrations.TTSDiskCache.DiskStreamEvents, Meta.WitAi.TTS.Integrations.TTSDiskCache.GetDiskCachePath(), Meta.WitAi.Requests.VRequest.RequestAudioStream(), and Meta.WitAi.TTS.Data.TTSDiskCacheSettings.StreamFromDisk.
Member Data Documentation
_defaultSettings
TTSDiskCacheSettings Meta.WitAi.TTS.Integrations.TTSDiskCache._defaultSettings = new TTSDiskCacheSettings() private
The cache default settings.
Definition at line 34 of file TTSDiskCache.cs.
_diskPath
string Meta.WitAi.TTS.Integrations.TTSDiskCache._diskPath = "TTS/" private
The relative path from the DiskCacheLocation in TTSDiskCacheSettings.
Definition at line 28 of file TTSDiskCache.cs.
_events
TTSStreamEvents Meta.WitAi.TTS.Integrations.TTSDiskCache._events = new TTSStreamEvents() private
The cache streaming events.
Definition at line 40 of file TTSDiskCache.cs.
_streamRequests
Dictionary<string, VRequest> Meta.WitAi.TTS.Integrations.TTSDiskCache._streamRequests = new Dictionary<string, VRequest>() private
Definition at line 48 of file TTSDiskCache.cs.
Property Documentation
DiskCacheDefaultSettings
TTSDiskCacheSettings Meta.WitAi.TTS.Integrations.TTSDiskCache.DiskCacheDefaultSettings get
The default cache settings.
Implements Meta.WitAi.TTS.Interfaces.ITTSDiskCacheHandler.
Definition at line 35 of file TTSDiskCache.cs.
DiskPath
string Meta.WitAi.TTS.Integrations.TTSDiskCache.DiskPath get
Definition at line 29 of file TTSDiskCache.cs.
DiskStreamEvents
TTSStreamEvents Meta.WitAi.TTS.Integrations.TTSDiskCache.DiskStreamEvents get set
All events for streaming from the disk cache.
Implements Meta.WitAi.TTS.Interfaces.ITTSDiskCacheHandler.
Definition at line 41 of file TTSDiskCache.cs.
        {
            get => _events;
            set { _events = value; }
        }
The documentation for this class was generated from the following file:
Assets/Oculus/Voice/Lib/Wit.ai/Features/TTS/Scripts/Runtime/Integrations/TTSDiskCache.cs