VR_Test: OVRHaptics.OVRHapticsOutput Class Reference
OVRHaptics.OVRHapticsOutput Class Reference
Classes
class ClipPlaybackTracker
Public Member Functions
OVRHapticsOutput (uint controller)
void Process ()
The system calls this each frame to update haptics playback.
void Preempt (OVRHapticsClip clip)
Immediately plays the specified clip without waiting for any currently-playing clip to finish.
void Queue (OVRHapticsClip clip)
Enqueues the specified clip to play after any currently-playing clip finishes.
void Mix (OVRHapticsClip clip)
Adds the samples from the specified clip to the ones in the currently-playing clip(s).
void Clear ()
Private Attributes
bool m_lowLatencyMode = true
bool m_paddingEnabled = true
int m_prevSamplesQueued = 0
float m_prevSamplesQueuedTime = 0
int m_numPredictionHits = 0
int m_numPredictionMisses = 0
int m_numUnderruns = 0
List< ClipPlaybackTracker > m_pendingClips = new List<ClipPlaybackTracker>()
uint m_controller = 0
OVRNativeBuffer m_nativeBuffer
OVRHapticsClip m_paddingClip = new OVRHapticsClip()
int PrevSampleRateHz = -1
Detailed Description
Definition at line 134 of file OVRHaptics.cs.
Constructor & Destructor Documentation
OVRHapticsOutput()
OVRHaptics.OVRHapticsOutput.OVRHapticsOutput (uint controller)
Definition at line 163 of file OVRHaptics.cs.
        {
#if UNITY_ANDROID
            m_paddingEnabled = false;
#endif
            m_controller = controller;
        }
Member Function Documentation
Clear()
void OVRHaptics.OVRHapticsOutput.Clear ()
Definition at line 401 of file OVRHaptics.cs.
        {
            m_pendingClips.Clear();
        }
Mix()
void OVRHaptics.OVRHapticsOutput.Mix (OVRHapticsClip clip)
Adds the samples from the specified clip to the ones in the currently-playing clip(s).
Definition at line 327 of file OVRHaptics.cs.
        {
            int numClipsToMix = 0;
            int numSamplesToMix = 0;
            int numSamplesRemaining = clip.Count;
            while (numSamplesRemaining > 0 && numClipsToMix < m_pendingClips.Count)
            {
                int numSamplesRemainingInClip =
                    m_pendingClips[numClipsToMix].Clip.Count - m_pendingClips[numClipsToMix].ReadCount;
                numSamplesRemaining -= numSamplesRemainingInClip;
                numSamplesToMix += numSamplesRemainingInClip;
                numClipsToMix++;
            }
            if (numSamplesRemaining > 0)
            {
                numSamplesToMix += numSamplesRemaining;
                numSamplesRemaining = 0;
            }
            if (numClipsToMix > 0)
            {
                OVRHapticsClip mixClip = new OVRHapticsClip(numSamplesToMix);
                OVRHapticsClip a = clip;
                int aReadCount = 0;
                for (int i = 0; i < numClipsToMix; i++)
                {
                    OVRHapticsClip b = m_pendingClips[i].Clip;
                    for (int bReadCount = m_pendingClips[i].ReadCount; bReadCount < b.Count; bReadCount++)
                    {
                        if (OVRHaptics.Config.SampleSizeInBytes == 1)
{
                            byte sample = 0; // TODO support multi-byte samples
                            if ((aReadCount < a.Count) && (bReadCount < b.Count))
{
                                sample = (byte)(Mathf.Clamp(a.Samples[aReadCount] + b.Samples[bReadCount], 0,
                                    System.Byte.MaxValue)); // TODO support multi-byte samples
                                aReadCount++;
                            }
                            else if (bReadCount < b.Count)
{
                                sample = b.Samples[bReadCount]; // TODO support multi-byte samples
                            }
                            mixClip.WriteSample(sample); // TODO support multi-byte samples
                        }
                    }
                }
                while (aReadCount < a.Count)
                {
                    if (OVRHaptics.Config.SampleSizeInBytes == 1)
                    {
                        mixClip.WriteSample(a.Samples[aReadCount]); // TODO support multi-byte samples
                    }
                    aReadCount++;
                }
                m_pendingClips[0] = new ClipPlaybackTracker(mixClip);
                for (int i = 1; i < numClipsToMix; i++)
                {
                    m_pendingClips.RemoveAt(1);
                }
            }
            else
            {
                m_pendingClips.Add(new ClipPlaybackTracker(clip));
            }
        }
References OVRHapticsClip.Count, OVRHapticsClip.Samples, and OVRHapticsClip.WriteSample().
Preempt()
void OVRHaptics.OVRHapticsOutput.Preempt (OVRHapticsClip clip)
Immediately plays the specified clip without waiting for any currently-playing clip to finish.
Definition at line 310 of file OVRHaptics.cs.
        {
            m_pendingClips.Clear();
            m_pendingClips.Add(new ClipPlaybackTracker(clip));
        }
Process()
void OVRHaptics.OVRHapticsOutput.Process ()
The system calls this each frame to update haptics playback.
Definition at line 174 of file OVRHaptics.cs.
        {
            if (OVRHaptics.Config.SampleRateHz == 0)
            {
                if (PrevSampleRateHz != 0)
                {
                    Debug.Log("Unable to process a controller whose SampleRateHz is 0 now.");
                    PrevSampleRateHz = 0;
                }
                return;
            }
            PrevSampleRateHz = OVRHaptics.Config.SampleRateHz;
            // Resize the native buffer if the Config changes
            if (m_nativeBuffer.GetCapacity() != Config.MaximumBufferSamplesCount * Config.SampleSizeInBytes)
            {
                m_nativeBuffer.Reset(Config.MaximumBufferSamplesCount * Config.SampleSizeInBytes);
            }
            var hapticsState = OVRPlugin.GetControllerHapticsState(m_controller);
            float elapsedTime = Time.realtimeSinceStartup - m_prevSamplesQueuedTime;
            if (m_prevSamplesQueued > 0)
            {
                int expectedSamples = m_prevSamplesQueued - (int)(elapsedTime * OVRHaptics.Config.SampleRateHz + 0.5f);
                if (expectedSamples < 0)
                    expectedSamples = 0;
                if ((hapticsState.SamplesQueued - expectedSamples) == 0)
                    m_numPredictionHits++;
                else
                    m_numPredictionMisses++;
                //Debug.Log(hapticsState.SamplesAvailable + "a " + hapticsState.SamplesQueued + "q " + expectedSamples + "e "
                //+ "Prediction Accuracy: " + m_numPredictionHits / (float)(m_numPredictionMisses + m_numPredictionHits));
                if ((expectedSamples > 0) && (hapticsState.SamplesQueued == 0))
                {
                    m_numUnderruns++;
                    //Debug.LogError("Samples Underrun (" + m_controller + " #" + m_numUnderruns + ") -"
                    //        + " Expected: " + expectedSamples
                    //        + " Actual: " + hapticsState.SamplesQueued);
                }
                m_prevSamplesQueued = hapticsState.SamplesQueued;
                m_prevSamplesQueuedTime = Time.realtimeSinceStartup;
            }
            int desiredSamplesCount = OVRHaptics.Config.OptimalBufferSamplesCount;
            if (m_lowLatencyMode)
            {
                float sampleRateMs = 1000.0f / (float)OVRHaptics.Config.SampleRateHz;
                float elapsedMs = elapsedTime * 1000.0f;
                int samplesNeededPerFrame = (int)Mathf.Ceil(elapsedMs / sampleRateMs);
                int lowLatencySamplesCount = OVRHaptics.Config.MinimumSafeSamplesQueued + samplesNeededPerFrame;
                if (lowLatencySamplesCount < desiredSamplesCount)
                    desiredSamplesCount = lowLatencySamplesCount;
            }
            if (hapticsState.SamplesQueued > desiredSamplesCount)
                return;
            if (desiredSamplesCount > OVRHaptics.Config.MaximumBufferSamplesCount)
                desiredSamplesCount = OVRHaptics.Config.MaximumBufferSamplesCount;
            if (desiredSamplesCount > hapticsState.SamplesAvailable)
                desiredSamplesCount = hapticsState.SamplesAvailable;
            int acquiredSamplesCount = 0;
            int clipIndex = 0;
            while (acquiredSamplesCount < desiredSamplesCount && clipIndex < m_pendingClips.Count)
            {
                int numSamplesToCopy = desiredSamplesCount - acquiredSamplesCount;
                int remainingSamplesInClip = m_pendingClips[clipIndex].Clip.Count - m_pendingClips[clipIndex].ReadCount;
                if (numSamplesToCopy > remainingSamplesInClip)
                    numSamplesToCopy = remainingSamplesInClip;
                if (numSamplesToCopy > 0)
                {
                    int numBytes = numSamplesToCopy * OVRHaptics.Config.SampleSizeInBytes;
                    int dstOffset = acquiredSamplesCount * OVRHaptics.Config.SampleSizeInBytes;
                    int srcOffset = m_pendingClips[clipIndex].ReadCount * OVRHaptics.Config.SampleSizeInBytes;
                    Marshal.Copy(m_pendingClips[clipIndex].Clip.Samples, srcOffset,
                        m_nativeBuffer.GetPointer(dstOffset), numBytes);
                    m_pendingClips[clipIndex].ReadCount += numSamplesToCopy;
                    acquiredSamplesCount += numSamplesToCopy;
                }
                clipIndex++;
            }
            for (int i = m_pendingClips.Count - 1; i >= 0 && m_pendingClips.Count > 0; i--)
            {
                if (m_pendingClips[i].ReadCount >= m_pendingClips[i].Clip.Count)
                    m_pendingClips.RemoveAt(i);
            }
            if (m_paddingEnabled)
            {
                int desiredPadding = desiredSamplesCount - (hapticsState.SamplesQueued + acquiredSamplesCount);
                if (desiredPadding < (OVRHaptics.Config.MinimumBufferSamplesCount - acquiredSamplesCount))
                    desiredPadding = (OVRHaptics.Config.MinimumBufferSamplesCount - acquiredSamplesCount);
                if (desiredPadding > hapticsState.SamplesAvailable)
                    desiredPadding = hapticsState.SamplesAvailable;
                if (desiredPadding > 0)
                {
                    int numBytes = desiredPadding * OVRHaptics.Config.SampleSizeInBytes;
                    int dstOffset = acquiredSamplesCount * OVRHaptics.Config.SampleSizeInBytes;
                    int srcOffset = 0;
                    Marshal.Copy(m_paddingClip.Samples, srcOffset, m_nativeBuffer.GetPointer(dstOffset), numBytes);
                    acquiredSamplesCount += desiredPadding;
                }
            }
            if (acquiredSamplesCount > 0)
            {
                OVRPlugin.HapticsBuffer hapticsBuffer;
                hapticsBuffer.Samples = m_nativeBuffer.GetPointer();
                hapticsBuffer.SamplesCount = acquiredSamplesCount;
                OVRPlugin.SetControllerHaptics(m_controller, hapticsBuffer);
                hapticsState = OVRPlugin.GetControllerHapticsState(m_controller);
                m_prevSamplesQueued = hapticsState.SamplesQueued;
                m_prevSamplesQueuedTime = Time.realtimeSinceStartup;
            }
        }
References OVRNativeBuffer.GetCapacity(), OVRNativeBuffer.GetPointer(), OVRNativeBuffer.Reset(), and OVRHapticsClip.Samples.
Queue()
void OVRHaptics.OVRHapticsOutput.Queue (OVRHapticsClip clip)
Enqueues the specified clip to play after any currently-playing clip finishes.
Definition at line 319 of file OVRHaptics.cs.
        {
            m_pendingClips.Add(new ClipPlaybackTracker(clip));
        }
Member Data Documentation
m_controller
uint OVRHaptics.OVRHapticsOutput.m_controller = 0 private
Definition at line 155 of file OVRHaptics.cs.
m_lowLatencyMode
bool OVRHaptics.OVRHapticsOutput.m_lowLatencyMode = true private
Definition at line 147 of file OVRHaptics.cs.
m_nativeBuffer
OVRNativeBuffer OVRHaptics.OVRHapticsOutput.m_nativeBuffer private
Initial value:
=
            new OVRNativeBuffer(OVRHaptics.Config.MaximumBufferSamplesCount * OVRHaptics.Config.SampleSizeInBytes)
Definition at line 157 of file OVRHaptics.cs.
m_numPredictionHits
int OVRHaptics.OVRHapticsOutput.m_numPredictionHits = 0 private
Definition at line 151 of file OVRHaptics.cs.
m_numPredictionMisses
int OVRHaptics.OVRHapticsOutput.m_numPredictionMisses = 0 private
Definition at line 152 of file OVRHaptics.cs.
m_numUnderruns
int OVRHaptics.OVRHapticsOutput.m_numUnderruns = 0 private
Definition at line 153 of file OVRHaptics.cs.
m_paddingClip
OVRHapticsClip OVRHaptics.OVRHapticsOutput.m_paddingClip = new OVRHapticsClip() private
Definition at line 160 of file OVRHaptics.cs.
m_paddingEnabled
bool OVRHaptics.OVRHapticsOutput.m_paddingEnabled = true private
Definition at line 148 of file OVRHaptics.cs.
m_pendingClips
List<ClipPlaybackTracker> OVRHaptics.OVRHapticsOutput.m_pendingClips = new List<ClipPlaybackTracker>() private
Definition at line 154 of file OVRHaptics.cs.
m_prevSamplesQueued
int OVRHaptics.OVRHapticsOutput.m_prevSamplesQueued = 0 private
Definition at line 149 of file OVRHaptics.cs.
m_prevSamplesQueuedTime
float OVRHaptics.OVRHapticsOutput.m_prevSamplesQueuedTime = 0 private
Definition at line 150 of file OVRHaptics.cs.
PrevSampleRateHz
int OVRHaptics.OVRHapticsOutput.PrevSampleRateHz = -1 private
Definition at line 161 of file OVRHaptics.cs.
The documentation for this class was generated from the following file:
Assets/Oculus/VR/Scripts/OVRHaptics.cs