VR_Test: OVRLipSyncContextMorphTarget Class Reference
OVRLipSyncContextMorphTarget Class Reference
Public Attributes
SkinnedMeshRenderer skinnedMeshRenderer = null
int[] visemeToBlendTargets = Enumerable.Range(0, OVRLipSync.VisemeCount).ToArray()
bool enableVisemeTestKeys = false
KeyCode[] visemeTestKeys
KeyCode laughterKey = KeyCode.CapsLock
int laughterBlendTarget = OVRLipSync.VisemeCount
float laughterThreshold = 0.5f
float laughterMultiplier = 1.5f
int smoothAmount = 70
Private Member Functions
void Start ()
Start this instance.
void Update ()
Update this instance.
void CheckForKeys ()
Sends the signals.
void SetVisemeToMorphTarget (OVRLipSync.Frame frame)
Sets the viseme to morph target.
void SetLaughterToMorphTarget (OVRLipSync.Frame frame)
Sets the laughter to morph target.
void CheckVisemeKey (KeyCode key, int viseme, int amount)
Sends the viseme signal.
void CheckLaughterKey ()
Sends the laughter signal.
Private Attributes
OVRLipSyncContextBase lipsyncContext = null
Detailed Description
Definition at line 26 of file OVRLipSyncContextMorphTarget.cs.
Member Function Documentation
CheckForKeys()
void OVRLipSyncContextMorphTarget.CheckForKeys () private
Sends the signals.
Definition at line 144 of file OVRLipSyncContextMorphTarget.cs.
    {
        if (enableVisemeTestKeys)
        {
            for (int i = 0; i < OVRLipSync.VisemeCount; ++i)
            {
                CheckVisemeKey(visemeTestKeys[i], i, 100);
            }
        }
        CheckLaughterKey();
    }
References CheckLaughterKey(), and CheckVisemeKey().
CheckLaughterKey()
void OVRLipSyncContextMorphTarget.CheckLaughterKey () private
Sends the laughter signal.
Definition at line 216 of file OVRLipSyncContextMorphTarget.cs.
    {
        if (Input.GetKeyDown(laughterKey))
        {
            lipsyncContext.SetLaughterBlend(100);
        }
        if (Input.GetKeyUp(laughterKey))
        {
            lipsyncContext.SetLaughterBlend(0);
        }
    }
References OVRLipSyncContextBase.SetLaughterBlend().
CheckVisemeKey()
void OVRLipSyncContextMorphTarget.CheckVisemeKey (KeyCode key, int viseme, int amount) private
Sends the viseme signal.
Parameters
key Key.
viseme Viseme.
arg1 Arg1.
Definition at line 201 of file OVRLipSyncContextMorphTarget.cs.
    {
        if (Input.GetKeyDown(key))
        {
            lipsyncContext.SetVisemeBlend(visemeToBlendTargets[viseme], amount);
        }
        if (Input.GetKeyUp(key))
        {
            lipsyncContext.SetVisemeBlend(visemeToBlendTargets[viseme], 0);
        }
    }
References OVRLipSyncContextBase.SetVisemeBlend().
SetLaughterToMorphTarget()
void OVRLipSyncContextMorphTarget.SetLaughterToMorphTarget (OVRLipSync::Frame frame) private
Sets the laughter to morph target.
Definition at line 177 of file OVRLipSyncContextMorphTarget.cs.
    {
        if (laughterBlendTarget != -1)
        {
            // Laughter score will be raw classifier output in [0,1]
            float laughterScore = frame.laughterScore;
            // Threshold then re-map to [0,1]
            laughterScore = laughterScore < laughterThreshold ? 0.0f : laughterScore - laughterThreshold;
            laughterScore = Mathf.Min(laughterScore * laughterMultiplier, 1.0f);
            laughterScore *= 1.0f / laughterThreshold;
            skinnedMeshRenderer.SetBlendShapeWeight(
                laughterBlendTarget,
                laughterScore * 100.0f);
        }
    }
SetVisemeToMorphTarget()
void OVRLipSyncContextMorphTarget.SetVisemeToMorphTarget (OVRLipSync::Frame frame) private
Sets the viseme to morph target.
Definition at line 160 of file OVRLipSyncContextMorphTarget.cs.
    {
        for (int i = 0; i < visemeToBlendTargets.Length; i++)
        {
            if (visemeToBlendTargets[i] != -1)
            {
                // Viseme blend weights are in range of 0->1.0, we need to make range 100
                skinnedMeshRenderer.SetBlendShapeWeight(
                    visemeToBlendTargets[i],
                    frame.Visemes[i] * 100.0f);
            }
        }
    }
Start()
void OVRLipSyncContextMorphTarget.Start () private
Start this instance.
Definition at line 90 of file OVRLipSyncContextMorphTarget.cs.
    {
        // morph target needs to be set manually; possibly other components will need the same
        if(skinnedMeshRenderer == null)
        {
            Debug.LogError("LipSyncContextMorphTarget.Start Error: " +
                "Please set the target Skinned Mesh Renderer to be controlled!");
            return;
        }
        // make sure there is a phoneme context assigned to this object
        lipsyncContext = GetComponent<OVRLipSyncContextBase>();
        if(lipsyncContext == null)
        {
            Debug.LogError("LipSyncContextMorphTarget.Start Error: " +
                "No OVRLipSyncContext component on this object!");
        }
        else
        {
            // Send smoothing amount to context
            lipsyncContext.Smoothing = smoothAmount;
        }
    }
Update()
void OVRLipSyncContextMorphTarget.Update () private
Update this instance.
Definition at line 117 of file OVRLipSyncContextMorphTarget.cs.
    {
        if((lipsyncContext != null) && (skinnedMeshRenderer != null))
        {
            // get the current viseme frame
            OVRLipSync.Frame frame = lipsyncContext.GetCurrentPhonemeFrame();
            if (frame != null)
            {
                SetVisemeToMorphTarget(frame);
                SetLaughterToMorphTarget(frame);
            }
            // TEST visemes by capturing key inputs and sending a signal
            CheckForKeys();
            // Update smoothing value
            if (smoothAmount != lipsyncContext.Smoothing)
            {
                lipsyncContext.Smoothing = smoothAmount;
            }
        }
    }
References CheckForKeys(), OVRLipSyncContextBase.GetCurrentPhonemeFrame(), SetLaughterToMorphTarget(), and SetVisemeToMorphTarget().
Member Data Documentation
enableVisemeTestKeys
bool OVRLipSyncContextMorphTarget.enableVisemeTestKeys = false
Definition at line 40 of file OVRLipSyncContextMorphTarget.cs.
laughterBlendTarget
int OVRLipSyncContextMorphTarget.laughterBlendTarget = OVRLipSync.VisemeCount
Definition at line 66 of file OVRLipSyncContextMorphTarget.cs.
laughterKey
KeyCode OVRLipSyncContextMorphTarget.laughterKey = KeyCode.CapsLock
Definition at line 63 of file OVRLipSyncContextMorphTarget.cs.
laughterMultiplier
float OVRLipSyncContextMorphTarget.laughterMultiplier = 1.5f
Definition at line 74 of file OVRLipSyncContextMorphTarget.cs.
laughterThreshold
float OVRLipSyncContextMorphTarget.laughterThreshold = 0.5f
Definition at line 70 of file OVRLipSyncContextMorphTarget.cs.
lipsyncContext
OVRLipSyncContextBase OVRLipSyncContextMorphTarget.lipsyncContext = null private
Definition at line 84 of file OVRLipSyncContextMorphTarget.cs.
skinnedMeshRenderer
SkinnedMeshRenderer OVRLipSyncContextMorphTarget.skinnedMeshRenderer = null
Definition at line 32 of file OVRLipSyncContextMorphTarget.cs.
smoothAmount
int OVRLipSyncContextMorphTarget.smoothAmount = 70
Definition at line 79 of file OVRLipSyncContextMorphTarget.cs.
visemeTestKeys
KeyCode [] OVRLipSyncContextMorphTarget.visemeTestKeys
Initial value:
=
    {
        KeyCode.BackQuote,
        KeyCode.Tab,
        KeyCode.Q,
        KeyCode.W,
        KeyCode.E,
        KeyCode.R,
        KeyCode.T,
        KeyCode.Y,
        KeyCode.U,
        KeyCode.I,
        KeyCode.O,
        KeyCode.P,
        KeyCode.LeftBracket,
        KeyCode.RightBracket,
        KeyCode.Backslash,
    }
Definition at line 43 of file OVRLipSyncContextMorphTarget.cs.
    {
        KeyCode.BackQuote,
        KeyCode.Tab,
        KeyCode.Q,
        KeyCode.W,
        KeyCode.E,
        KeyCode.R,
        KeyCode.T,
        KeyCode.Y,
        KeyCode.U,
        KeyCode.I,
        KeyCode.O,
        KeyCode.P,
        KeyCode.LeftBracket,
        KeyCode.RightBracket,
        KeyCode.Backslash,
    };
visemeToBlendTargets
int [] OVRLipSyncContextMorphTarget.visemeToBlendTargets = Enumerable.Range(0, OVRLipSync.VisemeCount).ToArray()
Definition at line 36 of file OVRLipSyncContextMorphTarget.cs.
The documentation for this class was generated from the following file:
Assets/Oculus/LipSync/Scripts/OVRLipSyncContextMorphTarget.cs