VR_Test: OVRBoundary Class Reference
OVRBoundary Class Reference
Provides access to the Oculus boundary system.
Classes
struct BoundaryTestResult
Provides test results of boundary system queries.
Public Types
enum Node { HandLeft = OVRPlugin.Node.HandLeft , HandRight = OVRPlugin.Node.HandRight , Head = OVRPlugin.Node.Head }
Specifies a tracked node that can be queried through the boundary system.
enum BoundaryType { OuterBoundary = OVRPlugin.BoundaryType.OuterBoundary , PlayArea = OVRPlugin.BoundaryType.PlayArea }
Specifies a boundary type surface.
Public Member Functions
bool GetConfigured ()
Returns true if the boundary system is currently configured with valid boundary data.
OVRBoundary.BoundaryTestResult TestNode (OVRBoundary.Node node, OVRBoundary.BoundaryType boundaryType)
Returns the results of testing a tracked node against the specified boundary type. All points are returned in local tracking space shared by tracked nodes and accessible through OVRCameraRig's trackingSpace anchor.
OVRBoundary.BoundaryTestResult TestPoint (Vector3 point, OVRBoundary.BoundaryType boundaryType)
Returns the results of testing a 3d point against the specified boundary type. The test point is expected in local tracking space. All points are returned in local tracking space shared by tracked nodes and accessible through OVRCameraRig's trackingSpace anchor.
Vector3[] GetGeometry (OVRBoundary.BoundaryType boundaryType)
Returns an array of 3d points (in clockwise order) that define the specified boundary type. All points are returned in local tracking space shared by tracked nodes and accessible through OVRCameraRig's trackingSpace anchor.
Vector3 GetDimensions (OVRBoundary.BoundaryType boundaryType)
Returns a vector that indicates the spatial dimensions of the specified boundary type. (x = width, y = height, z = depth)
bool GetVisible ()
Returns true if the boundary system is currently visible.
void SetVisible (bool value)
Requests that the boundary system visibility be set to the specified value. The actual visibility can be overridden by the system (i.e., proximity trigger) or by the user (boundary system disabled)
Private Attributes
List< Vector3 > cachedGeometryList = new List<Vector3>()
Static Private Attributes
static int cachedVector3fSize = Marshal.SizeOf(typeof(OVRPlugin.Vector3f))
static OVRNativeBuffer cachedGeometryNativeBuffer = new OVRNativeBuffer(0)
static float[] cachedGeometryManagedBuffer = new float[0]
Detailed Description
Provides access to the Oculus boundary system.
Definition at line 40 of file OVRBoundary.cs.
Member Enumeration Documentation
BoundaryType
enum OVRBoundary.BoundaryType
Specifies a boundary type surface.
Definition at line 60 of file OVRBoundary.cs.
    {
        // Outer boundary that closely matches the user's configured walls.
        [System.Obsolete("Deprecated. This enum value will not be supported in OpenXR", false)]
        OuterBoundary = OVRPlugin.BoundaryType.OuterBoundary,
        // Smaller convex area inset within the outer boundary.
        PlayArea = OVRPlugin.BoundaryType.PlayArea,
    }
Node
enum OVRBoundary.Node
Specifies a tracked node that can be queried through the boundary system.
Definition at line 45 of file OVRBoundary.cs.
    {
        // Tracks the left hand node.
        HandLeft = OVRPlugin.Node.HandLeft,
        // Tracks the right hand node.
        HandRight = OVRPlugin.Node.HandRight,
        // Tracks the head node.
        Head = OVRPlugin.Node.Head,
    }
Member Function Documentation
GetConfigured()
bool OVRBoundary.GetConfigured ()
Returns true if the boundary system is currently configured with valid boundary data.
Definition at line 92 of file OVRBoundary.cs.
    {
        if (OVRManager.loadedXRDevice == OVRManager.XRDevice.Oculus)
            return OVRPlugin.GetBoundaryConfigured();
        else
        {
#if !USING_XR_SDK && !REQUIRES_XR_SDK
            return Boundary.configured;
#else
            return false;
#endif
        }
    }
GetDimensions()
Vector3 OVRBoundary.GetDimensions (OVRBoundary::BoundaryType boundaryType)
Returns a vector that indicates the spatial dimensions of the specified boundary type. (x = width, y = height, z = depth)
Definition at line 217 of file OVRBoundary.cs.
    {
        if (OVRManager.loadedXRDevice == OVRManager.XRDevice.Oculus)
            return OVRPlugin.GetBoundaryDimensions((OVRPlugin.BoundaryType)boundaryType).FromVector3f();
        else
        {
#if !USING_XR_SDK && !REQUIRES_XR_SDK
            Vector3 dimensions;
            if (Boundary.TryGetDimensions(out dimensions,
                    (boundaryType == BoundaryType.PlayArea) ? Boundary.Type.PlayArea : Boundary.Type.TrackedArea))
                return dimensions;
#endif
            return Vector3.zero;
        }
    }
GetGeometry()
Vector3[] OVRBoundary.GetGeometry (OVRBoundary::BoundaryType boundaryType)
Returns an array of 3d points (in clockwise order) that define the specified boundary type. All points are returned in local tracking space shared by tracked nodes and accessible through OVRCameraRig's trackingSpace anchor.
Definition at line 158 of file OVRBoundary.cs.
    {
        if (OVRManager.loadedXRDevice != OVRManager.XRDevice.Oculus)
        {
#if !USING_XR_SDK && !REQUIRES_XR_SDK
            if (Boundary.TryGetGeometry(cachedGeometryList,
                    (boundaryType == BoundaryType.PlayArea) ? Boundary.Type.PlayArea : Boundary.Type.TrackedArea))
            {
                Vector3[] arr = cachedGeometryList.ToArray();
                return arr;
            }
#endif
            Debug.LogError("This functionality is not supported in your current version of Unity.");
            return null;
        }
        int pointsCount = 0;
        if (OVRPlugin.GetBoundaryGeometry2((OVRPlugin.BoundaryType)boundaryType, IntPtr.Zero, ref pointsCount))
        {
            if (pointsCount > 0)
            {
                int requiredNativeBufferCapacity = pointsCount * cachedVector3fSize;
                if (cachedGeometryNativeBuffer.GetCapacity() < requiredNativeBufferCapacity)
                    cachedGeometryNativeBuffer.Reset(requiredNativeBufferCapacity);
                int requiredManagedBufferCapacity = pointsCount * 3;
                if (cachedGeometryManagedBuffer.Length < requiredManagedBufferCapacity)
                    cachedGeometryManagedBuffer = new float[requiredManagedBufferCapacity];
                if (OVRPlugin.GetBoundaryGeometry2((OVRPlugin.BoundaryType)boundaryType,
                        cachedGeometryNativeBuffer.GetPointer(), ref pointsCount))
                {
                    Marshal.Copy(cachedGeometryNativeBuffer.GetPointer(), cachedGeometryManagedBuffer, 0,
                        requiredManagedBufferCapacity);
                    Vector3[] points = new Vector3[pointsCount];
                    for (int i = 0; i < pointsCount; i++)
                    {
                        points[i] = new OVRPlugin.Vector3f()
{
                            x = cachedGeometryManagedBuffer[3 * i + 0],
                            y = cachedGeometryManagedBuffer[3 * i + 1],
                            z = cachedGeometryManagedBuffer[3 * i + 2],
                        }.FromFlippedZVector3f();
                    }
                    return points;
                }
            }
        }
        return new Vector3[0];
    }
References OVRNativeBuffer.GetCapacity(), OVRNativeBuffer.GetPointer(), and OVRNativeBuffer.Reset().
GetVisible()
bool OVRBoundary.GetVisible ()
Returns true if the boundary system is currently visible.
Definition at line 238 of file OVRBoundary.cs.
    {
        if (OVRManager.loadedXRDevice == OVRManager.XRDevice.Oculus)
            return OVRPlugin.GetBoundaryVisible();
        else
        {
#if !USING_XR_SDK && !REQUIRES_XR_SDK
            return Boundary.visible;
#else
            return false;
#endif
        }
    }
SetVisible()
void OVRBoundary.SetVisible (bool value)
Requests that the boundary system visibility be set to the specified value. The actual visibility can be overridden by the system (i.e., proximity trigger) or by the user (boundary system disabled)
Definition at line 257 of file OVRBoundary.cs.
    {
        if (OVRManager.loadedXRDevice == OVRManager.XRDevice.Oculus)
            OVRPlugin.SetBoundaryVisible(value);
        else
        {
#if !USING_XR_SDK && !REQUIRES_XR_SDK
            Boundary.visible = value;
#endif
        }
    }
TestNode()
OVRBoundary.BoundaryTestResult OVRBoundary.TestNode (OVRBoundary::Node node, OVRBoundary::BoundaryType boundaryType)
Returns the results of testing a tracked node against the specified boundary type. All points are returned in local tracking space shared by tracked nodes and accessible through OVRCameraRig's trackingSpace anchor.
Definition at line 111 of file OVRBoundary.cs.
    {
        OVRPlugin.BoundaryTestResult ovrpRes =
            OVRPlugin.TestBoundaryNode((OVRPlugin.Node)node, (OVRPlugin.BoundaryType)boundaryType);
        OVRBoundary.BoundaryTestResult res = new OVRBoundary.BoundaryTestResult()
        {
            IsTriggering = (ovrpRes.IsTriggering == OVRPlugin.Bool.True),
            ClosestDistance = ovrpRes.ClosestDistance,
            ClosestPoint = ovrpRes.ClosestPoint.FromFlippedZVector3f(),
            ClosestPointNormal = ovrpRes.ClosestPointNormal.FromFlippedZVector3f(),
        };
        return res;
    }
TestPoint()
OVRBoundary.BoundaryTestResult OVRBoundary.TestPoint (Vector3 point, OVRBoundary::BoundaryType boundaryType)
Returns the results of testing a 3d point against the specified boundary type. The test point is expected in local tracking space. All points are returned in local tracking space shared by tracked nodes and accessible through OVRCameraRig's trackingSpace anchor.
Definition at line 133 of file OVRBoundary.cs.
    {
        OVRPlugin.BoundaryTestResult ovrpRes =
            OVRPlugin.TestBoundaryPoint(point.ToFlippedZVector3f(), (OVRPlugin.BoundaryType)boundaryType);
        OVRBoundary.BoundaryTestResult res = new OVRBoundary.BoundaryTestResult()
        {
            IsTriggering = (ovrpRes.IsTriggering == OVRPlugin.Bool.True),
            ClosestDistance = ovrpRes.ClosestDistance,
            ClosestPoint = ovrpRes.ClosestPoint.FromFlippedZVector3f(),
            ClosestPointNormal = ovrpRes.ClosestPointNormal.FromFlippedZVector3f(),
        };
        return res;
    }
Member Data Documentation
cachedGeometryList
List<Vector3> OVRBoundary.cachedGeometryList = new List<Vector3>() private
Definition at line 152 of file OVRBoundary.cs.
cachedGeometryManagedBuffer
float [] OVRBoundary.cachedGeometryManagedBuffer = new float[0] static private
Definition at line 151 of file OVRBoundary.cs.
cachedGeometryNativeBuffer
OVRNativeBuffer OVRBoundary.cachedGeometryNativeBuffer = new OVRNativeBuffer(0) static private
Definition at line 150 of file OVRBoundary.cs.
cachedVector3fSize
int OVRBoundary.cachedVector3fSize = Marshal.SizeOf(typeof(OVRPlugin.Vector3f)) static private
Definition at line 149 of file OVRBoundary.cs.
The documentation for this class was generated from the following file:
Assets/Oculus/VR/Scripts/OVRBoundary.cs