VR_Test: Oculus.Voice.Bindings.Android.VoiceSDKImplRequest Class Reference
Oculus.Voice.Bindings.Android.VoiceSDKImplRequest Class Reference
A class generated by VoiceSDKImpl to track voice request calls.
Public Member Functions
VoiceSDKImplRequest (VoiceSDKBinding newService, NLPRequestInputType newInputType, bool newImmediately, WitRequestOptions newOptions, VoiceServiceRequestEvents newEvents)
void HandleStartListening ()
Called audio is now listening.
void HandleStopListening ()
Called audio is no longer listening.
void HandlePartialResponse (string responseJson)
Callback when in progress response data has been received.
void HandlePartialTranscription (string transcription)
Called for partial transcription of text.
void HandleFullTranscription (string transcription)
Called for final transcription of text.
void HandleTransmissionBegan ()
Transmission began.
void HandleCanceled ()
Called when an error message has been received.
void HandleError (string error, string message, string errorBody)
Called when an error message has been received.
void HandleResponse (string responseJson)
Callback when final response data has been received.
Public Member Functions inherited from Meta.Voice.NLPRequest< VoiceServiceRequestEvent, WitRequestOptions, VoiceServiceRequestEvents, VoiceServiceRequestResults >
void Send (string text)
Applies the specified text to the options if possible & then submits.
Protected Member Functions
override void HandleAudioActivation ()
override void HandleAudioDeactivation ()
override void HandleSend ()
override void HandleCancel ()
Protected Member Functions inherited from Meta.WitAi.Requests.VoiceServiceRequest
VoiceServiceRequest (NLPRequestInputType newInputType, WitRequestOptions newOptions, VoiceServiceRequestEvents newEvents)
Constructor for Voice Service requests.
override VoiceServiceRequestResults GetResultsWithMessage (string newMessage)
Returns an empty result object with the current status code.
override void ApplyTranscription (string newTranscription, bool newIsFinal)
Applies a transcription to the current results.
override void ApplyResultResponseData (WitResponseNode newData)
Applies response data to the current results.
override void RaiseEvent (VoiceServiceRequestEvent eventCallback)
Performs an event callback with this request as the parameter.
Protected Member Functions inherited from Meta.Voice.NLPRequest< VoiceServiceRequestEvent, WitRequestOptions, VoiceServiceRequestEvents, VoiceServiceRequestResults >
NLPRequest (NLPRequestInputType newInputType, TOptions newOptions, TEvents newEvents)
Constructor for NLP text & audio requests.
override void SetState (VoiceRequestState newState)
Apply the voice request state.
override void AppendLogData (StringBuilder log, bool warning)
Append NLP request specific data to log.
override string GetActivateAudioError ()
Throw error on text request.
override string GetSendError ()
Throw error on text request.
Properties
VoiceSDKBinding Service [get, private set]
bool Immediately [get, private set]
Properties inherited from Meta.WitAi.Requests.VoiceServiceRequest
int StatusCode [get, protected set]
The status code returned from the last request.
Properties inherited from Meta.Voice.NLPRequest< VoiceServiceRequestEvent, WitRequestOptions, VoiceServiceRequestEvents, VoiceServiceRequestResults >
NLPRequestInputType InputType [get, private set]
The request data input type to be used.
Detailed Description
A class generated by VoiceSDKImpl to track voice request calls.
Definition at line 31 of file VoiceSDKImplRequest.cs.
Constructor & Destructor Documentation
VoiceSDKImplRequest()
Oculus.Voice.Bindings.Android.VoiceSDKImplRequest.VoiceSDKImplRequest (VoiceSDKBinding newService, NLPRequestInputType newInputType, bool newImmediately, WitRequestOptions newOptions, VoiceServiceRequestEvents newEvents)
Definition at line 37 of file VoiceSDKImplRequest.cs.
                                                 : base(newInputType, newOptions, newEvents)
        {
            Service = newService;
            Immediately = newImmediately;
        }
Member Function Documentation
HandleAudioActivation()
override void Oculus.Voice.Bindings.Android.VoiceSDKImplRequest.HandleAudioActivation () protected
Definition at line 44 of file VoiceSDKImplRequest.cs.
        {
            if (Immediately)
            {
                Service.ActivateImmediately(Options);
            }
            else
            {
                Service.Activate(Options);
            }
        }
HandleAudioDeactivation()
override void Oculus.Voice.Bindings.Android.VoiceSDKImplRequest.HandleAudioDeactivation () protected
Definition at line 56 of file VoiceSDKImplRequest.cs.
        {
            Service.Deactivate();
        }
HandleCancel()
override void Oculus.Voice.Bindings.Android.VoiceSDKImplRequest.HandleCancel () protected
Definition at line 69 of file VoiceSDKImplRequest.cs.
        {
            Service.DeactivateAndAbortRequest();
        }
HandleCanceled()
void Oculus.Voice.Bindings.Android.VoiceSDKImplRequest.HandleCanceled ()
Called when an error message has been received.
Definition at line 132 of file VoiceSDKImplRequest.cs.
        {
            HandleCancel();
        }
HandleError()
void Oculus.Voice.Bindings.Android.VoiceSDKImplRequest.HandleError (string error, string message, string errorBody)
Called when an error message has been received.
Definition at line 140 of file VoiceSDKImplRequest.cs.
        {
            HandleFailure($"{error} - {message}");
        }
HandleFullTranscription()
void Oculus.Voice.Bindings.Android.VoiceSDKImplRequest.HandleFullTranscription (string transcription)
Called for final transcription of text.
Definition at line 113 of file VoiceSDKImplRequest.cs.
        {
            ApplyTranscription(transcription, true);
        }
References Meta.WitAi.Requests.VoiceServiceRequest.ApplyTranscription().
HandlePartialResponse()
void Oculus.Voice.Bindings.Android.VoiceSDKImplRequest.HandlePartialResponse (string responseJson)
Callback when in progress response data has been received.
Parameters
responseJson The unparsed json data
Definition at line 96 of file VoiceSDKImplRequest.cs.
        {
            WitResponseNode responseData = WitResponseNode.Parse(responseJson);
            HandlePartialNlpResponse(responseData);
        }
HandlePartialTranscription()
void Oculus.Voice.Bindings.Android.VoiceSDKImplRequest.HandlePartialTranscription (string transcription)
Called for partial transcription of text.
Definition at line 105 of file VoiceSDKImplRequest.cs.
        {
            ApplyTranscription(transcription, false);
        }
References Meta.WitAi.Requests.VoiceServiceRequest.ApplyTranscription().
HandleResponse()
void Oculus.Voice.Bindings.Android.VoiceSDKImplRequest.HandleResponse (string responseJson)
Callback when final response data has been received.
Parameters
responseJson The unparsed json data
Definition at line 149 of file VoiceSDKImplRequest.cs.
        {
            WitResponseNode responseData = WitResponseNode.Parse(responseJson);
            HandleFinalNlpResponse(responseData, null);
        }
HandleSend()
override void Oculus.Voice.Bindings.Android.VoiceSDKImplRequest.HandleSend () protected
Definition at line 61 of file VoiceSDKImplRequest.cs.
        {
            if (InputType == NLPRequestInputType.Text)
            {
                Service.Activate(Options.Text, Options);
            }
        }
HandleStartListening()
void Oculus.Voice.Bindings.Android.VoiceSDKImplRequest.HandleStartListening ()
Called audio is now listening.
Definition at line 79 of file VoiceSDKImplRequest.cs.
        {
            SetAudioInputState(VoiceAudioInputState.On);
        }
HandleStopListening()
void Oculus.Voice.Bindings.Android.VoiceSDKImplRequest.HandleStopListening ()
Called audio is no longer listening.
Definition at line 87 of file VoiceSDKImplRequest.cs.
        {
            SetAudioInputState(VoiceAudioInputState.Off);
        }
HandleTransmissionBegan()
void Oculus.Voice.Bindings.Android.VoiceSDKImplRequest.HandleTransmissionBegan ()
Transmission began.
Definition at line 121 of file VoiceSDKImplRequest.cs.
        {
            if (InputType == NLPRequestInputType.Audio)
            {
                Send();
            }
        }
References Meta.Voice.NLPRequest< VoiceServiceRequestEvent, WitRequestOptions, VoiceServiceRequestEvents, VoiceServiceRequestResults >.InputType, and Meta.Voice.NLPRequest< VoiceServiceRequestEvent, WitRequestOptions, VoiceServiceRequestEvents, VoiceServiceRequestResults >.Send().
Property Documentation
Immediately
bool Oculus.Voice.Bindings.Android.VoiceSDKImplRequest.Immediately get private set
Definition at line 34 of file VoiceSDKImplRequest.cs.
{ get; private set; }
Service
VoiceSDKBinding Oculus.Voice.Bindings.Android.VoiceSDKImplRequest.Service get private set
Definition at line 33 of file VoiceSDKImplRequest.cs.
{ get; private set; }
The documentation for this class was generated from the following file:
Assets/Oculus/Voice/Scripts/Runtime/Bindings/Android/VoiceSDKImplRequest.cs