VR_Test: Meta.Voice.Samples.TTSVoices.SimpleDropdownList Class Reference
Meta.Voice.Samples.TTSVoices.SimpleDropdownList Class Reference
A dropdown ui interface that uses 'UnityEngine.Text' labels and builds content via a load method that accepts a list of strings.
Public Member Functions
void LoadDropdown (string[] newOptions)
Load dropdown with specified options.
void SelectOption (int newIndex)
Select an item in the dropdown list.
void SelectOption (string option)
Select option by name.
int GetOptionIndex (string option)
A method for obtaining the index of a dropdown option string.
void SetShowing (bool toShowing)
Show or hide the popup.
Public Attributes
string DropdownToggleUnselectedText = "..."
Protected Member Functions
virtual void Awake ()
On awake, find dropdown cell.
virtual void Start ()
Perform dropdown setup methods.
virtual void OnEnable ()
Add toggle delegate.
virtual void OnDisable ()
Remove toggle delegate.
virtual void LoadCell (Toggle cell, int index, string option, ref float y)
Load a specific cell.
Properties
string[] Options [get]
int SelectedOptionIndex [get]
string SelectedOption [get]
SimpleDropdownIndexEvent OnIndexSelected [get]
SimpleDropdownOptionEvent OnOptionSelected [get]
bool IsShowing [get, private set]
Whether the popup is currently showing or not.
Private Member Functions
void FindCellPrefab ()
void OnCellClick (int index, bool toSelected)
When a cell is clicked, select a specific option.
void OnToggleClick (bool toToggle)
Called when toggle button is clicked.
Private Attributes
Toggle _dropdownToggle
Transform _dropdownButtonArrowImage
CanvasGroup _dropdownListPopup
ScrollRect _dropdownListScrollRect
Toggle _dropdownListCellPrefab
float _dropdownCellTextPadding = 2f
string[] _options
int _selectedOptionIndex = -1
SimpleDropdownIndexEvent _onIndexSelected = new SimpleDropdownIndexEvent()
SimpleDropdownOptionEvent _onOptionSelected = new SimpleDropdownOptionEvent()
List< Toggle > _cells = new List<Toggle>()
Detailed Description
A dropdown ui interface that uses 'UnityEngine.Text' labels and builds content via a load method that accepts a list of strings.
Definition at line 24 of file SimpleDropdownList.cs.
Member Function Documentation
Awake()
virtual void Meta.Voice.Samples.TTSVoices.SimpleDropdownList.Awake () protected virtual
On awake, find dropdown cell.
Definition at line 85 of file SimpleDropdownList.cs.
        {
            FindCellPrefab();
        }
FindCellPrefab()
void Meta.Voice.Samples.TTSVoices.SimpleDropdownList.FindCellPrefab () private
Definition at line 91 of file SimpleDropdownList.cs.
        {
            if (_dropdownListCellPrefab == null)
            {
                _dropdownListCellPrefab = _dropdownListScrollRect.content.GetComponentInChildren<Toggle>();
                if (_dropdownListCellPrefab != null)
                {
                    _dropdownListCellPrefab.gameObject.SetActive(false);
                }
                else
                {
                    Debug.LogError("No Dropdown Cell Prefab Found");
                }
            }
        }
GetOptionIndex()
int Meta.Voice.Samples.TTSVoices.SimpleDropdownList.GetOptionIndex (string option)
A method for obtaining the index of a dropdown option string.
Parameters
option Accepts an option text string that matches a loaded text option.
Returns
Returns the index of the provided option string
Definition at line 344 of file SimpleDropdownList.cs.
        {
            if (_options != null)
            {
                for (int o = 0; o < _options.Length; o++)
                {
                    if (string.Equals(_options[o], option))
                    {
                        return o;
                    }
                }
            }
            return -1;
        }
LoadCell()
virtual void Meta.Voice.Samples.TTSVoices.SimpleDropdownList.LoadCell (Toggle cell, int index, string option, ref float y) protected virtual
Load a specific cell.
Parameters
index Cell index
Returns
Height of cell
Definition at line 235 of file SimpleDropdownList.cs.
        {
            // Apply name to cell
            Text cellText = cell.GetComponentInChildren<Text>();
            if (cellText != null)
            {
                cellText.text = option;
            }
            // Apply callback to cell
            cell.onValueChanged.RemoveAllListeners();
            cell.isOn = false;
            cell.onValueChanged.AddListener((isSelected) => OnCellClick(index, isSelected));
            // Apply width to cell
            RectTransform cellRect = cell.GetComponent<RectTransform>();
            cellRect.anchorMin = new Vector2(0f, 1f);
            cellRect.anchorMax = new Vector2(1f, 1f);
            cellRect.pivot = new Vector2(0.5f, 1f);
            cellRect.SetSizeWithCurrentAnchors(RectTransform.Axis.Horizontal, _dropdownListScrollRect.content.rect.width);
            cellRect.anchoredPosition = new Vector2(0f, -y);
            // Apply height
            float height = cellRect.rect.height;
            if (cellText != null)
            {
                float textMargin = Mathf.Max(0f, height - cellText.rectTransform.rect.height);
                height = Mathf.CeilToInt(cellText.preferredHeight + _dropdownCellTextPadding + textMargin);
                cellRect.SetSizeWithCurrentAnchors(RectTransform.Axis.Vertical, height);
            }
            // Add new height
            y += height;
        }
References Meta.Voice.Samples.TTSVoices.SimpleDropdownList.OnCellClick().
LoadDropdown()
void Meta.Voice.Samples.TTSVoices.SimpleDropdownList.LoadDropdown (string[] newOptions)
Load dropdown with specified options.
Parameters
newOptions The options to be used
Definition at line 175 of file SimpleDropdownList.cs.
        {
            // Get options
            _options = newOptions;
            // Disable all previous cells
            foreach (var cell in _cells)
            {
                cell.gameObject.SetActive(false);
            }
            // Setup if needed, or log error
            FindCellPrefab();
            if (_dropdownListCellPrefab == null)
            {
                VLog.W($"Cannot load {gameObject.name} without a cell prefab");
                return;
            }
            // Iterate all options
            float height = 0f;
            int total = _options == null ? 0 : _options.Length;
            for (int c = 0; c < total; c++)
            {
                // Get existing cell if possible
                Toggle cell = c < _cells.Count ? _cells[c] : null;
                // Instantiate if needed
                if (cell == null)
                {
                    // Instantiate
                    cell = Instantiate(_dropdownListCellPrefab.gameObject).GetComponent<Toggle>();
                    cell.name = $"{_dropdownListCellPrefab.gameObject.name}_CELL_{c:000}";
                    cell.transform.SetParent(_dropdownListScrollRect.content, false);
                    // Override cell
                    if (c < _cells.Count)
                    {
                        _cells[c] = cell;
                    }
                    // Add new cell
                    else
                    {
                        _cells.Add(cell);
                    }
                }
                // Enable & load
                cell.gameObject.SetActive(true);
                LoadCell(cell, c, _options[c], ref height);
            }
            // Set height to content of scrolldown list
            _dropdownListScrollRect.content.SetInsetAndSizeFromParentEdge(RectTransform.Edge.Top, 0f, height);
        }
References Meta.Voice.Samples.TTSVoices.SimpleDropdownList.LoadCell(), and Meta.WitAi.VLog.W().
OnCellClick()
void Meta.Voice.Samples.TTSVoices.SimpleDropdownList.OnCellClick (int index, bool toSelected) private
When a cell is clicked, select a specific option.
Parameters
index Cell index clicked
toSelected Whether cell was selected or unselected
Definition at line 332 of file SimpleDropdownList.cs.
        {
            if (toSelected && index != SelectedOptionIndex)
            {
                SelectOption(index);
            }
        }
References Meta.Voice.Samples.TTSVoices.SimpleDropdownList.SelectOption().
OnDisable()
virtual void Meta.Voice.Samples.TTSVoices.SimpleDropdownList.OnDisable () protected virtual
Remove toggle delegate.
Definition at line 135 of file SimpleDropdownList.cs.
        {
            _dropdownToggle.onValueChanged.RemoveListener(OnToggleClick);
        }
References Meta.Voice.Samples.TTSVoices.SimpleDropdownList.OnToggleClick().
OnEnable()
virtual void Meta.Voice.Samples.TTSVoices.SimpleDropdownList.OnEnable () protected virtual
Add toggle delegate.
Definition at line 128 of file SimpleDropdownList.cs.
        {
            _dropdownToggle.onValueChanged.AddListener(OnToggleClick);
        }
References Meta.Voice.Samples.TTSVoices.SimpleDropdownList.OnToggleClick().
OnToggleClick()
void Meta.Voice.Samples.TTSVoices.SimpleDropdownList.OnToggleClick (bool toToggle) private
Called when toggle button is clicked.
Definition at line 388 of file SimpleDropdownList.cs.
        {
            if (toToggle != IsShowing)
            {
                SetShowing(toToggle);
            }
        }
References Meta.Voice.Samples.TTSVoices.SimpleDropdownList.IsShowing, and Meta.Voice.Samples.TTSVoices.SimpleDropdownList.SetShowing().
SelectOption() [1/2]
void Meta.Voice.Samples.TTSVoices.SimpleDropdownList.SelectOption (int newIndex)
Select an item in the dropdown list.
Parameters
newIndex The option index to be selected
Definition at line 276 of file SimpleDropdownList.cs.
        {
            // Ignore if same
            if (newIndex == SelectedOptionIndex)
            {
                return;
            }
            // Apply new index
            _selectedOptionIndex = newIndex;
            // Get option text
            string optionText = SelectedOption;
            // Apply to button
            Text buttonText = _dropdownToggle.GetComponentInChildren<Text>();
            if (buttonText != null)
            {
                if (string.IsNullOrEmpty(optionText))
                {
                    buttonText.text = DropdownToggleUnselectedText;
                }
                else
                {
                    buttonText.text = optionText;
                }
            }
            // Adjust cells
            int total = _cells == null ? 0 : _cells.Count;
            for (int i = 0; i < total; i++)
            {
                _cells[i].isOn = i == SelectedOptionIndex;
                _cells[i].interactable = i != SelectedOptionIndex;
            }
            // Call event
            OnOptionSelected?.Invoke(optionText);
            OnIndexSelected?.Invoke(SelectedOptionIndex);
            // Selected
            if (IsShowing)
            {
                SetShowing(false);
            }
        }
References Meta.Voice.Samples.TTSVoices.SimpleDropdownList.IsShowing, and Meta.Voice.Samples.TTSVoices.SimpleDropdownList.SetShowing().
SelectOption() [2/2]
void Meta.Voice.Samples.TTSVoices.SimpleDropdownList.SelectOption (string option)
Select option by name.
Parameters
option The option to be selected
SetShowing()
void Meta.Voice.Samples.TTSVoices.SimpleDropdownList.SetShowing (bool toShowing)
Show or hide the popup.
Parameters
toShowing The option index to be selected
Definition at line 365 of file SimpleDropdownList.cs.
        {
            if (toShowing && (Options == null || Options.Length <= 0))
            {
                Debug.Log("SimpleDropdownList - Cannot show without any options");
                return;
            }
            IsShowing = toShowing;
            _dropdownToggle.isOn = IsShowing;
            if (_dropdownListPopup != null)
            {
                _dropdownListPopup.alpha = toShowing ? 1f : 0f;
                _dropdownListPopup.interactable = toShowing;
                _dropdownListPopup.blocksRaycasts = toShowing;
            }
            if (_dropdownButtonArrowImage != null)
            {
                _dropdownButtonArrowImage.localRotation = Quaternion.Euler(0f, 0f, IsShowing ? 0f : 180f);
            }
        }
References Meta.Voice.Samples.TTSVoices.SimpleDropdownList.IsShowing.
Start()
virtual void Meta.Voice.Samples.TTSVoices.SimpleDropdownList.Start () protected virtual
Perform dropdown setup methods.
Definition at line 110 of file SimpleDropdownList.cs.
        {
            // Hide
            SetShowing(false);
            // Load dropdown
            if (_options != null && _options.Length > 0)
            {
                LoadDropdown(Options);
            }
            // Force a selection refresh
            int index = _selectedOptionIndex;
            _selectedOptionIndex = index - 1;
            SelectOption(index);
        }
References Meta.Voice.Samples.TTSVoices.SimpleDropdownList.LoadDropdown(), Meta.Voice.Samples.TTSVoices.SimpleDropdownList.SelectOption(), and Meta.Voice.Samples.TTSVoices.SimpleDropdownList.SetShowing().
Member Data Documentation
_cells
List<Toggle> Meta.Voice.Samples.TTSVoices.SimpleDropdownList._cells = new List<Toggle>() private
Definition at line 80 of file SimpleDropdownList.cs.
_dropdownButtonArrowImage
Transform Meta.Voice.Samples.TTSVoices.SimpleDropdownList._dropdownButtonArrowImage private
Definition at line 30 of file SimpleDropdownList.cs.
_dropdownCellTextPadding
float Meta.Voice.Samples.TTSVoices.SimpleDropdownList._dropdownCellTextPadding = 2f private
Definition at line 42 of file SimpleDropdownList.cs.
_dropdownListCellPrefab
Toggle Meta.Voice.Samples.TTSVoices.SimpleDropdownList._dropdownListCellPrefab private
Definition at line 40 of file SimpleDropdownList.cs.
_dropdownListPopup
CanvasGroup Meta.Voice.Samples.TTSVoices.SimpleDropdownList._dropdownListPopup private
Definition at line 36 of file SimpleDropdownList.cs.
_dropdownListScrollRect
ScrollRect Meta.Voice.Samples.TTSVoices.SimpleDropdownList._dropdownListScrollRect private
Definition at line 38 of file SimpleDropdownList.cs.
_dropdownToggle
Toggle Meta.Voice.Samples.TTSVoices.SimpleDropdownList._dropdownToggle private
Definition at line 28 of file SimpleDropdownList.cs.
_onIndexSelected
SimpleDropdownIndexEvent Meta.Voice.Samples.TTSVoices.SimpleDropdownList._onIndexSelected = new SimpleDropdownIndexEvent() private
Definition at line 67 of file SimpleDropdownList.cs.
_onOptionSelected
SimpleDropdownOptionEvent Meta.Voice.Samples.TTSVoices.SimpleDropdownList._onOptionSelected = new SimpleDropdownOptionEvent() private
Definition at line 71 of file SimpleDropdownList.cs.
_options
string [] Meta.Voice.Samples.TTSVoices.SimpleDropdownList._options private
Definition at line 45 of file SimpleDropdownList.cs.
_selectedOptionIndex
int Meta.Voice.Samples.TTSVoices.SimpleDropdownList._selectedOptionIndex = -1 private
Definition at line 50 of file SimpleDropdownList.cs.
DropdownToggleUnselectedText
string Meta.Voice.Samples.TTSVoices.SimpleDropdownList.DropdownToggleUnselectedText = "..."
Definition at line 32 of file SimpleDropdownList.cs.
Property Documentation
IsShowing
bool Meta.Voice.Samples.TTSVoices.SimpleDropdownList.IsShowing get private set
Whether the popup is currently showing or not.
Definition at line 77 of file SimpleDropdownList.cs.
{ get; private set; }
OnIndexSelected
SimpleDropdownIndexEvent Meta.Voice.Samples.TTSVoices.SimpleDropdownList.OnIndexSelected get
Definition at line 68 of file SimpleDropdownList.cs.
OnOptionSelected
SimpleDropdownOptionEvent Meta.Voice.Samples.TTSVoices.SimpleDropdownList.OnOptionSelected get
Definition at line 72 of file SimpleDropdownList.cs.
Options
string [] Meta.Voice.Samples.TTSVoices.SimpleDropdownList.Options get
Definition at line 46 of file SimpleDropdownList.cs.
SelectedOption
string Meta.Voice.Samples.TTSVoices.SimpleDropdownList.SelectedOption get
Definition at line 54 of file SimpleDropdownList.cs.
        {
            get
            {
                if (_options != null && SelectedOptionIndex >= 0 && SelectedOptionIndex < _options.Length)
                {
                    return _options[SelectedOptionIndex];
                }
                return null;
            }
        }
SelectedOptionIndex
int Meta.Voice.Samples.TTSVoices.SimpleDropdownList.SelectedOptionIndex get
Definition at line 51 of file SimpleDropdownList.cs.
The documentation for this class was generated from the following file:
Assets/Oculus/Voice/Samples/TTSVoices/Scripts/SimpleDropdownList.cs