VR_Test: ONSPReflectionZone Class Reference
ONSPReflectionZone Class Reference
Public Attributes
AudioMixerSnapshot mixerSnapshot = null
float fadeTime = 0.0f
Private Member Functions
void Start ()
Start this instance.
void Update ()
Update this instance.
void OnTriggerEnter (Collider other)
Raises the trigger enter event.
void OnTriggerExit (Collider other)
Raises the trigger exit event.
bool CheckForAudioListener (GameObject gameObject)
Checks for audio listener.
void PushCurrentMixerShapshot ()
Pushs the current mixer snapshot onto the snapshot stack.
void PopCurrentMixerSnapshot ()
void SetReflectionValues ()
Sets the reflection values. This is done when entering a zone (use zone values).
void SetReflectionValues (ref ReflectionSnapshot mss)
Sets the reflection values. This is done when exiting a zone (use popped values).
Static Private Attributes
static Stack< ReflectionSnapshot > snapshotList = new Stack<ReflectionSnapshot>()
static ReflectionSnapshot currentSnapshot = new ReflectionSnapshot()
Detailed Description
Definition at line 37 of file ONSPReflectionZone.cs.
Member Function Documentation
CheckForAudioListener()
bool ONSPReflectionZone.CheckForAudioListener (GameObject gameObject) private
Checks for audio listener.
Returns
true, if for audio listener was checked, false otherwise.
Parameters
gameObject Game object.
Definition at line 93 of file ONSPReflectionZone.cs.
    {
        AudioListener al = gameObject.GetComponentInChildren<AudioListener>();
        if(al != null)
            return true;
        return false;
    }
OnTriggerEnter()
void ONSPReflectionZone.OnTriggerEnter (Collider other) private
Raises the trigger enter event.
Parameters
other Other.
Definition at line 64 of file ONSPReflectionZone.cs.
    {
        if(CheckForAudioListener(other.gameObject) == true)
        {
            PushCurrentMixerShapshot();
        }
    }
References CheckForAudioListener(), and PushCurrentMixerShapshot().
OnTriggerExit()
void ONSPReflectionZone.OnTriggerExit (Collider other) private
Raises the trigger exit event.
Parameters
other Other.
Definition at line 76 of file ONSPReflectionZone.cs.
    {
        if(CheckForAudioListener(other.gameObject) == true)
        {
            PopCurrentMixerSnapshot();
        }
    }
References CheckForAudioListener(), and PopCurrentMixerSnapshot().
PopCurrentMixerSnapshot()
void ONSPReflectionZone.PopCurrentMixerSnapshot () private
Pops the current reflection values from reflectionsList stack.
Definition at line 120 of file ONSPReflectionZone.cs.
    {
        ReflectionSnapshot snapshot = snapshotList.Pop();
        // Set the popped reflection values
        SetReflectionValues(ref snapshot);
    }
References SetReflectionValues().
PushCurrentMixerShapshot()
void ONSPReflectionZone.PushCurrentMixerShapshot () private
Pushs the current mixer snapshot onto the snapshot stack.
Definition at line 105 of file ONSPReflectionZone.cs.
    {
        ReflectionSnapshot css = currentSnapshot;
        snapshotList.Push(css);
        // Set the zone reflection values
        // NOTE: There will be conditions that might need resolution when dealing with volumes that
        // overlap. Best practice is to never have volumes half-way inside other volumes; larger
        // volumes should completely contain smaller volumes
        SetReflectionValues();
    }
References SetReflectionValues().
SetReflectionValues() [1/2]
void ONSPReflectionZone.SetReflectionValues () private
Sets the reflection values. This is done when entering a zone (use zone values).
Definition at line 131 of file ONSPReflectionZone.cs.
    {
        if (mixerSnapshot != null)
        {
            Debug.Log("Setting off snapshot " + mixerSnapshot.name);
            mixerSnapshot.TransitionTo(fadeTime);
            // Set the current snapshot to be equal to this one
            currentSnapshot.mixerSnapshot = mixerSnapshot;
            currentSnapshot.fadeTime      = fadeTime;
        }
        else
        {
            Debug.Log("Mixer snapshot not set - Please ensure play area has at least one encompassing snapshot.");
        }
    }
SetReflectionValues() [2/2]
void ONSPReflectionZone.SetReflectionValues (ref ReflectionSnapshot mss) private
Sets the reflection values. This is done when exiting a zone (use popped values).
Parameters
rm Rm.
Definition at line 152 of file ONSPReflectionZone.cs.
    {
        if(mss.mixerSnapshot != null)
        {
            Debug.Log("Setting off snapshot " + mss.mixerSnapshot.name);
            mss.mixerSnapshot.TransitionTo(mss.fadeTime);
            // Set the current snapshot to be equal to this one
            currentSnapshot.mixerSnapshot = mss.mixerSnapshot;
            currentSnapshot.fadeTime = mss.fadeTime;
        }
        else
        {
            Debug.Log("Mixer snapshot not set - Please ensure play area has at least one encompassing snapshot.");
        }
    }
Start()
void ONSPReflectionZone.Start () private
Start this instance.
Definition at line 49 of file ONSPReflectionZone.cs.
    {
    }
Update()
void ONSPReflectionZone.Update () private
Update this instance.
Definition at line 56 of file ONSPReflectionZone.cs.
    {
    }
Member Data Documentation
currentSnapshot
ReflectionSnapshot ONSPReflectionZone.currentSnapshot = new ReflectionSnapshot() static private
Definition at line 44 of file ONSPReflectionZone.cs.
fadeTime
float ONSPReflectionZone.fadeTime = 0.0f
Definition at line 40 of file ONSPReflectionZone.cs.
mixerSnapshot
AudioMixerSnapshot ONSPReflectionZone.mixerSnapshot = null
Definition at line 39 of file ONSPReflectionZone.cs.
snapshotList
Stack<ReflectionSnapshot> ONSPReflectionZone.snapshotList = new Stack<ReflectionSnapshot>() static private
Definition at line 43 of file ONSPReflectionZone.cs.
The documentation for this class was generated from the following file:
Assets/Oculus/Spatializer/scripts/helpers/ONSPReflectionZone.cs