VR_Test: OculusSampleFramework.OVROverlaySample Class Reference
OculusSampleFramework.OVROverlaySample Class Reference
Usage: demonstrate how to use overlay layers for a paneled UI system On Mobile, we support both Cylinder layer and Quad layer Press any button: it will cycle [world geometry Quad]->[overlay layer Quad]->[world geometry cylinder]->[overlay layer cylinder] On PC, only Quad layer is supported Press any button: it will cycle [world geometry Quad]->[overlay layer Quad].
Public Member Functions
void RadioPressed (string radioLabel, string group, Toggle t)
Usage: radio button handler.
Public Attributes
GameObject mainCamera
The main camera used to calculate reprojected OVROverlay quad.
GameObject uiCamera
The camera used to render UI panels.
GameObject uiGeoParent
The parents of grouped UI panels.
GameObject worldspaceGeoParent
OVROverlay cameraRenderOverlay
The OVROverlay component to pass the uiCamera rendered RT to.
OVROverlay renderingLabelOverlay
The OVROverlay component displaying which rendering mode is active.
Texture applicationLabelTexture
The quad textures to indicate the active rendering method.
Texture compositorLabelTexture
GameObject prefabForLevelLoadSim
The resources & settings needed for the level loading simulation demo.
OVROverlay cubemapOverlay
OVROverlay loadingTextQuadOverlay
float distanceFromCamToLoadText
float cubeSpawnRadius
float heightBetweenItems
int numObjectsPerLevel
int numLevels
int numLoopsTrigger = 500000000
Private Member Functions
void Start ()
void Update ()
void ActivateWorldGeo ()
Usage: Activate the world geometry and deactivate OVROverlay display.
void ActivateOVROverlay ()
Usage: Activate OVROverlay display and deactivate the world geometry.
void ActivateNone ()
Usage: Deactivate both world geometry and OVROverlay display.
void TriggerLoad ()
This function is to simulate a level load event in Unity The idea is to enable a cubemap overlay right before any action that will stall the main thread This cubemap overlay can be combined with other OVROverlay objects, such as animated textures to indicate "Loading...".
IEnumerator WaitforOVROverlay ()
void TriggerUnload ()
Usage: Destroy all loaded resources and switch back to world geometry rendering mode.
void CameraAndRenderTargetSetup ()
Usage: Recreate UI render target according overlay type and overlay size.
void SimulateLevelLoad ()
Usage: block main thread with an empty for loop and generate a bunch of cubes around the player.
void ClearObjects ()
Usage: destroy all created cubes and garbage collect.
Private Attributes
bool inMenu
Toggle applicationRadioButton
Toggle references.
Toggle noneRadioButton
List< GameObject > spawnedCubes = new List<GameObject>()
Static Private Attributes
const string ovrOverlayID = "OVROverlayID"
The string identifiers for DebugUI radio buttons.
const string applicationID = "ApplicationID"
const string noneID = "NoneID"
Detailed Description
Usage: demonstrate how to use overlay layers for a paneled UI system On Mobile, we support both Cylinder layer and Quad layer Press any button: it will cycle [world geometry Quad]->[overlay layer Quad]->[world geometry cylinder]->[overlay layer cylinder] On PC, only Quad layer is supported Press any button: it will cycle [world geometry Quad]->[overlay layer Quad].
You should be able to observe sharper and less aliased image when switch from world geometry to overlay layer.
Definition at line 50 of file OVROverlaySample.cs.
Member Function Documentation
ActivateNone()
void OculusSampleFramework.OVROverlaySample.ActivateNone () private
Usage: Deactivate both world geometry and OVROverlay display.
Definition at line 202 of file OVROverlaySample.cs.
        {
            worldspaceGeoParent.SetActive(false);
            uiCamera.SetActive(false);
            cameraRenderOverlay.enabled = false;
            uiGeoParent.SetActive(false);
            renderingLabelOverlay.enabled = false;
            Debug.Log("Switched to ActivateNone");
        }
References OculusSampleFramework.OVROverlaySample.uiCamera, and OculusSampleFramework.OVROverlaySample.uiGeoParent.
ActivateOVROverlay()
void OculusSampleFramework.OVROverlaySample.ActivateOVROverlay () private
Usage: Activate OVROverlay display and deactivate the world geometry.
Definition at line 188 of file OVROverlaySample.cs.
        {
            worldspaceGeoParent.SetActive(false);
            uiCamera.SetActive(true);
            cameraRenderOverlay.enabled = true;
            uiGeoParent.SetActive(true);
            renderingLabelOverlay.enabled = true;
            renderingLabelOverlay.textures[0] = compositorLabelTexture;
            Debug.Log("Switched to ActivateOVROVerlay");
        }
References OculusSampleFramework.OVROverlaySample.renderingLabelOverlay, OVROverlay.textures, OculusSampleFramework.OVROverlaySample.uiCamera, and OculusSampleFramework.OVROverlaySample.uiGeoParent.
ActivateWorldGeo()
void OculusSampleFramework.OVROverlaySample.ActivateWorldGeo () private
Usage: Activate the world geometry and deactivate OVROverlay display.
Definition at line 174 of file OVROverlaySample.cs.
        {
            worldspaceGeoParent.SetActive(true);
            uiGeoParent.SetActive(false);
            uiCamera.SetActive(false);
            cameraRenderOverlay.enabled = false;
            renderingLabelOverlay.enabled = true;
            renderingLabelOverlay.textures[0] = applicationLabelTexture;
            Debug.Log("Switched to ActivateWorldGeo");
        }
References OculusSampleFramework.OVROverlaySample.applicationLabelTexture, OculusSampleFramework.OVROverlaySample.renderingLabelOverlay, OVROverlay.textures, OculusSampleFramework.OVROverlaySample.uiCamera, and OculusSampleFramework.OVROverlaySample.uiGeoParent.
CameraAndRenderTargetSetup()
void OculusSampleFramework.OVROverlaySample.CameraAndRenderTargetSetup () private
Usage: Recreate UI render target according overlay type and overlay size.
Definition at line 254 of file OVROverlaySample.cs.
        {
            float overlayWidth = cameraRenderOverlay.transform.localScale.x;
            float overlayHeight = cameraRenderOverlay.transform.localScale.y;
            float overlayRadius = cameraRenderOverlay.transform.localScale.z;
#if UNITY_ANDROID
            // Gear VR display panel resolution
            float hmdPanelResWidth = 2560;
            float hmdPanelResHeight = 1440;
#else
            // Rift display panel resolution
            float hmdPanelResWidth = 2160;
            float hmdPanelResHeight = 1200;
#endif
            float singleEyeScreenPhysicalResX = hmdPanelResWidth * 0.5f;
            float singleEyeScreenPhysicalResY = hmdPanelResHeight;
            // Calculate RT Height
            // screenSizeYInWorld : how much world unity the full screen can cover at overlayQuad's location vertically
            // pixelDensityY: pixels / world unit ( meter )
            float halfFovY = mainCamera.GetComponent<Camera>().fieldOfView / 2;
            float screenSizeYInWorld = 2 * overlayRadius * Mathf.Tan(Mathf.Deg2Rad * halfFovY);
            float pixelDensityYPerWorldUnit = singleEyeScreenPhysicalResY / screenSizeYInWorld;
            float renderTargetHeight = pixelDensityYPerWorldUnit * overlayWidth;
            // Calculate RT width
            float renderTargetWidth = 0.0f;
            // screenSizeXInWorld : how much world unity the full screen can cover at overlayQuad's location horizontally
            // pixelDensityY: pixels / world unit ( meter )
            float screenSizeXInWorld = screenSizeYInWorld * mainCamera.GetComponent<Camera>().aspect;
            float pixelDensityXPerWorldUnit = singleEyeScreenPhysicalResX / screenSizeXInWorld;
            renderTargetWidth = pixelDensityXPerWorldUnit * overlayWidth;
            // Compute the orthographic size for the camera
            float orthographicSize = overlayHeight / 2.0f;
            float orthoCameraAspect = overlayWidth / overlayHeight;
            uiCamera.GetComponent<Camera>().orthographicSize = orthographicSize;
            uiCamera.GetComponent<Camera>().aspect = orthoCameraAspect;
            if (uiCamera.GetComponent<Camera>().targetTexture != null)
                uiCamera.GetComponent<Camera>().targetTexture.Release();
            RenderTexture overlayRT = new RenderTexture(
                (int)renderTargetWidth * 2,
                (int)renderTargetHeight * 2,
                0,
                RenderTextureFormat.ARGB32,
                RenderTextureReadWrite.sRGB);
            Debug.Log("Created RT of resolution w: " + renderTargetWidth + " and h: " + renderTargetHeight);
            overlayRT.hideFlags = HideFlags.DontSave;
            overlayRT.useMipMap = true;
            overlayRT.filterMode = FilterMode.Trilinear;
            overlayRT.anisoLevel = 4;
#if UNITY_5_5_OR_NEWER
            overlayRT.autoGenerateMips = true;
#else
        overlayRT.generateMips = true;
#endif
            uiCamera.GetComponent<Camera>().targetTexture = overlayRT;
            cameraRenderOverlay.textures[0] = overlayRT;
        }
References OculusSampleFramework.OVROverlaySample.cameraRenderOverlay, OculusSampleFramework.OVROverlaySample.mainCamera, OVROverlay.textures, and OculusSampleFramework.OVROverlaySample.uiCamera.
ClearObjects()
void OculusSampleFramework.OVROverlaySample.ClearObjects () private
Usage: destroy all created cubes and garbage collect.
Definition at line 362 of file OVROverlaySample.cs.
        {
            for (int i = 0; i < spawnedCubes.Count; i++)
            {
                DestroyImmediate(spawnedCubes[i]);
            }
            spawnedCubes.Clear();
            GC.Collect();
        }
RadioPressed()
void OculusSampleFramework.OVROverlaySample.RadioPressed (string radioLabel, string group, Toggle t)
Usage: radio button handler.
Definition at line 380 of file OVROverlaySample.cs.
        {
            if (string.Compare(radioLabel, ovrOverlayID) == 0)
            {
                ActivateOVROverlay();
            }
            else if (string.Compare(radioLabel, applicationID) == 0)
            {
                ActivateWorldGeo();
            }
            else if (string.Compare(radioLabel, noneID) == 0)
            {
                ActivateNone();
            }
        }
References OculusSampleFramework.OVROverlaySample.ActivateNone(), OculusSampleFramework.OVROverlaySample.ActivateOVROverlay(), OculusSampleFramework.OVROverlaySample.ActivateWorldGeo(), and OculusSampleFramework.OVROverlaySample.ovrOverlayID.
SimulateLevelLoad()
void OculusSampleFramework.OVROverlaySample.SimulateLevelLoad () private
Usage: block main thread with an empty for loop and generate a bunch of cubes around the player.
Definition at line 327 of file OVROverlaySample.cs.
        {
            int numToPrint = 0;
            for (int p = 0; p < numLoopsTrigger; p++)
            {
                numToPrint++;
            }
            Debug.Log("Finished " + numToPrint + " Loops");
            Vector3 playerPos = mainCamera.transform.position;
            playerPos.y = 0.5f;
            // Generate a bunch of blocks, "blocking" the mainthread ;)
            for (int j = 0; j < numLevels; j++)
            {
                for (var i = 0; i < numObjectsPerLevel; i++)
                {
                    var angle = i * Mathf.PI * 2 / numObjectsPerLevel;
                    float stagger = (i % 2 == 0) ? 1.5f : 1.0f;
                    var pos = new Vector3(Mathf.Cos(angle), 0, Mathf.Sin(angle)) * cubeSpawnRadius * stagger;
                    pos.y = j * heightBetweenItems;
                    var newInst = Instantiate(prefabForLevelLoadSim, pos + playerPos, Quaternion.identity);
                    var newObjTransform = newInst.transform;
                    newObjTransform.LookAt(playerPos);
                    Vector3 newAngle = newObjTransform.rotation.eulerAngles;
                    newAngle.x = 0.0f;
                    newObjTransform.rotation = Quaternion.Euler(newAngle);
                    spawnedCubes.Add(newInst);
                }
            }
        }
References OculusSampleFramework.OVROverlaySample.mainCamera, and OculusSampleFramework.OVROverlaySample.prefabForLevelLoadSim.
Start()
void OculusSampleFramework.OVROverlaySample.Start () private
Definition at line 122 of file OVROverlaySample.cs.
        {
            DebugUIBuilder.instance.AddLabel("OVROverlay Sample");
            DebugUIBuilder.instance.AddDivider();
            DebugUIBuilder.instance.AddLabel("Level Loading Example");
            DebugUIBuilder.instance.AddButton("Simulate Level Load", TriggerLoad);
            DebugUIBuilder.instance.AddButton("Destroy Cubes", TriggerUnload);
            DebugUIBuilder.instance.AddDivider();
            DebugUIBuilder.instance.AddLabel("OVROverlay vs. Application Render Comparison");
            DebugUIBuilder.instance
                .AddRadio("OVROverlay", "group", delegate(Toggle t) { RadioPressed(ovrOverlayID, "group", t); })
                .GetComponentInChildren<Toggle>();
            applicationRadioButton = DebugUIBuilder.instance
                .AddRadio("Application", "group", delegate(Toggle t) { RadioPressed(applicationID, "group", t); })
                .GetComponentInChildren<Toggle>();
            noneRadioButton = DebugUIBuilder.instance
                .AddRadio("None", "group", delegate(Toggle t) { RadioPressed(noneID, "group", t); })
                .GetComponentInChildren<Toggle>();
            DebugUIBuilder.instance.Show();
            // Start with Overlay Quad
            CameraAndRenderTargetSetup();
            cameraRenderOverlay.enabled = true;
            cameraRenderOverlay.currentOverlayShape = OVROverlay.OverlayShape.Quad;
            spawnedCubes.Capacity = numObjectsPerLevel * numLevels;
        }
TriggerLoad()
void OculusSampleFramework.OVROverlaySample.TriggerLoad () private
This function is to simulate a level load event in Unity The idea is to enable a cubemap overlay right before any action that will stall the main thread This cubemap overlay can be combined with other OVROverlay objects, such as animated textures to indicate "Loading...".
Definition at line 218 of file OVROverlaySample.cs.
        {
            StartCoroutine(WaitforOVROverlay());
        }
TriggerUnload()
void OculusSampleFramework.OVROverlaySample.TriggerUnload () private
Usage: Destroy all loaded resources and switch back to world geometry rendering mode.
Definition at line 245 of file OVROverlaySample.cs.
        {
            ClearObjects();
            applicationRadioButton.isOn = true;
        }
References OculusSampleFramework.OVROverlaySample.ClearObjects().
Update()
void OculusSampleFramework.OVROverlaySample.Update () private
Definition at line 150 of file OVROverlaySample.cs.
        {
            // Switch ui display types
            if (OVRInput.GetDown(OVRInput.Button.Two) || OVRInput.GetDown(OVRInput.Button.Start))
            {
                if (inMenu) DebugUIBuilder.instance.Hide();
                else DebugUIBuilder.instance.Show();
                inMenu = !inMenu;
            }
            // Trigger loading simulator via keyboard
            if (Input.GetKeyDown(KeyCode.A))
            {
                TriggerLoad();
            }
        }
WaitforOVROverlay()
IEnumerator OculusSampleFramework.OVROverlaySample.WaitforOVROverlay () private
Definition at line 223 of file OVROverlaySample.cs.
        {
            Transform camTransform = mainCamera.transform;
            Transform uiTextOverlayTrasnform = loadingTextQuadOverlay.transform;
            Vector3 newPos = camTransform.position + camTransform.forward * distanceFromCamToLoadText;
            newPos.y = camTransform.position.y;
            uiTextOverlayTrasnform.position = newPos;
            cubemapOverlay.enabled = true;
            loadingTextQuadOverlay.enabled = true;
            noneRadioButton.isOn = true;
            yield return new WaitForSeconds(0.1f);
            ClearObjects();
            SimulateLevelLoad();
            cubemapOverlay.enabled = false;
            loadingTextQuadOverlay.enabled = false;
            yield return null;
        }
Member Data Documentation
applicationID
const string OculusSampleFramework.OVROverlaySample.applicationID = "ApplicationID" static private
Definition at line 59 of file OVROverlaySample.cs.
applicationLabelTexture
Texture OculusSampleFramework.OVROverlaySample.applicationLabelTexture
The quad textures to indicate the active rendering method.
Definition at line 100 of file OVROverlaySample.cs.
applicationRadioButton
Toggle OculusSampleFramework.OVROverlaySample.applicationRadioButton private
Toggle references.
Definition at line 65 of file OVROverlaySample.cs.
cameraRenderOverlay
OVROverlay OculusSampleFramework.OVROverlaySample.cameraRenderOverlay
The OVROverlay component to pass the uiCamera rendered RT to.
Definition at line 90 of file OVROverlaySample.cs.
compositorLabelTexture
Texture OculusSampleFramework.OVROverlaySample.compositorLabelTexture
Definition at line 102 of file OVROverlaySample.cs.
cubemapOverlay
OVROverlay OculusSampleFramework.OVROverlaySample.cubemapOverlay
Definition at line 110 of file OVROverlaySample.cs.
cubeSpawnRadius
float OculusSampleFramework.OVROverlaySample.cubeSpawnRadius
Definition at line 113 of file OVROverlaySample.cs.
distanceFromCamToLoadText
float OculusSampleFramework.OVROverlaySample.distanceFromCamToLoadText
Definition at line 112 of file OVROverlaySample.cs.
heightBetweenItems
float OculusSampleFramework.OVROverlaySample.heightBetweenItems
Definition at line 114 of file OVROverlaySample.cs.
inMenu
bool OculusSampleFramework.OVROverlaySample.inMenu private
Definition at line 52 of file OVROverlaySample.cs.
loadingTextQuadOverlay
OVROverlay OculusSampleFramework.OVROverlaySample.loadingTextQuadOverlay
Definition at line 111 of file OVROverlaySample.cs.
mainCamera
GameObject OculusSampleFramework.OVROverlaySample.mainCamera
The main camera used to calculate reprojected OVROverlay quad.
Definition at line 73 of file OVROverlaySample.cs.
noneID
const string OculusSampleFramework.OVROverlaySample.noneID = "NoneID" static private
Definition at line 60 of file OVROverlaySample.cs.
noneRadioButton
Toggle OculusSampleFramework.OVROverlaySample.noneRadioButton private
Definition at line 67 of file OVROverlaySample.cs.
numLevels
int OculusSampleFramework.OVROverlaySample.numLevels
Definition at line 116 of file OVROverlaySample.cs.
numLoopsTrigger
int OculusSampleFramework.OVROverlaySample.numLoopsTrigger = 500000000
Definition at line 117 of file OVROverlaySample.cs.
numObjectsPerLevel
int OculusSampleFramework.OVROverlaySample.numObjectsPerLevel
Definition at line 115 of file OVROverlaySample.cs.
ovrOverlayID
const string OculusSampleFramework.OVROverlaySample.ovrOverlayID = "OVROverlayID" static private
The string identifiers for DebugUI radio buttons.
Definition at line 57 of file OVROverlaySample.cs.
prefabForLevelLoadSim
GameObject OculusSampleFramework.OVROverlaySample.prefabForLevelLoadSim
The resources & settings needed for the level loading simulation demo.
Definition at line 108 of file OVROverlaySample.cs.
renderingLabelOverlay
OVROverlay OculusSampleFramework.OVROverlaySample.renderingLabelOverlay
The OVROverlay component displaying which rendering mode is active.
Definition at line 95 of file OVROverlaySample.cs.
spawnedCubes
List<GameObject> OculusSampleFramework.OVROverlaySample.spawnedCubes = new List<GameObject>() private
Definition at line 118 of file OVROverlaySample.cs.
uiCamera
GameObject OculusSampleFramework.OVROverlaySample.uiCamera
The camera used to render UI panels.
Definition at line 78 of file OVROverlaySample.cs.
uiGeoParent
GameObject OculusSampleFramework.OVROverlaySample.uiGeoParent
The parents of grouped UI panels.
Definition at line 83 of file OVROverlaySample.cs.
worldspaceGeoParent
GameObject OculusSampleFramework.OVROverlaySample.worldspaceGeoParent
Definition at line 85 of file OVROverlaySample.cs.
The documentation for this class was generated from the following file:
Assets/Oculus/SampleFramework/Usage/OVROverlay/Scripts/OVROverlaySample.cs