VR_Test: Meta.WitAi.WitRequest Class Reference
Meta.WitAi.WitRequest Class Reference
Manages a single request lifecycle when sending/receiving data from Wit.ai.
Public Member Functions
override string ToString ()
Simply return the Path to be called.
delegate Dictionary< string, string > OnProvideCustomHeadersEvent ()
delegate Uri OnCustomizeUriEvent (UriBuilder uriBuilder)
delegate void PreSendRequestDelegate (ref Uri src_uri, out Dictionary< string, string > headers)
WitRequest (WitConfiguration newConfiguration, string newPath, WitRequestOptions newOptions, VoiceServiceRequestEvents newEvents)
Initialize wit request with configuration & path to endpoint.
void Write (byte[] data, int offset, int length)
Write request data to the Wit.ai post's body input stream.
Public Member Functions inherited from Meta.Voice.NLPRequest< VoiceServiceRequestEvent, WitRequestOptions, VoiceServiceRequestEvents, VoiceServiceRequestResults >
void Send (string text)
Applies the specified text to the options if possible & then submits.
Public Attributes
byte[] postData
string postContentType
string forcedHttpMethodType = null
AudioDurationTracker audioDurationTracker
Action< string > onRawResponse
Returns the raw string response that was received before converting it to a JSON object.
OnCustomizeUriEvent onCustomizeUri
Provides an opportunity to customize the url just before a request executed.
Static Public Attributes
static PreSendRequestDelegate onPreSendRequest
Allows customization of the request before it is sent out.
Protected Member Functions
override void SetState (VoiceRequestState newState)
override void OnInit ()
Finalize initialization.
override void HandleAudioActivation ()
override void HandleAudioDeactivation ()
override string GetSendError ()
override void HandleSend ()
Start the async request for data from the Wit.ai servers.
override void OnTranscriptionChanged ()
override void OnPartialResponse ()
override void OnFullResponse ()
override void HandleCancel ()
override void OnComplete ()
Protected Member Functions inherited from Meta.WitAi.Requests.VoiceServiceRequest
VoiceServiceRequest (NLPRequestInputType newInputType, WitRequestOptions newOptions, VoiceServiceRequestEvents newEvents)
Constructor for Voice Service requests.
override VoiceServiceRequestResults GetResultsWithMessage (string newMessage)
Returns an empty result object with the current status code.
override void ApplyTranscription (string newTranscription, bool newIsFinal)
Applies a transcription to the current results.
override void ApplyResultResponseData (WitResponseNode newData)
Applies response data to the current results.
override void RaiseEvent (VoiceServiceRequestEvent eventCallback)
Performs an event callback with this request as the parameter.
Protected Member Functions inherited from Meta.Voice.NLPRequest< VoiceServiceRequestEvent, WitRequestOptions, VoiceServiceRequestEvents, VoiceServiceRequestResults >
NLPRequest (NLPRequestInputType newInputType, TOptions newOptions, TEvents newEvents)
Constructor for NLP text & audio requests.
override void SetState (VoiceRequestState newState)
Apply the voice request state.
override void AppendLogData (StringBuilder log, bool warning)
Append NLP request specific data to log.
override string GetActivateAudioError ()
Throw error on text request.
override string GetSendError ()
Throw error on text request.
Properties
WitConfiguration Configuration [get, private set]
The wit Configuration to be used with this request.
int Timeout = 1000 [get, private set]
The request timeout in ms.
AudioEncoding AudioEncoding [get, set]
Encoding settings for audio based requests.
AudioEncoding audioEncoding [get, set]
string Path [get, private set]
Endpoint to be used for this request.
string Command [get, private set]
Final portion of the endpoint Path.
bool IsPost [get, private set]
Whether a post command should be called.
VoiceServiceRequestOptions.QueryParam[] queryParams [get]
Key value pair that is sent as a query param in the Wit.ai uri.
bool IsRequestStreamActive [get]
Returns true if the request is being performed.
bool HasResponseStarted [get, private set]
Returns true if the response had begun.
bool IsInputStreamReady [get, private set]
Returns true if the response had begun.
string StatusDescription [get, private set]
The current status of the request.
Properties inherited from Meta.WitAi.Requests.VoiceServiceRequest
int StatusCode [get, protected set]
The status code returned from the last request.
Properties inherited from Meta.Voice.NLPRequest< VoiceServiceRequestEvent, WitRequestOptions, VoiceServiceRequestEvents, VoiceServiceRequestResults >
NLPRequestInputType InputType [get, private set]
The request data input type to be used.
Events
OnProvideCustomHeadersEvent onProvideCustomHeaders
Provides an opportunity to provide custom headers for the request just before it is executed.
Action< WitRequest > onInputStreamReady
Callback called when the server is ready to receive data from the WitRequest's input stream. See WitRequest.Write()
Action< string > onPartialTranscription
Returns a partial utterance from an in process request.
Action< string > onFullTranscription
Returns a full utterance from a completed request.
Action< WitRequest > onPartialResponse
Callback called when a response is received from the server off a partial transcription.
Action< WitRequest > onResponse
Callback called when a response is received from the server.
Private Member Functions
Uri GetUri ()
Dictionary< string, string > GetHeaders ()
void StartThreadedRequest (Uri uri, Dictionary< string, string > headers)
Performs a threaded http request.
void StartResponse ()
void HandleTimeoutTimer (object state, bool timeout)
void HandleWriteStream (IAsyncResult ar)
void HandleResponse (IAsyncResult asyncResult)
void CheckStatus ()
string ReadToDelimiter (StreamReader reader, string delimiter)
void ProcessStringResponses (string stringResponse)
void ProcessStringResponse (string stringResponse)
bool WaitingForPost ()
void CloseRequestStream ()
void CloseActiveStream ()
void MainThreadCallback (Action action)
void WatchMainThreadCallbacks ()
System.Collections.IEnumerator PerformMainThreadCallbacks ()
bool HasMainThreadCallbacks ()
Private Attributes
HttpWebRequest _request
Stream _writeStream
object _streamLock = new object()
int _bytesWritten
string _stackTrace
DateTime _requestStartTime
ConcurrentQueue< byte[]> _writeBuffer = new ConcurrentQueue<byte[]>()
WitResponseNode _lastResponseData
Last response data parsed.
bool _initialized = false
Only set state if initialized.
CoroutineUtility.CoroutinePerformer _performer = null
ConcurrentQueue< Action > _mainThreadCallbacks = new ConcurrentQueue<Action>()
Detailed Description
Manages a single request lifecycle when sending/receiving data from Wit.ai.
Note: This is not intended to be instantiated directly. Requests should be created with the WitRequestFactory
Definition at line 38 of file WitRequest.cs.
Constructor & Destructor Documentation
WitRequest()
Meta.WitAi.WitRequest.WitRequest (WitConfiguration newConfiguration, string newPath, WitRequestOptions newOptions, VoiceServiceRequestEvents newEvents)
Initialize wit request with configuration & path to endpoint.
Parameters
newConfiguration
newOptions
newEvents
Definition at line 210 of file WitRequest.cs.
            : base(NLPRequestInputType.Audio, newOptions, newEvents)
        {
            // Set Configuration & path
            Configuration = newConfiguration;
            Path = newPath;
            // Finalize
            _initialized = true;
            SetState(VoiceRequestState.Initialized);
        }
References Meta.WitAi.WitRequest._initialized, Meta.WitAi.WitRequest.Configuration, and Meta.WitAi.WitRequest.Path.
Member Function Documentation
CheckStatus()
void Meta.WitAi.WitRequest.CheckStatus () private
Definition at line 769 of file WitRequest.cs.
        {
            if (StatusCode == 0) return;
            switch (StatusCode)
            {
                case WitConstants.ERROR_CODE_ABORTED:
                    throw new WebException("Request was aborted", WebExceptionStatus.RequestCanceled);
                default:
                    throw new WebException("Status changed before response was received.", (WebExceptionStatus) StatusCode);
            }
        }
CloseActiveStream()
void Meta.WitAi.WitRequest.CloseActiveStream () private
Definition at line 917 of file WitRequest.cs.
        {
            IsInputStreamReady = false;
            lock (_streamLock)
            {
                if (null != _writeStream)
                {
                    try
                    {
                        _writeStream.Close();
                    }
                    catch (Exception e)
                    {
                        VLog.W($"Write Stream - Close Failed\n{e}");
                    }
                    _writeStream = null;
                }
            }
        }
CloseRequestStream()
void Meta.WitAi.WitRequest.CloseRequestStream () private
Definition at line 903 of file WitRequest.cs.
        {
            // Cancel due to no audio if not an error
            if (WaitingForPost())
            {
                Cancel("Request was closed with no audio captured.");
            }
            // Close
            else
            {
                CloseActiveStream();
            }
        }
GetHeaders()
Dictionary< string, string > Meta.WitAi.WitRequest.GetHeaders () private
Definition at line 312 of file WitRequest.cs.
        {
            // Get default headers
            Dictionary<string, string> headers = WitVRequest.GetWitHeaders(Configuration, Options?.RequestId, false);
            // Append additional headers
            if (onProvideCustomHeaders != null)
            {
                foreach (OnProvideCustomHeadersEvent e in onProvideCustomHeaders.GetInvocationList())
                {
                    Dictionary<string, string> customHeaders = e();
                    if (customHeaders != null)
                    {
                        foreach (var key in customHeaders.Keys)
{
                            headers[key] = customHeaders[key];
                        }
                    }
                }
            }
            // Return headers
            return headers;
        }
GetSendError()
override string Meta.WitAi.WitRequest.GetSendError () protected
Definition at line 273 of file WitRequest.cs.
        {
            // No configuration found
            if (Configuration == null)
            {
                return "Configuration is not set. Cannot start request.";
            }
            // Cannot start without client access token
            if (string.IsNullOrEmpty(Configuration.GetClientAccessToken()))
            {
                return "Client access token is not defined. Cannot start request.";
            }
            // Cannot perform without input stream delegate
            if (onInputStreamReady == null)
            {
                return "No input stream delegate found";
            }
            // Base
            return base.GetSendError();
        }
GetUri()
Uri Meta.WitAi.WitRequest.GetUri () private
Definition at line 294 of file WitRequest.cs.
        {
            // Get query parameters
            Dictionary<string, string> queryParams = new Dictionary<string, string>(Options.QueryParams);
            // Get uri using override
            var uri = WitVRequest.GetWitUri(Configuration, Path, queryParams);
            #pragma warning disable CS0618
            if (onCustomizeUri != null)
            {
                #pragma warning disable CS0618
                uri = onCustomizeUri(new UriBuilder(uri));
            }
            // Return uri
            return uri;
        }
HandleAudioActivation()
override void Meta.WitAi.WitRequest.HandleAudioActivation () protected
Definition at line 254 of file WitRequest.cs.
        {
            SetAudioInputState(VoiceAudioInputState.On);
        }
HandleAudioDeactivation()
override void Meta.WitAi.WitRequest.HandleAudioDeactivation () protected
Definition at line 259 of file WitRequest.cs.
        {
            // If transmitting,
            if (State == VoiceRequestState.Transmitting)
            {
                CloseRequestStream();
            }
            // Call deactivated
            SetAudioInputState(VoiceAudioInputState.Off);
        }
HandleCancel()
override void Meta.WitAi.WitRequest.HandleCancel () protected
Definition at line 938 of file WitRequest.cs.
        {
            // Close stream
            CloseActiveStream();
            // Apply abort code
            if (StatusCode == 0)
            {
                StatusCode = WitConstants.ERROR_CODE_ABORTED;
                StatusDescription = Results.Message;
            }
            // Abort request
            if (null != _request)
            {
                _request.Abort();
                _request = null;
            }
        }
HandleResponse()
void Meta.WitAi.WitRequest.HandleResponse (IAsyncResult asyncResult) private
Definition at line 617 of file WitRequest.cs.
        {
            // Begin response
            HasResponseStarted = true;
            string stringResponse = "";
            try
            {
                // Get response
                CheckStatus();
                using (var response = _request.EndGetResponse(asyncResult))
                {
                    // Got response
                    CheckStatus();
                    HttpWebResponse httpResponse = response as HttpWebResponse;
                    // Apply status & description
                    StatusCode = (int) httpResponse.StatusCode;
                    StatusDescription = httpResponse.StatusDescription;
                    // Get stream
                    using (var responseStream = httpResponse.GetResponseStream())
                    {
                        using (var responseReader = new StreamReader(responseStream))
{
                            string chunk;
                            while ((chunk = ReadToDelimiter(responseReader, WitConstants.ENDPOINT_JSON_DELIMITER)) != null)
{
                                stringResponse = chunk;
                                ProcessStringResponse(stringResponse);
                            }
                        }
                    }
                }
            }
            catch (JSONParseException e)
            {
                _stackTrace = e.StackTrace;
                StatusCode = WitConstants.ERROR_CODE_INVALID_DATA_FROM_SERVER;
                StatusDescription = "Server returned invalid data.";
                VLog.W(e);
            }
            catch (WebException e)
            {
                if (e.Status != WebExceptionStatus.RequestCanceled)
                {
                    // Apply status & error
                    _stackTrace = e.StackTrace;
                    StatusCode = (int) e.Status;
                    StatusDescription = e.Message;
                    VLog.W(e);
                    // Attempt additional parse
                    if (e.Response is HttpWebResponse errorResponse)
                    {
                        StatusCode = (int) errorResponse.StatusCode;
                        try
{
                            using (var errorStream = errorResponse.GetResponseStream())
{
                                if (errorStream != null)
{
                                    using (StreamReader errorReader = new StreamReader(errorStream))
{
                                        stringResponse = errorReader.ReadToEnd();
                                        if (!string.IsNullOrEmpty(stringResponse))
{
                                            ProcessStringResponses(stringResponse);
                                        }
                                    }
                                }
                            }
                        }
                        catch (JSONParseException)
{
                            // Response wasn't encoded error, ignore it.
                        }
                        catch (Exception errorResponseError)
{
                            // We've already caught that there is an error, we'll ignore any errors
                            // reading error response data and use the status/original error for validation
                            VLog.W(errorResponseError);
                            _stackTrace = e.StackTrace;
                        }
                    }
                }
            }
            catch (Exception e)
            {
                _stackTrace = e.StackTrace;
                StatusCode = WitConstants.ERROR_CODE_GENERAL;
                StatusDescription = e.Message;
                VLog.W(e);
            }
            // Close request stream if possible
            CloseRequestStream();
            // Confirm valid response
            if (null != _lastResponseData)
            {
                var error = _lastResponseData["error"];
                if (!string.IsNullOrEmpty(error))
                {
                    // Get code if possible
                    var code = _lastResponseData["code"];
                    if (code != null)
                    {
                        StatusCode = code.AsInt;
                    }
                    // Use general error if code is not provided
                    if (StatusCode == (int)HttpStatusCode.OK)
                    {
                        StatusCode = WitConstants.ERROR_CODE_GENERAL;
                    }
                    // Set error & description
                    if (string.IsNullOrEmpty(StatusDescription))
                    {
                        StatusDescription = $"Error: {code}\n{error}";
                    }
                }
            }
            // Invalid response
            else if (StatusCode == (int)HttpStatusCode.OK)
            {
                StatusCode = WitConstants.ERROR_CODE_NO_DATA_FROM_SERVER;
                StatusDescription = $"Server did not return a valid json response.";
                #if UNITY_EDITOR
                StatusDescription += $"\nActual Response\n{stringResponse}";
                #endif
            }
            // Done
            HasResponseStarted = false;
            MainThreadCallback(() =>
            {
                // Append error if needed
                if (null != _lastResponseData)
                {
                    var error = _lastResponseData["error"];
                    if (!string.IsNullOrEmpty(error))
                    {
                        StatusDescription += $"\n{error}";
                    }
                }
                // Call completion delegate
                HandleFinalNlpResponse(_lastResponseData, StatusCode == (int)HttpStatusCode.OK ? string.Empty : $"{StatusDescription}\n\nStackTrace:\n{_stackTrace}\n\n");
            });
        }
HandleSend()
override void Meta.WitAi.WitRequest.HandleSend () protected
Start the async request for data from the Wit.ai servers.
Definition at line 340 of file WitRequest.cs.
        {
            // Begin
            HasResponseStarted = false;
            // Generate results
            StatusCode = 0;
            StatusDescription = "Starting request";
            _bytesWritten = 0;
            _requestStartTime = DateTime.UtcNow;
            _stackTrace = "-";
            // Get uri & headers
            var uri = GetUri();
            var headers = GetHeaders();
            // Allow overrides
            onPreSendRequest?.Invoke(ref uri, out headers);
            #if UNITY_WEBGL && !UNITY_EDITOR
            StartUnityRequest(uri, headers);
            #else
            #if UNITY_WEBGL && UNITY_EDITOR
            if (IsPost)
            {
                VLog.W("Voice input is not supported in WebGL this functionality is fully enabled at edit time, but may not work at runtime.");
            }
            #endif
            StartThreadedRequest(uri, headers);
            #endif
        }
References Meta.WitAi.WitRequest.HasResponseStarted, Meta.WitAi.WitRequest.IsPost, Meta.WitAi.WitRequest.onPreSendRequest, Meta.WitAi.WitRequest.StartThreadedRequest(), Meta.WitAi.Requests.VoiceServiceRequest.StatusCode, Meta.WitAi.WitRequest.StatusDescription, and Meta.WitAi.VLog.W().
HandleTimeoutTimer()
void Meta.WitAi.WitRequest.HandleTimeoutTimer (object state, bool timeout) private
Definition at line 455 of file WitRequest.cs.
        {
            // Ignore false or too late
            if (!timeout)
            {
                return;
            }
            // No longer active
            StatusCode = WitConstants.ERROR_CODE_TIMEOUT;
            // Clean up the current request if it is still going
            if (null != _request)
            {
                _request.Abort();
            }
            // Close any open stream resources and clean up streaming state flags
            CloseActiveStream();
            // Complete
            MainThreadCallback(() =>
            {
                string path = "";
                if (null != _request?.RequestUri?.PathAndQuery)
                {
                    var uriSections = _request.RequestUri.PathAndQuery.Split(new char[] { '?' });
                    path = uriSections[0];
                }
                // TODO: T153403776 There are still problems with this logic. We're not properly propigating down if
                // this was a cancellation due to user request or actual timeout.
                var time = (DateTime.UtcNow - _requestStartTime);
                if (time.Seconds > Timeout)
                {
                    StatusDescription = $"Request [{path}] timed out after {time.Seconds:0.00} seconds";
                }
                HandleFinalNlpResponse(null, StatusDescription);
            });
        }
HandleWriteStream()
void Meta.WitAi.WitRequest.HandleWriteStream (IAsyncResult ar) private
Definition at line 498 of file WitRequest.cs.
        {
            try
            {
                // Start response stream
                StartResponse();
                // Get write stream
                var stream = _request.EndGetRequestStream(ar);
                // Got write stream
                _bytesWritten = 0;
                // Immediate post
                if (postData != null && postData.Length > 0)
                {
                    Debug.Log("Wrote directly");
                    _bytesWritten += postData.Length;
                    stream.Write(postData, 0, postData.Length);
                    stream.Close();
                }
                // Wait for input stream
                else
                {
                    // Request stream is ready to go
                    IsInputStreamReady = true;
                    _writeStream = stream;
                    // Call input stream ready delegate
                    if (onInputStreamReady != null)
                    {
                        MainThreadCallback(() => onInputStreamReady(this));
                    }
                }
            }
            catch (WebException e)
            {
                // Ignore cancelation errors & if error already occured
                if (e.Status == WebExceptionStatus.RequestCanceled || StatusCode != 0)
                {
                    return;
                }
                // Write stream error
                _stackTrace = e.StackTrace;
                StatusCode = (int) e.Status;
                StatusDescription = e.Message;
                VLog.W(e);
                MainThreadCallback(() => HandleFinalNlpResponse(null, StatusDescription));
            }
            catch (Exception e)
            {
                // Call an error if have not done so yet
                if (StatusCode != 0)
                {
                    return;
                }
                // Non web error occured
                _stackTrace = e.StackTrace;
                StatusCode = WitConstants.ERROR_CODE_GENERAL;
                StatusDescription = e.Message;
                VLog.W(e);
                MainThreadCallback(() => HandleFinalNlpResponse(null, StatusDescription));
            }
        }
HasMainThreadCallbacks()
bool Meta.WitAi.WitRequest.HasMainThreadCallbacks () private
Definition at line 1034 of file WitRequest.cs.
        {
            return IsActive || _mainThreadCallbacks.Count > 0;
        }
MainThreadCallback()
void Meta.WitAi.WitRequest.MainThreadCallback (Action action) private
Definition at line 988 of file WitRequest.cs.
        {
            if (action == null)
            {
                return;
            }
            _mainThreadCallbacks.Enqueue(action);
        }
OnComplete()
override void Meta.WitAi.WitRequest.OnComplete () protected
Definition at line 959 of file WitRequest.cs.
        {
            base.OnComplete();
            // Close write stream if still existing
            if (null != _writeStream)
            {
                CloseActiveStream();
            }
            // Abort request if still existing
            if (null != _request)
            {
                _request.Abort();
                _request = null;
            }
            // Finalize response
            onResponse?.Invoke(this);
            onResponse = null;
        }
OnFullResponse()
override void Meta.WitAi.WitRequest.OnFullResponse () protected
Definition at line 893 of file WitRequest.cs.
        {
            base.OnFullResponse();
        }
OnInit()
override void Meta.WitAi.WitRequest.OnInit () protected
Finalize initialization.
Definition at line 237 of file WitRequest.cs.
        {
            // Determine configuration setting
            Timeout = Configuration == null ? Timeout : Configuration.timeoutMS;
            // Set request settings
            Command = Path.Split('/').First();
            IsPost = WitEndpointConfig.GetEndpointConfig(Configuration).Speech == this.Command
                     || WitEndpointConfig.GetEndpointConfig(Configuration).Dictation == this.Command;
            // Finalize bases
            base.OnInit();
        }
References Meta.WitAi.WitRequest.Command, Meta.WitAi.WitRequest.Configuration, Meta.WitAi.Configuration.WitEndpointConfig.GetEndpointConfig(), Meta.WitAi.WitRequest.IsPost, Meta.WitAi.WitRequest.Path, and Meta.WitAi.WitRequest.Timeout.
OnPartialResponse()
override void Meta.WitAi.WitRequest.OnPartialResponse () protected
Definition at line 887 of file WitRequest.cs.
        {
            onPartialResponse?.Invoke(this);
            base.OnPartialResponse();
        }
OnTranscriptionChanged()
override void Meta.WitAi.WitRequest.OnTranscriptionChanged () protected
Definition at line 874 of file WitRequest.cs.
        {
            if (!IsFinalTranscription)
            {
                onPartialTranscription?.Invoke(Transcription);
            }
            else
            {
                onFullTranscription?.Invoke(Transcription);
            }
            base.OnTranscriptionChanged();
        }
PerformMainThreadCallbacks()
System.Collections.IEnumerator Meta.WitAi.WitRequest.PerformMainThreadCallbacks () private
Definition at line 1009 of file WitRequest.cs.
        {
            // While checking, continue
            while (HasMainThreadCallbacks())
            {
                // Wait for frame
                if (Application.isPlaying && !Application.isBatchMode)
                {
                    yield return new WaitForEndOfFrame();
                }
                // Wait for a tick
                else
                {
                    yield return null;
                }
                // Perform if possible
                while (_mainThreadCallbacks.Count > 0 && _mainThreadCallbacks.TryDequeue(out var result))
                {
                    result();
                }
            }
            _performer = null;
        }
ProcessStringResponse()
void Meta.WitAi.WitRequest.ProcessStringResponse (string stringResponse) private
Definition at line 842 of file WitRequest.cs.
        {
            // Call raw response for every received response
            if (!string.IsNullOrEmpty(stringResponse))
            {
                MainThreadCallback(() => onRawResponse?.Invoke(stringResponse));
            }
            // Decode full response
            WitResponseNode responseNode = WitResponseNode.Parse(stringResponse);
            bool hasResponse = responseNode.HasResponse();
            bool isFinal = responseNode.GetIsFinal();
            string transcription = responseNode.GetTranscription();
            _lastResponseData = responseNode;
            // Apply on main thread
            MainThreadCallback(() =>
            {
                // Set transcription
                if (!string.IsNullOrEmpty(transcription) && (!hasResponse || isFinal))
                {
                    ApplyTranscription(transcription, isFinal);
                }
                // Set response
                if (hasResponse)
                {
                    HandlePartialNlpResponse(responseNode);
                }
            });
        }
ProcessStringResponses()
void Meta.WitAi.WitRequest.ProcessStringResponses (string stringResponse) private
Definition at line 833 of file WitRequest.cs.
        {
            // Split by delimiter
            foreach (var stringPart in stringResponse.Split(new string[]{WitConstants.ENDPOINT_JSON_DELIMITER}, StringSplitOptions.RemoveEmptyEntries))
            {
                ProcessStringResponse(stringPart);
            }
        }
ReadToDelimiter()
string Meta.WitAi.WitRequest.ReadToDelimiter (StreamReader reader, string delimiter) private
Definition at line 782 of file WitRequest.cs.
        {
            // Allocate all vars
            StringBuilder results = new StringBuilder();
            int delLength = delimiter.Length;
            int i;
            bool found;
            char nextChar;
            // Iterate each byte in the stream
            while (reader != null && !reader.EndOfStream)
            {
                // Continue until found
                if (reader.Peek() == 0)
                {
                    continue;
                }
                // Append next character
                nextChar = (char)reader.Read();
                results.Append(nextChar);
                // Continue until long as delimiter
                if (results.Length < delLength)
                {
                    continue;
                }
                // Check if string builder ends with delimiter
                found = true;
                for (i=0;i<delLength;i++)
                {
                    // Stop checking if not delimiter
                    if (delimiter[i] != results[results.Length - delLength + i])
                    {
                        found = false;
                        break;
                    }
                }
                // Found delimiter
                if (found)
                {
                    return results.ToString(0, results.Length - delLength);
                }
            }
            // If no delimiter is found, return the rest of the chunk
            return results.Length == 0 ? null : results.ToString();
        }
SetState()
override void Meta.WitAi.WitRequest.SetState (VoiceRequestState newState) protected
Definition at line 226 of file WitRequest.cs.
        {
            if (_initialized)
            {
                base.SetState(newState);
            }
        }
StartResponse()
void Meta.WitAi.WitRequest.StartResponse () private
Definition at line 438 of file WitRequest.cs.
        {
            if (_request == null)
            {
                if (StatusCode == 0)
                {
                    StatusCode = WitConstants.ERROR_CODE_GENERAL;
                    StatusDescription = $"Request canceled prior to start";
                }
                HandleFinalNlpResponse(null, StatusDescription);
                return;
            }
            var asyncResult = _request.BeginGetResponse(HandleResponse, _request);
            ThreadPool.RegisterWaitForSingleObject(asyncResult.AsyncWaitHandle, HandleTimeoutTimer, _request, Timeout, true);
        }
StartThreadedRequest()
void Meta.WitAi.WitRequest.StartThreadedRequest (Uri uri, Dictionary< string, string > headers) private
Performs a threaded http request.
Definition at line 377 of file WitRequest.cs.
        {
            // Create http web request
            _request = WebRequest.Create(uri.AbsoluteUri) as HttpWebRequest;
            // Off to not wait for a response indefinitely
            _request.KeepAlive = false;
            // Configure request method, content type & chunked
            if (forcedHttpMethodType != null)
            {
                _request.Method = forcedHttpMethodType;
            }
            if (null != postContentType)
            {
                if (forcedHttpMethodType == null) {
                    _request.Method = "POST";
                }
                _request.ContentType = postContentType;
                _request.ContentLength = postData.Length;
            }
            if (IsPost)
            {
                _request.Method = string.IsNullOrEmpty(forcedHttpMethodType) ? "POST" : forcedHttpMethodType;
                _request.ContentType = AudioEncoding.ToString();
                _request.SendChunked = true;
            }
            // Apply user agent
            if (headers.ContainsKey(WitConstants.HEADER_USERAGENT))
            {
                _request.UserAgent = headers[WitConstants.HEADER_USERAGENT];
                headers.Remove(WitConstants.HEADER_USERAGENT);
            }
            // Apply all other headers
            foreach (var key in headers.Keys)
            {
                _request.Headers[key] = headers[key];
            }
            // Apply timeout
            _request.Timeout = Timeout;
            // Begin calling on main thread if needed
            WatchMainThreadCallbacks();
            // Perform http post or put
            if (_request.Method == "POST" || _request.Method == "PUT")
            {
                var getRequestTask = _request.BeginGetRequestStream(HandleWriteStream, _request);
                ThreadPool.RegisterWaitForSingleObject(getRequestTask.AsyncWaitHandle,
                    HandleTimeoutTimer, _request, Timeout, true);
            }
            // Move right to response
            else
            {
                StartResponse();
            }
        }
References Meta.WitAi.WitRequest.IsPost, and Meta.WitAi.WitRequest.Timeout.
WaitingForPost()
bool Meta.WitAi.WitRequest.WaitingForPost () private
Definition at line 898 of file WitRequest.cs.
        {
            return IsPost && _bytesWritten == 0 && StatusCode == 0;
        }
WatchMainThreadCallbacks()
void Meta.WitAi.WitRequest.WatchMainThreadCallbacks () private
Definition at line 997 of file WitRequest.cs.
        {
            // Ignore if already performing
            if (_performer != null)
            {
                return;
            }
            // Check callbacks every frame (editor or runtime)
            _performer = CoroutineUtility.StartCoroutine(PerformMainThreadCallbacks());
        }
Write()
void Meta.WitAi.WitRequest.Write (byte[] data, int offset, int length)
Write request data to the Wit.ai post's body input stream.
Note: If the stream is not open (IsActive) this will throw an IOException. Data will be written synchronously. This should not be called from the main thread.
Parameters
data
offset
length
Definition at line 574 of file WitRequest.cs.
        {
            // Ignore without write stream
            if (!IsInputStreamReady || data == null || length == 0)
            {
                return;
            }
            try
            {
                _writeStream.Write(data, offset, length);
                _bytesWritten += length;
                if (audioDurationTracker != null)
                {
                    audioDurationTracker.AddBytes(length);
                }
            }
            catch (ObjectDisposedException e)
            {
                // Handling edge case where stream is closed remotely
                // This problem occurs when the Web server resets or closes the connection after
                // the client application sends the HTTP header.
                // https://support.microsoft.com/en-us/topic/fix-you-receive-a-system-objectdisposedexception-exception-when-you-try-to-access-a-stream-object-that-is-returned-by-the-endgetrequeststream-method-in-the-net-framework-2-0-bccefe57-0a61-517a-5d5f-2dce0cc63265
                VLog.W($"Stream already disposed. It is likely the server reset the connection before streaming started.\n{e}");
                // This prevents a very long holdup on _writeStream.Close
                _writeStream = null;
            }
            catch (IOException e)
            {
                VLog.W(e.Message);
            }
            catch (Exception e)
            {
                VLog.E(e);
            }
            // Perform a cancellation if still waiting for a post
            if (WaitingForPost())
            {
                MainThreadCallback(() => Cancel("Stream was closed with no data written."));
            }
        }
References Meta.WitAi.VLog.E(), Meta.WitAi.WitRequest.IsInputStreamReady, and Meta.WitAi.VLog.W().
Member Data Documentation
_bytesWritten
int Meta.WitAi.WitRequest._bytesWritten private
Definition at line 117 of file WitRequest.cs.
_initialized
bool Meta.WitAi.WitRequest._initialized = false private
Only set state if initialized.
Definition at line 225 of file WitRequest.cs.
_lastResponseData
WitResponseNode Meta.WitAi.WitRequest._lastResponseData private
Last response data parsed.
Definition at line 137 of file WitRequest.cs.
_mainThreadCallbacks
ConcurrentQueue<Action> Meta.WitAi.WitRequest._mainThreadCallbacks = new ConcurrentQueue<Action>() private
Definition at line 985 of file WitRequest.cs.
_performer
CoroutineUtility.CoroutinePerformer Meta.WitAi.WitRequest._performer = null private
Definition at line 983 of file WitRequest.cs.
_request
HttpWebRequest Meta.WitAi.WitRequest._request private
Definition at line 114 of file WitRequest.cs.
_requestStartTime
DateTime Meta.WitAi.WitRequest._requestStartTime private
Definition at line 119 of file WitRequest.cs.
_stackTrace
string Meta.WitAi.WitRequest._stackTrace private
Definition at line 118 of file WitRequest.cs.
_streamLock
object Meta.WitAi.WitRequest._streamLock = new object() private
Definition at line 116 of file WitRequest.cs.
_writeBuffer
ConcurrentQueue<byte[]> Meta.WitAi.WitRequest._writeBuffer = new ConcurrentQueue<byte[]>() private
Definition at line 120 of file WitRequest.cs.
_writeStream
Stream Meta.WitAi.WitRequest._writeStream private
Definition at line 115 of file WitRequest.cs.
audioDurationTracker
AudioDurationTracker Meta.WitAi.WitRequest.audioDurationTracker
Definition at line 113 of file WitRequest.cs.
forcedHttpMethodType
string Meta.WitAi.WitRequest.forcedHttpMethodType = null
Definition at line 96 of file WitRequest.cs.
onCustomizeUri
OnCustomizeUriEvent Meta.WitAi.WitRequest.onCustomizeUri
Provides an opportunity to customize the url just before a request executed.
Definition at line 165 of file WitRequest.cs.
onPreSendRequest
PreSendRequestDelegate Meta.WitAi.WitRequest.onPreSendRequest static
Allows customization of the request before it is sent out.
Note: This is for devs who are routing requests to their servers before sending data to Wit.ai. This allows adding any additional headers, url modifications, or customization of the request.
Definition at line 174 of file WitRequest.cs.
onRawResponse
Action<string> Meta.WitAi.WitRequest.onRawResponse
Returns the raw string response that was received before converting it to a JSON object.
NOTE: This response comes back on a different thread. Do not attempt ot set UI control values or other interactions from this callback. This is intended to be used for demo and test UI, not for regular use.
Definition at line 159 of file WitRequest.cs.
postContentType
string Meta.WitAi.WitRequest.postContentType
Definition at line 95 of file WitRequest.cs.
postData
byte [] Meta.WitAi.WitRequest.postData
Definition at line 94 of file WitRequest.cs.
Property Documentation
AudioEncoding
AudioEncoding Meta.WitAi.WitRequest.AudioEncoding get set
Encoding settings for audio based requests.
Definition at line 52 of file WitRequest.cs.
{ get; set; }
audioEncoding
AudioEncoding Meta.WitAi.WitRequest.audioEncoding get set
Definition at line 54 of file WitRequest.cs.
        {
            get => AudioEncoding;
            set => AudioEncoding = value;
        }
Command
string Meta.WitAi.WitRequest.Command get private set
Final portion of the endpoint Path.
Definition at line 67 of file WitRequest.cs.
{ get; private set; }
Configuration
WitConfiguration Meta.WitAi.WitRequest.Configuration get private set
The wit Configuration to be used with this request.
Definition at line 44 of file WitRequest.cs.
{ get; private set; }
HasResponseStarted
bool Meta.WitAi.WitRequest.HasResponseStarted get private set
Returns true if the response had begun.
Definition at line 107 of file WitRequest.cs.
{ get; private set; }
IsInputStreamReady
bool Meta.WitAi.WitRequest.IsInputStreamReady get private set
Returns true if the response had begun.
Definition at line 111 of file WitRequest.cs.
{ get; private set; }
IsPost
bool Meta.WitAi.WitRequest.IsPost get private set
Whether a post command should be called.
Definition at line 71 of file WitRequest.cs.
{ get; private set; }
IsRequestStreamActive
bool Meta.WitAi.WitRequest.IsRequestStreamActive get
Returns true if the request is being performed.
Definition at line 103 of file WitRequest.cs.
Path
string Meta.WitAi.WitRequest.Path get private set
Endpoint to be used for this request.
Definition at line 63 of file WitRequest.cs.
{ get; private set; }
queryParams
VoiceServiceRequestOptions.QueryParam [] Meta.WitAi.WitRequest.queryParams get
Key value pair that is sent as a query param in the Wit.ai uri.
Definition at line 76 of file WitRequest.cs.
        {
            get
            {
                List<VoiceServiceRequestOptions.QueryParam> results = new List<VoiceServiceRequestOptions.QueryParam>();
                foreach (var key in Options?.QueryParams?.Keys)
                {
                    VoiceServiceRequestOptions.QueryParam p = new VoiceServiceRequestOptions.QueryParam()
                    {
                        key = key,
                        value = Options?.QueryParams[key]
                    };
                    results.Add(p);
                }
                return results.ToArray();
            }
        }
StatusDescription
string Meta.WitAi.WitRequest.StatusDescription get private set
The current status of the request.
Definition at line 127 of file WitRequest.cs.
{ get; private set; }
Timeout
int Meta.WitAi.WitRequest.Timeout = 1000 get private set
The request timeout in ms.
Definition at line 48 of file WitRequest.cs.
{ get; private set; } = 1000;
Event Documentation
onFullTranscription
Action<string> Meta.WitAi.WitRequest.onFullTranscription
Returns a full utterance from a completed request.
NOTE: This response comes back on a different thread.
Definition at line 189 of file WitRequest.cs.
onInputStreamReady
Action<WitRequest> Meta.WitAi.WitRequest.onInputStreamReady
Callback called when the server is ready to receive data from the WitRequest's input stream. See WitRequest.Write()
Definition at line 151 of file WitRequest.cs.
onPartialResponse
Action<WitRequest> Meta.WitAi.WitRequest.onPartialResponse
Callback called when a response is received from the server off a partial transcription.
Definition at line 195 of file WitRequest.cs.
onPartialTranscription
Action<string> Meta.WitAi.WitRequest.onPartialTranscription
Returns a partial utterance from an in process request.
NOTE: This response comes back on a different thread.
Definition at line 182 of file WitRequest.cs.
onProvideCustomHeaders
OnProvideCustomHeadersEvent Meta.WitAi.WitRequest.onProvideCustomHeaders
Provides an opportunity to provide custom headers for the request just before it is executed.
Definition at line 145 of file WitRequest.cs.
onResponse
Action<WitRequest> Meta.WitAi.WitRequest.onResponse
Callback called when a response is received from the server.
Definition at line 200 of file WitRequest.cs.
The documentation for this class was generated from the following file:
Assets/Oculus/Voice/Lib/Wit.ai/Scripts/Runtime/WitRequest.cs