VR_Test: Meta.Voice.Samples.TTSVoices.TTSSpeakerObserver Class Reference
Meta.Voice.Samples.TTSVoices.TTSSpeakerObserver Class Reference
A demo script that provides access to a TTSSpeaker and overrides all TTSSpeaker callback events.
Protected Member Functions
virtual void Awake ()
Obtains speaker if not set.
virtual void OnEnable ()
On enable, add all callbacks.
virtual void OnDisable ()
On disable, remove all callbacks.
virtual void OnPlaybackQueueBegin ()
Callback for queue begin.
virtual void OnPlaybackQueueComplete ()
Callback for queue completion.
virtual void OnLoadBegin (TTSSpeaker speaker, TTSClipData clipData)
Callback for load begin.
virtual void OnLoadAbort (TTSSpeaker speaker, TTSClipData clipData)
Callback for load cancelation.
virtual void OnLoadFailed (TTSSpeaker speaker, TTSClipData clipData, string error)
Callback for load error.
virtual void OnLoadSuccess (TTSSpeaker speaker, TTSClipData clipData)
Callback for load success.
virtual void OnPlaybackReady (TTSSpeaker speaker, TTSClipData clipData)
Callback for playback is ready for a clip.
virtual void OnPlaybackStart (TTSSpeaker speaker, TTSClipData clipData)
Callback for playback for a clip has begun.
virtual void OnPlaybackCancelled (TTSSpeaker speaker, TTSClipData clipData, string reason)
Callback for playback for a clip has been canceled.
virtual void OnPlaybackComplete (TTSSpeaker speaker, TTSClipData clipData)
Callback for playback completion.
Properties
TTSSpeaker Speaker [get]
Private Attributes
TTSSpeaker _speaker
Detailed Description
A demo script that provides access to a TTSSpeaker and overrides all TTSSpeaker callback events.
Definition at line 19 of file TTSSpeakerObserver.cs.
Member Function Documentation
Awake()
virtual void Meta.Voice.Samples.TTSVoices.TTSSpeakerObserver.Awake () protected virtual
Obtains speaker if not set.
Reimplemented in Meta.Voice.Samples.TTSVoices.TTSSpeakerVoiceSelect.
Definition at line 29 of file TTSSpeakerObserver.cs.
        {
            if (_speaker == null)
            {
                _speaker = gameObject.GetComponentInChildren<TTSSpeaker>();
            }
        }
OnDisable()
virtual void Meta.Voice.Samples.TTSVoices.TTSSpeakerObserver.OnDisable () protected virtual
On disable, remove all callbacks.
Reimplemented in Meta.Voice.Samples.TTSVoices.TTSSpeakerEffectSelect, and Meta.Voice.Samples.TTSVoices.TTSSpeakerVoiceSelect.
Definition at line 61 of file TTSSpeakerObserver.cs.
        {
            if (_speaker == null)
            {
                return;
            }
            _speaker.Events.OnPlaybackQueueBegin.RemoveListener(OnPlaybackQueueBegin);
            _speaker.Events.OnPlaybackQueueComplete.RemoveListener(OnPlaybackQueueComplete);
            _speaker.Events.OnLoadBegin.RemoveListener(OnLoadBegin);
            _speaker.Events.OnLoadAbort.RemoveListener(OnLoadAbort);
            _speaker.Events.OnLoadFailed.RemoveListener(OnLoadFailed);
            _speaker.Events.OnLoadSuccess.RemoveListener(OnLoadSuccess);
            _speaker.Events.OnPlaybackReady.RemoveListener(OnPlaybackReady);
            _speaker.Events.OnPlaybackStart.RemoveListener(OnPlaybackStart);
            _speaker.Events.OnPlaybackCancelled.RemoveListener(OnPlaybackCancelled);
            _speaker.Events.OnPlaybackComplete.RemoveListener(OnPlaybackComplete);
        }
References Meta.WitAi.TTS.Utilities.TTSSpeakerClipEvents.OnLoadAbort, Meta.Voice.Samples.TTSVoices.TTSSpeakerObserver.OnLoadAbort(), Meta.WitAi.TTS.Utilities.TTSSpeakerClipEvents.OnLoadBegin, Meta.Voice.Samples.TTSVoices.TTSSpeakerObserver.OnLoadBegin(), Meta.WitAi.TTS.Utilities.TTSSpeakerClipEvents.OnLoadFailed, Meta.Voice.Samples.TTSVoices.TTSSpeakerObserver.OnLoadFailed(), Meta.WitAi.TTS.Utilities.TTSSpeakerClipEvents.OnLoadSuccess, Meta.Voice.Samples.TTSVoices.TTSSpeakerObserver.OnLoadSuccess(), Meta.WitAi.TTS.Utilities.TTSSpeakerClipEvents.OnPlaybackCancelled, Meta.Voice.Samples.TTSVoices.TTSSpeakerObserver.OnPlaybackCancelled(), Meta.WitAi.TTS.Utilities.TTSSpeakerClipEvents.OnPlaybackComplete, Meta.Voice.Samples.TTSVoices.TTSSpeakerObserver.OnPlaybackComplete(), Meta.Voice.Samples.TTSVoices.TTSSpeakerObserver.OnPlaybackQueueBegin(), Meta.Voice.Samples.TTSVoices.TTSSpeakerObserver.OnPlaybackQueueComplete(), Meta.WitAi.TTS.Utilities.TTSSpeakerClipEvents.OnPlaybackReady, Meta.Voice.Samples.TTSVoices.TTSSpeakerObserver.OnPlaybackReady(), Meta.WitAi.TTS.Utilities.TTSSpeakerClipEvents.OnPlaybackStart, and Meta.Voice.Samples.TTSVoices.TTSSpeakerObserver.OnPlaybackStart().
OnEnable()
virtual void Meta.Voice.Samples.TTSVoices.TTSSpeakerObserver.OnEnable () protected virtual
On enable, add all callbacks.
Reimplemented in Meta.Voice.Samples.TTSVoices.TTSSpeakerEffectSelect, Meta.Voice.Samples.TTSVoices.TTSSpeakerStatusLabel, and Meta.Voice.Samples.TTSVoices.TTSSpeakerVoiceSelect.
Definition at line 40 of file TTSSpeakerObserver.cs.
        {
            if (_speaker == null)
            {
                return;
            }
            _speaker.Events.OnPlaybackQueueBegin.AddListener(OnPlaybackQueueBegin);
            _speaker.Events.OnPlaybackQueueComplete.AddListener(OnPlaybackQueueComplete);
            _speaker.Events.OnLoadBegin.AddListener(OnLoadBegin);
            _speaker.Events.OnLoadAbort.AddListener(OnLoadAbort);
            _speaker.Events.OnLoadFailed.AddListener(OnLoadFailed);
            _speaker.Events.OnLoadSuccess.AddListener(OnLoadSuccess);
            _speaker.Events.OnPlaybackReady.AddListener(OnPlaybackReady);
            _speaker.Events.OnPlaybackStart.AddListener(OnPlaybackStart);
            _speaker.Events.OnPlaybackCancelled.AddListener(OnPlaybackCancelled);
            _speaker.Events.OnPlaybackComplete.AddListener(OnPlaybackComplete);
        }
References Meta.WitAi.TTS.Utilities.TTSSpeakerClipEvents.OnLoadAbort, Meta.Voice.Samples.TTSVoices.TTSSpeakerObserver.OnLoadAbort(), Meta.WitAi.TTS.Utilities.TTSSpeakerClipEvents.OnLoadBegin, Meta.Voice.Samples.TTSVoices.TTSSpeakerObserver.OnLoadBegin(), Meta.WitAi.TTS.Utilities.TTSSpeakerClipEvents.OnLoadFailed, Meta.Voice.Samples.TTSVoices.TTSSpeakerObserver.OnLoadFailed(), Meta.WitAi.TTS.Utilities.TTSSpeakerClipEvents.OnLoadSuccess, Meta.Voice.Samples.TTSVoices.TTSSpeakerObserver.OnLoadSuccess(), Meta.WitAi.TTS.Utilities.TTSSpeakerClipEvents.OnPlaybackCancelled, Meta.Voice.Samples.TTSVoices.TTSSpeakerObserver.OnPlaybackCancelled(), Meta.WitAi.TTS.Utilities.TTSSpeakerClipEvents.OnPlaybackComplete, Meta.Voice.Samples.TTSVoices.TTSSpeakerObserver.OnPlaybackComplete(), Meta.Voice.Samples.TTSVoices.TTSSpeakerObserver.OnPlaybackQueueBegin(), Meta.Voice.Samples.TTSVoices.TTSSpeakerObserver.OnPlaybackQueueComplete(), Meta.WitAi.TTS.Utilities.TTSSpeakerClipEvents.OnPlaybackReady, Meta.Voice.Samples.TTSVoices.TTSSpeakerObserver.OnPlaybackReady(), Meta.WitAi.TTS.Utilities.TTSSpeakerClipEvents.OnPlaybackStart, and Meta.Voice.Samples.TTSVoices.TTSSpeakerObserver.OnPlaybackStart().
OnLoadAbort()
virtual void Meta.Voice.Samples.TTSVoices.TTSSpeakerObserver.OnLoadAbort (TTSSpeaker speaker, TTSClipData clipData) protected virtual
Callback for load cancelation.
Reimplemented in Meta.Voice.Samples.TTSVoices.TTSSpeakerStatusLabel.
Definition at line 104 of file TTSSpeakerObserver.cs.
        {
        }
OnLoadBegin()
virtual void Meta.Voice.Samples.TTSVoices.TTSSpeakerObserver.OnLoadBegin (TTSSpeaker speaker, TTSClipData clipData) protected virtual
Callback for load begin.
Reimplemented in Meta.Voice.Samples.TTSVoices.TTSSpeakerStatusLabel.
Definition at line 97 of file TTSSpeakerObserver.cs.
        {
        }
OnLoadFailed()
virtual void Meta.Voice.Samples.TTSVoices.TTSSpeakerObserver.OnLoadFailed (TTSSpeaker speaker, TTSClipData clipData, string error) protected virtual
Callback for load error.
Reimplemented in Meta.Voice.Samples.TTSVoices.TTSSpeakerStatusLabel.
Definition at line 111 of file TTSSpeakerObserver.cs.
        {
        }
OnLoadSuccess()
virtual void Meta.Voice.Samples.TTSVoices.TTSSpeakerObserver.OnLoadSuccess (TTSSpeaker speaker, TTSClipData clipData) protected virtual
Callback for load success.
Reimplemented in Meta.Voice.Samples.TTSVoices.TTSSpeakerStatusLabel.
Definition at line 118 of file TTSSpeakerObserver.cs.
        {
        }
OnPlaybackCancelled()
virtual void Meta.Voice.Samples.TTSVoices.TTSSpeakerObserver.OnPlaybackCancelled (TTSSpeaker speaker, TTSClipData clipData, string reason) protected virtual
Callback for playback for a clip has been canceled.
Reimplemented in Meta.Voice.Samples.TTSVoices.TTSSpeakerStatusLabel.
Definition at line 140 of file TTSSpeakerObserver.cs.
        {
        }
OnPlaybackComplete()
virtual void Meta.Voice.Samples.TTSVoices.TTSSpeakerObserver.OnPlaybackComplete (TTSSpeaker speaker, TTSClipData clipData) protected virtual
Callback for playback completion.
Reimplemented in Meta.Voice.Samples.TTSVoices.TTSSpeakerStatusLabel.
Definition at line 147 of file TTSSpeakerObserver.cs.
        {
        }
OnPlaybackQueueBegin()
virtual void Meta.Voice.Samples.TTSVoices.TTSSpeakerObserver.OnPlaybackQueueBegin () protected virtual
Callback for queue begin.
Definition at line 82 of file TTSSpeakerObserver.cs.
        {
        }
OnPlaybackQueueComplete()
virtual void Meta.Voice.Samples.TTSVoices.TTSSpeakerObserver.OnPlaybackQueueComplete () protected virtual
Callback for queue completion.
Definition at line 89 of file TTSSpeakerObserver.cs.
        {
        }
OnPlaybackReady()
virtual void Meta.Voice.Samples.TTSVoices.TTSSpeakerObserver.OnPlaybackReady (TTSSpeaker speaker, TTSClipData clipData) protected virtual
Callback for playback is ready for a clip.
Reimplemented in Meta.Voice.Samples.TTSVoices.TTSSpeakerStatusLabel.
Definition at line 126 of file TTSSpeakerObserver.cs.
        {
        }
OnPlaybackStart()
virtual void Meta.Voice.Samples.TTSVoices.TTSSpeakerObserver.OnPlaybackStart (TTSSpeaker speaker, TTSClipData clipData) protected virtual
Callback for playback for a clip has begun.
Reimplemented in Meta.Voice.Samples.TTSVoices.TTSSpeakerStatusLabel.
Definition at line 133 of file TTSSpeakerObserver.cs.
        {
        }
Member Data Documentation
_speaker
TTSSpeaker Meta.Voice.Samples.TTSVoices.TTSSpeakerObserver._speaker private
Definition at line 23 of file TTSSpeakerObserver.cs.
Property Documentation
Speaker
TTSSpeaker Meta.Voice.Samples.TTSVoices.TTSSpeakerObserver.Speaker get
Definition at line 24 of file TTSSpeakerObserver.cs.
The documentation for this class was generated from the following file:
Assets/Oculus/Voice/Samples/TTSVoices/Scripts/TTSSpeakerObserver.cs